#!/usr/bin/env python3
"""Complete i18n overrides and round-2 patches for mkofman.com translations."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from i18n_constants import LANGS, T

ROOT = Path(__file__).resolve().parent
DATA_PATH = ROOT / "i18n_overrides_data.json"
ROUND2_JSON_PATH = ROOT / "i18n_round2_translations.json"
TRANSLATIONS_PATH = ROOT.parent / "js" / "translations.js"
GAPS_PATH = Path("/tmp/i18n_gaps.json")

# Flat key -> {lang: translation} for all 369 gap keys (generated by fill_all_translations.py)
if DATA_PATH.exists():
    OVERRIDES: dict[str, dict[str, str]] = json.loads(DATA_PATH.read_text(encoding="utf-8"))
else:
    OVERRIDES = {}


def _load_json_obj(path: Path) -> dict[str, Any]:
    raw = path.read_text(encoding="utf-8")
    start = raw.find("{")
    end = raw.rfind("}")
    return json.loads(raw[start : end + 1])


def _flatten(obj: Any, prefix: str = "") -> dict[str, str]:
    out: dict[str, str] = {}
    if isinstance(obj, dict):
        for key, val in obj.items():
            path = f"{prefix}.{key}" if prefix else key
            out.update(_flatten(val, path))
    elif isinstance(obj, str):
        out[prefix] = obj
    return out


def _gap_paths() -> set[str]:
    if not GAPS_PATH.exists():
        return set()
    gaps = json.loads(GAPS_PATH.read_text(encoding="utf-8"))
    return {f"{sec}.{key}" for sec, keys in gaps.items() for key in keys}


# Round-2: keys in translations.js not covered by i18n_gaps.json
ROUND2: dict[str, dict[str, str]] = {
    "about.secTechTitle": T(
        "Tecnología e infraestructura",
        "Technologie & Infrastruktur",
        "Technologie & infrastructure",
        "Технологии и инфраструктура",
        "Технології та інфраструктура",
        "技术与基础设施",
        "التكنولوجيا والبنية التحتية",
        "טכנולוגיה ותשתיות",
    ),
    "about.principlesEyebrow": T(
        "Principios operativos",
        "Operating Principles",
        "Principes opérationnels",
        "Операционные принципы",
        "Операційні принципи",
        "运营原则",
        "مبادئ تشغيلية",
        "עקרונות תפעול",
    ),
    "about.principlesTitle": T(
        "Cómo lidero",
        "Wie ich führe",
        "Comment je dirige",
        "Как я руковожу",
        "Як я керую",
        "我如何领导",
        "كيف أقود",
        "איך אני מנהיג",
    ),
    "about.p1title": T(
        "Comprender el sistema",
        "Das System verstehen",
        "Comprendre le système",
        "Понять систему",
        "Зрозуміти систему",
        "理解系统",
        "فهم النظام",
        "להבין את המערכת",
    ),
    "about.p1text": T(
        "Antes de cambiar una organización, comprenda sus incentivos, arquitectura, restricciones y fuentes de confianza.",
        "Bevor man eine Organisation verändert, deren Anreize, Architektur, Einschränkungen und Vertrauensquellen verstehen.",
        "Avant de changer une organisation, comprendre ses incitations, son architecture, ses contraintes et ses sources de confiance.",
        "Прежде чем менять организацию, нужно понять её стимулы, архитектуру, ограничения и источники доверия.",
        "Перш ніж змінювати організацію, потрібно зрозуміти її стимули, архітектуру, обмеження та джерела довіри.",
        "在改变组织之前，理解其激励、架构、约束和信任来源。",
        "قبل تغيير منظمة، افهم حوافزها وهندستها وقيودها ومصادر الثقة.",
        "לפני שינוי ארגון, להבין את התמריצים, הארכיטקטורה, האילוצים ומקורות האמון.",
    ),
    "about.p2title": T(
        "Hacer explícita la responsabilidad",
        "Verantwortung explizit machen",
        "Rendre la responsabilité explicite",
        "Сделать ответственность явной",
        "Зробити відповідальність явною",
        "使问责明确",
        "جعل المساءلة صريحة",
        "להפוך אחריות לברורה",
    ),
    "about.p2text": T(
        "La propiedad clara y los resultados medibles convierten la estrategia de material de presentación en realidad operativa.",
        "Klare Ownership und messbare Ergebnisse verwandeln Strategie von Präsentationsmaterial in Operating-Realität.",
        "Une propriété claire et des résultats mesurables transforment la stratégie de support de présentation en réalité opérationnelle.",
        "Ясная ответственность и измеримые результаты превращают стратегию из презентации в операционную реальность.",
        "Чітка відповідальність і вимірювані результати перетворюють стратегію з презентації на операційну реальність.",
        "明确的所有权和可衡量结果将战略从演示材料变为运营现实。",
        "الملكية الواضحة والنتائج القابلة للقياس تحوّل الاستراتيجية من عرض إلى واقع تشغيلي.",
        "בעלות ברורה ותוצאות מדידות הופכות אסטרטגיה מחומר מצגת למציאות תפעולית.",
    ),
    "about.p3title": T(
        "Dejar instituciones más fuertes",
        "Stärkere Institutionen hinterlassen",
        "Laisser des institutions plus fortes",
        "Оставлять более сильные institution",
        "Залишати сильніші institution",
        "留下更强的机构",
        "ترك مؤسسات أقوى",
        "להשאיר מוסדות חזקים יותר",
    ),
    "about.p3text": T(
        "El liderazgo debe multiplicar la capacidad desarrollando personas, mejorando decisiones y construyendo sistemas que perduren.",
        "Führung soll Fähigkeit vervielfachen, indem Menschen entwickelt, Entscheidungen verbessert und Systeme gebaut werden, die Bestand haben.",
        "Le leadership doit multiplier la capacité en développant les personnes, en améliorant les décisions et en construisant des systèmes durables.",
        "Лидерство должно умножать способности, развивая людей, улучшая решения и строя системы, которые переживают смену лидеров.",
        "Лідерство має примножувати spromожності, розвиваючи людей, покращуючи рішення та будуючи системи, які переживають зміну лідерів.",
        "领导力应通过培养人才、改善决策和构建持久系统来增强能力。",
        "يجب أن تضاعف القيادة القدرة بتطوير الأفراد وتحسين القرارات وبناء أنظمة تدوم.",
        "מנהיגות צריכה להכפיל יכולת על ידי פיתוח אנשים, שיפור החלטות ובניית מערכות שנשארות.",
    ),
}
ROUND2["about.p3title"]["ru"] = "Оставлять более сильные institution"
ROUND2["about.p3title"]["uk"] = "Залишати сильніші institution"
ROUND2["about.p3text"]["uk"] = "Лідerstvo має примножувати spromожності, розвиваючи людей, покращуючи rішення та будуючи системи, які переживають зміну лідerів."


def discover_round2() -> dict[str, dict[str, str]]:
    """Find translations.js keys not in gaps that are still English-identical."""
    if not TRANSLATIONS_PATH.exists():
        return dict(ROUND2)
    translations = _load_json_obj(TRANSLATIONS_PATH)
    en_flat = _flatten(translations.get("en", {}))
    gap_paths = _gap_paths()
    discovered: dict[str, dict[str, str]] = dict(ROUND2)
    for path, en_val in en_flat.items():
        if path in gap_paths or path in discovered:
            continue
        needs = False
        for lang in LANGS:
            lang_val = _flatten(translations.get(lang, {})).get(path, "")
            if lang_val == en_val:
                needs = True
                break
        if needs and path in OVERRIDES:
            discovered[path] = dict(OVERRIDES[path])
    return discovered


def write_round2_json(path: Path | None = None) -> Path:
    out = path or ROUND2_JSON_PATH
    data = discover_round2()
    out.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return out


if __name__ == "__main__":
    write_round2_json()
    print(f"Wrote {ROUND2_JSON_PATH} — {len(discover_round2())} round-2 keys")
