LANG_PATCHES = {
    "es": {
        "ui": {
            "sending": "Enviando…",
            "formError": "No se pudo enviar. Por favor, escriba directamente por correo electrónico.",
        },
        "nav": {
            "speaking": "Conferencias",
            "caseStudies": "Casos de estudio",
            "mediaKit": "Kit de prensa",
            "groupMain": "Principal",
            "groupServices": "Servicios",
            "groupWork": "Trabajo",
        },
        "cta": {
            "eyebrow": "Trabajemos juntos",
            "title": "Solicitar asesoría o una conferencia",
            "lead": "Para funciones de asesoría, puestos en juntas directivas, conferencias y alianzas estratégicas.",
            "button": "Póngase en contacto",
        },
        "meta": {
            "speaking": {
                "title": "Conferencias — Michael Kofman",
                "description": "Invite a Michael Kofman a hablar sobre liderazgo ejecutivo, estrategia tecnológica, salud digital y gobierno corporativo.",
            },
            "caseStudies": {
                "title": "Casos de estudio — Michael Kofman",
                "description": "Casos de estudio de la trayectoria de Michael Kofman: 9 Net Avenue Inc. y Digital Invest Inc.",
            },
            "mediaKit": {
                "title": "Kit de prensa — Michael Kofman",
                "description": "Biografías oficiales, fotografías e información de contacto para prensa y organizadores de eventos.",
            },
            "article1": {
                "title": "De la ingeniería a la infraestructura global — Michael Kofman",
                "description": "Michael Kofman sobre su trayectoria desde la ingeniería satelital hasta la fundación de empresas globales de infraestructura de datos.",
            },
            "article2": {
                "title": "Medicina de precisión y tecnología — Michael Kofman",
                "description": "Michael Kofman sobre la integración de las ciencias de la vida con IA, ML y tecnologías de ADN en la medicina moderna.",
            },
        },
        "speaking": {
            "eyebrow": "Conferencias",
            "title": "Invite a Michael Kofman a su evento",
            "lead": "Disponible para conferencias sobre liderazgo ejecutivo, estrategia tecnológica, salud digital, infraestructura de datos y gobierno corporativo.",
            "topicsEyebrow": "Temas de conferencia",
            "topicsTitle": "Áreas de experiencia",
            "topicsLead": "Los temas se basan en décadas de experiencia fundando y dirigiendo empresas en Estados Unidos y Europa.",
            "processEyebrow": "Cómo invitar",
            "processTitle": "Proceso de contratación",
            "process1title": "Envíe una solicitud",
            "process1desc": "Use el formulario de contacto o escriba a mkofman@mkofman.com con los detalles del evento, la audiencia y los temas preferidos.",
            "process2title": "Confirme el alcance",
            "process2desc": "Defina el formato (ponencia principal, panel, sesión de junta o mesa redonda ejecutiva) y la logística.",
            "process3title": "Genere impacto",
            "process3desc": "Las presentaciones se basan en resultados reales de iniciativas en almacenamiento de datos, govtech y medicina de precisión.",
            "cta": "Solicitar una conferencia",
        },
        "caseStudies": {
            "eyebrow": "Casos de estudio",
            "title": "Construyendo empresas que escalan",
            "lead": "Resultados seleccionados de la fundación y dirección de empresas en infraestructura de datos y salud digital.",
            "cs1eyebrow": "Infraestructura de datos · 1996 — 2000",
            "cs1title": "9 Net Avenue Inc.",
            "cs1challenge": "Desafío",
            "cs1challengeText": "Construir y escalar una empresa de almacenamiento de datos en un mercado tecnológico en rápida consolidación.",
            "cs1action": "Enfoque",
            "cs1actionText": "Fundé 9 Net Avenue Inc. en 1996. La empresa se convirtió rápidamente en una de las mayores compañías de almacenamiento de datos del mundo.",
            "cs1result": "Resultado",
            "cs1resultText": "En 2000 fue adquirida por Concentric Networks (NASDAQ: CNTX) y luego por XO Communications (NASDAQ: XOXO), alcanzando una capitalización máxima de mercado de 19.500 millones de dólares. Tras la adquisición, adquirí amplia experiencia con empresas cotizadas, consejos de administración y decisiones estratégicas de alto nivel.",
            "cs2eyebrow": "Salud digital · 2021 — Presente",
            "cs2title": "Digital Invest Inc.",
            "cs2challenge": "Desafío",
            "cs2challengeText": "Transformar enfoques médicos obsoletos mediante ciencia, tecnologías de ADN, IA y ML a través de una nueva plataforma bio-matemática.",
            "cs2action": "Enfoque",
            "cs2actionText": "Fundé y escalé Digital Invest Inc. desde su inicio hasta una salida a bolsa exitosa. Dirigí todo el proceso de oferta pública: estructuración legal, cumplimiento financiero, roadshows con inversores y coordinación con la SEC. También dirigí el diseño, la construcción y la operación de múltiples centros de datos en EE. UU. y Europa.",
            "cs2result": "Resultado",
            "cs2resultText": "Logramos un crecimiento financiero sostenido y posicionamos a la empresa entre las 10 principales compañías de medicina de precisión de EE. UU. (2023). Digital Invest integra proyectos innovadores como Human Digital Model, BioMath Life y Aero-Ground Robotics Operations Network.",
        },
        "mediaKit": {
            "eyebrow": "Prensa y eventos",
            "title": "Kit de prensa",
            "lead": "Biografías oficiales, material visual y datos de contacto para prensa, conferencias y consultas de juntas directivas.",
            "bioEyebrow": "Biografías",
            "bioTitle": "Biografías oficiales",
            "bioShortLabel": "50 palabras",
            "bioShort": "Michael Kofman es CEO de Digital Invest Inc. y miembro de consejos, asesor y fundador de empresas de tecnología y salud digital en EE. UU. y Europa.",
            "bioMediumLabel": "150 palabras",
            "bioMedium": "Michael Kofman es CEO de Digital Invest Inc. y forma parte de su consejo de administración. Visionario tecnológico, es reconocido por su enfoque dinámico para comprender las necesidades cambiantes del mercado actual. Como emprendedor, miembro de consejos y asesor de empresas públicas y privadas, ha fundado con éxito varias compañías en Estados Unidos y Europa. Su experiencia abarca liderazgo ejecutivo, análisis estratégico de tecnologías y mercados emergentes, seguridad y privacidad de la información, investigación, ciencia y desarrollo, administración e inversión.",
            "bioLongLabel": "500 palabras",
            "bioLong": "Michael Kofman es CEO de Digital Invest Inc. y forma parte de su consejo de administración. Visionario tecnológico, es reconocido por su enfoque dinámico para comprender las necesidades cambiantes del mercado actual. Su experiencia abarca liderazgo ejecutivo, análisis estratégico de tecnologías y mercados emergentes, seguridad y privacidad de la información, investigación, ciencia y desarrollo, administración e inversión. Como emprendedor, consejero y asesor de empresas públicas y privadas, Michael Kofman ha fundado con éxito varias compañías en Estados Unidos y Europa. Fundó 9 Net Avenue Inc., adquirida con una capitalización máxima de mercado de 19.500 millones de dólares, y lidera Digital Invest Inc. en almacenamiento de datos e innovación tecnológica avanzada. Ha dirigido estrategia tecnológica para programas gubernamentales y de defensa, fundó XIBI Group Inc. y DataPeer Inc. en el ámbito del almacenamiento de datos, y desempeñó un papel clave en Biotechnology Group Inc. Colaboró con Harvard Medical School y Stanford Biomath en reportes genéticos. Es autor de artículos técnicos sobre sistemas satelitales y ópticos; su patente de HDTV satelital digital fue adquirida por Sony. Formación: Doctor en Ciencias Técnicas (2009), Ph.D. en Tecnología de la Información (2004), Universidad Estatal Marítima Técnica de Ucrania.",
            "photosEyebrow": "Fotografía",
            "photosTitle": "Imágenes aprobadas",
            "photosLead": "Retratos en alta resolución disponibles previa solicitud en mkofman@mkofman.com.",
            "contactEyebrow": "Contacto de prensa",
            "contactTitle": "Consultas de medios",
            "contactLead": "Para entrevistas, invitaciones a conferencias y solicitudes de prensa.",
        },
        "articles": {
            "backLink": "← Volver a Insights",
            "article1date": "Perspectiva ejecutiva",
            "article1title": "De la ingeniería a la infraestructura global de datos",
            "article1p1": "Mi carrera comenzó en la planta de construcción naval de Nikolaev, en Ucrania, desarrollando sistemas transceptores satelitales para transmitir información clasificada a buques militares. Fui reconocido como ingeniero electrónico del más alto nivel: la 6.ª categoría en una planta de 93.000 empleados.",
            "article1p2": "Entre 1989 y 1994 fundé y dirigí Astra Corp, uno de los mayores fabricantes europeos de sistemas satelitales transceptores digitales. De 1994 a 1996, como CEO de Elitan United Inc., ayudé a escalar la empresa de nueve a más de 4.000 empleados en todo el mundo.",
            "article1p3": "En 1996 fundé 9 Net Avenue Inc., que rápidamente se convirtió en una de las mayores compañías de almacenamiento de datos del mundo. En 2000 fue adquirida por Concentric Networks (NASDAQ: CNTX) y XO Communications (NASDAQ: XOXO), alcanzando una capitalización máxima de mercado de 19.500 millones de dólares.",
            "article1p4": "De 2001 a 2019 dirigí la estrategia tecnológica para programas gubernamentales, de defensa y de empresas estatales, liderando iniciativas de gran escala en big data, infraestructura segura y centros de datos de alto rendimiento en Estados Unidos y Europa.",
            "article2date": "Salud digital",
            "article2title": "Medicina de precisión y convergencia entre ciencia y tecnología",
            "article2p1": "Creo firmemente en el potencial de combinar las ciencias de la vida con los últimos avances tecnológicos. En Biotechnology Group Inc. (2008-2014), nos enfocamos en pruebas y análisis de ADN, automatización de procesos para crear perfiles genéticos e investigación genética humana integral.",
            "article2p2": "Bajo mi liderazgo, se iniciaron proyectos exitosos de pruebas genéticas en Ucrania, Rusia y los países bálticos. En colaboración con Harvard Medical School y Stanford Biomath, desempeñé un papel clave en el desarrollo de reportes genéticos fáciles de comprender para médicos y pacientes.",
            "article2p3": "Con Digital Invest Inc., fundada en 2021, nos dedicamos al ámbito bio-matemático, transformando enfoques médicos obsoletos mediante ciencia, tecnologías de ADN, IA y ML. La empresa se escaló desde su inicio hasta una salida a bolsa exitosa y fue reconocida entre las 10 mejores compañías de EE. UU. en medicina de precisión y salud digital en 2023.",
            "article2p4": "Digital Invest integra diversos proyectos innovadores, incluidos Human Digital Model, BioMath Life y Aero-Ground Robotics Operations Network, cada uno impulsando la integración de la ciencia de datos y las ciencias de la vida.",
        },
        "home": {
            "heroSub": "CEO, asesor de juntas directivas y estratega tecnológico para empresas públicas y privadas en tecnología, almacenamiento de datos y salud digital.",
            "featuredEyebrow": "Como aparece en",
            "primaryCta": "Solicitar asesoría",
            "secondaryCta": "Ver casos de estudio",
            "caseStudiesEyebrow": "Resultados comprobados",
            "caseStudiesTitle": "Casos de estudio",
            "caseStudiesLead": "Fundación, escalamiento y liderazgo de empresas desde su inicio hasta adquisiciones y salidas a bolsa.",
            "caseStudiesLink": "Ver todos los casos de estudio →",
            "cs1title": "9 Net Avenue Inc.",
            "cs1desc": "Construyó una de las mayores compañías de almacenamiento de datos del mundo, adquirida con una capitalización máxima de mercado de 19.500 millones de dólares.",
            "cs2title": "Digital Invest Inc.",
            "cs2desc": "Fundada y escalada desde su inicio hasta la salida a bolsa: Top 10 de compañías de medicina de precisión en EE. UU., 2023.",
        },
        "recognition": {
            "moreLink": "Ver patentes, publicaciones y notas de prensa en Insights →",
        },
        "insights": {
            "articlesEyebrow": "Perspectivas",
            "articlesTitle": "Perspectivas ejecutivas",
        },
    },
    "de": {
        "ui": {
            "sending": "Wird gesendet…",
            "formError": "Senden fehlgeschlagen. Bitte senden Sie direkt eine E-Mail.",
        },
        "nav": {
            "speaking": "Vorträge",
            "caseStudies": "Fallstudien",
            "mediaKit": "Pressemappe",
            "groupMain": "Hauptmenü",
            "groupServices": "Leistungen",
            "groupWork": "Referenzen",
        },
        "cta": {
            "eyebrow": "Zusammenarbeiten",
            "title": "Beratung oder Vortrag anfragen",
            "lead": "Für Beratungsmandate, Board-Positionen, Vorträge und strategische Partnerschaften.",
            "button": "Kontakt aufnehmen",
        },
        "meta": {
            "speaking": {
                "title": "Vorträge — Michael Kofman",
                "description": "Laden Sie Michael Kofman als Sprecher zu Themen wie Executive Leadership, Technologiestrategie, Digital Health und Corporate Governance ein.",
            },
            "caseStudies": {
                "title": "Fallstudien — Michael Kofman",
                "description": "Fallstudien aus Michael Kofmans Laufbahn: 9 Net Avenue Inc. und Digital Invest Inc.",
            },
            "mediaKit": {
                "title": "Pressemappe — Michael Kofman",
                "description": "Offizielle Biografien, Fotos und Kontaktdaten für Presse und Veranstalter.",
            },
            "article1": {
                "title": "Von der Ingenieurtechnik zur globalen Infrastruktur — Michael Kofman",
                "description": "Michael Kofman über seinen Weg von der Satellitentechnik zur Gründung globaler Dateninfrastruktur-Unternehmen.",
            },
            "article2": {
                "title": "Präzisionsmedizin und Technologie — Michael Kofman",
                "description": "Michael Kofman über die Verbindung von Life Sciences mit KI, ML und DNA-Technologien in der modernen Medizin.",
            },
        },
        "speaking": {
            "eyebrow": "Vortragsanfragen",
            "title": "Michael Kofman als Sprecher einladen",
            "lead": "Verfügbar für Vorträge zu Executive Leadership, Technologiestrategie, Digital Health, Dateninfrastruktur und Corporate Governance.",
            "topicsEyebrow": "Vortragsthemen",
            "topicsTitle": "Expertisebereiche",
            "topicsLead": "Die Themen basieren auf jahrzehntelanger Erfahrung beim Aufbau und Führen von Unternehmen in den USA und Europa.",
            "processEyebrow": "So buchen Sie",
            "processTitle": "Buchungsprozess",
            "process1title": "Anfrage senden",
            "process1desc": "Nutzen Sie das Kontaktformular oder schreiben Sie an mkofman@mkofman.com mit Angaben zu Veranstaltung, Publikum und Wunschthemen.",
            "process2title": "Umfang abstimmen",
            "process2desc": "Format (Keynote, Panel, Board-Session oder Executive Roundtable) und Logistik abstimmen.",
            "process3title": "Mehrwert liefern",
            "process3desc": "Die Vorträge basieren auf realen Ergebnissen aus Projekten in Data Storage, GovTech und Präzisionsmedizin.",
            "cta": "Vortragsanfrage senden",
        },
        "caseStudies": {
            "eyebrow": "Fallstudien",
            "title": "Unternehmen auf Skalierungskurs",
            "lead": "Ausgewählte Ergebnisse aus der Gründung und Führung von Unternehmen in Dateninfrastruktur und Digital Health.",
            "cs1eyebrow": "Dateninfrastruktur · 1996 — 2000",
            "cs1title": "9 Net Avenue Inc.",
            "cs1challenge": "Herausforderung",
            "cs1challengeText": "Ein Data-Storage-Unternehmen in einem sich schnell konsolidierenden Technologiemarkt aufbauen und skalieren.",
            "cs1action": "Ansatz",
            "cs1actionText": "Ich gründete 9 Net Avenue Inc. im Jahr 1996. Das Unternehmen wurde schnell zu einem der weltweit größten Data-Storage-Unternehmen.",
            "cs1result": "Ergebnis",
            "cs1resultText": "Im Jahr 2000 erfolgte die Übernahme durch Concentric Networks (NASDAQ: CNTX), danach XO Communications (NASDAQ: XOXO), mit einem Spitzenmarktwert von 19,5 Milliarden US-Dollar. Nach der Übernahme sammelte ich umfassende Erfahrung in börsennotierten Unternehmen, in Aufsichtsgremien und bei strategischen Entscheidungen auf höchster Führungsebene.",
            "cs2eyebrow": "Digital Health · 2021 — Heute",
            "cs2title": "Digital Invest Inc.",
            "cs2challenge": "Herausforderung",
            "cs2challengeText": "Veraltete medizinische Ansätze durch Wissenschaft, DNA-Technologien, KI und ML auf einer neuen bio-mathematischen Plattform transformieren.",
            "cs2action": "Ansatz",
            "cs2actionText": "Ich gründete und skalierte Digital Invest Inc. vom Start bis zu einem erfolgreichen IPO. Ich leitete den gesamten Börsengangsprozess: rechtliche Strukturierung, finanzielle Compliance, Investoren-Roadshows und SEC-Koordination. Zudem verantwortete ich Planung, Bau und Betrieb mehrerer Rechenzentren in den USA und Europa.",
            "cs2result": "Ergebnis",
            "cs2resultText": "Stetiges finanzielles Wachstum positionierte das Unternehmen unter den Top 10 Präzisionsmedizin-Unternehmen in den USA (2023). Digital Invest umfasst innovative Projekte wie Human Digital Model, BioMath Life und Aero-Ground Robotics Operations Network.",
        },
        "mediaKit": {
            "eyebrow": "Presse und Events",
            "title": "Pressemappe",
            "lead": "Offizielle Biografien, Bildmaterial und Kontaktdaten für Presse, Konferenzen und Board-Anfragen.",
            "bioEyebrow": "Biografien",
            "bioTitle": "Offizielle Biografien",
            "bioShortLabel": "50 Wörter",
            "bioShort": "Michael Kofman ist CEO von Digital Invest Inc. sowie Board-Mitglied, Berater und Gründer von Unternehmen in Technologie und Digital Health in den USA und Europa.",
            "bioMediumLabel": "150 Wörter",
            "bioMedium": "Michael Kofman ist CEO von Digital Invest Inc. und Mitglied des Board of Directors. Als Technologie-Visionär ist er für seinen dynamischen Ansatz bekannt, die sich ständig wandelnden Anforderungen des heutigen komplexen Marktes zu verstehen. Als Unternehmer, Board-Mitglied und Berater öffentlicher und privater Unternehmen hat er in den USA und Europa mehrere Unternehmen erfolgreich aufgebaut. Seine Expertise umfasst Executive Leadership, strategische Analyse neuer Technologien und Märkte, Informationssicherheit und Datenschutz, Forschung, Wissenschaft und Entwicklung, Administration und Investment.",
            "bioLongLabel": "500 Wörter",
            "bioLong": "Michael Kofman ist CEO von Digital Invest Inc. und Mitglied des Board of Directors. Als Technologie-Visionär ist er für seinen dynamischen Ansatz bekannt, die sich wandelnden Anforderungen des heutigen komplexen Marktes zu verstehen. Seine Expertise umfasst Executive Leadership, strategische Analyse neuer Technologien und Märkte, Informationssicherheit und Datenschutz, Forschung, Wissenschaft und Entwicklung, Administration und Investment. Als Unternehmer, Board-Mitglied und Berater öffentlicher wie privater Unternehmen hat Michael Kofman in den USA und Europa mehrere Unternehmen erfolgreich gegründet. Er gründete 9 Net Avenue Inc., das bei einem Spitzenmarktwert von 19,5 Milliarden US-Dollar übernommen wurde, und leitet Digital Invest Inc. in den Bereichen Data Storage und fortschrittliche Technologieinnovation. Er verantwortete Technologiestrategien für Regierungs- und Verteidigungsprogramme, gründete XIBI Group Inc. und DataPeer Inc. im Data-Storage-Bereich und spielte eine bedeutende Rolle bei Biotechnology Group Inc. Er arbeitete mit Harvard Medical School und Stanford Biomath an genetischen Berichten zusammen. Er ist Autor technischer Facharbeiten zu Satelliten- und optischen Systemen; ein Patent für digitales Satelliten-HDTV wurde von Sony erworben. Ausbildung: Doktor der Technischen Wissenschaften (2009), Ph.D. in Informationstechnologie (2004), Ukrainische Staatliche Maritime Technische Universität.",
            "photosEyebrow": "Fotografie",
            "photosTitle": "Freigegebene Bilder",
            "photosLead": "Hochauflösende Porträts sind auf Anfrage unter mkofman@mkofman.com erhältlich.",
            "contactEyebrow": "Pressekontakt",
            "contactTitle": "Medienanfragen",
            "contactLead": "Für Interviews, Vortragseinladungen und Presseanfragen.",
        },
        "articles": {
            "backLink": "← Zurück zu Insights",
            "article1date": "Executive Perspective",
            "article1title": "Von der Ingenieurtechnik zur globalen Dateninfrastruktur",
            "article1p1": "Meine Karriere begann im Schiffbauwerk Nikolaev in der Ukraine, wo ich Satelliten-Transceiversysteme zur Übertragung klassifizierter Informationen an Kriegsschiffe entwickelte. Ich wurde als Elektronikingenieur höchster Stufe ausgezeichnet, der 6. Kategorie in einem Werk mit 93.000 Mitarbeitenden.",
            "article1p2": "Von 1989 bis 1994 gründete und leitete ich Astra Corp, einen der größten europäischen Hersteller digitaler Satelliten-Transceiversysteme. Von 1994 bis 1996 half ich als CEO von Elitan United Inc., das Unternehmen von neun auf über 4.000 Mitarbeitende weltweit zu skalieren.",
            "article1p3": "1996 gründete ich 9 Net Avenue Inc., das schnell zu einem der weltweit größten Data-Storage-Unternehmen wurde. Im Jahr 2000 wurde es von Concentric Networks (NASDAQ: CNTX) und XO Communications (NASDAQ: XOXO) übernommen und erreichte einen Spitzenmarktwert von 19,5 Milliarden US-Dollar.",
            "article1p4": "Von 2001 bis 2019 verantwortete ich die Technologiestrategie für Regierungs-, Verteidigungs- und Staatsunternehmensprogramme und leitete groß angelegte Initiativen in Big Data, sicherer Infrastruktur und Hochdurchsatz-Rechenzentren in den USA und Europa.",
            "article2date": "Digital Health",
            "article2title": "Präzisionsmedizin und die Konvergenz von Wissenschaft und Technologie",
            "article2p1": "Ich bin fest davon überzeugt, dass die Kombination von Life Sciences mit den neuesten technologischen Fortschritten enormes Potenzial bietet. Bei Biotechnology Group Inc. (2008-2014) konzentrierten wir uns auf DNA-Tests und -Analysen, Prozessautomatisierung zur Erstellung genetischer Profile und umfassende humangenetische Forschung.",
            "article2p2": "Unter meiner Leitung wurden erfolgreiche genetische Testprojekte in der Ukraine, in Russland und in den baltischen Staaten initiiert. In Zusammenarbeit mit Harvard Medical School und Stanford Biomath spielte ich eine entscheidende Rolle bei der Entwicklung leicht verständlicher genetischer Berichte für Ärzte und Patienten.",
            "article2p3": "Mit Digital Invest Inc., gegründet 2021, widmen wir uns dem bio-mathematischen Bereich und transformieren veraltete medizinische Ansätze mithilfe von Wissenschaft, DNA-Technologien, KI und ML. Das Unternehmen wurde vom Start bis zu einem erfolgreichen IPO skaliert und 2023 als eines der Top 10 Unternehmen der USA in Präzisionsmedizin und Digital Health ausgezeichnet.",
            "article2p4": "Digital Invest umfasst vielfältige innovative Projekte, darunter Human Digital Model, BioMath Life und Aero-Ground Robotics Operations Network, die jeweils die Integration von Data Science und Life Sciences vorantreiben.",
        },
        "home": {
            "heroSub": "CEO, Board-Berater und strategischer Technologe für öffentliche und private Unternehmen in Technologie, Data Storage und Digital Health.",
            "featuredEyebrow": "Bekannt aus",
            "primaryCta": "Beratung anfragen",
            "secondaryCta": "Fallstudien ansehen",
            "caseStudiesEyebrow": "Nachweisbare Ergebnisse",
            "caseStudiesTitle": "Fallstudien",
            "caseStudiesLead": "Unternehmen gründen, skalieren und führen - vom Start bis zu Übernahme und IPO.",
            "caseStudiesLink": "Alle Fallstudien anzeigen →",
            "cs1title": "9 Net Avenue Inc.",
            "cs1desc": "Aufbau eines der weltweit größten Data-Storage-Unternehmen, übernommen bei einem Spitzenmarktwert von 19,5 Milliarden US-Dollar.",
            "cs2title": "Digital Invest Inc.",
            "cs2desc": "Vom Start bis zum IPO aufgebaut und skaliert - Top-10-US-Unternehmen für Präzisionsmedizin, 2023.",
        },
        "recognition": {
            "moreLink": "Patente, Publikationen und Presseberichte auf Insights anzeigen →",
        },
        "insights": {
            "articlesEyebrow": "Perspektiven",
            "articlesTitle": "Executive-Perspektiven",
        },
    },
    "fr": {
        "ui": {
            "sending": "Envoi en cours…",
            "formError": "Envoi impossible. Merci d'envoyer un e-mail directement.",
        },
        "nav": {
            "speaking": "Interventions",
            "caseStudies": "Études de cas",
            "mediaKit": "Kit média",
            "groupMain": "Principal",
            "groupServices": "Services",
            "groupWork": "Réalisations",
        },
        "cta": {
            "eyebrow": "Collaborons",
            "title": "Demander un accompagnement ou une intervention",
            "lead": "Pour des rôles de conseil, des mandats d'administrateur, des interventions et des partenariats stratégiques.",
            "button": "Prendre contact",
        },
        "meta": {
            "speaking": {
                "title": "Interventions — Michael Kofman",
                "description": "Invitez Michael Kofman à intervenir sur le leadership exécutif, la stratégie technologique, la santé numérique et la gouvernance d'entreprise.",
            },
            "caseStudies": {
                "title": "Études de cas — Michael Kofman",
                "description": "Études de cas issues de la carrière de Michael Kofman : 9 Net Avenue Inc. et Digital Invest Inc.",
            },
            "mediaKit": {
                "title": "Kit média — Michael Kofman",
                "description": "Biographies officielles, photos et informations de contact pour la presse et les organisateurs d'événements.",
            },
            "article1": {
                "title": "De l'ingénierie à l'infrastructure mondiale — Michael Kofman",
                "description": "Michael Kofman revient sur son parcours, de l'ingénierie satellitaire à la création d'entreprises mondiales d'infrastructure de données.",
            },
            "article2": {
                "title": "Médecine de précision et technologie — Michael Kofman",
                "description": "Michael Kofman sur la convergence des sciences de la vie avec l'IA, le ML et les technologies ADN dans la médecine moderne.",
            },
        },
        "speaking": {
            "eyebrow": "Interventions",
            "title": "Inviter Michael Kofman à intervenir",
            "lead": "Disponible pour des interventions sur le leadership exécutif, la stratégie technologique, la santé numérique, l'infrastructure de données et la gouvernance d'entreprise.",
            "topicsEyebrow": "Thèmes d'intervention",
            "topicsTitle": "Domaines d'expertise",
            "topicsLead": "Les thèmes s'appuient sur des décennies d'expérience dans la création et la direction d'entreprises aux États-Unis et en Europe.",
            "processEyebrow": "Comment inviter",
            "processTitle": "Processus de réservation",
            "process1title": "Envoyer une demande",
            "process1desc": "Utilisez le formulaire de contact ou écrivez à mkofman@mkofman.com avec les détails de l'événement, le public et les thèmes souhaités.",
            "process2title": "Valider le périmètre",
            "process2desc": "Définissez le format (keynote, panel, session de conseil d'administration ou table ronde exécutive) et la logistique.",
            "process3title": "Créer de la valeur",
            "process3desc": "Les interventions s'appuient sur des résultats concrets obtenus dans le data storage, la govtech et la médecine de précision.",
            "cta": "Demander une intervention",
        },
        "caseStudies": {
            "eyebrow": "Études de cas",
            "title": "Construire des entreprises qui passent à l'échelle",
            "lead": "Résultats sélectionnés issus de la création et de la direction d'entreprises en infrastructure de données et santé numérique.",
            "cs1eyebrow": "Infrastructure de données · 1996 — 2000",
            "cs1title": "9 Net Avenue Inc.",
            "cs1challenge": "Défi",
            "cs1challengeText": "Créer et développer une entreprise de Data Storage dans un marché technologique en consolidation rapide.",
            "cs1action": "Approche",
            "cs1actionText": "J'ai fondé 9 Net Avenue Inc. en 1996. L'entreprise est rapidement devenue l'une des plus grandes sociétés de Data Storage au monde.",
            "cs1result": "Résultat",
            "cs1resultText": "En 2000, elle a été acquise par Concentric Networks (NASDAQ: CNTX), puis XO Communications (NASDAQ: XOXO), atteignant une capitalisation boursière maximale de 19,5 milliards de dollars. Après l'acquisition, j'ai acquis une solide expérience avec des entreprises cotées, la gouvernance de conseil et la prise de décisions stratégiques au plus haut niveau.",
            "cs2eyebrow": "Santé numérique · 2021 — Aujourd'hui",
            "cs2title": "Digital Invest Inc.",
            "cs2challenge": "Défi",
            "cs2challengeText": "Transformer des approches médicales obsolètes grâce à la science, aux technologies ADN, à l'IA et au ML via une nouvelle plateforme bio-mathématique.",
            "cs2action": "Approche",
            "cs2actionText": "J'ai fondé et développé Digital Invest Inc. de sa création à une introduction en bourse réussie. J'ai dirigé l'ensemble du processus d'IPO : structuration juridique, conformité financière, roadshows investisseurs et coordination avec la SEC. J'ai également piloté la conception, la construction et l'exploitation de plusieurs data centers aux États-Unis et en Europe.",
            "cs2result": "Résultat",
            "cs2resultText": "Nous avons atteint une croissance financière soutenue, positionnant l'entreprise parmi les 10 meilleures sociétés de médecine de précision aux États-Unis (2023). Digital Invest regroupe des projets innovants tels que Human Digital Model, BioMath Life et Aero-Ground Robotics Operations Network.",
        },
        "mediaKit": {
            "eyebrow": "Presse et événements",
            "title": "Kit média",
            "lead": "Biographies officielles, visuels et coordonnées pour la presse, les conférences et les demandes de conseil d'administration.",
            "bioEyebrow": "Biographies",
            "bioTitle": "Biographies officielles",
            "bioShortLabel": "50 mots",
            "bioShort": "Michael Kofman est CEO de Digital Invest Inc., administrateur, conseiller et fondateur d'entreprises technologiques et de santé numérique aux États-Unis et en Europe.",
            "bioMediumLabel": "150 mots",
            "bioMedium": "Michael Kofman est CEO de Digital Invest Inc. et siège à son Board of Directors. Visionnaire technologique, il est reconnu pour son approche dynamique des besoins en constante évolution des marchés complexes actuels. Entrepreneur, administrateur et conseiller auprès d'entreprises publiques et privées, il a fondé avec succès plusieurs sociétés aux États-Unis et en Europe. Son expertise couvre la direction exécutive, l'analyse stratégique des technologies et marchés émergents, la sécurité et la confidentialité de l'information, la recherche, la science et le développement, l'administration et l'investissement.",
            "bioLongLabel": "500 mots",
            "bioLong": "Michael Kofman est CEO de Digital Invest Inc. et siège à son Board of Directors. Visionnaire technologique, il est reconnu pour son approche dynamique des besoins en constante évolution des marchés complexes actuels. Son expertise couvre la direction exécutive, l'analyse stratégique des technologies et marchés émergents, la sécurité et la confidentialité de l'information, la recherche, la science et le développement, l'administration et l'investissement. Entrepreneur, administrateur et conseiller d'entreprises publiques et privées, Michael Kofman a fondé avec succès plusieurs sociétés aux États-Unis et en Europe. Il a fondé 9 Net Avenue Inc., acquise avec une valorisation boursière de 19,5 milliards de dollars, et dirige Digital Invest Inc. dans le Data Storage et l'innovation technologique avancée. Il a dirigé la stratégie technologique de programmes gouvernementaux et de défense, fondé XIBI Group Inc. et DataPeer Inc. dans le Data Storage, et joué un rôle majeur au sein de Biotechnology Group Inc. Il a collaboré avec Harvard Medical School et Stanford Biomath sur des rapports génétiques. Auteur d'articles techniques sur les systèmes satellitaires et optiques ; son brevet de TVHD satellite numérique a été acquis par Sony. Formation : Doctor of Technical Sciences (2009), Ph.D. in Information Technology (2004), Ukrainian State Marine Technical University.",
            "photosEyebrow": "Photographie",
            "photosTitle": "Images approuvées",
            "photosLead": "Portraits en haute résolution disponibles sur demande à mkofman@mkofman.com.",
            "contactEyebrow": "Contact presse",
            "contactTitle": "Demandes médias",
            "contactLead": "Pour les interviews, invitations à intervenir et demandes presse.",
        },
        "articles": {
            "backLink": "← Retour vers Insights",
            "article1date": "Perspective dirigeante",
            "article1title": "De l'ingénierie à l'infrastructure mondiale de données",
            "article1p1": "Ma carrière a commencé à l'usine navale de Nikolaev, en Ukraine, où je développais des systèmes transpondeurs satellitaires pour transmettre des informations classifiées aux navires militaires. J'ai été reconnu comme ingénieur en électronique de plus haut niveau, 6e catégorie, dans une usine de 93 000 employés.",
            "article1p2": "De 1989 à 1994, j'ai fondé et dirigé Astra Corp, l'un des plus grands fabricants européens de systèmes satellitaires transpondeurs numériques. De 1994 à 1996, en tant que CEO d'Elitan United Inc., j'ai contribué à faire passer l'entreprise de neuf à plus de 4 000 employés dans le monde.",
            "article1p3": "En 1996, j'ai fondé 9 Net Avenue Inc., rapidement devenue l'une des plus grandes entreprises mondiales de Data Storage. En 2000, elle a été acquise par Concentric Networks (NASDAQ: CNTX) et XO Communications (NASDAQ: XOXO), atteignant une capitalisation boursière maximale de 19,5 milliards de dollars.",
            "article1p4": "De 2001 à 2019, j'ai dirigé la stratégie technologique pour des programmes gouvernementaux, de défense et d'entreprises publiques, en menant de grandes initiatives dans le big data, l'infrastructure sécurisée et les data centers à haut débit aux États-Unis et en Europe.",
            "article2date": "Santé numérique",
            "article2title": "Médecine de précision et convergence de la science et de la technologie",
            "article2p1": "Je crois fermement au potentiel de la combinaison des sciences de la vie avec les dernières avancées technologiques. Chez Biotechnology Group Inc. (2008-2014), nous nous sommes concentrés sur les tests et analyses ADN, l'automatisation des processus de création de profils génétiques et la recherche génétique humaine complète.",
            "article2p2": "Sous ma direction, des projets réussis de tests génétiques ont été lancés en Ukraine, en Russie et dans les pays baltes. En collaboration avec Harvard Medical School et Stanford Biomath, j'ai joué un rôle clé dans le développement de rapports génétiques faciles à comprendre pour les médecins comme pour les patients.",
            "article2p3": "Avec Digital Invest Inc., fondée en 2021, nous nous consacrons au domaine bio-mathématique, transformant les approches médicales obsolètes grâce à la science, aux technologies ADN, à l'IA et au ML. L'entreprise a été développée de sa création jusqu'à une introduction en bourse réussie et reconnue parmi les 10 meilleures entreprises américaines de médecine de précision et de santé numérique en 2023.",
            "article2p4": "Digital Invest regroupe divers projets innovants, dont Human Digital Model, BioMath Life et Aero-Ground Robotics Operations Network, chacun faisant progresser l'intégration de la data science et des sciences de la vie.",
        },
        "home": {
            "heroSub": "CEO, conseiller de conseils d'administration et stratège technologique pour des entreprises publiques et privées en technologie, Data Storage et santé numérique.",
            "featuredEyebrow": "Vu dans",
            "primaryCta": "Demander un accompagnement",
            "secondaryCta": "Voir les études de cas",
            "caseStudiesEyebrow": "Résultats prouvés",
            "caseStudiesTitle": "Études de cas",
            "caseStudiesLead": "Créer, développer et diriger des entreprises de leur lancement jusqu'à l'acquisition et l'IPO.",
            "caseStudiesLink": "Voir toutes les études de cas →",
            "cs1title": "9 Net Avenue Inc.",
            "cs1desc": "A construit l'une des plus grandes sociétés mondiales de Data Storage, acquise avec une capitalisation boursière maximale de 19,5 milliards de dollars.",
            "cs2title": "Digital Invest Inc.",
            "cs2desc": "Fondée et développée de sa création jusqu'à l'IPO : Top 10 des entreprises américaines de médecine de précision en 2023.",
        },
        "recognition": {
            "moreLink": "Voir les brevets, publications et mentions presse dans Insights →",
        },
        "insights": {
            "articlesEyebrow": "Points de vue",
            "articlesTitle": "Perspectives dirigeantes",
        },
    },
    "uk": {
        "ui": {
            "sending": "Надсилання…",
            "formError": "Не вдалося надіслати. Будь ласка, напишіть напряму на email.",
        },
        "nav": {
            "speaking": "Виступи",
            "caseStudies": "Кейси",
            "mediaKit": "Медіа-кит",
            "groupMain": "Основне",
            "groupServices": "Послуги",
            "groupWork": "Робота",
        },
        "cta": {
            "eyebrow": "Співпраця",
            "title": "Запросити консультацію або виступ",
            "lead": "Для advisory-ролей, членства в радах директорів, виступів і стратегічних партнерств.",
            "button": "Зв'язатися",
        },
        "meta": {
            "speaking": {
                "title": "Виступи — Michael Kofman",
                "description": "Запросіть Michael Kofman виступити про executive-лідерство, технологічну стратегію, digital health і корпоративне управління.",
            },
            "caseStudies": {
                "title": "Кейси — Michael Kofman",
                "description": "Кейси з кар'єри Michael Kofman — 9 Net Avenue Inc. та Digital Invest Inc.",
            },
            "mediaKit": {
                "title": "Медіа-кит — Michael Kofman",
                "description": "Офіційні біографії, фотографії та контактна інформація для преси й організаторів подій.",
            },
            "article1": {
                "title": "Від інженерії до глобальної інфраструктури — Michael Kofman",
                "description": "Michael Kofman про шлях від супутникової інженерії до заснування глобальних компаній у сфері інфраструктури даних.",
            },
            "article2": {
                "title": "Прецизійна медицина і технології — Michael Kofman",
                "description": "Michael Kofman про поєднання наук про життя з AI, ML і ДНК-технологіями в сучасній медицині.",
            },
        },
        "speaking": {
            "eyebrow": "Публічні виступи",
            "title": "Запросіть Michael Kofman виступити",
            "lead": "Доступний для виступів про executive-лідерство, технологічну стратегію, digital health, інфраструктуру даних і корпоративне управління.",
            "topicsEyebrow": "Теми виступів",
            "topicsTitle": "Сфери експертизи",
            "topicsLead": "Теми базуються на десятиліттях досвіду заснування та керівництва компаніями у США та Європі.",
            "processEyebrow": "Як запросити",
            "processTitle": "Процес бронювання",
            "process1title": "Надішліть запит",
            "process1desc": "Скористайтеся контактною формою або напишіть на mkofman@mkofman.com, вказавши деталі події, аудиторію та бажані теми.",
            "process2title": "Узгодьте формат",
            "process2desc": "Погодьте формат (keynote, панель, сесія ради директорів або executive roundtable) і логістику.",
            "process3title": "Отримайте практичну цінність",
            "process3desc": "Виступи спираються на реальні результати проєктів у data storage, govtech і прецизійній медицині.",
            "cta": "Запросити виступ",
        },
        "caseStudies": {
            "eyebrow": "Кейси",
            "title": "Побудова компаній, що масштабуються",
            "lead": "Вибрані результати заснування та керівництва компаніями у сферах інфраструктури даних і digital health.",
            "cs1eyebrow": "Інфраструктура даних · 1996 — 2000",
            "cs1title": "9 Net Avenue Inc.",
            "cs1challenge": "Виклик",
            "cs1challengeText": "Побудувати та масштабувати компанію Data Storage на технологічному ринку, що швидко консолідувався.",
            "cs1action": "Підхід",
            "cs1actionText": "9 Net Avenue Inc. була заснована у 1996 році. Компанія швидко стала однією з найбільших у світі у сфері Data Storage.",
            "cs1result": "Результат",
            "cs1resultText": "У 2000 році компанію придбали Concentric Networks (NASDAQ: CNTX), а потім XO Communications (NASDAQ: XOXO), з піковою ринковою вартістю 19,5 млрд доларів. Після угоди було отримано значний досвід роботи з публічними компаніями, радами директорів і стратегічними рішеннями на найвищому рівні.",
            "cs2eyebrow": "Digital Health · 2021 — дотепер",
            "cs2title": "Digital Invest Inc.",
            "cs2challenge": "Виклик",
            "cs2challengeText": "Трансформувати застарілі підходи в медицині за допомогою науки, ДНК-технологій, AI і ML через нову біо-математичну платформу.",
            "cs2action": "Підхід",
            "cs2actionText": "Digital Invest Inc. була заснована та масштабована від старту до успішного IPO. Було очолено повний процес публічного розміщення: юридичне структурування, фінансовий комплаєнс, роудшоу для інвесторів і координацію із SEC. Також було організовано проєктування, будівництво та операційну діяльність кількох дата-центрів у США та Європі.",
            "cs2result": "Результат",
            "cs2resultText": "Досягнуто стабільного фінансового зростання, що вивело компанію до Top 10 компаній прецизійної медицини у США (2023). Digital Invest об'єднує інноваційні проєкти Human Digital Model, BioMath Life та Aero-Ground Robotics Operations Network.",
        },
        "mediaKit": {
            "eyebrow": "Преса та події",
            "title": "Медіа-кит",
            "lead": "Офіційні біографії, зображення та контакти для преси, конференцій і запитів від рад директорів.",
            "bioEyebrow": "Біографії",
            "bioTitle": "Офіційні біографії",
            "bioShortLabel": "50 слів",
            "bioShort": "Michael Kofman — CEO Digital Invest Inc., член рад директорів, радник і засновник компаній у сферах технологій і digital health у США та Європі.",
            "bioMediumLabel": "150 слів",
            "bioMedium": "Michael Kofman — CEO Digital Invest Inc. і член її Board of Directors. Технологічний візіонер, відомий динамічним підходом до розуміння потреб сучасного складного ринку, що постійно змінюється. Як підприємець, член рад директорів і радник публічних та приватних компаній, він успішно заснував кілька компаній у США та Європі. Його експертиза охоплює executive-менеджмент, стратегічний аналіз нових технологій і ринків, інформаційну безпеку та приватність, дослідження, науку й розробки, адміністрування та інвестиції.",
            "bioLongLabel": "500 слів",
            "bioLong": "Michael Kofman — CEO Digital Invest Inc. і член її Board of Directors. Технологічний візіонер, відомий динамічним підходом до розуміння потреб сучасного складного ринку, що постійно змінюється. Його експертиза охоплює executive-менеджмент, стратегічний аналіз нових технологій і ринків, інформаційну безпеку та приватність, дослідження, науку й розробки, адміністрування та інвестиції. Як підприємець, член рад директорів і радник публічних та приватних компаній, Michael Kofman успішно заснував кілька компаній у США та Європі. Він заснував 9 Net Avenue Inc., придбану на піку ринкової вартості 19,5 млрд доларів, і очолює Digital Invest Inc. у напрямах data storage та передових технологічних інновацій. Він керував технологічною стратегією для державних і оборонних програм, заснував XIBI Group Inc. і DataPeer Inc. у сфері data storage та відіграв важливу роль у Biotechnology Group Inc. Співпрацював із Harvard Medical School і Stanford Biomath над генетичними звітами. Автор технічних праць із супутникових та оптичних систем; патент на цифрове супутникове HDTV був придбаний Sony. Освіта: доктор технічних наук (2009), Ph.D. з інформаційних технологій (2004), Ukrainian State Marine Technical University.",
            "photosEyebrow": "Фотографії",
            "photosTitle": "Погоджені зображення",
            "photosLead": "Портрети високої роздільної здатності доступні за запитом на mkofman@mkofman.com.",
            "contactEyebrow": "Контакт для преси",
            "contactTitle": "Медійні запити",
            "contactLead": "Для інтерв'ю, запрошень на виступи та запитів від преси.",
        },
        "articles": {
            "backLink": "← Назад до Insights",
            "article1date": "Погляд керівника",
            "article1title": "Від інженерії до глобальної інфраструктури даних",
            "article1p1": "Моя кар'єра почалася на Миколаївському суднобудівному заводі в Україні, де я розробляв супутникові трансиверні системи для передавання засекреченої інформації військовим кораблям. Мене визнали інженером-електронщиком найвищого рівня — 6-ї категорії на підприємстві з 93 000 працівників.",
            "article1p2": "У 1989-1994 роках я заснував і очолював Astra Corp, одного з найбільших у Європі виробників цифрових супутникових трансиверних систем. У 1994-1996 роках, як CEO Elitan United Inc., я допоміг масштабувати компанію з дев'яти до понад 4 000 працівників у світі.",
            "article1p3": "У 1996 році я заснував 9 Net Avenue Inc., яка швидко стала однією з найбільших у світі компаній Data Storage. До 2000 року її придбали Concentric Networks (NASDAQ: CNTX) та XO Communications (NASDAQ: XOXO), і вона досягла пікової ринкової вартості 19,5 млрд доларів.",
            "article1p4": "У 2001-2019 роках я керував технологічною стратегією для державних, оборонних і квазідержавних програм, очолюючи масштабні ініціативи у сфері big data, захищеної інфраструктури та високопродуктивних дата-центрів у США та Європі.",
            "article2date": "Digital Health",
            "article2title": "Прецизійна медицина та конвергенція науки й технологій",
            "article2p1": "Я переконаний у потенціалі поєднання наук про життя з найновішими технологічними досягненнями. У Biotechnology Group Inc. (2008-2014) ми зосереджувалися на ДНК-тестуванні та аналізі, автоматизації процесів створення генетичних профілів і комплексних дослідженнях генетики людини.",
            "article2p2": "Під моїм керівництвом було започатковано успішні проєкти генетичного тестування в Україні, Росії та країнах Балтії. У співпраці з Harvard Medical School і Stanford Biomath я відіграв ключову роль у створенні зрозумілих генетичних звітів як для лікарів, так і для пацієнтів.",
            "article2p3": "З Digital Invest Inc., заснованою у 2021 році, ми працюємо в біо-математичному напрямі, трансформуючи застарілі підходи в медицині за допомогою науки, ДНК-технологій, AI і ML. Компанію було масштабовано від старту до успішного IPO, а у 2023 році її визнано однією з Top 10 найкращих компаній США у сфері прецизійної медицини та digital health.",
            "article2p4": "Digital Invest об'єднує інноваційні проєкти, зокрема Human Digital Model, BioMath Life та Aero-Ground Robotics Operations Network, кожен з яких посилює інтеграцію data science і наук про життя.",
        },
        "home": {
            "heroSub": "CEO, радник рад директорів і стратегічний технолог для публічних і приватних компаній у технологіях, data storage та digital health.",
            "featuredEyebrow": "Публікації та медіа",
            "primaryCta": "Запросити консультацію",
            "secondaryCta": "Переглянути кейси",
            "caseStudiesEyebrow": "Підтверджені результати",
            "caseStudiesTitle": "Кейси",
            "caseStudiesLead": "Заснування, масштабування та керівництво компаніями від старту до угод M&A та IPO.",
            "caseStudiesLink": "Переглянути всі кейси →",
            "cs1title": "9 Net Avenue Inc.",
            "cs1desc": "Побудовано одну з найбільших у світі компаній Data Storage, придбану при піковій ринковій вартості 19,5 млрд доларів.",
            "cs2title": "Digital Invest Inc.",
            "cs2desc": "Засновано та масштабовано від старту до IPO — Top 10 компаній прецизійної медицини у США, 2023.",
        },
        "recognition": {
            "moreLink": "Переглянути патенти, публікації та матеріали преси на сторінці Insights →",
        },
        "insights": {
            "articlesEyebrow": "Погляди",
            "articlesTitle": "Погляди керівника",
        },
    },
    "zh": {
        "ui": {
            "sending": "发送中…",
            "formError": "发送失败。请直接发送电子邮件。",
        },
        "nav": {
            "speaking": "演讲邀约",
            "caseStudies": "案例研究",
            "mediaKit": "媒体资料包",
            "groupMain": "主要",
            "groupServices": "服务",
            "groupWork": "成果",
        },
        "cta": {
            "eyebrow": "合作共赢",
            "title": "申请咨询或演讲",
            "lead": "适用于顾问合作、董事会职位、演讲邀约及战略合作伙伴关系。",
            "button": "联系我",
        },
        "meta": {
            "speaking": {
                "title": "演讲邀约 — Michael Kofman",
                "description": "邀请 Michael Kofman 就高管领导力、技术战略、数字健康和公司治理发表演讲。",
            },
            "caseStudies": {
                "title": "案例研究 — Michael Kofman",
                "description": "Michael Kofman 职业生涯案例研究：9 Net Avenue Inc. 与 Digital Invest Inc.",
            },
            "mediaKit": {
                "title": "媒体资料包 — Michael Kofman",
                "description": "面向媒体与活动主办方的官方简介、照片及联系方式。",
            },
            "article1": {
                "title": "从工程到全球基础设施 — Michael Kofman",
                "description": "Michael Kofman 讲述自己从卫星工程到创办全球数据基础设施公司的职业路径。",
            },
            "article2": {
                "title": "精准医疗与科技融合 — Michael Kofman",
                "description": "Michael Kofman 谈生命科学与 AI、ML 及 DNA 技术在现代医学中的融合。",
            },
        },
        "speaking": {
            "eyebrow": "演讲活动",
            "title": "邀请 Michael Kofman 演讲",
            "lead": "可就高管领导力、技术战略、数字健康、数据基础设施和公司治理进行演讲。",
            "topicsEyebrow": "演讲主题",
            "topicsTitle": "专业领域",
            "topicsLead": "主题内容基于其在美国和欧洲创办并领导企业数十年的实践经验。",
            "processEyebrow": "邀请方式",
            "processTitle": "预订流程",
            "process1title": "提交咨询",
            "process1desc": "请通过联系表单或发送邮件至 mkofman@mkofman.com，提供活动详情、受众信息及期望主题。",
            "process2title": "确认范围",
            "process2desc": "确认形式（主题演讲、论坛对谈、董事会会议或高管圆桌）及相关执行安排。",
            "process3title": "交付价值",
            "process3desc": "演讲内容基于在数据存储、政务科技和精准医疗领域的真实业务成果。",
            "cta": "申请演讲邀约",
        },
        "caseStudies": {
            "eyebrow": "案例研究",
            "title": "打造可规模化增长的公司",
            "lead": "精选其在数据基础设施与数字健康领域创办并领导企业的成果。",
            "cs1eyebrow": "数据基础设施 · 1996 — 2000",
            "cs1title": "9 Net Avenue Inc.",
            "cs1challenge": "挑战",
            "cs1challengeText": "在快速整合的科技市场中建立并扩展一家数据存储公司。",
            "cs1action": "策略",
            "cs1actionText": "1996 年创立 9 Net Avenue Inc.，公司迅速成长为全球最大的数据存储企业之一。",
            "cs1result": "成果",
            "cs1resultText": "到 2000 年，公司先后被 Concentric Networks（NASDAQ: CNTX）和 XO Communications（NASDAQ: XOXO）收购，峰值市值达到 195 亿美元。收购后，他积累了在上市公司、董事会治理及最高层战略决策方面的丰富经验。",
            "cs2eyebrow": "数字健康 · 2021 — 至今",
            "cs2title": "Digital Invest Inc.",
            "cs2challenge": "挑战",
            "cs2challengeText": "通过全新的生物数学平台，结合科学、DNA 技术、AI 与 ML，革新医学中的过时方法。",
            "cs2action": "策略",
            "cs2actionText": "创立并推动 Digital Invest Inc. 从零发展到成功 IPO，主导完整上市流程，包括法律架构、财务合规、投资者路演及与 SEC 协调。同时负责美国和欧洲多个数据中心的设计、建设与运营。",
            "cs2result": "成果",
            "cs2resultText": "实现持续财务增长，使公司跻身美国精准医疗企业前十（2023）。Digital Invest 旗下包括 Human Digital Model、BioMath Life 及 Aero-Ground Robotics Operations Network 等创新项目。",
        },
        "mediaKit": {
            "eyebrow": "媒体与活动",
            "title": "媒体资料包",
            "lead": "面向媒体、会议及董事会合作咨询的官方简介、视觉资料与联系方式。",
            "bioEyebrow": "人物简介",
            "bioTitle": "官方简介",
            "bioShortLabel": "50 词",
            "bioShort": "Michael Kofman 是 Digital Invest Inc. 的 CEO，同时担任董事会成员、顾问，并在美国和欧洲创办多家科技与数字健康企业。",
            "bioMediumLabel": "150 词",
            "bioMedium": "Michael Kofman 是 Digital Invest Inc. 的 CEO，并担任其董事会成员。作为技术远见者，他以动态方式洞察当今复杂市场不断变化的需求。作为企业家、董事会成员以及公私营企业顾问，他已在美国和欧洲成功创办多家公司。其专长覆盖高管领导力、新兴技术与市场战略分析、信息安全与隐私、科研与开发、管理及投资。",
            "bioLongLabel": "500 词",
            "bioLong": "Michael Kofman 是 Digital Invest Inc. 的 CEO，并担任其董事会成员。作为技术远见者，他以动态方式洞察当今复杂市场不断变化的需求。其专长涵盖高管领导力、新兴技术与市场战略分析、信息安全与隐私、科研与开发、管理及投资。作为企业家、董事会成员以及公私营企业顾问，Michael Kofman 在美国和欧洲成功创办了多家公司。他创立了 9 Net Avenue Inc.，并在峰值市值达 195 亿美元时被收购；目前他领导 Digital Invest Inc. 推动数据存储与先进技术创新。他曾主导政府及国防项目的技术战略，创立了数据存储领域的 XIBI Group Inc. 与 DataPeer Inc.，并在 Biotechnology Group Inc. 中发挥关键作用。他与 Harvard Medical School 和 Stanford Biomath 合作开展遗传报告项目。著有卫星与光学系统技术论文；其数字卫星 HDTV 专利被 Sony 收购。教育背景：技术科学博士（2009）、信息技术博士（2004）、Ukrainian State Marine Technical University。",
            "photosEyebrow": "摄影素材",
            "photosTitle": "授权图片",
            "photosLead": "如需高清肖像照，请发送邮件至 mkofman@mkofman.com。",
            "contactEyebrow": "媒体联系人",
            "contactTitle": "媒体咨询",
            "contactLead": "用于采访、演讲邀请及媒体合作请求。",
        },
        "articles": {
            "backLink": "← 返回 Insights",
            "article1date": "高管观点",
            "article1title": "从工程实践到全球数据基础设施",
            "article1p1": "我的职业生涯始于乌克兰尼古拉耶夫造船厂，当时负责开发用于向军舰传输机密信息的卫星收发系统。我被评为最高等级电子工程师，即在拥有 93,000 名员工的工厂中达到第 6 类工程师级别。",
            "article1p2": "1989 至 1994 年，我创立并领导了 Astra Corp，它是欧洲最大的数字卫星收发系统制造商之一。1994 至 1996 年，作为 Elitan United Inc. 的 CEO，我帮助公司从 9 人扩展到全球 4,000 余名员工。",
            "article1p3": "1996 年，我创立了 9 Net Avenue Inc.，该公司迅速成长为全球最大的数据存储企业之一。到 2000 年，公司被 Concentric Networks（NASDAQ: CNTX）和 XO Communications（NASDAQ: XOXO）收购，峰值市值达到 195 亿美元。",
            "article1p4": "2001 至 2019 年，我负责政府、国防及国有企业项目的技术战略，主导了美国和欧洲在大数据、安全基础设施及高吞吐数据中心方面的大型计划。",
            "article2date": "数字健康",
            "article2title": "精准医疗与科学技术融合",
            "article2p1": "我始终坚信生命科学与前沿技术结合所蕴含的巨大潜力。在 Biotechnology Group Inc.（2008-2014）期间，我们重点推进 DNA 检测与分析、遗传画像流程自动化以及全面的人类遗传学研究。",
            "article2p2": "在我的领导下，乌克兰、俄罗斯和波罗的海国家启动了多个成功的基因检测项目。与 Harvard Medical School 和 Stanford Biomath 的合作中，我在为医生和患者开发易于理解的基因报告方面发挥了关键作用。",
            "article2p3": "我们于 2021 年创立 Digital Invest Inc.，专注生物数学领域，借助科学、DNA 技术、AI 与 ML 改变传统医疗方式。公司从创立发展至成功 IPO，并在 2023 年被评为美国精准医疗与数字健康领域十佳公司之一。",
            "article2p4": "Digital Invest 旗下包括 Human Digital Model、BioMath Life 与 Aero-Ground Robotics Operations Network 等创新项目，持续推动数据科学与生命科学的深度融合。",
        },
        "home": {
            "heroSub": "面向公私营企业的 CEO、董事会顾问与战略技术专家，专注科技、数据存储与数字健康领域。",
            "featuredEyebrow": "媒体报道",
            "primaryCta": "申请顾问咨询",
            "secondaryCta": "查看案例研究",
            "caseStudiesEyebrow": "可验证成果",
            "caseStudiesTitle": "案例研究",
            "caseStudiesLead": "从创立到并购和 IPO，持续推动企业创建、扩张与领导。",
            "caseStudiesLink": "查看全部案例研究 →",
            "cs1title": "9 Net Avenue Inc.",
            "cs1desc": "打造了全球最大的数据存储企业之一，并在峰值市值 195 亿美元时被收购。",
            "cs2title": "Digital Invest Inc.",
            "cs2desc": "从创立扩展至成功 IPO，入选 2023 年美国精准医疗十强企业。",
        },
        "recognition": {
            "moreLink": "在 Insights 查看专利、出版物与媒体报道 →",
        },
        "insights": {
            "articlesEyebrow": "观点洞察",
            "articlesTitle": "高管观点",
        },
    },
    "ar": {
        "ui": {
            "sending": "جارٍ الإرسال…",
            "formError": "تعذر الإرسال. يرجى إرسال بريد إلكتروني مباشرة.",
        },
        "nav": {
            "speaking": "المحاضرات",
            "caseStudies": "دراسات الحالة",
            "mediaKit": "الحقيبة الإعلامية",
            "groupMain": "الرئيسية",
            "groupServices": "الخدمات",
            "groupWork": "الأعمال",
        },
        "cta": {
            "eyebrow": "لنعمل معًا",
            "title": "طلب استشارة أو دعوة للتحدث",
            "lead": "للأدوار الاستشارية، ومناصب مجالس الإدارة، والفعاليات الخطابية، والشراكات الاستراتيجية.",
            "button": "تواصل الآن",
        },
        "meta": {
            "speaking": {
                "title": "المحاضرات — Michael Kofman",
                "description": "ادعُ Michael Kofman للحديث عن القيادة التنفيذية، واستراتيجية التكنولوجيا، والصحة الرقمية، وحوكمة الشركات.",
            },
            "caseStudies": {
                "title": "دراسات الحالة — Michael Kofman",
                "description": "دراسات حالة من مسيرة Michael Kofman: 9 Net Avenue Inc. وDigital Invest Inc.",
            },
            "mediaKit": {
                "title": "الحقيبة الإعلامية — Michael Kofman",
                "description": "سير ذاتية رسمية، وصور، وبيانات اتصال للصحافة ومنظمي الفعاليات.",
            },
            "article1": {
                "title": "من الهندسة إلى البنية التحتية العالمية — Michael Kofman",
                "description": "Michael Kofman حول المسار المهني من هندسة الأقمار الصناعية إلى تأسيس شركات بنية تحتية عالمية للبيانات.",
            },
            "article2": {
                "title": "الطب الدقيق والتكنولوجيا — Michael Kofman",
                "description": "Michael Kofman حول دمج علوم الحياة مع AI وML وتقنيات الحمض النووي في الطب الحديث.",
            },
        },
        "speaking": {
            "eyebrow": "المشاركات الخطابية",
            "title": "ادعُ Michael Kofman للتحدث",
            "lead": "متاح للمحاضرات حول القيادة التنفيذية، واستراتيجية التكنولوجيا، والصحة الرقمية، وبنية البيانات، وحوكمة الشركات.",
            "topicsEyebrow": "موضوعات التحدث",
            "topicsTitle": "مجالات الخبرة",
            "topicsLead": "تعتمد الموضوعات على عقود من الخبرة في تأسيس وقيادة شركات في الولايات المتحدة وأوروبا.",
            "processEyebrow": "كيفية الدعوة",
            "processTitle": "خطوات الحجز",
            "process1title": "أرسل استفسارًا",
            "process1desc": "استخدم نموذج التواصل أو راسل mkofman@mkofman.com مع تفاصيل الحدث والجمهور والموضوعات المفضلة.",
            "process2title": "تأكيد النطاق",
            "process2desc": "تحديد الصيغة (كلمة رئيسية، أو جلسة نقاش، أو جلسة مجلس إدارة، أو مائدة مستديرة تنفيذية) واللوجستيات.",
            "process3title": "تحقيق قيمة عملية",
            "process3desc": "ترتكز العروض على نتائج فعلية من مشاريع في تخزين البيانات وgovtech والطب الدقيق.",
            "cta": "طلب مشاركة خطابية",
        },
        "caseStudies": {
            "eyebrow": "دراسات الحالة",
            "title": "بناء شركات قابلة للتوسع",
            "lead": "نتائج مختارة من تأسيس وقيادة شركات في البنية التحتية للبيانات والصحة الرقمية.",
            "cs1eyebrow": "بنية البيانات · 1996 — 2000",
            "cs1title": "9 Net Avenue Inc.",
            "cs1challenge": "التحدي",
            "cs1challengeText": "بناء شركة تخزين بيانات وتوسيعها في سوق تقني سريع الاندماج.",
            "cs1action": "النهج",
            "cs1actionText": "أسس Michael Kofman شركة 9 Net Avenue Inc. عام 1996. وسرعان ما أصبحت واحدة من أكبر شركات تخزين البيانات في العالم.",
            "cs1result": "النتيجة",
            "cs1resultText": "بحلول عام 2000، تم الاستحواذ عليها من قبل Concentric Networks (NASDAQ: CNTX) ثم XO Communications (NASDAQ: XOXO)، ووصلت إلى قيمة سوقية قصوى بلغت 19.5 مليار دولار. وبعد الاستحواذ، اكتسب خبرة واسعة في العمل مع الشركات العامة، ومجالس الإدارة، واتخاذ القرارات الاستراتيجية على أعلى المستويات التنفيذية.",
            "cs2eyebrow": "الصحة الرقمية · 2021 — حتى الآن",
            "cs2title": "Digital Invest Inc.",
            "cs2challenge": "التحدي",
            "cs2challengeText": "تحويل الأساليب الطبية القديمة عبر العلوم وتقنيات الحمض النووي وAI وML من خلال منصة بيولوجية رياضية جديدة.",
            "cs2action": "النهج",
            "cs2actionText": "أسس Michael Kofman شركة Digital Invest Inc. وقاد توسعها من البداية حتى طرح عام أولي ناجح. كما قاد كامل عملية الطرح: الهيكلة القانونية، والامتثال المالي، وجولات المستثمرين، والتنسيق مع SEC. وأشرف على تصميم وبناء وتشغيل عدة مراكز بيانات في الولايات المتحدة وأوروبا.",
            "cs2result": "النتيجة",
            "cs2resultText": "تحقق نمو مالي متسق، ما وضع الشركة ضمن أفضل 10 شركات طب دقيق في الولايات المتحدة (2023). وتضم Digital Invest مشاريع ابتكارية مثل Human Digital Model وBioMath Life وAero-Ground Robotics Operations Network.",
        },
        "mediaKit": {
            "eyebrow": "الصحافة والفعاليات",
            "title": "الحقيبة الإعلامية",
            "lead": "سير رسمية، وصور معتمدة، وبيانات تواصل للصحافة والمؤتمرات واستفسارات مجالس الإدارة.",
            "bioEyebrow": "السير الذاتية",
            "bioTitle": "السير الرسمية",
            "bioShortLabel": "50 كلمة",
            "bioShort": "Michael Kofman هو CEO لشركة Digital Invest Inc. وعضو مجلس إدارة ومستشار ومؤسس لشركات في التكنولوجيا والصحة الرقمية عبر الولايات المتحدة وأوروبا.",
            "bioMediumLabel": "150 كلمة",
            "bioMedium": "Michael Kofman هو CEO لشركة Digital Invest Inc. وعضو في Board of Directors. ويُعد صاحب رؤية تقنية معروفًا بنهجه الديناميكي في فهم متطلبات السوق المعقدة والمتغيرة باستمرار. وبصفته رائد أعمال وعضو مجلس إدارة ومستشارًا لشركات عامة وخاصة، نجح في تأسيس عدة شركات في الولايات المتحدة وأوروبا. وتشمل خبرته القيادة التنفيذية، والتحليل الاستراتيجي للتقنيات والأسواق الناشئة، وأمن المعلومات والخصوصية، والبحث العلمي والتطوير، والإدارة، والاستثمار.",
            "bioLongLabel": "500 كلمة",
            "bioLong": "Michael Kofman هو CEO لشركة Digital Invest Inc. وعضو في Board of Directors. وهو صاحب رؤية تقنية معروف بنهجه الديناميكي لفهم احتياجات السوق المعقدة والمتغيرة باستمرار. وتمتد خبرته إلى القيادة التنفيذية، والتحليل الاستراتيجي للتقنيات والأسواق الناشئة، وأمن المعلومات والخصوصية، والبحث العلمي والتطوير، والإدارة، والاستثمار. وبصفته رائد أعمال وعضو مجلس إدارة ومستشارًا لشركات عامة وخاصة، نجح Michael Kofman في تأسيس عدة شركات في الولايات المتحدة وأوروبا. وقد أسس 9 Net Avenue Inc. التي تم الاستحواذ عليها عند قيمة سوقية قصوى بلغت 19.5 مليار دولار، ويقود Digital Invest Inc. في مجالات تخزين البيانات والابتكار التكنولوجي المتقدم. كما قاد الاستراتيجية التقنية لبرامج حكومية ودفاعية، وأسّس XIBI Group Inc. وDataPeer Inc. في قطاع تخزين البيانات، ولعب دورًا مهمًا في Biotechnology Group Inc. وتعاون مع Harvard Medical School وStanford Biomath في إعداد التقارير الجينية. وهو مؤلف أوراق تقنية حول الأنظمة الفضائية والبصرية؛ كما استحوذت Sony على براءة اختراع له في HDTV الفضائي الرقمي. المؤهلات: Doctor of Technical Sciences (2009)، وPh.D. in Information Technology (2004)، من Ukrainian State Marine Technical University.",
            "photosEyebrow": "الصور",
            "photosTitle": "صور معتمدة",
            "photosLead": "تتوفر صور شخصية عالية الدقة عند الطلب عبر mkofman@mkofman.com.",
            "contactEyebrow": "تواصل إعلامي",
            "contactTitle": "استفسارات الصحافة",
            "contactLead": "للمقابلات والدعوات الخطابية والطلبات الإعلامية.",
        },
        "articles": {
            "backLink": "← العودة إلى Insights",
            "article1date": "رؤية تنفيذية",
            "article1title": "من الهندسة إلى البنية التحتية العالمية للبيانات",
            "article1p1": "بدأت مسيرتي في مصنع نيكولايف لبناء السفن في أوكرانيا، حيث طورت أنظمة إرسال واستقبال عبر الأقمار الصناعية لنقل معلومات سرية إلى السفن العسكرية. وتم الاعتراف بي كمهندس إلكترونيات من أعلى مستوى - الفئة السادسة - في مصنع يضم 93,000 موظف.",
            "article1p2": "من 1989 إلى 1994، أسست وقادت Astra Corp، إحدى أكبر الشركات الأوروبية المصنعة لأنظمة الإرسال والاستقبال الفضائية الرقمية. ومن 1994 إلى 1996، وبصفتي CEO لشركة Elitan United Inc.، ساعدت في توسيع الشركة من تسعة موظفين إلى أكثر من 4,000 موظف حول العالم.",
            "article1p3": "في عام 1996، أسست 9 Net Avenue Inc. التي سرعان ما أصبحت واحدة من أكبر شركات تخزين البيانات في العالم. وبحلول عام 2000، تم الاستحواذ عليها من قبل Concentric Networks (NASDAQ: CNTX) وXO Communications (NASDAQ: XOXO)، لتصل إلى قيمة سوقية قصوى بلغت 19.5 مليار دولار.",
            "article1p4": "بين 2001 و2019، قدت استراتيجية التكنولوجيا لبرامج حكومية ودفاعية وبرامج الشركات المملوكة للدولة، وقادت مبادرات واسعة في البيانات الضخمة والبنية التحتية الآمنة ومراكز البيانات عالية الإنتاجية عبر الولايات المتحدة وأوروبا.",
            "article2date": "الصحة الرقمية",
            "article2title": "الطب الدقيق وتقاطع العلم مع التكنولوجيا",
            "article2p1": "أنا مؤمن بقوة بإمكانات الجمع بين علوم الحياة وأحدث التطورات التقنية. في Biotechnology Group Inc. (2008-2014)، ركزنا على اختبارات وتحليل الحمض النووي، وأتمتة عمليات إعداد الملفات الجينية، والبحث الجيني البشري الشامل.",
            "article2p2": "تحت قيادتي، انطلقت مشاريع ناجحة للاختبارات الجينية في أوكرانيا وروسيا ودول البلطيق. وبالتعاون مع Harvard Medical School وStanford Biomath، لعبت دورًا محوريًا في تطوير تقارير جينية واضحة وسهلة الفهم للأطباء والمرضى.",
            "article2p3": "مع Digital Invest Inc. التي تأسست عام 2021، نعمل في المجال البيولوجي الرياضي لتحويل الأساليب القديمة في الطب عبر العلوم وتقنيات الحمض النووي وAI وML. وقد توسعت الشركة من بدايتها حتى طرح عام أولي ناجح، وتم تصنيفها ضمن أفضل 10 شركات أمريكية في الطب الدقيق والصحة الرقمية عام 2023.",
            "article2p4": "تضم Digital Invest مشاريع ابتكارية متعددة، منها Human Digital Model وBioMath Life وAero-Ground Robotics Operations Network، وكل مشروع يدفع تكامل علوم البيانات مع علوم الحياة.",
        },
        "home": {
            "heroSub": "CEO، ومستشار مجالس إدارة، واستراتيجي تقني للشركات العامة والخاصة في التكنولوجيا وتخزين البيانات والصحة الرقمية.",
            "featuredEyebrow": "كما ورد في",
            "primaryCta": "طلب استشارة",
            "secondaryCta": "عرض دراسات الحالة",
            "caseStudiesEyebrow": "نتائج مثبتة",
            "caseStudiesTitle": "دراسات الحالة",
            "caseStudiesLead": "تأسيس الشركات وتوسيعها وقيادتها من البداية حتى الاستحواذ والطرح العام.",
            "caseStudiesLink": "عرض جميع دراسات الحالة →",
            "cs1title": "9 Net Avenue Inc.",
            "cs1desc": "بنى واحدة من أكبر شركات تخزين البيانات في العالم، وتم الاستحواذ عليها عند قيمة سوقية قصوى بلغت 19.5 مليار دولار.",
            "cs2title": "Digital Invest Inc.",
            "cs2desc": "تأسست وتوسعت من البداية حتى طرح عام أولي ناجح - ضمن أفضل 10 شركات طب دقيق في الولايات المتحدة لعام 2023.",
        },
        "recognition": {
            "moreLink": "اطّلع على براءات الاختراع والمنشورات والتغطية الإعلامية في Insights →",
        },
        "insights": {
            "articlesEyebrow": "رؤى",
            "articlesTitle": "رؤى تنفيذية",
        },
    },
    "he": {
        "ui": {
            "sending": "שולח…",
            "formError": "לא ניתן היה לשלוח. נא לשלוח אימייל ישירות.",
        },
        "nav": {
            "speaking": "הרצאות",
            "caseStudies": "מקרי בוחן",
            "mediaKit": "ערכת מדיה",
            "groupMain": "ראשי",
            "groupServices": "שירותים",
            "groupWork": "עבודה",
        },
        "cta": {
            "eyebrow": "בואו נעבוד יחד",
            "title": "בקשת ייעוץ או הזמנת הרצאה",
            "lead": "לתפקידי ייעוץ, משרות בדירקטוריון, הרצאות ושותפויות אסטרטגיות.",
            "button": "יצירת קשר",
        },
        "meta": {
            "speaking": {
                "title": "הרצאות — Michael Kofman",
                "description": "הזמינו את Michael Kofman להרצות על מנהיגות ניהולית, אסטרטגיית טכנולוגיה, בריאות דיגיטלית וממשל תאגידי.",
            },
            "caseStudies": {
                "title": "מקרי בוחן — Michael Kofman",
                "description": "מקרי בוחן מהקריירה של Michael Kofman: 9 Net Avenue Inc. ו-Digital Invest Inc.",
            },
            "mediaKit": {
                "title": "ערכת מדיה — Michael Kofman",
                "description": "ביוגרפיות רשמיות, תמונות ופרטי קשר עבור עיתונות ומפיקי אירועים.",
            },
            "article1": {
                "title": "מהנדסה לתשתית גלובלית — Michael Kofman",
                "description": "Michael Kofman על מסלול הקריירה מהנדסת לוויינים ועד הקמת חברות גלובליות לתשתיות נתונים.",
            },
            "article2": {
                "title": "רפואה מדויקת וטכנולוגיה — Michael Kofman",
                "description": "Michael Kofman על שילוב מדעי החיים עם AI, ML וטכנולוגיות DNA ברפואה המודרנית.",
            },
        },
        "speaking": {
            "eyebrow": "הרצאות וכנסים",
            "title": "הזמינו את Michael Kofman להרצות",
            "lead": "זמין להרצאות בנושאי מנהיגות ניהולית, אסטרטגיה טכנולוגית, בריאות דיגיטלית, תשתיות נתונים וממשל תאגידי.",
            "topicsEyebrow": "נושאי ההרצאה",
            "topicsTitle": "תחומי מומחיות",
            "topicsLead": "הנושאים מבוססים על עשרות שנות ניסיון בהקמה ובהובלה של חברות בארצות הברית ובאירופה.",
            "processEyebrow": "איך להזמין",
            "processTitle": "תהליך ההזמנה",
            "process1title": "שלחו פנייה",
            "process1desc": "השתמשו בטופס יצירת הקשר או שלחו אימייל ל-mkofman@mkofman.com עם פרטי האירוע, קהל היעד והנושאים המבוקשים.",
            "process2title": "אישור היקף",
            "process2desc": "מתאמים את הפורמט (הרצאת מפתח, פאנל, ישיבת דירקטוריון או שולחן עגול להנהלה) ואת הלוגיסטיקה.",
            "process3title": "יצירת ערך",
            "process3desc": "המצגות מבוססות על תוצאות אמיתיות ממיזמים בתחומי אחסון נתונים, govtech ורפואה מדויקת.",
            "cta": "בקשת הזמנת הרצאה",
        },
        "caseStudies": {
            "eyebrow": "מקרי בוחן",
            "title": "בניית חברות שמצליחות להתרחב",
            "lead": "תוצאות נבחרות מהקמה והובלה של חברות בתחומי תשתיות נתונים ובריאות דיגיטלית.",
            "cs1eyebrow": "תשתיות נתונים · 1996 — 2000",
            "cs1title": "9 Net Avenue Inc.",
            "cs1challenge": "אתגר",
            "cs1challengeText": "לבנות ולהרחיב חברת Data Storage בשוק טכנולוגי שנמצא בתהליך קונסולידציה מהיר.",
            "cs1action": "גישה",
            "cs1actionText": "Michael Kofman ייסד את 9 Net Avenue Inc. בשנת 1996. החברה הפכה במהירות לאחת מחברות ה-Data Storage הגדולות בעולם.",
            "cs1result": "תוצאה",
            "cs1resultText": "בשנת 2000 נרכשה החברה על ידי Concentric Networks (NASDAQ: CNTX), ובהמשך על ידי XO Communications (NASDAQ: XOXO), והגיעה לשווי שוק שיא של 19.5 מיליארד דולר. לאחר הרכישה נצבר ניסיון רב בעבודה עם חברות ציבוריות, ישיבה בדירקטוריונים וקבלת החלטות אסטרטגיות בדרג הניהולי הבכיר ביותר.",
            "cs2eyebrow": "בריאות דיגיטלית · 2021 — היום",
            "cs2title": "Digital Invest Inc.",
            "cs2challenge": "אתגר",
            "cs2challengeText": "להפוך גישות רפואיות מיושנות באמצעות מדע, טכנולוגיות DNA, AI ו-ML דרך פלטפורמה ביו-מתמטית חדשה.",
            "cs2action": "גישה",
            "cs2actionText": "Michael Kofman ייסד והרחיב את Digital Invest Inc. מהקמה ועד IPO מוצלח. הוא הוביל את כל תהליך ההנפקה: מבנה משפטי, ציות פיננסי, סבבי משקיעים ותיאום מול SEC. בנוסף הוביל תכנון, הקמה ותפעול של מספר מרכזי נתונים בארצות הברית ובאירופה.",
            "cs2result": "תוצאה",
            "cs2resultText": "הושגה צמיחה פיננסית עקבית, שמיצבה את החברה בין 10 החברות המובילות בארה״ב ברפואה מדויקת (2023). Digital Invest כוללת פרויקטים חדשניים כמו Human Digital Model, BioMath Life ו-Aero-Ground Robotics Operations Network.",
        },
        "mediaKit": {
            "eyebrow": "עיתונות ואירועים",
            "title": "ערכת מדיה",
            "lead": "ביוגרפיות רשמיות, חומרי תמונה ופרטי קשר עבור עיתונות, כנסים ופניות דירקטוריון.",
            "bioEyebrow": "ביוגרפיות",
            "bioTitle": "ביוגרפיות רשמיות",
            "bioShortLabel": "50 מילים",
            "bioShort": "Michael Kofman הוא CEO של Digital Invest Inc., חבר דירקטוריון, יועץ ומייסד חברות בתחומי הטכנולוגיה והבריאות הדיגיטלית בארה״ב ובאירופה.",
            "bioMediumLabel": "150 מילים",
            "bioMedium": "Michael Kofman הוא CEO של Digital Invest Inc. ומשמש כחבר ב-Board of Directors שלה. כאיש חזון טכנולוגי, הוא מוכר בגישתו הדינמית להבנת הצרכים המשתנים של שוק מורכב. כיזם, חבר דירקטוריון ויועץ לחברות ציבוריות ופרטיות, הוא הקים בהצלחה מספר חברות בארצות הברית ובאירופה. תחומי המומחיות שלו כוללים הנהלה בכירה, ניתוח אסטרטגי של טכנולוגיות ושווקים מתפתחים, אבטחת מידע ופרטיות, מחקר, מדע ופיתוח, ניהול והשקעות.",
            "bioLongLabel": "500 מילים",
            "bioLong": "Michael Kofman הוא CEO של Digital Invest Inc. ומשמש כחבר ב-Board of Directors שלה. כאיש חזון טכנולוגי, הוא מוכר בגישתו הדינמית להבנת הצרכים המשתנים של השוק המורכב של ימינו. מומחיותו כוללת הנהלה בכירה, ניתוח אסטרטגי של טכנולוגיות ושווקים מתפתחים, אבטחת מידע ופרטיות, מחקר, מדע ופיתוח, ניהול והשקעות. כיזם, חבר דירקטוריון ויועץ לחברות ציבוריות ופרטיות, Michael Kofman הקים בהצלחה מספר חברות בארצות הברית ובאירופה. הוא ייסד את 9 Net Avenue Inc., שנרכשה בשווי שוק שיא של 19.5 מיליארד דולר, ומוביל את Digital Invest Inc. בתחומי אחסון נתונים וחדשנות טכנולוגית מתקדמת. הוא ניהל אסטרטגיה טכנולוגית לתוכניות ממשלתיות וביטחוניות, ייסד את XIBI Group Inc. ואת DataPeer Inc. בתחום אחסון הנתונים, ומילא תפקיד משמעותי ב-Biotechnology Group Inc. הוא שיתף פעולה עם Harvard Medical School ו-Stanford Biomath בתחום הדוחות הגנטיים. מחבר מאמרים טכניים על מערכות לוויין ואופטיקה; פטנט בתחום HDTV לווייני דיגיטלי נרכש על ידי Sony. השכלה: Doctor of Technical Sciences (2009), Ph.D. in Information Technology (2004), Ukrainian State Marine Technical University.",
            "photosEyebrow": "צילום",
            "photosTitle": "תמונות מאושרות",
            "photosLead": "דיוקנאות באיכות גבוהה זמינים לפי בקשה בכתובת mkofman@mkofman.com.",
            "contactEyebrow": "קשרי עיתונות",
            "contactTitle": "פניות מדיה",
            "contactLead": "לראיונות, הזמנות להרצאות ופניות תקשורת.",
        },
        "articles": {
            "backLink": "← חזרה ל-Insights",
            "article1date": "נקודת מבט ניהולית",
            "article1title": "מהנדסה לתשתיות נתונים גלובליות",
            "article1p1": "הקריירה שלי החלה במפעל לבניית ספינות בניקולאייב שבאוקראינה, בפיתוח מערכות משדר-מקלט לווייניות להעברת מידע מסווג לספינות צבאיות. הוכרתי כמהנדס אלקטרוניקה ברמה הגבוהה ביותר - קטגוריה 6 - במפעל של 93,000 עובדים.",
            "article1p2": "בין 1989 ל-1994 ייסדתי והובלתי את Astra Corp, אחת היצרניות הגדולות באירופה של מערכות לוויין דיגיטליות מסוג משדר-מקלט. בין 1994 ל-1996, כ-CEO של Elitan United Inc., סייעתי להרחבת החברה מתשעה עובדים ליותר מ-4,000 עובדים ברחבי העולם.",
            "article1p3": "בשנת 1996 ייסדתי את 9 Net Avenue Inc., שהפכה במהירות לאחת מחברות ה-Data Storage הגדולות בעולם. עד שנת 2000 היא נרכשה על ידי Concentric Networks (NASDAQ: CNTX) ו-XO Communications (NASDAQ: XOXO), והגיעה לשווי שוק שיא של 19.5 מיליארד דולר.",
            "article1p4": "בין 2001 ל-2019 הובלתי אסטרטגיית טכנולוגיה לתוכניות ממשלתיות, ביטחוניות ולחברות בבעלות מדינה, תוך הובלת יוזמות רחבות היקף בתחומי Big Data, תשתיות מאובטחות ומרכזי נתונים בתפוקה גבוהה בארצות הברית ובאירופה.",
            "article2date": "בריאות דיגיטלית",
            "article2title": "רפואה מדויקת והמפגש בין מדע לטכנולוגיה",
            "article2p1": "אני מאמין עמוקות בפוטנציאל של שילוב מדעי החיים עם החידושים הטכנולוגיים המתקדמים ביותר. ב-Biotechnology Group Inc. ‏(2008-2014) התמקדנו בבדיקות וניתוחי DNA, אוטומציה של תהליכי יצירת פרופילים גנטיים, ומחקר גנטי מקיף של האדם.",
            "article2p2": "תחת הנהגתי, הושקו פרויקטים מוצלחים של בדיקות גנטיות באוקראינה, רוסיה ומדינות הבלטיות. בשיתוף עם Harvard Medical School ו-Stanford Biomath מילאתי תפקיד מרכזי בפיתוח דוחות גנטיים מובנים לרופאים ולמטופלים.",
            "article2p3": "עם Digital Invest Inc., שנוסדה ב-2021, אנו מתמקדים בתחום הביו-מתמטי ומשנים גישות מיושנות ברפואה באמצעות מדע, טכנולוגיות DNA, AI ו-ML. החברה הורחבה מהקמה ועד IPO מוצלח והוכרה בין 10 החברות הטובות בארצות הברית ברפואה מדויקת ובריאות דיגיטלית בשנת 2023.",
            "article2p4": "Digital Invest כוללת פרויקטים חדשניים מגוונים, בהם Human Digital Model, ‏BioMath Life ו-Aero-Ground Robotics Operations Network - וכל אחד מהם מקדם את שילוב מדעי הנתונים עם מדעי החיים.",
        },
        "home": {
            "heroSub": "CEO, יועץ לדירקטוריונים וטכנולוג אסטרטגי עבור חברות ציבוריות ופרטיות בתחומי הטכנולוגיה, אחסון הנתונים והבריאות הדיגיטלית.",
            "featuredEyebrow": "פורסם ב-",
            "primaryCta": "בקשת ייעוץ",
            "secondaryCta": "צפייה במקרי בוחן",
            "caseStudiesEyebrow": "תוצאות מוכחות",
            "caseStudiesTitle": "מקרי בוחן",
            "caseStudiesLead": "הקמה, הרחבה והובלת חברות מהשלב הראשוני ועד רכישה ו-IPO.",
            "caseStudiesLink": "צפייה בכל מקרי הבוחן →",
            "cs1title": "9 Net Avenue Inc.",
            "cs1desc": "נבנתה כאחת מחברות ה-Data Storage הגדולות בעולם ונרכשה בשווי שוק שיא של 19.5 מיליארד דולר.",
            "cs2title": "Digital Invest Inc.",
            "cs2desc": "הוקמה והורחבה מההתחלה ועד IPO מוצלח - בין 10 החברות המובילות בארה״ב ברפואה מדויקת, 2023.",
        },
        "recognition": {
            "moreLink": "צפו בפטנטים, פרסומים וכתבות בעיתונות בעמוד Insights →",
        },
        "insights": {
            "articlesEyebrow": "תובנות",
            "articlesTitle": "נקודות מבט ניהוליות",
        },
    },
}
