window.__LANG_ar = {
  "ui": {
    "toggleTheme": "تبديل السمة الفاتحة/الداكنة",
    "selectLanguage": "اختر اللغة",
    "messageSent": "تم إرسال الرسالة",
    "sendMessage": "إرسال",
    "toggleNav": "فتح القائمة",
    "sending": "جارٍ الإرسال…",
    "formError": "تعذر الإرسال. يرجى إرسال بريد إلكتروني مباشرة.",
    "present": "حتى الآن"
  },
  "nav": {
    "home": "الرئيسية",
    "about": "نبذة",
    "ventures": "المشاريع",
    "career": "السجل",
    "recognition": "التكريم",
    "contact": "تواصل",
    "consulting": "الاستشارات",
    "insights": "رؤى",
    "speaking": "المحاضرات",
    "caseStudies": "دراسات الحالة",
    "mediaKit": "الحقيبة الإعلامية",
    "groupMain": "الرئيسية",
    "groupServices": "خدمات",
    "groupWork": "الأعمال",
    "briefIpo": "ملخص: IPO",
    "briefGenetic": "Brief: البيانات الجينية",
    "briefAi": "Brief: استراتيجية AI",
    "articleInfra": "بنية البيانات التحتية",
    "articleHealth": "الطب الدقيق",
    "board": "استشارات",
    "thesis": "أطروحة القيادة",
    "press": "صحافة",
    "ip": "الملكية الفكرية"
  },
  "footer": {
    "navigation": "التنقل",
    "ventures": "المشاريع",
    "connect": "تواصل",
    "desc": "تنفيذي تقني ومؤسس ومستشار مجالس إدارة.",
    "copyright": "© {year} Michael Kofman. جميع الحقوق محفوظة.",
    "writeTitle": "اكتب لي",
    "writeEmail": "بريدك الإلكتروني",
    "writeMessage": "رسالتك",
    "writeSend": "إرسال",
    "writeSuccess": "شكراً — تم إرسال رسالتك.",
    "more": "المزيد",
    "privacy": "الخصوصية"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — تنفيذي تقني",
      "description": "تنفيذي تقني ومؤسس ومستشار — البنية التحتية وعلوم الحياة والأنظمة المستقلة."
    },
    "about": {
      "title": "نبذة — Michael Kofman",
      "description": "سيرة Michael Kofman — الرئيس التنفيذي لـ Digital Invest Inc. ومؤسس AGRON Inc."
    },
    "ventures": {
      "title": "المشاريع — Michael Kofman",
      "description": "الشركات التي أسسها مايكل كوفمان وقادها — من Digital Invest Inc. إلى 9 Net Avenue Inc. — لبناء أعمال تحويلية في التكنولوجيا والرعاية الصحية."
    },
    "career": {
      "title": "السجل — Michael Kofman",
      "description": "سجل مهني في الهندسة والبنية التحتية والأسواق العامة وعلوم الحياة والأنظمة المستقلة."
    },
    "recognition": {
      "title": "التكريم — Michael Kofman",
      "description": "الجوائز والتكريمات لمايكل كوفمان — رائد العام، Who's Who، براءات الاختراع وتقدير القطاع."
    },
    "contact": {
      "title": "تواصل — Michael Kofman",
      "description": "التواصل مع مايكل كوفمان — الرئيس التنفيذي لـ Digital Invest Inc. للاستشارات والمحاضرات والاستفسارات التجارية."
    },
    "consulting": {
      "title": "الاستشارات — Michael Kofman",
      "description": "أدوار استشارية ومقاعد في مجالس الإدارة ومحاضرات وشراكات استراتيجية مع Michael Kofman."
    },
    "insights": {
      "title": "رؤى — Michael Kofman",
      "description": "كتابات أصلية وbriefs تنفيذية من Michael Kofman."
    },
    "speaking": {
      "title": "المحاضرات — Michael Kofman",
      "description": "ادعُ Michael Kofman للحديث عن القيادة التنفيذية، واستراتيجية التكنولوجيا، والصحة الرقمية، وحوكمة الشركات."
    },
    "caseStudies": {
      "title": "دراسات الحالة — Michael Kofman",
      "description": "دراسات حالة من مسيرة Michael Kofman: 9 Net Avenue Inc. وDigital Invest Inc."
    },
    "mediaKit": {
      "title": "الحقيبة الإعلامية — Michael Kofman",
      "description": "سير ذاتية رسمية، وصور، وبيانات اتصال للصحافة ومنظمي الفعاليات."
    },
    "article1": {
      "title": "من الهندسة إلى البنية التحتية العالمية — Michael Kofman",
      "description": "Michael Kofman حول المسار المهني من هندسة الأقمار الصناعية إلى تأسيس شركات بنية تحتية عالمية للبيانات."
    },
    "article2": {
      "title": "الطب الدقيق والتكنولوجيا — Michael Kofman",
      "description": "Michael Kofman حول دمج علوم الحياة مع AI وML وتقنيات الحمض النووي في الطب الحديث."
    },
    "privacy": {
      "title": "سياسة الخصوصية — Michael Kofman",
      "description": "سياسة خصوصية mkofman.com — النماذج والتحليلات."
    },
    "board": {
      "title": "استشارات — Michael Kofman",
      "description": "محادثات استشارية استراتيجية مع منظمات التكنولوجيا والرعاية الصحية والبنية التحتية."
    },
    "thesis": {
      "title": "أطروحة القيادة — Michael Kofman",
      "description": "مبادئ Michael Kofman لبناء شركات دائمة وحوكمة التكنولوجيا والقيادة في مواجهة التغيير الجوهري."
    },
    "press": {
      "title": "أرشيف الصحافة — Michael Kofman",
      "description": "Selected press coverage spanning Michael Kofman's career."
    },
    "ip": {
      "title": "الملكية الفكرية — Michael Kofman",
      "description": "Patents, publications وapplied research لـ Michael Kofman."
    },
    "briefIpo": {
      "title": "ما يغيره الاكتتاب العام — Michael Kofman",
      "description": "ملخص تنفيذي عن operating discipline وgovernance وaccountability قبل وبعد IPO."
    },
    "briefGenetic": {
      "title": "من البيانات الجينية إلى القرارات السريرية — Michael Kofman",
      "description": "ملخص تنفيذي عن ترجمة المعلومات الجينومية إلى ذكاء سريري مسؤول وم useful وscalable."
    },
    "briefAi": {
      "title": "استراتيجية AI — Michael Kofman",
      "description": "ملخص تنفيذي عن نقل الذكاء الاصطناعي من التجريب إلى قدرة مؤسسية محكومة وقابلة للقياس."
    },
    "deck": {
      "title": "نظرة تنفيذية — Michael Kofman",
      "description": "Private executive overview للqualified introductions."
    }
  },
  "home": {
    "heroEyebrow": "الموقع الرسمي لـ Michael Kofman",
    "heroTitle1": "مبني ليدوم.",
    "heroTitle2": "قيادة بحكمة.",
    "heroCta": "اكتشف قصتي",
    "heroAlt": "Michael Kofman",
    "quote1text": "من بين الشركات الأمريكية الرائدة في الطب الدقيق والصحة الرقمية.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "رائد الأعمال للعام — تقديراً للقيادة والإنجازات في ابتكار المنصات والبنية التحتية.",
    "quote2author": "Entrepreneur Magazine · 2001",
    "quote3text": "Digital Invest Inc. ضمن أفضل 10 شركات أمريكية في الطب الدقيق والصحة الرقمية.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "دقة هندسية مع استراتيجية أعمال — من أنظمة الأقمار الصناعية إلى بنية تحتية بقيمة",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "تعرف على Michael Kofman",
    "aboutTitle": "شركات مصممة للبقاء",
    "aboutLead1": "الرئيس التنفيذي لـ Digital Invest Inc. ومؤسس AGRON Inc. أسس وقاد شركات في الولايات المتحدة وأوروبا.",
    "aboutLead2": "من 9 Net Avenue (ذروة تقييم",
    "aboutLink": "السيرة الكاملة",
    "expertiseEyebrow": "مجالات التركيز",
    "expertiseTitle": "قيادة تنفيذية عبر الصناعات",
    "expertiseLead": "أربعة عقود في بناء الشركات والاستشارة والاستثمار في البنية التحتية والصحة والروبوتات.",
    "exp1title": "الرئيس التنفيذي والمؤسس",
    "exp1desc": "أسس وقاد عدة شركات تقنية في الولايات المتحدة وأوروبا.",
    "exp1link": "المشاريع ←",
    "exp2title": "مهندس تقني",
    "exp2desc": "صمم اتصالات آمنة ومحركات تحليلات تنبؤية ومنصات تكامل بيانات على المستوى الوطني للقطاعات الحكومية والعسكرية والاتصالات.",
    "exp2link": "المسيرة ←",
    "exp3title": "الصحة الرقمية",
    "exp3desc": "يقود تحويل الطب من خلال الذكاء الاصطناعي والتعلم الآلي وتقنيات الحمض النووي. تعاون مع Harvard Medical School وStanford Biomath في التقارير الجينية.",
    "exp3link": "Digital Invest ←",
    "exp4title": "مستشار مجلس",
    "exp4desc": "يشغل مقاعد في مجالس الإدارة ويقدم المشورة للشركات العامة والخاصة بشأن التوجه الاستراتيجي والحوكمة ومبادرات النمو التقني.",
    "exp4link": "الاستشارات →",
    "stat1": "سنوات القيادة",
    "stat2": "شركات تأسست",
    "stat3": "أقصى قيمة سوقية",
    "stat4": "موظفون",
    "recEyebrow": "التكريم",
    "recTitle": "تكريمات مختارة",
    "recLead": "جوائز صناعية وتقدير من الأقران في ريادة الأعمال والطب والهندسة.",
    "award1title": "رائد أعمال العام",
    "award1desc": "Entrepreneur Magazine · 2001",
    "award2title": "أفضل 10 طب دقيق",
    "award2desc": "Digital Invest Inc. — U.S., 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "التكريم والصحافة →",
    "heroSub": "التكنولوجيا والأعمال والاستثمار في البنية التحتية وعلوم الحياة والأنظمة المستقلة.",
    "primaryCta": "طلب استشارة",
    "secondaryCta": "عرض دراسات الحالة",
    "featuredEyebrow": "ظهر في",
    "caseStudiesEyebrow": "نتائج مثبتة",
    "caseStudiesTitle": "دراسات الحالة",
    "caseStudiesLead": "تأسيس الشركات وتوسيعها وقيادتها من البداية حتى الاستحواذ والطرح العام.",
    "caseStudiesLink": "عرض جميع دراسات الحالة →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "بنى واحدة من أكبر شركات تخزين البيانات في العالم، وتم الاستحواذ عليها عند قيمة سوقية قصوى بلغت 19.5 مليار دولار.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "تأسست وتوسعت من البداية حتى طرح عام أولي ناجح - ضمن أفضل 10 شركات طب دقيق في الولايات المتحدة لعام 2023.",
    "cs3title": "AGRON Inc.",
    "cs3desc": "Founded in 2026 — the AGRON Ecosystem for UAV capability development, geospatial systems, and maritime intelligence.",
    "boardCtaEyebrow": "Advisory",
    "boardCtaTitle": "Experience for the Decisions That Define an Enterprise",
    "boardCtaLead": "Independent perspective for boards and leaders navigating technology, governance, transformation, and growth.",
    "boardCtaBtn": "Explore Advisory",
    "testimonialsEyebrow": "Trusted Perspective",
    "testimonialsTitle": "What Colleagues Value",
    "videoEyebrow": "Executive Perspective",
    "videoTitle": "Leadership at the Intersection of Technology and Enterprise",
    "videoLead": "A concise introduction to the principles, experience, and long-term perspective behind Michael Kofman's work.",
    "videoCta": "Read Leadership Thesis →",
    "heroName": "Michael Kofman",
    "heroRole": "تنفيذي تقني · مؤسس · مستشار",
    "introText": "Michael Kofman تنفيذي تقني ومؤسس شركات. يشمل عمله هندسة الأقمار الصناعية وبنية الإنترنت والشركات التقنية العامة وعلوم الحياة. أسس 9 Net Avenue Inc.، التي استحوذت عليها Concentric Networks عام 2000. CEO لـ Digital Invest Inc. في الطب الرياضي الحيوي والذكاء الجينومي؛ ومؤسس AGRON Inc. في العمليات المستقلة جواً-أرضاً والأنظمة الجيospatiale. يشارك في مجالس الإدارة ويقدم الاستشارات في التكنولوجيا والصحة والبنية التحتية.",
    "introLink": "السيرة الكاملة →",
    "currentEyebrow": "العمل الحالي",
    "currentTitle": "التركيز الحالي",
    "currentDiTitle": "Digital Invest Inc.",
    "currentDiDesc": "الطب الرياضي الحيوي والبيانات الجينومية والذكاء السريري — تطبيق AI وML وتقنيات DNA لنتائج صحية مسؤولة.",
    "currentDiLink": "Ventures →",
    "currentAgTitle": "AGRON Inc.",
    "currentAgDesc": "عمليات مستقلة جواً-أرضاً وتطوير قدرات UAV والأنظمة الجيospatiale والبنية التحتية للاستخبارات البحرية.",
    "currentAgLink": "agron1.com →",
    "careerEyebrow": "سجل مختار",
    "careerTitle": "استمرارية عبر الفترات التقنية",
    "careerLead": "محطات مختارة من الهندسة إلى العمل الحالي في الأنظمة المستقلة.",
    "career1title": "الهندسة والاتصالات",
    "career1desc": "أنظمة transceiver للأقمار الصناعية واتصالات رقمية وقيادة هندسية مبكرة.",
    "career2title": "الإنترنت والبنية التحتية",
    "career2desc": "بنية الإنترنت التحtية ومراكز البيانات والتخزين والاتصالات على نطاق واسع.",
    "career3title": "شركات التكنولوجيا والأسواق العامة",
    "career3desc": "بناء الشركات والاستحواذات وخبرة الشركات العامة بما في ذلك 9 Net Avenue Inc.",
    "career4title": "علوم الحياة وبيانات الإنسان",
    "career4desc": "التكنولوجيا الحيوية والبيانات الجينية والطب الدقيق ومنصات intelligence الصحية.",
    "career5title": "أنظمة مستقلة",
    "career5desc": "روبotics جو-أرض، عمليات UAV وبنية geospatial.",
    "careerLink": "السجل →",
    "perspectivesEyebrow": "وجهات نظر",
    "perspectivesTitle": "كتابات مختارة",
    "perspectivesLink": "جميع الرؤى →",
    "footerHomeDesc": "تنفيذي تقني ومؤسس ومستشار مجالس إدارة.",
    "activeSitesLink": "جميع المواقع النشطة →"
  },
  "about": {
    "eyebrow": "نبذة عن Michael Kofman",
    "title": "ثلاثة عقود من الخبرة",
    "lead": "تنفيذي تقني ومؤسس ومستشار.",
    "glance": "نظرة سريعة",
    "role": "الدور الحالي",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "الموقع",
    "locationVal": "Charlotte, North Carolina",
    "education": "التعليم",
    "educationVal": "دكتوراه في العلوم التقنية\nPh.D. في تكنولوجيا المعلومات\nدرجات ماجستير — إلكترونيات، أنظمة الأقمار الصناعية الرقمية والاقتصاد",
    "university": "الجامعة",
    "universityVal": "الجامعة التقنية البحرية الحكومية الأوكرانية",
    "languages": "اللغات",
    "languagesVal": "الإنجليزية، الروسية، الأوكرانية",
    "contactLabel": "تواصل",
    "principlesEyebrow": "مبادئ تشغيلية",
    "principlesTitle": "كيف أقود",
    "p1title": "فهم النظام",
    "p1text": "قبل تغيير منظمة، افهم حوافزها وهندستها وقيودها ومصادر الثقة.",
    "p2title": "جعل المساءلة صريحة",
    "p2text": "الملكية الواضحة والنتائج القابلة للقياس تحوّل الاستراتيجية من عرض إلى واقع تشغيلي.",
    "p3title": "ترك مؤسسات أقوى",
    "p3text": "يجب أن تضاعف القيادة القدرة بتطوير الأفراد وتحسين القرارات وبناء أنظمة تدوم.",
    "archiveEyebrow": "من الأرشيف",
    "archiveTitle": "من الأرشيف",
    "archiveLead": "مواد أصيلة عن بناء الشركات والبنية التحتية والقيادة.",
    "photo9netTitle": "9 Net Avenue",
    "photo9netCaption": "المؤسس والرئيس التنفيذي — شركة استضافة وبنية تحتية للإنترنت، استحوذت عليها Concentric Networks عام 2000.",
    "photoServerTitle": "بنية البيانات التحتية",
    "photoServerCaption": "بيئات التخزين والشبكات والخوادم في DataPeer والشركات ذات الصلة.",
    "photoTodayTitle": "اليوم",
    "photoTodayCaption": "Digital Invest Inc. وAGRON Inc. وعمل استشاري.",
    "secIntroTitle": "مقدمة",
    "secTechTitle": "التكنولوجيا والبنية التحتية",
    "secBusinessTitle": "أعمال",
    "secCurrentTitle": "العمل الحالي",
    "secBackgroundTitle": "الخلفية",
    "recordLink": "السجل →",
    "secBackgroundP1": "Doctor of Technical Sciences و Ph.D. in Information Technology. مؤلف أوراق تقنية؛ براءة HDTV فضائية acquired by Sony.",
    "bioP1": "Michael Kofman تنفيذي تقني ومؤسس ومستشار. CEO لـ Digital Invest Inc. ومؤسس AGRON Inc.، مع خبرة في هندسة الأقمار الصناعية وبنية الإنترنت والشركات التقنية العامة وعلوم الحياة.",
    "bioP2": "As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. In 2026 he founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network. He also created Digital Invest, dedicated to the bio-mathematical sphere and transforming medicine through science, DNA technologies, AI, and ML.",
    "secBioTitle": "الطب الدقيق والتكنولوجيا الحيوية",
    "secBioP1": "قبل Digital Invest، لعب دوراً بارزاً في نجاح Biotechnology Group Inc. (2008 — 2014)، شركة ملتزمة بفحص وتحليل الحمض النووي، وأتمتة عمليات إنشاء الملفات الجينية، والبحث الجيني البشري الشامل. يؤمن السيد Kofman إيماناً راسخاً بإمكانات الجمع بين علوم الحياة وأحدث التقدم التكنولوجي.",
    "secBioP2": "تحت قيادته، أُطلقت مشاريع ناجحة للفحص الجيني في أوكرانيا وروسيا ودول Baltic. تُثري هذه التجربة الفريدة باستمرار بالتقنيات الحديثة والمعدات الجديدة. بالتعاون مع Harvard Medical School وStanford Biomath، لعب السيد Kofman دوراً حاسماً في تطوير تقارير جينية يسهل فهمها للأطباء والمرضى على حد سواء. وقد اعتُمد هذا النهج المبتكر على نطاق واسع من قبل المختبرات الرائدة في الولايات المتحدة وخارجها.",
    "secTechP1": "خلفية هندسية في أنظمة transceiver للأقمار الصناعية واتصالات رقمية في Astra Corp.",
    "secTechP2": "في 2006، أسس السيد Kofman شركة XIBI Group Inc. — شركة تقنية شغل فيها منصباً في مجلس الإدارة. تتخصص الشركة الأمريكية في خدمات تخزين البيانات وإدارة البيانات الضخمة للمؤسسات التجارية والحكومية الكبرى.",
    "secTechP3": "من 2000 إلى 2004، قاد السيد Kofman شركة DataPeer Inc. — شركة لإدارة وتخزين البيانات تقدم مجموعة واسعة من الخدمات المتعلقة بتخزين المعلومات للشركات الصغيرة والمتوسطة. في DataPeer طوّر حلولاً تقنية فريدة سهلت تتبع المعلومات بشكل أسرع وإتاحة الوصول إلى البيانات بسهولة أكبر للمستخدمين النهائيين والمؤسسات الحكومية حول العالم.",
    "secTechP4": "Founded 9 Net Avenue Inc. in 1996. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "secPost9NetP1": "بعد استحواذ 9 Net Avenue، اكتسب السيد Kofman خبرة واسعة في العمل مع الشركات العامة، والمشاركة في مجالس الإدارة، واتخاذ القرارات الاستراتيجية على أعلى المستويات التنفيذية.",
    "secEarlyTitle": "المسيرة المبكرة والهندسة",
    "secEarlyP1": "من 1994 إلى 1996، شغل السيد Kofman منصب الرئيس التنفيذي ومدير تكنولوجيا المعلومات في Elitan United Inc. — شركة تقنية معلومات من Massachusetts تقدم استراتيجيات شاملة وخدمات تقنية للمؤسسات العالمية الرائدة. لعب دوراً محورياً في تطوير وإدارة بنية تحتية قابلة للتوسع، قائداً نمو الشركة من تسعة موظفين فقط إلى أكثر من 4000 موظف حول العالم.",
    "secEarlyP2": "من 1989 إلى 1994، كان مؤسساً والرئيس التنفيذي لـ Astra Corp، إحدى أكبر الشركات المصنعة لأنظمة أقمار صناعية رقمية للإرسال والاستقبال في أوروبا، حاصلاً على اعتراف دولي في مجال أجهزة الأقمار الصناعية. شملت مسؤولياته البحث وتطوير أنظمة التشغيل وتطبيقات برمجيات الشبكات والاستراتيجية التقنية الشاملة.",
    "secEarlyP3": "من 1984 إلى 1989، عمل السيد Kofman في مصنع بناء السفن في Nikolaev بأوكرانيا، حيث شارك بنشاط في تطوير وإنشاء أنظمة أقمار صناعية للإرسال والاستقبال لنقل المعلومات المصنفة إلى السفن العسكرية والعكس. اُعترف به كمهندس إلكترونيات من أعلى المستويات، حاصلاً على الفئة السادسة — أرفع تكريم في المصنع الذي يضم 93 ألف موظف.",
    "secResearchTitle": "البحث وبراءات الاختراع",
    "secResearchP1": "Michael Kofman مؤلف أوراق تقنية تركز على أنظمة الأقمار الصناعية والبصرية لنقل البيانات. كما حصل على براءة اختراع في مجال أنظمة التلفزيون عالي الوضوح (HDTV) عبر الأقمار الصناعية الرقمية، التي استحوذت عليها لاحقاً Sony.",
    "secAgronTitle": "Robotics, UAV & Maritime Intelligence",
    "secAgronP1": "In 2026, Mr. Kofman founded AGRON Inc. to build the AGRON Ecosystem — a corporate operating architecture for aerial and ground robotics, governed mission execution, and network infrastructure connecting teams, assets, and operational data. The ecosystem delivers consulting, assessment, capability development, and training for UAV and Counter-UAS organizations, alongside maritime intelligence and security services at agron1.com.",
    "secBusinessP1": "أسس وقاد عدة شركات تقنية. السجل الكامل في The Record.",
    "secCurrentP1": "CEO لـ Digital Invest Inc. في الطب الرياضي الحيوي والذكاء الجينومي. مؤسس AGRON Inc. في العمليات المستقلة جواً-أرضاً."
  },
  "ventures": {
    "eyebrow": "محفظة المشاريع",
    "title": "شركات أسستها وقادها",
    "lead": "من الطب الدقيق والروبوتات إلى البنية التحتية العالمية للبيانات — تأسيس وتوسيع وقيادة في الولايات المتحدة وأوروبا.",
    "ecosystemEyebrow": "Venture Ecosystem",
    "ecosystemTitle": "Companies Across Technology Frontiers",
    "ecosystemLead": "A portfolio shaped by recurring themes: trusted data, intelligent infrastructure, human health, and systems built for scale.",
    "statusActive": "نشط",
    "statusExited": "خروج",
    "statusLegacy": "إرث",
    "v1lesson": "الدرس: تفوز البنية التحتية عندما تتحسن الموثوقية والاقتصاد وثقة العملاء معاً.",
    "v2lesson": "الدرس: يتطلب الطب الدقيق انضباطاً متساوياً في العلم والبرمجيات والخصوصية والفائدة السريرية.",
    "v3lesson": "الدرس: تخلق الاستقلالية قيمة فقط عندما يشكل الاستشعار والاتصالات والإشراف البشري نظاماً واحداً مرناً.",
    "v5lesson": "الدرس: نمو البنية التحتية يُبنى بالتميز التشغيلي قبل الخروج بكثير.",
    "currentEyebrow": "حالي",
    "historyEyebrow": "تاريخ مختار",
    "v2highlight": "Harvard Medical School و Stanford Biomath — تعاون في التقارير الجينية",
    "activeSitesEyebrow": "مشاريع نشطة",
    "activeSitesTitle": "مواقع نشطة",
    "activeSitesLead": "مواقع حية للشركات الحالية ومبادرات المحفظة.",
    "activeSitesMeta": "10 مواقع نشطة · انقر على أي بطاقة للزيارة",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — an Aerial-Ground Robotics Operations Network spanning UAV and Counter-UAS consulting, technology assessment, capability development, training infrastructure, product validation, geospatial systems (ISDRI), and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "v0role": "Founder",
    "v0year": "2026 — Present",
    "v2role": "الرئيس التنفيذي والمدير التقني",
    "v2year": "2008 — 2014",
    "v3year": "2006 — 2011",
    "v4year": "2000 — 2004",
    "v5highlight": "Acquired · Concentric Networks, 2000",
    "v5p1": "Founded and led a hosting and internet infrastructure company. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "v5year": "1996 — 2000",
    "v6year": "1994 — 1996",
    "v7year": "1989 — 1994",
    "v8year": "1984 — 1989",
    "v1highlight": "من أفضل 10 شركات أمريكية في الطب الدقيق — 2023",
    "v1p1": "طب biomathematical وبيانات genomics وذكاء clínico — AI وML وتقنيات DNA في سير العمل clínico والبحثي.",
    "v1role": "المؤسس والرئيس التنفيذي · عضو مجلس الإدارة",
    "v1year": "2021 — حتى الآن",
    "v2p1": "فحص وتحليل الحمض النووي، وأتمتة الملفات الجينية، والبحث الجيني البشري الشامل. أطلق مشاريع فحص جيني في أوكرانيا وروسيا ودول Baltic.",
    "v2p2": "تعاون مع Harvard Medical School وStanford Biomath في تقارير جينية اعتمدتها المختبرات الرائدة حول العالم.",
    "v3highlight": "حلول بيانات للمؤسسات والحكومة",
    "v3p1": "خدمات تخزين البيانات وإدارة البيانات الضخمة للمؤسسات التجارية والحكومية الكبرى. رسّخ الشركة كمزود موثوق لحلول البيانات المؤسسية.",
    "v3role": "المؤسس والرئيس التنفيذي · مجلس الإدارة",
    "v4highlight": "منصة عالمية لإدارة البيانات",
    "v4p1": "إدارة وتخزين البيانات للشركات الصغيرة والمتوسطة. طوّر حلولاً لتتبع أسرع للمعلومات وإتاحة أسهل للبيانات للمستخدمين النهائيين والمؤسسات الحكومية حول العالم.",
    "v4role": "المؤسس والرئيس التنفيذي",
    "v5role": "المؤسس والرئيس التنفيذي",
    "v6highlight": "استراتيجية تقنية المعلومات والبنية التحتية العالمية",
    "v6p1": "شركة تقنية معلومات من Massachusetts تقدم استراتيجيات شاملة وخدمات تقنية للمؤسسات العالمية الرائدة. قاد تطوير البنية التحتية القابلة للتوسع وعمليات تقنية المعلومات العالمية.",
    "v6role": "الرئيس التنفيذي ومدير تكنولوجيا المعلومات",
    "v7highlight": "رائد أوروبي في أنظمة الأقمار الصناعية",
    "v7p1": "إحدى أكبر الشركات المصنعة لأنظمة أقمار صناعية رقمية للإرسال والاستقبال في أوروبا. قاد البحث وتطوير أنظمة التشغيل وتطبيقات برمجيات الشبكات والاستراتيجية التقنية الشاملة.",
    "v7role": "المؤسس والرئيس التنفيذي",
    "v8highlight": "هندسة أنظمة أقمار صناعية عسكرية",
    "v8p1": "تطوير وإنشاء أنظمة أقمار صناعية للإرسال والاستقبال لنقل المعلومات المصنفة إلى السفن العسكرية. اُعترف به كمهندس إلكترونيات من أعلى المستويات في مصنع يضم 93,000 موظف.",
    "v8role": "مهندس إلكترونيات · أعلى فئة (السادسة)",
    "v1p2": "مبادرات المحفظة تشمل <a href=\"https://biomathlife.com\" target=\"_blank\" rel=\"noopener\">BioMath Life</a> و<a href=\"https://www.biomathcore.com\" target=\"_blank\" rel=\"noopener\">BioMath Core</a> و<a href=\"https://www.type1and2.com\" target=\"_blank\" rel=\"noopener\">Type 1 &amp; 2</a> و<a href=\"https://www.luna29.com\" target=\"_blank\" rel=\"noopener\">Luna29</a> — دراسات حالة مفصلة قريباً.",
    "v1brole": "الرئيس التنفيذي",
    "v1bp1": "فترة انتقالية بين العمل في التكنولوجيا الحيوية وتطوير تقنيات جديدة — بناء خبرة تشغيلية وبحث وتطوير قبل Digital Invest Inc.",
    "v1byear": "2014 — 2020"
  },
  "career": {
    "eyebrow": "المسيرة المهنية",
    "title": "السجل",
    "lead": "التكنولوجيا والشركات والخبرة التشغيلية عبر فترات متتالية من التغير التكنولوجي.",
    "timelineEyebrow": "الجدول الزمني",
    "timelineTitle": "محطات رئيسية",
    "strengthsEyebrow": "نقاط القوة",
    "strengthsTitle": "مجالات الخبرة",
    "filterAll": "All",
    "filterHealthcare": "Healthcare",
    "filterInfrastructure": "Infrastructure",
    "filterDefense": "Defense",
    "filterTelecom": "Telecommunications",
    "periodCurrent": "أنظمة مستقلة",
    "periodCurrentLead": "الذكاء الاصطناعي والروبotics والعمليات المستقلة والأنظمة الج geospatial والبنية التحتية الحالية ذات الصلة.",
    "period1title": "الهندسة والاتصالات",
    "period1lead": "الهندسة المبكرة وأنظمة الأقمار الصناعية والاتصالات والعمل التقني ذي الصلة.",
    "period2title": "الإنترنت والبنية التحتية",
    "period2lead": "بنية الإنترنت التحتية والاتصالات ومراكز البيانات والتخزين والشركات ذات الصلة.",
    "period3title": "الشركات والأسواق العامة",
    "period3lead": "بناء الشركات والمعاملات والمشاركة في الشركات العامة والأدوار التنفيذية.",
    "period4title": "علوم الحياة وبيانات الإنسان",
    "period4lead": "التكنولوجيا الحيوية وتكنولوجيا الصحة والبيانات والطب الدقيق.",
    "period5title": "برامج حكومية ودفاعية",
    "period5lead": "استراتيجية وتقديم التكنولوجيا لبرامج الحكومة والدفاع والمؤسسات المملوكة للدولة.",
    "t1desc": "Digital Invest Inc.، تأسست 2021. طب biomathematical وبيانات genomics ومنصات clínico. Healthcare Tech Outlook (2023).",
    "t0desc": "Founded AGRON Inc. to build the AGRON Ecosystem — consulting, assessment, capability development, training infrastructure, and product support for UAV and Counter-UAS programmes, plus AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure. Connects aerial and ground robotics, governed mission execution, and network infrastructure linking teams, assets, and operational data.",
    "t0role": "Founder",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — Present",
    "t10title": "Nikolaev Shipbuilding Plant",
    "t10year": "1984 — 1989",
    "t1title": "Digital Invest Inc.",
    "t2year": "2001 — 2019",
    "t3role": "الرئيس التنفيذي والمدير التقني",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4year": "2000 — 2012",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "Founded and led 9 Net Avenue Inc., a hosting and internet infrastructure company. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994",
    "t10desc": "طوّر وأنشأ أنظمة أقمار صناعية للإرسال والاستقبال لنقل المعلومات المصنفة إلى السفن العسكرية. اُعترف به كمهندس إلكترونيات من أعلى المستويات في مصنع يضم 93,000 موظف — بداية مسيرة متميزة في التكنولوجيا والابتكار.",
    "t10role": "مهندس إلكترونيات — الفئة السادسة (الأعلى)",
    "t1role": "المؤسس والرئيس التنفيذي",
    "t1year": "2021 — حتى الآن",
    "t2desc": "وجّه الاستراتيجية التكنولوجية وتسليمها لبرامج سرية وعالية الحساسية تشمل وكالات حكومية أمريكية وأنظمة دفاعية للحلفاء ومؤسسات مملوكة للدولة. ترأس مشاريع تقنية معقدة للشركات المملوكة للحكومة عبر قطاعات متعددة. بعد 11 سبتمبر 2001، قاد مبادرات حكومية واسعة النطاق تركز على البيانات الضخمة والاتصالات الآمنة والتحليلات التنبؤية وتكامل البيانات على المستوى الوطني — بما في ذلك تصميم وبناء وتشغيل مراكز بيانات عالية الإنتاجية في الولايات المتحدة وأوروبا. تواصل مع ضباط البرامج العسكرية وموردي التكنولوجيا والجهات التنظيمية.",
    "t2role": "كبير المستشارين التقنيين / مهندس البرامج",
    "t2title": "GovTech والدفاع والبرامج الحكومية",
    "t3desc": "قاد فحص وتحليل الحمض النووي، وأتمتة الملفات الجينية، والبحث الجيني البشري الشامل. أطلق مشاريع فحص جيني في أوكرانيا وروسيا ودول Baltic. تعاون مع Harvard Medical School وStanford Biomath لتطوير تقارير جينية يسهل فهمها اعتمدتها المختبرات الرائدة حول العالم.",
    "t4desc": "وجّه عمليات نشر البنية التحتية الوطنية في كندا وإيطاليا وسويسرا وأوكرانيا وجمهوريات Baltic. أشرف على أكثر من 1000 مهندس وموظف نشر في عمليات الاتصالات بما في ذلك أنظمة التبديل وتوسيع النطاق العريض والاتصال عبر الحدود. نفّذ أنظمة أساسية لتكرار الشبكة وتحسين وقت التشغيل والتوجيه الذكي.",
    "t4role": "نائب رئيس التكنولوجيا / المدير التقني الإقليمي — أوروبا الشرقية ورابطة الدول المستقلة",
    "t4title": "مشاريع الاتصالات",
    "t5desc": "أسس شركة تقنية متخصصة في تخزين البيانات وإدارة البيانات الضخمة للمؤسسات التجارية والحكومية الكبرى. رسّخ الشركة كمزود موثوق لحلول البيانات المؤسسية.",
    "t5role": "المؤسس والرئيس التنفيذي · مجلس الإدارة",
    "t6desc": "أسس شركة لإدارة وتخزين البيانات للشركات الصغيرة والمتوسطة. طوّر حلولاً تقنية فريدة لتتبع أسرع للمعلومات وإتاحة أسهل للبيانات للمستخدمين النهائيين والمؤسسات الحكومية حول العالم.",
    "t6role": "المؤسس والرئيس التنفيذي",
    "t7role": "المؤسس والرئيس التنفيذي",
    "t8desc": "قاد استراتيجيات تقنية المعلومات الشاملة والخدمات التقنية للمؤسسات العالمية الرائدة من Massachusetts خلال فترة توسع سريع، وبنى بنية تحتية قابلة للتوسع وعمليات تقنية معلومات عالمية.",
    "t8role": "الرئيس التنفيذي ومدير تكنولوجيا المعلومات",
    "t9desc": "أسس إحدى أكبر الشركات المصنعة لأنظمة أقمار صناعية رقمية للإرسال والاستقبال في أوروبا. قاد البحث وتطوير أنظمة التشغيل وتطبيقات برمجيات الشبكات والاستراتيجية التقنية الشاملة، حاصلاً على اعتراف دولي.",
    "t9role": "المؤسس والرئيس التنفيذي",
    "t1bdesc": "فترة انتقالية بين العمل في التكنولوجيا الحيوية وتطوير تقنيات جديدة — بناء خبرة تشغيلية وبحث وتطوير قبل Digital Invest Inc.",
    "t1brole": "الرئيس التنفيذي",
    "t1byear": "2014 — 2020"
  },
  "recognition": {
    "eyebrow": "الجوائز",
    "title": "الجوائز والتقدير",
    "lead": "تكريم في ريادة الأعمال والطب الدقيق والهندسة والقيادة التنفيذية.",
    "industryEyebrow": "جوائز الصناعة",
    "industryTitle": "تكريمات كبرى",
    "ipEyebrow": "الملكية الفكرية",
    "ipTitle": "براءات ومنشورات",
    "eduEyebrow": "التعليم",
    "eduTitle": "المؤهلات الأكاديمية",
    "pressEyebrow": "الصحافة",
    "pressTitle": "ظهر في",
    "moreLink": "اطّلع على براءات الاختراع والمنشورات والتغطية الإعلامية في Insights →",
    "a1desc": "Entrepreneur Magazine · 2001",
    "a3title": "Who's Who in America",
    "a4title": "Who's Who in the World",
    "a5title": "Who's Who in Science & Engineering",
    "ip1year": "براءة اختراع",
    "ip2year": "منشورات",
    "press1role": "تقرير عن Digital Invest Inc.",
    "press1title": "Healthcare Tech Outlook",
    "press2title": "Top Precision Medicine Solutions",
    "a1title": "رائد الأعمال للعام",
    "a2title": "من أفضل 10 شركات أمريكية في الطب الدقيق",
    "a2desc": "Digital Invest Inc. معترف بها بين أفضل 10 شركات أمريكية في الطب الدقيق والصحة الرقمية — 2023.",
    "a3desc": "مُدرج، 1999 — 2018 — لإنجازات استثنائية في إنشاء وتطوير الأعمال.",
    "a4desc": "مُدرج، 2000 — 2004 — بين القادة العالميين في العلوم والهندسة وابتكار الأعمال.",
    "a5desc": "مُدرج، 2000 — 2014 — لمساهماته في التكنولوجيا وأنظمة الأقمار الصناعية والبنية التحتية الرقمية.",
    "a6title": "مهندس إلكترونيات — الفئة السادسة",
    "a6desc": "أرفع تكريم في Nikolaev Shipbuilding Plant (93,000 موظف) لهندسة أنظمة أقمار صناعية للإرسال والاستقبال.",
    "ip1title": "أنظمة HDTV عبر الأقمار الصناعية الرقمية",
    "ip1role": "استحوذت عليها لاحقاً Sony",
    "ip1desc": "براءة في أنظمة HDTV فضائية رقمية، استحوذت عليها Sony Corporation.",
    "ip2title": "أوراق تقنية",
    "ip2role": "أنظمة الأقمار الصناعية والبصرية",
    "ip2desc": "مؤلف أوراق تقنية تركز على أنظمة الأقمار الصناعية والبصرية لنقل البيانات. تشمل مساهماته البحثية معالجة الإشارات ونمذجة المحاكاة ومنصات الأتمتة المطبقة في الاتصالات والبنية التحتية الوطنية والصحة الرقمية.",
    "ip3year": "بحث",
    "ip3title": "تعاون دولي",
    "ip3role": "الولايات المتحدة وأوروبا",
    "ip3desc": "شارك في تعاون بحثي دولي ومبادرات نقل المعرفة. طوّر أنظمة هندسية مدمجة لجمع البيانات والتشخيص التنبؤي والتنسيق السحابي عبر صناعات متعددة.",
    "edu1title": "دكتوراه في العلوم التقنية",
    "edu2title": "دكتوراه في تكنولوجيا المعلومات",
    "edu3title": "درجات الماجستير",
    "edu3desc": "الإلكترونيات وأنظمة الأقمار الصناعية الرقمية والاقتصاد",
    "press1desc": "Healthcare Tech Outlook عن Digital Invest Inc. (2023).",
    "press1link": "قراءة التقرير ←",
    "press2role": "اعتراف صناعي",
    "press2desc": "مُدرجة بين أفضل شركات حلول الطب الدقيق، مسلطة الضوء على دور Digital Invest في تطوير المناهج البيو-رياضية للرعاية الصحية الحديثة.",
    "press2link": "عرض القائمة ←"
  },
  "contact": {
    "eyebrow": "تواصل",
    "title": "تواصل",
    "lead": "للاستشارات ومجالس الإدارة والشراكات الاستراتيجية.",
    "infoTitle": "تواصل مباشر",
    "email": "البريد الإلكتروني",
    "phone": "الهاتف",
    "location": "الموقع",
    "locationVal": "Charlotte, North Carolina\nالولايات المتحدة",
    "linkedin": "LinkedIn",
    "company": "الشركة الحالية",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member\nAGRON Inc.\nالمؤسس",
    "formTitle": "إرسال رسالة",
    "formLead": "املأ النموذج وسأرد قريباً.",
    "firstName": "الاسم الأول",
    "lastName": "اسم العائلة",
    "emailLabel": "البريد الإلكتروني",
    "subject": "الموضوع",
    "message": "رسالة",
    "inquiryType": "نوع الاستفسار",
    "inquiryAdvisory": "استشارات",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "calendlyEyebrow": "جدولة محادثة",
    "calendlyTitle": "اختر وقتاً مناسباً",
    "calendlyLead": "للاستفسارات الم calificada عن مجلس الإدارة والاستشارات والمحاضرات والشراكات الاستراتيجية.",
    "calendlyPlaceholder": "سيظهر تقويم المواعيد هنا.",
    "calendlyCta": "فتح تقويم المواعيد",
    "inquiryBusiness": "أعمال",
    "infoEyebrow": "معلومات الاتصال"
  },
  "consulting": {
    "eyebrow": "خدمات استشارية",
    "title": "الاستشارات",
    "heroEyebrow": "التوجيه الاستراتيجي للأعمال",
    "heroTitle": "استشارات استراتيجية",
    "heroLead": "خمس وثلاثون سنة في تأسيس الشركات والاستشارة في الولايات المتحدة وأوروبا — البنية التحتية للبيانات والحكومة الرقمية والطب الدقيق والروبوتات.",
    "cta": "التواصل مع Michael Kofman",
    "introLead": "الرئيس التنفيذي لـ Digital Invest Inc. وعضو مجلس الإدارة. التركيز: التقنيات الناشئة والأمن والبحث وتخصيص رأس المال.",
    "specialtiesEyebrow": "مجالات التركيز",
    "specialtiesTitle": "تخصصات Michael Kofman",
    "area1title": "خدمة مجلس الإدارة",
    "area1desc": "عمل مستقل في مجالس الإدارة على استراتيجية التكنولوجيا والحوكمة المؤسسية والإشراف في مراحل النمو.",
    "area2title": "استشارات CEOs والمؤسسين",
    "area2desc": "استراتيجية الشركات والتكنولوجيا والتطوير التنظيمي والمعاملات وخبرة أسواق رأس المال.",
    "area3title": "العناية الواجبة التقنية",
    "area3desc": "تقييم البنية التحتية ومنصات البيانات وهندسة الأمن والتكنولوجيا التطبيقية بناءً على خبرة تشغيلية موثقة.",
    "redirectLead": "العمل الاستشاري الاستراتيجي موثق في صفحة Advisory. للاستفسارات المهنية، استخدم Contact.",
    "redirectLink": "استشارات →"
  },
  "insights": {
    "eyebrow": "وجهات نظر",
    "title": "رؤى",
    "heroTitle": "وجهات نظر تنفيذية",
    "selectedEyebrow": "أبرز المحتوى",
    "selectedTitle": "تقدير مميز",
    "allPressTitle": "جميع التغطيات الصحفية",
    "quotesEyebrow": "في الإعلام",
    "quotesTitle": "تقدير صناعي واقتباسات",
    "articlesEyebrow": "وجهات نظر",
    "articlesTitle": "رؤى تنفيذية",
    "briefsEyebrow": "ملخصات تنفيذية",
    "briefsTitle": "أفكار للقادة",
    "briefsLead": "Perspectives قصيرة وعملية عن governance والتكنولogia والرعاية الصحية وبناء الشركات.",
    "brief1title": "ما يغيره الاكتتاب العام",
    "brief1desc": "انضباط التشغيل والحوكمة الذي تتطلبه readiness للأسواق العامة.",
    "brief1tag": "أسواق رأس المال",
    "brief2title": "من البيانات الجينية إلى القرارات السريرية",
    "brief2desc": "كيفية بناء ذكاء صحي مفيد دون تجاوز الأدلة أو الثقة.",
    "brief2tag": "الطب الدقيق",
    "brief3title": "استراتيجية الذكاء الاصطناعي وساء التجريبي",
    "brief3desc": "إطار لتحويل experiments إلى governed enterprise capability.",
    "brief3tag": "الذكاء الاصطناعي",
    "readingEyebrow": "قائمة القراءة",
    "readingTitle": "كتب تشكّل التفكير الاستراتيجي",
    "r1title": "The Innovator's Dilemma",
    "r1author": "Clayton M. Christensen",
    "r2title": "Thinking, Fast and Slow",
    "r2author": "Daniel Kahneman",
    "r3title": "The Beginning of Infinity",
    "r3author": "David Deutsch",
    "r4title": "Good Strategy/Bad Strategy",
    "r4author": "Richard Rumelt",
    "r5title": "The Structure of Scientific Revolutions",
    "r5author": "Thomas S. Kuhn",
    "newsletterEyebrow": "ملاحظات متفرقة",
    "newsletterTitle": "منظور تنفيذي بلا ضجيج",
    "newsletterLead": "Periodic essays وbrief observations عن technology وgovernance وبناء شركات durable.",
    "newsletterCta": "اشترك في التحديثات",
    "lead": "كتابة substantive وexecutive briefs.",
    "relatedLead": "Recognition وpress coverage وpatents documented separately.",
    "topicsLead": "تعتمد الموضوعات على خبرة تشغيلية موثقة في التكنولوجيا والصحة والبنية التحتية."
  },
  "cta": {
    "eyebrow": "لنعمل معًا",
    "title": "طلب استشارة أو دعوة للتحدث",
    "lead": "للأدوار الاستشارية، ومناصب مجالس الإدارة، والفعاليات الخطابية، والشراكات الاستراتيجية.",
    "button": "تواصل الآن"
  },
  "speaking": {
    "eyebrow": "المشاركات الخطابية",
    "title": "ادعُ Michael Kofman للتحدث",
    "lead": "متاح للمحاضرات حول القيادة التنفيذية، واستراتيجية التكنولوجيا، والصحة الرقمية، وبنية البيانات، وحوكمة الشركات.",
    "topicsEyebrow": "موضوعات التحدث",
    "topicsTitle": "مجالات الخبرة",
    "topicsLead": "تعتمد الموضوعات على عقود من الخبرة في تأسيس وقيادة شركات في الولايات المتحدة وأوروبا.",
    "processEyebrow": "كيفية الدعوة",
    "processTitle": "خطوات الحجز",
    "process1title": "أرسل استفسارًا",
    "process1desc": "استخدم نموذج التواصل أو راسل mkofman@mkofman.com مع تفاصيل الحدث والجمهور والموضوعات المفضلة.",
    "process2title": "تأكيد النطاق",
    "process2desc": "تحديد الصيغة (كلمة رئيسية، أو جلسة نقاش، أو جلسة مجلس إدارة، أو مائدة مستديرة تنفيذية) واللوجستيات.",
    "process3title": "تحقيق قيمة عملية",
    "process3desc": "ترتكز العروض على نتائج فعلية من مشاريع في تخزين البيانات وgovtech والطب الدقيق.",
    "cta": "طلب مشاركة خطابية",
    "catalogEyebrow": "موضوعات المحاضرات",
    "catalogTitle": "محادثات تنفيذية من أجل تغيير جوهري",
    "catalogLead": "محاضرات رئيسية وجلسات مجلس إدارة و briefings قيادية م adapted للجمهور والقطاع وسياق القرار.",
    "t1title": "حوكمة الذكاء الاصطناعي قبل أن يحكم المؤسسة",
    "t1audience": "مجالس الإدارة ولجان التدقيق والمخاطر",
    "t1format": "briefing لمجلس الإدارة أو keynote",
    "t2title": "من trend التكنولوجيا إلى استراتيجية المؤسسة",
    "t2audience": "CEOs وفرق تنفيذية ومستثمرون",
    "t2format": "keynote أو workshop تنفيذي",
    "t3title": "بناء الشركات عبر دورات السوق",
    "t3audience": "مؤسسون وقادة نمو وprivate equity",
    "t3format": "fireside chat أو keynote",
    "t4title": "الطب الدقيق: الوعد والدليل والمسؤولية",
    "t4audience": "قادة الرعاية الصحية وclinicians وinnovators",
    "t4format": "keynote صناعي أو panel",
    "t5title": "دور مجلس الإدارة في مخاطر السيبر والتكنولوجيا",
    "t5audience": "directors وgeneral counsel وقادة مخاطر",
    "t5format": "جلسة تثقيف لمجلس الإدارة",
    "t6title": "هندسة الثقة في البنية التحتية الرقمية",
    "t6audience": "منظمات التكنولوجيا والبنية التحتية",
    "t6format": "keynote تقني-تنفيذي",
    "t7title": "القيادة عبر الحدود والتخصصات",
    "t7audience": "فرق قيادة عالمية وجامعات",
    "t7format": "keynote أو محادثة moderated",
    "t8title": "من مؤسس إلى باني مؤسسة",
    "t8audience": "رواد أعمال وتنفيذيون من الجيل التالي",
    "t8format": "workshop أو fireside chat"
  },
  "caseStudies": {
    "eyebrow": "دراسات الحالة",
    "title": "بناء شركات قابلة للتوسع",
    "lead": "نتائج مختارة من تأسيس وقيادة شركات في البنية التحتية للبيانات والصحة الرقمية.",
    "cs1eyebrow": "بنية البيانات التحتية · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "التحدي",
    "cs1challengeText": "بناء شركة تخزين بيانات وتوسيعها في سوق تقني سريع الاندماج.",
    "cs1action": "النهج",
    "cs1actionText": "أسس Michael Kofman شركة 9 Net Avenue Inc. عام 1996. وسرعان ما أصبحت واحدة من أكبر شركات تخزين البيانات في العالم.",
    "cs1result": "النتيجة",
    "cs1resultText": "استحوذت عليها Concentric Networks (NASDAQ: CNTX) عام 2000؛ ثم أصبحت جزءاً من XO Communications (NASDAQ: XOXO). واصل العمل مع الشركات العامة والأدوار على مستوى مجلس الإدارة بعد الصفقة.",
    "cs2eyebrow": "الصحة الرقمية · 2021 — حتى الآن",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "التحدي",
    "cs2challengeText": "تحويل الأساليب الطبية القديمة عبر العلوم وتقنيات الحمض النووي وAI وML من خلال منصة بيولوجية رياضية جديدة.",
    "cs2action": "النهج",
    "cs2actionText": "تأسست Digital Invest Inc. عام 2021. الطب biomathematical والذكاء genomics ومنصات البيانات clínico.",
    "cs2result": "النتيجة",
    "cs2resultText": "تحقق نمو مالي متسق، ما وضع الشركة ضمن أفضل 10 شركات طب دقيق في الولايات المتحدة (2023). وتضم Digital Invest مشاريع ابتكارية مثل Human Digital Model وBioMath Life وAero-Ground Robotics Operations Network.",
    "cs3eyebrow": "الروبotics وUAV · 2026 — الحاضر",
    "cs3title": "AGRON Inc.",
    "cs3challenge": "التحدي",
    "cs3challengeText": "المنظمات التي تبني قدرات UAV وCounter-UAS تحتاج تقييماً مستقلاً وتدريباً منظماً وبنية تشغيلية — لا منصات معزولة أو piloting ad hoc.",
    "cs3action": "النهج",
    "cs3actionText": "أسس AGRON Inc. عام 2026 لقيادة AGRON Ecosystem — استشارات وتقييم وتطوير قدرات وبنية تدريب ودعم تطوير المنتجات وأنظمة geospatial عبر ISDRI وAGRON Maritime Intelligence + Security لليachts والmarinas والبنية البحرية الخاصة.",
    "cs3result": "النتيجة",
    "cs3resultText": "نظام بيئي متصل للخدمات المهنية يشمل الاستشارات وتطوير القدرات والبنية التدريبية والأنظمة الجغرافية المكانية والاستخبارات البحرية عبر AGRON وISDRI والشركات ذات الصلة.",
    "caseStudiesLead": "تأسيس وتوسيع وقيادة شركات من المراحل المبكرة حتى الاستحواذ."
  },
  "mediaKit": {
    "eyebrow": "الصحافة والفعاليات",
    "title": "الحقيبة الإعلامية",
    "lead": "سير رسمية، وصور معتمدة، وبيانات تواصل للصحافة والمؤتمرات واستفسارات مجالس الإدارة.",
    "bioEyebrow": "سير ذاتية",
    "bioTitle": "السير الرسمية",
    "bioShortLabel": "50 كلمة",
    "bioShort": "Michael Kofman هو CEO لشركة Digital Invest Inc. وعضو مجلس إدارة ومستشار ومؤسس لشركات في التكنولوجيا والصحة الرقمية عبر الولايات المتحدة وأوروبا.",
    "bioMediumLabel": "150 كلمة",
    "bioMedium": "Michael Kofman هو CEO لشركة Digital Invest Inc. وعضو في Board of Directors. ويُعد صاحب رؤية تقنية معروفًا بنهجه الديناميكي في فهم متطلبات السوق المعقدة والمتغيرة باستمرار. وبصفته رائد أعمال وعضو مجلس إدارة ومستشارًا لشركات عامة وخاصة، نجح في تأسيس عدة شركات في الولايات المتحدة وأوروبا. وتشمل خبرته القيادة التنفيذية، والتحليل الاستراتيجي للتقنيات والأسواق الناشئة، وأمن المعلومات والخصوصية، والبحث العلمي والتطوير، والإدارة، والاستثمار.",
    "bioLongLabel": "500 كلمة",
    "bioLong": "Michael Kofman CEO لـ Digital Invest Inc. وعضو مجلس إدارتها. أسس 9 Net Avenue Inc.، acquired by Concentric Networks 2000، ويقود Digital Invest في biomathematical medicine وgenomic intelligence. أسس AGRON Inc. 2026 لـ autonomous aerial-ground operations وgeospatial systems. Author technical papers؛ patent digital satellite HDTV acquired Sony.",
    "photosEyebrow": "الصور",
    "photosTitle": "صور معتمدة",
    "photosLead": "تتوفر صور شخصية عالية الدقة عند الطلب عبر mkofman@mkofman.com.",
    "contactEyebrow": "تواصل إعلامي",
    "contactTitle": "استفسارات الصحافة",
    "contactLead": "للمقابلات والدعوات الخطابية والطلبات الإعلامية.",
    "downloadEyebrow": "تنزيل",
    "downloadTitle": "حزمة إعلامية من صفحة واحدة",
    "downloadLead": "PDF يتضمن سيراً ذاتية رسمية وصورة شخصية وجهة اتصال إعلامية — جاهز للمشاركة مع المنظمين والصحفيين.",
    "downloadCta": "تنزيل PDF",
    "brandEyebrow": "أصول العلامة التجارية",
    "brandTitle": "الهوية والاستخدام",
    "brandLead": "Approved visual assets للeditorial وconference وpartner use.",
    "brandColors": "لوحة الألوان الرسمية",
    "brandLogo": "الشعار الأساسي",
    "brandDownload": "تنزيل أصول العلامة التجارية"
  },
  "articles": {
    "backLink": "← العودة إلى Insights",
    "article1date": "منظور تنفيذي",
    "article1title": "من الهندسة إلى البنية التحتية العالمية للبيانات",
    "article1p1": "بدأت مسيرتي في مصنع نيكولايف لبناء السفن في أوكرانيا، حيث طورت أنظمة إرسال واستقبال عبر الأقمار الصناعية لنقل معلومات سرية إلى السفن العسكرية. وتم الاعتراف بي كمهندس إلكترونيات من أعلى مستوى - الفئة السادسة - في مصنع يضم 93,000 موظف.",
    "article1p2": "من 1989 إلى 1994، أسست وقادت Astra Corp، إحدى أكبر الشركات الأوروبية المصنعة لأنظمة الإرسال والاستقبال الفضائية الرقمية. ومن 1994 إلى 1996، وبصفتي CEO لشركة Elitan United Inc.، ساعدت في توسيع الشركة من تسعة موظفين إلى أكثر من 4,000 موظف حول العالم.",
    "article1p3": "في عام 1996، أسست 9 Net Avenue Inc.، شركة استضافة وبنية تحتية للإنترنت. في عام 2000 استحوذت عليها Concentric Networks (NASDAQ: CNTX) وأصبحت لاحقاً جزءاً من XO Communications (NASDAQ: XOXO).",
    "article1p4": "بين 2001 و2019، قدت استراتيجية التكنولوجيا لبرامج حكومية ودفاعية وبرامج الشركات المملوكة للدولة، وقادت مبادرات واسعة في البيانات الضخمة والبنية التحتية الآمنة ومراكز البيانات عالية الإنتاجية عبر الولايات المتحدة وأوروبا.",
    "article2date": "الصحة الرقمية",
    "article2title": "الطب الدقيق وتقاطع العلم مع التكنولوجيا",
    "article2p1": "أنا مؤمن بقوة بإمكانات الجمع بين علوم الحياة وأحدث التطورات التقنية. في Biotechnology Group Inc. (2008-2014)، ركزنا على اختبارات وتحليل الحمض النووي، وأتمتة عمليات إعداد الملفات الجينية، والبحث الجيني البشري الشامل.",
    "article2p2": "تحت قيادتي، انطلقت مشاريع ناجحة للاختبارات الجينية في أوكرانيا وروسيا ودول البلطيق. وبالتعاون مع Harvard Medical School وStanford Biomath، لعبت دورًا محوريًا في تطوير تقارير جينية واضحة وسهلة الفهم للأطباء والمرضى.",
    "article2p3": "مع Digital Invest Inc.، تأسست 2021، نعمل في الطب biomathematical — علم وتقنيات DNA وAI وML في الذكاء clínico. Healthcare Tech Outlook (2023).",
    "article2p4": "تضم Digital Invest مشاريع ابتكارية متعددة، منها Human Digital Model وBioMath Life وAero-Ground Robotics Operations Network، وكل مشروع يدفع تكامل علوم البيانات مع علوم الحياة."
  },
  "privacy": {
    "eyebrow": "قانوني",
    "title": "سياسة الخصوصية",
    "lead": "كيف يتعامل mkofman.com مع المعلومات عند زيارة الموقع أو إرسال رسالة.",
    "updated": "آخر تحديث: يوليو 2026",
    "s1title": "المعلومات التي نجمعها",
    "s1text": "عند إرسال نموذج، نتلقى الحقول التي تقدمها. إذا كانت التحليلات مفعّلة، قد نجمع بيانات استخدام مجهولة.",
    "s2title": "كيف نستخدم المعلومات",
    "s2text": "للرد على الاستفسارات وتحسين الموقع. لا نبيع البيانات الشخصية.",
    "s3title": "خدمات طرف ثالث",
    "s3text": "قد تُعالَج النماذج عبر Formspree. التحليلات عبر Plausible أو Google Analytics عند التفعيل.",
    "s4title": "حقوقك",
    "s4text": "طلب الوصول أو التصحيح أو الحذف: mkofman@mkofman.com.",
    "s5title": "اتصل بنا",
    "s5text": "أسئلة حول هذه السياسة: mkofman@mkofman.com"
  },
  "board": {
    "eyebrow": "استشارات",
    "title": "استشارات",
    "body": "منفتح على محادثات استشارية استراتيجية مع منظمات التكنولوجيا والرعاية الصحية والبنية التحتية — استناداً إلى خبرة تشغيلية مباشرة في بناء الشركات واستراتيجية التكنولوجيا والتنفيذ في مراحل النمو.",
    "contactLink": "للاستفسارات الاستشارية",
    "lead": "Board & Advisory"
  },
  "thesis": {
    "eyebrow": "أطروحة القيادة",
    "title": "البناء على المدى البعيد. القرار في الحاضر.",
    "lead": "تتغير التكنولوجيا بسرعة؛ التزامات القيادة لا. توحّد المؤسسات الدائمة الطموح مع الانضباط والأدلة والمساءلة.",
    "believeEyebrow": "ما أؤمن به",
    "believeTitle": "سبعة مبادئ للمؤسسات الدائمة",
    "b1title": "يجب أن تنتج الاسترategia خيارات",
    "b1text": "الاستراتيجية ليست catalogاً للطموحات. تحدد أين تتنافس وما القدرات التي تبنيها وما لا ت Pursue وكيف يُقاس النجاح.",
    "b2title": "التكنولوجيا مسألة حوكمة",
    "b2text": "يجب أن تفهم مجالس الإدارة كيف تخلق التكنولوجيا قيمة وتركّز المخاطر وتغيّر المساءلة. تفويض كل سؤال تقني قرار بحد ذاته.",
    "b3title": "يجب أن تتفوق الأدلة على الحماس",
    "b3text": "الconviction مهم، لكن الأسواق والأنظمة والعلم يجب اختبارها. يخلق القادة آليات ت expose الافتراضات قبل العملاء أو المنظمين.",
    "b4title": "البنية تشكّل المؤسسة",
    "b4text": "تحدد البنية التقنية السرعة والمرونة والأمن والخيارات المستقبلية. تصبح الاختصارات قيوداً مؤسسية long after اختفاء سياقها الأصلي.",
    "b5title": "الثقة بنية تشغيلية",
    "b5text": "يُبنى الثقة عبر التزامات واضحة وتنفيذ موثوق وممارسات بيانات مسؤولة وتواصل مباشر عند تغيّر الظروف.",
    "b6title": "يجب أن يتبع رأس المال القدرة",
    "b6text": "يجب أن تعزز استثمارات النمو القدرات المتمايزة والطلب القابل للقياس، لا أن تحل الإنفاق محل فهم product-market.",
    "b7title": "القادة يصمّمون خلفاءهم",
    "b7text": "يبني أقوى القادة أنظمة ومواهب وجودة قرار تدوم beyond مشاركتهم.",
    "rejectEyebrow": "ما أرفضه",
    "rejectTitle": "ثلاثة أوهام مكلفة",
    "r1title": "مسرح الابتكار",
    "r1text": "الإعلانات وال pilots واللغة العصرية لا ت equal capability. يجب أن تحسّن الابتكار نتيجة مهمة.",
    "r2title": "نمو بلا حوكمة",
    "r2text": "يضخّم الحجم نقاط الضعف غير المحلولة. يجب أن تنضج الضوابط والثقافة والمساءلة قبل أن تجعل التعقيدات التصحيح مكلفاً.",
    "r3title": "يقين زائف",
    "r3text": "لا ينبغي أن تمحو confidence التنفيذية uncertainty. القرارات القوية تجعل الافتراضات visible وتحفظ options عند تغيّر الحقائق.",
    "horizonEyebrow": "الأفق",
    "horizonTitle": "الميزة التالية هي التكامل المسؤول",
    "horizonText": "الفرصة الحاسمة ليست technology واحدة. بل التكامل المنضبط للذكاء الاصطناعي وأنظمة البيانات المتقدمة والbiology والautomation في مؤسسات يمكن للناس الوثوق بها."
  },
  "press": {
    "eyebrow": "صحافة وإعلام",
    "title": "تغطية مختارة",
    "lead": "أرشيف موجز للتقدير والتقارير من جهات خارجية في التكنولوجيا وريادة الأعمال والطب الدقيق.",
    "archiveEyebrow": "الأرشيف",
    "y2023type": "تقدير صناعي",
    "y2023title": "Top 10 Precision Medicine Companies",
    "y2023desc": "Healthcare Tech Outlook recognized Digital Invest Inc.",
    "y2023link": "عرض التقرير",
    "y2001type": "جائزة تنفيذية",
    "y2001title": "رائد أعمال العام",
    "y2001desc": "تقدير Entrepreneur Magazine.",
    "y2001link": "عرض الأرشيف",
    "y1999type": "تقدير биográfي",
    "y1999title": "Who's Who in America",
    "y1999desc": "Recognition beginning in 1999.",
    "clipEyebrow": "من الأرشيف",
    "clipMeta": "Industry Feature · DataPeer Inc.",
    "clipTitle": "State of the Storage Industry",
    "clipLead": "مقابلة مبكرة مع Michael Kofman بصفته Founder وChairman وCEO لـ DataPeer Inc. — حول الألياف البصرية ونقل الأقمار الصناعية وSAN وسوق التخزين الناشئ.",
    "clipBody": "يُشير التقرير إلى تكريم «رائد أعمال العام» من Entrepreneur Magazine (2001)، ويناقش نهج DataPeer في التخزين الحيوي وiSCSI واستمرارية الأعمال.",
    "clipOpen": "فتح المسح الكامل →",
    "y2000type": "مقابلة",
    "y2000title": "State of the Storage Industry",
    "y2000desc": "مقابلة بارزة مع Michael Kofman بصفته Founder وChairman وCEO لـ DataPeer Inc. حول شبكات التخزين وiSCSI واستمرارية الأعمال."
  },
  "ip": {
    "eyebrow": "الملكية الفكرية",
    "title": "أفكار مطبّقة، موثّقة",
    "lead": "Selected patents, publications وresearch programs, connecting engineering rigor مع practical business وsocietal outcomes.",
    "patentEyebrow": "براءات الاختراع",
    "patentTitle": "اختراعات محمية",
    "patentIntro": "Patent work reflects sustained focus على systems improving collection, movement, protection وinterpretation of information.",
    "publicationsEyebrow": "منشورات",
    "publicationsTitle": "كتابة تقنية وتنفيذية",
    "publicationsIntro": "Published work translates complex technical subjects إلى methods, frameworks وdecisions useful للpractitioners وleaders.",
    "researchEyebrow": "بحث",
    "researchTitle": "برامج متعددة التخصصات",
    "researchIntro": "Research initiatives span secure communications, predictive analytics, genetic interpretation, human digital modeling وautonomous systems."
  },
  "testimonials": {
    "t1quote": "يجمع Michael دقة الم engineer مع حكم CEO متمرس. يطرح الأسئلة التي تحسّن القرار.",
    "t1name": "زميل في مجلس الإدارة",
    "t1role": "شركة تقنية عامة",
    "t2quote": "قدرته على ربط العلم والمنتج والحوكمة والواقع التجاري ت bring clarity نادرة للمبادرات المعقدة.",
    "t2name": "شريك استراتيجي",
    "t2role": "قطاع الصحة الرقمية",
    "t3quote": "Michael م direct وthoughtful وfocused على durable value. يساعد فرق القيادة على رؤية opportunity وobligation.",
    "t3name": "متعاون تنفيذي",
    "t3role": "بنية تحتية عالمية"
  },
  "deck": {
    "title": "Michael Kofman",
    "subtitle": "تنفيذي تقني · مؤسس · مستشار",
    "thesis": "التكنولوجيا والأعمال والاستثمار في البنية التحتية وعلوم الحياة والأنظمة المستقلة.",
    "contact": "مناقشة سرية: تواصل مع Michael Kofman عبر mkofman.com"
  },
  "briefIpo": {
    "title": "ما يغيره الاكتتاب العام",
    "desc": "الأسواق العامة لا تغير هيكل رأس المال فحسب؛ بل تغير العقد التشغيلي.",
    "p1": "يُ described الاكتتاب العام غالباً كحدث تمويل. عملياً، هو transition مؤسسي. يجب أن تصبح forecasting وcontrols وdisclosure وgovernance وexecutive communication repeatable قبل listing.",
    "p2": "تبدأ readiness بجودة القرار. يحتاج management إلى reliable metrics وclear ownership وoperating cadence. شركة لا ت reconcili internal narrative ست struggle في external one.",
    "p3": "يتغير دور board أيضاً. يجب على directors balance growth وoversight وفهم material risks وensure incentives support durable value.",
    "p4": "أ strongest public companies تحافظ على entrepreneurial speed مع institutional discipline. الهدف trustworthy execution على مستوى accountability أعلى.",
    "eyebrow": "ملخص تنفيذي"
  },
  "briefGenetic": {
    "title": "من البيانات الجينية إلى القرارات السريرية",
    "desc": "تعتمد قيمة المعلومات الجينومية على التفسير والأدلة والدمج المسؤول في الرعاية.",
    "p1": "البيانات الجينية وفيرة؛ المعنى مفيد سريرياً نادر. تصبح النتيجة قيمة فقط عند تفسيرها في السياق وربطها بأدلة م validated وتقديمها بشكل يدعم قراراً حقيقياً.",
    "p2": "يتطلب هذا الترجمة تعاوناً بين علم الأحياء الجزيئي والطب والإحصاء وهندسة البرمجيات وتواصل المرضى. ضعف في أي طبقة قد يحول الت sophistication التقنية إلى confusion سريري.",
    "p3": "الخصوصية والموافقة متطلبات معمارية وليست حواشي قانونية. يجب أن تحد الأنظمة من التعرض غير الضروري وتجعل مصدر البيانات مرئياً وتحافظ على agency المريض.",
    "p4": "سيتقدم الطب الدقيق عبر تكامل مدروس: أدلة أفضل ونماذج شفافة وسير عمل متكاملة ونتائج يمكن للأطباء والمرضى تقييمها. الثقة جزء من المنتج.",
    "eyebrow": "ملخص تنفيذي"
  },
  "briefAi": {
    "title": "استراتيجية الذكاء الاصطناعي وساء التجريبي",
    "desc": "يخلق الذكاء الاصطناعي المؤسسي قيمة عندما تنضج الملكية والبيانات وسير العمل والحوكمة معاً.",
    "p1": "تبدأ كثير من مبادرات الذكاء الاصطناعي بعرض مقنع وتتوقف قبل الإنتاج. العنصر المفقود نادراً ما يكون النموذج وحده. القيمة المستدامة تتطلب نتيجة أعمال محددة ومالكاً مسؤولاً وبيانات موثوقة وسير عمل يستخدمه الناس فعلاً.",
    "p2": "يجب على القادة التمييز بين الأتمتة والتنبؤ ودعم القرار. لكل منها متطلبات مختلفة للدقة والقابلية للتفسير والمراجعة البشرية والمخاطر. قالب حوكمة واحد لا يناسب كل حالة.",
    "p3": "يجب أن تشمل القياس أكثر من الأداء التقني. التبني ووقت الدورة ومعدلات الخطأ وتأثير العملاء والتعرض الأمني وتكلفة الإشراف تحدد ما إذا كانت قدرة الذكاء الاصطناعي سليمة اقتصادياً ومؤسسياً.",
    "p4": "النهج الفائز هو محفظة مُدارة: توسيع حالات الاستخدام المثبتة وإيقاف الضعيفة مبكراً والحفاظ على حدود صريحة للقرارات عالية العواقب. استراتيجية الذكاء الاصطناعي هي في النهاية استرategia تشغيل.",
    "eyebrow": "ملخص تنفيذي"
  }
};
