window.__LANG_ar = {
  "ui": {
    "toggleTheme": "تبديل السمة الفاتحة/الداكنة",
    "selectLanguage": "اختر اللغة",
    "messageSent": "تم إرسال الرسالة",
    "sendMessage": "إرسال",
    "toggleNav": "فتح القائمة",
    "sending": "جارٍ الإرسال…",
    "formError": "تعذر الإرسال. يرجى إرسال بريد إلكتروني مباشرة.",
    "present": "حتى الآن"
  },
  "nav": {
    "home": "الرئيسية",
    "about": "نبذة",
    "ventures": "المشاريع",
    "career": "The Record",
    "recognition": "التكريم",
    "contact": "اتصل",
    "consulting": "الاستشارات",
    "insights": "رؤى",
    "speaking": "المحاضرات",
    "caseStudies": "دراسات الحالة",
    "mediaKit": "الحقيبة الإعلامية",
    "groupMain": "الرئيسية",
    "groupServices": "الخدمات",
    "groupWork": "الأعمال",
    "briefIpo": "Brief: IPO",
    "briefGenetic": "Brief: Genetic Data",
    "briefAi": "Brief: AI Strategy",
    "articleInfra": "Data Infrastructure",
    "articleHealth": "Precision Medicine",
    "board": "Board & Advisory",
    "thesis": "Leadership Thesis",
    "press": "Press",
    "ip": "Intellectual Property"
  },
  "footer": {
    "navigation": "التنقل",
    "ventures": "المشاريع",
    "connect": "تواصل",
    "desc": "تنفيذي تقني ومؤسس ومستشار مجالس إدارة.",
    "copyright": "© {year} Michael Kofman. جميع الحقوق محفوظة.",
    "writeTitle": "اكتب لي",
    "writeEmail": "بريدك الإلكتروني",
    "writeMessage": "رسالتك",
    "writeSend": "إرسال",
    "writeSuccess": "شكراً — تم إرسال رسالتك.",
    "more": "المزيد",
    "privacy": "الخصوصية"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — تنفيذي تقني",
      "description": "تنفيذي تقني ومؤسس ومستشار — البنية التحتية وعلوم الحياة والأنظمة المستقلة."
    },
    "about": {
      "title": "نبذة — Michael Kofman",
      "description": "سيرة Michael Kofman — الرئيس التنفيذي لـ Digital Invest Inc. ومؤسس AGRON Inc."
    },
    "ventures": {
      "title": "المشاريع — Michael Kofman",
      "description": "الشركات التي أسسها مايكل كوفمان وقادها — من Digital Invest Inc. إلى 9 Net Avenue Inc. — لبناء أعمال تحويلية في التكنولوجيا والرعاية الصحية."
    },
    "career": {
      "title": "The Record — Michael Kofman",
      "description": "سجل مهني في الهندسة والبنية التحتية والأسواق العامة وعلوم الحياة والأنظمة المستقلة."
    },
    "recognition": {
      "title": "التكريم — Michael Kofman",
      "description": "الجوائز والتكريمات لمايكل كوفمان — رائد العام، Who's Who، براءات الاختراع وتقدير القطاع."
    },
    "contact": {
      "title": "اتصل — Michael Kofman",
      "description": "التواصل مع مايكل كوفمان — الرئيس التنفيذي لـ Digital Invest Inc. للاستشارات والمحاضرات والاستفسارات التجارية."
    },
    "consulting": {
      "title": "الاستشارات — Michael Kofman",
      "description": "أدوار استشارية ومقاعد في مجالس الإدارة ومحاضرات وشراكات استراتيجية مع Michael Kofman."
    },
    "insights": {
      "title": "رؤى — Michael Kofman",
      "description": "كتابات أصلية وbriefs تنفيذية من Michael Kofman."
    },
    "speaking": {
      "title": "المحاضرات — Michael Kofman",
      "description": "ادعُ Michael Kofman للحديث عن القيادة التنفيذية، واستراتيجية التكنولوجيا، والصحة الرقمية، وحوكمة الشركات."
    },
    "caseStudies": {
      "title": "دراسات الحالة — Michael Kofman",
      "description": "دراسات حالة من مسيرة Michael Kofman: 9 Net Avenue Inc. وDigital Invest Inc."
    },
    "mediaKit": {
      "title": "الحقيبة الإعلامية — Michael Kofman",
      "description": "سير ذاتية رسمية، وصور، وبيانات اتصال للصحافة ومنظمي الفعاليات."
    },
    "article1": {
      "title": "من الهندسة إلى البنية التحتية العالمية — Michael Kofman",
      "description": "Michael Kofman حول المسار المهني من هندسة الأقمار الصناعية إلى تأسيس شركات بنية تحتية عالمية للبيانات."
    },
    "article2": {
      "title": "الطب الدقيق والتكنولوجيا — Michael Kofman",
      "description": "Michael Kofman حول دمج علوم الحياة مع AI وML وتقنيات الحمض النووي في الطب الحديث."
    },
    "privacy": {
      "title": "سياسة الخصوصية — Michael Kofman",
      "description": "سياسة خصوصية mkofman.com — النماذج والتحليلات."
    },
    "board": {
      "title": "Board Advisory — Michael Kofman",
      "description": "Board service and strategic advisory from Michael Kofman for technology, healthcare, infrastructure, and growth-stage organizations."
    },
    "thesis": {
      "title": "Leadership Thesis — Michael Kofman",
      "description": "Michael Kofman's principles for building durable companies, governing technology, and leading through consequential change."
    },
    "press": {
      "title": "Press Archive — Michael Kofman",
      "description": "Selected press coverage, awards, and media references spanning Michael Kofman's career in technology and entrepreneurship."
    },
    "ip": {
      "title": "Intellectual Property — Michael Kofman",
      "description": "Patents, publications, and applied research by Michael Kofman across computing, communications, data, and digital health."
    },
    "briefIpo": {
      "title": "What an IPO Changes — Michael Kofman",
      "description": "An executive brief on the operating discipline, governance, and accountability required before and after an initial public offering."
    },
    "briefGenetic": {
      "title": "From Genetic Data to Clinical Decisions — Michael Kofman",
      "description": "An executive brief on translating genomic information into responsible, useful, and scalable clinical intelligence."
    },
    "briefAi": {
      "title": "AI Strategy Beyond the Pilot — Michael Kofman",
      "description": "An executive brief on moving artificial intelligence from experimentation to governed, measurable enterprise capability."
    },
    "deck": {
      "title": "Executive Overview — Michael Kofman",
      "description": "Private executive overview for qualified introductions."
    }
  },
  "home": {
    "heroEyebrow": "الموقع الرسمي لـ Michael Kofman",
    "heroTitle1": "مبني ليدوم.",
    "heroTitle2": "قيادة بحكمة.",
    "heroCta": "اكتشف قصتي",
    "heroAlt": "Michael Kofman",
    "quote1text": "من بين الشركات الأمريكية الرائدة في الطب الدقيق والصحة الرقمية.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "رائد الأعمال للعام — تقديراً للقيادة والإنجازات في ابتكار المنصات والبنية التحتية.",
    "quote2author": "Entrepreneur Magazine · 2001",
    "quote3text": "Digital Invest Inc. ضمن أفضل 10 شركات أمريكية في الطب الدقيق والصحة الرقمية.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "دقة هندسية مع استراتيجية أعمال — من أنظمة الأقمار الصناعية إلى بنية تحتية بقيمة",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "تعرف على Michael Kofman",
    "aboutTitle": "شركات مصممة للبقاء",
    "aboutLead1": "الرئيس التنفيذي لـ Digital Invest Inc. ومؤسس AGRON Inc. أسس وقاد شركات في الولايات المتحدة وأوروبا.",
    "aboutLead2": "من 9 Net Avenue (ذروة تقييم",
    "aboutLink": "السيرة الكاملة",
    "expertiseEyebrow": "مجالات التركيز",
    "expertiseTitle": "قيادة تنفيذية عبر الصناعات",
    "expertiseLead": "أربعة عقود في بناء الشركات والاستشارة والاستثمار في البنية التحتية والصحة والروبوتات.",
    "exp1title": "الرئيس التنفيذي والمؤسس",
    "exp1desc": "أسس وقاد عدة شركات تقنية في الولايات المتحدة وأوروبا.",
    "exp1link": "المشاريع ←",
    "exp2title": "مهندس تقني",
    "exp2desc": "صمم اتصالات آمنة ومحركات تحليلات تنبؤية ومنصات تكامل بيانات على المستوى الوطني للقطاعات الحكومية والعسكرية والاتصالات.",
    "exp2link": "المسيرة ←",
    "exp3title": "الصحة الرقمية",
    "exp3desc": "يقود تحويل الطب من خلال الذكاء الاصطناعي والتعلم الآلي وتقنيات الحمض النووي. تعاون مع Harvard Medical School وStanford Biomath في التقارير الجينية.",
    "exp3link": "Digital Invest ←",
    "exp4title": "مستشار مجلس",
    "exp4desc": "يشغل مقاعد في مجالس الإدارة ويقدم المشورة للشركات العامة والخاصة بشأن التوجه الاستراتيجي والحوكمة ومبادرات النمو التقني.",
    "exp4link": "الاستشارات →",
    "stat1": "سنوات القيادة",
    "stat2": "شركات تأسست",
    "stat3": "أقصى قيمة سوقية",
    "stat4": "موظفون",
    "recEyebrow": "التكريم",
    "recTitle": "تكريمات مختارة",
    "recLead": "جوائز صناعية وتقدير من الأقران في ريادة الأعمال والطب والهندسة.",
    "award1title": "رائد الأعمال للعام",
    "award1desc": "Entrepreneur Magazine · 2001",
    "award2title": "أفضل 10 طب دقيق",
    "award2desc": "Digital Invest Inc. — U.S., 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "التكريم والصحافة →",
    "heroSub": "التكنولوجيا والأعمال والاستثمار في البنية التحتية وعلوم الحياة والأنظمة المستقلة.",
    "primaryCta": "طلب استشارة",
    "secondaryCta": "عرض دراسات الحالة",
    "featuredEyebrow": "ظهر في",
    "caseStudiesEyebrow": "نتائج مثبتة",
    "caseStudiesTitle": "دراسات الحالة",
    "caseStudiesLead": "تأسيس وتوسيع وقيادة شركات من المراحل المبكرة حتى الاستحواذ.",
    "caseStudiesLink": "عرض جميع دراسات الحالة →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "Founded 9 Net Avenue Inc.; acquired by Concentric Networks in 2000.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "تأسست وتوسعت من البداية حتى طرح عام أولي ناجح - ضمن أفضل 10 شركات طب دقيق في الولايات المتحدة لعام 2023.",
    "cs3title": "AGRON Inc.",
    "cs3desc": "Founded in 2026 — the AGRON Ecosystem for UAV capability development, geospatial systems, and maritime intelligence.",
    "boardCtaEyebrow": "Board & Advisory",
    "boardCtaTitle": "Experience for the Decisions That Define an Enterprise",
    "boardCtaLead": "Independent perspective for boards and leaders navigating technology, governance, transformation, and growth.",
    "boardCtaBtn": "Explore Board Advisory",
    "testimonialsEyebrow": "Trusted Perspective",
    "testimonialsTitle": "What Colleagues Value",
    "videoEyebrow": "Executive Perspective",
    "videoTitle": "Leadership at the Intersection of Technology and Enterprise",
    "videoLead": "A concise introduction to the principles, experience, and long-term perspective behind Michael Kofman's work.",
    "videoCta": "Read Leadership Thesis →",
    "heroName": "Michael Kofman",
    "heroRole": "تنفيذي تقني · مؤسس · مستشار",
    "introText": "Michael Kofman تنفيذي تقني ومؤسس شركات. يشمل عمله هندسة الأقمار الصناعية وبنية الإنترنت والشركات التقنية العامة وعلوم الحياة. أسس 9 Net Avenue Inc.، التي استحوذت عليها Concentric Networks عام 2000. CEO لـ Digital Invest Inc. في الطب الرياضي الحيوي والذكاء الجينومي؛ ومؤسس AGRON Inc. في العمليات المستقلة جواً-أرضاً والأنظمة الجيospatiale. يشارك في مجالس الإدارة ويقدم الاستشارات في التكنولوجيا والصحة والبنية التحتية.",
    "introLink": "السيرة الكاملة →",
    "currentEyebrow": "العمل الحالي",
    "currentTitle": "التركيز الحالي",
    "currentDiTitle": "Digital Invest Inc.",
    "currentDiDesc": "الطب الرياضي الحيوي والبيانات الجينومية والذكاء السريري — تطبيق AI وML وتقنيات DNA لنتائج صحية مسؤولة.",
    "currentDiLink": "Ventures →",
    "currentAgTitle": "AGRON Inc.",
    "currentAgDesc": "عمليات مستقلة جواً-أرضاً وتطوير قدرات UAV والأنظمة الجيospatiale والبنية التحتية للاستخبارات البحرية.",
    "currentAgLink": "agron1.com →",
    "careerEyebrow": "سجل مختار",
    "careerTitle": "استمرارية عبر الفترات التقنية",
    "careerLead": "Selected milestones from engineering through current work in autonomous systems.",
    "career1title": "Engineering & Communications",
    "career1desc": "Satellite transceiver systems, digital communications, and early engineering leadership.",
    "career2title": "Internet & Infrastructure",
    "career2desc": "Internet infrastructure, data centers, storage, and telecommunications at scale.",
    "career3title": "Technology Companies & Public Markets",
    "career3desc": "Company-building, acquisitions, and public-company experience including 9 Net Avenue Inc.",
    "career4title": "Life Sciences & Human Data",
    "career4desc": "Biotechnology, genetic data, precision medicine, and health intelligence platforms.",
    "career5title": "Autonomous Systems",
    "career5desc": "Aerial-ground robotics, UAV operations, and geospatial infrastructure.",
    "careerLink": "The Record →",
    "perspectivesEyebrow": "Perspectives",
    "perspectivesTitle": "Selected Writing",
    "perspectivesLink": "All insights →",
    "footerHomeDesc": "تنفيذي تقني ومؤسس ومستشار مجالس إدارة."
  },
  "about": {
    "eyebrow": "نبذة عن Michael Kofman",
    "title": "ثلاثة عقود من الخبرة",
    "lead": "تنفيذي تقني ومؤسس ومستشار.",
    "glance": "نظرة سريعة",
    "role": "الدور الحالي",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "الموقع",
    "locationVal": "Charlotte, North Carolina",
    "education": "التعليم",
    "educationVal": "Doctor of Technical Sciences\nPh.D. in Information Technology\nMaster's in Electronic Engineering",
    "university": "الجامعة",
    "universityVal": "Ukrainian State Marine Technical University",
    "languages": "اللغات",
    "languagesVal": "English, Russian, Ukrainian",
    "contactLabel": "اتصل",
    "principlesEyebrow": "Operating Principles",
    "principlesTitle": "How I Lead",
    "p1title": "Understand the System",
    "p1text": "Before changing an organization, understand its incentives, architecture, constraints, and sources of trust.",
    "p2title": "Make Accountability Explicit",
    "p2text": "Clear ownership and measurable outcomes turn strategy from presentation material into operating reality.",
    "p3title": "Leave Stronger Institutions",
    "p3text": "Leadership should compound capability by developing people, improving decisions, and building systems that endure.",
    "archiveEyebrow": "From the Archive",
    "archiveTitle": "من الأرشيف",
    "archiveLead": "Authentic material from company building, infrastructure, and leadership.",
    "photo9netTitle": "9 Net Avenue",
    "photo9netCaption": "Founder & CEO — hosting and internet infrastructure company, acquired by Concentric Networks in 2000.",
    "photoServerTitle": "Data Infrastructure",
    "photoServerCaption": "Hands-on years in storage, networking, and high-density server environments at DataPeer and related ventures.",
    "photoTodayTitle": "Today",
    "photoTodayCaption": "Digital Invest Inc., AGRON Inc., and board advisory work.",
    "secIntroTitle": "Introduction",
    "secTechTitle": "التكنولوجيا والبنية التحتية",
    "secBusinessTitle": "Business",
    "secCurrentTitle": "Current Work",
    "secBackgroundTitle": "Background",
    "recordLink": "The Record →",
    "secBackgroundP1": "Doctor of Technical Sciences و Ph.D. in Information Technology. مؤلف أوراق تقنية؛ براءة HDTV فضائية acquired by Sony.",
    "bioP1": "Michael Kofman تنفيذي تقني ومؤسس ومستشار. CEO لـ Digital Invest Inc. ومؤسس AGRON Inc.، مع خبرة في هندسة الأقمار الصناعية وبنية الإنترنت والشركات التقنية العامة وعلوم الحياة.",
    "bioP2": "As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. In 2026 he founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network. He also created Digital Invest, dedicated to the bio-mathematical sphere and transforming medicine through science, DNA technologies, AI, and ML.",
    "secBioTitle": "الطب الدقيق والتكنولوجيا الحيوية",
    "secBioP1": "قبل Digital Invest، لعب دوراً بارزاً في نجاح Biotechnology Group Inc. (2008 — 2014)، شركة ملتزمة بفحص وتحليل الحمض النووي، وأتمتة عمليات إنشاء الملفات الجينية، والبحث الجيني البشري الشامل. يؤمن السيد Kofman إيماناً راسخاً بإمكانات الجمع بين علوم الحياة وأحدث التقدم التكنولوجي.",
    "secBioP2": "تحت قيادته، أُطلقت مشاريع ناجحة للفحص الجيني في أوكرانيا وروسيا ودول Baltic. تُثري هذه التجربة الفريدة باستمرار بالتقنيات الحديثة والمعدات الجديدة. بالتعاون مع Harvard Medical School وStanford Biomath، لعب السيد Kofman دوراً حاسماً في تطوير تقارير جينية يسهل فهمها للأطباء والمرضى على حد سواء. وقد اعتُمد هذا النهج المبتكر على نطاق واسع من قبل المختبرات الرائدة في الولايات المتحدة وخارجها.",
    "secTechP1": "خلفية هندسية في أنظمة transceiver للأقمار الصناعية واتصالات رقمية في Astra Corp.",
    "secTechP2": "في 2006، أسس السيد Kofman شركة XIBI Group Inc. — شركة تقنية شغل فيها منصباً في مجلس الإدارة. تتخصص الشركة الأمريكية في خدمات تخزين البيانات وإدارة البيانات الضخمة للمؤسسات التجارية والحكومية الكبرى.",
    "secTechP3": "من 2000 إلى 2004، قاد السيد Kofman شركة DataPeer Inc. — شركة لإدارة وتخزين البيانات تقدم مجموعة واسعة من الخدمات المتعلقة بتخزين المعلومات للشركات الصغيرة والمتوسطة. في DataPeer طوّر حلولاً تقنية فريدة سهلت تتبع المعلومات بشكل أسرع وإتاحة الوصول إلى البيانات بسهولة أكبر للمستخدمين النهائيين والمؤسسات الحكومية حول العالم.",
    "secTechP4": "Founded 9 Net Avenue Inc. in 1996. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "secPost9NetP1": "بعد استحواذ 9 Net Avenue، اكتسب السيد Kofman خبرة واسعة في العمل مع الشركات العامة، والمشاركة في مجالس الإدارة، واتخاذ القرارات الاستراتيجية على أعلى المستويات التنفيذية.",
    "secEarlyTitle": "المسيرة المبكرة والهندسة",
    "secEarlyP1": "من 1994 إلى 1996، شغل السيد Kofman منصب الرئيس التنفيذي ومدير تكنولوجيا المعلومات في Elitan United Inc. — شركة تقنية معلومات من Massachusetts تقدم استراتيجيات شاملة وخدمات تقنية للمؤسسات العالمية الرائدة. لعب دوراً محورياً في تطوير وإدارة بنية تحتية قابلة للتوسع، قائداً نمو الشركة من تسعة موظفين فقط إلى أكثر من 4000 موظف حول العالم.",
    "secEarlyP2": "من 1989 إلى 1994، كان مؤسساً والرئيس التنفيذي لـ Astra Corp، إحدى أكبر الشركات المصنعة لأنظمة أقمار صناعية رقمية للإرسال والاستقبال في أوروبا، حاصلاً على اعتراف دولي في مجال أجهزة الأقمار الصناعية. شملت مسؤولياته البحث وتطوير أنظمة التشغيل وتطبيقات برمجيات الشبكات والاستراتيجية التقنية الشاملة.",
    "secEarlyP3": "من 1984 إلى 1989، عمل السيد Kofman في مصنع بناء السفن في Nikolaev بأوكرانيا، حيث شارك بنشاط في تطوير وإنشاء أنظمة أقمار صناعية للإرسال والاستقبال لنقل المعلومات المصنفة إلى السفن العسكرية والعكس. اُعترف به كمهندس إلكترونيات من أعلى المستويات، حاصلاً على الفئة السادسة — أرفع تكريم في المصنع الذي يضم 93 ألف موظف.",
    "secResearchTitle": "البحث وبراءات الاختراع",
    "secResearchP1": "Michael Kofman مؤلف أوراق تقنية تركز على أنظمة الأقمار الصناعية والبصرية لنقل البيانات. كما حصل على براءة اختراع في مجال أنظمة التلفزيون عالي الوضوح (HDTV) عبر الأقمار الصناعية الرقمية، التي استحوذت عليها لاحقاً Sony.",
    "secAgronTitle": "Robotics, UAV & Maritime Intelligence",
    "secAgronP1": "In 2026, Mr. Kofman founded AGRON Inc. to build the AGRON Ecosystem — a corporate operating architecture for aerial and ground robotics, governed mission execution, and network infrastructure connecting teams, assets, and operational data. The ecosystem delivers consulting, assessment, capability development, and training for UAV and Counter-UAS organizations, alongside maritime intelligence and security services at agron1.com.",
    "secBusinessP1": "أسس وقاد عدة شركات تقنية. السجل الكامل في The Record.",
    "secCurrentP1": "CEO لـ Digital Invest Inc. في الطب الرياضي الحيوي والذكاء الجينومي. مؤسس AGRON Inc. في العمليات المستقلة جواً-أرضاً."
  },
  "ventures": {
    "eyebrow": "محفظة المشاريع",
    "title": "شركات أسستها وقادها",
    "lead": "من الطب الدقيق والروبوتات إلى البنية التحتية العالمية للبيانات — تأسيس وتوسيع وقيادة في الولايات المتحدة وأوروبا.",
    "ecosystemEyebrow": "Venture Ecosystem",
    "ecosystemTitle": "Companies Across Technology Frontiers",
    "ecosystemLead": "A portfolio shaped by recurring themes: trusted data, intelligent infrastructure, human health, and systems built for scale.",
    "statusActive": "Active",
    "statusExited": "Exited",
    "statusLegacy": "Legacy",
    "v1lesson": "Lesson: infrastructure wins when reliability, economics, and customer trust improve together.",
    "v2lesson": "Lesson: precision medicine requires equal discipline in science, software, privacy, and clinical usefulness.",
    "v3lesson": "Lesson: autonomy creates value only when sensing, communications, and human oversight form one resilient system.",
    "v5lesson": "الدرس: نمو البنية التحتية يُبنى بالتميز التشغيلي قبل الخروج بكثير.",
    "currentEyebrow": "Current",
    "historyEyebrow": "Selected History",
    "v2highlight": "Harvard Medical School و Stanford Biomath — تعاون في التقارير الجينية",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — an Aerial-Ground Robotics Operations Network spanning UAV and Counter-UAS consulting, technology assessment, capability development, training infrastructure, product validation, geospatial systems (ISDRI), and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "v0role": "Founder",
    "v0year": "2026 — Present",
    "v1highlight": "من أفضل 10 شركات أمريكية في الطب الدقيق — 2023",
    "v1p1": "طب biomathematical وبيانات genomics وذكاء clínico — AI وML وتقنيات DNA في سير العمل clínico والبحثي.",
    "v1role": "المؤسس والرئيس التنفيذي · عضو مجلس الإدارة",
    "v1year": "2021 — حتى الآن",
    "v2p1": "فحص وتحليل الحمض النووي، وأتمتة الملفات الجينية، والبحث الجيني البشري الشامل. أطلق مشاريع فحص جيني في أوكرانيا وروسيا ودول Baltic.",
    "v2p2": "تعاون مع Harvard Medical School وStanford Biomath في تقارير جينية اعتمدتها المختبرات الرائدة حول العالم.",
    "v2role": "الرئيس التنفيذي والمدير التقني",
    "v2year": "2008 — 2014",
    "v3highlight": "حلول بيانات للمؤسسات والحكومة",
    "v3p1": "خدمات تخزين البيانات وإدارة البيانات الضخمة للمؤسسات التجارية والحكومية الكبرى. رسّخ الشركة كمزود موثوق لحلول البيانات المؤسسية.",
    "v3role": "المؤسس والرئيس التنفيذي · مجلس الإدارة",
    "v3year": "2006 — 2011",
    "v4highlight": "منصة عالمية لإدارة البيانات",
    "v4p1": "إدارة وتخزين البيانات للشركات الصغيرة والمتوسطة. طوّر حلولاً لتتبع أسرع للمعلومات وإتاحة أسهل للبيانات للمستخدمين النهائيين والمؤسسات الحكومية حول العالم.",
    "v4role": "المؤسس والرئيس التنفيذي",
    "v4year": "2000 — 2004",
    "v5highlight": "Acquired · Concentric Networks, 2000",
    "v5p1": "Founded and led a hosting and internet infrastructure company. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "v5role": "المؤسس والرئيس التنفيذي",
    "v5year": "1996 — 2000",
    "v6highlight": "استراتيجية تقنية المعلومات والبنية التحتية العالمية",
    "v6p1": "شركة تقنية معلومات من Massachusetts تقدم استراتيجيات شاملة وخدمات تقنية للمؤسسات العالمية الرائدة. قاد تطوير البنية التحتية القابلة للتوسع وعمليات تقنية المعلومات العالمية.",
    "v6role": "الرئيس التنفيذي ومدير تكنولوجيا المعلومات",
    "v6year": "1994 — 1996",
    "v7highlight": "رائد أوروبي في أنظمة الأقمار الصناعية",
    "v7p1": "إحدى أكبر الشركات المصنعة لأنظمة أقمار صناعية رقمية للإرسال والاستقبال في أوروبا. قاد البحث وتطوير أنظمة التشغيل وتطبيقات برمجيات الشبكات والاستراتيجية التقنية الشاملة.",
    "v7role": "المؤسس والرئيس التنفيذي",
    "v7year": "1989 — 1994",
    "v8highlight": "هندسة أنظمة أقمار صناعية عسكرية",
    "v8p1": "تطوير وإنشاء أنظمة أقمار صناعية للإرسال والاستقبال لنقل المعلومات المصنفة إلى السفن العسكرية. اُعترف به كمهندس إلكترونيات من أعلى المستويات في مصنع يضم 93,000 موظف.",
    "v8role": "مهندس إلكترونيات · أعلى فئة (السادسة)",
    "v8year": "1984 — 1989"
  },
  "career": {
    "eyebrow": "المسيرة المهنية",
    "title": "The Record",
    "lead": "التكنولوجيا والشركات والخبرة التشغيلية عبر فترات متتالية من التغير التكنولوجي.",
    "timelineEyebrow": "الجدول الزمني",
    "timelineTitle": "محطات رئيسية",
    "strengthsEyebrow": "نقاط القوة",
    "strengthsTitle": "مجالات الخبرة",
    "filterAll": "All",
    "filterHealthcare": "Healthcare",
    "filterInfrastructure": "Infrastructure",
    "filterDefense": "Defense",
    "filterTelecom": "Telecommunications",
    "periodCurrent": "Autonomous Systems",
    "periodCurrentLead": "AI, robotics, autonomous operations, geospatial systems, and related current infrastructure.",
    "period1title": "Engineering & Communications",
    "period1lead": "Early engineering, satellite systems, communications, and related technology work.",
    "period2title": "Internet & Infrastructure",
    "period2lead": "Internet infrastructure, telecommunications, data centers, storage, and related companies.",
    "period3title": "Companies & Public Markets",
    "period3lead": "Company building, transactions, public-company involvement, and executive roles.",
    "period4title": "Life Sciences & Human Data",
    "period4lead": "Biotechnology, health-related technology, data, and precision medicine.",
    "period5title": "Government & Defense Programs",
    "period5lead": "Technology strategy and delivery for government, defense, and state-owned enterprise programs.",
    "t1desc": "Digital Invest Inc.، تأسست 2021. طب biomathematical وبيانات genomics ومنصات clínico. Healthcare Tech Outlook (2023).",
    "t0desc": "Founded AGRON Inc. to build the AGRON Ecosystem — consulting, assessment, capability development, training infrastructure, and product support for UAV and Counter-UAS programmes, plus AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure. Connects aerial and ground robotics, governed mission execution, and network infrastructure linking teams, assets, and operational data.",
    "t0role": "Founder",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — Present",
    "t10desc": "طوّر وأنشأ أنظمة أقمار صناعية للإرسال والاستقبال لنقل المعلومات المصنفة إلى السفن العسكرية. اُعترف به كمهندس إلكترونيات من أعلى المستويات في مصنع يضم 93,000 موظف — بداية مسيرة متميزة في التكنولوجيا والابتكار.",
    "t10role": "مهندس إلكترونيات — الفئة السادسة (الأعلى)",
    "t10title": "Nikolaev Shipbuilding Plant",
    "t10year": "1984 — 1989",
    "t1role": "المؤسس والرئيس التنفيذي",
    "t1title": "Digital Invest Inc.",
    "t1year": "2021 — حتى الآن",
    "t2desc": "وجّه الاستراتيجية التكنولوجية وتسليمها لبرامج سرية وعالية الحساسية تشمل وكالات حكومية أمريكية وأنظمة دفاعية للحلفاء ومؤسسات مملوكة للدولة. ترأس مشاريع تقنية معقدة للشركات المملوكة للحكومة عبر قطاعات متعددة. بعد 11 سبتمبر 2001، قاد مبادرات حكومية واسعة النطاق تركز على البيانات الضخمة والاتصالات الآمنة والتحليلات التنبؤية وتكامل البيانات على المستوى الوطني — بما في ذلك تصميم وبناء وتشغيل مراكز بيانات عالية الإنتاجية في الولايات المتحدة وأوروبا. تواصل مع ضباط البرامج العسكرية وموردي التكنولوجيا والجهات التنظيمية.",
    "t2role": "كبير المستشارين التقنيين / مهندس البرامج",
    "t2title": "GovTech والدفاع والبرامج الحكومية",
    "t2year": "2001 — 2019",
    "t3desc": "قاد فحص وتحليل الحمض النووي، وأتمتة الملفات الجينية، والبحث الجيني البشري الشامل. أطلق مشاريع فحص جيني في أوكرانيا وروسيا ودول Baltic. تعاون مع Harvard Medical School وStanford Biomath لتطوير تقارير جينية يسهل فهمها اعتمدتها المختبرات الرائدة حول العالم.",
    "t3role": "الرئيس التنفيذي والمدير التقني",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4desc": "وجّه عمليات نشر البنية التحتية الوطنية في كندا وإيطاليا وسويسرا وأوكرانيا وجمهوريات Baltic. أشرف على أكثر من 1000 مهندس وموظف نشر في عمليات الاتصالات بما في ذلك أنظمة التبديل وتوسيع النطاق العريض والاتصال عبر الحدود. نفّذ أنظمة أساسية لتكرار الشبكة وتحسين وقت التشغيل والتوجيه الذكي.",
    "t4role": "نائب رئيس التكنولوجيا / المدير التقني الإقليمي — أوروبا الشرقية ورابطة الدول المستقلة",
    "t4title": "مشاريع الاتصالات",
    "t4year": "2000 — 2012",
    "t5desc": "أسس شركة تقنية متخصصة في تخزين البيانات وإدارة البيانات الضخمة للمؤسسات التجارية والحكومية الكبرى. رسّخ الشركة كمزود موثوق لحلول البيانات المؤسسية.",
    "t5role": "المؤسس والرئيس التنفيذي · مجلس الإدارة",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6desc": "أسس شركة لإدارة وتخزين البيانات للشركات الصغيرة والمتوسطة. طوّر حلولاً تقنية فريدة لتتبع أسرع للمعلومات وإتاحة أسهل للبيانات للمستخدمين النهائيين والمؤسسات الحكومية حول العالم.",
    "t6role": "المؤسس والرئيس التنفيذي",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "Founded and led 9 Net Avenue Inc., a hosting and internet infrastructure company. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "t7role": "المؤسس والرئيس التنفيذي",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8desc": "قاد استراتيجيات تقنية المعلومات الشاملة والخدمات التقنية للمؤسسات العالمية الرائدة من Massachusetts خلال فترة توسع سريع، وبنى بنية تحتية قابلة للتوسع وعمليات تقنية معلومات عالمية.",
    "t8role": "الرئيس التنفيذي ومدير تكنولوجيا المعلومات",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9desc": "أسس إحدى أكبر الشركات المصنعة لأنظمة أقمار صناعية رقمية للإرسال والاستقبال في أوروبا. قاد البحث وتطوير أنظمة التشغيل وتطبيقات برمجيات الشبكات والاستراتيجية التقنية الشاملة، حاصلاً على اعتراف دولي.",
    "t9role": "المؤسس والرئيس التنفيذي",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994"
  },
  "recognition": {
    "eyebrow": "الجوائز",
    "title": "الجوائز والتقدير",
    "lead": "تكريم في ريادة الأعمال والطب الدقيق والهندسة والقيادة التنفيذية.",
    "industryEyebrow": "جوائز الصناعة",
    "industryTitle": "تكريمات كبرى",
    "ipEyebrow": "الملكية الفكرية",
    "ipTitle": "براءات ومنشورات",
    "eduEyebrow": "التعليم",
    "eduTitle": "المؤهلات الأكاديمية",
    "pressEyebrow": "الصحافة",
    "pressTitle": "ظهر في",
    "moreLink": "اطّلع على براءات الاختراع والمنشورات والتغطية الإعلامية في Insights →",
    "a1title": "رائد الأعمال للعام",
    "a1desc": "Entrepreneur Magazine · 2001",
    "a2title": "من أفضل 10 شركات أمريكية في الطب الدقيق",
    "a2desc": "Digital Invest Inc. معترف بها بين أفضل 10 شركات أمريكية في الطب الدقيق والصحة الرقمية — 2023.",
    "a3title": "Who's Who in America",
    "a3desc": "مُدرج، 1999 — 2018 — لإنجازات استثنائية في إنشاء وتطوير الأعمال.",
    "a4title": "Who's Who in the World",
    "a4desc": "مُدرج، 2000 — 2004 — بين القادة العالميين في العلوم والهندسة وابتكار الأعمال.",
    "a5title": "Who's Who in Science & Engineering",
    "a5desc": "مُدرج، 2000 — 2014 — لمساهماته في التكنولوجيا وأنظمة الأقمار الصناعية والبنية التحتية الرقمية.",
    "a6title": "مهندس إلكترونيات — الفئة السادسة",
    "a6desc": "أرفع تكريم في Nikolaev Shipbuilding Plant (93,000 موظف) لهندسة أنظمة أقمار صناعية للإرسال والاستقبال.",
    "ip1year": "براءة اختراع",
    "ip1title": "أنظمة HDTV عبر الأقمار الصناعية الرقمية",
    "ip1role": "استحوذت عليها لاحقاً Sony",
    "ip1desc": "براءة في أنظمة HDTV فضائية رقمية، استحوذت عليها Sony Corporation.",
    "ip2year": "منشورات",
    "ip2title": "أوراق تقنية",
    "ip2role": "أنظمة الأقمار الصناعية والبصرية",
    "ip2desc": "مؤلف أوراق تقنية تركز على أنظمة الأقمار الصناعية والبصرية لنقل البيانات. تشمل مساهماته البحثية معالجة الإشارات ونمذجة المحاكاة ومنصات الأتمتة المطبقة في الاتصالات والبنية التحتية الوطنية والصحة الرقمية.",
    "ip3year": "بحث",
    "ip3title": "تعاون دولي",
    "ip3role": "الولايات المتحدة وأوروبا",
    "ip3desc": "شارك في تعاون بحثي دولي ومبادرات نقل المعرفة. طوّر أنظمة هندسية مدمجة لجمع البيانات والتشخيص التنبؤي والتنسيق السحابي عبر صناعات متعددة.",
    "edu1title": "دكتوراه في العلوم التقنية",
    "edu2title": "دكتوراه في تكنولوجيا المعلومات",
    "edu3title": "درجات الماجستير",
    "edu3desc": "الإلكترونيات وأنظمة الأقمار الصناعية الرقمية والاقتصاد",
    "press1title": "Healthcare Tech Outlook",
    "press1role": "تقرير عن Digital Invest Inc.",
    "press1desc": "Healthcare Tech Outlook عن Digital Invest Inc. (2023).",
    "press1link": "قراءة التقرير ←",
    "press2title": "Top Precision Medicine Solutions",
    "press2role": "اعتراف صناعي",
    "press2desc": "مُدرجة بين أفضل شركات حلول الطب الدقيق، مسلطة الضوء على دور Digital Invest في تطوير المناهج البيو-رياضية للرعاية الصحية الحديثة.",
    "press2link": "عرض القائمة ←"
  },
  "contact": {
    "eyebrow": "تواصل",
    "title": "لنبقَ على تواصل",
    "lead": "للاستشارات ومجالس الإدارة والشراكات الاستراتيجية.",
    "infoTitle": "تواصل مباشر",
    "email": "البريد",
    "phone": "الهاتف",
    "location": "الموقع",
    "locationVal": "Charlotte, North Carolina\nUnited States",
    "linkedin": "LinkedIn",
    "company": "الشركة الحالية",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member\nAGRON Inc.\nFounder",
    "formTitle": "إرسال رسالة",
    "formLead": "املأ النموذج وسأرد قريباً.",
    "firstName": "الاسم الأول",
    "lastName": "اسم العائلة",
    "emailLabel": "البريد الإلكتروني",
    "subject": "الموضوع",
    "message": "الرسالة",
    "inquiryType": "Inquiry Type",
    "inquiryAdvisory": "Advisory / Board Role",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "calendlyEyebrow": "Schedule a Conversation",
    "calendlyTitle": "Choose a Convenient Time",
    "calendlyLead": "For qualified board, advisory, speaking, and strategic partnership inquiries.",
    "calendlyPlaceholder": "Scheduling calendar will appear here.",
    "calendlyCta": "Open Scheduling Calendar",
    "inquiryBusiness": "Business",
    "infoEyebrow": "معلومات الاتصال"
  },
  "consulting": {
    "eyebrow": "خدمات استشارية",
    "title": "الاستشارات",
    "heroEyebrow": "التوجيه الاستراتيجي للأعمال",
    "heroTitle": "استشارات استراتيجية",
    "heroLead": "خمس وثلاثون سنة في تأسيس الشركات والاستشارة في الولايات المتحدة وأوروبا — البنية التحتية للبيانات والحكومة الرقمية والطب الدقيق والروبوتات.",
    "cta": "التواصل مع Michael Kofman",
    "introLead": "الرئيس التنفيذي لـ Digital Invest Inc. وعضو مجلس الإدارة. التركيز: التقنيات الناشئة والأمن والبحث وتخصيص رأس المال.",
    "specialtiesEyebrow": "مجالات التركيز",
    "specialtiesTitle": "تخصصات Michael Kofman",
    "area1title": "Board Service",
    "area1desc": "Independent director and board-level work in technology strategy, corporate governance, and growth-stage oversight.",
    "area2title": "CEO & Founder Advisory",
    "area2desc": "Corporate and technology strategy, organizational development, transactions, and applicable capital-markets experience.",
    "area3title": "Technology Due Diligence",
    "area3desc": "Evaluation of infrastructure, data platforms, security architecture, and applied technology based on documented operating experience."
  },
  "insights": {
    "eyebrow": "Perspectives",
    "title": "رؤى",
    "heroTitle": "وجهات نظر تنفيذية",
    "selectedEyebrow": "أبرز المحتوى",
    "selectedTitle": "تقدير مميز",
    "allPressTitle": "جميع التغطيات الصحفية",
    "quotesEyebrow": "في الإعلام",
    "quotesTitle": "تقدير صناعي واقتباسات",
    "articlesEyebrow": "رؤى",
    "articlesTitle": "رؤى تنفيذية",
    "briefsEyebrow": "Executive Briefs",
    "briefsTitle": "Ideas for Leaders",
    "briefsLead": "Short, practical perspectives on governance, technology, healthcare, and company building.",
    "brief1title": "What an IPO Changes",
    "brief1desc": "The operating and governance disciplines that public-market readiness demands.",
    "brief1tag": "Capital Markets",
    "brief2title": "From Genetic Data to Clinical Decisions",
    "brief2desc": "How to build useful health intelligence without outrunning evidence or trust.",
    "brief2tag": "Precision Medicine",
    "brief3title": "AI Strategy Beyond the Pilot",
    "brief3desc": "A framework for turning experiments into governed enterprise capability.",
    "brief3tag": "Artificial Intelligence",
    "readingEyebrow": "Reading List",
    "readingTitle": "Books That Shape Strategic Thinking",
    "r1title": "The Innovator's Dilemma",
    "r1author": "Clayton M. Christensen",
    "r2title": "Thinking, Fast and Slow",
    "r2author": "Daniel Kahneman",
    "r3title": "The Beginning of Infinity",
    "r3author": "David Deutsch",
    "r4title": "Good Strategy/Bad Strategy",
    "r4author": "Richard Rumelt",
    "r5title": "The Structure of Scientific Revolutions",
    "r5author": "Thomas S. Kuhn",
    "newsletterEyebrow": "Occasional Notes",
    "newsletterTitle": "Executive Perspective, Without the Noise",
    "newsletterLead": "Periodic essays and brief observations on technology, governance, and durable company building.",
    "newsletterCta": "Subscribe for Updates",
    "lead": "Substantive writing and executive briefs.",
    "relatedLead": "Recognition, press coverage, and patents are documented separately.",
    "topicsLead": "تعتمد الموضوعات على خبرة تشغيلية موثقة في التكنولوجيا والصحة والبنية التحتية."
  },
  "cta": {
    "eyebrow": "لنعمل معًا",
    "title": "طلب استشارة أو دعوة للتحدث",
    "lead": "للأدوار الاستشارية، ومناصب مجالس الإدارة، والفعاليات الخطابية، والشراكات الاستراتيجية.",
    "button": "تواصل الآن"
  },
  "speaking": {
    "eyebrow": "المشاركات الخطابية",
    "title": "ادعُ Michael Kofman للتحدث",
    "lead": "متاح للمحاضرات حول القيادة التنفيذية، واستراتيجية التكنولوجيا، والصحة الرقمية، وبنية البيانات، وحوكمة الشركات.",
    "topicsEyebrow": "موضوعات التحدث",
    "topicsTitle": "مجالات الخبرة",
    "topicsLead": "تعتمد الموضوعات على عقود من الخبرة في تأسيس وقيادة شركات في الولايات المتحدة وأوروبا.",
    "processEyebrow": "كيفية الدعوة",
    "processTitle": "خطوات الحجز",
    "process1title": "أرسل استفسارًا",
    "process1desc": "استخدم نموذج التواصل أو راسل mkofman@mkofman.com مع تفاصيل الحدث والجمهور والموضوعات المفضلة.",
    "process2title": "تأكيد النطاق",
    "process2desc": "تحديد الصيغة (كلمة رئيسية، أو جلسة نقاش، أو جلسة مجلس إدارة، أو مائدة مستديرة تنفيذية) واللوجستيات.",
    "process3title": "تحقيق قيمة عملية",
    "process3desc": "ترتكز العروض على نتائج فعلية من مشاريع في تخزين البيانات وgovtech والطب الدقيق.",
    "cta": "طلب مشاركة خطابية",
    "catalogEyebrow": "Speaking Topics",
    "catalogTitle": "Executive Conversations for Consequential Change",
    "catalogLead": "Keynotes, board sessions, and leadership briefings tailored to the audience, sector, and decision context.",
    "t1title": "Governing AI Before It Governs the Enterprise",
    "t1audience": "Boards, audit and risk committees",
    "t1format": "Board briefing or keynote",
    "t2title": "From Technology Trend to Enterprise Strategy",
    "t2audience": "CEOs, executive teams, investors",
    "t2format": "Keynote or executive workshop",
    "t3title": "Building Companies Through Market Cycles",
    "t3audience": "Founders, growth leaders, private equity",
    "t3format": "Fireside chat or keynote",
    "t4title": "Precision Medicine: Promise, Proof, and Responsibility",
    "t4audience": "Healthcare leaders, clinicians, innovators",
    "t4format": "Industry keynote or panel",
    "t5title": "The Board's Role in Cyber and Technology Risk",
    "t5audience": "Directors, general counsel, risk leaders",
    "t5format": "Board education session",
    "t6title": "Engineering Trust into Digital Infrastructure",
    "t6audience": "Technology and infrastructure organizations",
    "t6format": "Technical-executive keynote",
    "t7title": "Leading Across Borders and Disciplines",
    "t7audience": "Global leadership teams and universities",
    "t7format": "Keynote or moderated conversation",
    "t8title": "From Founder to Institution Builder",
    "t8audience": "Entrepreneurs and next-generation executives",
    "t8format": "Workshop or fireside chat"
  },
  "caseStudies": {
    "eyebrow": "دراسات الحالة",
    "title": "بناء شركات قابلة للتوسع",
    "lead": "نتائج مختارة من تأسيس وقيادة شركات في البنية التحتية للبيانات والصحة الرقمية.",
    "cs1eyebrow": "بنية البيانات · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "التحدي",
    "cs1challengeText": "بناء شركة تخزين بيانات وتوسيعها في سوق تقني سريع الاندماج.",
    "cs1action": "النهج",
    "cs1actionText": "أسس Michael Kofman شركة 9 Net Avenue Inc. عام 1996. وسرعان ما أصبحت واحدة من أكبر شركات تخزين البيانات في العالم.",
    "cs1result": "النتيجة",
    "cs1resultText": "Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO). Following the transaction, continued work with public companies and board-level roles.",
    "cs2eyebrow": "الصحة الرقمية · 2021 — حتى الآن",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "التحدي",
    "cs2challengeText": "تحويل الأساليب الطبية القديمة عبر العلوم وتقنيات الحمض النووي وAI وML من خلال منصة بيولوجية رياضية جديدة.",
    "cs2action": "النهج",
    "cs2actionText": "تأسست Digital Invest Inc. عام 2021. الطب biomathematical والذكاء genomics ومنصات البيانات clínico.",
    "cs2result": "النتيجة",
    "cs2resultText": "Healthcare Tech Outlook (2023). مشاريع: Human Digital Model و BioMath Life.",
    "cs3eyebrow": "Robotics & UAV · 2026 — Present",
    "cs3title": "AGRON Inc.",
    "cs3challenge": "Challenge",
    "cs3challengeText": "Organizations building UAV and Counter-UAS capability need independent assessment, structured training, and operational architecture — not isolated platforms or ad-hoc piloting.",
    "cs3action": "Approach",
    "cs3actionText": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — consulting, assessment and validation, capability development, training infrastructure, product development support, geospatial systems through ISDRI, and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "cs3result": "Outcome",
    "cs3resultText": "A connected professional services ecosystem spanning five service domains and multiple companies — Global Drone Academy, AGRON, ISDRI, and GUARD — with programmes delivered across 10+ countries and 10,000+ UAV operators, instructors, and specialists trained.",
    "caseStudiesLead": "تأسيس وتوسيع وقيادة شركات من المراحل المبكرة حتى الاستحواذ."
  },
  "mediaKit": {
    "eyebrow": "الصحافة والفعاليات",
    "title": "الحقيبة الإعلامية",
    "lead": "سير رسمية، وصور معتمدة، وبيانات تواصل للصحافة والمؤتمرات واستفسارات مجالس الإدارة.",
    "bioEyebrow": "السير الذاتية",
    "bioTitle": "السير الرسمية",
    "bioShortLabel": "50 كلمة",
    "bioShort": "Michael Kofman هو CEO لشركة Digital Invest Inc. وعضو مجلس إدارة ومستشار ومؤسس لشركات في التكنولوجيا والصحة الرقمية عبر الولايات المتحدة وأوروبا.",
    "bioMediumLabel": "150 كلمة",
    "bioMedium": "Michael Kofman هو CEO لشركة Digital Invest Inc. وعضو في Board of Directors. ويُعد صاحب رؤية تقنية معروفًا بنهجه الديناميكي في فهم متطلبات السوق المعقدة والمتغيرة باستمرار. وبصفته رائد أعمال وعضو مجلس إدارة ومستشارًا لشركات عامة وخاصة، نجح في تأسيس عدة شركات في الولايات المتحدة وأوروبا. وتشمل خبرته القيادة التنفيذية، والتحليل الاستراتيجي للتقنيات والأسواق الناشئة، وأمن المعلومات والخصوصية، والبحث العلمي والتطوير، والإدارة، والاستثمار.",
    "bioLongLabel": "500 كلمة",
    "bioLong": "Michael Kofman is CEO of Digital Invest Inc. and serves on its board. He founded 9 Net Avenue Inc., acquired by Concentric Networks in 2000, and leads Digital Invest in bio-mathematical medicine and genomic intelligence. He founded AGRON Inc. in 2026 for autonomous aerial-ground operations and geospatial systems. Author of technical papers on satellite and optical systems; patent in digital satellite HDTV acquired by Sony. Education: Doctor of Technical Sciences, Ph.D. in Information Technology.",
    "photosEyebrow": "الصور",
    "photosTitle": "صور معتمدة",
    "photosLead": "تتوفر صور شخصية عالية الدقة عند الطلب عبر mkofman@mkofman.com.",
    "contactEyebrow": "تواصل إعلامي",
    "contactTitle": "استفسارات الصحافة",
    "contactLead": "للمقابلات والدعوات الخطابية والطلبات الإعلامية.",
    "downloadEyebrow": "Download",
    "downloadTitle": "One-Page Media Kit",
    "downloadLead": "PDF with official bios, portrait, and press contact — ready to share with organizers and journalists.",
    "downloadCta": "Download PDF",
    "brandEyebrow": "Brand Assets",
    "brandTitle": "Identity & Usage",
    "brandLead": "Approved visual assets for editorial, conference, and partner use. Please preserve proportions, spacing, and original colors.",
    "brandColors": "Official Color Palette",
    "brandLogo": "Primary Logo",
    "brandDownload": "Download Brand Assets"
  },
  "articles": {
    "backLink": "← العودة إلى Insights",
    "article1date": "رؤية تنفيذية",
    "article1title": "من الهندسة إلى البنية التحتية العالمية للبيانات",
    "article1p1": "بدأت مسيرتي في مصنع نيكولايف لبناء السفن في أوكرانيا، حيث طورت أنظمة إرسال واستقبال عبر الأقمار الصناعية لنقل معلومات سرية إلى السفن العسكرية. وتم الاعتراف بي كمهندس إلكترونيات من أعلى مستوى - الفئة السادسة - في مصنع يضم 93,000 موظف.",
    "article1p2": "من 1989 إلى 1994، أسست وقادت Astra Corp، إحدى أكبر الشركات الأوروبية المصنعة لأنظمة الإرسال والاستقبال الفضائية الرقمية. ومن 1994 إلى 1996، وبصفتي CEO لشركة Elitan United Inc.، ساعدت في توسيع الشركة من تسعة موظفين إلى أكثر من 4,000 موظف حول العالم.",
    "article1p3": "In 1996, I founded 9 Net Avenue Inc., a hosting and internet infrastructure company. In 2000 it was acquired by Concentric Networks (NASDAQ: CNTX) and subsequently became part of XO Communications (NASDAQ: XOXO).",
    "article1p4": "بين 2001 و2019، قدت استراتيجية التكنولوجيا لبرامج حكومية ودفاعية وبرامج الشركات المملوكة للدولة، وقادت مبادرات واسعة في البيانات الضخمة والبنية التحتية الآمنة ومراكز البيانات عالية الإنتاجية عبر الولايات المتحدة وأوروبا.",
    "article2date": "الصحة الرقمية",
    "article2title": "الطب الدقيق وتقاطع العلم مع التكنولوجيا",
    "article2p1": "أنا مؤمن بقوة بإمكانات الجمع بين علوم الحياة وأحدث التطورات التقنية. في Biotechnology Group Inc. (2008-2014)، ركزنا على اختبارات وتحليل الحمض النووي، وأتمتة عمليات إعداد الملفات الجينية، والبحث الجيني البشري الشامل.",
    "article2p2": "تحت قيادتي، انطلقت مشاريع ناجحة للاختبارات الجينية في أوكرانيا وروسيا ودول البلطيق. وبالتعاون مع Harvard Medical School وStanford Biomath، لعبت دورًا محوريًا في تطوير تقارير جينية واضحة وسهلة الفهم للأطباء والمرضى.",
    "article2p3": "مع Digital Invest Inc.، تأسست 2021، نعمل في الطب biomathematical — علم وتقنيات DNA وAI وML في الذكاء clínico. Healthcare Tech Outlook (2023).",
    "article2p4": "تطوّر Digital Invest الطب البيو-رياضي عبر مشاريع مثل Human Digital Model وBioMath Life. في 2026 أسس Michael Kofman شركة AGRON Inc. لقيادة Aerial-Ground Robotics Operations Network — قدرات الطائرات بدون طيار والأنظمة الجغرافية المكانية والاستخبارات البحرية على agron1.com."
  },
  "privacy": {
    "eyebrow": "قانوني",
    "title": "سياسة الخصوصية",
    "lead": "كيف يتعامل mkofman.com مع المعلومات عند زيارة الموقع أو إرسال رسالة.",
    "updated": "آخر تحديث: يوليو 2026",
    "s1title": "المعلومات التي نجمعها",
    "s1text": "عند إرسال نموذج، نتلقى الحقول التي تقدمها. إذا كانت التحليلات مفعّلة، قد نجمع بيانات استخدام مجهولة.",
    "s2title": "كيف نستخدم المعلومات",
    "s2text": "للرد على الاستفسارات وتحسين الموقع. لا نبيع البيانات الشخصية.",
    "s3title": "خدمات طرف ثالث",
    "s3text": "قد تُعالَج النماذج عبر Formspree. التحليلات عبر Plausible أو Google Analytics عند التفعيل.",
    "s4title": "حقوقك",
    "s4text": "طلب الوصول أو التصحيح أو الحذف: mkofman@mkofman.com.",
    "s5title": "اتصل بنا",
    "s5text": "أسئلة حول هذه السياسة: mkofman@mkofman.com"
  },
  "board": {
    "eyebrow": "Board & Strategic Advisory",
    "title": "Board & Advisory",
    "lead": "Board & Advisory",
    "rolesEyebrow": "Ways to Engage",
    "rolesTitle": "Board-Level Partnership",
    "role1title": "Independent Director",
    "role1desc": "Constructive oversight, informed challenge, and long-range perspective for public and private company boards.",
    "role2title": "Advisory Board Member",
    "role2desc": "Practical guidance on emerging technologies, product strategy, market positioning, and institutional readiness.",
    "role3title": "CEO & Founder Advisor",
    "role3desc": "Confidential counsel for leaders facing inflection points in scale, governance, succession, financing, or transformation.",
    "role4title": "Special Committee Advisor",
    "role4desc": "Focused support for transactions, technology diligence, cybersecurity exposure, and other high-stakes mandates.",
    "valueEyebrow": "Perspective",
    "valueTitle": "What I Bring to the Table",
    "value1title": "Operator's Discipline",
    "value1desc": "Experience building organizations from inception through global scale, acquisition, and public-market accountability.",
    "value2title": "Technical Fluency",
    "value2desc": "The ability to translate complex systems, scientific claims, and technology risk into clear board decisions.",
    "value3title": "Cross-Market Judgment",
    "value3desc": "A perspective shaped by technology, telecommunications, defense, data infrastructure, and precision medicine.",
    "value4title": "Governance Mindset",
    "value4desc": "A commitment to fiduciary responsibility, candid dialogue, ethical innovation, and durable stakeholder value.",
    "cta": "Discuss a Board Mandate",
    "availability": "Select independent director, advisory board, and strategic counsel engagements are considered.",
    "area1title": "Board Service",
    "area1desc": "Independent director and board-level work in technology strategy, corporate governance, and growth-stage oversight.",
    "area2title": "CEO & Founder Advisory",
    "area2desc": "Corporate and technology strategy, organizational development, transactions, and applicable capital-markets experience.",
    "area3title": "Technology Due Diligence",
    "area3desc": "Evaluation of infrastructure, data platforms, security architecture, and applied technology based on documented operating experience."
  },
  "thesis": {
    "eyebrow": "Leadership Thesis",
    "title": "Build for the Long Term. Decide in the Present.",
    "lead": "Technology changes quickly; the obligations of leadership do not. Durable enterprises unite ambition with discipline, evidence, and accountability.",
    "believeEyebrow": "What I Believe",
    "believeTitle": "Seven Principles for Enduring Organizations",
    "b1title": "Strategy Must Produce Choices",
    "b1text": "A strategy is not a catalog of aspirations. It defines where to compete, what capabilities to build, what not to pursue, and how success will be measured.",
    "b2title": "Technology Is a Governance Issue",
    "b2text": "Boards must understand how technology creates value, concentrates risk, and changes accountability. Delegating every technical question is itself a decision.",
    "b3title": "Evidence Should Outrank Enthusiasm",
    "b3text": "Conviction matters, but markets, systems, and science must be tested. Leaders create mechanisms that expose assumptions before customers or regulators do.",
    "b4title": "Architecture Shapes the Enterprise",
    "b4text": "Technical architecture determines speed, resilience, security, and future options. Shortcuts become institutional constraints long after their original context disappears.",
    "b5title": "Trust Is Operating Infrastructure",
    "b5text": "Trust is built through clear commitments, reliable execution, responsible data practices, and direct communication when conditions change.",
    "b6title": "Capital Must Follow Capability",
    "b6text": "Growth investment should reinforce differentiated capabilities and measurable demand, not substitute spending for product-market understanding.",
    "b7title": "Leaders Design Their Successors",
    "b7text": "The strongest leaders build systems, talent, and decision quality that endure beyond their own involvement.",
    "rejectEyebrow": "What I Reject",
    "rejectTitle": "Three Expensive Illusions",
    "r1title": "Innovation Theater",
    "r1text": "Announcements, pilots, and fashionable language do not equal capability. Innovation must improve an outcome that matters.",
    "r2title": "Growth Without Governance",
    "r2text": "Scale magnifies unresolved weaknesses. Controls, culture, and accountability should mature before complexity makes correction costly.",
    "r3title": "False Certainty",
    "r3text": "Executive confidence should not erase uncertainty. Strong decisions make assumptions visible and preserve options when facts change.",
    "horizonEyebrow": "The Horizon",
    "horizonTitle": "The Next Advantage Is Responsible Integration",
    "horizonText": "The defining opportunity is not any single technology. It is the disciplined integration of AI, advanced data systems, biology, and automation into institutions people can trust."
  },
  "press": {
    "eyebrow": "Press & Media",
    "title": "Selected Coverage",
    "lead": "A concise archive of third-party recognition and reporting across technology, entrepreneurship, and precision medicine.",
    "archiveEyebrow": "Archive",
    "y2023type": "Industry Recognition",
    "y2023title": "Top 10 Precision Medicine Companies",
    "y2023desc": "Healthcare Tech Outlook recognized Digital Invest Inc. among leading U.S. companies advancing precision medicine and digital health.",
    "y2023link": "View feature",
    "y2001type": "Executive Award",
    "y2001title": "Entrepreneur of the Year",
    "y2001desc": "Entrepreneur Magazine recognition.",
    "y2001link": "View archive",
    "y1999type": "Biographical Recognition",
    "y1999title": "Who's Who in America",
    "y1999desc": "Recognition beginning in 1999, followed by listings in Who's Who in the World and Who's Who in Science and Engineering.",
    "clipEyebrow": "From the Archive",
    "clipMeta": "Industry Feature · DataPeer Inc.",
    "clipTitle": "State of the Storage Industry",
    "clipLead": "An early interview with Michael Kofman as Founder, Chairman, and CEO of DataPeer Inc. — reflecting on fiber optics, satellite transmission, SAN, and the emerging storage market.",
    "clipBody": "The feature notes recognition as Entrepreneur of the Year by Entrepreneur Magazine (2001) and discusses DataPeer’s approach to mission-critical storage, iSCSI, and business continuity.",
    "clipOpen": "Open full page scan →",
    "y2000type": "Interview",
    "y2000title": "State of the Storage Industry",
    "y2000desc": "Featured interview as Founder, Chairman, and CEO of DataPeer Inc. on storage networks, iSCSI, and business continuity."
  },
  "ip": {
    "eyebrow": "Intellectual Property",
    "title": "Applied Ideas, Documented",
    "lead": "Selected patents, publications, and research programs connecting engineering rigor with practical business and societal outcomes.",
    "patentEyebrow": "Patents",
    "patentTitle": "Protected Inventions",
    "patentIntro": "Patent work reflects a sustained focus on systems that improve the collection, movement, protection, and interpretation of information.",
    "publicationsEyebrow": "Publications",
    "publicationsTitle": "Technical & Executive Writing",
    "publicationsIntro": "Published work translates complex technical subjects into methods, frameworks, and decisions useful to practitioners and leaders.",
    "researchEyebrow": "Research",
    "researchTitle": "Interdisciplinary Programs",
    "researchIntro": "Research initiatives span secure communications, predictive analytics, genetic interpretation, human digital modeling, and autonomous systems."
  },
  "testimonials": {
    "t1quote": "Michael combines an engineer's precision with the judgment of an experienced chief executive. He asks the questions that improve the decision.",
    "t1name": "Board Colleague",
    "t1role": "Public Technology Company",
    "t2quote": "His ability to connect science, product, governance, and commercial reality brings uncommon clarity to complex initiatives.",
    "t2name": "Strategic Partner",
    "t2role": "Digital Health Sector",
    "t3quote": "Michael is direct, thoughtful, and focused on durable value. He helps leadership teams see both the opportunity and the obligation.",
    "t3name": "Executive Collaborator",
    "t3role": "Global Infrastructure"
  },
  "deck": {
    "title": "Michael Kofman",
    "subtitle": "تنفيذي تقني · مؤسس · مستشار",
    "thesis": "التكنولوجيا والأعمال والاستثمار في البنية التحتية وعلوم الحياة والأنظمة المستقلة.",
    "contact": "Confidential discussion: contact Michael Kofman through mkofman.com"
  },
  "briefIpo": {
    "title": "What an IPO Changes",
    "desc": "Public markets do not merely change a company's capital structure; they change its operating contract.",
    "p1": "An initial public offering is often described as a financing event. In practice, it is an institutional transition. Forecasting, controls, disclosure, governance, and executive communication must become repeatable before the listing, not improvised afterward.",
    "p2": "Readiness begins with decision quality. Management needs reliable metrics, clear ownership, and an operating cadence that can explain both performance and variance. A company that cannot reconcile its internal narrative will struggle to communicate a credible external one.",
    "p3": "The board's role also changes. Directors must balance growth with oversight, understand material technology and market risks, and ensure that incentives support durable value rather than a single quarter.",
    "p4": "The strongest public companies preserve entrepreneurial speed while adding institutional discipline. The objective is not bureaucracy; it is trustworthy execution at a higher level of accountability.",
    "eyebrow": "ملخص تنفيذي"
  },
  "briefGenetic": {
    "title": "From Genetic Data to Clinical Decisions",
    "desc": "The value of genomic information depends on interpretation, evidence, and responsible integration into care.",
    "p1": "Genetic data is abundant; clinically useful meaning is scarce. A result becomes valuable only when it is interpreted in context, connected to validated evidence, and presented in a form that supports a real decision.",
    "p2": "That translation requires collaboration across molecular biology, medicine, statistics, software engineering, and patient communication. Weakness in any layer can turn technical sophistication into clinical confusion.",
    "p3": "Privacy and consent are architectural requirements, not legal footnotes. Systems must limit unnecessary exposure, make data provenance visible, and preserve patient agency as information moves between laboratories, platforms, and care teams.",
    "p4": "Precision medicine will advance through measured integration: better evidence, transparent models, interoperable workflows, and outcomes that clinicians and patients can evaluate. Trust is part of the product.",
    "eyebrow": "ملخص تنفيذي"
  },
  "briefAi": {
    "title": "AI Strategy Beyond the Pilot",
    "desc": "Enterprise AI creates value when ownership, data, workflow, and governance mature together.",
    "p1": "Many AI initiatives begin with a compelling demonstration and stall before production. The missing element is rarely the model alone. Sustainable value requires a defined business outcome, accountable owner, dependable data, and a workflow people will actually use.",
    "p2": "Leaders should distinguish automation, prediction, and decision support. Each carries different requirements for accuracy, explainability, human review, and risk. A single governance template will not fit every use case.",
    "p3": "Measurement must include more than technical performance. Adoption, cycle time, error rates, customer impact, security exposure, and the cost of supervision determine whether an AI capability is economically and institutionally sound.",
    "p4": "The winning approach is a managed portfolio: scale proven use cases, stop weak ones early, and maintain explicit boundaries for high-consequence decisions. AI strategy is ultimately operating strategy.",
    "eyebrow": "ملخص تنفيذي"
  }
};
