window.__LANG_en = {
  "ui": {
    "toggleTheme": "Toggle light/dark theme",
    "selectLanguage": "Select language",
    "messageSent": "Message Sent",
    "sendMessage": "Send Message",
    "toggleNav": "Toggle navigation",
    "sending": "Sending…",
    "formError": "Could not send. Please email directly.",
    "present": "Present"
  },
  "nav": {
    "home": "Home",
    "about": "About",
    "ventures": "Ventures",
    "career": "Career",
    "recognition": "Recognition",
    "contact": "Contact",
    "consulting": "Consulting",
    "insights": "Insights",
    "speaking": "Speaking",
    "caseStudies": "Case Studies",
    "mediaKit": "Media Kit",
    "groupMain": "Main",
    "groupServices": "Services",
    "groupWork": "Work"
  },
  "footer": {
    "navigation": "Navigation",
    "ventures": "Ventures",
    "connect": "Connect",
    "desc": "CEO, strategic technologist, and award-winning entrepreneur building the future of technology, digital health, and infrastructure.",
    "copyright": "© 2025–2026 Michael Kofman. All Rights Reserved.",
    "writeTitle": "Write to Me",
    "writeEmail": "Your email",
    "writeMessage": "Your message",
    "writeSend": "Send",
    "writeSuccess": "Thank you — your message has been sent.",
    "more": "More",
    "privacy": "Privacy Policy"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — CEO & Strategic Technologist",
      "description": "Official website of Michael Kofman — award-winning CEO, founder, and strategic technologist."
    },
    "about": {
      "title": "About — Michael Kofman",
      "description": "Biography of Michael Kofman — CEO of Digital Invest Inc. — technology visionary and award-winning entrepreneur."
    },
    "ventures": {
      "title": "Ventures — Michael Kofman",
      "description": "Companies founded and led by Michael Kofman."
    },
    "career": {
      "title": "Career — Michael Kofman",
      "description": "Professional career timeline of Michael Kofman."
    },
    "recognition": {
      "title": "Recognition — Michael Kofman",
      "description": "Awards, honors, and recognition received by Michael Kofman."
    },
    "contact": {
      "title": "Contact — Michael Kofman",
      "description": "Contact Michael Kofman for advisory roles, speaking engagements, and business inquiries."
    },
    "consulting": {
      "title": "Consulting — Michael Kofman",
      "description": "Advisory roles, board positions, speaking engagements, and strategic partnerships with Michael Kofman."
    },
    "insights": {
      "title": "Insights — Michael Kofman",
      "description": "Publications, press features, patents, and industry recognition from Michael Kofman."
    },
    "speaking": {
      "title": "Speaking — Michael Kofman",
      "description": "Invite Michael Kofman to speak on executive leadership, technology strategy, digital health, and board governance."
    },
    "caseStudies": {
      "title": "Case Studies — Michael Kofman",
      "description": "Case studies from Michael Kofman's career — 9 Net Avenue Inc. and Digital Invest Inc."
    },
    "mediaKit": {
      "title": "Media Kit — Michael Kofman",
      "description": "Official biographies, photos, and contact information for press and event organizers."
    },
    "article1": {
      "title": "From Engineering to Global Infrastructure — Michael Kofman",
      "description": "Michael Kofman on a career path from satellite engineering to founding global data infrastructure companies."
    },
    "article2": {
      "title": "Precision Medicine and Technology — Michael Kofman",
      "description": "Michael Kofman on combining life sciences with AI, ML, and DNA technologies in modern medicine."
    },
    "privacy": {
      "title": "Privacy Policy — Michael Kofman",
      "description": "Privacy policy for mkofman.com — how we handle contact form data and site analytics."
    }
  },
  "home": {
    "heroEyebrow": "Official Website of Michael Kofman",
    "heroTitle1": "Visionary Leadership.",
    "heroTitle2": "Strategic Innovation.",
    "heroCta": "Discover My Story",
    "heroAlt": "Michael Kofman — CEO and Strategic Technologist",
    "quote1text": "A technology visionary recognized for his dynamic approach to understanding the ever-changing demands of today's complex marketplace.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "Entrepreneur of the Year — recognized for leadership and breakthrough achievements in platform innovation and infrastructure.",
    "quote2author": "Entrepreneur Magazine, 1999 — 2001",
    "quote3text": "Digital Invest Inc. named among America's Top 10 Best Companies in Precision Medicine and Digital Health.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "Known for uniting engineering precision with business strategy, delivering high-value outcomes, and building future-oriented companies from scratch.",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "Meet Michael Kofman",
    "aboutTitle": "A Legacy of Innovation and Leadership",
    "aboutLead1": "Michael Kofman is a technological visionary renowned for his dynamic approach to understanding the ever-evolving needs of today's complex market. An entrepreneur, board member, and advisor for both public and private companies, he has successfully established several companies in the United States and Europe.",
    "aboutLead2": "From founding one of the world's largest Data Storage companies — acquired at a peak market value of $19.5 billion — to leading Digital Invest Inc. in data storage and advanced technology innovation, his career spans executive acumen, strategic technology, and transformative leadership. Digital Invest comprises diverse innovative projects, including Human Digital Model, BioMath Life, and Aero-Ground Robotics Operations Network.",
    "aboutLink": "Read Full Biography",
    "expertiseEyebrow": "Multifaceted Expertise",
    "expertiseTitle": "Executive Leadership Across Industries",
    "expertiseLead": "Explore Michael Kofman's diverse expertise as a CEO, technologist, advisor, and investor. With decades of experience, he provides unparalleled insight and guidance to drive success.",
    "exp1title": "CEO & Founder",
    "exp1desc": "Founded and scaled multiple companies from inception through IPO, achieving consistent financial growth and global presence across technology and healthcare sectors.",
    "exp1link": "View Ventures →",
    "exp2title": "Technology Architect",
    "exp2desc": "Designed secure communications, predictive analytics engines, and national-level data integration platforms for government, military, and telecom sectors.",
    "exp2link": "View Career →",
    "exp3title": "Digital Health",
    "exp3desc": "Leading the transformation of medicine through AI, ML, and DNA technologies. Collaborated with Harvard Medical School and Stanford Biomath on genetic reporting.",
    "exp3link": "Digital Invest →",
    "exp4title": "Board Advisor",
    "exp4desc": "Serves on boards and advises public and private companies on strategic direction, corporate governance, and technology-driven growth initiatives.",
    "exp4link": "Consulting →",
    "stat1": "Years of Leadership",
    "stat2": "Companies Founded",
    "stat3": "Peak Market Value",
    "stat4": "Employees Scaled",
    "recEyebrow": "Recognition",
    "recTitle": "Awards & Honors",
    "recLead": "Consistently recognized for exceptional achievements in business creation, innovation, and executive leadership.",
    "award1title": "Entrepreneur of the Year",
    "award1desc": "Entrepreneur Magazine, 1999 — 2001",
    "award2title": "Top 10 Precision Medicine",
    "award2desc": "Digital Invest Inc. — U.S., 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "View All Recognition",
    "heroSub": "CEO, board advisor, and strategic technologist for public and private companies in technology, data storage, and digital health.",
    "primaryCta": "Request Advisory",
    "secondaryCta": "View Case Studies",
    "featuredEyebrow": "As Featured In",
    "caseStudiesEyebrow": "Proven Outcomes",
    "caseStudiesTitle": "Case Studies",
    "caseStudiesLead": "Founding, scaling, and leading companies from inception through acquisition and IPO.",
    "caseStudiesLink": "View All Case Studies →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "Built one of the world's largest Data Storage companies — acquired at a peak market value of $19.5 billion.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "Founded and scaled from inception through IPO — Top 10 U.S. Precision Medicine Company, 2023."
  },
  "about": {
    "eyebrow": "About Michael Kofman",
    "title": "A Legacy of Innovation",
    "lead": "Technology visionary, entrepreneur, and executive leader with a career spanning over three decades across continents and industries.",
    "glance": "At a Glance",
    "role": "Current Role",
    "roleVal": "CEO & Board Member · Digital Invest Inc.",
    "location": "Location",
    "locationVal": "Charlotte, North Carolina",
    "education": "Education",
    "educationVal": "Doctor of Technical Sciences (2009)\nPh.D. in Information Technology (2004)\nMaster's in Electronic Engineering",
    "university": "University",
    "universityVal": "Ukrainian State Marine Technical University",
    "languages": "Languages",
    "languagesVal": "English, Russian, Ukrainian",
    "contactLabel": "Contact",
    "bioP1": "Michael Kofman is the CEO of Digital Invest Inc. and serves on its Board of Directors. A technological visionary, he is renowned for his dynamic approach to understanding the ever-evolving needs of today's complex market. His expertise spans executive acumen, strategic analysis of emerging technologies and markets, information security and privacy, research, science and development, administration, and investment.",
    "bioP2": "As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. Recently, he embarked on an ambitious project with the creation of Digital Invest, a company dedicated to the bio-mathematical sphere, aimed at transforming outdated approaches in medicine using the latest advancements in science, DNA technologies, AI, and ML.",
    "secBioTitle": "Precision Medicine & Biotechnology",
    "secBioP1": "Prior to Digital Invest, he played a significant role in the success of Biotechnology Group Inc. (2008–2014), a company committed to DNA testing and analysis, process automation for creating genetic profiles, and comprehensive human genetic research. Mr. Kofman is a firm believer in the potential of combining life sciences with the latest technological advancements.",
    "secBioP2": "Under his leadership, successful genetic testing projects have been initiated in Ukraine, Russia, and the Baltic countries. This unique experience is continually enriched with modern technologies and new equipment. In collaboration with Harvard Medical School and Stanford Biomath, Mr. Kofman played a crucial role in developing easily understandable genetic reports for both doctors and patients. This innovative approach has been widely adopted by leading laboratories in the United States and abroad.",
    "secTechTitle": "Technology & Infrastructure",
    "secTechP1": "From 2001 to 2019, Mr. Kofman directed technology strategy for government, defense, and state-owned enterprise programs — including complex technical initiatives for government-owned companies. Following September 11, 2001, he led large-scale government projects centered on big data, secure infrastructure, and high-throughput data centers across the United States and Europe.",
    "secTechP2": "In 2006, Mr. Kofman founded XIBI Group Inc. — a technology company where he served on the board of directors. The American company specializes in data storage and big data management services for large commercial and government organizations.",
    "secTechP3": "From 2000 to 2004, Mr. Kofman led DataPeer Inc. — a data management and storage company offering a wide range of services related to information storage for small and medium-sized businesses. At DataPeer he developed unique technological solutions that facilitated faster information tracking and easier data accessibility for individual end-users and government institutions worldwide.",
    "secTechP4": "In 1996, Mr. Kofman founded 9 Net Avenue Inc. It quickly became one of the world's largest hosting companies. By 2000, 9 Net Avenue was acquired by Concentric Networks (NASDAQ: CNTX), and then by XO Communications (NASDAQ: XOXO), reaching a peak market value of $19.5 billion.",
    "secPost9NetP1": "Following the acquisition of 9 Net Avenue, Mr. Kofman gained extensive experience working with public companies, serving on boards of directors, and participating in strategic decision-making at the highest executive level.",
    "secEarlyTitle": "Early Career & Engineering",
    "secEarlyP1": "From 1994 to 1996, Mr. Kofman served as CEO and Director of Information Technology at Elitan United Inc. — an IT company from Massachusetts, which provided comprehensive strategies and technological services for leading global organizations. He played a pivotal role in developing and managing a scalable infrastructure, leading the company's growth from just nine to over 4,000 employees worldwide.",
    "secEarlyP2": "From 1989 to 1994, he was the founder and CEO of Astra Corp, one of the largest manufacturers of digital transceiver satellite systems in Europe, earning international recognition in the field of satellite devices. His responsibilities encompassed research, operating system development, network software applications, and overall technical strategy.",
    "secEarlyP3": "From 1984 to 1989, Mr. Kofman worked at the shipbuilding plant in Nikolaev, Ukraine, where he actively participated in the development and creation of satellite transceiver systems for transmitting classified information to military ships and back. He was recognized as an electronics engineer of the highest level, receiving the 6th category — the highest recognition at the plant, where 93 thousand people worked.",
    "secResearchTitle": "Research & Patents",
    "secResearchP1": "Michael Kofman is the author of technical papers focused on satellite and optical systems for data transmission. He also received a patent in the field of digital satellite high-definition television (HDTV) systems, which was subsequently acquired by Sony."
  },
  "ventures": {
    "eyebrow": "Portfolio of Ventures",
    "title": "Building Companies That Transform Industries",
    "lead": "From precision medicine to global telecommunications — a track record of founding, scaling, and leading companies to market-defining success.",
    "v1year": "2021 — Present",
    "v1role": "Founder & CEO · Board Member",
    "v1p1": "Founded and scaled Digital Invest from inception through a successful IPO. The company is dedicated to the bio-mathematical sphere, transforming medicine through AI, ML, and DNA technologies.",
    "v1highlight": "Top 10 U.S. Precision Medicine Company — 2023",
    "v2year": "2008 — 2014",
    "v2role": "CEO & CTO",
    "v2p1": "DNA testing and analysis, automation of genetic profiling, and comprehensive human genetic research. Initiated genetic testing projects in Ukraine, Russia, and the Baltic countries.",
    "v2p2": "Collaborated with Harvard Medical School and Stanford Biomath on genetic reports adopted by leading laboratories worldwide.",
    "v2highlight": "Harvard Medical School & Stanford Biomath Partner",
    "v3year": "2006 — 2011",
    "v3role": "Founder & CEO · Board of Directors",
    "v3p1": "Data storage and big data management services for large commercial and government organizations. Established the company as a trusted provider of enterprise data solutions.",
    "v3highlight": "Enterprise & Government Data Solutions",
    "v4year": "2000 — 2004",
    "v4role": "Founder & CEO",
    "v4p1": "Data management and storage for small and medium-sized businesses. Developed solutions for faster information tracking and easier data accessibility for end-users and government institutions worldwide.",
    "v4highlight": "Global Data Management Platform",
    "v5year": "1996 — 2000",
    "v5role": "Founder & CEO",
    "v5p1": "Built one of the world's largest hosting companies. By 2000, acquired by Concentric Networks (NASDAQ: CNTX), then XO Communications (NASDAQ: XOXO), reaching a peak market value of $19.5 billion.",
    "v5highlight": "Acquired · Peak Value $19.5 Billion",
    "v6year": "1994 — 1996",
    "v6role": "CEO & Director of Information Technology",
    "v6p1": "IT company from Massachusetts providing comprehensive strategies and technological services for leading global organizations. Led scalable infrastructure development and global IT operations.",
    "v6highlight": "Global IT Strategy & Infrastructure",
    "v7year": "1989 — 1994",
    "v7role": "Founder & CEO",
    "v7p1": "One of Europe's largest manufacturers of digital transceiver satellite systems. Led research, operating system development, network software applications, and overall technical strategy.",
    "v7highlight": "European Satellite Systems Leader",
    "v8year": "1984 — 1989",
    "v8role": "Electronics Engineer · Highest Category (6th)",
    "v8p1": "Development and creation of satellite transceiver systems for transmitting classified information to military ships. Recognized as an electronics engineer of the highest level at a plant of 93,000 employees.",
    "v8highlight": "Military Satellite Systems Engineering"
  },
  "career": {
    "eyebrow": "Professional Journey",
    "title": "Three Decades of Executive Leadership",
    "lead": "From military satellite engineering to founding global technology companies and leading precision medicine innovation.",
    "timelineEyebrow": "Career Timeline",
    "timelineTitle": "Key Milestones",
    "strengthsEyebrow": "Core Strengths",
    "strengthsTitle": "Areas of Expertise",
    "t1year": "2021 — Present",
    "t1title": "Digital Invest Inc.",
    "t1role": "Founder & CEO",
    "t1desc": "Founded and scaled the company from inception through a successful IPO. Led the full public offering process — legal structuring, financial compliance, investor roadshows, and SEC coordination. Directed design, construction, and operations of multiple data centers in the U.S. and Europe. Built enterprise-level software systems for automation, predictive monitoring, and centralized data control. Achieved consistent financial growth, positioning the company among Top 10 Precision Medicine Companies in the U.S. (2023).",
    "t2year": "2001 — 2019",
    "t2title": "GovTech, Defense & State Programs",
    "t2role": "Chief Technology Advisor / Program Architect",
    "t2desc": "Directed technology strategy and delivery for classified and high-sensitivity programs involving U.S. government agencies, allied defense systems, and state-owned enterprises. Headed complex technical projects for government-owned companies across multiple sectors. Following September 11, 2001, led large-scale government initiatives centered on big data, secure communications, predictive analytics, and national-level data integration — including the design, construction, and operation of high-throughput data centers across the United States and Europe. Interfaced with military program officers, technology vendors, and regulatory entities.",
    "t3year": "2008 — 2014",
    "t3title": "Biotechnology Group Inc.",
    "t3role": "CEO & CTO",
    "t3desc": "Led DNA testing and analysis, automation of genetic profiling, and comprehensive human genetic research. Initiated genetic testing projects in Ukraine, Russia, and the Baltic countries. Collaborated with Harvard Medical School and Stanford Biomath to develop understandable genetic reports adopted by leading laboratories worldwide.",
    "t4year": "2000 — 2012",
    "t4title": "Telecommunications Projects",
    "t4role": "VP of Technology / Regional CTO — Eastern Europe & CIS",
    "t4desc": "Directed national infrastructure rollouts across Canada, Italy, Switzerland, Ukraine, and the Baltic Republics. Oversaw 1,000+ engineering and deployment staff across telecom operations including switching systems, broadband expansion, and cross-border connectivity. Implemented core systems for network redundancy, uptime optimization, and intelligent routing.",
    "t5year": "2006 — 2011",
    "t5title": "XIBI Group Inc.",
    "t5role": "Founder & CEO · Board of Directors",
    "t5desc": "Founded a technology company specializing in data storage and big data management services for large commercial and government organizations. Established the company as a trusted provider of enterprise data solutions.",
    "t6year": "2000 — 2004",
    "t6title": "DataPeer Inc.",
    "t6role": "Founder & CEO",
    "t6desc": "Established a data management and storage company for SMBs. Developed unique technological solutions for faster information tracking and easier data accessibility for end-users and government institutions worldwide.",
    "t7year": "1996 — 2000",
    "t7title": "9 Net Avenue Inc.",
    "t7role": "Founder & CEO",
    "t7desc": "Built one of the world's largest hosting companies. By 2000, acquired by Concentric Networks (NASDAQ: CNTX), then XO Communications (NASDAQ: XOXO), reaching a peak market value of $19.5 billion.",
    "t8year": "1994 — 1996",
    "t8title": "Elitan United Inc.",
    "t8role": "CEO & Director of Information Technology",
    "t8desc": "Led comprehensive IT strategies and technological services for leading global organizations from Massachusetts during a period of rapid expansion, building scalable infrastructure and global IT operations.",
    "t9year": "1989 — 1994",
    "t9title": "Astra Corp",
    "t9role": "Founder & CEO",
    "t9desc": "Founded one of Europe's largest manufacturers of digital transceiver satellite systems. Led research, operating system development, network software applications, and overall technical strategy, earning international recognition.",
    "t10year": "1984 — 1989",
    "t10title": "Nikolaev Shipbuilding Plant",
    "t10role": "Electronics Engineer — 6th Category (Highest)",
    "t10desc": "Developed and created satellite transceiver systems for transmitting classified information to military ships. Recognized as an electronics engineer of the highest level at a plant of 93,000 employees — the beginning of a distinguished career in technology and innovation.",
    "s1title": "Executive Leadership",
    "s1desc": "Dual-sided CEO/CTO management across public and private companies, from startup to IPO and beyond.",
    "s2title": "IPO & Financial Scaling",
    "s2desc": "Full public offering execution — legal structuring, SEC coordination, investor roadshows, and compliance.",
    "s3title": "Platform Architecture",
    "s3desc": "Scalable systems design for enterprise automation, predictive monitoring, and centralized data control.",
    "s4title": "Secure Infrastructure",
    "s4desc": "Data center development and operations for government, military, and high-security commercial platforms."
  },
  "recognition": {
    "eyebrow": "Awards & Honors",
    "title": "Recognition of Excellence",
    "lead": "Decades of exceptional achievements in business creation, innovation, and executive leadership — consistently recognized by industry and peers.",
    "industryEyebrow": "Industry Awards",
    "industryTitle": "Major Honors",
    "ipEyebrow": "Intellectual Property",
    "ipTitle": "Patents & Publications",
    "eduEyebrow": "Education",
    "eduTitle": "Academic Credentials",
    "pressEyebrow": "Press & Media",
    "pressTitle": "Featured In",
    "moreLink": "View patents, publications, and press features on Insights →",
    "a1title": "Entrepreneur of the Year",
    "a1desc": "Entrepreneur Magazine, 1999 — 2001 — leadership and breakthrough achievements in platform innovation and infrastructure.",
    "a2title": "Top 10 U.S. Precision Medicine Company",
    "a2desc": "Digital Invest Inc. recognized among America's 10 Best Companies in Precision Medicine and Digital Health — 2023.",
    "a3title": "Who's Who in America",
    "a3desc": "Listed, 1999 — 2018 — for exceptional achievements in business creation and development.",
    "a4title": "Who's Who in the World",
    "a4desc": "Listed, 2000 — 2004 — among global leaders in science, engineering, and business innovation.",
    "a5title": "Who's Who in Science & Engineering",
    "a5desc": "Listed, 2000 — 2014 — for contributions to technology, satellite systems, and digital infrastructure.",
    "a6title": "Electronics Engineer — 6th Category",
    "a6desc": "Highest recognition at Nikolaev Shipbuilding Plant (93,000 employees) for satellite transceiver systems engineering.",
    "ip1year": "Patent",
    "ip1title": "Digital Satellite HDTV Systems",
    "ip1role": "Subsequently Acquired by Sony",
    "ip1desc": "Received a patent in the field of digital satellite high-definition television (HDTV) systems. The patent was subsequently acquired by Sony Corporation, validating the innovation's commercial significance.",
    "ip2year": "Publications",
    "ip2title": "Technical Papers",
    "ip2role": "Satellite & Optical Systems",
    "ip2desc": "Author of technical papers focused on satellite and optical systems for data transmission. Research contributions span signal processing, simulation modeling, and automation platforms applied in telecommunications, national infrastructure, and digital health.",
    "ip3year": "Research",
    "ip3title": "International Collaborations",
    "ip3role": "U.S. & Europe",
    "ip3desc": "Engaged in international research collaborations and knowledge transfer initiatives. Developed embedded engineering systems for data acquisition, predictive diagnostics, and cloud-based orchestration across multiple industries.",
    "edu1title": "Doctor of Technical Sciences",
    "edu1desc": "2009 — Ukrainian State Marine Technical University",
    "edu2title": "Ph.D. in Information Technology",
    "edu2desc": "2004 — Ukrainian State Marine Technical University",
    "edu3title": "Master's Degrees",
    "edu3desc": "Electronics, Digital Satellite Systems, and Economics",
    "press1title": "Healthcare Tech Outlook",
    "press1role": "Digital Invest Inc. Feature",
    "press1desc": "Digital Invest Inc. featured as one of America's leading companies in precision medicine and digital health, recognized for innovative approaches to transforming medicine through AI, ML, and DNA technologies.",
    "press1link": "Read Feature →",
    "press2title": "Top Precision Medicine Solutions",
    "press2role": "Industry Recognition",
    "press2desc": "Named among the top precision medicine solutions companies, highlighting Digital Invest's role in advancing bio-mathematical approaches to modern healthcare.",
    "press2link": "View Listing →"
  },
  "contact": {
    "eyebrow": "Get in Touch",
    "title": "Let's Connect",
    "lead": "For advisory roles, board positions, speaking engagements, and strategic partnerships.",
    "infoTitle": "Reach Out Directly",
    "email": "Email",
    "phone": "Phone",
    "location": "Location",
    "locationVal": "Charlotte, North Carolina\nUnited States",
    "linkedin": "LinkedIn",
    "company": "Current Company",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member",
    "formTitle": "Send a Message",
    "formLead": "Fill out the form below and I'll get back to you promptly.",
    "firstName": "First Name",
    "lastName": "Last Name",
    "emailLabel": "Email Address",
    "subject": "Subject",
    "message": "Message",
    "inquiryType": "Inquiry Type",
    "inquiryAdvisory": "Advisory / Board Role",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "infoEyebrow": "Contact Information"
  },
  "consulting": {
    "eyebrow": "Advisory Services",
    "title": "Consulting",
    "heroEyebrow": "Strategic Business Guidance",
    "heroTitle": "Expert Consulting with Michael Kofman",
    "heroLead": "Michael Kofman is a technological visionary renowned for his dynamic approach to understanding the ever-evolving needs of today's complex market. An entrepreneur, board member, and advisor for both public and private companies, he has successfully established several companies in the United States and Europe.",
    "cta": "Contact Michael Kofman",
    "introLead": "Michael Kofman is the CEO of Digital Invest Inc. and serves on its Board of Directors. His expertise spans executive acumen, strategic analysis of emerging technologies and markets, information security and privacy, research, science and development, administration, and investment.",
    "specialtiesEyebrow": "Areas of Focus",
    "specialtiesTitle": "What Michael Kofman Specializes In"
  },
  "insights": {
    "eyebrow": "Thought Leadership",
    "title": "Insights",
    "heroTitle": "Insights for Success",
    "selectedEyebrow": "Selected Highlights",
    "selectedTitle": "Featured Recognition",
    "allPressTitle": "All Press Features",
    "quotesEyebrow": "In the Media",
    "quotesTitle": "Industry Recognition & Quotes",
    "articlesEyebrow": "Perspectives",
    "articlesTitle": "Executive Perspectives"
  },
  "cta": {
    "eyebrow": "Work Together",
    "title": "Request Advisory or a Speaking Engagement",
    "lead": "For advisory roles, board positions, speaking engagements, and strategic partnerships.",
    "button": "Get in Touch"
  },
  "speaking": {
    "eyebrow": "Speaking Engagements",
    "title": "Invite Michael Kofman to Speak",
    "lead": "Available for speaking engagements on executive leadership, technology strategy, digital health, data infrastructure, and corporate governance.",
    "topicsEyebrow": "Speaking Topics",
    "topicsTitle": "Areas of Expertise",
    "topicsLead": "Topics draw on decades of experience founding and leading companies in the United States and Europe.",
    "processEyebrow": "How to Invite",
    "processTitle": "Booking Process",
    "process1title": "Send an Inquiry",
    "process1desc": "Use the contact form or email mkofman@mkofman.com with event details, audience, and preferred topics.",
    "process2title": "Confirm Scope",
    "process2desc": "Discuss format — keynote, panel, board session, or executive roundtable — and logistics.",
    "process3title": "Deliver Value",
    "process3desc": "Presentations are grounded in real outcomes from ventures across data storage, govtech, and precision medicine.",
    "cta": "Request a Speaking Engagement"
  },
  "caseStudies": {
    "eyebrow": "Case Studies",
    "title": "Building Companies That Scale",
    "lead": "Selected outcomes from founding and leading companies across data infrastructure and digital health.",
    "cs1eyebrow": "Data Infrastructure · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "Challenge",
    "cs1challengeText": "Build and scale a Data Storage company in a rapidly consolidating technology market.",
    "cs1action": "Approach",
    "cs1actionText": "Founded 9 Net Avenue Inc. in 1996. The company quickly became one of the world's largest Data Storage companies.",
    "cs1result": "Outcome",
    "cs1resultText": "By 2000, acquired by Concentric Networks (NASDAQ: CNTX), then XO Communications (NASDAQ: XOXO), reaching a peak market value of $19.5 billion. Following the acquisition, gained extensive experience working with public companies, serving on boards of directors, and participating in strategic decision-making at the highest executive level.",
    "cs2eyebrow": "Digital Health · 2021 — Present",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "Challenge",
    "cs2challengeText": "Transform outdated approaches in medicine using science, DNA technologies, AI, and ML through a new bio-mathematical platform.",
    "cs2action": "Approach",
    "cs2actionText": "Founded and scaled Digital Invest Inc. from inception through a successful IPO. Led the full public offering process — legal structuring, financial compliance, investor roadshows, and SEC coordination. Directed design, construction, and operations of multiple data centers in the U.S. and Europe.",
    "cs2result": "Outcome",
    "cs2resultText": "Achieved consistent financial growth, positioning the company among Top 10 Precision Medicine Companies in the U.S. (2023). Digital Invest comprises diverse innovative projects, including Human Digital Model, BioMath Life, and Aero-Ground Robotics Operations Network."
  },
  "mediaKit": {
    "eyebrow": "Press & Events",
    "title": "Media Kit",
    "lead": "Official biographies, imagery, and contact details for press, conferences, and board inquiries.",
    "bioEyebrow": "Biographies",
    "bioTitle": "Official Bios",
    "bioShortLabel": "50 Words",
    "bioShort": "Michael Kofman is CEO of Digital Invest Inc. and a board member, advisor, and founder of companies in technology and digital health across the U.S. and Europe.",
    "bioMediumLabel": "150 Words",
    "bioMedium": "Michael Kofman is the CEO of Digital Invest Inc. and serves on its Board of Directors. A technological visionary, he is renowned for his dynamic approach to understanding the ever-evolving needs of today's complex market. As an entrepreneur, board member, and advisor for both public and private companies, he has successfully established several companies in the United States and Europe. His expertise spans executive acumen, strategic analysis of emerging technologies and markets, information security and privacy, research, science and development, administration, and investment.",
    "bioLongLabel": "500 Words",
    "bioLong": "Michael Kofman is the CEO of Digital Invest Inc. and serves on its Board of Directors. A technological visionary, he is renowned for his dynamic approach to understanding the ever-evolving needs of today's complex market. His expertise spans executive acumen, strategic analysis of emerging technologies and markets, information security and privacy, research, science and development, administration, and investment. As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. He founded 9 Net Avenue Inc., acquired at a peak market value of $19.5 billion, and leads Digital Invest Inc. in data storage and advanced technology innovation. He has directed technology strategy for government and defense programs, founded XIBI Group Inc. and DataPeer Inc. in data storage, and played a significant role in Biotechnology Group Inc. Collaborated with Harvard Medical School and Stanford Biomath on genetic reporting. Author of technical papers on satellite and optical systems; patent in digital satellite HDTV acquired by Sony. Education: Doctor of Technical Sciences (2009), Ph.D. in Information Technology (2004), Ukrainian State Marine Technical University.",
    "photosEyebrow": "Photography",
    "photosTitle": "Approved Images",
    "photosLead": "High-resolution portraits available upon request at mkofman@mkofman.com.",
    "contactEyebrow": "Press Contact",
    "contactTitle": "Media Inquiries",
    "contactLead": "For interviews, speaking invitations, and press requests.",
    "downloadEyebrow": "Download",
    "downloadTitle": "One-Page Media Kit",
    "downloadLead": "PDF with official bios, portrait, and press contact — ready to share with organizers and journalists.",
    "downloadCta": "Download PDF"
  },
  "articles": {
    "backLink": "← Back to Insights",
    "article1date": "Executive Perspective",
    "article1title": "From Engineering to Global Data Infrastructure",
    "article1p1": "My career began at the Nikolaev Shipbuilding Plant in Ukraine, developing satellite transceiver systems for transmitting classified information to military ships. I was recognized as an electronics engineer of the highest level — the 6th category at a plant of 93,000 employees.",
    "article1p2": "From 1989 to 1994, I founded and led Astra Corp, one of Europe's largest manufacturers of digital transceiver satellite systems. From 1994 to 1996, as CEO of Elitan United Inc., I helped scale the company from nine to over 4,000 employees worldwide.",
    "article1p3": "In 1996, I founded 9 Net Avenue Inc., which quickly became one of the world's largest Data Storage companies. By 2000, it was acquired by Concentric Networks (NASDAQ: CNTX) and XO Communications (NASDAQ: XOXO), reaching a peak market value of $19.5 billion.",
    "article1p4": "From 2001 to 2019, I directed technology strategy for government, defense, and state-owned enterprise programs — leading large-scale initiatives in big data, secure infrastructure, and high-throughput data centers across the United States and Europe.",
    "article2date": "Digital Health",
    "article2title": "Precision Medicine and the Convergence of Science and Technology",
    "article2p1": "I am a firm believer in the potential of combining life sciences with the latest technological advancements. At Biotechnology Group Inc. (2008–2014), we focused on DNA testing and analysis, process automation for creating genetic profiles, and comprehensive human genetic research.",
    "article2p2": "Under my leadership, successful genetic testing projects were initiated in Ukraine, Russia, and the Baltic countries. In collaboration with Harvard Medical School and Stanford Biomath, I played a crucial role in developing easily understandable genetic reports for both doctors and patients.",
    "article2p3": "With Digital Invest Inc., founded in 2021, we are dedicated to the bio-mathematical sphere — transforming outdated approaches in medicine using science, DNA technologies, AI, and ML. The company was scaled from inception through a successful IPO and recognized among America's Top 10 Best Companies in Precision Medicine and Digital Health in 2023.",
    "article2p4": "Digital Invest comprises diverse innovative projects, including Human Digital Model, BioMath Life, and Aero-Ground Robotics Operations Network — each advancing the integration of data science and life sciences."
  },
  "privacy": {
    "eyebrow": "Legal",
    "title": "Privacy Policy",
    "lead": "This policy explains how mkofman.com handles information when you visit the site or send a message.",
    "updated": "Last updated: July 2026",
    "s1title": "Information We Collect",
    "s1text": "When you submit a contact or footer form, we receive the fields you provide (such as name, email, and message). If analytics are enabled, we may collect anonymized usage data (pages visited, referrer, device type).",
    "s2title": "How We Use Information",
    "s2text": "Form submissions are used to respond to your inquiry. Analytics help improve the website. We do not sell personal data.",
    "s3title": "Third-Party Services",
    "s3text": "Forms may be processed by Formspree. Analytics may use Plausible or Google Analytics if configured. These providers have their own privacy policies.",
    "s4title": "Your Rights",
    "s4text": "You may request access, correction, or deletion of your data by emailing mkofman@mkofman.com.",
    "s5title": "Contact",
    "s5text": "Questions about this policy: mkofman@mkofman.com"
  }
};
