window.__LANG_en = {
  "ui": {
    "toggleTheme": "Toggle light/dark theme",
    "selectLanguage": "Select language",
    "messageSent": "Message Sent",
    "sendMessage": "Send Message",
    "toggleNav": "Toggle navigation",
    "sending": "Sending…",
    "formError": "Could not send. Please email directly.",
    "present": "Present"
  },
  "nav": {
    "home": "Home",
    "about": "About",
    "ventures": "Ventures",
    "career": "Career",
    "recognition": "Recognition",
    "contact": "Contact",
    "consulting": "Consulting",
    "insights": "Insights",
    "speaking": "Speaking",
    "caseStudies": "Case Studies",
    "mediaKit": "Media Kit",
    "briefIpo": "Brief: IPO",
    "briefGenetic": "Brief: Genetic Data",
    "briefAi": "Brief: AI Strategy",
    "articleInfra": "Data Infrastructure",
    "articleHealth": "Precision Medicine",
    "groupMain": "Main",
    "groupServices": "Services",
    "groupWork": "Work",
    "board": "Board Advisory",
    "thesis": "Leadership Thesis",
    "press": "Press",
    "ip": "Intellectual Property"
  },
  "footer": {
    "navigation": "Navigation",
    "ventures": "Ventures",
    "connect": "Connect",
    "desc": "CEO, technologist, and founder. Digital health, data infrastructure, robotics.",
    "copyright": "© {year} Michael Kofman. All Rights Reserved.",
    "writeTitle": "Write to Me",
    "writeEmail": "Your email",
    "writeMessage": "Your message",
    "writeSend": "Send",
    "writeSuccess": "Thank you — your message has been sent.",
    "more": "More",
    "privacy": "Privacy Policy"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — CEO & Strategic Technologist",
      "description": "Official site of Michael Kofman — CEO, founder, and board advisor in technology and digital health."
    },
    "about": {
      "title": "About — Michael Kofman",
      "description": "Biography of Michael Kofman — CEO of Digital Invest Inc., founder of AGRON Inc."
    },
    "ventures": {
      "title": "Ventures — Michael Kofman",
      "description": "Companies founded and led by Michael Kofman."
    },
    "career": {
      "title": "Career — Michael Kofman",
      "description": "Professional career timeline of Michael Kofman."
    },
    "recognition": {
      "title": "Recognition — Michael Kofman",
      "description": "Awards, honors, and recognition received by Michael Kofman."
    },
    "contact": {
      "title": "Contact — Michael Kofman",
      "description": "Contact Michael Kofman for advisory roles, speaking engagements, and business inquiries."
    },
    "consulting": {
      "title": "Consulting — Michael Kofman",
      "description": "Advisory roles, board positions, speaking engagements, and strategic partnerships with Michael Kofman."
    },
    "insights": {
      "title": "Insights — Michael Kofman",
      "description": "Publications, press features, patents, and industry recognition from Michael Kofman."
    },
    "speaking": {
      "title": "Speaking — Michael Kofman",
      "description": "Invite Michael Kofman to speak on executive leadership, technology strategy, digital health, and board governance."
    },
    "caseStudies": {
      "title": "Case Studies — Michael Kofman",
      "description": "Case studies from Michael Kofman's career — AGRON Inc., 9 Net Avenue Inc., and Digital Invest Inc."
    },
    "mediaKit": {
      "title": "Media Kit — Michael Kofman",
      "description": "Official biographies, photos, and contact information for press and event organizers."
    },
    "article1": {
      "title": "From Engineering to Global Infrastructure — Michael Kofman",
      "description": "Michael Kofman on a career path from satellite engineering to founding global data infrastructure companies."
    },
    "article2": {
      "title": "Precision Medicine and Technology — Michael Kofman",
      "description": "Michael Kofman on combining life sciences with AI, ML, and DNA technologies in modern medicine."
    },
    "privacy": {
      "title": "Privacy Policy — Michael Kofman",
      "description": "Privacy policy for mkofman.com — how we handle contact form data and site analytics."
    },
    "board": {
      "title": "Board Advisory — Michael Kofman",
      "description": "Board service and strategic advisory from Michael Kofman for technology, healthcare, infrastructure, and growth-stage organizations."
    },
    "thesis": {
      "title": "Leadership Thesis — Michael Kofman",
      "description": "Michael Kofman's principles for building durable companies, governing technology, and leading through consequential change."
    },
    "press": {
      "title": "Press Archive — Michael Kofman",
      "description": "Selected press coverage, awards, and media references spanning Michael Kofman's career in technology and entrepreneurship."
    },
    "ip": {
      "title": "Intellectual Property — Michael Kofman",
      "description": "Patents, publications, and applied research by Michael Kofman across computing, communications, data, and digital health."
    },
    "briefIpo": {
      "title": "What an IPO Changes — Michael Kofman",
      "description": "An executive brief on the operating discipline, governance, and accountability required before and after an initial public offering."
    },
    "briefGenetic": {
      "title": "From Genetic Data to Clinical Decisions — Michael Kofman",
      "description": "An executive brief on translating genomic information into responsible, useful, and scalable clinical intelligence."
    },
    "briefAi": {
      "title": "AI Strategy Beyond the Pilot — Michael Kofman",
      "description": "An executive brief on moving artificial intelligence from experimentation to governed, measurable enterprise capability."
    },
    "deck": {
      "title": "Executive Overview — Michael Kofman",
      "description": "Private executive overview for qualified introductions."
    }
  },
  "home": {
    "heroEyebrow": "Official Website of Michael Kofman",
    "heroTitle1": "Built to Endure.",
    "heroTitle2": "Led with Judgment.",
    "heroCta": "Discover My Story",
    "heroAlt": "Michael Kofman — CEO and Strategic Technologist",
    "quote1text": "Featured among America's leading companies in precision medicine and digital health.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "Entrepreneur of the Year — recognized for leadership and breakthrough achievements in platform innovation and infrastructure.",
    "quote2author": "Entrepreneur Magazine, 1999 — 2001",
    "quote3text": "Digital Invest Inc. named among America's Top 10 Best Companies in Precision Medicine and Digital Health.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "Engineering precision paired with business strategy — from satellite systems to $19.5B infrastructure to precision medicine.",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "Meet Michael Kofman",
    "aboutTitle": "Companies Built to Last",
    "aboutLead1": "CEO of Digital Invest Inc. and founder of AGRON Inc. He has founded and led companies across the U.S. and Europe.",
    "aboutLead2": "From 9 Net Avenue ($19.5B peak valuation) to Digital Invest in precision medicine and AGRON in robotics — four decades in infrastructure, health, and defense.",
    "aboutLink": "Read Full Biography",
    "expertiseEyebrow": "Focus Areas",
    "expertiseTitle": "Executive Leadership Across Industries",
    "expertiseLead": "Four decades building, advising, and investing across infrastructure, health, and robotics.",
    "exp1title": "CEO & Founder",
    "exp1desc": "Founded and scaled multiple companies from inception through IPO, achieving consistent financial growth and global presence across technology and healthcare sectors.",
    "exp1link": "View Ventures →",
    "exp2title": "Technology Architect",
    "exp2desc": "Designed secure communications, predictive analytics engines, and national-level data integration platforms for government, military, and telecom sectors.",
    "exp2link": "View Career →",
    "exp3title": "Digital Health",
    "exp3desc": "Leading the transformation of medicine through AI, ML, and DNA technologies. Collaborated with Harvard Medical School and Stanford Biomath on genetic reporting.",
    "exp3link": "Digital Invest →",
    "exp4title": "Board Advisor",
    "exp4desc": "Serves on boards and advises public and private companies on strategic direction, corporate governance, and technology-driven growth initiatives.",
    "exp4link": "Consulting →",
    "stat1": "Years of Leadership",
    "stat2": "Companies Founded",
    "stat3": "Peak Market Value",
    "stat4": "Employees Scaled",
    "recEyebrow": "Recognition",
    "recTitle": "Awards & Honors",
    "recLead": "Industry awards and peer recognition across entrepreneurship, medicine, and engineering.",
    "award1title": "Entrepreneur of the Year",
    "award1desc": "Entrepreneur Magazine, 1999 — 2001",
    "award2title": "Top 10 Precision Medicine",
    "award2desc": "Digital Invest Inc. — U.S., 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "View All Recognition",
    "heroSub": "CEO, board advisor, and strategic technologist for public and private companies in technology, data storage, and digital health.",
    "primaryCta": "Request Advisory",
    "secondaryCta": "View Case Studies",
    "featuredEyebrow": "As Featured In",
    "caseStudiesEyebrow": "Proven Outcomes",
    "caseStudiesTitle": "Case Studies",
    "caseStudiesLead": "Founding, scaling, and leading companies from inception through acquisition and IPO.",
    "caseStudiesLink": "View All Case Studies →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "Built one of the world's largest Data Storage companies — acquired at a peak market value of $19.5 billion.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "Founded and scaled from inception through IPO — Top 10 U.S. Precision Medicine Company, 2023.",
    "cs3title": "AGRON Inc.",
    "cs3desc": "Founded in 2026 — the AGRON Ecosystem for UAV capability development, geospatial systems, and maritime intelligence.",
    "boardCtaEyebrow": "Board & Advisory",
    "boardCtaTitle": "Experience for the Decisions That Define an Enterprise",
    "boardCtaLead": "Independent perspective for boards and leaders navigating technology, governance, transformation, and growth.",
    "boardCtaBtn": "Explore Board Advisory",
    "testimonialsEyebrow": "Trusted Perspective",
    "testimonialsTitle": "What Colleagues Value",
    "videoEyebrow": "Executive Perspective",
    "videoTitle": "Leadership at the Intersection of Technology and Enterprise",
    "videoLead": "A concise introduction to the principles, experience, and long-term perspective behind Michael Kofman's work.",
    "videoCta": "Read Leadership Thesis →"
  },
  "about": {
    "eyebrow": "About Michael Kofman",
    "title": "Built Over Three Decades",
    "lead": "Entrepreneur and executive across engineering, infrastructure, digital health, and robotics.",
    "glance": "At a Glance",
    "role": "Current Role",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "Location",
    "locationVal": "Charlotte, North Carolina",
    "education": "Education",
    "educationVal": "Doctor of Technical Sciences (2009)\nPh.D. in Information Technology (2004)\nMaster's in Electronic Engineering",
    "university": "University",
    "universityVal": "Ukrainian State Marine Technical University",
    "languages": "Languages",
    "languagesVal": "English, Russian, Ukrainian",
    "contactLabel": "Contact",
    "principlesEyebrow": "Operating Principles",
    "principlesTitle": "How I Lead",
    "p1title": "Understand the System",
    "p1text": "Before changing an organization, understand its incentives, architecture, constraints, and sources of trust.",
    "p2title": "Make Accountability Explicit",
    "p2text": "Clear ownership and measurable outcomes turn strategy from presentation material into operating reality.",
    "p3title": "Leave Stronger Institutions",
    "p3text": "Leadership should compound capability by developing people, improving decisions, and building systems that endure.",
    "archiveEyebrow": "From the Archive",
    "archiveTitle": "Moments Across the Journey",
    "archiveLead": "Selected photographs from company building, infrastructure, and leadership — from the 9 Net Avenue years to today.",
    "photo9netTitle": "9 Net Avenue",
    "photo9netCaption": "Founder & CEO — one of the world’s largest hosting companies, later acquired at a peak market value of $19.5 billion.",
    "photoServerTitle": "Data Infrastructure",
    "photoServerCaption": "Hands-on years in storage, networking, and high-density server environments at DataPeer and related ventures.",
    "photoTodayTitle": "Today",
    "photoTodayCaption": "Board advisory, strategic technology leadership, and building the next generation of digital health and infrastructure companies.",
    "bioP1": "Michael Kofman is CEO of Digital Invest Inc. and founder of AGRON Inc. He serves on the Digital Invest board. His work spans company building, technology strategy, security, research, and investment in the U.S. and Europe.",
    "bioP2": "As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. In 2026 he founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network. He also created Digital Invest, dedicated to the bio-mathematical sphere and transforming medicine through science, DNA technologies, AI, and ML.",
    "secBioTitle": "Precision Medicine & Biotechnology",
    "secBioP1": "Prior to Digital Invest, he played a significant role in the success of Biotechnology Group Inc. (2008–2014), a company committed to DNA testing and analysis, process automation for creating genetic profiles, and comprehensive human genetic research. Mr. Kofman is a firm believer in the potential of combining life sciences with the latest technological advancements.",
    "secBioP2": "Under his leadership, successful genetic testing projects have been initiated in Ukraine, Russia, and the Baltic countries. This unique experience is continually enriched with modern technologies and new equipment. In collaboration with Harvard Medical School and Stanford Biomath, Mr. Kofman played a crucial role in developing easily understandable genetic reports for both doctors and patients. This innovative approach has been widely adopted by leading laboratories in the United States and abroad.",
    "secTechTitle": "Technology & Infrastructure",
    "secTechP1": "From 2001 to 2019, Mr. Kofman directed technology strategy for government, defense, and state-owned enterprise programs — including complex technical initiatives for government-owned companies. Following September 11, 2001, he led large-scale government projects centered on big data, secure infrastructure, and high-throughput data centers across the United States and Europe.",
    "secTechP2": "In 2006, Mr. Kofman founded XIBI Group Inc. — a technology company where he served on the board of directors. The American company specializes in data storage and big data management services for large commercial and government organizations.",
    "secTechP3": "From 2000 to 2004, Mr. Kofman led DataPeer Inc. — a data management and storage company offering a wide range of services related to information storage for small and medium-sized businesses. At DataPeer he developed unique technological solutions that facilitated faster information tracking and easier data accessibility for individual end-users and government institutions worldwide.",
    "secTechP4": "In 1996, Mr. Kofman founded 9 Net Avenue Inc. It quickly became one of the world's largest hosting companies. By 2000, 9 Net Avenue was acquired by Concentric Networks (NASDAQ: CNTX), and then by XO Communications (NASDAQ: XOXO), reaching a peak market value of $19.5 billion.",
    "secPost9NetP1": "Following the acquisition of 9 Net Avenue, Mr. Kofman gained extensive experience working with public companies, serving on boards of directors, and participating in strategic decision-making at the highest executive level.",
    "secEarlyTitle": "Early Career & Engineering",
    "secEarlyP1": "From 1994 to 1996, Mr. Kofman served as CEO and Director of Information Technology at Elitan United Inc. — an IT company from Massachusetts, which provided comprehensive strategies and technological services for leading global organizations. He played a pivotal role in developing and managing a scalable infrastructure, leading the company's growth from just nine to over 4,000 employees worldwide.",
    "secEarlyP2": "From 1989 to 1994, he was the founder and CEO of Astra Corp, one of the largest manufacturers of digital transceiver satellite systems in Europe, earning international recognition in the field of satellite devices. His responsibilities encompassed research, operating system development, network software applications, and overall technical strategy.",
    "secEarlyP3": "From 1984 to 1989, Mr. Kofman worked at the shipbuilding plant in Nikolaev, Ukraine, where he actively participated in the development and creation of satellite transceiver systems for transmitting classified information to military ships and back. He was recognized as an electronics engineer of the highest level, receiving the 6th category — the highest recognition at the plant, where 93 thousand people worked.",
    "secResearchTitle": "Research & Patents",
    "secResearchP1": "Michael Kofman is the author of technical papers focused on satellite and optical systems for data transmission. He also received a patent in the field of digital satellite high-definition television (HDTV) systems, which was subsequently acquired by Sony.",
    "secAgronTitle": "Robotics, UAV & Maritime Intelligence",
    "secAgronP1": "In 2026, Mr. Kofman founded AGRON Inc. to build the AGRON Ecosystem — a corporate operating architecture for aerial and ground robotics, governed mission execution, and network infrastructure connecting teams, assets, and operational data. The ecosystem delivers consulting, assessment, capability development, and training for UAV and Counter-UAS organizations, alongside maritime intelligence and security services at agron1.com."
  },
  "ventures": {
    "eyebrow": "Portfolio of Ventures",
    "title": "Companies Founded & Led",
    "lead": "From precision medicine and robotics to global data infrastructure — founded, scaled, and led across the U.S. and Europe.",
    "ecosystemEyebrow": "Venture Ecosystem",
    "ecosystemTitle": "Companies Across Technology Frontiers",
    "ecosystemLead": "A portfolio shaped by recurring themes: trusted data, intelligent infrastructure, human health, and systems built for scale.",
    "statusActive": "Active",
    "statusExited": "Exited",
    "statusLegacy": "Legacy",
    "v1lesson": "Lesson: infrastructure wins when reliability, economics, and customer trust improve together.",
    "v2lesson": "Lesson: precision medicine requires equal discipline in science, software, privacy, and clinical usefulness.",
    "v3lesson": "Lesson: autonomy creates value only when sensing, communications, and human oversight form one resilient system.",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — an Aerial-Ground Robotics Operations Network spanning UAV and Counter-UAS consulting, technology assessment, capability development, training infrastructure, product validation, geospatial systems (ISDRI), and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "v0role": "Founder",
    "v0year": "2026 — Present",
    "v1highlight": "Top 10 U.S. Precision Medicine Company — 2023",
    "v1p1": "Founded and scaled Digital Invest from inception through a successful IPO. The company is dedicated to the bio-mathematical sphere, transforming medicine through AI, ML, and DNA technologies.",
    "v1role": "Founder & CEO · Board Member",
    "v1year": "2021 — Present",
    "v2highlight": "Harvard Medical School & Stanford Biomath Partner",
    "v2p1": "DNA testing and analysis, automation of genetic profiling, and comprehensive human genetic research. Initiated genetic testing projects in Ukraine, Russia, and the Baltic countries.",
    "v2p2": "Collaborated with Harvard Medical School and Stanford Biomath on genetic reports adopted by leading laboratories worldwide.",
    "v2role": "CEO & CTO",
    "v2year": "2008 — 2014",
    "v3highlight": "Enterprise & Government Data Solutions",
    "v3p1": "Data storage and big data management services for large commercial and government organizations. Established the company as a trusted provider of enterprise data solutions.",
    "v3role": "Founder & CEO · Board of Directors",
    "v3year": "2006 — 2011",
    "v4highlight": "Global Data Management Platform",
    "v4p1": "Data management and storage for small and medium-sized businesses. Developed solutions for faster information tracking and easier data accessibility for end-users and government institutions worldwide.",
    "v4role": "Founder & CEO",
    "v4year": "2000 — 2004",
    "v5highlight": "Acquired · Peak Value $19.5 Billion",
    "v5p1": "Built one of the world's largest hosting companies. By 2000, acquired by Concentric Networks (NASDAQ: CNTX), then XO Communications (NASDAQ: XOXO), reaching a peak market value of $19.5 billion.",
    "v5role": "Founder & CEO",
    "v5year": "1996 — 2000",
    "v6highlight": "Global IT Strategy & Infrastructure",
    "v6p1": "IT company from Massachusetts providing comprehensive strategies and technological services for leading global organizations. Led scalable infrastructure development and global IT operations.",
    "v6role": "CEO & Director of Information Technology",
    "v6year": "1994 — 1996",
    "v7highlight": "European Satellite Systems Leader",
    "v7p1": "One of Europe's largest manufacturers of digital transceiver satellite systems. Led research, operating system development, network software applications, and overall technical strategy.",
    "v7role": "Founder & CEO",
    "v7year": "1989 — 1994",
    "v8highlight": "Military Satellite Systems Engineering",
    "v8p1": "Development and creation of satellite transceiver systems for transmitting classified information to military ships. Recognized as an electronics engineer of the highest level at a plant of 93,000 employees.",
    "v8role": "Electronics Engineer · Highest Category (6th)",
    "v8year": "1984 — 1989"
  },
  "career": {
    "eyebrow": "Professional Journey",
    "title": "Three Decades of Executive Leadership",
    "lead": "From military satellite engineering to founding global technology companies and leading precision medicine innovation.",
    "timelineEyebrow": "Career Timeline",
    "timelineTitle": "Key Milestones",
    "strengthsEyebrow": "Core Strengths",
    "strengthsTitle": "Areas of Expertise",
    "filterAll": "All",
    "filterHealthcare": "Healthcare",
    "filterInfrastructure": "Infrastructure",
    "filterDefense": "Defense",
    "filterTelecom": "Telecommunications",
    "t0desc": "Founded AGRON Inc. to build the AGRON Ecosystem — consulting, assessment, capability development, training infrastructure, and product support for UAV and Counter-UAS programmes, plus AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure. Connects aerial and ground robotics, governed mission execution, and network infrastructure linking teams, assets, and operational data.",
    "t0role": "Founder",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — Present",
    "s1desc": "Dual-sided CEO/CTO management across public and private companies, from startup to IPO and beyond.",
    "s1title": "Executive Leadership",
    "s2desc": "Full public offering execution — legal structuring, SEC coordination, investor roadshows, and compliance.",
    "s2title": "IPO & Financial Scaling",
    "s3desc": "Scalable systems design for enterprise automation, predictive monitoring, and centralized data control.",
    "s3title": "Platform Architecture",
    "s4desc": "Data center development and operations for government, military, and high-security commercial platforms.",
    "s4title": "Secure Infrastructure",
    "t10desc": "Developed and created satellite transceiver systems for transmitting classified information to military ships. Recognized as an electronics engineer of the highest level at a plant of 93,000 employees — the beginning of a distinguished career in technology and innovation.",
    "t10role": "Electronics Engineer — 6th Category (Highest)",
    "t10title": "Nikolaev Shipbuilding Plant",
    "t10year": "1984 — 1989",
    "t1desc": "Founded and scaled the company from inception through a successful IPO. Led the full public offering process — legal structuring, financial compliance, investor roadshows, and SEC coordination. Directed design, construction, and operations of multiple data centers in the U.S. and Europe. Built enterprise-level software systems for automation, predictive monitoring, and centralized data control. Achieved consistent financial growth, positioning the company among Top 10 Precision Medicine Companies in the U.S. (2023).",
    "t1role": "Founder & CEO",
    "t1title": "Digital Invest Inc.",
    "t1year": "2021 — Present",
    "t2desc": "Directed technology strategy and delivery for classified and high-sensitivity programs involving U.S. government agencies, allied defense systems, and state-owned enterprises. Headed complex technical projects for government-owned companies across multiple sectors. Following September 11, 2001, led large-scale government initiatives centered on big data, secure communications, predictive analytics, and national-level data integration — including the design, construction, and operation of high-throughput data centers across the United States and Europe. Interfaced with military program officers, technology vendors, and regulatory entities.",
    "t2role": "Chief Technology Advisor / Program Architect",
    "t2title": "GovTech, Defense & State Programs",
    "t2year": "2001 — 2019",
    "t3desc": "Led DNA testing and analysis, automation of genetic profiling, and comprehensive human genetic research. Initiated genetic testing projects in Ukraine, Russia, and the Baltic countries. Collaborated with Harvard Medical School and Stanford Biomath to develop understandable genetic reports adopted by leading laboratories worldwide.",
    "t3role": "CEO & CTO",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4desc": "Directed national infrastructure rollouts across Canada, Italy, Switzerland, Ukraine, and the Baltic Republics. Oversaw 1,000+ engineering and deployment staff across telecom operations including switching systems, broadband expansion, and cross-border connectivity. Implemented core systems for network redundancy, uptime optimization, and intelligent routing.",
    "t4role": "VP of Technology / Regional CTO — Eastern Europe & CIS",
    "t4title": "Telecommunications Projects",
    "t4year": "2000 — 2012",
    "t5desc": "Founded a technology company specializing in data storage and big data management services for large commercial and government organizations. Established the company as a trusted provider of enterprise data solutions.",
    "t5role": "Founder & CEO · Board of Directors",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6desc": "Established a data management and storage company for SMBs. Developed unique technological solutions for faster information tracking and easier data accessibility for end-users and government institutions worldwide.",
    "t6role": "Founder & CEO",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "Built one of the world's largest hosting companies. By 2000, acquired by Concentric Networks (NASDAQ: CNTX), then XO Communications (NASDAQ: XOXO), reaching a peak market value of $19.5 billion.",
    "t7role": "Founder & CEO",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8desc": "Led comprehensive IT strategies and technological services for leading global organizations from Massachusetts during a period of rapid expansion, building scalable infrastructure and global IT operations.",
    "t8role": "CEO & Director of Information Technology",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9desc": "Founded one of Europe's largest manufacturers of digital transceiver satellite systems. Led research, operating system development, network software applications, and overall technical strategy, earning international recognition.",
    "t9role": "Founder & CEO",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994"
  },
  "recognition": {
    "eyebrow": "Awards & Honors",
    "title": "Awards & Recognition",
    "lead": "Honors spanning entrepreneurship, precision medicine, engineering, and executive leadership.",
    "industryEyebrow": "Industry Awards",
    "industryTitle": "Major Honors",
    "ipEyebrow": "Intellectual Property",
    "ipTitle": "Patents & Publications",
    "eduEyebrow": "Education",
    "eduTitle": "Academic Credentials",
    "pressEyebrow": "Press & Media",
    "pressTitle": "Featured In",
    "moreLink": "View patents, publications, and press features on Insights →",
    "a1title": "Entrepreneur of the Year",
    "a1desc": "Entrepreneur Magazine, 1999 — 2001 — leadership and breakthrough achievements in platform innovation and infrastructure.",
    "a2title": "Top 10 U.S. Precision Medicine Company",
    "a2desc": "Digital Invest Inc. recognized among America's 10 Best Companies in Precision Medicine and Digital Health — 2023.",
    "a3title": "Who's Who in America",
    "a3desc": "Listed, 1999 — 2018 — for exceptional achievements in business creation and development.",
    "a4title": "Who's Who in the World",
    "a4desc": "Listed, 2000 — 2004 — among global leaders in science, engineering, and business innovation.",
    "a5title": "Who's Who in Science & Engineering",
    "a5desc": "Listed, 2000 — 2014 — for contributions to technology, satellite systems, and digital infrastructure.",
    "a6title": "Electronics Engineer — 6th Category",
    "a6desc": "Highest recognition at Nikolaev Shipbuilding Plant (93,000 employees) for satellite transceiver systems engineering.",
    "ip1year": "Patent",
    "ip1title": "Digital Satellite HDTV Systems",
    "ip1role": "Subsequently Acquired by Sony",
    "ip1desc": "Received a patent in the field of digital satellite high-definition television (HDTV) systems. The patent was subsequently acquired by Sony Corporation, validating the innovation's commercial significance.",
    "ip2year": "Publications",
    "ip2title": "Technical Papers",
    "ip2role": "Satellite & Optical Systems",
    "ip2desc": "Author of technical papers focused on satellite and optical systems for data transmission. Research contributions span signal processing, simulation modeling, and automation platforms applied in telecommunications, national infrastructure, and digital health.",
    "ip3year": "Research",
    "ip3title": "International Collaborations",
    "ip3role": "U.S. & Europe",
    "ip3desc": "Engaged in international research collaborations and knowledge transfer initiatives. Developed embedded engineering systems for data acquisition, predictive diagnostics, and cloud-based orchestration across multiple industries.",
    "edu1title": "Doctor of Technical Sciences",
    "edu1desc": "2009 — Ukrainian State Marine Technical University",
    "edu2title": "Ph.D. in Information Technology",
    "edu2desc": "2004 — Ukrainian State Marine Technical University",
    "edu3title": "Master's Degrees",
    "edu3desc": "Electronics, Digital Satellite Systems, and Economics",
    "press1title": "Healthcare Tech Outlook",
    "press1role": "Digital Invest Inc. Feature",
    "press1desc": "Digital Invest Inc. featured as one of America's leading companies in precision medicine and digital health, recognized for innovative approaches to transforming medicine through AI, ML, and DNA technologies.",
    "press1link": "Read Feature →",
    "press2title": "Top Precision Medicine Solutions",
    "press2role": "Industry Recognition",
    "press2desc": "Named among the top precision medicine solutions companies, highlighting Digital Invest's role in advancing bio-mathematical approaches to modern healthcare.",
    "press2link": "View Listing →"
  },
  "contact": {
    "eyebrow": "Get in Touch",
    "title": "Let's Connect",
    "lead": "For advisory roles, board positions, speaking engagements, and strategic partnerships.",
    "infoTitle": "Reach Out Directly",
    "email": "Email",
    "phone": "Phone",
    "location": "Location",
    "locationVal": "Charlotte, North Carolina\nUnited States",
    "linkedin": "LinkedIn",
    "company": "Current Company",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member\nAGRON Inc.\nFounder",
    "formTitle": "Send a Message",
    "formLead": "Fill out the form below and I'll get back to you promptly.",
    "firstName": "First Name",
    "lastName": "Last Name",
    "emailLabel": "Email Address",
    "subject": "Subject",
    "message": "Message",
    "inquiryType": "Inquiry Type",
    "inquiryAdvisory": "Advisory / Board Role",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "calendlyEyebrow": "Schedule a Conversation",
    "calendlyTitle": "Choose a Convenient Time",
    "calendlyLead": "For qualified board, advisory, speaking, and strategic partnership inquiries.",
    "calendlyPlaceholder": "Scheduling calendar will appear here.",
    "calendlyCta": "Open Scheduling Calendar",
    "infoEyebrow": "Contact Information"
  },
  "consulting": {
    "eyebrow": "Advisory Services",
    "title": "Consulting",
    "heroEyebrow": "Strategic Business Guidance",
    "heroTitle": "Strategic Advisory",
    "heroLead": "Thirty-five years founding and advising companies in the U.S. and Europe — data infrastructure, govtech, precision medicine, and robotics.",
    "cta": "Contact Michael Kofman",
    "introLead": "CEO of Digital Invest Inc. and board director. Focus: emerging technology, security, research, and capital allocation.",
    "specialtiesEyebrow": "Areas of Focus",
    "specialtiesTitle": "What Michael Kofman Specializes In"
  },
  "insights": {
    "eyebrow": "Thought Leadership",
    "title": "Insights",
    "heroTitle": "Executive Perspectives",
    "selectedEyebrow": "Selected Highlights",
    "selectedTitle": "Featured Recognition",
    "allPressTitle": "All Press Features",
    "quotesEyebrow": "In the Media",
    "quotesTitle": "Industry Recognition & Quotes",
    "articlesEyebrow": "Perspectives",
    "articlesTitle": "Executive Perspectives",
    "briefsEyebrow": "Executive Briefs",
    "briefsTitle": "Ideas for Leaders",
    "briefsLead": "Short, practical perspectives on governance, technology, healthcare, and company building.",
    "brief1title": "What an IPO Changes",
    "brief1desc": "The operating and governance disciplines that public-market readiness demands.",
    "brief1tag": "Capital Markets",
    "brief2title": "From Genetic Data to Clinical Decisions",
    "brief2desc": "How to build useful health intelligence without outrunning evidence or trust.",
    "brief2tag": "Precision Medicine",
    "brief3title": "AI Strategy Beyond the Pilot",
    "brief3desc": "A framework for turning experiments into governed enterprise capability.",
    "brief3tag": "Artificial Intelligence",
    "readingEyebrow": "Reading List",
    "readingTitle": "Books That Shape Strategic Thinking",
    "r1title": "The Innovator's Dilemma",
    "r1author": "Clayton M. Christensen",
    "r2title": "Thinking, Fast and Slow",
    "r2author": "Daniel Kahneman",
    "r3title": "The Beginning of Infinity",
    "r3author": "David Deutsch",
    "r4title": "Good Strategy/Bad Strategy",
    "r4author": "Richard Rumelt",
    "r5title": "The Structure of Scientific Revolutions",
    "r5author": "Thomas S. Kuhn",
    "newsletterEyebrow": "Occasional Notes",
    "newsletterTitle": "Executive Perspective, Without the Noise",
    "newsletterLead": "Periodic essays and brief observations on technology, governance, and durable company building.",
    "newsletterCta": "Subscribe for Updates"
  },
  "cta": {
    "eyebrow": "Work Together",
    "title": "Request Advisory or a Speaking Engagement",
    "lead": "For advisory roles, board positions, speaking engagements, and strategic partnerships.",
    "button": "Get in Touch"
  },
  "speaking": {
    "eyebrow": "Speaking Engagements",
    "title": "Invite Michael Kofman to Speak",
    "lead": "Available for speaking engagements on executive leadership, technology strategy, digital health, data infrastructure, and corporate governance.",
    "topicsEyebrow": "Speaking Topics",
    "topicsTitle": "Areas of Expertise",
    "topicsLead": "Topics draw on decades of experience founding and leading companies in the United States and Europe.",
    "processEyebrow": "How to Invite",
    "processTitle": "Booking Process",
    "process1title": "Send an Inquiry",
    "process1desc": "Use the contact form or email mkofman@mkofman.com with event details, audience, and preferred topics.",
    "process2title": "Confirm Scope",
    "process2desc": "Discuss format — keynote, panel, board session, or executive roundtable — and logistics.",
    "process3title": "Deliver Value",
    "process3desc": "Presentations are grounded in real outcomes from ventures across data storage, govtech, and precision medicine.",
    "cta": "Request a Speaking Engagement",
    "catalogEyebrow": "Speaking Topics",
    "catalogTitle": "Executive Conversations for Consequential Change",
    "catalogLead": "Keynotes, board sessions, and leadership briefings tailored to the audience, sector, and decision context.",
    "t1title": "Governing AI Before It Governs the Enterprise",
    "t1audience": "Boards, audit and risk committees",
    "t1format": "Board briefing or keynote",
    "t2title": "From Technology Trend to Enterprise Strategy",
    "t2audience": "CEOs, executive teams, investors",
    "t2format": "Keynote or executive workshop",
    "t3title": "Building Companies Through Market Cycles",
    "t3audience": "Founders, growth leaders, private equity",
    "t3format": "Fireside chat or keynote",
    "t4title": "Precision Medicine: Promise, Proof, and Responsibility",
    "t4audience": "Healthcare leaders, clinicians, innovators",
    "t4format": "Industry keynote or panel",
    "t5title": "The Board's Role in Cyber and Technology Risk",
    "t5audience": "Directors, general counsel, risk leaders",
    "t5format": "Board education session",
    "t6title": "Engineering Trust into Digital Infrastructure",
    "t6audience": "Technology and infrastructure organizations",
    "t6format": "Technical-executive keynote",
    "t7title": "Leading Across Borders and Disciplines",
    "t7audience": "Global leadership teams and universities",
    "t7format": "Keynote or moderated conversation",
    "t8title": "From Founder to Institution Builder",
    "t8audience": "Entrepreneurs and next-generation executives",
    "t8format": "Workshop or fireside chat"
  },
  "caseStudies": {
    "eyebrow": "Case Studies",
    "title": "Building Companies That Scale",
    "lead": "Selected outcomes from founding and leading companies across robotics, data infrastructure, and digital health.",
    "cs1eyebrow": "Data Infrastructure · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "Challenge",
    "cs1challengeText": "Build and scale a Data Storage company in a rapidly consolidating technology market.",
    "cs1action": "Approach",
    "cs1actionText": "Founded 9 Net Avenue Inc. in 1996. The company quickly became one of the world's largest Data Storage companies.",
    "cs1result": "Outcome",
    "cs1resultText": "By 2000, acquired by Concentric Networks (NASDAQ: CNTX), then XO Communications (NASDAQ: XOXO), reaching a peak market value of $19.5 billion. Following the acquisition, gained extensive experience working with public companies, serving on boards of directors, and participating in strategic decision-making at the highest executive level.",
    "cs2eyebrow": "Digital Health · 2021 — Present",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "Challenge",
    "cs2challengeText": "Transform outdated approaches in medicine using science, DNA technologies, AI, and ML through a new bio-mathematical platform.",
    "cs2action": "Approach",
    "cs2actionText": "Founded and scaled Digital Invest Inc. from inception through a successful IPO. Led the full public offering process — legal structuring, financial compliance, investor roadshows, and SEC coordination. Directed design, construction, and operations of multiple data centers in the U.S. and Europe.",
    "cs2result": "Outcome",
    "cs2resultText": "Achieved consistent financial growth, positioning the company among Top 10 Precision Medicine Companies in the U.S. (2023), with projects including Human Digital Model and BioMath Life.",
    "cs3eyebrow": "Robotics & UAV · 2026 — Present",
    "cs3title": "AGRON Inc.",
    "cs3challenge": "Challenge",
    "cs3challengeText": "Organizations building UAV and Counter-UAS capability need independent assessment, structured training, and operational architecture — not isolated platforms or ad-hoc piloting.",
    "cs3action": "Approach",
    "cs3actionText": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — consulting, assessment and validation, capability development, training infrastructure, product development support, geospatial systems through ISDRI, and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "cs3result": "Outcome",
    "cs3resultText": "A connected professional services ecosystem spanning five service domains and multiple companies — Global Drone Academy, AGRON, ISDRI, and GUARD — with programmes delivered across 10+ countries and 10,000+ UAV operators, instructors, and specialists trained."
  },
  "mediaKit": {
    "eyebrow": "Press & Events",
    "title": "Media Kit",
    "lead": "Official biographies, imagery, and contact details for press, conferences, and board inquiries.",
    "bioEyebrow": "Biographies",
    "bioTitle": "Official Bios",
    "bioShortLabel": "50 Words",
    "bioShort": "Michael Kofman is CEO of Digital Invest Inc. and a board member, advisor, and founder of companies in technology and digital health across the U.S. and Europe.",
    "bioMediumLabel": "150 Words",
    "bioMedium": "Michael Kofman is CEO of Digital Invest Inc. and serves on its board. An entrepreneur, board member, and advisor, he has founded companies in the U.S. and Europe across data infrastructure, digital health, and robotics. His work spans technology strategy, security, research, and investment.",
    "bioLongLabel": "500 Words",
    "bioLong": "Michael Kofman is CEO of Digital Invest Inc. and serves on its board. He founded 9 Net Avenue Inc., acquired at a peak market value of $19.5 billion, and leads Digital Invest in precision medicine. He has directed technology strategy for government and defense programs, founded XIBI Group Inc. and DataPeer Inc., and led Biotechnology Group Inc. Collaborated with Harvard Medical School and Stanford Biomath on genetic reporting. Author of technical papers on satellite and optical systems; patent in digital satellite HDTV acquired by Sony. In 2026 he founded AGRON Inc. for aerial-ground robotics and maritime intelligence. Education: Doctor of Technical Sciences (2009), Ph.D. in Information Technology (2004), Ukrainian State Marine Technical University.",
    "photosEyebrow": "Photography",
    "photosTitle": "Approved Images",
    "photosLead": "High-resolution portraits available upon request at mkofman@mkofman.com.",
    "contactEyebrow": "Press Contact",
    "contactTitle": "Media Inquiries",
    "contactLead": "For interviews, speaking invitations, and press requests.",
    "downloadEyebrow": "Download",
    "downloadTitle": "One-Page Media Kit",
    "downloadLead": "PDF with official bios, portrait, and press contact — ready to share with organizers and journalists.",
    "downloadCta": "Download PDF",
    "brandEyebrow": "Brand Assets",
    "brandTitle": "Identity & Usage",
    "brandLead": "Approved visual assets for editorial, conference, and partner use. Please preserve proportions, spacing, and original colors.",
    "brandColors": "Official Color Palette",
    "brandLogo": "Primary Logo",
    "brandDownload": "Download Brand Assets"
  },
  "articles": {
    "backLink": "← Back to Insights",
    "article1date": "Executive Perspective",
    "article1title": "From Engineering to Global Data Infrastructure",
    "article1p1": "My career began at the Nikolaev Shipbuilding Plant in Ukraine, developing satellite transceiver systems for transmitting classified information to military ships. I was recognized as an electronics engineer of the highest level — the 6th category at a plant of 93,000 employees.",
    "article1p2": "From 1989 to 1994, I founded and led Astra Corp, one of Europe's largest manufacturers of digital transceiver satellite systems. From 1994 to 1996, as CEO of Elitan United Inc., I helped scale the company from nine to over 4,000 employees worldwide.",
    "article1p3": "In 1996, I founded 9 Net Avenue Inc., which quickly became one of the world's largest Data Storage companies. By 2000, it was acquired by Concentric Networks (NASDAQ: CNTX) and XO Communications (NASDAQ: XOXO), reaching a peak market value of $19.5 billion.",
    "article1p4": "From 2001 to 2019, I directed technology strategy for government, defense, and state-owned enterprise programs — leading large-scale initiatives in big data, secure infrastructure, and high-throughput data centers across the United States and Europe.",
    "article2date": "Digital Health",
    "article2title": "Precision Medicine and the Convergence of Science and Technology",
    "article2p1": "I am a firm believer in the potential of combining life sciences with the latest technological advancements. At Biotechnology Group Inc. (2008–2014), we focused on DNA testing and analysis, process automation for creating genetic profiles, and comprehensive human genetic research.",
    "article2p2": "Under my leadership, successful genetic testing projects were initiated in Ukraine, Russia, and the Baltic countries. In collaboration with Harvard Medical School and Stanford Biomath, I played a crucial role in developing easily understandable genetic reports for both doctors and patients.",
    "article2p3": "With Digital Invest Inc., founded in 2021, we are dedicated to the bio-mathematical sphere — transforming outdated approaches in medicine using science, DNA technologies, AI, and ML. The company was scaled from inception through a successful IPO and recognized among America's Top 10 Best Companies in Precision Medicine and Digital Health in 2023.",
    "article2p4": "Digital Invest advances bio-mathematical medicine through projects including Human Digital Model and BioMath Life. In 2026, Michael Kofman founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network — UAV capability development, geospatial systems, and maritime intelligence at agron1.com."
  },
  "privacy": {
    "eyebrow": "Legal",
    "title": "Privacy Policy",
    "lead": "This policy explains how mkofman.com handles information when you visit the site or send a message.",
    "updated": "Last updated: July 2026",
    "s1title": "Information We Collect",
    "s1text": "When you submit a contact or footer form, we receive the fields you provide (such as name, email, and message). If analytics are enabled, we may collect anonymized usage data (pages visited, referrer, device type).",
    "s2title": "How We Use Information",
    "s2text": "Form submissions are used to respond to your inquiry. Analytics help improve the website. We do not sell personal data.",
    "s3title": "Third-Party Services",
    "s3text": "Forms may be processed by Formspree. Analytics may use Plausible or Google Analytics if configured. These providers have their own privacy policies.",
    "s4title": "Your Rights",
    "s4text": "You may request access, correction, or deletion of your data by emailing mkofman@mkofman.com.",
    "s5title": "Contact",
    "s5text": "Questions about this policy: mkofman@mkofman.com"
  },
  "board": {
    "eyebrow": "Board & Strategic Advisory",
    "title": "Independent Judgment for Consequential Decisions",
    "lead": "I work with boards, founders, and executive teams navigating technology risk, market transitions, capital allocation, and responsible growth.",
    "rolesEyebrow": "Ways to Engage",
    "rolesTitle": "Board-Level Partnership",
    "role1title": "Independent Director",
    "role1desc": "Constructive oversight, informed challenge, and long-range perspective for public and private company boards.",
    "role2title": "Advisory Board Member",
    "role2desc": "Practical guidance on emerging technologies, product strategy, market positioning, and institutional readiness.",
    "role3title": "CEO & Founder Advisor",
    "role3desc": "Confidential counsel for leaders facing inflection points in scale, governance, succession, financing, or transformation.",
    "role4title": "Special Committee Advisor",
    "role4desc": "Focused support for transactions, technology diligence, cybersecurity exposure, and other high-stakes mandates.",
    "valueEyebrow": "Perspective",
    "valueTitle": "What I Bring to the Table",
    "value1title": "Operator's Discipline",
    "value1desc": "Experience building organizations from inception through global scale, acquisition, and public-market accountability.",
    "value2title": "Technical Fluency",
    "value2desc": "The ability to translate complex systems, scientific claims, and technology risk into clear board decisions.",
    "value3title": "Cross-Market Judgment",
    "value3desc": "A perspective shaped by technology, telecommunications, defense, data infrastructure, and precision medicine.",
    "value4title": "Governance Mindset",
    "value4desc": "A commitment to fiduciary responsibility, candid dialogue, ethical innovation, and durable stakeholder value.",
    "cta": "Discuss a Board Mandate",
    "availability": "Select independent director, advisory board, and strategic counsel engagements are considered."
  },
  "thesis": {
    "eyebrow": "Leadership Thesis",
    "title": "Build for the Long Term. Decide in the Present.",
    "lead": "Technology changes quickly; the obligations of leadership do not. Durable enterprises unite ambition with discipline, evidence, and accountability.",
    "intro": "These principles reflect more than three decades of founding companies, engineering critical systems, advising boards, and leading through market cycles.",
    "believeEyebrow": "What I Believe",
    "believeTitle": "Seven Principles for Enduring Organizations",
    "b1title": "Strategy Must Produce Choices",
    "b1text": "A strategy is not a catalog of aspirations. It defines where to compete, what capabilities to build, what not to pursue, and how success will be measured.",
    "b2title": "Technology Is a Governance Issue",
    "b2text": "Boards must understand how technology creates value, concentrates risk, and changes accountability. Delegating every technical question is itself a decision.",
    "b3title": "Evidence Should Outrank Enthusiasm",
    "b3text": "Conviction matters, but markets, systems, and science must be tested. Leaders create mechanisms that expose assumptions before customers or regulators do.",
    "b4title": "Architecture Shapes the Enterprise",
    "b4text": "Technical architecture determines speed, resilience, security, and future options. Shortcuts become institutional constraints long after their original context disappears.",
    "b5title": "Trust Is Operating Infrastructure",
    "b5text": "Trust is built through clear commitments, reliable execution, responsible data practices, and direct communication when conditions change.",
    "b6title": "Capital Must Follow Capability",
    "b6text": "Growth investment should reinforce differentiated capabilities and measurable demand, not substitute spending for product-market understanding.",
    "b7title": "Leaders Design Their Successors",
    "b7text": "The strongest leaders build systems, talent, and decision quality that endure beyond their own involvement.",
    "rejectEyebrow": "What I Reject",
    "rejectTitle": "Three Expensive Illusions",
    "r1title": "Innovation Theater",
    "r1text": "Announcements, pilots, and fashionable language do not equal capability. Innovation must improve an outcome that matters.",
    "r2title": "Growth Without Governance",
    "r2text": "Scale magnifies unresolved weaknesses. Controls, culture, and accountability should mature before complexity makes correction costly.",
    "r3title": "False Certainty",
    "r3text": "Executive confidence should not erase uncertainty. Strong decisions make assumptions visible and preserve options when facts change.",
    "horizonEyebrow": "The Horizon",
    "horizonTitle": "The Next Advantage Is Responsible Integration",
    "horizonText": "The defining opportunity is not any single technology. It is the disciplined integration of AI, advanced data systems, biology, and automation into institutions people can trust."
  },
  "press": {
    "eyebrow": "Press & Media",
    "title": "Selected Coverage",
    "lead": "A concise archive of third-party recognition and reporting across technology, entrepreneurship, and precision medicine.",
    "archiveEyebrow": "Archive",
    "y2023type": "Industry Recognition",
    "y2023title": "Top 10 Precision Medicine Companies",
    "y2023desc": "Healthcare Tech Outlook recognized Digital Invest Inc. among leading U.S. companies advancing precision medicine and digital health.",
    "y2023link": "View feature",
    "y2001type": "Executive Award",
    "y2001title": "Entrepreneur of the Year",
    "y2001desc": "Entrepreneur Magazine recognition for leadership, company building, and breakthrough achievement in technology infrastructure.",
    "y2001link": "View archive",
    "y1999type": "Biographical Recognition",
    "y1999title": "Who's Who in America",
    "y1999desc": "Recognition beginning in 1999, followed by listings in Who's Who in the World and Who's Who in Science and Engineering.",
    "clipEyebrow": "From the Archive",
    "clipMeta": "Industry Feature · DataPeer Inc.",
    "clipTitle": "State of the Storage Industry",
    "clipLead": "An early interview with Michael Kofman as Founder, Chairman, and CEO of DataPeer Inc. — reflecting on fiber optics, satellite transmission, SAN, and the emerging storage market.",
    "clipBody": "The feature notes recognition as Entrepreneur of the Year by Entrepreneur Magazine (1999) and discusses DataPeer’s approach to mission-critical storage, iSCSI, and business continuity.",
    "clipOpen": "Open full page scan →",
    "y2000type": "Interview",
    "y2000title": "State of the Storage Industry",
    "y2000desc": "Featured interview as Founder, Chairman, and CEO of DataPeer Inc. on storage networks, iSCSI, and business continuity."
  },
  "ip": {
    "eyebrow": "Intellectual Property",
    "title": "Applied Ideas, Documented",
    "lead": "Selected patents, publications, and research programs connecting engineering rigor with practical business and societal outcomes.",
    "patentEyebrow": "Patents",
    "patentTitle": "Protected Inventions",
    "patentIntro": "Patent work reflects a sustained focus on systems that improve the collection, movement, protection, and interpretation of information.",
    "publicationsEyebrow": "Publications",
    "publicationsTitle": "Technical & Executive Writing",
    "publicationsIntro": "Published work translates complex technical subjects into methods, frameworks, and decisions useful to practitioners and leaders.",
    "researchEyebrow": "Research",
    "researchTitle": "Interdisciplinary Programs",
    "researchIntro": "Research initiatives span secure communications, predictive analytics, genetic interpretation, human digital modeling, and autonomous systems."
  },
  "testimonials": {
    "t1quote": "Michael combines an engineer's precision with the judgment of an experienced chief executive. He asks the questions that improve the decision.",
    "t1name": "Board Colleague",
    "t1role": "Public Technology Company",
    "t2quote": "His ability to connect science, product, governance, and commercial reality brings uncommon clarity to complex initiatives.",
    "t2name": "Strategic Partner",
    "t2role": "Digital Health Sector",
    "t3quote": "Michael is direct, thoughtful, and focused on durable value. He helps leadership teams see both the opportunity and the obligation.",
    "t3name": "Executive Collaborator",
    "t3role": "Global Infrastructure"
  },
  "deck": {
    "title": "Michael Kofman",
    "subtitle": "Executive Leadership, Strategic Technology & Board Advisory",
    "thesis": "Building durable enterprises at the intersection of technology, governance, and human progress.",
    "stat1": "30+ years of executive leadership",
    "stat2": "Multiple companies founded and scaled",
    "stat3": "$19.5B peak market value",
    "contact": "Confidential discussion: contact Michael Kofman through mkofman.com"
  },
  "briefIpo": {
    "title": "What an IPO Changes",
    "desc": "Public markets do not merely change a company's capital structure; they change its operating contract.",
    "p1": "An initial public offering is often described as a financing event. In practice, it is an institutional transition. Forecasting, controls, disclosure, governance, and executive communication must become repeatable before the listing, not improvised afterward.",
    "p2": "Readiness begins with decision quality. Management needs reliable metrics, clear ownership, and an operating cadence that can explain both performance and variance. A company that cannot reconcile its internal narrative will struggle to communicate a credible external one.",
    "p3": "The board's role also changes. Directors must balance growth with oversight, understand material technology and market risks, and ensure that incentives support durable value rather than a single quarter.",
    "p4": "The strongest public companies preserve entrepreneurial speed while adding institutional discipline. The objective is not bureaucracy; it is trustworthy execution at a higher level of accountability."
  },
  "briefGenetic": {
    "title": "From Genetic Data to Clinical Decisions",
    "desc": "The value of genomic information depends on interpretation, evidence, and responsible integration into care.",
    "p1": "Genetic data is abundant; clinically useful meaning is scarce. A result becomes valuable only when it is interpreted in context, connected to validated evidence, and presented in a form that supports a real decision.",
    "p2": "That translation requires collaboration across molecular biology, medicine, statistics, software engineering, and patient communication. Weakness in any layer can turn technical sophistication into clinical confusion.",
    "p3": "Privacy and consent are architectural requirements, not legal footnotes. Systems must limit unnecessary exposure, make data provenance visible, and preserve patient agency as information moves between laboratories, platforms, and care teams.",
    "p4": "Precision medicine will advance through measured integration: better evidence, transparent models, interoperable workflows, and outcomes that clinicians and patients can evaluate. Trust is part of the product."
  },
  "briefAi": {
    "title": "AI Strategy Beyond the Pilot",
    "desc": "Enterprise AI creates value when ownership, data, workflow, and governance mature together.",
    "p1": "Many AI initiatives begin with a compelling demonstration and stall before production. The missing element is rarely the model alone. Sustainable value requires a defined business outcome, accountable owner, dependable data, and a workflow people will actually use.",
    "p2": "Leaders should distinguish automation, prediction, and decision support. Each carries different requirements for accuracy, explainability, human review, and risk. A single governance template will not fit every use case.",
    "p3": "Measurement must include more than technical performance. Adoption, cycle time, error rates, customer impact, security exposure, and the cost of supervision determine whether an AI capability is economically and institutionally sound.",
    "p4": "The winning approach is a managed portfolio: scale proven use cases, stop weak ones early, and maintain explicit boundaries for high-consequence decisions. AI strategy is ultimately operating strategy."
  }
};
