window.__LANG_en = {
  "ui": {
    "toggleTheme": "Toggle light/dark theme",
    "selectLanguage": "Select language",
    "messageSent": "Message Sent",
    "sendMessage": "Send Message",
    "toggleNav": "Toggle navigation",
    "sending": "Sending…",
    "formError": "Could not send. Please email directly.",
    "present": "Present"
  },
  "nav": {
    "home": "Home",
    "about": "About",
    "ventures": "Ventures",
    "career": "The Record",
    "recognition": "Recognition",
    "contact": "Contact",
    "consulting": "Consulting",
    "insights": "Insights",
    "speaking": "Speaking",
    "caseStudies": "Case Studies",
    "mediaKit": "Media Kit",
    "briefIpo": "Brief: IPO",
    "briefGenetic": "Brief: Genetic Data",
    "briefAi": "Brief: AI Strategy",
    "articleInfra": "Data Infrastructure",
    "articleHealth": "Precision Medicine",
    "groupMain": "Main",
    "groupServices": "Services",
    "groupWork": "Work",
    "board": "Board Advisory",
    "thesis": "Leadership Thesis",
    "press": "Press",
    "ip": "Intellectual Property"
  },
  "footer": {
    "navigation": "Navigation",
    "ventures": "Ventures",
    "connect": "Connect",
    "desc": "Technology executive, founder, and board advisor.",
    "copyright": "© {year} Michael Kofman. All Rights Reserved.",
    "writeTitle": "Write to Me",
    "writeEmail": "Your email",
    "writeMessage": "Your message",
    "writeSend": "Send",
    "writeSuccess": "Thank you — your message has been sent.",
    "more": "More",
    "privacy": "Privacy Policy"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — Technology Executive",
      "description": "Technology executive, founder, and board advisor — infrastructure, life sciences, and autonomous systems."
    },
    "about": {
      "title": "About — Michael Kofman",
      "description": "Biography of Michael Kofman — CEO of Digital Invest Inc., founder of AGRON Inc."
    },
    "ventures": {
      "title": "Ventures — Michael Kofman",
      "description": "Companies founded and led by Michael Kofman."
    },
    "career": {
      "title": "The Record — Michael Kofman",
      "description": "Professional record across engineering, infrastructure, public markets, life sciences, and autonomous systems."
    },
    "recognition": {
      "title": "Recognition — Michael Kofman",
      "description": "Awards, honors, and recognition received by Michael Kofman."
    },
    "contact": {
      "title": "Contact — Michael Kofman",
      "description": "Contact Michael Kofman for advisory roles, speaking engagements, and business inquiries."
    },
    "consulting": {
      "title": "Consulting — Michael Kofman",
      "description": "Advisory roles, board positions, speaking engagements, and strategic partnerships with Michael Kofman."
    },
    "insights": {
      "title": "Insights — Michael Kofman",
      "description": "Publications, press features, patents, and industry recognition from Michael Kofman."
    },
    "speaking": {
      "title": "Speaking — Michael Kofman",
      "description": "Invite Michael Kofman to speak on executive leadership, technology strategy, digital health, and board governance."
    },
    "caseStudies": {
      "title": "Case Studies — Michael Kofman",
      "description": "Case studies from Michael Kofman's career — AGRON Inc., 9 Net Avenue Inc., and Digital Invest Inc."
    },
    "mediaKit": {
      "title": "Media Kit — Michael Kofman",
      "description": "Official biographies, photos, and contact information for press and event organizers."
    },
    "article1": {
      "title": "From Engineering to Global Infrastructure — Michael Kofman",
      "description": "Michael Kofman on a career path from satellite engineering to founding global data infrastructure companies."
    },
    "article2": {
      "title": "Precision Medicine and Technology — Michael Kofman",
      "description": "Michael Kofman on combining life sciences with AI, ML, and DNA technologies in modern medicine."
    },
    "privacy": {
      "title": "Privacy Policy — Michael Kofman",
      "description": "Privacy policy for mkofman.com — how we handle contact form data and site analytics."
    },
    "board": {
      "title": "Board Advisory — Michael Kofman",
      "description": "Board service and strategic advisory from Michael Kofman for technology, healthcare, infrastructure, and growth-stage organizations."
    },
    "thesis": {
      "title": "Leadership Thesis — Michael Kofman",
      "description": "Michael Kofman's principles for building durable companies, governing technology, and leading through consequential change."
    },
    "press": {
      "title": "Press Archive — Michael Kofman",
      "description": "Selected press coverage, awards, and media references spanning Michael Kofman's career in technology and entrepreneurship."
    },
    "ip": {
      "title": "Intellectual Property — Michael Kofman",
      "description": "Patents, publications, and applied research by Michael Kofman across computing, communications, data, and digital health."
    },
    "briefIpo": {
      "title": "What an IPO Changes — Michael Kofman",
      "description": "An executive brief on the operating discipline, governance, and accountability required before and after an initial public offering."
    },
    "briefGenetic": {
      "title": "From Genetic Data to Clinical Decisions — Michael Kofman",
      "description": "An executive brief on translating genomic information into responsible, useful, and scalable clinical intelligence."
    },
    "briefAi": {
      "title": "AI Strategy Beyond the Pilot — Michael Kofman",
      "description": "An executive brief on moving artificial intelligence from experimentation to governed, measurable enterprise capability."
    },
    "deck": {
      "title": "Executive Overview — Michael Kofman",
      "description": "Private executive overview for qualified introductions."
    }
  },
  "home": {
    "heroName": "Michael Kofman",
    "heroRole": "Technology Executive · Founder · Board Advisor",
    "heroSub": "Technology, business, and investment across infrastructure, life sciences, and autonomous systems.",
    "heroAlt": "Michael Kofman",
    "featuredEyebrow": "As Featured In",
    "introText": "Michael Kofman is a technology executive and company founder. His work spans satellite engineering, internet infrastructure, public technology companies, and life sciences. He founded 9 Net Avenue Inc., acquired by Concentric Networks in 2000. He is CEO of Digital Invest Inc., in bio-mathematical medicine and genomic intelligence, and founder of AGRON Inc., in autonomous aerial-ground operations and geospatial systems. He serves on boards and advises in technology, health, and infrastructure.",
    "introLink": "Full biography →",
    "currentEyebrow": "Current Work",
    "currentTitle": "Where Focus Is Now",
    "currentDiTitle": "Digital Invest Inc.",
    "currentDiDesc": "Bio-mathematical medicine, genomic data, and clinical intelligence — applying AI, machine learning, and DNA technologies to responsible health outcomes.",
    "currentDiLink": "Ventures →",
    "currentAgTitle": "AGRON Inc.",
    "currentAgDesc": "Autonomous aerial-ground operations, UAV capability development, geospatial systems, and maritime intelligence infrastructure.",
    "currentAgLink": "agron1.com →",
    "careerEyebrow": "Selected Record",
    "careerTitle": "Continuity Across Technology Periods",
    "careerLead": "Selected milestones from engineering through current work in autonomous systems.",
    "career1title": "Engineering & Communications",
    "career1desc": "Satellite transceiver systems, digital communications, and early engineering leadership.",
    "career2title": "Internet & Infrastructure",
    "career2desc": "Internet infrastructure, data centers, storage, and telecommunications at scale.",
    "career3title": "Technology Companies & Public Markets",
    "career3desc": "Company-building, acquisitions, and public-company experience including 9 Net Avenue Inc.",
    "career4title": "Life Sciences & Human Data",
    "career4desc": "Biotechnology, genetic data, precision medicine, and health intelligence platforms.",
    "career5title": "Autonomous Systems",
    "career5desc": "Aerial-ground robotics, UAV operations, and geospatial infrastructure.",
    "careerLink": "The Record →",
    "recEyebrow": "Recognition",
    "recTitle": "Selected Recognition",
    "recLead": "Documented honors and industry references from existing archives.",
    "award1title": "Entrepreneur of the Year",
    "award1desc": "Entrepreneur Magazine · 2001",
    "award2title": "Precision Medicine Recognition",
    "award2desc": "Healthcare Tech Outlook feature · Digital Invest Inc. · 2023",
    "award3title": "Who's Who",
    "award3desc": "America · World · Science & Engineering editions",
    "recLink": "Recognition & press →",
    "perspectivesEyebrow": "Perspectives",
    "perspectivesTitle": "Selected Writing",
    "perspectivesLink": "All insights →",
    "footerHomeDesc": "Technology executive, founder, and board advisor."
  },
  "about": {
    "eyebrow": "About Michael Kofman",
    "title": "Michael Kofman",
    "lead": "Technology executive, founder, and board advisor.",
    "glance": "At a Glance",
    "role": "Current Role",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "Location",
    "locationVal": "Charlotte, North Carolina",
    "education": "Education",
    "educationVal": "Doctor of Technical Sciences\nPh.D. in Information Technology\nMaster's in Electronic Engineering",
    "university": "University",
    "universityVal": "Ukrainian State Marine Technical University",
    "languages": "Languages",
    "languagesVal": "English, Russian, Ukrainian",
    "contactLabel": "Contact",
    "secIntroTitle": "Introduction",
    "secTechTitle": "Technology",
    "secBusinessTitle": "Business",
    "secCurrentTitle": "Current Work",
    "secBackgroundTitle": "Background",
    "recordLink": "The Record →",
    "archiveEyebrow": "From the Archive",
    "archiveTitle": "Selected Photographs",
    "archiveLead": "Authentic material from company building, infrastructure, and leadership.",
    "photo9netTitle": "9 Net Avenue",
    "photo9netCaption": "Founder & CEO — hosting and internet infrastructure company, acquired by Concentric Networks in 2000.",
    "photoServerTitle": "Data Infrastructure",
    "photoServerCaption": "Storage, networking, and server environments at DataPeer and related ventures.",
    "photoTodayTitle": "Today",
    "photoTodayCaption": "Digital Invest Inc., AGRON Inc., and board advisory work.",
    "bioP1": "Michael Kofman is a technology executive, founder, and board advisor. He is CEO of Digital Invest Inc. and founder of AGRON Inc., with prior work spanning satellite engineering, internet infrastructure, public technology companies, and life sciences in the U.S. and Europe.",
    "secTechP1": "Engineering background includes satellite transceiver systems at the Nikolaev Shipbuilding Plant and digital communications work at Astra Corp, one of Europe's manufacturers of digital transceiver satellite systems.",
    "secBusinessP1": "Founded and led multiple technology companies including 9 Net Avenue Inc., DataPeer Inc., XIBI Group Inc., and Elitan United Inc. Full chronology is documented in The Record.",
    "secCurrentP1": "CEO of Digital Invest Inc., focused on bio-mathematical medicine and genomic intelligence. Founder of AGRON Inc., building autonomous aerial-ground operations, UAV capability development, and geospatial systems.",
    "secBackgroundP1": "Doctor of Technical Sciences and Ph.D. in Information Technology. Author of technical papers on satellite and optical systems; patent in digital satellite HDTV subsequently acquired by Sony.",
    "secResearchTitle": "Research & Patents",
    "secResearchP1": "Technical papers on satellite and optical data transmission systems. Patent in digital satellite high-definition television (HDTV), subsequently acquired by Sony."
  },
  "ventures": {
    "eyebrow": "Ventures",
    "title": "Companies & Ventures",
    "lead": "Current companies and selected history from Michael Kofman's professional record.",
    "currentEyebrow": "Current",
    "historyEyebrow": "Selected History",
    "statusActive": "Active",
    "statusExited": "Exited",
    "statusLegacy": "Legacy",
    "v1lesson": "Lesson: infrastructure wins when reliability, economics, and customer trust improve together.",
    "v2lesson": "Lesson: precision medicine requires equal discipline in science, software, privacy, and clinical usefulness.",
    "v3lesson": "Lesson: autonomy creates value only when sensing, communications, and human oversight form one resilient system.",
    "v5lesson": "Lesson: infrastructure scale is earned through operational excellence long before the exit.",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — an Aerial-Ground Robotics Operations Network spanning UAV and Counter-UAS consulting, technology assessment, capability development, training infrastructure, product validation, geospatial systems (ISDRI), and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "v0role": "Founder",
    "v0year": "2026 — Present",
    "v1highlight": "Healthcare Tech Outlook feature — 2023",
    "v1p1": "Bio-mathematical medicine, genomic data, and clinical intelligence — AI, machine learning, and DNA technologies applied to clinical and research workflows.",
    "v1role": "Founder & CEO · Board Member",
    "v1year": "2021 — Present",
    "v2highlight": "Harvard Medical School & Stanford Biomath Partner",
    "v2p1": "DNA testing and analysis, automation of genetic profiling, and comprehensive human genetic research. Initiated genetic testing projects in Ukraine, Russia, and the Baltic countries.",
    "v2p2": "Collaborated with Harvard Medical School and Stanford Biomath on genetic reporting formats used in laboratory workflows.",
    "v2role": "CEO & CTO",
    "v2year": "2008 — 2014",
    "v3highlight": "Enterprise & Government Data Solutions",
    "v3p1": "Data storage and big data management services for large commercial and government organizations. Established the company as a trusted provider of enterprise data solutions.",
    "v3role": "Founder & CEO · Board of Directors",
    "v3year": "2006 — 2011",
    "v4highlight": "Global Data Management Platform",
    "v4p1": "Data management and storage for small and medium-sized businesses. Developed solutions for faster information tracking and easier data accessibility for end-users and government institutions worldwide.",
    "v4role": "Founder & CEO",
    "v4year": "2000 — 2004",
    "v5highlight": "Acquired · Concentric Networks, 2000",
    "v5p1": "Founded and led a hosting and internet infrastructure company. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "v5role": "Founder & CEO",
    "v5year": "1996 — 2000",
    "v6highlight": "Global IT Strategy & Infrastructure",
    "v6p1": "IT company from Massachusetts providing comprehensive strategies and technological services for leading global organizations. Led scalable infrastructure development and global IT operations.",
    "v6role": "CEO & Director of Information Technology",
    "v6year": "1994 — 1996",
    "v7highlight": "European Satellite Systems Leader",
    "v7p1": "One of Europe's largest manufacturers of digital transceiver satellite systems. Led research, operating system development, network software applications, and overall technical strategy.",
    "v7role": "Founder & CEO",
    "v7year": "1989 — 1994",
    "v8highlight": "Military Satellite Systems Engineering",
    "v8p1": "Development and creation of satellite transceiver systems for transmitting classified information to military ships. Recognized as an electronics engineer of the highest level at a plant of 93,000 employees.",
    "v8role": "Electronics Engineer · Highest Category (6th)",
    "v8year": "1984 — 1989"
  },
  "career": {
    "eyebrow": "Professional Record",
    "title": "The Record",
    "lead": "Documented activity across engineering, infrastructure, public markets, life sciences, and autonomous systems.",
    "periodCurrent": "Current",
    "periodCurrentLead": "Principal companies and projects in active development.",
    "period1title": "Engineering & Communications",
    "period1lead": "Early engineering, satellite systems, communications, and related technology work.",
    "period2title": "Internet & Infrastructure",
    "period2lead": "Internet infrastructure, telecommunications, data centers, storage, and related companies.",
    "period3title": "Companies & Public Markets",
    "period3lead": "Company building, transactions, public-company involvement, and executive roles.",
    "period4title": "Life Sciences & Human Data",
    "period4lead": "Biotechnology, health-related technology, data, and precision medicine.",
    "period5title": "Government & Defense Programs",
    "period5lead": "Technology strategy and delivery for government, defense, and state-owned enterprise programs.",
    "t0desc": "Founded AGRON Inc. to build the AGRON Ecosystem — consulting, assessment, capability development, training infrastructure, and product support for UAV and Counter-UAS programmes, plus AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure. Connects aerial and ground robotics, governed mission execution, and network infrastructure linking teams, assets, and operational data.",
    "t0role": "Founder",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — Present",
    "s1desc": "CEO/CTO leadership across public and private companies, from early stage through scale.",
    "s1title": "Executive Leadership",
    "s2desc": "Full public offering execution — legal structuring, SEC coordination, investor roadshows, and compliance.",
    "s2title": "IPO & Financial Scaling",
    "s3desc": "Scalable systems design for enterprise automation, predictive monitoring, and centralized data control.",
    "s3title": "Platform Architecture",
    "s4desc": "Data center development and operations for government, military, and high-security commercial platforms.",
    "s4title": "Secure Infrastructure",
    "t10desc": "Developed satellite transceiver systems for military communications. Electronics engineer, 6th category — highest level at the Nikolaev Shipbuilding Plant (93,000 employees).",
    "t10role": "Electronics Engineer — 6th Category (Highest)",
    "t10title": "Nikolaev Shipbuilding Plant",
    "t10year": "1984 — 1989",
    "t1desc": "Founded Digital Invest Inc. in 2021. Leads bio-mathematical medicine, genomic intelligence, and clinical data platforms. Directed data-center and enterprise software operations in the U.S. and Europe. Featured in Healthcare Tech Outlook (2023).",
    "t1role": "Founder & CEO",
    "t1title": "Digital Invest Inc.",
    "t1year": "2021 — Present",
    "t2desc": "Directed technology strategy and delivery for government, defense, and state-owned enterprise programs — including secure infrastructure, data integration, and high-throughput data centers in the U.S. and Europe.",
    "t2role": "Chief Technology Advisor / Program Architect",
    "t2title": "GovTech, Defense & State Programs",
    "t2year": "2001 — 2019",
    "t3desc": "Led DNA testing and analysis, automation of genetic profiling, and human genetic research. Initiated genetic testing projects in Ukraine, Russia, and the Baltic countries. Collaborated with Harvard Medical School and Stanford Biomath on genetic reporting formats used in laboratory workflows.",
    "t3role": "CEO & CTO",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4desc": "Directed national infrastructure rollouts across Canada, Italy, Switzerland, Ukraine, and the Baltic Republics. Oversaw large engineering and deployment teams across telecom operations including switching systems, broadband expansion, and cross-border connectivity.",
    "t4role": "VP of Technology / Regional CTO — Eastern Europe & CIS",
    "t4title": "Telecommunications Projects",
    "t4year": "2000 — 2012",
    "t5desc": "Founded a technology company specializing in data storage and big data management services for large commercial and government organizations. Established the company as a trusted provider of enterprise data solutions.",
    "t5role": "Founder & CEO · Board of Directors",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6desc": "Established a data management and storage company for SMBs. Developed unique technological solutions for faster information tracking and easier data accessibility for end-users and government institutions worldwide.",
    "t6role": "Founder & CEO",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "Founded and led 9 Net Avenue Inc., a hosting and internet infrastructure company. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "t7role": "Founder & CEO",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8desc": "Led comprehensive IT strategies and technological services for leading global organizations from Massachusetts during a period of rapid expansion, building scalable infrastructure and global IT operations.",
    "t8role": "CEO & Director of Information Technology",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9desc": "Founded Astra Corp, a manufacturer of digital transceiver satellite systems. Led research, operating system development, network software applications, and technical strategy.",
    "t9role": "Founder & CEO",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994"
  },
  "recognition": {
    "eyebrow": "Documented Record",
    "title": "Recognition",
    "lead": "Honors, credentials, and references from existing archives.",
    "industryEyebrow": "Honors & References",
    "industryTitle": "Selected Entries",
    "ipEyebrow": "Intellectual Property",
    "ipTitle": "Patents & Publications",
    "eduEyebrow": "Education",
    "eduTitle": "Academic Credentials",
    "pressEyebrow": "Press & Media",
    "pressTitle": "Featured In",
    "moreLink": "View patents, publications, and press features on Insights →",
    "a1title": "Entrepreneur of the Year",
    "a1desc": "Entrepreneur Magazine · 2001",
    "a2title": "Precision Medicine Recognition",
    "a2desc": "Healthcare Tech Outlook feature · Digital Invest Inc. · 2023",
    "a3title": "Who's Who in America",
    "a3desc": "Listed · 1999 — 2018",
    "a4title": "Who's Who in the World",
    "a4desc": "Listed · 2000 — 2004",
    "a5title": "Who's Who in Science & Engineering",
    "a5desc": "Listed · 2000 — 2014",
    "a6title": "Electronics Engineer — 6th Category",
    "a6desc": "Nikolaev Shipbuilding Plant · satellite transceiver systems engineering",
    "ip1year": "Patent",
    "ip1title": "Digital Satellite HDTV Systems",
    "ip1role": "Patent acquired by Sony Corporation",
    "ip1desc": "Patent in digital satellite high-definition television (HDTV) systems, subsequently acquired by Sony Corporation.",
    "ip2year": "Publications",
    "ip2title": "Technical Papers",
    "ip2role": "Satellite & Optical Systems",
    "ip2desc": "Author of technical papers focused on satellite and optical systems for data transmission. Research contributions span signal processing, simulation modeling, and automation platforms applied in telecommunications, national infrastructure, and digital health.",
    "ip3year": "Research",
    "ip3title": "International Collaborations",
    "ip3role": "U.S. & Europe",
    "ip3desc": "Engaged in international research collaborations and knowledge transfer initiatives. Developed embedded engineering systems for data acquisition, predictive diagnostics, and cloud-based orchestration across multiple industries.",
    "edu1title": "Doctor of Technical Sciences",
    "edu2title": "Ph.D. in Information Technology",
    "edu3title": "Master's Degrees",
    "edu3desc": "Electronics, Digital Satellite Systems, and Economics",
    "press1title": "Healthcare Tech Outlook",
    "press1role": "Digital Invest Inc. Feature",
    "press1desc": "Healthcare Tech Outlook feature on Digital Invest Inc. and precision medicine (2023).",
    "press1link": "Read Feature →",
    "press2title": "Top Precision Medicine Solutions",
    "press2role": "Industry Recognition",
    "press2desc": "Listed among precision medicine solutions companies · Digital Invest Inc.",
    "press2link": "View Listing →"
  },
  "contact": {
    "eyebrow": "Contact",
    "title": "Contact",
    "lead": "Business, board and advisory, media, and other professional inquiries.",
    "infoTitle": "Reach Out Directly",
    "email": "Email",
    "phone": "Phone",
    "location": "Location",
    "locationVal": "Charlotte, North Carolina\nUnited States",
    "linkedin": "LinkedIn",
    "company": "Current Company",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member\nAGRON Inc.\nFounder",
    "formTitle": "Send a Message",
    "formLead": "Professional inquiries only.",
    "firstName": "First Name",
    "lastName": "Last Name",
    "emailLabel": "Email Address",
    "subject": "Subject",
    "message": "Message",
    "inquiryType": "Inquiry Type",
    "inquiryBusiness": "Business",
    "inquiryAdvisory": "Board & Advisory",
    "inquiryPress": "Media",
    "inquiryOther": "Other professional inquiry",
    "calendlyEyebrow": "Schedule a Conversation",
    "calendlyTitle": "Choose a Convenient Time",
    "calendlyLead": "For qualified board, advisory, speaking, and strategic partnership inquiries.",
    "calendlyPlaceholder": "Scheduling calendar will appear here.",
    "calendlyCta": "Open Scheduling Calendar",
    "infoEyebrow": "Contact Information"
  },
  "consulting": {
    "eyebrow": "Board & Advisory",
    "title": "Board & Advisory",
    "heroEyebrow": "Selective Engagement",
    "heroTitle": "Board & Strategic Advisory",
    "heroLead": "Selected board and strategic advisory engagements for technology, health, infrastructure, and growth-stage organizations.",
    "cta": "For board and advisory inquiries",
    "introLead": "Experience spans company building, public and private markets, technology architecture, and executive leadership across the U.S. and Europe.",
    "specialtiesEyebrow": "Areas",
    "specialtiesTitle": "Board Service · CEO & Founder Advisory · Technology Due Diligence",
    "area1title": "Board Service",
    "area1desc": "Independent director and board-level work in technology strategy, corporate governance, and growth-stage oversight.",
    "area2title": "CEO & Founder Advisory",
    "area2desc": "Corporate and technology strategy, organizational development, transactions, and applicable capital-markets experience.",
    "area3title": "Technology Due Diligence",
    "area3desc": "Evaluation of infrastructure, data platforms, security architecture, and applied technology based on documented operating experience."
  },
  "insights": {
    "eyebrow": "Perspectives",
    "title": "Insights",
    "heroTitle": "Selected Writing",
    "selectedEyebrow": "Selected Highlights",
    "selectedTitle": "Featured Recognition",
    "allPressTitle": "All Press Features",
    "quotesEyebrow": "In the Media",
    "quotesTitle": "Industry Recognition & Quotes",
    "articlesEyebrow": "Perspectives",
    "articlesTitle": "Executive Perspectives",
    "briefsEyebrow": "Executive Briefs",
    "briefsTitle": "Ideas for Leaders",
    "briefsLead": "Short, practical perspectives on governance, technology, healthcare, and company building.",
    "brief1title": "What an IPO Changes",
    "brief1desc": "The operating and governance disciplines that public-market readiness demands.",
    "brief1tag": "Capital Markets",
    "brief2title": "From Genetic Data to Clinical Decisions",
    "brief2desc": "How to build useful health intelligence without outrunning evidence or trust.",
    "brief2tag": "Precision Medicine",
    "brief3title": "AI Strategy Beyond the Pilot",
    "brief3desc": "A framework for turning experiments into governed enterprise capability.",
    "brief3tag": "Artificial Intelligence",
    "readingEyebrow": "Reading List",
    "readingTitle": "Books That Shape Strategic Thinking",
    "r1title": "The Innovator's Dilemma",
    "r1author": "Clayton M. Christensen",
    "r2title": "Thinking, Fast and Slow",
    "r2author": "Daniel Kahneman",
    "r3title": "The Beginning of Infinity",
    "r3author": "David Deutsch",
    "r4title": "Good Strategy/Bad Strategy",
    "r4author": "Richard Rumelt",
    "r5title": "The Structure of Scientific Revolutions",
    "r5author": "Thomas S. Kuhn",
    "newsletterEyebrow": "Occasional Notes",
    "newsletterTitle": "Executive Perspective, Without the Noise",
    "newsletterLead": "Periodic essays and brief observations on technology, governance, and durable company building.",
    "newsletterCta": "Subscribe for Updates"
  },
  "cta": {
    "eyebrow": "Work Together",
    "title": "Request Advisory or a Speaking Engagement",
    "lead": "For advisory roles, board positions, speaking engagements, and strategic partnerships.",
    "button": "Get in Touch"
  },
  "speaking": {
    "eyebrow": "Speaking Engagements",
    "title": "Invite Michael Kofman to Speak",
    "lead": "Available for speaking engagements on executive leadership, technology strategy, digital health, data infrastructure, and corporate governance.",
    "topicsEyebrow": "Speaking Topics",
    "topicsTitle": "Areas of Expertise",
    "topicsLead": "Topics draw on decades of experience founding and leading companies in the United States and Europe.",
    "processEyebrow": "How to Invite",
    "processTitle": "Booking Process",
    "process1title": "Send an Inquiry",
    "process1desc": "Use the contact form or email mkofman@mkofman.com with event details, audience, and preferred topics.",
    "process2title": "Confirm Scope",
    "process2desc": "Discuss format — keynote, panel, board session, or executive roundtable — and logistics.",
    "process3title": "Deliver Value",
    "process3desc": "Presentations are grounded in real outcomes from ventures across data storage, govtech, and precision medicine.",
    "cta": "Request a Speaking Engagement",
    "catalogEyebrow": "Speaking Topics",
    "catalogTitle": "Executive Conversations for Consequential Change",
    "catalogLead": "Keynotes, board sessions, and leadership briefings tailored to the audience, sector, and decision context.",
    "t1title": "Governing AI Before It Governs the Enterprise",
    "t1audience": "Boards, audit and risk committees",
    "t1format": "Board briefing or keynote",
    "t2title": "From Technology Trend to Enterprise Strategy",
    "t2audience": "CEOs, executive teams, investors",
    "t2format": "Keynote or executive workshop",
    "t3title": "Building Companies Through Market Cycles",
    "t3audience": "Founders, growth leaders, private equity",
    "t3format": "Fireside chat or keynote",
    "t4title": "Precision Medicine: Promise, Proof, and Responsibility",
    "t4audience": "Healthcare leaders, clinicians, innovators",
    "t4format": "Industry keynote or panel",
    "t5title": "The Board's Role in Cyber and Technology Risk",
    "t5audience": "Directors, general counsel, risk leaders",
    "t5format": "Board education session",
    "t6title": "Engineering Trust into Digital Infrastructure",
    "t6audience": "Technology and infrastructure organizations",
    "t6format": "Technical-executive keynote",
    "t7title": "Leading Across Borders and Disciplines",
    "t7audience": "Global leadership teams and universities",
    "t7format": "Keynote or moderated conversation",
    "t8title": "From Founder to Institution Builder",
    "t8audience": "Entrepreneurs and next-generation executives",
    "t8format": "Workshop or fireside chat"
  },
  "caseStudies": {
    "eyebrow": "Case Studies",
    "title": "Case Studies",
    "lead": "Selected company records with context, role, work, and outcome.",
    "cs1eyebrow": "Data Infrastructure · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "Challenge",
    "cs1challengeText": "Build and scale a Data Storage company in a rapidly consolidating technology market.",
    "cs1action": "Approach",
    "cs1actionText": "Founded 9 Net Avenue Inc. in 1996 as a hosting and internet infrastructure company.",
    "cs1result": "Outcome",
    "cs1resultText": "Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO). Following the transaction, continued work with public companies and board-level roles.",
    "cs2eyebrow": "Digital Health · 2021 — Present",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "Challenge",
    "cs2challengeText": "Apply science, DNA technologies, AI, and ML through a bio-mathematical platform in medicine.",
    "cs2action": "Approach",
    "cs2actionText": "Founded Digital Invest Inc. in 2021. Leads bio-mathematical medicine, genomic intelligence, and clinical data platforms; directed data-center and enterprise software operations in the U.S. and Europe.",
    "cs2result": "Outcome",
    "cs2resultText": "Healthcare Tech Outlook feature (2023). Projects include Human Digital Model and BioMath Life.",
    "cs3eyebrow": "Robotics & UAV · 2026 — Present",
    "cs3title": "AGRON Inc.",
    "cs3challenge": "Challenge",
    "cs3challengeText": "Organizations building UAV and Counter-UAS capability need independent assessment, structured training, and operational architecture — not isolated platforms or ad-hoc piloting.",
    "cs3action": "Approach",
    "cs3actionText": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — consulting, assessment and validation, capability development, training infrastructure, product development support, geospatial systems through ISDRI, and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "cs3result": "Outcome",
    "cs3resultText": "A connected professional services ecosystem spanning consulting, capability development, training infrastructure, geospatial systems, and maritime intelligence through AGRON, ISDRI, and related companies."
  },
  "mediaKit": {
    "eyebrow": "Press & Events",
    "title": "Media Kit",
    "lead": "Official biographies, imagery, and contact details for press, conferences, and board inquiries.",
    "bioEyebrow": "Biographies",
    "bioTitle": "Official Bios",
    "bioShortLabel": "50 Words",
    "bioShort": "Michael Kofman is CEO of Digital Invest Inc. and a board member, advisor, and founder of companies in technology and digital health across the U.S. and Europe.",
    "bioMediumLabel": "150 Words",
    "bioMedium": "Michael Kofman is CEO of Digital Invest Inc. and serves on its board. An entrepreneur, board member, and advisor, he has founded companies in the U.S. and Europe across data infrastructure, digital health, and robotics. His work spans technology strategy, security, research, and investment.",
    "bioLongLabel": "500 Words",
    "bioLong": "Michael Kofman is CEO of Digital Invest Inc. and serves on its board. He founded 9 Net Avenue Inc., acquired by Concentric Networks in 2000, and leads Digital Invest in bio-mathematical medicine and genomic intelligence. He founded AGRON Inc. in 2026 for autonomous aerial-ground operations and geospatial systems. Author of technical papers on satellite and optical systems; patent in digital satellite HDTV acquired by Sony. Education: Doctor of Technical Sciences, Ph.D. in Information Technology.",
    "photosEyebrow": "Photography",
    "photosTitle": "Approved Images",
    "photosLead": "High-resolution portraits available upon request at mkofman@mkofman.com.",
    "contactEyebrow": "Press Contact",
    "contactTitle": "Media Inquiries",
    "contactLead": "For interviews, speaking invitations, and press requests.",
    "downloadEyebrow": "Download",
    "downloadTitle": "One-Page Media Kit",
    "downloadLead": "PDF with official bios, portrait, and press contact — ready to share with organizers and journalists.",
    "downloadCta": "Download PDF",
    "brandEyebrow": "Brand Assets",
    "brandTitle": "Identity & Usage",
    "brandLead": "Approved visual assets for editorial, conference, and partner use. Please preserve proportions, spacing, and original colors.",
    "brandColors": "Official Color Palette",
    "brandLogo": "Primary Logo",
    "brandDownload": "Download Brand Assets"
  },
  "articles": {
    "backLink": "← Back to Insights",
    "article1date": "Executive Perspective",
    "article1title": "From Engineering to Global Data Infrastructure",
    "article1p1": "My career began at the Nikolaev Shipbuilding Plant in Ukraine, developing satellite transceiver systems for transmitting classified information to military ships. I was recognized as an electronics engineer of the highest level — the 6th category at a plant of 93,000 employees.",
    "article1p2": "From 1989 to 1994, I founded and led Astra Corp, a manufacturer of digital transceiver satellite systems. From 1994 to 1996, as CEO of Elitan United Inc., I led IT strategy and infrastructure during a period of rapid expansion.",
    "article1p3": "In 1996, I founded 9 Net Avenue Inc., a hosting and internet infrastructure company. In 2000 it was acquired by Concentric Networks (NASDAQ: CNTX) and subsequently became part of XO Communications (NASDAQ: XOXO).",
    "article1p4": "From 2001 to 2019, I directed technology strategy for government, defense, and state-owned enterprise programs — leading large-scale initiatives in big data, secure infrastructure, and high-throughput data centers across the United States and Europe.",
    "article2date": "Digital Health",
    "article2title": "Precision Medicine and the Convergence of Science and Technology",
    "article2p1": "Life sciences advance when rigorous technology is applied to evidence, interpretation, and clinical utility.",
    "article2p2": "Under my leadership, successful genetic testing projects were initiated in Ukraine, Russia, and the Baltic countries. In collaboration with Harvard Medical School and Stanford Biomath, I played a crucial role in developing easily understandable genetic reports for both doctors and patients.",
    "article2p3": "With Digital Invest Inc., founded in 2021, we work in bio-mathematical medicine — applying science, DNA technologies, AI, and ML to clinical intelligence. Healthcare Tech Outlook featured the company in 2023.",
    "article2p4": "Digital Invest advances bio-mathematical medicine through projects including Human Digital Model and BioMath Life. In 2026, Michael Kofman founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network — UAV capability development, geospatial systems, and maritime intelligence at agron1.com."
  },
  "privacy": {
    "eyebrow": "Legal",
    "title": "Privacy Policy",
    "lead": "This policy explains how mkofman.com handles information when you visit the site or send a message.",
    "updated": "Last updated: July 2026",
    "s1title": "Information We Collect",
    "s1text": "When you submit a contact or footer form, we receive the fields you provide (such as name, email, and message). If analytics are enabled, we may collect anonymized usage data (pages visited, referrer, device type).",
    "s2title": "How We Use Information",
    "s2text": "Form submissions are used to respond to your inquiry. Analytics help improve the website. We do not sell personal data.",
    "s3title": "Third-Party Services",
    "s3text": "Forms may be processed by Formspree. Analytics may use Plausible or Google Analytics if configured. These providers have their own privacy policies.",
    "s4title": "Your Rights",
    "s4text": "You may request access, correction, or deletion of your data by emailing mkofman@mkofman.com.",
    "s5title": "Contact",
    "s5text": "Questions about this policy: mkofman@mkofman.com"
  },
  "board": {
    "eyebrow": "Board & Strategic Advisory",
    "title": "Independent Judgment for Consequential Decisions",
    "lead": "I work with boards, founders, and executive teams navigating technology risk, market transitions, capital allocation, and responsible growth.",
    "rolesEyebrow": "Ways to Engage",
    "rolesTitle": "Board-Level Partnership",
    "role1title": "Independent Director",
    "role1desc": "Constructive oversight, informed challenge, and long-range perspective for public and private company boards.",
    "role2title": "Advisory Board Member",
    "role2desc": "Practical guidance on emerging technologies, product strategy, market positioning, and institutional readiness.",
    "role3title": "CEO & Founder Advisor",
    "role3desc": "Confidential counsel for leaders facing inflection points in scale, governance, succession, financing, or transformation.",
    "role4title": "Special Committee Advisor",
    "role4desc": "Focused support for transactions, technology diligence, cybersecurity exposure, and other high-stakes mandates.",
    "valueEyebrow": "Perspective",
    "valueTitle": "What I Bring to the Table",
    "value1title": "Operator's Discipline",
    "value1desc": "Experience building organizations from inception through global scale, acquisition, and public-market accountability.",
    "value2title": "Technical Fluency",
    "value2desc": "The ability to translate complex systems, scientific claims, and technology risk into clear board decisions.",
    "value3title": "Cross-Market Judgment",
    "value3desc": "A perspective shaped by technology, telecommunications, defense, data infrastructure, and precision medicine.",
    "value4title": "Governance Mindset",
    "value4desc": "A commitment to fiduciary responsibility, candid dialogue, ethical innovation, and durable stakeholder value.",
    "cta": "Discuss a Board Mandate",
    "availability": "Select independent director, advisory board, and strategic counsel engagements are considered."
  },
  "thesis": {
    "eyebrow": "Leadership Thesis",
    "title": "Build for the Long Term. Decide in the Present.",
    "lead": "Technology changes quickly; the obligations of leadership do not. Durable enterprises unite ambition with discipline, evidence, and accountability.",
    "intro": "These principles reflect more than three decades of founding companies, engineering critical systems, advising boards, and leading through market cycles.",
    "believeEyebrow": "What I Believe",
    "believeTitle": "Seven Principles for Enduring Organizations",
    "b1title": "Strategy Must Produce Choices",
    "b1text": "A strategy is not a catalog of aspirations. It defines where to compete, what capabilities to build, what not to pursue, and how success will be measured.",
    "b2title": "Technology Is a Governance Issue",
    "b2text": "Boards must understand how technology creates value, concentrates risk, and changes accountability. Delegating every technical question is itself a decision.",
    "b3title": "Evidence Should Outrank Enthusiasm",
    "b3text": "Conviction matters, but markets, systems, and science must be tested. Leaders create mechanisms that expose assumptions before customers or regulators do.",
    "b4title": "Architecture Shapes the Enterprise",
    "b4text": "Technical architecture determines speed, resilience, security, and future options. Shortcuts become institutional constraints long after their original context disappears.",
    "b5title": "Trust Is Operating Infrastructure",
    "b5text": "Trust is built through clear commitments, reliable execution, responsible data practices, and direct communication when conditions change.",
    "b6title": "Capital Must Follow Capability",
    "b6text": "Growth investment should reinforce differentiated capabilities and measurable demand, not substitute spending for product-market understanding.",
    "b7title": "Leaders Design Their Successors",
    "b7text": "The strongest leaders build systems, talent, and decision quality that endure beyond their own involvement.",
    "rejectEyebrow": "What I Reject",
    "rejectTitle": "Three Expensive Illusions",
    "r1title": "Innovation Theater",
    "r1text": "Announcements, pilots, and fashionable language do not equal capability. Innovation must improve an outcome that matters.",
    "r2title": "Growth Without Governance",
    "r2text": "Scale magnifies unresolved weaknesses. Controls, culture, and accountability should mature before complexity makes correction costly.",
    "r3title": "False Certainty",
    "r3text": "Executive confidence should not erase uncertainty. Strong decisions make assumptions visible and preserve options when facts change.",
    "horizonEyebrow": "The Horizon",
    "horizonTitle": "The Next Advantage Is Responsible Integration",
    "horizonText": "The defining opportunity is not any single technology. It is the disciplined integration of AI, advanced data systems, biology, and automation into institutions people can trust."
  },
  "press": {
    "eyebrow": "Press & Media",
    "title": "Selected Coverage",
    "lead": "A concise archive of third-party recognition and reporting across technology, entrepreneurship, and precision medicine.",
    "archiveEyebrow": "Archive",
    "y2023type": "Industry Recognition",
    "y2023title": "Healthcare Tech Outlook Feature",
    "y2023desc": "Healthcare Tech Outlook recognized Digital Invest Inc. among leading U.S. companies advancing precision medicine and digital health.",
    "y2023link": "View feature",
    "y2001type": "Executive Award",
    "y2001title": "Entrepreneur of the Year",
    "y2001desc": "Entrepreneur Magazine recognition.",
    "y2001link": "View archive",
    "y1999type": "Biographical Recognition",
    "y1999title": "Who's Who in America",
    "y1999desc": "Recognition beginning in 1999, followed by listings in Who's Who in the World and Who's Who in Science and Engineering.",
    "clipEyebrow": "From the Archive",
    "clipMeta": "Industry Feature · DataPeer Inc.",
    "clipTitle": "State of the Storage Industry",
    "clipLead": "An early interview with Michael Kofman as Founder, Chairman, and CEO of DataPeer Inc. — reflecting on fiber optics, satellite transmission, SAN, and the emerging storage market.",
    "clipBody": "The feature notes recognition as Entrepreneur of the Year by Entrepreneur Magazine (2001) and discusses DataPeer’s approach to mission-critical storage, iSCSI, and business continuity.",
    "clipOpen": "Open full page scan →",
    "y2000type": "Interview",
    "y2000title": "State of the Storage Industry",
    "y2000desc": "Featured interview as Founder, Chairman, and CEO of DataPeer Inc. on storage networks, iSCSI, and business continuity."
  },
  "ip": {
    "eyebrow": "Intellectual Property",
    "title": "Applied Ideas, Documented",
    "lead": "Selected patents, publications, and research programs connecting engineering rigor with practical business and societal outcomes.",
    "patentEyebrow": "Patents",
    "patentTitle": "Protected Inventions",
    "patentIntro": "Patent work reflects a sustained focus on systems that improve the collection, movement, protection, and interpretation of information.",
    "publicationsEyebrow": "Publications",
    "publicationsTitle": "Technical & Executive Writing",
    "publicationsIntro": "Published work translates complex technical subjects into methods, frameworks, and decisions useful to practitioners and leaders.",
    "researchEyebrow": "Research",
    "researchTitle": "Interdisciplinary Programs",
    "researchIntro": "Research initiatives span secure communications, predictive analytics, genetic interpretation, human digital modeling, and autonomous systems."
  },
  "testimonials": {
    "t1quote": "Michael combines an engineer's precision with the judgment of an experienced chief executive. He asks the questions that improve the decision.",
    "t1name": "Board Colleague",
    "t1role": "Public Technology Company",
    "t2quote": "His ability to connect science, product, governance, and commercial reality brings uncommon clarity to complex initiatives.",
    "t2name": "Strategic Partner",
    "t2role": "Digital Health Sector",
    "t3quote": "Michael is direct, thoughtful, and focused on durable value. He helps leadership teams see both the opportunity and the obligation.",
    "t3name": "Executive Collaborator",
    "t3role": "Global Infrastructure"
  },
  "deck": {
    "title": "Michael Kofman",
    "subtitle": "Technology Executive · Founder · Board Advisor",
    "thesis": "Technology, business, and investment across infrastructure, life sciences, and autonomous systems.",
    "contact": "Confidential discussion: contact Michael Kofman through mkofman.com"
  },
  "briefIpo": {
    "title": "What an IPO Changes",
    "desc": "Public markets do not merely change a company's capital structure; they change its operating contract.",
    "p1": "An initial public offering is often described as a financing event. In practice, it is an institutional transition. Forecasting, controls, disclosure, governance, and executive communication must become repeatable before the listing, not improvised afterward.",
    "p2": "Readiness begins with decision quality. Management needs reliable metrics, clear ownership, and an operating cadence that can explain both performance and variance. A company that cannot reconcile its internal narrative will struggle to communicate a credible external one.",
    "p3": "The board's role also changes. Directors must balance growth with oversight, understand material technology and market risks, and ensure that incentives support durable value rather than a single quarter.",
    "p4": "The strongest public companies preserve entrepreneurial speed while adding institutional discipline. The objective is not bureaucracy; it is trustworthy execution at a higher level of accountability.",
    "eyebrow": "Executive Brief"
  },
  "briefGenetic": {
    "title": "From Genetic Data to Clinical Decisions",
    "desc": "The value of genomic information depends on interpretation, evidence, and responsible integration into care.",
    "p1": "Genetic data is abundant; clinically useful meaning is scarce. A result becomes valuable only when it is interpreted in context, connected to validated evidence, and presented in a form that supports a real decision.",
    "p2": "That translation requires collaboration across molecular biology, medicine, statistics, software engineering, and patient communication. Weakness in any layer can turn technical sophistication into clinical confusion.",
    "p3": "Privacy and consent are architectural requirements, not legal footnotes. Systems must limit unnecessary exposure, make data provenance visible, and preserve patient agency as information moves between laboratories, platforms, and care teams.",
    "p4": "Precision medicine will advance through measured integration: better evidence, transparent models, interoperable workflows, and outcomes that clinicians and patients can evaluate. Trust is part of the product.",
    "eyebrow": "Executive Brief"
  },
  "briefAi": {
    "title": "AI Strategy Beyond the Pilot",
    "desc": "Enterprise AI creates value when ownership, data, workflow, and governance mature together.",
    "p1": "Many AI initiatives begin with a compelling demonstration and stall before production. The missing element is rarely the model alone. Sustainable value requires a defined business outcome, accountable owner, dependable data, and a workflow people will actually use.",
    "p2": "Leaders should distinguish automation, prediction, and decision support. Each carries different requirements for accuracy, explainability, human review, and risk. A single governance template will not fit every use case.",
    "p3": "Measurement must include more than technical performance. Adoption, cycle time, error rates, customer impact, security exposure, and the cost of supervision determine whether an AI capability is economically and institutionally sound.",
    "p4": "The winning approach is a managed portfolio: scale proven use cases, stop weak ones early, and maintain explicit boundaries for high-consequence decisions. AI strategy is ultimately operating strategy.",
    "eyebrow": "Executive Brief"
  }
};
