window.__LANG_es = {
  "ui": {
    "toggleTheme": "Cambiar tema claro/oscuro",
    "selectLanguage": "Seleccionar idioma",
    "messageSent": "Mensaje enviado",
    "sendMessage": "Enviar mensaje",
    "toggleNav": "Abrir menú",
    "sending": "Enviando…",
    "formError": "No se pudo enviar. Por favor, escriba directamente por correo electrónico.",
    "present": "Actual"
  },
  "nav": {
    "home": "Inicio",
    "about": "Biografía",
    "ventures": "Empresas",
    "career": "El registro",
    "recognition": "Reconocimientos",
    "contact": "Contacto",
    "consulting": "Consultoría",
    "insights": "Perspectivas",
    "speaking": "Conferencias",
    "caseStudies": "Casos de estudio",
    "mediaKit": "Kit de prensa",
    "groupMain": "Principal",
    "groupServices": "Servicios",
    "groupWork": "Trabajo",
    "briefIpo": "Informe: IPO",
    "briefGenetic": "Brief: datos genéticos",
    "briefAi": "Brief: estrategia de IA",
    "articleInfra": "Infraestructura de datos",
    "articleHealth": "Medicina de precisión",
    "board": "Asesoría",
    "thesis": "Tesis de liderazgo",
    "press": "Prensa",
    "ip": "Propiedad intelectual"
  },
  "footer": {
    "navigation": "Navegación",
    "ventures": "Empresas",
    "connect": "Contacto",
    "desc": "Ejecutivo tecnológico, fundador y asesor de consejos.",
    "copyright": "© {year} Michael Kofman. Todos los derechos reservados.",
    "writeTitle": "Escríbame",
    "writeEmail": "Su email",
    "writeMessage": "Su mensaje",
    "writeSend": "Enviar",
    "writeSuccess": "Gracias — su mensaje ha sido enviado.",
    "more": "Más",
    "privacy": "Privacidad"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — Ejecutivo tecnológico",
      "description": "Ejecutivo tecnológico, fundador y asesor de consejos — infraestructura, ciencias de la vida y sistemas autónomos."
    },
    "about": {
      "title": "Biografía — Michael Kofman",
      "description": "Biografía de Michael Kofman — CEO de Digital Invest Inc., fundador de AGRON Inc."
    },
    "ventures": {
      "title": "Empresas — Michael Kofman",
      "description": "Empresas fundadas y dirigidas por Michael Kofman."
    },
    "career": {
      "title": "El registro — Michael Kofman",
      "description": "Registro profesional en ingeniería, infraestructura, mercados públicos, ciencias de la vida y sistemas autónomos."
    },
    "recognition": {
      "title": "Reconocimientos — Michael Kofman",
      "description": "Premios, honores y reconocimientos de Michael Kofman — Emprendedor del Año, Who's Who, patentes y distinciones del sector."
    },
    "contact": {
      "title": "Contacto — Michael Kofman",
      "description": "Contacte a Michael Kofman — CEO de Digital Invest Inc. Para conferencias, roles de asesoría y consultas comerciales."
    },
    "consulting": {
      "title": "Consultoría — Michael Kofman",
      "description": "Roles de asesoría, puestos en juntas directivas, conferencias y alianzas estratégicas con Michael Kofman."
    },
    "insights": {
      "title": "Perspectivas — Michael Kofman",
      "description": "Escritos originales y briefs ejecutivos de Michael Kofman."
    },
    "speaking": {
      "title": "Conferencias — Michael Kofman",
      "description": "Invite a Michael Kofman a hablar sobre liderazgo ejecutivo, estrategia tecnológica, salud digital y gobierno corporativo."
    },
    "caseStudies": {
      "title": "Casos de estudio — Michael Kofman",
      "description": "Casos de estudio de la trayectoria de Michael Kofman: 9 Net Avenue Inc. y Digital Invest Inc."
    },
    "mediaKit": {
      "title": "Kit de prensa — Michael Kofman",
      "description": "Biografías oficiales, fotografías e información de contacto para prensa y organizadores de eventos."
    },
    "article1": {
      "title": "De la ingeniería a la infraestructura global — Michael Kofman",
      "description": "Michael Kofman sobre su trayectoria desde la ingeniería satelital hasta la fundación de empresas globales de infraestructura de datos."
    },
    "article2": {
      "title": "Medicina de precisión y tecnología — Michael Kofman",
      "description": "Michael Kofman sobre la integración de las ciencias de la vida con IA, ML y tecnologías de ADN en la medicina moderna."
    },
    "privacy": {
      "title": "Política de privacidad — Michael Kofman",
      "description": "Política de privacidad de mkofman.com: formularios de contacto y analítica."
    },
    "board": {
      "title": "Asesoría — Michael Kofman",
      "description": "Conversaciones de asesoría estratégica con organizaciones de tecnología, salud e infraestructura."
    },
    "thesis": {
      "title": "Tesis de liderazgo — Michael Kofman",
      "description": "Los principios de Michael Kofman para construir empresas duraderas, gobernar la tecnología y liderar cambios trascendentales."
    },
    "press": {
      "title": "Archivo de prensa — Michael Kofman",
      "description": "Cobertura de prensa, premios y referencias mediáticas seleccionadas de la carrera de Michael Kofman en tecnología y emprendimiento."
    },
    "ip": {
      "title": "Propiedad intelectual — Michael Kofman",
      "description": "Patentes, publicaciones e investigación aplicada de Michael Kofman en computación, comunicaciones, datos y salud digital."
    },
    "briefIpo": {
      "title": "Lo que cambia un IPO — Michael Kofman",
      "description": "Informe ejecutivo sobre la disciplina operativa, gobernanza y responsabilidad requeridas antes y después de una oferta pública inicial."
    },
    "briefGenetic": {
      "title": "De datos genéticos a decisiones clínicas — Michael Kofman",
      "description": "Informe ejecutivo sobre traducir información genómica en inteligencia clínica responsable, útil y escalable."
    },
    "briefAi": {
      "title": "Estrategia de IA más allá del piloto — Michael Kofman",
      "description": "Informe ejecutivo sobre cómo llevar la inteligencia artificial de la experimentación a capacidad empresarial gobernada y medible."
    },
    "deck": {
      "title": "Resumen ejecutivo — Michael Kofman",
      "description": "Resumen ejecutivo privado para introducciones calificadas."
    }
  },
  "home": {
    "heroEyebrow": "Sitio oficial de Michael Kofman",
    "heroTitle1": "Hecho para perdurar.",
    "heroTitle2": "Liderado con criterio.",
    "heroCta": "Descubra mi historia",
    "heroAlt": "Michael Kofman",
    "quote1text": "Destacado entre las principales empresas de medicina de precisión y salud digital de EE. UU.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "Empresario del Año — reconocido por liderazgo y logros innovadores en plataformas e infraestructura.",
    "quote2author": "Entrepreneur Magazine · 2001",
    "quote3text": "Digital Invest Inc. entre las 10 mejores empresas de EE. UU. en medicina de precisión y salud digital.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "Precisión de ingeniería y estrategia empresarial — desde sistemas satelitales hasta infraestructura de $",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "Conozca a Michael Kofman",
    "aboutTitle": "Empresas hechas para durar",
    "aboutLead1": "CEO de Digital Invest Inc. y fundador de AGRON Inc. Ha fundado y dirigido empresas en Estados Unidos y Europa.",
    "aboutLead2": "Desde 9 Net Avenue (valoración pico de $",
    "aboutLink": "Leer biografía completa",
    "expertiseEyebrow": "Áreas de enfoque",
    "expertiseTitle": "Liderazgo ejecutivo en múltiples industrias",
    "expertiseLead": "Cuatro décadas construyendo, asesorando e invirtiendo en infraestructura, salud y robótica.",
    "exp1title": "CEO y fundador",
    "exp1desc": "Fundó y dirigió múltiples empresas tecnológicas en Estados Unidos y Europa.",
    "exp1link": "Ver empresas →",
    "exp2title": "Arquitecto tecnológico",
    "exp2desc": "Diseñó comunicaciones seguras, motores de analítica predictiva y plataformas de integración de datos a nivel nacional para los sectores gubernamental, militar y de telecomunicaciones.",
    "exp2link": "Ver carrera →",
    "exp3title": "Salud digital",
    "exp3desc": "Lidera la transformación de la medicina mediante IA, ML y tecnologías de ADN. Colaboró con Harvard Medical School y Stanford Biomath en informes genéticos.",
    "exp3link": "Digital Invest →",
    "exp4title": "Asesor de junta",
    "exp4desc": "Participa en juntas directivas y asesora a empresas públicas y privadas sobre dirección estratégica, gobierno corporativo e iniciativas de crecimiento impulsadas por la tecnología.",
    "exp4link": "Consultoría →",
    "stat1": "Años de liderazgo",
    "stat2": "Empresas fundadas",
    "stat3": "Valor máximo de mercado",
    "stat4": "Empleados escalados",
    "recEyebrow": "Reconocimientos",
    "recTitle": "Reconocimientos seleccionados",
    "recLead": "Honores documentados y referencias del sector en archivos existentes.",
    "award1title": "Emprendedor del Año",
    "award1desc": "Entrepreneur Magazine · 2001",
    "award2title": "Reconocimiento en medicina de precisión",
    "award2desc": "Healthcare Tech Outlook · Digital Invest Inc. · 2023",
    "award3title": "Who's Who",
    "award3desc": "Ediciones América · Mundo · Ciencia e ingeniería",
    "recLink": "Reconocimientos y prensa →",
    "heroSub": "Tecnología, negocios e inversión en infraestructura, ciencias de la vida y sistemas autónomos.",
    "primaryCta": "Solicitar asesoría",
    "secondaryCta": "Ver casos de estudio",
    "featuredEyebrow": "Del archivo",
    "caseStudiesEyebrow": "Resultados comprobados",
    "caseStudiesTitle": "Casos de estudio",
    "caseStudiesLead": "Fundación, escalamiento y liderazgo de empresas desde su inicio hasta adquisiciones y salidas a bolsa.",
    "caseStudiesLink": "Ver todos los casos de estudio →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "Construyó una de las mayores compañías de almacenamiento de datos del mundo, adquirida con una capitalización máxima de mercado de 19.500 millones de dólares.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "Fundada y escalada desde su inicio hasta la salida a bolsa: Top 10 de compañías de medicina de precisión en EE. UU., 2023.",
    "cs3title": "AGRON Inc.",
    "cs3desc": "Founded in 2026 — the AGRON Ecosystem for UAV capability development, geospatial systems, and maritime intelligence.",
    "boardCtaEyebrow": "Advisory",
    "boardCtaTitle": "Experience for the Decisions That Define an Enterprise",
    "boardCtaLead": "Independent perspective for boards and leaders navigating technology, governance, transformation, and growth.",
    "boardCtaBtn": "Explore Advisory",
    "testimonialsEyebrow": "Trusted Perspective",
    "testimonialsTitle": "What Colleagues Value",
    "videoEyebrow": "Executive Perspective",
    "videoTitle": "Leadership at the Intersection of Technology and Enterprise",
    "videoLead": "A concise introduction to the principles, experience, and long-term perspective behind Michael Kofman's work.",
    "videoCta": "Read Leadership Thesis →",
    "heroName": "Michael Kofman",
    "heroRole": "Ejecutivo tecnológico · Fundador · Asesor de consejos",
    "introText": "Michael Kofman es ejecutivo tecnológico y fundador de empresas. Su trabajo abarca ingeniería satelital, infraestructura de internet, empresas tecnológicas públicas y ciencias de la vida. Fundó 9 Net Avenue Inc., adquirida por Concentric Networks en 2000. Es CEO de Digital Invest Inc., en medicina biomatemática e inteligencia genómica, y fundador de AGRON Inc., en operaciones autónomas aéreo-terrestres y sistemas geoespaciales. Participa en consejos y asesora en tecnología, salud e infraestructura.",
    "introLink": "Biografía completa →",
    "currentEyebrow": "Trabajo actual",
    "currentTitle": "Dónde está el foco ahora",
    "currentDiTitle": "Digital Invest Inc.",
    "currentDiDesc": "Medicina biomatemática, datos genómicos e inteligencia clínica — aplicación de IA, aprendizaje automático y tecnologías de ADN a resultados de salud responsables.",
    "currentDiLink": "Empresas →",
    "currentAgTitle": "AGRON Inc.",
    "currentAgDesc": "Operaciones autónomas aéreo-terrestres, desarrollo de capacidades UAV, sistemas geoespaciales e infraestructura de inteligencia marítima.",
    "currentAgLink": "agron1.com →",
    "careerEyebrow": "Registro seleccionado",
    "careerTitle": "Continuidad entre periodos tecnológicos",
    "careerLead": "Hitos seleccionados desde la ingeniería hasta el trabajo actual en sistemas autónomos.",
    "career1title": "Ingeniería y comunicaciones",
    "career1desc": "Sistemas transceptores satelitales, comunicaciones digitales y liderazgo en ingeniería temprana.",
    "career2title": "Internet e infraestructura",
    "career2desc": "Infraestructura de internet, centros de datos, almacenamiento y telecomunicaciones a escala.",
    "career3title": "Empresas tecnológicas y mercados públicos",
    "career3desc": "Creación de empresas, adquisiciones y experiencia en empresas públicas, incluida 9 Net Avenue Inc.",
    "career4title": "Ciencias de la vida y datos humanos",
    "career4desc": "Biotecnología, datos genéticos, medicina de precisión y plataformas de inteligencia sanitaria.",
    "career5title": "Sistemas autónomos",
    "career5desc": "Robótica aérea-terrestre, operaciones UAV e infraestructura geoespacial.",
    "careerLink": "El registro →",
    "perspectivesEyebrow": "Perspectivas",
    "perspectivesTitle": "Escritos seleccionados",
    "perspectivesLink": "Todas las perspectivas →",
    "footerHomeDesc": "Ejecutivo tecnológico, fundador y asesor de consejos.",
    "activeSitesLink": "Todos los sitios activos →"
  },
  "about": {
    "eyebrow": "Sobre Michael Kofman",
    "title": "Construido en tres décadas",
    "lead": "Ejecutivo tecnológico, fundador y asesor de consejos.",
    "glance": "En resumen",
    "role": "Cargo actual",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "Ubicación",
    "locationVal": "Charlotte, North Carolina",
    "education": "Educación",
    "educationVal": "Doctor en Ciencias Técnicas\nPh.D. en Tecnologías de la Información\nMaestrías — Electrónica, Sistemas Satelitales Digitales y Economía",
    "university": "Universidad",
    "universityVal": "Universidad Técnica Naval Estatal de Ucrania",
    "languages": "Idiomas",
    "languagesVal": "Inglés, ruso, ucraniano",
    "contactLabel": "Contacto",
    "principlesEyebrow": "Principios operativos",
    "principlesTitle": "Cómo lidero",
    "p1title": "Comprender el sistema",
    "p1text": "Antes de cambiar una organización, comprenda sus incentivos, arquitectura, restricciones y fuentes de confianza.",
    "p2title": "Hacer explícita la responsabilidad",
    "p2text": "La propiedad clara y los resultados medibles convierten la estrategia de material de presentación en realidad operativa.",
    "p3title": "Dejar instituciones más fuertes",
    "p3text": "El liderazgo debe multiplicar la capacidad desarrollando personas, mejorando decisiones y construyendo sistemas que perduren.",
    "archiveEyebrow": "Del archivo",
    "archiveTitle": "Del archivo",
    "archiveLead": "Material auténtico sobre creación de empresas, infraestructura y liderazgo.",
    "photo9netTitle": "9 Net Avenue",
    "photo9netCaption": "Fundador y CEO — empresa de hosting e infraestructura de internet, adquirida por Concentric Networks en 2000.",
    "photoServerTitle": "Infraestructura de datos",
    "photoServerCaption": "Entornos de almacenamiento, redes y servidores en DataPeer y empresas relacionadas.",
    "photoTodayTitle": "Hoy",
    "photoTodayCaption": "Digital Invest Inc., AGRON Inc. y trabajo de asesoría.",
    "secIntroTitle": "Introducción",
    "secTechTitle": "Tecnología e infraestructura",
    "secBusinessTitle": "Negocios",
    "secCurrentTitle": "Trabajo actual",
    "secBackgroundTitle": "Formación",
    "recordLink": "El registro →",
    "secBackgroundP1": "Doctor en Ciencias Técnicas y Ph.D. en Tecnologías de la Información. Autor de trabajos técnicos; patente HDTV satelital adquirida por Sony.",
    "bioP1": "Michael Kofman es ejecutivo tecnológico, fundador y asesor de consejos. Es CEO de Digital Invest Inc. y fundador de AGRON Inc., con experiencia previa en ingeniería satelital, infraestructura de internet, empresas tecnológicas públicas y ciencias de la vida en EE. UU. y Europa.",
    "bioP2": "As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. In 2026 he founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network. He also created Digital Invest, dedicated to the bio-mathematical sphere and transforming medicine through science, DNA technologies, AI, and ML.",
    "secBioTitle": "Medicina de precisión y biotecnología",
    "secBioP1": "Antes de Digital Invest, desempeñó un papel decisivo en el éxito de Biotechnology Group Inc. (2008–2014), empresa dedicada a pruebas y análisis de ADN, automatización de perfiles genéticos e investigación genética humana integral. El Sr. Kofman cree firmemente en el potencial de combinar las ciencias de la vida con los últimos avances tecnológicos.",
    "secBioP2": "Bajo su liderazgo se iniciaron proyectos exitosos de pruebas genéticas en Ucrania, Rusia y los países bálticos. Esta experiencia única se enriquece continuamente con tecnologías modernas y nuevo equipamiento. En colaboración con Harvard Medical School y Stanford Biomath, el Sr. Kofman desempeñó un papel crucial en el desarrollo de informes genéticos comprensibles para médicos y pacientes. Este enfoque innovador ha sido ampliamente adoptado por laboratorios líderes en Estados Unidos y en el extranjero.",
    "secTechP1": "Formación en ingeniería de sistemas transceptores satelitales en Nikolaev Shipbuilding Plant y comunicaciones digitales en Astra Corp.",
    "secTechP2": "En 2006, el Sr. Kofman fundó XIBI Group Inc. — empresa tecnológica en cuya junta directiva sirvió. La compañía estadounidense se especializa en almacenamiento de datos y servicios de gestión de big data para grandes organizaciones comerciales y gubernamentales.",
    "secTechP3": "De 2000 a 2004, el Sr. Kofman dirigió DataPeer Inc. — empresa de gestión y almacenamiento de datos que ofrecía una amplia gama de servicios de almacenamiento de información para pequeñas y medianas empresas. En DataPeer desarrolló soluciones tecnológicas únicas que facilitaron un seguimiento más rápido de la información y un acceso más sencillo a los datos para usuarios finales e instituciones gubernamentales en todo el mundo.",
    "secTechP4": "En 1996, el Sr. Kofman fundó 9 Net Avenue Inc., que rápidamente se convirtió en una de las mayores empresas de hosting del mundo. En 2000, 9 Net Avenue fue adquirida por Concentric Networks (NASDAQ: CNTX) y posteriormente por XO Communications (NASDAQ: XOXO), alcanzando un valor de mercado máximo de 2000",
    "secPost9NetP1": "Tras la adquisición de 9 Net Avenue, el Sr. Kofman adquirió una amplia experiencia trabajando en empresas públicas, participando en juntas directivas y tomando decisiones estratégicas al más alto nivel ejecutivo.",
    "secEarlyTitle": "Primeros años y ingeniería",
    "secEarlyP1": "De 1994 a 1996, el Sr. Kofman fue CEO y Director de Tecnología de la Información en Elitan United Inc. — empresa de TI de Massachusetts que ofrecía estrategias integrales y servicios tecnológicos a organizaciones globales líderes. Desempeñó un papel fundamental en el desarrollo y gestión de infraestructura escalable, llevando el crecimiento de la empresa de solo nueve a más de 4.000 empleados en todo el mundo.",
    "secEarlyP2": "De 1989 a 1994, fue fundador y CEO de Astra Corp, uno de los mayores fabricantes europeos de sistemas satelitales de transcepción digital, con reconocimiento internacional en el campo de dispositivos satelitales. Sus responsabilidades abarcaban investigación, desarrollo de sistemas operativos, aplicaciones de software de red y estrategia técnica general.",
    "secEarlyP3": "De 1984 a 1989, el Sr. Kofman trabajó en el astillero de Nikolaev, Ucrania, donde participó activamente en el desarrollo y creación de sistemas satelitales de transcepción para transmitir información clasificada a buques militares y de regreso. Fue reconocido como ingeniero electrónico del más alto nivel, recibiendo la 6.ª categoría — la máxima distinción en el astillero, donde trabajaban 93 mil personas.",
    "secResearchTitle": "Investigación y patentes",
    "secResearchP1": "Michael Kofman es autor de trabajos técnicos sobre sistemas satelitales y ópticos de transmisión de datos. También obtuvo una patente en el campo de sistemas de televisión de alta definición (HDTV) por satélite digital, posteriormente adquirida por Sony.",
    "secAgronTitle": "Robotics, UAV & Maritime Intelligence",
    "secAgronP1": "In 2026, Mr. Kofman founded AGRON Inc. to build the AGRON Ecosystem — a corporate operating architecture for aerial and ground robotics, governed mission execution, and network infrastructure connecting teams, assets, and operational data. The ecosystem delivers consulting, assessment, capability development, and training for UAV and Counter-UAS organizations, alongside maritime intelligence and security services at agron1.com.",
    "secBusinessP1": "Fundó y dirigió múltiples empresas tecnológicas, incluidas 9 Net Avenue Inc., DataPeer Inc., XIBI Group Inc. y Elitan United Inc. La cronología completa está en The Record.",
    "secCurrentP1": "CEO de Digital Invest Inc., enfocado en medicina biomatemática e inteligencia genómica. Fundador de AGRON Inc., en operaciones autónomas aéreo-terrestres y sistemas geoespaciales."
  },
  "ventures": {
    "eyebrow": "Portafolio de empresas",
    "title": "Empresas fundadas y lideradas",
    "lead": "Desde medicina de precisión y robótica hasta infraestructura global de datos — fundadas, escaladas y dirigidas en EE. UU. y Europa.",
    "ecosystemEyebrow": "Venture Ecosystem",
    "ecosystemTitle": "Companies Across Technology Frontiers",
    "ecosystemLead": "A portfolio shaped by recurring themes: trusted data, intelligent infrastructure, human health, and systems built for scale.",
    "statusActive": "Activo",
    "statusExited": "Salida",
    "statusLegacy": "Legado",
    "v1lesson": "Lección: la infraestructura gana cuando la fiabilidad, la economía y la confianza del cliente mejoran juntas.",
    "v2lesson": "Lección: la medicina de precisión exige la misma disciplina en ciencia, software, privacidad y utilidad clínica.",
    "v3lesson": "Lección: la autonomía crea valor solo cuando la detección, las comunicaciones y la supervisión humana forman un sistema resiliente.",
    "v5lesson": "Lección: la escala en infraestructura se gana con excelencia operativa mucho antes de la salida.",
    "currentEyebrow": "Actual",
    "historyEyebrow": "Historia seleccionada",
    "v2highlight": "Harvard Medical School y Stanford Biomath — colaboración en informes genéticos",
    "activeSitesEyebrow": "Proyectos activos",
    "activeSitesTitle": "Sitios activos",
    "activeSitesLead": "Sitios web activos de empresas actuales e iniciativas de portfolio.",
    "activeSitesMeta": "10 sitios activos · haga clic en cualquier tarjeta para visitar",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — an Aerial-Ground Robotics Operations Network spanning UAV and Counter-UAS consulting, technology assessment, capability development, training infrastructure, product validation, geospatial systems (ISDRI), and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "v0role": "Founder",
    "v0year": "2026 — Present",
    "v2role": "CEO y CTO",
    "v2year": "2008 — 2014",
    "v3year": "2006 — 2011",
    "v4year": "2000 — 2004",
    "v5highlight": "Adquirida · Valor máximo de 2000",
    "v5p1": "Construyó una de las mayores empresas de hosting del mundo. En 2000, adquirida por Concentric Networks (NASDAQ: CNTX) y luego por XO Communications (NASDAQ: XOXO), alcanzando un valor de mercado máximo de 2000",
    "v5year": "1996 — 2000",
    "v6year": "1994 — 1996",
    "v7year": "1989 — 1994",
    "v8year": "1984 — 1989",
    "v1highlight": "Top 10 empresa de medicina de precisión en EE. UU. — 2023",
    "v1p1": "Medicina biomatemática, datos genómicos e inteligencia clínica — IA, ML y tecnologías de ADN aplicadas a flujos clínicos y de investigación.",
    "v1role": "Fundador y CEO · Miembro del consejo",
    "v1year": "2021 — Actual",
    "v2p1": "Pruebas y análisis de ADN, automatización de perfiles genéticos e investigación genética humana integral. Inició proyectos de pruebas genéticas en Ucrania, Rusia y los países bálticos.",
    "v2p2": "Colaboró con Harvard Medical School y Stanford Biomath en informes genéticos adoptados por laboratorios líderes en todo el mundo.",
    "v3highlight": "Soluciones de datos empresariales y gubernamentales",
    "v3p1": "Almacenamiento de datos y servicios de gestión de big data para grandes organizaciones comerciales y gubernamentales. Estableció la empresa como proveedor de confianza de soluciones de datos empresariales.",
    "v3role": "Fundador y CEO · Consejo de administración",
    "v4highlight": "Plataforma global de gestión de datos",
    "v4p1": "Gestión y almacenamiento de datos para pequeñas y medianas empresas. Desarrolló soluciones para un seguimiento más rápido de la información y un acceso más sencillo a los datos para usuarios finales e instituciones gubernamentales en todo el mundo.",
    "v4role": "Fundador y CEO",
    "v5role": "Fundador y CEO",
    "v6highlight": "Estrategia de TI e infraestructura global",
    "v6p1": "Empresa de TI de Massachusetts que ofrecía estrategias integrales y servicios tecnológicos a organizaciones globales líderes. Lideró el desarrollo de infraestructura escalable y operaciones de TI globales.",
    "v6role": "CEO y Director de Tecnología de la Información",
    "v7highlight": "Líder europeo en sistemas satelitales",
    "v7p1": "Uno de los mayores fabricantes europeos de sistemas satelitales de transcepción digital. Lideró investigación, desarrollo de sistemas operativos, aplicaciones de software de red y estrategia técnica general.",
    "v7role": "Fundador y CEO",
    "v8highlight": "Ingeniería de sistemas satelitales militares",
    "v8p1": "Desarrollo y creación de sistemas satelitales de transcepción para transmitir información clasificada a buques militares. Reconocido como ingeniero electrónico del más alto nivel en un astillero de 93.000 empleados.",
    "v8role": "Ingeniero electrónico · Categoría máxima (6.ª)",
    "v1p2": "Iniciativas de cartera: <a href=\"https://biomathlife.com\" target=\"_blank\" rel=\"noopener\">BioMath Life</a>, <a href=\"https://www.biomathcore.com\" target=\"_blank\" rel=\"noopener\">BioMath Core</a>, <a href=\"https://www.type1and2.com\" target=\"_blank\" rel=\"noopener\">Type 1 &amp; 2</a> y <a href=\"https://www.luna29.com\" target=\"_blank\" rel=\"noopener\">Luna29</a> — casos de estudio detallados próximamente.",
    "v1brole": "CEO",
    "v1bp1": "Período de transición entre biotecnología y nuevo desarrollo tecnológico — experiencia operativa y de I+D antes de Digital Invest Inc.",
    "v1byear": "2014 — 2020"
  },
  "career": {
    "eyebrow": "Registro profesional",
    "title": "El registro",
    "lead": "Tecnología, empresas y experiencia operativa a través de periodos sucesivos de cambio tecnológico.",
    "timelineEyebrow": "Línea de tiempo",
    "timelineTitle": "Hitos clave",
    "strengthsEyebrow": "Fortalezas",
    "strengthsTitle": "Áreas de experiencia",
    "filterAll": "All",
    "filterHealthcare": "Healthcare",
    "filterInfrastructure": "Infrastructure",
    "filterDefense": "Defense",
    "filterTelecom": "Telecommunications",
    "periodCurrent": "Sistemas autónomos",
    "periodCurrentLead": "IA, robótica, operaciones autónomas, sistemas geoespaciales e infraestructura actual relacionada.",
    "period1title": "Ingeniería y comunicaciones",
    "period1lead": "Ingeniería temprana, sistemas satelitales, comunicaciones y trabajo tecnológico relacionado.",
    "period2title": "Internet e infraestructura",
    "period2lead": "Infraestructura de internet, telecomunicaciones, centros de datos, almacenamiento y empresas relacionadas.",
    "period3title": "Empresas y mercados públicos",
    "period3lead": "Creación de empresas, transacciones, participación en compañías públicas y roles ejecutivos.",
    "period4title": "Ciencias de la vida y datos humanos",
    "period4lead": "Biotecnología, tecnología sanitaria, datos y medicina de precisión.",
    "period5title": "Programas gubernamentales y de defensa",
    "period5lead": "Estrategia y entrega tecnológica para programas gubernamentales, de defensa y empresas estatales.",
    "t1desc": "Fundó Digital Invest Inc. en 2021. Dirige medicina biomatemática, inteligencia genómica y plataformas de datos clínicos. Healthcare Tech Outlook (2023).",
    "t0desc": "Founded AGRON Inc. to build the AGRON Ecosystem — consulting, assessment, capability development, training infrastructure, and product support for UAV and Counter-UAS programmes, plus AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure. Connects aerial and ground robotics, governed mission execution, and network infrastructure linking teams, assets, and operational data.",
    "t0role": "Founder",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — Present",
    "t10title": "Astillero de Nikolaev",
    "t10year": "1984 — 1989",
    "t1title": "Digital Invest Inc.",
    "t2year": "2001 — 2019",
    "t3role": "CEO y CTO",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4year": "2000 — 2012",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "Construyó una de las mayores empresas de hosting del mundo. En 2000, adquirida por Concentric Networks (NASDAQ: CNTX) y luego por XO Communications (NASDAQ: XOXO), alcanzando un valor de mercado máximo de 2000",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994",
    "t10desc": "Desarrolló y creó sistemas satelitales de transcepción para transmitir información clasificada a buques militares. Reconocido como ingeniero electrónico del más alto nivel en un astillero de 93.000 empleados — el inicio de una distinguida carrera en tecnología e innovación.",
    "t10role": "Ingeniero electrónico — 6.ª categoría (máxima)",
    "t1role": "Fundador y CEO",
    "t1year": "2021 — Actual",
    "t2desc": "Dirigió la estrategia y ejecución tecnológica de programas clasificados y de alta sensibilidad con agencias gubernamentales de EE. UU., sistemas de defensa aliados y empresas estatales. Encabezó proyectos técnicos complejos para empresas de propiedad estatal en múltiples sectores. Tras el 11 de septiembre de 2001, lideró iniciativas gubernamentales a gran escala centradas en big data, comunicaciones seguras, analítica predictiva e integración de datos a nivel nacional — incluido el diseño, construcción y operación de centros de datos de alto rendimiento en Estados Unidos y Europa. Interactuó con oficiales de programas militares, proveedores tecnológicos y entidades reguladoras.",
    "t2role": "Asesor tecnológico principal / Arquitecto de programas",
    "t2title": "GovTech, defensa y programas estatales",
    "t3desc": "Lideró pruebas y análisis de ADN, automatización de perfiles genéticos e investigación genética humana integral. Inició proyectos de pruebas genéticas en Ucrania, Rusia y los países bálticos. Colaboró con Harvard Medical School y Stanford Biomath para desarrollar informes genéticos comprensibles adoptados por laboratorios líderes en todo el mundo.",
    "t4desc": "Dirigió despliegues de infraestructura nacional en Canadá, Italia, Suiza, Ucrania y las repúblicas bálticas. Supervisó a más de 1.000 ingenieros y personal de despliegue en operaciones de telecomunicaciones, incluidos sistemas de conmutación, expansión de banda ancha y conectividad transfronteriza. Implementó sistemas centrales de redundancia de red, optimización de disponibilidad y enrutamiento inteligente.",
    "t4role": "VP de Tecnología / CTO regional — Europa del Este y CEI",
    "t4title": "Proyectos de telecomunicaciones",
    "t5desc": "Fundó una empresa tecnológica especializada en almacenamiento de datos y gestión de big data para grandes organizaciones comerciales y gubernamentales. Estableció la empresa como proveedor de confianza de soluciones de datos empresariales.",
    "t5role": "Fundador y CEO · Consejo de administración",
    "t6desc": "Estableció una empresa de gestión y almacenamiento de datos para pymes. Desarrolló soluciones tecnológicas únicas para un seguimiento más rápido de la información y un acceso más sencillo a los datos para usuarios finales e instituciones gubernamentales en todo el mundo.",
    "t6role": "Fundador y CEO",
    "t7role": "Fundador y CEO",
    "t8desc": "Lideró estrategias integrales de TI y servicios tecnológicos para organizaciones globales líderes desde Massachusetts en un período de rápida expansión, construyendo infraestructura escalable y operaciones de TI globales.",
    "t8role": "CEO y Director de Tecnología de la Información",
    "t9desc": "Fundó uno de los mayores fabricantes europeos de sistemas satelitales de transcepción digital. Lideró investigación, desarrollo de sistemas operativos, aplicaciones de software de red y estrategia técnica general, obteniendo reconocimiento internacional.",
    "t9role": "Fundador y CEO",
    "t1bdesc": "Período de transición entre biotecnología y nuevo desarrollo tecnológico — experiencia operativa y de I+D antes de Digital Invest Inc.",
    "t1brole": "CEO",
    "t1byear": "2014 — 2020"
  },
  "recognition": {
    "eyebrow": "Registro documentado",
    "title": "Premios y reconocimientos",
    "lead": "Distinciones en emprendimiento, medicina de precisión, ingeniería y liderazgo ejecutivo.",
    "industryEyebrow": "Honores y referencias",
    "industryTitle": "Entradas seleccionadas",
    "ipEyebrow": "Propiedad intelectual",
    "ipTitle": "Patentes y publicaciones",
    "eduEyebrow": "Educación",
    "eduTitle": "Credenciales académicas",
    "pressEyebrow": "Prensa",
    "pressTitle": "Destacado en",
    "moreLink": "Ver patentes, publicaciones y notas de prensa en Insights →",
    "a1desc": "Entrepreneur Magazine · 2001",
    "a3title": "Who's Who in America",
    "a4title": "Who's Who in the World",
    "a5title": "Who's Who in Science & Engineering",
    "ip1year": "Patente",
    "ip2year": "Publicaciones",
    "press1role": "Reportaje sobre Digital Invest Inc.",
    "press1title": "Healthcare Tech Outlook",
    "press2title": "Top Precision Medicine Solutions",
    "a1title": "Emprendedor del año",
    "a2title": "Top 10 empresa de medicina de precisión en EE. UU.",
    "a2desc": "Digital Invest Inc. reconocida entre las 10 mejores empresas de medicina de precisión y salud digital de América — 2023.",
    "a3desc": "Incluido, 1999 — 2018 — por logros excepcionales en creación y desarrollo empresarial.",
    "a4desc": "Incluido, 2000 — 2004 — entre líderes globales en ciencia, ingeniería e innovación empresarial.",
    "a5desc": "Incluido, 2000 — 2014 — por contribuciones a la tecnología, sistemas satelitales e infraestructura digital.",
    "a6title": "Ingeniero electrónico — 6.ª categoría",
    "a6desc": "Máximo reconocimiento en el Astillero de Nikolaev (93.000 empleados) por ingeniería de sistemas satelitales de transcepción.",
    "ip1title": "Sistemas HDTV satelitales digitales",
    "ip1role": "Posteriormente adquirida por Sony",
    "ip1desc": "Patente en sistemas HDTV satelitales digitales, adquirida posteriormente por Sony Corporation.",
    "ip2title": "Trabajos técnicos",
    "ip2role": "Sistemas satelitales y ópticos",
    "ip2desc": "Autor de trabajos técnicos sobre sistemas satelitales y ópticos de transmisión de datos. Sus contribuciones abarcan procesamiento de señales, modelado de simulación y plataformas de automatización aplicadas en telecomunicaciones, infraestructura nacional y salud digital.",
    "ip3year": "Investigación",
    "ip3title": "Colaboraciones internacionales",
    "ip3role": "EE. UU. y Europa",
    "ip3desc": "Participó en colaboraciones de investigación internacional e iniciativas de transferencia de conocimiento. Desarrolló sistemas de ingeniería embebidos para adquisición de datos, diagnósticos predictivos y orquestación en la nube en múltiples industrias.",
    "edu1title": "Doctor en Ciencias Técnicas",
    "edu2title": "Doctorado en Tecnologías de la Información",
    "edu3title": "Maestrías",
    "edu3desc": "Electrónica, sistemas satelitales digitales y economía",
    "press1desc": "Healthcare Tech Outlook sobre Digital Invest Inc. y medicina de precisión (2023).",
    "press1link": "Leer reportaje →",
    "press2role": "Reconocimiento del sector",
    "press2desc": "Nombrada entre las principales empresas de soluciones de medicina de precisión, destacando el papel de Digital Invest en el avance de enfoques biomatemáticos en la atención sanitaria moderna.",
    "press2link": "Ver listado →"
  },
  "contact": {
    "eyebrow": "Contacto",
    "title": "Contacto",
    "lead": "Para roles de asesoría, juntas directivas y alianzas estratégicas.",
    "infoTitle": "Contacto directo",
    "email": "Correo electrónico",
    "phone": "Teléfono",
    "location": "Ubicación",
    "locationVal": "Charlotte, North Carolina\nEstados Unidos",
    "linkedin": "LinkedIn",
    "company": "Empresa actual",
    "companyVal": "Digital Invest Inc.\nCEO y miembro del consejo\nAGRON Inc.\nFundador",
    "formTitle": "Enviar mensaje",
    "formLead": "Complete el formulario y le responderé pronto.",
    "firstName": "Nombre",
    "lastName": "Apellido",
    "emailLabel": "Correo electrónico",
    "subject": "Asunto",
    "message": "Mensaje",
    "inquiryType": "Tipo de consulta",
    "inquiryAdvisory": "Asesoría",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "calendlyEyebrow": "Programar una conversación",
    "calendlyTitle": "Elija un horario conveniente",
    "calendlyLead": "Para consultas calificadas de juntas, asesoría, conferencias y alianzas estratégicas.",
    "calendlyPlaceholder": "El calendario de citas aparecerá aquí.",
    "calendlyCta": "Abrir calendario de citas",
    "inquiryBusiness": "Negocios",
    "infoEyebrow": "Información de contacto"
  },
  "consulting": {
    "eyebrow": "Servicios de asesoría",
    "title": "Consultoría",
    "heroEyebrow": "Orientación empresarial estratégica",
    "heroTitle": "Asesoría estratégica",
    "heroLead": "Treinta y cinco años fundando y asesorando empresas en EE. UU. y Europa — infraestructura de datos, govtech, medicina de precisión y robótica.",
    "cta": "Contactar a Michael Kofman",
    "introLead": "CEO de Digital Invest Inc. y miembro del consejo. Enfoque: tecnología emergente, seguridad, investigación y asignación de capital.",
    "specialtiesEyebrow": "Áreas de enfoque",
    "specialtiesTitle": "En qué se especializa Michael Kofman",
    "area1title": "Servicio en juntas",
    "area1desc": "Trabajo independiente en juntas directivas y nivel consejo en estrategia tecnológica, gobierno corporativo y supervisión en etapas de crecimiento.",
    "area2title": "Asesoría para CEO y fundadores",
    "area2desc": "Estrategia corporativa y tecnológica, desarrollo organizacional, transacciones y experiencia aplicable en mercados de capitales.",
    "area3title": "Due diligence tecnológico",
    "area3desc": "Evaluación de infraestructura, plataformas de datos, arquitectura de seguridad y tecnología aplicada basada en experiencia operativa documentada.",
    "redirectLead": "El trabajo de asesoría estratégica está documentado en la página Advisory. Para consultas profesionales, use Contact.",
    "redirectLink": "Asesoría →"
  },
  "insights": {
    "eyebrow": "Perspectivas",
    "title": "Perspectivas",
    "heroTitle": "Perspectivas ejecutivas",
    "selectedEyebrow": "Destacados seleccionados",
    "selectedTitle": "Reconocimiento destacado",
    "allPressTitle": "Todas las apariciones en prensa",
    "quotesEyebrow": "En los medios",
    "quotesTitle": "Reconocimiento del sector y citas",
    "articlesEyebrow": "Perspectivas",
    "articlesTitle": "Perspectivas ejecutivas",
    "briefsEyebrow": "Informes ejecutivos",
    "briefsTitle": "Ideas para líderes",
    "briefsLead": "Perspectivas breves y prácticas sobre gobernanza, tecnología, salud y creación de empresas.",
    "brief1title": "Lo que cambia un IPO",
    "brief1desc": "Las disciplinas operativas y de gobernanza que exige la preparación para mercados públicos.",
    "brief1tag": "Mercados de capitales",
    "brief2title": "De datos genéticos a decisiones clínicas",
    "brief2desc": "Cómo construir inteligencia sanitaria útil sin adelantarse a la evidencia o la confianza.",
    "brief2tag": "Medicina de precisión",
    "brief3title": "Estrategia de IA más allá del piloto",
    "brief3desc": "Un marco para convertir experimentos en capacidad empresarial gobernada.",
    "brief3tag": "Inteligencia artificial",
    "readingEyebrow": "Lista de lectura",
    "readingTitle": "Libros que moldean el pensamiento estratégico",
    "r1title": "The Innovator's Dilemma",
    "r1author": "Clayton M. Christensen",
    "r2title": "Thinking, Fast and Slow",
    "r2author": "Daniel Kahneman",
    "r3title": "The Beginning of Infinity",
    "r3author": "David Deutsch",
    "r4title": "Good Strategy/Bad Strategy",
    "r4author": "Richard Rumelt",
    "r5title": "The Structure of Scientific Revolutions",
    "r5author": "Thomas S. Kuhn",
    "newsletterEyebrow": "Notas ocasionales",
    "newsletterTitle": "Perspectiva ejecutiva, sin ruido",
    "newsletterLead": "Ensayos periódicos y breves observaciones sobre tecnología, gobernanza y creación de empresas duraderas.",
    "newsletterCta": "Suscribirse a actualizaciones",
    "lead": "Escritos sustantivos e informes ejecutivos.",
    "relatedLead": "Reconocimientos, cobertura de prensa y patentes se documentan por separado.",
    "topicsLead": "Los temas se basan en experiencia operativa documentada en tecnología, salud e infraestructura."
  },
  "cta": {
    "eyebrow": "Trabajemos juntos",
    "title": "Solicitar asesoría o una conferencia",
    "lead": "Para funciones de asesoría, puestos en juntas directivas, conferencias y alianzas estratégicas.",
    "button": "Póngase en contacto"
  },
  "speaking": {
    "eyebrow": "Conferencias",
    "title": "Invite a Michael Kofman a su evento",
    "lead": "Disponible para conferencias sobre liderazgo ejecutivo, estrategia tecnológica, salud digital, infraestructura de datos y gobierno corporativo.",
    "topicsEyebrow": "Temas de conferencia",
    "topicsTitle": "Áreas de experiencia",
    "topicsLead": "Los temas se basan en décadas de experiencia fundando y dirigiendo empresas en Estados Unidos y Europa.",
    "processEyebrow": "Cómo invitar",
    "processTitle": "Proceso de contratación",
    "process1title": "Envíe una solicitud",
    "process1desc": "Use el formulario de contacto o escriba a mkofman@mkofman.com con los detalles del evento, la audiencia y los temas preferidos.",
    "process2title": "Confirme el alcance",
    "process2desc": "Defina el formato (ponencia principal, panel, sesión de junta o mesa redonda ejecutiva) y la logística.",
    "process3title": "Genere impacto",
    "process3desc": "Las presentaciones se basan en resultados reales de iniciativas en almacenamiento de datos, govtech y medicina de precisión.",
    "cta": "Solicitar una conferencia",
    "catalogEyebrow": "Temas de conferencias",
    "catalogTitle": "Conversaciones ejecutivas para el cambio trascendental",
    "catalogLead": "Keynotes, sesiones de consejo y briefings de liderazgo adaptados a la audiencia, sector y contexto de decisión.",
    "t1title": "Gobernar la IA antes de que gobierne la empresa",
    "t1audience": "Consejos, comités de auditoría y riesgo",
    "t1format": "Briefing de consejo o keynote",
    "t2title": "De tendencia tecnológica a estrategia empresarial",
    "t2audience": "CEOs, equipos ejecutivos, inversores",
    "t2format": "Keynote o taller ejecutivo",
    "t3title": "Construir empresas a través de ciclos de mercado",
    "t3audience": "Fundadores, líderes de crecimiento, private equity",
    "t3format": "Charla íntima o keynote",
    "t4title": "Medicina de precisión: promesa, prueba y responsabilidad",
    "t4audience": "Líderes sanitarios, clínicos, innovadores",
    "t4format": "Keynote sectorial o panel",
    "t5title": "El papel del consejo en riesgo cibernético y tecnológico",
    "t5audience": "Directores, consejo general, líderes de riesgo",
    "t5format": "Sesión de formación de consejo",
    "t6title": "Ingeniería de confianza en infraestructura digital",
    "t6audience": "Organizaciones de tecnología e infraestructura",
    "t6format": "Keynote técnico-ejecutivo",
    "t7title": "Liderar a través de fronteras y disciplinas",
    "t7audience": "Equipos de liderazgo global y universidades",
    "t7format": "Keynote o conversación moderada",
    "t8title": "De fundador a constructor de instituciones",
    "t8audience": "Emprendedores y ejecutivos de próxima generación",
    "t8format": "Taller o charla íntima"
  },
  "caseStudies": {
    "eyebrow": "Casos de estudio",
    "title": "Construyendo empresas que escalan",
    "lead": "Resultados seleccionados de la fundación y dirección de empresas en infraestructura de datos y salud digital.",
    "cs1eyebrow": "Infraestructura de datos · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "Desafío",
    "cs1challengeText": "Construir y escalar una empresa de almacenamiento de datos en un mercado tecnológico en rápida consolidación.",
    "cs1action": "Enfoque",
    "cs1actionText": "Fundé 9 Net Avenue Inc. en 1996. La empresa se convirtió rápidamente en una de las mayores compañías de almacenamiento de datos del mundo.",
    "cs1result": "Resultado",
    "cs1resultText": "Adquirida por Concentric Networks (NASDAQ: CNTX) en 2000; posteriormente parte de XO Communications (NASDAQ: XOXO). Tras la transacción, continuó el trabajo con empresas públicas y roles a nivel de consejo.",
    "cs2eyebrow": "Salud digital · 2021 — Presente",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "Desafío",
    "cs2challengeText": "Transformar enfoques médicos obsoletos mediante ciencia, tecnologías de ADN, IA y ML a través de una nueva plataforma bio-matemática.",
    "cs2action": "Enfoque",
    "cs2actionText": "Fundé Digital Invest Inc. en 2021. Dirijo medicina biomatemática, inteligencia genómica y plataformas de datos clínicos.",
    "cs2result": "Resultado",
    "cs2resultText": "Logramos un crecimiento financiero sostenido y posicionamos a la empresa entre las 10 principales compañías de medicina de precisión de EE. UU. (2023). Digital Invest integra proyectos innovadores como Human Digital Model, BioMath Life y Aero-Ground Robotics Operations Network.",
    "cs3eyebrow": "Robótica y UAV · 2026 — Presente",
    "cs3title": "AGRON Inc.",
    "cs3challenge": "Desafío",
    "cs3challengeText": "Las organizaciones que desarrollan capacidad UAV y Counter-UAS necesitan evaluación independiente, formación estructurada y arquitectura operativa — no plataformas aisladas ni pilotos ad hoc.",
    "cs3action": "Enfoque",
    "cs3actionText": "Fundó AGRON Inc. en 2026 para liderar el AGRON Ecosystem — consultoría, evaluación y validación, desarrollo de capacidades, infraestructura de formación, apoyo al desarrollo de productos, sistemas geoespaciales a través de ISDRI y AGRON Maritime Intelligence + Security para yates, marinas e infraestructura marítima privada.",
    "cs3result": "Resultado",
    "cs3resultText": "Un ecosistema conectado de servicios profesionales que abarca consultoría, desarrollo de capacidades, infraestructura de formación, sistemas geoespaciales e inteligencia marítima a través de AGRON, ISDRI y empresas relacionadas.",
    "caseStudiesLead": "Fundación, escalamiento y liderazgo de empresas desde etapas tempranas hasta adquisición."
  },
  "mediaKit": {
    "eyebrow": "Prensa y eventos",
    "title": "Kit de prensa",
    "lead": "Biografías oficiales, material visual y datos de contacto para prensa, conferencias y consultas de juntas directivas.",
    "bioEyebrow": "Biografías",
    "bioTitle": "Biografías oficiales",
    "bioShortLabel": "50 palabras",
    "bioShort": "Michael Kofman es CEO de Digital Invest Inc. y miembro de consejos, asesor y fundador de empresas de tecnología y salud digital en EE. UU. y Europa.",
    "bioMediumLabel": "150 palabras",
    "bioMedium": "Michael Kofman es CEO de Digital Invest Inc. y forma parte de su consejo de administración. Visionario tecnológico, es reconocido por su enfoque dinámico para comprender las necesidades cambiantes del mercado actual. Como emprendedor, miembro de consejos y asesor de empresas públicas y privadas, ha fundado con éxito varias compañías en Estados Unidos y Europa. Su experiencia abarca liderazgo ejecutivo, análisis estratégico de tecnologías y mercados emergentes, seguridad y privacidad de la información, investigación, ciencia y desarrollo, administración e inversión.",
    "bioLongLabel": "500 palabras",
    "bioLong": "Michael Kofman es CEO de Digital Invest Inc. y miembro de su consejo. Fundó 9 Net Avenue Inc., adquirida por Concentric Networks en 2000, y dirige Digital Invest en medicina biomatemática e inteligencia genómica. Fundó AGRON Inc. en 2026 para operaciones autónomas aéreo-terrestres y sistemas geoespaciales. Autor de trabajos técnicos sobre sistemas satelitales y ópticos; patente en HDTV satelital digital adquirida por Sony. Formación: Doctor en Ciencias Técnicas, Ph.D. en Tecnologías de la Información.",
    "photosEyebrow": "Fotografía",
    "photosTitle": "Imágenes aprobadas",
    "photosLead": "Retratos en alta resolución disponibles previa solicitud en mkofman@mkofman.com.",
    "contactEyebrow": "Contacto de prensa",
    "contactTitle": "Consultas de medios",
    "contactLead": "Para entrevistas, invitaciones a conferencias y solicitudes de prensa.",
    "downloadEyebrow": "Descarga",
    "downloadTitle": "Kit de medios de una página",
    "downloadLead": "PDF con biografías oficiales, retrato y contacto de prensa — listo para compartir con organizadores y periodistas.",
    "downloadCta": "Descargar PDF",
    "brandEyebrow": "Activos de marca",
    "brandTitle": "Identidad y uso",
    "brandLead": "Activos visuales aprobados para uso editorial, conferencias y socios. Preserve proporciones, espaciado y colores originales.",
    "brandColors": "Paleta de colores oficial",
    "brandLogo": "Logotipo principal",
    "brandDownload": "Descargar activos de marca"
  },
  "articles": {
    "backLink": "← Volver a Insights",
    "article1date": "Perspectiva ejecutiva",
    "article1title": "De la ingeniería a la infraestructura global de datos",
    "article1p1": "Mi carrera comenzó en la planta de construcción naval de Nikolaev, en Ucrania, desarrollando sistemas transceptores satelitales para transmitir información clasificada a buques militares. Fui reconocido como ingeniero electrónico del más alto nivel: la 6.ª categoría en una planta de 93.000 empleados.",
    "article1p2": "Entre 1989 y 1994 fundé y dirigí Astra Corp, uno de los mayores fabricantes europeos de sistemas satelitales transceptores digitales. De 1994 a 1996, como CEO de Elitan United Inc., ayudé a escalar la empresa de nueve a más de 4.000 empleados en todo el mundo.",
    "article1p3": "En 1996 fundé 9 Net Avenue Inc., empresa de hosting e infraestructura de internet. En 2000 fue adquirida por Concentric Networks (NASDAQ: CNTX) y posteriormente formó parte de XO Communications (NASDAQ: XOXO).",
    "article1p4": "De 2001 a 2019 dirigí la estrategia tecnológica para programas gubernamentales, de defensa y de empresas estatales, liderando iniciativas de gran escala en big data, infraestructura segura y centros de datos de alto rendimiento en Estados Unidos y Europa.",
    "article2date": "Salud digital",
    "article2title": "Medicina de precisión y convergencia entre ciencia y tecnología",
    "article2p1": "Creo firmemente en el potencial de combinar las ciencias de la vida con los últimos avances tecnológicos. En Biotechnology Group Inc. (2008-2014), nos enfocamos en pruebas y análisis de ADN, automatización de procesos para crear perfiles genéticos e investigación genética humana integral.",
    "article2p2": "Bajo mi liderazgo, se iniciaron proyectos exitosos de pruebas genéticas en Ucrania, Rusia y los países bálticos. En colaboración con Harvard Medical School y Stanford Biomath, desempeñé un papel clave en el desarrollo de reportes genéticos fáciles de comprender para médicos y pacientes.",
    "article2p3": "Con Digital Invest Inc., fundada en 2021, trabajamos en medicina biomatemática — ciencia, tecnologías de ADN, IA y ML aplicadas a inteligencia clínica. Healthcare Tech Outlook (2023).",
    "article2p4": "Digital Invest integra diversos proyectos innovadores, incluidos Human Digital Model, BioMath Life y Aero-Ground Robotics Operations Network, cada uno impulsando la integración de la ciencia de datos y las ciencias de la vida."
  },
  "privacy": {
    "eyebrow": "Legal",
    "title": "Política de privacidad",
    "lead": "Cómo mkofman.com trata la información cuando visita el sitio o envía un mensaje.",
    "updated": "Actualizado: julio de 2026",
    "s1title": "Información que recopilamos",
    "s1text": "Al enviar un formulario, recibimos los campos que usted proporciona (nombre, email, mensaje). Si la analítica está activa, podemos recopilar datos de uso anonimizados.",
    "s2title": "Cómo usamos la información",
    "s2text": "Los formularios se usan para responder consultas y mejorar el sitio. No vendemos datos personales.",
    "s3title": "Servicios de terceros",
    "s3text": "Los formularios pueden procesarse con Formspree. La analítica puede usar Plausible o Google Analytics si está configurada.",
    "s4title": "Sus derechos",
    "s4text": "Puede solicitar acceso, corrección o eliminación escribiendo a mkofman@mkofman.com.",
    "s5title": "Contacto",
    "s5text": "Preguntas sobre esta política: mkofman@mkofman.com"
  },
  "board": {
    "eyebrow": "Asesoría",
    "title": "Asesoría",
    "body": "Abierto a conversaciones de asesoría estratégica con organizaciones de tecnología, salud e infraestructura — basándome en experiencia operativa directa en creación de empresas, estrategia tecnológica y ejecución en etapas de crecimiento.",
    "contactLink": "Para consultas de asesoría",
    "lead": "Board & Advisory"
  },
  "thesis": {
    "eyebrow": "Tesis de liderazgo",
    "title": "Construir a largo plazo. Decidir en el presente.",
    "lead": "La tecnología cambia rápido; las obligaciones del liderazgo, no. Las empresas duraderas unen ambición con disciplina, evidencia y responsabilidad.",
    "believeEyebrow": "En qué creo",
    "believeTitle": "Siete principios para organizaciones duraderas",
    "b1title": "La estrategia debe producir decisiones",
    "b1text": "Una estrategia no es un catálogo de aspiraciones. Define dónde competir, qué capacidades construir, qué no perseguir y cómo se medirá el éxito.",
    "b2title": "La tecnología es un asunto de gobernanza",
    "b2text": "Los consejos deben entender cómo la tecnología crea valor, concentra riesgo y cambia la responsabilidad. Delegar cada pregunta técnica es en sí una decisión.",
    "b3title": "La evidencia debe superar al entusiasmo",
    "b3text": "La convicción importa, pero mercados, sistemas y ciencia deben probarse. Los líderes crean mecanismos que exponen supuestos antes que clientes o reguladores.",
    "b4title": "La arquitectura moldea la empresa",
    "b4text": "La arquitectura técnica determina velocidad, resiliencia, seguridad y opciones futuras. Los atajos se convierten en restricciones institucionales mucho después de que desaparece su contexto original.",
    "b5title": "La confianza es infraestructura operativa",
    "b5text": "La confianza se construye con compromisos claros, ejecución fiable, prácticas responsables de datos y comunicación directa cuando cambian las condiciones.",
    "b6title": "El capital debe seguir a la capacidad",
    "b6text": "La inversión en crecimiento debe reforzar capacidades diferenciadas y demanda medible, no sustituir el gasto por comprensión del producto-mercado.",
    "b7title": "Los líderes diseñan a sus sucesores",
    "b7text": "Los líderes más sólidos construyen sistemas, talento y calidad de decisión que perduran más allá de su propia participación.",
    "rejectEyebrow": "Lo que rechazo",
    "rejectTitle": "Tres ilusiones costosas",
    "r1title": "Teatro de innovación",
    "r1text": "Anuncios, pilotos y lenguaje de moda no equivalen a capacidad. La innovación debe mejorar un resultado que importa.",
    "r2title": "Crecimiento sin gobernanza",
    "r2text": "La escala magnifica debilidades no resueltas. Controles, cultura y responsabilidad deben madurar antes de que la complejidad haga costosa la corrección.",
    "r3title": "Falsa certeza",
    "r3text": "La confianza ejecutiva no debe borrar la incertidumbre. Las decisiones sólidas hacen visibles los supuestos y preservan opciones cuando cambian los hechos.",
    "horizonEyebrow": "El horizonte",
    "horizonTitle": "La próxima ventaja es la integración responsable",
    "horizonText": "La oportunidad definitoria no es una sola tecnología. Es la integración disciplinada de IA, sistemas avanzados de datos, biología y automatización en instituciones en las que la gente puede confiar."
  },
  "press": {
    "eyebrow": "Prensa y medios",
    "title": "Cobertura seleccionada",
    "lead": "Un archivo conciso de reconocimiento y reportajes de terceros en tecnología, emprendimiento y medicina de precisión.",
    "archiveEyebrow": "Archivo",
    "y2023type": "Reconocimiento sectorial",
    "y2023title": "Top 10 Precision Medicine Companies",
    "y2023desc": "Healthcare Tech Outlook reconoció a Digital Invest Inc. entre las principales empresas de EE. UU. que avanzan en medicina de precisión y salud digital.",
    "y2023link": "Ver reportaje",
    "y2001type": "Premio ejecutivo",
    "y2001title": "Emprendedor del Año",
    "y2001desc": "Reconocimiento de Entrepreneur Magazine.",
    "y2001link": "Ver archivo",
    "y1999type": "Reconocimiento biográfico",
    "y1999title": "Who's Who in America",
    "y1999desc": "Reconocimiento desde 1999, seguido de inclusiones en Who's Who in the World y Who's Who in Science and Engineering.",
    "clipEyebrow": "Del archivo",
    "clipMeta": "Industry Feature · DataPeer Inc.",
    "clipTitle": "State of the Storage Industry",
    "clipLead": "Entrevista temprana con Michael Kofman como Founder, Chairman y CEO de DataPeer Inc. — sobre fibra óptica, transmisión satelital, SAN y el mercado emergente de almacenamiento.",
    "clipBody": "El artículo destaca el reconocimiento como Emprendedor del Año por Entrepreneur Magazine (2001) y analiza el enfoque de DataPeer en almacenamiento crítico, iSCSI y continuidad del negocio.",
    "clipOpen": "Abrir escaneo completo →",
    "y2000type": "Entrevista",
    "y2000title": "State of the Storage Industry",
    "y2000desc": "Entrevista destacada como Founder, Chairman y CEO de DataPeer Inc. sobre redes de almacenamiento, iSCSI y continuidad del negocio."
  },
  "ip": {
    "eyebrow": "Propiedad intelectual",
    "title": "Ideas aplicadas, documentadas",
    "lead": "Patentes, publicaciones y programas de investigación seleccionados que conectan el rigor de ingeniería con resultados empresariales y sociales prácticos.",
    "patentEyebrow": "Patentes",
    "patentTitle": "Invenciones protegidas",
    "patentIntro": "El trabajo de patentes refleja un enfoque sostenido en sistemas que mejoran la recopilación, movimiento, protección e interpretación de información.",
    "publicationsEyebrow": "Publicaciones",
    "publicationsTitle": "Escritura técnica y ejecutiva",
    "publicationsIntro": "La obra publicada traduce temas técnicos complejos en métodos, marcos y decisiones útiles para profesionales y líderes.",
    "researchEyebrow": "Investigación",
    "researchTitle": "Programas interdisciplinarios",
    "researchIntro": "Las iniciativas de investigación abarcan comunicaciones seguras, analítica predictiva, interpretación genética, modelado digital humano y sistemas autónomos."
  },
  "testimonials": {
    "t1quote": "Michael combina la precisión de un ingeniero con el criterio de un CEO experimentado. Hace las preguntas que mejoran la decisión.",
    "t1name": "Colega del consejo",
    "t1role": "Empresa tecnológica pública",
    "t2quote": "Su capacidad para conectar ciencia, producto, gobernanza y realidad comercial aporta una claridad poco común a iniciativas complejas.",
    "t2name": "Socio estratégico",
    "t2role": "Sector de salud digital",
    "t3quote": "Michael es directo, reflexivo y centrado en valor duradero. Ayuda a los equipos directivos a ver tanto la oportunidad como la obligación.",
    "t3name": "Colaborador ejecutivo",
    "t3role": "Infraestructura global"
  },
  "deck": {
    "title": "Michael Kofman",
    "subtitle": "Ejecutivo tecnológico · Fundador · Asesor de consejos",
    "thesis": "Tecnología, negocios e inversión en infraestructura, ciencias de la vida y sistemas autónomos.",
    "contact": "Discusión confidencial: contacte a Michael Kofman en mkofman.com"
  },
  "briefIpo": {
    "title": "Lo que cambia un IPO",
    "desc": "Los mercados públicos no solo cambian la estructura de capital; cambian el contrato operativo.",
    "p1": "Una oferta pública inicial suele describirse como un evento de financiación. En la práctica, es una transición institucional. Pronósticos, controles, divulgación, gobernanza y comunicación ejecutiva deben ser repetibles antes de la cotización, no improvisados después.",
    "p2": "La preparación comienza con la calidad de las decisiones. La dirección necesita métricas fiables, propiedad clara y un ritmo operativo que explique rendimiento y variaciones. Una empresa que no reconcilia su narrativa interna luchará por comunicar una externa creíble.",
    "p3": "El papel del consejo también cambia. Los directores deben equilibrar crecimiento y supervisión, comprender riesgos tecnológicos y de mercado materiales, y asegurar que los incentivos apoyen valor duradero, no un solo trimestre.",
    "p4": "Las empresas públicas más sólidas preservan velocidad emprendedora mientras añaden disciplina institucional. El objetivo no es burocracia; es ejecución confiable a un nivel superior de responsabilidad.",
    "eyebrow": "Informe ejecutivo"
  },
  "briefGenetic": {
    "title": "De datos genéticos a decisiones clínicas",
    "desc": "El valor de la información genómica depende de la interpretación, la evidencia y la integración responsable en la atención.",
    "p1": "Los datos genéticos son abundantes; el significado clínicamente útil es escaso. Un resultado se vuelve valioso solo cuando se interpreta en contexto, se conecta con evidencia validada y se presenta de forma que apoye una decisión real.",
    "p2": "Esa traducción requiere colaboración entre biología molecular, medicina, estadística, ingeniería de software y comunicación con pacientes. Una debilidad en cualquier capa puede convertir sofisticación técnica en confusión clínica.",
    "p3": "La privacidad y el consentimiento son requisitos arquitectónicos, no notas legales al pie. Los sistemas deben limitar la exposición innecesaria, hacer visible la procedencia de los datos y preservar la agencia del paciente cuando la información se mueve entre laboratorios, plataformas y equipos de atención.",
    "p4": "La medicina de precisión avanzará mediante integración medida: mejor evidencia, modelos transparentes, flujos interoperables y resultados que clínicos y pacientes puedan evaluar. La confianza es parte del producto.",
    "eyebrow": "Informe ejecutivo"
  },
  "briefAi": {
    "title": "Estrategia de IA más allá del piloto",
    "desc": "La IA empresarial crea valor cuando la propiedad, los datos, el flujo de trabajo y la gobernanza maduran juntos.",
    "p1": "Muchas iniciativas de IA comienzan con una demostración convincente y se estancan antes de producción. Lo que falta rara vez es solo el modelo. El valor sostenible requiere un resultado de negocio definido, un responsable, datos fiables y un flujo de trabajo que la gente realmente use.",
    "p2": "Los líderes deben distinguir automatización, predicción y apoyo a decisiones. Cada una exige distintos requisitos de precisión, explicabilidad, revisión humana y riesgo. Una plantilla de gobernanza única no encaja en todos los casos.",
    "p3": "La medición debe incluir más que el rendimiento técnico. Adopción, tiempo de ciclo, tasas de error, impacto en clientes, exposición de seguridad y coste de supervisión determinan si una capacidad de IA es económicamente e institucionalmente sólida.",
    "p4": "El enfoque ganador es un portfolio gestionado: escalar casos probados, detener los débiles pronto y mantener límites explícitos para decisiones de alta consecuencia. La estrategia de IA es, en última instancia, estrategia operativa.",
    "eyebrow": "Informe ejecutivo"
  }
};
