window.__LANG_es = {
  "ui": {
    "toggleTheme": "Cambiar tema claro/oscuro",
    "selectLanguage": "Seleccionar idioma",
    "messageSent": "Mensaje enviado",
    "sendMessage": "Enviar mensaje",
    "toggleNav": "Abrir menú",
    "sending": "Enviando…",
    "formError": "No se pudo enviar. Por favor, escriba directamente por correo electrónico.",
    "present": "Actual"
  },
  "nav": {
    "home": "Inicio",
    "about": "Biografía",
    "ventures": "Empresas",
    "career": "The Record",
    "recognition": "Reconocimientos",
    "contact": "Contacto",
    "consulting": "Consultoría",
    "insights": "Perspectivas",
    "speaking": "Conferencias",
    "caseStudies": "Casos de estudio",
    "mediaKit": "Kit de prensa",
    "groupMain": "Principal",
    "groupServices": "Servicios",
    "groupWork": "Trabajo",
    "briefIpo": "Brief: IPO",
    "briefGenetic": "Brief: Genetic Data",
    "briefAi": "Brief: AI Strategy",
    "articleInfra": "Data Infrastructure",
    "articleHealth": "Precision Medicine",
    "board": "Board Advisory",
    "thesis": "Leadership Thesis",
    "press": "Press",
    "ip": "Intellectual Property"
  },
  "footer": {
    "navigation": "Navegación",
    "ventures": "Empresas",
    "connect": "Contacto",
    "desc": "Ejecutivo tecnológico, fundador y asesor de consejos.",
    "copyright": "© {year} Michael Kofman. Todos los derechos reservados.",
    "writeTitle": "Escríbame",
    "writeEmail": "Su email",
    "writeMessage": "Su mensaje",
    "writeSend": "Enviar",
    "writeSuccess": "Gracias — su mensaje ha sido enviado.",
    "more": "Más",
    "privacy": "Privacidad"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — Ejecutivo tecnológico",
      "description": "Ejecutivo tecnológico, fundador y asesor de consejos — infraestructura, ciencias de la vida y sistemas autónomos."
    },
    "about": {
      "title": "Biografía — Michael Kofman",
      "description": "Biografía de Michael Kofman — CEO de Digital Invest Inc., fundador de AGRON Inc."
    },
    "ventures": {
      "title": "Empresas — Michael Kofman",
      "description": "Empresas fundadas y dirigidas por Michael Kofman."
    },
    "career": {
      "title": "The Record — Michael Kofman",
      "description": "Registro profesional en ingeniería, infraestructura, mercados públicos, ciencias de la vida y sistemas autónomos."
    },
    "recognition": {
      "title": "Reconocimientos — Michael Kofman",
      "description": "Premios, honores y reconocimientos de Michael Kofman — Emprendedor del Año, Who's Who, patentes y distinciones del sector."
    },
    "contact": {
      "title": "Contacto — Michael Kofman",
      "description": "Contacte a Michael Kofman — CEO de Digital Invest Inc. Para conferencias, roles de asesoría y consultas comerciales."
    },
    "consulting": {
      "title": "Consultoría — Michael Kofman",
      "description": "Roles de asesoría, puestos en juntas directivas, conferencias y alianzas estratégicas con Michael Kofman."
    },
    "insights": {
      "title": "Perspectivas — Michael Kofman",
      "description": "Publicaciones, prensa, patentes y reconocimiento del sector de Michael Kofman."
    },
    "speaking": {
      "title": "Conferencias — Michael Kofman",
      "description": "Invite a Michael Kofman a hablar sobre liderazgo ejecutivo, estrategia tecnológica, salud digital y gobierno corporativo."
    },
    "caseStudies": {
      "title": "Casos de estudio — Michael Kofman",
      "description": "Casos de estudio de la trayectoria de Michael Kofman: 9 Net Avenue Inc. y Digital Invest Inc."
    },
    "mediaKit": {
      "title": "Kit de prensa — Michael Kofman",
      "description": "Biografías oficiales, fotografías e información de contacto para prensa y organizadores de eventos."
    },
    "article1": {
      "title": "De la ingeniería a la infraestructura global — Michael Kofman",
      "description": "Michael Kofman sobre su trayectoria desde la ingeniería satelital hasta la fundación de empresas globales de infraestructura de datos."
    },
    "article2": {
      "title": "Medicina de precisión y tecnología — Michael Kofman",
      "description": "Michael Kofman sobre la integración de las ciencias de la vida con IA, ML y tecnologías de ADN en la medicina moderna."
    },
    "privacy": {
      "title": "Política de privacidad — Michael Kofman",
      "description": "Política de privacidad de mkofman.com: formularios de contacto y analítica."
    },
    "board": {
      "title": "Board Advisory — Michael Kofman",
      "description": "Board service and strategic advisory from Michael Kofman for technology, healthcare, infrastructure, and growth-stage organizations."
    },
    "thesis": {
      "title": "Leadership Thesis — Michael Kofman",
      "description": "Michael Kofman's principles for building durable companies, governing technology, and leading through consequential change."
    },
    "press": {
      "title": "Press Archive — Michael Kofman",
      "description": "Selected press coverage, awards, and media references spanning Michael Kofman's career in technology and entrepreneurship."
    },
    "ip": {
      "title": "Intellectual Property — Michael Kofman",
      "description": "Patents, publications, and applied research by Michael Kofman across computing, communications, data, and digital health."
    },
    "briefIpo": {
      "title": "What an IPO Changes — Michael Kofman",
      "description": "An executive brief on the operating discipline, governance, and accountability required before and after an initial public offering."
    },
    "briefGenetic": {
      "title": "From Genetic Data to Clinical Decisions — Michael Kofman",
      "description": "An executive brief on translating genomic information into responsible, useful, and scalable clinical intelligence."
    },
    "briefAi": {
      "title": "AI Strategy Beyond the Pilot — Michael Kofman",
      "description": "An executive brief on moving artificial intelligence from experimentation to governed, measurable enterprise capability."
    },
    "deck": {
      "title": "Executive Overview — Michael Kofman",
      "description": "Private executive overview for qualified introductions."
    }
  },
  "home": {
    "heroEyebrow": "Sitio oficial de Michael Kofman",
    "heroTitle1": "Hecho para perdurar.",
    "heroTitle2": "Liderado con criterio.",
    "heroCta": "Descubra mi historia",
    "heroAlt": "Michael Kofman",
    "quote1text": "Destacado entre las principales empresas de medicina de precisión y salud digital de EE. UU.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "Empresario del Año — reconocido por liderazgo y logros innovadores en plataformas e infraestructura.",
    "quote2author": "Entrepreneur Magazine · 2001",
    "quote3text": "Digital Invest Inc. entre las 10 mejores empresas de EE. UU. en medicina de precisión y salud digital.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "Precisión de ingeniería y estrategia empresarial — desde sistemas satelitales hasta infraestructura de $",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "Conozca a Michael Kofman",
    "aboutTitle": "Empresas hechas para durar",
    "aboutLead1": "CEO de Digital Invest Inc. y fundador de AGRON Inc. Ha fundado y dirigido empresas en Estados Unidos y Europa.",
    "aboutLead2": "Desde 9 Net Avenue (valoración pico de $",
    "aboutLink": "Leer biografía completa",
    "expertiseEyebrow": "Áreas de enfoque",
    "expertiseTitle": "Liderazgo ejecutivo en múltiples industrias",
    "expertiseLead": "Cuatro décadas construyendo, asesorando e invirtiendo en infraestructura, salud y robótica.",
    "exp1title": "CEO y fundador",
    "exp1desc": "Fundó y escaló múltiples empresas desde su inicio hasta la salida a bolsa, logrando un crecimiento financiero constante y presencia global en los sectores de tecnología y salud.",
    "exp1link": "Ver empresas →",
    "exp2title": "Arquitecto tecnológico",
    "exp2desc": "Diseñó comunicaciones seguras, motores de analítica predictiva y plataformas de integración de datos a nivel nacional para los sectores gubernamental, militar y de telecomunicaciones.",
    "exp2link": "Ver carrera →",
    "exp3title": "Salud digital",
    "exp3desc": "Lidera la transformación de la medicina mediante IA, ML y tecnologías de ADN. Colaboró con Harvard Medical School y Stanford Biomath en informes genéticos.",
    "exp3link": "Digital Invest →",
    "exp4title": "Asesor de junta",
    "exp4desc": "Participa en juntas directivas y asesora a empresas públicas y privadas sobre dirección estratégica, gobierno corporativo e iniciativas de crecimiento impulsadas por la tecnología.",
    "exp4link": "Consultoría →",
    "stat1": "Años de liderazgo",
    "stat2": "Empresas fundadas",
    "stat3": "Valor máximo de mercado",
    "stat4": "Empleados escalados",
    "recEyebrow": "Reconocimientos",
    "recTitle": "Reconocimientos seleccionados",
    "recLead": "Honores documentados y referencias del sector en archivos existentes.",
    "award1title": "Empresario del año",
    "award1desc": "Entrepreneur Magazine · 2001",
    "award2title": "Reconocimiento en medicina de precisión",
    "award2desc": "Healthcare Tech Outlook · Digital Invest Inc. · 2023",
    "award3title": "Who's Who",
    "award3desc": "Ediciones América · Mundo · Ciencia e ingeniería",
    "recLink": "Reconocimientos y prensa →",
    "heroSub": "Tecnología, negocios e inversión en infraestructura, ciencias de la vida y sistemas autónomos.",
    "primaryCta": "Solicitar asesoría",
    "secondaryCta": "Ver casos de estudio",
    "featuredEyebrow": "Como aparece en",
    "caseStudiesEyebrow": "Resultados comprobados",
    "caseStudiesTitle": "Casos de estudio",
    "caseStudiesLead": "Fundación, escalamiento y liderazgo de empresas desde su inicio hasta adquisiciones y salidas a bolsa.",
    "caseStudiesLink": "Ver todos los casos de estudio →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "Founded 9 Net Avenue Inc.; acquired by Concentric Networks in 2000.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "Healthcare Tech Outlook feature (2023).",
    "cs3title": "AGRON Inc.",
    "cs3desc": "Founded in 2026 — the AGRON Ecosystem for UAV capability development, geospatial systems, and maritime intelligence.",
    "boardCtaEyebrow": "Board & Advisory",
    "boardCtaTitle": "Experience for the Decisions That Define an Enterprise",
    "boardCtaLead": "Independent perspective for boards and leaders navigating technology, governance, transformation, and growth.",
    "boardCtaBtn": "Explore Board Advisory",
    "testimonialsEyebrow": "Trusted Perspective",
    "testimonialsTitle": "What Colleagues Value",
    "videoEyebrow": "Executive Perspective",
    "videoTitle": "Leadership at the Intersection of Technology and Enterprise",
    "videoLead": "A concise introduction to the principles, experience, and long-term perspective behind Michael Kofman's work.",
    "videoCta": "Read Leadership Thesis →",
    "heroName": "Michael Kofman",
    "heroRole": "Ejecutivo tecnológico · Fundador · Asesor de consejos",
    "introText": "Michael Kofman es ejecutivo tecnológico y fundador de empresas. Su trabajo abarca ingeniería satelital, infraestructura de internet, empresas tecnológicas públicas y ciencias de la vida. Fundó 9 Net Avenue Inc., adquirida por Concentric Networks en 2000. Es CEO de Digital Invest Inc., en medicina biomatemática e inteligencia genómica, y fundador de AGRON Inc., en operaciones autónomas aéreo-terrestres y sistemas geoespaciales. Participa en consejos y asesora en tecnología, salud e infraestructura.",
    "introLink": "Biografía completa →",
    "currentEyebrow": "Trabajo actual",
    "currentTitle": "Dónde está el foco ahora",
    "currentDiTitle": "Digital Invest Inc.",
    "currentDiDesc": "Medicina biomatemática, datos genómicos e inteligencia clínica — aplicación de IA, aprendizaje automático y tecnologías de ADN a resultados de salud responsables.",
    "currentDiLink": "Empresas →",
    "currentAgTitle": "AGRON Inc.",
    "currentAgDesc": "Operaciones autónomas aéreo-terrestres, desarrollo de capacidades UAV, sistemas geoespaciales e infraestructura de inteligencia marítima.",
    "currentAgLink": "agron1.com →",
    "careerEyebrow": "Registro seleccionado",
    "careerTitle": "Continuidad entre periodos tecnológicos",
    "careerLead": "Hitos seleccionados desde la ingeniería hasta el trabajo actual en sistemas autónomos.",
    "career1title": "Ingeniería y comunicaciones",
    "career1desc": "Sistemas transceptores satelitales, comunicaciones digitales y primeros liderazgos de ingeniería.",
    "career2title": "Internet e infraestructura",
    "career2desc": "Infraestructura de internet, centros de datos, almacenamiento y telecomunicaciones a escala.",
    "career3title": "Empresas tecnológicas y mercados públicos",
    "career3desc": "Creación de empresas, adquisiciones y experiencia en compañías cotizadas, incluida 9 Net Avenue Inc.",
    "career4title": "Ciencias de la vida y datos humanos",
    "career4desc": "Biotecnología, datos genéticos, medicina de precisión y plataformas de inteligencia sanitaria.",
    "career5title": "Sistemas autónomos",
    "career5desc": "Robótica aéreo-terrestre, operaciones UAV e infraestructura geoespacial.",
    "careerLink": "The Record →",
    "perspectivesEyebrow": "Perspectivas",
    "perspectivesTitle": "Textos seleccionados",
    "perspectivesLink": "Todas las perspectivas →",
    "footerHomeDesc": "Ejecutivo tecnológico, fundador y asesor de consejos."
  },
  "about": {
    "eyebrow": "Sobre Michael Kofman",
    "title": "Construido en tres décadas",
    "lead": "Ejecutivo tecnológico, fundador y asesor de consejos.",
    "glance": "En resumen",
    "role": "Cargo actual",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "Ubicación",
    "locationVal": "Charlotte, North Carolina",
    "education": "Educación",
    "educationVal": "Doctor of Technical Sciences\nPh.D. in Information Technology\nMaster's in Electronic Engineering",
    "university": "Universidad",
    "universityVal": "Ukrainian State Marine Technical University",
    "languages": "Idiomas",
    "languagesVal": "English, Russian, Ukrainian",
    "contactLabel": "Contacto",
    "principlesEyebrow": "Operating Principles",
    "principlesTitle": "How I Lead",
    "p1title": "Understand the System",
    "p1text": "Before changing an organization, understand its incentives, architecture, constraints, and sources of trust.",
    "p2title": "Make Accountability Explicit",
    "p2text": "Clear ownership and measurable outcomes turn strategy from presentation material into operating reality.",
    "p3title": "Leave Stronger Institutions",
    "p3text": "Leadership should compound capability by developing people, improving decisions, and building systems that endure.",
    "archiveEyebrow": "From the Archive",
    "archiveTitle": "Moments Across the Journey",
    "archiveLead": "Selected photographs from company building, infrastructure, and leadership — from the 9 Net Avenue years to today.",
    "photo9netTitle": "9 Net Avenue",
    "photo9netCaption": "Fundador y CEO — empresa de hosting e infraestructura de internet, adquirida por Concentric Networks en 2000.",
    "photoServerTitle": "Data Infrastructure",
    "photoServerCaption": "Hands-on years in storage, networking, and high-density server environments at DataPeer and related ventures.",
    "photoTodayTitle": "Today",
    "photoTodayCaption": "Board advisory, strategic technology leadership, and building the next generation of digital health and infrastructure companies.",
    "secIntroTitle": "Introduction",
    "secTechTitle": "Tecnología e infraestructura",
    "secBusinessTitle": "Business",
    "secCurrentTitle": "Current Work",
    "secBackgroundTitle": "Background",
    "recordLink": "The Record →",
    "bioP1": "Michael Kofman es ejecutivo tecnológico, fundador y asesor de consejos. Es CEO de Digital Invest Inc. y fundador de AGRON Inc., con experiencia previa en ingeniería satelital, infraestructura de internet, empresas tecnológicas públicas y ciencias de la vida en EE. UU. y Europa.",
    "bioP2": "As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. In 2026 he founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network. He also created Digital Invest, dedicated to the bio-mathematical sphere and transforming medicine through science, DNA technologies, AI, and ML.",
    "secBioTitle": "Medicina de precisión y biotecnología",
    "secBioP1": "Antes de Digital Invest, desempeñó un papel decisivo en el éxito de Biotechnology Group Inc. (2008–2014), empresa dedicada a pruebas y análisis de ADN, automatización de perfiles genéticos e investigación genética humana integral. El Sr. Kofman cree firmemente en el potencial de combinar las ciencias de la vida con los últimos avances tecnológicos.",
    "secBioP2": "Bajo su liderazgo se iniciaron proyectos exitosos de pruebas genéticas en Ucrania, Rusia y los países bálticos. Esta experiencia única se enriquece continuamente con tecnologías modernas y nuevo equipamiento. En colaboración con Harvard Medical School y Stanford Biomath, el Sr. Kofman desempeñó un papel crucial en el desarrollo de informes genéticos comprensibles para médicos y pacientes. Este enfoque innovador ha sido ampliamente adoptado por laboratorios líderes en Estados Unidos y en el extranjero.",
    "secTechP1": "Formación en ingeniería de sistemas transceptores satelitales en Nikolaev Shipbuilding Plant y comunicaciones digitales en Astra Corp.",
    "secTechP2": "En 2006, el Sr. Kofman fundó XIBI Group Inc. — empresa tecnológica en cuya junta directiva sirvió. La compañía estadounidense se especializa en almacenamiento de datos y servicios de gestión de big data para grandes organizaciones comerciales y gubernamentales.",
    "secTechP3": "De 2000 a 2004, el Sr. Kofman dirigió DataPeer Inc. — empresa de gestión y almacenamiento de datos que ofrecía una amplia gama de servicios de almacenamiento de información para pequeñas y medianas empresas. En DataPeer desarrolló soluciones tecnológicas únicas que facilitaron un seguimiento más rápido de la información y un acceso más sencillo a los datos para usuarios finales e instituciones gubernamentales en todo el mundo.",
    "secTechP4": "En 1996, el Sr. Kofman fundó 9 Net Avenue Inc., que rápidamente se convirtió en una de las mayores empresas de hosting del mundo. En 2000, 9 Net Avenue fue adquirida por Concentric Networks (NASDAQ: CNTX) y posteriormente por XO Communications (NASDAQ: XOXO), alcanzando un valor de mercado máximo de 2000",
    "secPost9NetP1": "Tras la adquisición de 9 Net Avenue, el Sr. Kofman adquirió una amplia experiencia trabajando en empresas públicas, participando en juntas directivas y tomando decisiones estratégicas al más alto nivel ejecutivo.",
    "secEarlyTitle": "Primeros años y ingeniería",
    "secEarlyP1": "De 1994 a 1996, el Sr. Kofman fue CEO y Director de Tecnología de la Información en Elitan United Inc. — empresa de TI de Massachusetts que ofrecía estrategias integrales y servicios tecnológicos a organizaciones globales líderes. Desempeñó un papel fundamental en el desarrollo y gestión de infraestructura escalable, llevando el crecimiento de la empresa de solo nueve a más de 4.000 empleados en todo el mundo.",
    "secEarlyP2": "De 1989 a 1994, fue fundador y CEO de Astra Corp, uno de los mayores fabricantes europeos de sistemas satelitales de transcepción digital, con reconocimiento internacional en el campo de dispositivos satelitales. Sus responsabilidades abarcaban investigación, desarrollo de sistemas operativos, aplicaciones de software de red y estrategia técnica general.",
    "secEarlyP3": "De 1984 a 1989, el Sr. Kofman trabajó en el astillero de Nikolaev, Ucrania, donde participó activamente en el desarrollo y creación de sistemas satelitales de transcepción para transmitir información clasificada a buques militares y de regreso. Fue reconocido como ingeniero electrónico del más alto nivel, recibiendo la 6.ª categoría — la máxima distinción en el astillero, donde trabajaban 93 mil personas.",
    "secResearchTitle": "Investigación y patentes",
    "secResearchP1": "Michael Kofman es autor de trabajos técnicos sobre sistemas satelitales y ópticos de transmisión de datos. También obtuvo una patente en el campo de sistemas de televisión de alta definición (HDTV) por satélite digital, posteriormente adquirida por Sony.",
    "secAgronTitle": "Robotics, UAV & Maritime Intelligence",
    "secAgronP1": "In 2026, Mr. Kofman founded AGRON Inc. to build the AGRON Ecosystem — a corporate operating architecture for aerial and ground robotics, governed mission execution, and network infrastructure connecting teams, assets, and operational data. The ecosystem delivers consulting, assessment, capability development, and training for UAV and Counter-UAS organizations, alongside maritime intelligence and security services at agron1.com.",
    "secBusinessP1": "Fundó y dirigió múltiples empresas tecnológicas, incluidas 9 Net Avenue Inc., DataPeer Inc., XIBI Group Inc. y Elitan United Inc. La cronología completa está en The Record.",
    "secCurrentP1": "CEO de Digital Invest Inc., enfocado en medicina biomatemática e inteligencia genómica. Fundador de AGRON Inc., en operaciones autónomas aéreo-terrestres y sistemas geoespaciales.",
    "secBackgroundP1": "Doctor en Ciencias Técnicas y Ph.D. en Tecnologías de la Información. Autor de trabajos técnicos; patente en HDTV satelital digital adquirida por Sony."
  },
  "ventures": {
    "eyebrow": "Portafolio de empresas",
    "title": "Empresas fundadas y lideradas",
    "lead": "Desde medicina de precisión y robótica hasta infraestructura global de datos — fundadas, escaladas y dirigidas en EE. UU. y Europa.",
    "ecosystemEyebrow": "Venture Ecosystem",
    "ecosystemTitle": "Companies Across Technology Frontiers",
    "ecosystemLead": "A portfolio shaped by recurring themes: trusted data, intelligent infrastructure, human health, and systems built for scale.",
    "statusActive": "Active",
    "statusExited": "Exited",
    "statusLegacy": "Legacy",
    "v1lesson": "Lesson: infrastructure wins when reliability, economics, and customer trust improve together.",
    "v2lesson": "Lesson: precision medicine requires equal discipline in science, software, privacy, and clinical usefulness.",
    "v3lesson": "Lesson: autonomy creates value only when sensing, communications, and human oversight form one resilient system.",
    "v5lesson": "Lección: la escala en infraestructura se gana con excelencia operativa mucho antes de la salida.",
    "currentEyebrow": "Current",
    "historyEyebrow": "Selected History",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — an Aerial-Ground Robotics Operations Network spanning UAV and Counter-UAS consulting, technology assessment, capability development, training infrastructure, product validation, geospatial systems (ISDRI), and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "v0role": "Founder",
    "v0year": "2026 — Present",
    "v1highlight": "Top 10 empresa de medicina de precisión en EE. UU. — 2023",
    "v1p1": "Fundó y escaló Digital Invest desde su inicio hasta una exitosa salida a bolsa. La empresa está dedicada a la esfera biomatemática, transformando la medicina mediante IA, ML y tecnologías de ADN.",
    "v1role": "Fundador y CEO · Miembro del consejo",
    "v1year": "2021 — Actual",
    "v2highlight": "Socio de Harvard Medical School y Stanford Biomath",
    "v2p1": "Pruebas y análisis de ADN, automatización de perfiles genéticos e investigación genética humana integral. Inició proyectos de pruebas genéticas en Ucrania, Rusia y los países bálticos.",
    "v2p2": "Colaboró con Harvard Medical School y Stanford Biomath en informes genéticos adoptados por laboratorios líderes en todo el mundo.",
    "v2role": "CEO y CTO",
    "v2year": "2008 — 2014",
    "v3highlight": "Soluciones de datos empresariales y gubernamentales",
    "v3p1": "Almacenamiento de datos y servicios de gestión de big data para grandes organizaciones comerciales y gubernamentales. Estableció la empresa como proveedor de confianza de soluciones de datos empresariales.",
    "v3role": "Fundador y CEO · Consejo de administración",
    "v3year": "2006 — 2011",
    "v4highlight": "Plataforma global de gestión de datos",
    "v4p1": "Gestión y almacenamiento de datos para pequeñas y medianas empresas. Desarrolló soluciones para un seguimiento más rápido de la información y un acceso más sencillo a los datos para usuarios finales e instituciones gubernamentales en todo el mundo.",
    "v4role": "Fundador y CEO",
    "v4year": "2000 — 2004",
    "v5highlight": "Adquirida · Valor máximo de 2000",
    "v5p1": "Construyó una de las mayores empresas de hosting del mundo. En 2000, adquirida por Concentric Networks (NASDAQ: CNTX) y luego por XO Communications (NASDAQ: XOXO), alcanzando un valor de mercado máximo de 2000",
    "v5role": "Fundador y CEO",
    "v5year": "1996 — 2000",
    "v6highlight": "Estrategia de TI e infraestructura global",
    "v6p1": "Empresa de TI de Massachusetts que ofrecía estrategias integrales y servicios tecnológicos a organizaciones globales líderes. Lideró el desarrollo de infraestructura escalable y operaciones de TI globales.",
    "v6role": "CEO y Director de Tecnología de la Información",
    "v6year": "1994 — 1996",
    "v7highlight": "Líder europeo en sistemas satelitales",
    "v7p1": "Uno de los mayores fabricantes europeos de sistemas satelitales de transcepción digital. Lideró investigación, desarrollo de sistemas operativos, aplicaciones de software de red y estrategia técnica general.",
    "v7role": "Fundador y CEO",
    "v7year": "1989 — 1994",
    "v8highlight": "Ingeniería de sistemas satelitales militares",
    "v8p1": "Desarrollo y creación de sistemas satelitales de transcepción para transmitir información clasificada a buques militares. Reconocido como ingeniero electrónico del más alto nivel en un astillero de 93.000 empleados.",
    "v8role": "Ingeniero electrónico · Categoría máxima (6.ª)",
    "v8year": "1984 — 1989"
  },
  "career": {
    "eyebrow": "Registro profesional",
    "title": "The Record",
    "lead": "Actividad documentada en ingeniería, infraestructura, mercados públicos, ciencias de la vida y sistemas autónomos.",
    "timelineEyebrow": "Línea de tiempo",
    "timelineTitle": "Hitos clave",
    "strengthsEyebrow": "Fortalezas",
    "strengthsTitle": "Áreas de experiencia",
    "filterAll": "All",
    "filterHealthcare": "Healthcare",
    "filterInfrastructure": "Infrastructure",
    "filterDefense": "Defense",
    "filterTelecom": "Telecommunications",
    "periodCurrent": "Current",
    "periodCurrentLead": "Principal companies and projects in active development.",
    "period1title": "Engineering & Communications",
    "period1lead": "Early engineering, satellite systems, communications, and related technology work.",
    "period2title": "Internet & Infrastructure",
    "period2lead": "Internet infrastructure, telecommunications, data centers, storage, and related companies.",
    "period3title": "Companies & Public Markets",
    "period3lead": "Company building, transactions, public-company involvement, and executive roles.",
    "period4title": "Life Sciences & Human Data",
    "period4lead": "Biotechnology, health-related technology, data, and precision medicine.",
    "period5title": "Government & Defense Programs",
    "period5lead": "Technology strategy and delivery for government, defense, and state-owned enterprise programs.",
    "t0desc": "Founded AGRON Inc. to build the AGRON Ecosystem — consulting, assessment, capability development, training infrastructure, and product support for UAV and Counter-UAS programmes, plus AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure. Connects aerial and ground robotics, governed mission execution, and network infrastructure linking teams, assets, and operational data.",
    "t0role": "Founder",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — Present",
    "s1desc": "Gestión dual CEO/CTO en empresas públicas y privadas, desde startup hasta IPO y más allá.",
    "s1title": "Liderazgo ejecutivo",
    "s2desc": "Ejecución integral de ofertas públicas — estructuración legal, coordinación con la SEC, roadshows con inversores y cumplimiento normativo.",
    "s2title": "IPO y escalado financiero",
    "s3desc": "Diseño de sistemas escalables para automatización empresarial, monitorización predictiva y control centralizado de datos.",
    "s3title": "Arquitectura de plataformas",
    "s4desc": "Desarrollo y operación de centros de datos para plataformas gubernamentales, militares y comerciales de alta seguridad.",
    "s4title": "Infraestructura segura",
    "t10desc": "Desarrolló y creó sistemas satelitales de transcepción para transmitir información clasificada a buques militares. Reconocido como ingeniero electrónico del más alto nivel en un astillero de 93.000 empleados — el inicio de una distinguida carrera en tecnología e innovación.",
    "t10role": "Ingeniero electrónico — 6.ª categoría (máxima)",
    "t10title": "Astillero de Nikolaev",
    "t10year": "1984 — 1989",
    "t1desc": "Fundó y escaló la empresa desde su inicio hasta una exitosa salida a bolsa. Lideró todo el proceso de oferta pública — estructuración legal, cumplimiento financiero, roadshows con inversores y coordinación con la SEC. Dirigió el diseño, construcción y operación de múltiples centros de datos en EE. UU. y Europa. Construyó sistemas de software empresariales para automatización, monitorización predictiva y control centralizado de datos. Logró un crecimiento financiero constante, posicionando la empresa entre las 10 mejores de medicina de precisión en EE. UU. (2023).",
    "t1role": "Fundador y CEO",
    "t1title": "Digital Invest Inc.",
    "t1year": "2021 — Actual",
    "t2desc": "Dirigió la estrategia y ejecución tecnológica de programas clasificados y de alta sensibilidad con agencias gubernamentales de EE. UU., sistemas de defensa aliados y empresas estatales. Encabezó proyectos técnicos complejos para empresas de propiedad estatal en múltiples sectores. Tras el 11 de septiembre de 2001, lideró iniciativas gubernamentales a gran escala centradas en big data, comunicaciones seguras, analítica predictiva e integración de datos a nivel nacional — incluido el diseño, construcción y operación de centros de datos de alto rendimiento en Estados Unidos y Europa. Interactuó con oficiales de programas militares, proveedores tecnológicos y entidades reguladoras.",
    "t2role": "Asesor tecnológico principal / Arquitecto de programas",
    "t2title": "GovTech, defensa y programas estatales",
    "t2year": "2001 — 2019",
    "t3desc": "Lideró pruebas y análisis de ADN, automatización de perfiles genéticos e investigación genética humana integral. Inició proyectos de pruebas genéticas en Ucrania, Rusia y los países bálticos. Colaboró con Harvard Medical School y Stanford Biomath para desarrollar informes genéticos comprensibles adoptados por laboratorios líderes en todo el mundo.",
    "t3role": "CEO y CTO",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4desc": "Dirigió despliegues de infraestructura nacional en Canadá, Italia, Suiza, Ucrania y las repúblicas bálticas. Supervisó a más de 1.000 ingenieros y personal de despliegue en operaciones de telecomunicaciones, incluidos sistemas de conmutación, expansión de banda ancha y conectividad transfronteriza. Implementó sistemas centrales de redundancia de red, optimización de disponibilidad y enrutamiento inteligente.",
    "t4role": "VP de Tecnología / CTO regional — Europa del Este y CEI",
    "t4title": "Proyectos de telecomunicaciones",
    "t4year": "2000 — 2012",
    "t5desc": "Fundó una empresa tecnológica especializada en almacenamiento de datos y gestión de big data para grandes organizaciones comerciales y gubernamentales. Estableció la empresa como proveedor de confianza de soluciones de datos empresariales.",
    "t5role": "Fundador y CEO · Consejo de administración",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6desc": "Estableció una empresa de gestión y almacenamiento de datos para pymes. Desarrolló soluciones tecnológicas únicas para un seguimiento más rápido de la información y un acceso más sencillo a los datos para usuarios finales e instituciones gubernamentales en todo el mundo.",
    "t6role": "Fundador y CEO",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "Construyó una de las mayores empresas de hosting del mundo. En 2000, adquirida por Concentric Networks (NASDAQ: CNTX) y luego por XO Communications (NASDAQ: XOXO), alcanzando un valor de mercado máximo de 2000",
    "t7role": "Fundador y CEO",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8desc": "Lideró estrategias integrales de TI y servicios tecnológicos para organizaciones globales líderes desde Massachusetts en un período de rápida expansión, construyendo infraestructura escalable y operaciones de TI globales.",
    "t8role": "CEO y Director de Tecnología de la Información",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9desc": "Fundó uno de los mayores fabricantes europeos de sistemas satelitales de transcepción digital. Lideró investigación, desarrollo de sistemas operativos, aplicaciones de software de red y estrategia técnica general, obteniendo reconocimiento internacional.",
    "t9role": "Fundador y CEO",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994"
  },
  "recognition": {
    "eyebrow": "Registro documentado",
    "title": "Premios y reconocimientos",
    "lead": "Distinciones en emprendimiento, medicina de precisión, ingeniería y liderazgo ejecutivo.",
    "industryEyebrow": "Honores y referencias",
    "industryTitle": "Entradas seleccionadas",
    "ipEyebrow": "Propiedad intelectual",
    "ipTitle": "Patentes y publicaciones",
    "eduEyebrow": "Educación",
    "eduTitle": "Credenciales académicas",
    "pressEyebrow": "Prensa",
    "pressTitle": "Destacado en",
    "moreLink": "Ver patentes, publicaciones y notas de prensa en Insights →",
    "a1title": "Emprendedor del año",
    "a1desc": "Entrepreneur Magazine · 2001",
    "a2title": "Top 10 empresa de medicina de precisión en EE. UU.",
    "a2desc": "Digital Invest Inc. reconocida entre las 10 mejores empresas de medicina de precisión y salud digital de América — 2023.",
    "a3title": "Who's Who in America",
    "a3desc": "Incluido, 1999 — 2018 — por logros excepcionales en creación y desarrollo empresarial.",
    "a4title": "Who's Who in the World",
    "a4desc": "Incluido, 2000 — 2004 — entre líderes globales en ciencia, ingeniería e innovación empresarial.",
    "a5title": "Who's Who in Science & Engineering",
    "a5desc": "Incluido, 2000 — 2014 — por contribuciones a la tecnología, sistemas satelitales e infraestructura digital.",
    "a6title": "Ingeniero electrónico — 6.ª categoría",
    "a6desc": "Máximo reconocimiento en el Astillero de Nikolaev (93.000 empleados) por ingeniería de sistemas satelitales de transcepción.",
    "ip1year": "Patente",
    "ip1title": "Sistemas HDTV satelitales digitales",
    "ip1role": "Posteriormente adquirida por Sony",
    "ip1desc": "Patente en sistemas HDTV satelitales digitales, adquirida posteriormente por Sony Corporation.",
    "ip2year": "Publicaciones",
    "ip2title": "Trabajos técnicos",
    "ip2role": "Sistemas satelitales y ópticos",
    "ip2desc": "Autor de trabajos técnicos sobre sistemas satelitales y ópticos de transmisión de datos. Sus contribuciones abarcan procesamiento de señales, modelado de simulación y plataformas de automatización aplicadas en telecomunicaciones, infraestructura nacional y salud digital.",
    "ip3year": "Investigación",
    "ip3title": "Colaboraciones internacionales",
    "ip3role": "EE. UU. y Europa",
    "ip3desc": "Participó en colaboraciones de investigación internacional e iniciativas de transferencia de conocimiento. Desarrolló sistemas de ingeniería embebidos para adquisición de datos, diagnósticos predictivos y orquestación en la nube en múltiples industrias.",
    "edu1title": "Doctor en Ciencias Técnicas",
    "edu2title": "Doctorado en Tecnologías de la Información",
    "edu3title": "Maestrías",
    "edu3desc": "Electrónica, sistemas satelitales digitales y economía",
    "press1title": "Healthcare Tech Outlook",
    "press1role": "Reportaje sobre Digital Invest Inc.",
    "press1desc": "Healthcare Tech Outlook sobre Digital Invest Inc. y medicina de precisión (2023).",
    "press1link": "Leer reportaje →",
    "press2title": "Top Precision Medicine Solutions",
    "press2role": "Reconocimiento del sector",
    "press2desc": "Nombrada entre las principales empresas de soluciones de medicina de precisión, destacando el papel de Digital Invest en el avance de enfoques biomatemáticos en la atención sanitaria moderna.",
    "press2link": "Ver listado →"
  },
  "contact": {
    "eyebrow": "Póngase en contacto",
    "title": "Conectemos",
    "lead": "Para roles de asesoría, juntas directivas y alianzas estratégicas.",
    "infoTitle": "Contacto directo",
    "email": "Correo",
    "phone": "Teléfono",
    "location": "Ubicación",
    "locationVal": "Charlotte, North Carolina\nUnited States",
    "linkedin": "LinkedIn",
    "company": "Empresa actual",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member\nAGRON Inc.\nFounder",
    "formTitle": "Enviar mensaje",
    "formLead": "Complete el formulario y le responderé pronto.",
    "firstName": "Nombre",
    "lastName": "Apellido",
    "emailLabel": "Correo electrónico",
    "subject": "Asunto",
    "message": "Mensaje",
    "inquiryType": "Inquiry Type",
    "inquiryAdvisory": "Advisory / Board Role",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "calendlyEyebrow": "Schedule a Conversation",
    "calendlyTitle": "Choose a Convenient Time",
    "calendlyLead": "For qualified board, advisory, speaking, and strategic partnership inquiries.",
    "calendlyPlaceholder": "Scheduling calendar will appear here.",
    "calendlyCta": "Open Scheduling Calendar",
    "inquiryBusiness": "Business",
    "infoEyebrow": "Información de contacto"
  },
  "consulting": {
    "eyebrow": "Servicios de asesoría",
    "title": "Consultoría",
    "heroEyebrow": "Orientación empresarial estratégica",
    "heroTitle": "Asesoría estratégica",
    "heroLead": "Treinta y cinco años fundando y asesorando empresas en EE. UU. y Europa — infraestructura de datos, govtech, medicina de precisión y robótica.",
    "cta": "Contactar a Michael Kofman",
    "introLead": "CEO de Digital Invest Inc. y miembro del consejo. Enfoque: tecnología emergente, seguridad, investigación y asignación de capital.",
    "specialtiesEyebrow": "Áreas de enfoque",
    "specialtiesTitle": "En qué se especializa Michael Kofman",
    "area1title": "Board Service",
    "area1desc": "Independent director and board-level work in technology strategy, corporate governance, and growth-stage oversight.",
    "area2title": "CEO & Founder Advisory",
    "area2desc": "Corporate and technology strategy, organizational development, transactions, and applicable capital-markets experience.",
    "area3title": "Technology Due Diligence",
    "area3desc": "Evaluation of infrastructure, data platforms, security architecture, and applied technology based on documented operating experience."
  },
  "insights": {
    "eyebrow": "Perspectivas",
    "title": "Perspectivas",
    "heroTitle": "Perspectivas ejecutivas",
    "selectedEyebrow": "Destacados seleccionados",
    "selectedTitle": "Reconocimiento destacado",
    "allPressTitle": "Todas las apariciones en prensa",
    "quotesEyebrow": "En los medios",
    "quotesTitle": "Reconocimiento del sector y citas",
    "articlesEyebrow": "Perspectivas",
    "articlesTitle": "Perspectivas ejecutivas",
    "briefsEyebrow": "Executive Briefs",
    "briefsTitle": "Ideas for Leaders",
    "briefsLead": "Short, practical perspectives on governance, technology, healthcare, and company building.",
    "brief1title": "What an IPO Changes",
    "brief1desc": "The operating and governance disciplines that public-market readiness demands.",
    "brief1tag": "Capital Markets",
    "brief2title": "From Genetic Data to Clinical Decisions",
    "brief2desc": "How to build useful health intelligence without outrunning evidence or trust.",
    "brief2tag": "Precision Medicine",
    "brief3title": "AI Strategy Beyond the Pilot",
    "brief3desc": "A framework for turning experiments into governed enterprise capability.",
    "brief3tag": "Artificial Intelligence",
    "readingEyebrow": "Reading List",
    "readingTitle": "Books That Shape Strategic Thinking",
    "r1title": "The Innovator's Dilemma",
    "r1author": "Clayton M. Christensen",
    "r2title": "Thinking, Fast and Slow",
    "r2author": "Daniel Kahneman",
    "r3title": "The Beginning of Infinity",
    "r3author": "David Deutsch",
    "r4title": "Good Strategy/Bad Strategy",
    "r4author": "Richard Rumelt",
    "r5title": "The Structure of Scientific Revolutions",
    "r5author": "Thomas S. Kuhn",
    "newsletterEyebrow": "Occasional Notes",
    "newsletterTitle": "Executive Perspective, Without the Noise",
    "newsletterLead": "Periodic essays and brief observations on technology, governance, and durable company building.",
    "newsletterCta": "Subscribe for Updates"
  },
  "cta": {
    "eyebrow": "Trabajemos juntos",
    "title": "Solicitar asesoría o una conferencia",
    "lead": "Para funciones de asesoría, puestos en juntas directivas, conferencias y alianzas estratégicas.",
    "button": "Póngase en contacto"
  },
  "speaking": {
    "eyebrow": "Conferencias",
    "title": "Invite a Michael Kofman a su evento",
    "lead": "Disponible para conferencias sobre liderazgo ejecutivo, estrategia tecnológica, salud digital, infraestructura de datos y gobierno corporativo.",
    "topicsEyebrow": "Temas de conferencia",
    "topicsTitle": "Áreas de experiencia",
    "topicsLead": "Los temas se basan en décadas de experiencia fundando y dirigiendo empresas en Estados Unidos y Europa.",
    "processEyebrow": "Cómo invitar",
    "processTitle": "Proceso de contratación",
    "process1title": "Envíe una solicitud",
    "process1desc": "Use el formulario de contacto o escriba a mkofman@mkofman.com con los detalles del evento, la audiencia y los temas preferidos.",
    "process2title": "Confirme el alcance",
    "process2desc": "Defina el formato (ponencia principal, panel, sesión de junta o mesa redonda ejecutiva) y la logística.",
    "process3title": "Genere impacto",
    "process3desc": "Las presentaciones se basan en resultados reales de iniciativas en almacenamiento de datos, govtech y medicina de precisión.",
    "cta": "Solicitar una conferencia",
    "catalogEyebrow": "Speaking Topics",
    "catalogTitle": "Executive Conversations for Consequential Change",
    "catalogLead": "Keynotes, board sessions, and leadership briefings tailored to the audience, sector, and decision context.",
    "t1title": "Governing AI Before It Governs the Enterprise",
    "t1audience": "Boards, audit and risk committees",
    "t1format": "Board briefing or keynote",
    "t2title": "From Technology Trend to Enterprise Strategy",
    "t2audience": "CEOs, executive teams, investors",
    "t2format": "Keynote or executive workshop",
    "t3title": "Building Companies Through Market Cycles",
    "t3audience": "Founders, growth leaders, private equity",
    "t3format": "Fireside chat or keynote",
    "t4title": "Precision Medicine: Promise, Proof, and Responsibility",
    "t4audience": "Healthcare leaders, clinicians, innovators",
    "t4format": "Industry keynote or panel",
    "t5title": "The Board's Role in Cyber and Technology Risk",
    "t5audience": "Directors, general counsel, risk leaders",
    "t5format": "Board education session",
    "t6title": "Engineering Trust into Digital Infrastructure",
    "t6audience": "Technology and infrastructure organizations",
    "t6format": "Technical-executive keynote",
    "t7title": "Leading Across Borders and Disciplines",
    "t7audience": "Global leadership teams and universities",
    "t7format": "Keynote or moderated conversation",
    "t8title": "From Founder to Institution Builder",
    "t8audience": "Entrepreneurs and next-generation executives",
    "t8format": "Workshop or fireside chat"
  },
  "caseStudies": {
    "eyebrow": "Casos de estudio",
    "title": "Construyendo empresas que escalan",
    "lead": "Resultados seleccionados de la fundación y dirección de empresas en infraestructura de datos y salud digital.",
    "cs1eyebrow": "Infraestructura de datos · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "Desafío",
    "cs1challengeText": "Construir y escalar una empresa de almacenamiento de datos en un mercado tecnológico en rápida consolidación.",
    "cs1action": "Enfoque",
    "cs1actionText": "Fundé 9 Net Avenue Inc. en 1996. La empresa se convirtió rápidamente en una de las mayores compañías de almacenamiento de datos del mundo.",
    "cs1result": "Resultado",
    "cs1resultText": "Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO). Following the transaction, continued work with public companies and board-level roles.",
    "cs2eyebrow": "Salud digital · 2021 — Presente",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "Desafío",
    "cs2challengeText": "Transformar enfoques médicos obsoletos mediante ciencia, tecnologías de ADN, IA y ML a través de una nueva plataforma bio-matemática.",
    "cs2action": "Enfoque",
    "cs2actionText": "Fundé y escalé Digital Invest Inc. desde su inicio hasta una salida a bolsa exitosa. Dirigí todo el proceso de oferta pública: estructuración legal, cumplimiento financiero, roadshows con inversores y coordinación con la SEC. También dirigí el diseño, la construcción y la operación de múltiples centros de datos en EE. UU. y Europa.",
    "cs2result": "Resultado",
    "cs2resultText": "Logramos un crecimiento financiero sostenido y posicionamos a la empresa entre las 10 principales compañías de medicina de precisión de EE. UU. (2023), con proyectos como Human Digital Model y BioMath Life.",
    "cs3eyebrow": "Robotics & UAV · 2026 — Present",
    "cs3title": "AGRON Inc.",
    "cs3challenge": "Challenge",
    "cs3challengeText": "Organizations building UAV and Counter-UAS capability need independent assessment, structured training, and operational architecture — not isolated platforms or ad-hoc piloting.",
    "cs3action": "Approach",
    "cs3actionText": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — consulting, assessment and validation, capability development, training infrastructure, product development support, geospatial systems through ISDRI, and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "cs3result": "Outcome",
    "cs3resultText": "A connected professional services ecosystem spanning five service domains and multiple companies — Global Drone Academy, AGRON, ISDRI, and GUARD — with programmes delivered across 10+ countries and 10,000+ UAV operators, instructors, and specialists trained."
  },
  "mediaKit": {
    "eyebrow": "Prensa y eventos",
    "title": "Kit de prensa",
    "lead": "Biografías oficiales, material visual y datos de contacto para prensa, conferencias y consultas de juntas directivas.",
    "bioEyebrow": "Biografías",
    "bioTitle": "Biografías oficiales",
    "bioShortLabel": "50 palabras",
    "bioShort": "Michael Kofman es CEO de Digital Invest Inc. y miembro de consejos, asesor y fundador de empresas de tecnología y salud digital en EE. UU. y Europa.",
    "bioMediumLabel": "150 palabras",
    "bioMedium": "Michael Kofman es CEO de Digital Invest Inc. y miembro de su consejo. Emprendedor, miembro de juntas y asesor; ha fundado empresas en EE. UU. y Europa en infraestructura de datos, salud digital y robótica. Su trabajo abarca estrategia tecnológica, seguridad, investigación e inversión.",
    "bioLongLabel": "500 palabras",
    "bioLong": "Michael Kofman is CEO of Digital Invest Inc. and serves on its board. He founded 9 Net Avenue Inc., acquired by Concentric Networks in 2000, and leads Digital Invest in bio-mathematical medicine and genomic intelligence. He founded AGRON Inc. in 2026 for autonomous aerial-ground operations and geospatial systems. Author of technical papers on satellite and optical systems; patent in digital satellite HDTV acquired by Sony. Education: Doctor of Technical Sciences, Ph.D. in Information Technology.",
    "photosEyebrow": "Fotografía",
    "photosTitle": "Imágenes aprobadas",
    "photosLead": "Retratos en alta resolución disponibles previa solicitud en mkofman@mkofman.com.",
    "contactEyebrow": "Contacto de prensa",
    "contactTitle": "Consultas de medios",
    "contactLead": "Para entrevistas, invitaciones a conferencias y solicitudes de prensa.",
    "downloadEyebrow": "Download",
    "downloadTitle": "One-Page Media Kit",
    "downloadLead": "PDF with official bios, portrait, and press contact — ready to share with organizers and journalists.",
    "downloadCta": "Download PDF",
    "brandEyebrow": "Brand Assets",
    "brandTitle": "Identity & Usage",
    "brandLead": "Approved visual assets for editorial, conference, and partner use. Please preserve proportions, spacing, and original colors.",
    "brandColors": "Official Color Palette",
    "brandLogo": "Primary Logo",
    "brandDownload": "Download Brand Assets"
  },
  "articles": {
    "backLink": "← Volver a Insights",
    "article1date": "Perspectiva ejecutiva",
    "article1title": "De la ingeniería a la infraestructura global de datos",
    "article1p1": "Mi carrera comenzó en la planta de construcción naval de Nikolaev, en Ucrania, desarrollando sistemas transceptores satelitales para transmitir información clasificada a buques militares. Fui reconocido como ingeniero electrónico del más alto nivel: la 6.ª categoría en una planta de 93.000 empleados.",
    "article1p2": "Entre 1989 y 1994 fundé y dirigí Astra Corp, uno de los mayores fabricantes europeos de sistemas satelitales transceptores digitales. De 1994 a 1996, como CEO de Elitan United Inc., ayudé a escalar la empresa de nueve a más de 4.000 empleados en todo el mundo.",
    "article1p3": "In 1996, I founded 9 Net Avenue Inc., a hosting and internet infrastructure company. In 2000 it was acquired by Concentric Networks (NASDAQ: CNTX) and subsequently became part of XO Communications (NASDAQ: XOXO).",
    "article1p4": "De 2001 a 2019 dirigí la estrategia tecnológica para programas gubernamentales, de defensa y de empresas estatales, liderando iniciativas de gran escala en big data, infraestructura segura y centros de datos de alto rendimiento en Estados Unidos y Europa.",
    "article2date": "Salud digital",
    "article2title": "Medicina de precisión y convergencia entre ciencia y tecnología",
    "article2p1": "Creo firmemente en el potencial de combinar las ciencias de la vida con los últimos avances tecnológicos. En Biotechnology Group Inc. (2008-2014), nos enfocamos en pruebas y análisis de ADN, automatización de procesos para crear perfiles genéticos e investigación genética humana integral.",
    "article2p2": "Bajo mi liderazgo, se iniciaron proyectos exitosos de pruebas genéticas en Ucrania, Rusia y los países bálticos. En colaboración con Harvard Medical School y Stanford Biomath, desempeñé un papel clave en el desarrollo de reportes genéticos fáciles de comprender para médicos y pacientes.",
    "article2p3": "Con Digital Invest Inc., fundada en 2021, nos dedicamos al ámbito bio-matemático, transformando enfoques médicos obsoletos mediante ciencia, tecnologías de ADN, IA y ML. La empresa se escaló desde su inicio hasta una salida a bolsa exitosa y fue reconocida entre las 10 mejores compañías de EE. UU. en medicina de precisión y salud digital en 2023.",
    "article2p4": "Digital Invest impulsa la medicina biomatemática con proyectos como Human Digital Model y BioMath Life. En 2026, Michael Kofman fundó AGRON Inc. para liderar la Aerial-Ground Robotics Operations Network — desarrollo de capacidades UAV, sistemas geoespaciales e inteligencia marítima en agron1.com."
  },
  "privacy": {
    "eyebrow": "Legal",
    "title": "Política de privacidad",
    "lead": "Cómo mkofman.com trata la información cuando visita el sitio o envía un mensaje.",
    "updated": "Actualizado: julio de 2026",
    "s1title": "Información que recopilamos",
    "s1text": "Al enviar un formulario, recibimos los campos que usted proporciona (nombre, email, mensaje). Si la analítica está activa, podemos recopilar datos de uso anonimizados.",
    "s2title": "Cómo usamos la información",
    "s2text": "Los formularios se usan para responder consultas y mejorar el sitio. No vendemos datos personales.",
    "s3title": "Servicios de terceros",
    "s3text": "Los formularios pueden procesarse con Formspree. La analítica puede usar Plausible o Google Analytics si está configurada.",
    "s4title": "Sus derechos",
    "s4text": "Puede solicitar acceso, corrección o eliminación escribiendo a mkofman@mkofman.com.",
    "s5title": "Contacto",
    "s5text": "Preguntas sobre esta política: mkofman@mkofman.com"
  },
  "board": {
    "eyebrow": "Board & Strategic Advisory",
    "title": "Independent Judgment for Consequential Decisions",
    "lead": "I work with boards, founders, and executive teams navigating technology risk, market transitions, capital allocation, and responsible growth.",
    "rolesEyebrow": "Ways to Engage",
    "rolesTitle": "Board-Level Partnership",
    "role1title": "Independent Director",
    "role1desc": "Constructive oversight, informed challenge, and long-range perspective for public and private company boards.",
    "role2title": "Advisory Board Member",
    "role2desc": "Practical guidance on emerging technologies, product strategy, market positioning, and institutional readiness.",
    "role3title": "CEO & Founder Advisor",
    "role3desc": "Confidential counsel for leaders facing inflection points in scale, governance, succession, financing, or transformation.",
    "role4title": "Special Committee Advisor",
    "role4desc": "Focused support for transactions, technology diligence, cybersecurity exposure, and other high-stakes mandates.",
    "valueEyebrow": "Perspective",
    "valueTitle": "What I Bring to the Table",
    "value1title": "Operator's Discipline",
    "value1desc": "Experience building organizations from inception through global scale, acquisition, and public-market accountability.",
    "value2title": "Technical Fluency",
    "value2desc": "The ability to translate complex systems, scientific claims, and technology risk into clear board decisions.",
    "value3title": "Cross-Market Judgment",
    "value3desc": "A perspective shaped by technology, telecommunications, defense, data infrastructure, and precision medicine.",
    "value4title": "Governance Mindset",
    "value4desc": "A commitment to fiduciary responsibility, candid dialogue, ethical innovation, and durable stakeholder value.",
    "cta": "Discuss a Board Mandate",
    "availability": "Select independent director, advisory board, and strategic counsel engagements are considered."
  },
  "thesis": {
    "eyebrow": "Leadership Thesis",
    "title": "Build for the Long Term. Decide in the Present.",
    "lead": "Technology changes quickly; the obligations of leadership do not. Durable enterprises unite ambition with discipline, evidence, and accountability.",
    "intro": "These principles reflect more than three decades of founding companies, engineering critical systems, advising boards, and leading through market cycles.",
    "believeEyebrow": "What I Believe",
    "believeTitle": "Seven Principles for Enduring Organizations",
    "b1title": "Strategy Must Produce Choices",
    "b1text": "A strategy is not a catalog of aspirations. It defines where to compete, what capabilities to build, what not to pursue, and how success will be measured.",
    "b2title": "Technology Is a Governance Issue",
    "b2text": "Boards must understand how technology creates value, concentrates risk, and changes accountability. Delegating every technical question is itself a decision.",
    "b3title": "Evidence Should Outrank Enthusiasm",
    "b3text": "Conviction matters, but markets, systems, and science must be tested. Leaders create mechanisms that expose assumptions before customers or regulators do.",
    "b4title": "Architecture Shapes the Enterprise",
    "b4text": "Technical architecture determines speed, resilience, security, and future options. Shortcuts become institutional constraints long after their original context disappears.",
    "b5title": "Trust Is Operating Infrastructure",
    "b5text": "Trust is built through clear commitments, reliable execution, responsible data practices, and direct communication when conditions change.",
    "b6title": "Capital Must Follow Capability",
    "b6text": "Growth investment should reinforce differentiated capabilities and measurable demand, not substitute spending for product-market understanding.",
    "b7title": "Leaders Design Their Successors",
    "b7text": "The strongest leaders build systems, talent, and decision quality that endure beyond their own involvement.",
    "rejectEyebrow": "What I Reject",
    "rejectTitle": "Three Expensive Illusions",
    "r1title": "Innovation Theater",
    "r1text": "Announcements, pilots, and fashionable language do not equal capability. Innovation must improve an outcome that matters.",
    "r2title": "Growth Without Governance",
    "r2text": "Scale magnifies unresolved weaknesses. Controls, culture, and accountability should mature before complexity makes correction costly.",
    "r3title": "False Certainty",
    "r3text": "Executive confidence should not erase uncertainty. Strong decisions make assumptions visible and preserve options when facts change.",
    "horizonEyebrow": "The Horizon",
    "horizonTitle": "The Next Advantage Is Responsible Integration",
    "horizonText": "The defining opportunity is not any single technology. It is the disciplined integration of AI, advanced data systems, biology, and automation into institutions people can trust."
  },
  "press": {
    "eyebrow": "Press & Media",
    "title": "Selected Coverage",
    "lead": "A concise archive of third-party recognition and reporting across technology, entrepreneurship, and precision medicine.",
    "archiveEyebrow": "Archive",
    "y2023type": "Industry Recognition",
    "y2023title": "Top 10 Precision Medicine Companies",
    "y2023desc": "Healthcare Tech Outlook recognized Digital Invest Inc. among leading U.S. companies advancing precision medicine and digital health.",
    "y2023link": "View feature",
    "y2001type": "Executive Award",
    "y2001title": "Entrepreneur of the Year",
    "y2001desc": "Entrepreneur Magazine recognition.",
    "y2001link": "View archive",
    "y1999type": "Biographical Recognition",
    "y1999title": "Who's Who in America",
    "y1999desc": "Recognition beginning in 1999, followed by listings in Who's Who in the World and Who's Who in Science and Engineering.",
    "clipEyebrow": "From the Archive",
    "clipMeta": "Industry Feature · DataPeer Inc.",
    "clipTitle": "State of the Storage Industry",
    "clipLead": "An early interview with Michael Kofman as Founder, Chairman, and CEO of DataPeer Inc. — reflecting on fiber optics, satellite transmission, SAN, and the emerging storage market.",
    "clipBody": "The feature notes recognition as Entrepreneur of the Year by Entrepreneur Magazine (2001) and discusses DataPeer’s approach to mission-critical storage, iSCSI, and business continuity.",
    "clipOpen": "Open full page scan →",
    "y2000type": "Interview",
    "y2000title": "State of the Storage Industry",
    "y2000desc": "Featured interview as Founder, Chairman, and CEO of DataPeer Inc. on storage networks, iSCSI, and business continuity."
  },
  "ip": {
    "eyebrow": "Intellectual Property",
    "title": "Applied Ideas, Documented",
    "lead": "Selected patents, publications, and research programs connecting engineering rigor with practical business and societal outcomes.",
    "patentEyebrow": "Patents",
    "patentTitle": "Protected Inventions",
    "patentIntro": "Patent work reflects a sustained focus on systems that improve the collection, movement, protection, and interpretation of information.",
    "publicationsEyebrow": "Publications",
    "publicationsTitle": "Technical & Executive Writing",
    "publicationsIntro": "Published work translates complex technical subjects into methods, frameworks, and decisions useful to practitioners and leaders.",
    "researchEyebrow": "Research",
    "researchTitle": "Interdisciplinary Programs",
    "researchIntro": "Research initiatives span secure communications, predictive analytics, genetic interpretation, human digital modeling, and autonomous systems."
  },
  "testimonials": {
    "t1quote": "Michael combines an engineer's precision with the judgment of an experienced chief executive. He asks the questions that improve the decision.",
    "t1name": "Board Colleague",
    "t1role": "Public Technology Company",
    "t2quote": "His ability to connect science, product, governance, and commercial reality brings uncommon clarity to complex initiatives.",
    "t2name": "Strategic Partner",
    "t2role": "Digital Health Sector",
    "t3quote": "Michael is direct, thoughtful, and focused on durable value. He helps leadership teams see both the opportunity and the obligation.",
    "t3name": "Executive Collaborator",
    "t3role": "Global Infrastructure"
  },
  "deck": {
    "title": "Michael Kofman",
    "subtitle": "Ejecutivo tecnológico · Fundador · Asesor de consejos",
    "thesis": "Tecnología, negocios e inversión en infraestructura, ciencias de la vida y sistemas autónomos.",
    "contact": "Confidential discussion: contact Michael Kofman through mkofman.com"
  },
  "briefIpo": {
    "title": "What an IPO Changes",
    "desc": "Public markets do not merely change a company's capital structure; they change its operating contract.",
    "p1": "An initial public offering is often described as a financing event. In practice, it is an institutional transition. Forecasting, controls, disclosure, governance, and executive communication must become repeatable before the listing, not improvised afterward.",
    "p2": "Readiness begins with decision quality. Management needs reliable metrics, clear ownership, and an operating cadence that can explain both performance and variance. A company that cannot reconcile its internal narrative will struggle to communicate a credible external one.",
    "p3": "The board's role also changes. Directors must balance growth with oversight, understand material technology and market risks, and ensure that incentives support durable value rather than a single quarter.",
    "p4": "The strongest public companies preserve entrepreneurial speed while adding institutional discipline. The objective is not bureaucracy; it is trustworthy execution at a higher level of accountability.",
    "eyebrow": "Informe ejecutivo"
  },
  "briefGenetic": {
    "title": "From Genetic Data to Clinical Decisions",
    "desc": "The value of genomic information depends on interpretation, evidence, and responsible integration into care.",
    "p1": "Genetic data is abundant; clinically useful meaning is scarce. A result becomes valuable only when it is interpreted in context, connected to validated evidence, and presented in a form that supports a real decision.",
    "p2": "That translation requires collaboration across molecular biology, medicine, statistics, software engineering, and patient communication. Weakness in any layer can turn technical sophistication into clinical confusion.",
    "p3": "Privacy and consent are architectural requirements, not legal footnotes. Systems must limit unnecessary exposure, make data provenance visible, and preserve patient agency as information moves between laboratories, platforms, and care teams.",
    "p4": "Precision medicine will advance through measured integration: better evidence, transparent models, interoperable workflows, and outcomes that clinicians and patients can evaluate. Trust is part of the product.",
    "eyebrow": "Informe ejecutivo"
  },
  "briefAi": {
    "title": "AI Strategy Beyond the Pilot",
    "desc": "Enterprise AI creates value when ownership, data, workflow, and governance mature together.",
    "p1": "Many AI initiatives begin with a compelling demonstration and stall before production. The missing element is rarely the model alone. Sustainable value requires a defined business outcome, accountable owner, dependable data, and a workflow people will actually use.",
    "p2": "Leaders should distinguish automation, prediction, and decision support. Each carries different requirements for accuracy, explainability, human review, and risk. A single governance template will not fit every use case.",
    "p3": "Measurement must include more than technical performance. Adoption, cycle time, error rates, customer impact, security exposure, and the cost of supervision determine whether an AI capability is economically and institutionally sound.",
    "p4": "The winning approach is a managed portfolio: scale proven use cases, stop weak ones early, and maintain explicit boundaries for high-consequence decisions. AI strategy is ultimately operating strategy.",
    "eyebrow": "Informe ejecutivo"
  }
};
