window.__LANG_es = {
  "ui": {
    "toggleTheme": "Cambiar tema claro/oscuro",
    "selectLanguage": "Seleccionar idioma",
    "messageSent": "Mensaje enviado",
    "sendMessage": "Enviar mensaje",
    "toggleNav": "Abrir menú",
    "sending": "Enviando…",
    "formError": "No se pudo enviar. Por favor, escriba directamente por correo electrónico.",
    "present": "Actual"
  },
  "nav": {
    "home": "Inicio",
    "about": "Biografía",
    "ventures": "Empresas",
    "career": "Carrera",
    "recognition": "Reconocimientos",
    "contact": "Contacto",
    "consulting": "Consultoría",
    "insights": "Perspectivas",
    "speaking": "Conferencias",
    "caseStudies": "Casos de estudio",
    "mediaKit": "Kit de prensa",
    "groupMain": "Principal",
    "groupServices": "Servicios",
    "groupWork": "Trabajo"
  },
  "footer": {
    "navigation": "Navegación",
    "ventures": "Empresas",
    "connect": "Contacto",
    "desc": "CEO, tecnólogo estratégico y emprendedor galardonado.",
    "copyright": "© 2025–2026 Michael Kofman. Todos los derechos reservados.",
    "writeTitle": "Escríbame",
    "writeEmail": "Su email",
    "writeMessage": "Su mensaje",
    "writeSend": "Enviar",
    "writeSuccess": "Gracias — su mensaje ha sido enviado.",
    "more": "Más"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — CEO y Tecnólogo Estratégico",
      "description": "Sitio oficial de Michael Kofman — CEO galardonado, fundador y tecnólogo estratégico."
    },
    "about": {
      "title": "Biografía — Michael Kofman",
      "description": "Biografía de Michael Kofman — CEO de Digital Invest Inc. — visionario tecnológico y emprendedor galardonado."
    },
    "ventures": {
      "title": "Empresas — Michael Kofman",
      "description": "Empresas fundadas y dirigidas por Michael Kofman — desde Digital Invest Inc. hasta 9 Net Avenue Inc. — construyendo negocios transformadores en tecnología y salud."
    },
    "career": {
      "title": "Carrera — Michael Kofman",
      "description": "Línea de tiempo profesional de Michael Kofman — desde ingeniería satelital hasta CEO de empresas globales de tecnología y salud."
    },
    "recognition": {
      "title": "Reconocimientos — Michael Kofman",
      "description": "Premios, honores y reconocimientos de Michael Kofman — Emprendedor del Año, Who's Who, patentes y distinciones del sector."
    },
    "contact": {
      "title": "Contacto — Michael Kofman",
      "description": "Contacte a Michael Kofman — CEO de Digital Invest Inc. Para conferencias, roles de asesoría y consultas comerciales."
    },
    "consulting": {
      "title": "Consultoría — Michael Kofman",
      "description": "Roles de asesoría, puestos en juntas directivas, conferencias y alianzas estratégicas con Michael Kofman."
    },
    "insights": {
      "title": "Perspectivas — Michael Kofman",
      "description": "Publicaciones, prensa, patentes y reconocimiento del sector de Michael Kofman."
    },
    "speaking": {
      "title": "Conferencias — Michael Kofman",
      "description": "Invite a Michael Kofman a hablar sobre liderazgo ejecutivo, estrategia tecnológica, salud digital y gobierno corporativo."
    },
    "caseStudies": {
      "title": "Casos de estudio — Michael Kofman",
      "description": "Casos de estudio de la trayectoria de Michael Kofman: 9 Net Avenue Inc. y Digital Invest Inc."
    },
    "mediaKit": {
      "title": "Kit de prensa — Michael Kofman",
      "description": "Biografías oficiales, fotografías e información de contacto para prensa y organizadores de eventos."
    },
    "article1": {
      "title": "De la ingeniería a la infraestructura global — Michael Kofman",
      "description": "Michael Kofman sobre su trayectoria desde la ingeniería satelital hasta la fundación de empresas globales de infraestructura de datos."
    },
    "article2": {
      "title": "Medicina de precisión y tecnología — Michael Kofman",
      "description": "Michael Kofman sobre la integración de las ciencias de la vida con IA, ML y tecnologías de ADN en la medicina moderna."
    }
  },
  "home": {
    "heroEyebrow": "Sitio oficial de Michael Kofman",
    "heroTitle1": "Liderazgo visionario.",
    "heroTitle2": "Innovación estratégica.",
    "heroCta": "Descubra mi historia",
    "heroAlt": "Michael Kofman — CEO and Strategic Technologist",
    "quote1text": "A technology visionary recognized for his dynamic approach to understanding the ever-changing demands of today's complex marketplace.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "Entrepreneur of the Year — recognized for leadership and breakthrough achievements in platform innovation and infrastructure.",
    "quote2author": "Entrepreneur Magazine, 1999 — 2001",
    "quote3text": "Digital Invest Inc. named among America's Top 10 Best Companies in Precision Medicine and Digital Health.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "Known for uniting engineering precision with business strategy, delivering high-value outcomes, and building future-oriented companies from scratch.",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "Conozca a Michael Kofman",
    "aboutTitle": "Un legado de innovación y liderazgo",
    "aboutLead1": "Michael Kofman is a technological visionary renowned for his dynamic approach to understanding the ever-evolving needs of today's complex market. An entrepreneur, board member, and advisor for both public and private companies, he has successfully established several companies in the United States and Europe.",
    "aboutLead2": "Desde la fundación de una de las mayores empresas de Data Storage del mundo — adquirida con un valor de mercado máximo de 19,5 mil millones de dólares — hasta liderar Digital Invest Inc. en almacenamiento de datos e innovación tecnológica avanzada. Digital Invest reúne diversos proyectos innovadores, incluidos Human Digital Model, BioMath Life y Aero-Ground Robotics Operations Network.",
    "aboutLink": "Leer biografía completa",
    "expertiseEyebrow": "Experiencia multifacética",
    "expertiseTitle": "Liderazgo ejecutivo en múltiples industrias",
    "expertiseLead": "Explore Michael Kofman's diverse expertise as a CEO, technologist, advisor, and investor. With decades of experience, he provides unparalleled insight and guidance to drive success.",
    "exp1title": "CEO y fundador",
    "exp1desc": "Fundó y escaló múltiples empresas desde su inicio hasta la salida a bolsa, logrando un crecimiento financiero constante y presencia global en los sectores de tecnología y salud.",
    "exp1link": "Ver empresas →",
    "exp2title": "Arquitecto tecnológico",
    "exp2desc": "Diseñó comunicaciones seguras, motores de analítica predictiva y plataformas de integración de datos a nivel nacional para los sectores gubernamental, militar y de telecomunicaciones.",
    "exp2link": "Ver carrera →",
    "exp3title": "Salud digital",
    "exp3desc": "Lidera la transformación de la medicina mediante IA, ML y tecnologías de ADN. Colaboró con Harvard Medical School y Stanford Biomath en informes genéticos.",
    "exp3link": "Digital Invest →",
    "exp4title": "Asesor de junta",
    "exp4desc": "Participa en juntas directivas y asesora a empresas públicas y privadas sobre dirección estratégica, gobierno corporativo e iniciativas de crecimiento impulsadas por la tecnología.",
    "exp4link": "Consultoría →",
    "stat1": "Años de liderazgo",
    "stat2": "Empresas fundadas",
    "stat3": "Valor máximo de mercado",
    "stat4": "Empleados escalados",
    "recEyebrow": "Reconocimientos",
    "recTitle": "Premios y distinciones",
    "recLead": "Consistently recognized for exceptional achievements in business creation, innovation, and executive leadership.",
    "award1title": "Emprendedor del año",
    "award1desc": "Entrepreneur Magazine, 1999 — 2001",
    "award2title": "Top 10 medicina de precisión",
    "award2desc": "Digital Invest Inc. — U.S., 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "Ver todos los reconocimientos",
    "heroSub": "CEO, asesor de juntas directivas y estratega tecnológico para empresas públicas y privadas en tecnología, almacenamiento de datos y salud digital.",
    "primaryCta": "Solicitar asesoría",
    "secondaryCta": "Ver casos de estudio",
    "featuredEyebrow": "Como aparece en",
    "caseStudiesEyebrow": "Resultados comprobados",
    "caseStudiesTitle": "Casos de estudio",
    "caseStudiesLead": "Fundación, escalamiento y liderazgo de empresas desde su inicio hasta adquisiciones y salidas a bolsa.",
    "caseStudiesLink": "Ver todos los casos de estudio →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "Construyó una de las mayores compañías de almacenamiento de datos del mundo, adquirida con una capitalización máxima de mercado de 19.500 millones de dólares.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "Fundada y escalada desde su inicio hasta la salida a bolsa: Top 10 de compañías de medicina de precisión en EE. UU., 2023."
  },
  "about": {
    "eyebrow": "Sobre Michael Kofman",
    "title": "Un legado de innovación",
    "lead": "Visionario tecnológico, emprendedor y líder ejecutivo con más de tres décadas de carrera.",
    "glance": "En resumen",
    "role": "Cargo actual",
    "roleVal": "CEO & Board Member · Digital Invest Inc.",
    "location": "Ubicación",
    "locationVal": "Charlotte, North Carolina",
    "education": "Educación",
    "educationVal": "Doctor of Technical Sciences (2009)\nPh.D. in Information Technology (2004)\nMaster's in Electronic Engineering",
    "university": "Universidad",
    "universityVal": "Ukrainian State Marine Technical University",
    "languages": "Idiomas",
    "languagesVal": "English, Russian, Ukrainian",
    "contactLabel": "Contacto",
    "bioP1": "Michael Kofman es CEO de Digital Invest Inc. y miembro de su Consejo de Administración. Visionario tecnológico, es reconocido por su enfoque dinámico para comprender las necesidades en constante evolución del complejo mercado actual. Su experiencia abarca liderazgo ejecutivo, análisis estratégico de tecnologías y mercados emergentes, seguridad de la información y privacidad, investigación, ciencia y desarrollo, administración e inversión.",
    "bioP2": "Como emprendedor, miembro de juntas directivas y asesor de empresas públicas y privadas, Michael Kofman ha fundado con éxito varias compañías en Estados Unidos y Europa. Recientemente emprendió un ambicioso proyecto con la creación de Digital Invest, empresa dedicada a la esfera biomatemática, orientada a transformar enfoques obsoletos en medicina mediante los últimos avances en ciencia, tecnologías de ADN, IA y ML.",
    "secBioTitle": "Medicina de precisión y biotecnología",
    "secBioP1": "Antes de Digital Invest, desempeñó un papel decisivo en el éxito de Biotechnology Group Inc. (2008–2014), empresa dedicada a pruebas y análisis de ADN, automatización de perfiles genéticos e investigación genética humana integral. El Sr. Kofman cree firmemente en el potencial de combinar las ciencias de la vida con los últimos avances tecnológicos.",
    "secBioP2": "Bajo su liderazgo se iniciaron proyectos exitosos de pruebas genéticas en Ucrania, Rusia y los países bálticos. Esta experiencia única se enriquece continuamente con tecnologías modernas y nuevo equipamiento. En colaboración con Harvard Medical School y Stanford Biomath, el Sr. Kofman desempeñó un papel crucial en el desarrollo de informes genéticos comprensibles para médicos y pacientes. Este enfoque innovador ha sido ampliamente adoptado por laboratorios líderes en Estados Unidos y en el extranjero.",
    "secTechTitle": "Tecnología e infraestructura",
    "secTechP1": "De 2001 a 2019, el Sr. Kofman dirigió la estrategia tecnológica de programas gubernamentales, de defensa y de empresas estatales — incluidas iniciativas técnicas complejas para compañías de propiedad estatal. Tras el 11 de septiembre de 2001, lideró proyectos gubernamentales a gran escala centrados en big data, infraestructura segura y centros de datos de alto rendimiento en Estados Unidos y Europa.",
    "secTechP2": "En 2006, el Sr. Kofman fundó XIBI Group Inc. — empresa tecnológica en cuya junta directiva sirvió. La compañía estadounidense se especializa en almacenamiento de datos y servicios de gestión de big data para grandes organizaciones comerciales y gubernamentales.",
    "secTechP3": "De 2000 a 2004, el Sr. Kofman dirigió DataPeer Inc. — empresa de gestión y almacenamiento de datos que ofrecía una amplia gama de servicios de almacenamiento de información para pequeñas y medianas empresas. En DataPeer desarrolló soluciones tecnológicas únicas que facilitaron un seguimiento más rápido de la información y un acceso más sencillo a los datos para usuarios finales e instituciones gubernamentales en todo el mundo.",
    "secTechP4": "En 1996, el Sr. Kofman fundó 9 Net Avenue Inc., que rápidamente se convirtió en una de las mayores empresas de hosting del mundo. En 2000, 9 Net Avenue fue adquirida por Concentric Networks (NASDAQ: CNTX) y posteriormente por XO Communications (NASDAQ: XOXO), alcanzando un valor de mercado máximo de 19,5 mil millones de dólares.",
    "secPost9NetP1": "Tras la adquisición de 9 Net Avenue, el Sr. Kofman adquirió una amplia experiencia trabajando en empresas públicas, participando en juntas directivas y tomando decisiones estratégicas al más alto nivel ejecutivo.",
    "secEarlyTitle": "Primeros años y ingeniería",
    "secEarlyP1": "De 1994 a 1996, el Sr. Kofman fue CEO y Director de Tecnología de la Información en Elitan United Inc. — empresa de TI de Massachusetts que ofrecía estrategias integrales y servicios tecnológicos a organizaciones globales líderes. Desempeñó un papel fundamental en el desarrollo y gestión de infraestructura escalable, llevando el crecimiento de la empresa de solo nueve a más de 4.000 empleados en todo el mundo.",
    "secEarlyP2": "De 1989 a 1994, fue fundador y CEO de Astra Corp, uno de los mayores fabricantes europeos de sistemas satelitales de transcepción digital, con reconocimiento internacional en el campo de dispositivos satelitales. Sus responsabilidades abarcaban investigación, desarrollo de sistemas operativos, aplicaciones de software de red y estrategia técnica general.",
    "secEarlyP3": "De 1984 a 1989, el Sr. Kofman trabajó en el astillero de Nikolaev, Ucrania, donde participó activamente en el desarrollo y creación de sistemas satelitales de transcepción para transmitir información clasificada a buques militares y de regreso. Fue reconocido como ingeniero electrónico del más alto nivel, recibiendo la 6.ª categoría — la máxima distinción en el astillero, donde trabajaban 93 mil personas.",
    "secResearchTitle": "Investigación y patentes",
    "secResearchP1": "Michael Kofman es autor de trabajos técnicos sobre sistemas satelitales y ópticos de transmisión de datos. También obtuvo una patente en el campo de sistemas de televisión de alta definición (HDTV) por satélite digital, posteriormente adquirida por Sony."
  },
  "ventures": {
    "eyebrow": "Portafolio de empresas",
    "title": "Construyendo empresas que transforman industrias",
    "lead": "De la medicina de precisión a las telecomunicaciones globales.",
    "v1year": "2021 — Actual",
    "v1role": "Fundador y CEO · Miembro del consejo",
    "v1p1": "Fundó y escaló Digital Invest desde su inicio hasta una exitosa salida a bolsa. La empresa está dedicada a la esfera biomatemática, transformando la medicina mediante IA, ML y tecnologías de ADN.",
    "v1highlight": "Top 10 empresa de medicina de precisión en EE. UU. — 2023",
    "v2year": "2008 — 2014",
    "v2role": "CEO y CTO",
    "v2p1": "Pruebas y análisis de ADN, automatización de perfiles genéticos e investigación genética humana integral. Inició proyectos de pruebas genéticas en Ucrania, Rusia y los países bálticos.",
    "v2p2": "Colaboró con Harvard Medical School y Stanford Biomath en informes genéticos adoptados por laboratorios líderes en todo el mundo.",
    "v2highlight": "Socio de Harvard Medical School y Stanford Biomath",
    "v3year": "2006 — 2011",
    "v3role": "Fundador y CEO · Consejo de administración",
    "v3p1": "Almacenamiento de datos y servicios de gestión de big data para grandes organizaciones comerciales y gubernamentales. Estableció la empresa como proveedor de confianza de soluciones de datos empresariales.",
    "v3highlight": "Soluciones de datos empresariales y gubernamentales",
    "v4year": "2000 — 2004",
    "v4role": "Fundador y CEO",
    "v4p1": "Gestión y almacenamiento de datos para pequeñas y medianas empresas. Desarrolló soluciones para un seguimiento más rápido de la información y un acceso más sencillo a los datos para usuarios finales e instituciones gubernamentales en todo el mundo.",
    "v4highlight": "Plataforma global de gestión de datos",
    "v5year": "1996 — 2000",
    "v5role": "Fundador y CEO",
    "v5p1": "Construyó una de las mayores empresas de hosting del mundo. En 2000, adquirida por Concentric Networks (NASDAQ: CNTX) y luego por XO Communications (NASDAQ: XOXO), alcanzando un valor de mercado máximo de 19,5 mil millones de dólares.",
    "v5highlight": "Adquirida · Valor máximo de 19,5 mil millones de dólares",
    "v6year": "1994 — 1996",
    "v6role": "CEO y Director de Tecnología de la Información",
    "v6p1": "Empresa de TI de Massachusetts que ofrecía estrategias integrales y servicios tecnológicos a organizaciones globales líderes. Lideró el desarrollo de infraestructura escalable y operaciones de TI globales.",
    "v6highlight": "Estrategia de TI e infraestructura global",
    "v7year": "1989 — 1994",
    "v7role": "Fundador y CEO",
    "v7p1": "Uno de los mayores fabricantes europeos de sistemas satelitales de transcepción digital. Lideró investigación, desarrollo de sistemas operativos, aplicaciones de software de red y estrategia técnica general.",
    "v7highlight": "Líder europeo en sistemas satelitales",
    "v8year": "1984 — 1989",
    "v8role": "Ingeniero electrónico · Categoría máxima (6.ª)",
    "v8p1": "Desarrollo y creación de sistemas satelitales de transcepción para transmitir información clasificada a buques militares. Reconocido como ingeniero electrónico del más alto nivel en un astillero de 93.000 empleados.",
    "v8highlight": "Ingeniería de sistemas satelitales militares"
  },
  "career": {
    "eyebrow": "Trayectoria profesional",
    "title": "Tres décadas de liderazgo ejecutivo",
    "lead": "Desde ingeniería satelital hasta empresas tecnológicas globales.",
    "timelineEyebrow": "Línea de tiempo",
    "timelineTitle": "Hitos clave",
    "strengthsEyebrow": "Fortalezas",
    "strengthsTitle": "Áreas de experiencia",
    "t1year": "2021 — Actual",
    "t1title": "Digital Invest Inc.",
    "t1role": "Fundador y CEO",
    "t1desc": "Fundó y escaló la empresa desde su inicio hasta una exitosa salida a bolsa. Lideró todo el proceso de oferta pública — estructuración legal, cumplimiento financiero, roadshows con inversores y coordinación con la SEC. Dirigió el diseño, construcción y operación de múltiples centros de datos en EE. UU. y Europa. Construyó sistemas de software empresariales para automatización, monitorización predictiva y control centralizado de datos. Logró un crecimiento financiero constante, posicionando la empresa entre las 10 mejores de medicina de precisión en EE. UU. (2023).",
    "t2year": "2001 — 2019",
    "t2title": "GovTech, defensa y programas estatales",
    "t2role": "Asesor tecnológico principal / Arquitecto de programas",
    "t2desc": "Dirigió la estrategia y ejecución tecnológica de programas clasificados y de alta sensibilidad con agencias gubernamentales de EE. UU., sistemas de defensa aliados y empresas estatales. Encabezó proyectos técnicos complejos para empresas de propiedad estatal en múltiples sectores. Tras el 11 de septiembre de 2001, lideró iniciativas gubernamentales a gran escala centradas en big data, comunicaciones seguras, analítica predictiva e integración de datos a nivel nacional — incluido el diseño, construcción y operación de centros de datos de alto rendimiento en Estados Unidos y Europa. Interactuó con oficiales de programas militares, proveedores tecnológicos y entidades reguladoras.",
    "t3year": "2008 — 2014",
    "t3title": "Biotechnology Group Inc.",
    "t3role": "CEO y CTO",
    "t3desc": "Lideró pruebas y análisis de ADN, automatización de perfiles genéticos e investigación genética humana integral. Inició proyectos de pruebas genéticas en Ucrania, Rusia y los países bálticos. Colaboró con Harvard Medical School y Stanford Biomath para desarrollar informes genéticos comprensibles adoptados por laboratorios líderes en todo el mundo.",
    "t4year": "2000 — 2012",
    "t4title": "Proyectos de telecomunicaciones",
    "t4role": "VP de Tecnología / CTO regional — Europa del Este y CEI",
    "t4desc": "Dirigió despliegues de infraestructura nacional en Canadá, Italia, Suiza, Ucrania y las repúblicas bálticas. Supervisó a más de 1.000 ingenieros y personal de despliegue en operaciones de telecomunicaciones, incluidos sistemas de conmutación, expansión de banda ancha y conectividad transfronteriza. Implementó sistemas centrales de redundancia de red, optimización de disponibilidad y enrutamiento inteligente.",
    "t5year": "2006 — 2011",
    "t5title": "XIBI Group Inc.",
    "t5role": "Fundador y CEO · Consejo de administración",
    "t5desc": "Fundó una empresa tecnológica especializada en almacenamiento de datos y gestión de big data para grandes organizaciones comerciales y gubernamentales. Estableció la empresa como proveedor de confianza de soluciones de datos empresariales.",
    "t6year": "2000 — 2004",
    "t6title": "DataPeer Inc.",
    "t6role": "Fundador y CEO",
    "t6desc": "Estableció una empresa de gestión y almacenamiento de datos para pymes. Desarrolló soluciones tecnológicas únicas para un seguimiento más rápido de la información y un acceso más sencillo a los datos para usuarios finales e instituciones gubernamentales en todo el mundo.",
    "t7year": "1996 — 2000",
    "t7title": "9 Net Avenue Inc.",
    "t7role": "Fundador y CEO",
    "t7desc": "Construyó una de las mayores empresas de hosting del mundo. En 2000, adquirida por Concentric Networks (NASDAQ: CNTX) y luego por XO Communications (NASDAQ: XOXO), alcanzando un valor de mercado máximo de 19,5 mil millones de dólares.",
    "t8year": "1994 — 1996",
    "t8title": "Elitan United Inc.",
    "t8role": "CEO y Director de Tecnología de la Información",
    "t8desc": "Lideró estrategias integrales de TI y servicios tecnológicos para organizaciones globales líderes desde Massachusetts en un período de rápida expansión, construyendo infraestructura escalable y operaciones de TI globales.",
    "t9year": "1989 — 1994",
    "t9title": "Astra Corp",
    "t9role": "Fundador y CEO",
    "t9desc": "Fundó uno de los mayores fabricantes europeos de sistemas satelitales de transcepción digital. Lideró investigación, desarrollo de sistemas operativos, aplicaciones de software de red y estrategia técnica general, obteniendo reconocimiento internacional.",
    "t10year": "1984 — 1989",
    "t10title": "Astillero de Nikolaev",
    "t10role": "Ingeniero electrónico — 6.ª categoría (máxima)",
    "t10desc": "Desarrolló y creó sistemas satelitales de transcepción para transmitir información clasificada a buques militares. Reconocido como ingeniero electrónico del más alto nivel en un astillero de 93.000 empleados — el inicio de una distinguida carrera en tecnología e innovación.",
    "s1title": "Liderazgo ejecutivo",
    "s1desc": "Gestión dual CEO/CTO en empresas públicas y privadas, desde startup hasta IPO y más allá.",
    "s2title": "IPO y escalado financiero",
    "s2desc": "Ejecución integral de ofertas públicas — estructuración legal, coordinación con la SEC, roadshows con inversores y cumplimiento normativo.",
    "s3title": "Arquitectura de plataformas",
    "s3desc": "Diseño de sistemas escalables para automatización empresarial, monitorización predictiva y control centralizado de datos.",
    "s4title": "Infraestructura segura",
    "s4desc": "Desarrollo y operación de centros de datos para plataformas gubernamentales, militares y comerciales de alta seguridad."
  },
  "recognition": {
    "eyebrow": "Premios y honores",
    "title": "Reconocimiento de excelencia",
    "lead": "Décadas de logros excepcionales en innovación y liderazgo.",
    "industryEyebrow": "Premios del sector",
    "industryTitle": "Grandes honores",
    "ipEyebrow": "Propiedad intelectual",
    "ipTitle": "Patentes y publicaciones",
    "eduEyebrow": "Educación",
    "eduTitle": "Credenciales académicas",
    "pressEyebrow": "Prensa",
    "pressTitle": "Destacado en",
    "moreLink": "Ver patentes, publicaciones y notas de prensa en Insights →",
    "a1title": "Emprendedor del año",
    "a1desc": "Entrepreneur Magazine, 1999 — 2001 — liderazgo y logros innovadores en plataformas e infraestructura.",
    "a2title": "Top 10 empresa de medicina de precisión en EE. UU.",
    "a2desc": "Digital Invest Inc. reconocida entre las 10 mejores empresas de medicina de precisión y salud digital de América — 2023.",
    "a3title": "Who's Who in America",
    "a3desc": "Incluido, 1999 — 2018 — por logros excepcionales en creación y desarrollo empresarial.",
    "a4title": "Who's Who in the World",
    "a4desc": "Incluido, 2000 — 2004 — entre líderes globales en ciencia, ingeniería e innovación empresarial.",
    "a5title": "Who's Who in Science & Engineering",
    "a5desc": "Incluido, 2000 — 2014 — por contribuciones a la tecnología, sistemas satelitales e infraestructura digital.",
    "a6title": "Ingeniero electrónico — 6.ª categoría",
    "a6desc": "Máximo reconocimiento en el Astillero de Nikolaev (93.000 empleados) por ingeniería de sistemas satelitales de transcepción.",
    "ip1year": "Patente",
    "ip1title": "Sistemas HDTV satelitales digitales",
    "ip1role": "Posteriormente adquirida por Sony",
    "ip1desc": "Obtuvo una patente en el campo de sistemas de televisión de alta definición (HDTV) por satélite digital. La patente fue posteriormente adquirida por Sony Corporation, validando la importancia comercial de la innovación.",
    "ip2year": "Publicaciones",
    "ip2title": "Trabajos técnicos",
    "ip2role": "Sistemas satelitales y ópticos",
    "ip2desc": "Autor de trabajos técnicos sobre sistemas satelitales y ópticos de transmisión de datos. Sus contribuciones abarcan procesamiento de señales, modelado de simulación y plataformas de automatización aplicadas en telecomunicaciones, infraestructura nacional y salud digital.",
    "ip3year": "Investigación",
    "ip3title": "Colaboraciones internacionales",
    "ip3role": "EE. UU. y Europa",
    "ip3desc": "Participó en colaboraciones de investigación internacional e iniciativas de transferencia de conocimiento. Desarrolló sistemas de ingeniería embebidos para adquisición de datos, diagnósticos predictivos y orquestación en la nube en múltiples industrias.",
    "edu1title": "Doctor en Ciencias Técnicas",
    "edu1desc": "2009 — Universidad Estatal Técnica Marina de Ucrania",
    "edu2title": "Doctorado en Tecnologías de la Información",
    "edu2desc": "2004 — Universidad Estatal Técnica Marina de Ucrania",
    "edu3title": "Maestrías",
    "edu3desc": "Electrónica, sistemas satelitales digitales y economía",
    "press1title": "Healthcare Tech Outlook",
    "press1role": "Reportaje sobre Digital Invest Inc.",
    "press1desc": "Digital Invest Inc. destacada como una de las empresas líderes de América en medicina de precisión y salud digital, reconocida por enfoques innovadores para transformar la medicina mediante IA, ML y tecnologías de ADN.",
    "press1link": "Leer reportaje →",
    "press2title": "Top Precision Medicine Solutions",
    "press2role": "Reconocimiento del sector",
    "press2desc": "Nombrada entre las principales empresas de soluciones de medicina de precisión, destacando el papel de Digital Invest en el avance de enfoques biomatemáticos en la atención sanitaria moderna.",
    "press2link": "Ver listado →"
  },
  "contact": {
    "eyebrow": "Póngase en contacto",
    "title": "Conectemos",
    "lead": "Para roles de asesoría, juntas directivas y alianzas estratégicas.",
    "infoTitle": "Contacto directo",
    "email": "Correo",
    "phone": "Teléfono",
    "location": "Ubicación",
    "locationVal": "Charlotte, North Carolina\nUnited States",
    "linkedin": "LinkedIn",
    "company": "Empresa actual",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member",
    "formTitle": "Enviar mensaje",
    "formLead": "Complete el formulario y le responderé pronto.",
    "firstName": "Nombre",
    "lastName": "Apellido",
    "emailLabel": "Correo electrónico",
    "subject": "Asunto",
    "message": "Mensaje",
    "inquiryType": "Inquiry Type",
    "inquiryAdvisory": "Advisory / Board Role",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "infoEyebrow": "Información de contacto"
  },
  "consulting": {
    "eyebrow": "Servicios de asesoría",
    "title": "Consultoría",
    "heroEyebrow": "Orientación empresarial estratégica",
    "heroTitle": "Consultoría experta con Michael Kofman",
    "heroLead": "Michael Kofman es un visionario tecnológico reconocido por su enfoque dinámico para comprender las necesidades en constante evolución del complejo mercado actual. Emprendedor, miembro de juntas directivas y asesor de empresas públicas y privadas, ha fundado con éxito varias compañías en Estados Unidos y Europa.",
    "cta": "Contactar a Michael Kofman",
    "introLead": "Michael Kofman es CEO de Digital Invest Inc. y miembro de su Consejo de Administración. Su experiencia abarca liderazgo ejecutivo, análisis estratégico de tecnologías y mercados emergentes, seguridad de la información y privacidad, investigación, ciencia y desarrollo, administración e inversión.",
    "specialtiesEyebrow": "Áreas de enfoque",
    "specialtiesTitle": "En qué se especializa Michael Kofman"
  },
  "insights": {
    "eyebrow": "Liderazgo de pensamiento",
    "title": "Perspectivas",
    "heroTitle": "Perspectivas para el éxito",
    "selectedEyebrow": "Destacados seleccionados",
    "selectedTitle": "Reconocimiento destacado",
    "allPressTitle": "Todas las apariciones en prensa",
    "quotesEyebrow": "En los medios",
    "quotesTitle": "Reconocimiento del sector y citas",
    "articlesEyebrow": "Perspectivas",
    "articlesTitle": "Perspectivas ejecutivas"
  },
  "cta": {
    "eyebrow": "Trabajemos juntos",
    "title": "Solicitar asesoría o una conferencia",
    "lead": "Para funciones de asesoría, puestos en juntas directivas, conferencias y alianzas estratégicas.",
    "button": "Póngase en contacto"
  },
  "speaking": {
    "eyebrow": "Conferencias",
    "title": "Invite a Michael Kofman a su evento",
    "lead": "Disponible para conferencias sobre liderazgo ejecutivo, estrategia tecnológica, salud digital, infraestructura de datos y gobierno corporativo.",
    "topicsEyebrow": "Temas de conferencia",
    "topicsTitle": "Áreas de experiencia",
    "topicsLead": "Los temas se basan en décadas de experiencia fundando y dirigiendo empresas en Estados Unidos y Europa.",
    "processEyebrow": "Cómo invitar",
    "processTitle": "Proceso de contratación",
    "process1title": "Envíe una solicitud",
    "process1desc": "Use el formulario de contacto o escriba a mkofman@mkofman.com con los detalles del evento, la audiencia y los temas preferidos.",
    "process2title": "Confirme el alcance",
    "process2desc": "Defina el formato (ponencia principal, panel, sesión de junta o mesa redonda ejecutiva) y la logística.",
    "process3title": "Genere impacto",
    "process3desc": "Las presentaciones se basan en resultados reales de iniciativas en almacenamiento de datos, govtech y medicina de precisión.",
    "cta": "Solicitar una conferencia"
  },
  "caseStudies": {
    "eyebrow": "Casos de estudio",
    "title": "Construyendo empresas que escalan",
    "lead": "Resultados seleccionados de la fundación y dirección de empresas en infraestructura de datos y salud digital.",
    "cs1eyebrow": "Infraestructura de datos · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "Desafío",
    "cs1challengeText": "Construir y escalar una empresa de almacenamiento de datos en un mercado tecnológico en rápida consolidación.",
    "cs1action": "Enfoque",
    "cs1actionText": "Fundé 9 Net Avenue Inc. en 1996. La empresa se convirtió rápidamente en una de las mayores compañías de almacenamiento de datos del mundo.",
    "cs1result": "Resultado",
    "cs1resultText": "En 2000 fue adquirida por Concentric Networks (NASDAQ: CNTX) y luego por XO Communications (NASDAQ: XOXO), alcanzando una capitalización máxima de mercado de 19.500 millones de dólares. Tras la adquisición, adquirí amplia experiencia con empresas cotizadas, consejos de administración y decisiones estratégicas de alto nivel.",
    "cs2eyebrow": "Salud digital · 2021 — Presente",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "Desafío",
    "cs2challengeText": "Transformar enfoques médicos obsoletos mediante ciencia, tecnologías de ADN, IA y ML a través de una nueva plataforma bio-matemática.",
    "cs2action": "Enfoque",
    "cs2actionText": "Fundé y escalé Digital Invest Inc. desde su inicio hasta una salida a bolsa exitosa. Dirigí todo el proceso de oferta pública: estructuración legal, cumplimiento financiero, roadshows con inversores y coordinación con la SEC. También dirigí el diseño, la construcción y la operación de múltiples centros de datos en EE. UU. y Europa.",
    "cs2result": "Resultado",
    "cs2resultText": "Logramos un crecimiento financiero sostenido y posicionamos a la empresa entre las 10 principales compañías de medicina de precisión de EE. UU. (2023). Digital Invest integra proyectos innovadores como Human Digital Model, BioMath Life y Aero-Ground Robotics Operations Network."
  },
  "mediaKit": {
    "eyebrow": "Prensa y eventos",
    "title": "Kit de prensa",
    "lead": "Biografías oficiales, material visual y datos de contacto para prensa, conferencias y consultas de juntas directivas.",
    "bioEyebrow": "Biografías",
    "bioTitle": "Biografías oficiales",
    "bioShortLabel": "50 palabras",
    "bioShort": "Michael Kofman es CEO de Digital Invest Inc. y miembro de consejos, asesor y fundador de empresas de tecnología y salud digital en EE. UU. y Europa.",
    "bioMediumLabel": "150 palabras",
    "bioMedium": "Michael Kofman es CEO de Digital Invest Inc. y forma parte de su consejo de administración. Visionario tecnológico, es reconocido por su enfoque dinámico para comprender las necesidades cambiantes del mercado actual. Como emprendedor, miembro de consejos y asesor de empresas públicas y privadas, ha fundado con éxito varias compañías en Estados Unidos y Europa. Su experiencia abarca liderazgo ejecutivo, análisis estratégico de tecnologías y mercados emergentes, seguridad y privacidad de la información, investigación, ciencia y desarrollo, administración e inversión.",
    "bioLongLabel": "500 palabras",
    "bioLong": "Michael Kofman es CEO de Digital Invest Inc. y forma parte de su consejo de administración. Visionario tecnológico, es reconocido por su enfoque dinámico para comprender las necesidades cambiantes del mercado actual. Su experiencia abarca liderazgo ejecutivo, análisis estratégico de tecnologías y mercados emergentes, seguridad y privacidad de la información, investigación, ciencia y desarrollo, administración e inversión. Como emprendedor, consejero y asesor de empresas públicas y privadas, Michael Kofman ha fundado con éxito varias compañías en Estados Unidos y Europa. Fundó 9 Net Avenue Inc., adquirida con una capitalización máxima de mercado de 19.500 millones de dólares, y lidera Digital Invest Inc. en almacenamiento de datos e innovación tecnológica avanzada. Ha dirigido estrategia tecnológica para programas gubernamentales y de defensa, fundó XIBI Group Inc. y DataPeer Inc. en el ámbito del almacenamiento de datos, y desempeñó un papel clave en Biotechnology Group Inc. Colaboró con Harvard Medical School y Stanford Biomath en reportes genéticos. Es autor de artículos técnicos sobre sistemas satelitales y ópticos; su patente de HDTV satelital digital fue adquirida por Sony. Formación: Doctor en Ciencias Técnicas (2009), Ph.D. en Tecnología de la Información (2004), Universidad Estatal Marítima Técnica de Ucrania.",
    "photosEyebrow": "Fotografía",
    "photosTitle": "Imágenes aprobadas",
    "photosLead": "Retratos en alta resolución disponibles previa solicitud en mkofman@mkofman.com.",
    "contactEyebrow": "Contacto de prensa",
    "contactTitle": "Consultas de medios",
    "contactLead": "Para entrevistas, invitaciones a conferencias y solicitudes de prensa."
  },
  "articles": {
    "backLink": "← Volver a Insights",
    "article1date": "Perspectiva ejecutiva",
    "article1title": "De la ingeniería a la infraestructura global de datos",
    "article1p1": "Mi carrera comenzó en la planta de construcción naval de Nikolaev, en Ucrania, desarrollando sistemas transceptores satelitales para transmitir información clasificada a buques militares. Fui reconocido como ingeniero electrónico del más alto nivel: la 6.ª categoría en una planta de 93.000 empleados.",
    "article1p2": "Entre 1989 y 1994 fundé y dirigí Astra Corp, uno de los mayores fabricantes europeos de sistemas satelitales transceptores digitales. De 1994 a 1996, como CEO de Elitan United Inc., ayudé a escalar la empresa de nueve a más de 4.000 empleados en todo el mundo.",
    "article1p3": "En 1996 fundé 9 Net Avenue Inc., que rápidamente se convirtió en una de las mayores compañías de almacenamiento de datos del mundo. En 2000 fue adquirida por Concentric Networks (NASDAQ: CNTX) y XO Communications (NASDAQ: XOXO), alcanzando una capitalización máxima de mercado de 19.500 millones de dólares.",
    "article1p4": "De 2001 a 2019 dirigí la estrategia tecnológica para programas gubernamentales, de defensa y de empresas estatales, liderando iniciativas de gran escala en big data, infraestructura segura y centros de datos de alto rendimiento en Estados Unidos y Europa.",
    "article2date": "Salud digital",
    "article2title": "Medicina de precisión y convergencia entre ciencia y tecnología",
    "article2p1": "Creo firmemente en el potencial de combinar las ciencias de la vida con los últimos avances tecnológicos. En Biotechnology Group Inc. (2008-2014), nos enfocamos en pruebas y análisis de ADN, automatización de procesos para crear perfiles genéticos e investigación genética humana integral.",
    "article2p2": "Bajo mi liderazgo, se iniciaron proyectos exitosos de pruebas genéticas en Ucrania, Rusia y los países bálticos. En colaboración con Harvard Medical School y Stanford Biomath, desempeñé un papel clave en el desarrollo de reportes genéticos fáciles de comprender para médicos y pacientes.",
    "article2p3": "Con Digital Invest Inc., fundada en 2021, nos dedicamos al ámbito bio-matemático, transformando enfoques médicos obsoletos mediante ciencia, tecnologías de ADN, IA y ML. La empresa se escaló desde su inicio hasta una salida a bolsa exitosa y fue reconocida entre las 10 mejores compañías de EE. UU. en medicina de precisión y salud digital en 2023.",
    "article2p4": "Digital Invest integra diversos proyectos innovadores, incluidos Human Digital Model, BioMath Life y Aero-Ground Robotics Operations Network, cada uno impulsando la integración de la ciencia de datos y las ciencias de la vida."
  }
};
