window.__LANG_fr = {
  "ui": {
    "toggleTheme": "Changer le thème clair/sombre",
    "selectLanguage": "Choisir la langue",
    "messageSent": "Message envoyé",
    "sendMessage": "Envoyer",
    "toggleNav": "Ouvrir le menu",
    "sending": "Envoi en cours…",
    "formError": "Envoi impossible. Merci d'envoyer un e-mail directement.",
    "present": "Aujourd'hui"
  },
  "nav": {
    "home": "Accueil",
    "about": "Biographie",
    "ventures": "Entreprises",
    "career": "Le parcours",
    "recognition": "Distinctions",
    "contact": "Contacter",
    "consulting": "Conseil",
    "insights": "Perspectives",
    "speaking": "Interventions",
    "caseStudies": "Études de cas",
    "mediaKit": "Kit média",
    "groupMain": "Principal",
    "groupServices": "Prestations",
    "groupWork": "Réalisations",
    "briefIpo": "Note : IPO",
    "briefGenetic": "Brief : données génétiques",
    "briefAi": "Brief : stratégie IA",
    "articleInfra": "Infrastructure de données",
    "articleHealth": "Médecine de précision",
    "board": "Conseil",
    "thesis": "Thèse de leadership",
    "press": "Presse",
    "ip": "Propriété intellectuelle"
  },
  "footer": {
    "navigation": "Menu",
    "ventures": "Entreprises",
    "connect": "Contact",
    "desc": "Dirigeant technologique, fondateur et conseiller de conseils d'administration.",
    "copyright": "© {year} Michael Kofman. Tous droits réservés.",
    "writeTitle": "Écrivez-moi",
    "writeEmail": "Votre email",
    "writeMessage": "Votre message",
    "writeSend": "Envoyer",
    "writeSuccess": "Merci — votre message a été envoyé.",
    "more": "Plus",
    "privacy": "Confidentialité"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — Dirigeant technologique",
      "description": "Dirigeant technologique, fondateur et conseiller — infrastructure, sciences de la vie et systèmes autonomes."
    },
    "about": {
      "title": "Biographie — Michael Kofman",
      "description": "Biographie de Michael Kofman — PDG de Digital Invest Inc., fondateur d'AGRON Inc."
    },
    "ventures": {
      "title": "Entreprises — Michael Kofman",
      "description": "Entreprises fondées et dirigées par Michael Kofman — de Digital Invest Inc. à 9 Net Avenue Inc. — bâtissant des entreprises transformatrices en technologie et santé."
    },
    "career": {
      "title": "Le parcours — Michael Kofman",
      "description": "Parcours professionnel en ingénierie, infrastructure, marchés publics, sciences de la vie et systèmes autonomes."
    },
    "recognition": {
      "title": "Distinctions — Michael Kofman",
      "description": "Prix, distinctions et reconnaissances de Michael Kofman — Entrepreneur de l'année, Who's Who, brevets et distinctions sectorielles."
    },
    "contact": {
      "title": "Contacter — Michael Kofman",
      "description": "Contacter Michael Kofman — PDG de Digital Invest Inc. Pour conférences, mandats de conseil et demandes commerciales."
    },
    "consulting": {
      "title": "Conseil — Michael Kofman",
      "description": "Mandats de conseil, postes au conseil d'administration, conférences et partenariats stratégiques avec Michael Kofman."
    },
    "insights": {
      "title": "Perspectives — Michael Kofman",
      "description": "Écrits originaux et briefs exécutifs de Michael Kofman."
    },
    "speaking": {
      "title": "Interventions — Michael Kofman",
      "description": "Invitez Michael Kofman à intervenir sur le leadership exécutif, la stratégie technologique, la santé numérique et la gouvernance d'entreprise."
    },
    "caseStudies": {
      "title": "Études de cas — Michael Kofman",
      "description": "Études de cas issues de la carrière de Michael Kofman : 9 Net Avenue Inc. et Digital Invest Inc."
    },
    "mediaKit": {
      "title": "Kit média — Michael Kofman",
      "description": "Biographies officielles, photos et informations de contact pour la presse et les organisateurs d'événements."
    },
    "article1": {
      "title": "De l'ingénierie à l'infrastructure mondiale — Michael Kofman",
      "description": "Michael Kofman revient sur son parcours, de l'ingénierie satellitaire à la création d'entreprises mondiales d'infrastructure de données."
    },
    "article2": {
      "title": "Médecine de précision et technologie — Michael Kofman",
      "description": "Michael Kofman sur la convergence des sciences de la vie avec l'IA, le ML et les technologies ADN dans la médecine moderne."
    },
    "privacy": {
      "title": "Politique de confidentialité — Michael Kofman",
      "description": "Politique de confidentialité de mkofman.com — formulaires et analytique."
    },
    "board": {
      "title": "Conseil — Michael Kofman",
      "description": "Conversations de conseil stratégique avec organisations technologiques, de santé et d'infrastructure."
    },
    "thesis": {
      "title": "Thèse de leadership — Michael Kofman",
      "description": "Principes de Michael Kofman pour bâtir des entreprises durables, gouverner la technologie et diriger des changements majeurs."
    },
    "press": {
      "title": "Archives presse — Michael Kofman",
      "description": "Couverture presse, prix et références médias sélectionnés de la carrière de Michael Kofman en technologie et entrepreneuriat."
    },
    "ip": {
      "title": "Propriété intellectuelle — Michael Kofman",
      "description": "Brevets, publications et recherche appliquée de Michael Kofman en informatique, communications, données et santé numérique."
    },
    "briefIpo": {
      "title": "Ce qu'un IPO change — Michael Kofman",
      "description": "Note exécutive sur la discipline opérationnelle, la gouvernance et la responsabilité avant et après une introduction en bourse."
    },
    "briefGenetic": {
      "title": "Des données génétiques aux décisions cliniques — Michael Kofman",
      "description": "Note exécutive sur la traduction de l'information génomique en intelligence clinique responsable, utile et scalable."
    },
    "briefAi": {
      "title": "Stratégie IA au-delà du pilote — Michael Kofman",
      "description": "Note exécutive sur le passage de l'expérimentation IA à une capacité d'entreprise gouvernée et mesurable."
    },
    "deck": {
      "title": "Aperçu exécutif — Michael Kofman",
      "description": "Aperçu exécutif privé pour introductions qualifiées."
    }
  },
  "home": {
    "heroEyebrow": "Site officiel de Michael Kofman",
    "heroTitle1": "Construit pour durer.",
    "heroTitle2": "Dirigé avec discernement.",
    "heroCta": "Découvrir mon parcours",
    "heroAlt": "Michael Kofman",
    "quote1text": "Figurant parmi les principales entreprises américaines en médecine de précision et santé numérique.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "Entrepreneur de l'année — reconnu pour son leadership et ses réalisations en innovation de plateformes et infrastructure.",
    "quote2author": "Entrepreneur Magazine · 2001",
    "quote3text": "Digital Invest Inc. parmi les 10 meilleures entreprises américaines en médecine de précision et santé numérique.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "Précision d'ingénierie et stratégie commerciale — des systèmes satellites à une infrastructure de",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "Michael Kofman",
    "aboutTitle": "Des entreprises faites pour durer",
    "aboutLead1": "PDG de Digital Invest Inc. et fondateur d'AGRON Inc. Il a fondé et dirigé des entreprises aux États-Unis et en Europe.",
    "aboutLead2": "De 9 Net Avenue (valorisation pic de",
    "aboutLink": "Biographie complète",
    "expertiseEyebrow": "Domaines d'intervention",
    "expertiseTitle": "Leadership exécutif",
    "expertiseLead": "Quatre décennies de création, de conseil et d'investissement dans l'infrastructure, la santé et la robotique.",
    "exp1title": "PDG & fondateur",
    "exp1desc": "A fondé et dirigé plusieurs entreprises technologiques aux États-Unis et en Europe.",
    "exp1link": "Entreprises →",
    "exp2title": "Architecte technologique",
    "exp2desc": "A conçu des communications sécurisées, des moteurs d'analyse prédictive et des plateformes d'intégration de données à l'échelle nationale pour les secteurs gouvernemental, militaire et télécom.",
    "exp2link": "Carrière →",
    "exp3title": "Santé numérique",
    "exp3desc": "Dirige la transformation de la médecine grâce à l'IA, au ML et aux technologies ADN. A collaboré avec Harvard Medical School et Stanford Biomath sur les rapports génétiques.",
    "exp3link": "Digital Invest →",
    "exp4title": "Conseiller du conseil",
    "exp4desc": "Siège au conseil d'administration et conseille des entreprises publiques et privées sur l'orientation stratégique, la gouvernance et la croissance portée par la technologie.",
    "exp4link": "Conseil →",
    "stat1": "Années de leadership",
    "stat2": "Entreprises fondées",
    "stat3": "Valeur de marché max.",
    "stat4": "Employés",
    "recEyebrow": "Distinctions",
    "recTitle": "Distinctions sélectionnées",
    "recLead": "Honneurs documentés et références sectorielles issues des archives.",
    "award1title": "Entrepreneur de l'année",
    "award1desc": "Entrepreneur Magazine · 2001",
    "award2title": "Reconnaissance en médecine de précision",
    "award2desc": "Healthcare Tech Outlook · Digital Invest Inc. · 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "Distinctions et presse →",
    "heroSub": "Technologie, business et investissement dans l'infrastructure, les sciences de la vie et les systèmes autonomes.",
    "primaryCta": "Demander un accompagnement",
    "secondaryCta": "Voir les études de cas",
    "featuredEyebrow": "Des archives",
    "caseStudiesEyebrow": "Résultats prouvés",
    "caseStudiesTitle": "Études de cas",
    "caseStudiesLead": "Créer, développer et diriger des entreprises de leur lancement jusqu'à l'acquisition et l'IPO.",
    "caseStudiesLink": "Voir toutes les études de cas →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "A construit l'une des plus grandes sociétés mondiales de Data Storage, acquise avec une capitalisation boursière maximale de 19,5 milliards de dollars.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "Fondée et développée de sa création jusqu'à l'IPO : Top 10 des entreprises américaines de médecine de précision en 2023.",
    "cs3title": "AGRON Inc.",
    "cs3desc": "Founded in 2026 — the AGRON Ecosystem for UAV capability development, geospatial systems, and maritime intelligence.",
    "boardCtaEyebrow": "Advisory",
    "boardCtaTitle": "Experience for the Decisions That Define an Enterprise",
    "boardCtaLead": "Independent perspective for boards and leaders navigating technology, governance, transformation, and growth.",
    "boardCtaBtn": "Explore Advisory",
    "testimonialsEyebrow": "Trusted Perspective",
    "testimonialsTitle": "What Colleagues Value",
    "videoEyebrow": "Executive Perspective",
    "videoTitle": "Leadership at the Intersection of Technology and Enterprise",
    "videoLead": "A concise introduction to the principles, experience, and long-term perspective behind Michael Kofman's work.",
    "videoCta": "Read Leadership Thesis →",
    "heroName": "Michael Kofman",
    "heroRole": "Dirigeant technologique · Fondateur · Conseiller",
    "introText": "Michael Kofman est dirigeant technologique et fondateur d'entreprises. Son parcours couvre l'ingénierie satellitaire, l'infrastructure internet, les sociétés technologiques cotées et les sciences de la vie. Il a fondé 9 Net Avenue Inc., acquise par Concentric Networks en 2000. Il est CEO de Digital Invest Inc., en médecine biomathématique et intelligence génomique, et fondateur d'AGRON Inc., en opérations autonomes aéro-terrestres et systèmes géospatiaux. Il siège à des conseils et conseille dans la technologie, la santé et l'infrastructure.",
    "introLink": "Biographie complète →",
    "currentEyebrow": "Travail actuel",
    "currentTitle": "Priorités actuelles",
    "currentDiTitle": "Digital Invest Inc.",
    "currentDiDesc": "Médecine biomathématique, données génomiques et intelligence clinique — IA, machine learning et technologies ADN au service de la santé.",
    "currentDiLink": "Entreprises →",
    "currentAgTitle": "AGRON Inc.",
    "currentAgDesc": "Opérations autonomes aéro-terrestres, développement de capacités UAV, systèmes géospatiaux et infrastructure de renseignement maritime.",
    "currentAgLink": "agron1.com →",
    "careerEyebrow": "Dossier sélectionné",
    "careerTitle": "Continuité à travers les périodes technologiques",
    "careerLead": "Jalons sélectionnés de l'ingénierie au travail actuel sur les systèmes autonomes.",
    "career1title": "Ingénierie & communications",
    "career1desc": "Systèmes émetteurs-récepteurs satellitaires, communications numériques et leadership en ingénierie précoce.",
    "career2title": "Internet & infrastructure",
    "career2desc": "Infrastructure internet, centres de données, stockage et télécommunications à grande échelle.",
    "career3title": "Entreprises technologiques & marchés publics",
    "career3desc": "Création d'entreprises, acquisitions et expérience de sociétés cotées, y compris 9 Net Avenue Inc.",
    "career4title": "Sciences de la vie & données humaines",
    "career4desc": "Biotechnologie, données génétiques, médecine de précision et plateformes d'intelligence santé.",
    "career5title": "Systèmes autonomes",
    "career5desc": "Robotique aéro-terrestre, opérations UAV et infrastructure géospatiale.",
    "careerLink": "Le parcours →",
    "perspectivesEyebrow": "Points de vue",
    "perspectivesTitle": "Écrits sélectionnés",
    "perspectivesLink": "Toutes les perspectives →",
    "footerHomeDesc": "Dirigeant technologique, fondateur et conseiller.",
    "activeSitesLink": "Tous les sites actifs →"
  },
  "about": {
    "eyebrow": "À propos",
    "title": "Trois décennies de parcours",
    "lead": "Dirigeant technologique, fondateur et conseiller.",
    "glance": "En bref",
    "role": "Rôle actuel",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "Localisation",
    "locationVal": "Charlotte, North Carolina",
    "education": "Formation",
    "educationVal": "Doctor of Technical Sciences\nPh.D. in Information Technology\nMasters — Électronique, Systèmes satellitaires numériques et Économie",
    "university": "Université",
    "universityVal": "Université technique navale d'État d'Ukraine",
    "languages": "Langues",
    "languagesVal": "Anglais, russe, ukrainien",
    "contactLabel": "Contacter",
    "principlesEyebrow": "Principes opérationnels",
    "principlesTitle": "Comment je dirige",
    "p1title": "Comprendre le système",
    "p1text": "Avant de changer une organisation, comprendre ses incitations, son architecture, ses contraintes et ses sources de confiance.",
    "p2title": "Rendre la responsabilité explicite",
    "p2text": "Une propriété claire et des résultats mesurables transforment la stratégie de support de présentation en réalité opérationnelle.",
    "p3title": "Laisser des institutions plus fortes",
    "p3text": "Le leadership doit multiplier la capacité en développant les personnes, en améliorant les décisions et en construisant des systèmes durables.",
    "archiveEyebrow": "Des archives",
    "archiveTitle": "De l'archive",
    "archiveLead": "Documents authentiques sur la création d'entreprises, l'infrastructure et le leadership.",
    "photo9netTitle": "9 Net Avenue",
    "photo9netCaption": "Fondateur et CEO — entreprise d'hébergement et d'infrastructure internet, acquise par Concentric Networks en 2000.",
    "photoServerTitle": "Infrastructure de données",
    "photoServerCaption": "Environnements de stockage, réseaux et serveurs chez DataPeer et entreprises associées.",
    "photoTodayTitle": "Aujourd'hui",
    "photoTodayCaption": "Digital Invest Inc., AGRON Inc. et travail de conseil.",
    "secIntroTitle": "Présentation",
    "secTechTitle": "Technologie & infrastructure",
    "secBusinessTitle": "Entreprise",
    "secCurrentTitle": "Travail actuel",
    "secBackgroundTitle": "Parcours",
    "recordLink": "Le parcours →",
    "secBackgroundP1": "Doctor of Technical Sciences et Ph.D. in Information Technology. Auteur de travaux techniques; brevet HDTV satellitaire acquis par Sony.",
    "bioP1": "Michael Kofman est dirigeant technologique, fondateur et conseiller. Il est CEO de Digital Invest Inc. et fondateur d'AGRON Inc., avec une expérience en ingénierie satellitaire, infrastructure internet, sociétés technologiques cotées et sciences de la vie aux États-Unis et en Europe.",
    "bioP2": "As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. In 2026 he founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network. He also created Digital Invest, dedicated to the bio-mathematical sphere and transforming medicine through science, DNA technologies, AI, and ML.",
    "secBioTitle": "Médecine de précision & biotechnologie",
    "secBioP1": "Avant Digital Invest, il a joué un rôle déterminant dans le succès de Biotechnology Group Inc. (2008–2014), une entreprise engagée dans les tests et analyses ADN, l'automatisation de la création de profils génétiques et la recherche génétique humaine complète. M. Kofman croit fermement au potentiel de la combinaison des sciences de la vie avec les dernières avancées technologiques.",
    "secBioP2": "Sous sa direction, des projets de tests génétiques réussis ont été lancés en Ukraine, en Russie et dans les pays baltes. Cette expérience unique est continuellement enrichie par des technologies modernes et de nouveaux équipements. En collaboration avec la Harvard Medical School et Stanford Biomath, M. Kofman a joué un rôle crucial dans le développement de rapports génétiques facilement compréhensibles pour les médecins et les patients. Cette approche innovante a été largement adoptée par les laboratoires de premier plan aux États-Unis et à l'étranger.",
    "secTechP1": "Formation en systèmes émetteurs-récepteurs satellitaires au Nikolaev Shipbuilding Plant et communications numériques chez Astra Corp.",
    "secTechP2": "En 2006, M. Kofman a fondé XIBI Group Inc. — une entreprise technologique dont il siégeait au conseil d'administration. La société américaine est spécialisée dans le stockage de données et les services de gestion du big data pour les grandes organisations commerciales et gouvernementales.",
    "secTechP3": "De 2000 à 2004, M. Kofman a dirigé DataPeer Inc. — une entreprise de gestion et de stockage de données offrant un large éventail de services liés au stockage d'informations pour les petites et moyennes entreprises. Chez DataPeer, il a développé des solutions technologiques uniques facilitant un suivi plus rapide des informations et un accès plus simple aux données pour les utilisateurs finaux et les institutions gouvernementales du monde entier.",
    "secTechP4": "En 1996, M. Kofman a fondé 9 Net Avenue Inc. L'entreprise est rapidement devenue l'un des plus grands hébergeurs au monde. En 2000, 9 Net Avenue a été acquise par Concentric Networks (NASDAQ: CNTX), puis par XO Communications (NASDAQ: XOXO), atteignant une valeur boursière maximale de 2000",
    "secPost9NetP1": "Après l'acquisition de 9 Net Avenue, M. Kofman a acquis une vaste expérience au sein d'entreprises cotées en bourse, de participation aux conseils d'administration et de prise de décisions stratégiques au plus haut niveau exécutif.",
    "secEarlyTitle": "Débuts de carrière & ingénierie",
    "secEarlyP1": "De 1994 à 1996, M. Kofman a été PDG et directeur des technologies de l'information chez Elitan United Inc. — une entreprise informatique du Massachusetts offrant des stratégies complètes et des services technologiques aux principales organisations mondiales. Il a joué un rôle central dans le développement et la gestion d'une infrastructure évolutive, faisant passer l'entreprise de neuf à plus de 4 000 employés dans le monde.",
    "secEarlyP2": "De 1989 à 1994, il a été fondateur et PDG d'Astra Corp, l'un des plus grands fabricants européens de systèmes satellitaires de transception numérique, reconnu internationalement dans le domaine des dispositifs satellitaires. Ses responsabilités comprenaient la recherche, le développement de systèmes d'exploitation, les applications logicielles réseau et la stratégie technique globale.",
    "secEarlyP3": "De 1984 à 1989, M. Kofman a travaillé au chantier naval de Nikolaev, en Ukraine, où il a activement participé au développement et à la création de systèmes de transception satellitaire pour transmettre des informations classifiées aux navires militaires et en retour. Il a été reconnu comme ingénieur électronicien du plus haut niveau, recevant la 6e catégorie — la plus haute distinction du chantier, qui comptait 93 000 employés.",
    "secResearchTitle": "Recherche & brevets",
    "secResearchP1": "Michael Kofman est l'auteur de travaux techniques sur les systèmes satellitaires et optiques de transmission de données. Il a également obtenu un brevet dans le domaine des systèmes de télévision haute définition (HDTV) par satellite numérique, ultérieurement acquis par Sony.",
    "secAgronTitle": "Robotics, UAV & Maritime Intelligence",
    "secAgronP1": "In 2026, Mr. Kofman founded AGRON Inc. to build the AGRON Ecosystem — a corporate operating architecture for aerial and ground robotics, governed mission execution, and network infrastructure connecting teams, assets, and operational data. The ecosystem delivers consulting, assessment, capability development, and training for UAV and Counter-UAS organizations, alongside maritime intelligence and security services at agron1.com.",
    "secBusinessP1": "A fondé et dirigé plusieurs entreprises technologiques, dont 9 Net Avenue Inc., DataPeer Inc., XIBI Group Inc. et Elitan United Inc. Chronologie complète dans The Record.",
    "secCurrentP1": "CEO de Digital Invest Inc. en médecine biomathématique et intelligence génomique. Fondateur d'AGRON Inc. en opérations autonomes aéro-terrestres et systèmes géospatiaux."
  },
  "ventures": {
    "eyebrow": "Portefeuille",
    "title": "Entreprises fondées et dirigées",
    "lead": "De la médecine de précision et la robotique à l'infrastructure mondiale de données — fondées, développées et dirigées aux États-Unis et en Europe.",
    "ecosystemEyebrow": "Venture Ecosystem",
    "ecosystemTitle": "Companies Across Technology Frontiers",
    "ecosystemLead": "A portfolio shaped by recurring themes: trusted data, intelligent infrastructure, human health, and systems built for scale.",
    "statusActive": "Actif",
    "statusExited": "Sortie",
    "statusLegacy": "Héritage",
    "v1lesson": "Leçon : l'infrastructure gagne quand fiabilité, économie et confiance client progressent ensemble.",
    "v2lesson": "Leçon : la médecine de précision exige la même discipline en science, logiciel, confidentialité et utilité clinique.",
    "v3lesson": "Leçon : l'autonomie crée de la valeur seulement quand capteurs, communications et supervision humaine forment un système résilient.",
    "v5lesson": "Leçon : l'échelle en infrastructure se gagne par l'excellence opérationnelle bien avant la sortie.",
    "currentEyebrow": "Actuel",
    "historyEyebrow": "Historique sélectionné",
    "v2highlight": "Harvard Medical School et Stanford Biomath — collaboration sur les rapports génétiques",
    "activeSitesEyebrow": "Projets actifs",
    "activeSitesTitle": "Sites actifs",
    "activeSitesLead": "Sites web actifs des entreprises actuelles et initiatives portfolio.",
    "activeSitesMeta": "10 sites actifs · cliquez sur une carte pour visiter",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — an Aerial-Ground Robotics Operations Network spanning UAV and Counter-UAS consulting, technology assessment, capability development, training infrastructure, product validation, geospatial systems (ISDRI), and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "v0role": "Founder",
    "v0year": "2026 — Present",
    "v2role": "PDG & CTO",
    "v2year": "2008 — 2014",
    "v3year": "2006 — 2011",
    "v4year": "2000 — 2004",
    "v5highlight": "Acquise · Valeur maximale de 2000",
    "v5p1": "Construction de l'un des plus grands hébergeurs au monde. En 2000, acquisition par Concentric Networks (NASDAQ: CNTX), puis XO Communications (NASDAQ: XOXO), atteignant une valeur boursière maximale de 2000",
    "v5year": "1996 — 2000",
    "v6year": "1994 — 1996",
    "v7year": "1989 — 1994",
    "v8year": "1984 — 1989",
    "v1highlight": "Top 10 entreprise de médecine de précision aux États-Unis — 2023",
    "v1p1": "Médecine biomathématique, données génomiques et intelligence clinique — IA, ML et technologies ADN appliquées aux workflows cliniques et de recherche.",
    "v1role": "Fondateur & PDG · Membre du conseil",
    "v1year": "2021 — Aujourd'hui",
    "v2p1": "Tests et analyses ADN, automatisation du profilage génétique et recherche génétique humaine complète. Lancement de projets de tests génétiques en Ukraine, en Russie et dans les pays baltes.",
    "v2p2": "Collaboration avec la Harvard Medical School et Stanford Biomath sur des rapports génétiques adoptés par les laboratoires de premier plan dans le monde entier.",
    "v3highlight": "Solutions de données d'entreprise & gouvernementales",
    "v3p1": "Stockage de données et services de gestion du big data pour les grandes organisations commerciales et gouvernementales. Établissement de l'entreprise comme fournisseur de confiance de solutions de données d'entreprise.",
    "v3role": "Fondateur & PDG · Conseil d'administration",
    "v4highlight": "Plateforme mondiale de gestion de données",
    "v4p1": "Gestion et stockage de données pour les petites et moyennes entreprises. Développement de solutions pour un suivi plus rapide des informations et un accès plus simple aux données pour les utilisateurs finaux et les institutions gouvernementales du monde entier.",
    "v4role": "Fondateur & PDG",
    "v5role": "Fondateur & PDG",
    "v6highlight": "Stratégie informatique & infrastructure mondiale",
    "v6p1": "Entreprise informatique du Massachusetts offrant des stratégies complètes et des services technologiques aux principales organisations mondiales. Direction du développement d'infrastructures évolutives et des opérations informatiques mondiales.",
    "v6role": "PDG & Directeur des technologies de l'information",
    "v7highlight": "Leader européen des systèmes satellitaires",
    "v7p1": "L'un des plus grands fabricants européens de systèmes satellitaires de transception numérique. Direction de la recherche, du développement de systèmes d'exploitation, des applications logicielles réseau et de la stratégie technique globale.",
    "v7role": "Fondateur & PDG",
    "v8highlight": "Ingénierie de systèmes satellitaires militaires",
    "v8p1": "Développement et création de systèmes de transception satellitaire pour transmettre des informations classifiées aux navires militaires. Reconnu comme ingénieur électronicien du plus haut niveau dans un chantier naval de 93 000 employés.",
    "v8role": "Ingénieur électronicien · Catégorie maximale (6e)",
    "v1p2": "Initiatives du portefeuille : <a href=\"https://biomathlife.com\" target=\"_blank\" rel=\"noopener\">BioMath Life</a>, <a href=\"https://www.biomathcore.com\" target=\"_blank\" rel=\"noopener\">BioMath Core</a>, <a href=\"https://www.type1and2.com\" target=\"_blank\" rel=\"noopener\">Type 1 &amp; 2</a> et <a href=\"https://www.luna29.com\" target=\"_blank\" rel=\"noopener\">Luna29</a> — études de cas détaillées à venir.",
    "v1brole": "PDG",
    "v1bp1": "Période de transition entre biotechnologie et nouveau développement technologique — expérience opérationnelle et R&D avant Digital Invest Inc.",
    "v1byear": "2014 — 2020"
  },
  "career": {
    "eyebrow": "Parcours professionnel",
    "title": "Le parcours",
    "lead": "Technologie, entreprises et expérience opérationnelle à travers des périodes de changement technologique.",
    "timelineEyebrow": "Chronologie",
    "timelineTitle": "Jalons clés",
    "strengthsEyebrow": "Forces",
    "strengthsTitle": "Domaines d'expertise",
    "filterAll": "All",
    "filterHealthcare": "Healthcare",
    "filterInfrastructure": "Infrastructure",
    "filterDefense": "Defense",
    "filterTelecom": "Telecommunications",
    "periodCurrent": "Systèmes autonomes",
    "periodCurrentLead": "IA, robotique, opérations autonomes, systèmes géospatiaux et infrastructure actuelle connexe.",
    "period1title": "Ingénierie & communications",
    "period1lead": "Premiers travaux d'ingénierie, systèmes satellitaires, communications et technologies connexes.",
    "period2title": "Internet & infrastructure",
    "period2lead": "Infrastructure internet, télécommunications, centres de données, stockage et entreprises connexes.",
    "period3title": "Entreprises & marchés publics",
    "period3lead": "Création d'entreprises, transactions, implication dans des sociétés cotées et rôles exécutifs.",
    "period4title": "Sciences de la vie & données humaines",
    "period4lead": "Biotechnologie, technologie de santé, données et médecine de précision.",
    "period5title": "Programmes gouvernementaux & défense",
    "period5lead": "Stratégie et déploiement technologiques pour programmes gouvernementaux, de défense et d'entreprises publiques.",
    "t1desc": "Digital Invest Inc., fondée en 2021. Médecine biomathématique, intelligence génomique et plateformes de données cliniques. Healthcare Tech Outlook (2023).",
    "t0desc": "Founded AGRON Inc. to build the AGRON Ecosystem — consulting, assessment, capability development, training infrastructure, and product support for UAV and Counter-UAS programmes, plus AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure. Connects aerial and ground robotics, governed mission execution, and network infrastructure linking teams, assets, and operational data.",
    "t0role": "Founder",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — Present",
    "t10title": "Chantier naval de Nikolaev",
    "t10year": "1984 — 1989",
    "t1title": "Digital Invest Inc.",
    "t2year": "2001 — 2019",
    "t3role": "PDG & CTO",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4year": "2000 — 2012",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "Construction de l'un des plus grands hébergeurs au monde. En 2000, acquisition par Concentric Networks (NASDAQ: CNTX), puis XO Communications (NASDAQ: XOXO), atteignant une valeur boursière maximale de 2000",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994",
    "t10desc": "Développement et création de systèmes de transception satellitaire pour transmettre des informations classifiées aux navires militaires. Reconnu comme ingénieur électronicien du plus haut niveau dans un chantier naval de 93 000 employés — le début d'une carrière distinguée en technologie et innovation.",
    "t10role": "Ingénieur électronicien — 6e catégorie (maximale)",
    "t1role": "Fondateur & PDG",
    "t1year": "2021 — Aujourd'hui",
    "t2desc": "Direction de la stratégie et de la mise en œuvre technologiques pour des programmes classifiés et hautement sensibles impliquant des agences gouvernementales américaines, des systèmes de défense alliés et des entreprises d'État. Direction de projets techniques complexes pour des sociétés publiques dans de multiples secteurs. À la suite du 11 septembre 2001, direction d'initiatives gouvernementales à grande échelle centrées sur le big data, les communications sécurisées, l'analytique prédictive et l'intégration des données au niveau national — y compris la conception, la construction et l'exploitation de centres de données à haut débit aux États-Unis et en Europe. Interface avec les responsables de programmes militaires, les fournisseurs technologiques et les entités réglementaires.",
    "t2role": "Conseiller technologique principal / Architecte de programmes",
    "t2title": "GovTech, défense & programmes d'État",
    "t3desc": "Direction des tests et analyses ADN, de l'automatisation du profilage génétique et de la recherche génétique humaine complète. Lancement de projets de tests génétiques en Ukraine, en Russie et dans les pays baltes. Collaboration avec la Harvard Medical School et Stanford Biomath pour développer des rapports génétiques compréhensibles adoptés par les laboratoires de premier plan dans le monde entier.",
    "t4desc": "Direction des déploiements d'infrastructures nationales au Canada, en Italie, en Suisse, en Ukraine et dans les républiques baltes. Supervision de plus de 1 000 ingénieurs et personnel de déploiement dans les opérations télécoms, y compris les systèmes de commutation, l'expansion de la bande passante et la connectivité transfrontalière. Mise en œuvre de systèmes centraux de redondance réseau, d'optimisation de la disponibilité et de routage intelligent.",
    "t4role": "VP Technologie / CTO régional — Europe de l'Est & CEI",
    "t4title": "Projets de télécommunications",
    "t5desc": "Fondation d'une entreprise technologique spécialisée dans le stockage de données et la gestion du big data pour les grandes organisations commerciales et gouvernementales. Établissement de l'entreprise comme fournisseur de confiance de solutions de données d'entreprise.",
    "t5role": "Fondateur & PDG · Conseil d'administration",
    "t6desc": "Création d'une entreprise de gestion et de stockage de données pour les PME. Développement de solutions technologiques uniques pour un suivi plus rapide des informations et un accès plus simple aux données pour les utilisateurs finaux et les institutions gouvernementales du monde entier.",
    "t6role": "Fondateur & PDG",
    "t7role": "Fondateur & PDG",
    "t8desc": "Direction de stratégies informatiques complètes et de services technologiques pour les principales organisations mondiales depuis le Massachusetts pendant une période d'expansion rapide, en construisant une infrastructure évolutive et des opérations informatiques mondiales.",
    "t8role": "PDG & Directeur des technologies de l'information",
    "t9desc": "Fondation de l'un des plus grands fabricants européens de systèmes satellitaires de transception numérique. Direction de la recherche, du développement de systèmes d'exploitation, des applications logicielles réseau et de la stratégie technique globale, obtenant une reconnaissance internationale.",
    "t9role": "Fondateur & PDG",
    "t1bdesc": "Période de transition entre biotechnologie et nouveau développement technologique — expérience opérationnelle et R&D avant Digital Invest Inc.",
    "t1brole": "PDG",
    "t1byear": "2014 — 2020"
  },
  "recognition": {
    "eyebrow": "Distinctions",
    "title": "Prix et reconnaissance",
    "lead": "Distinctions en entrepreneuriat, médecine de précision, ingénierie et leadership exécutif.",
    "industryEyebrow": "Prix du secteur",
    "industryTitle": "Grandes distinctions",
    "ipEyebrow": "Propriété intellectuelle",
    "ipTitle": "Brevets et publications",
    "eduEyebrow": "Formation",
    "eduTitle": "Diplômes",
    "pressEyebrow": "Presse",
    "pressTitle": "Vu dans",
    "moreLink": "Voir les brevets, publications et mentions presse dans Insights →",
    "a1desc": "Entrepreneur Magazine · 2001",
    "a3title": "Who's Who in America",
    "a4title": "Who's Who in the World",
    "a5title": "Who's Who in Science & Engineering",
    "ip1year": "Brevet",
    "ip2year": "Publications",
    "press1role": "Article sur Digital Invest Inc.",
    "press1title": "Healthcare Tech Outlook",
    "press2title": "Top Precision Medicine Solutions",
    "a1title": "Entrepreneur de l'année",
    "a2title": "Top 10 entreprise de médecine de précision aux États-Unis",
    "a2desc": "Digital Invest Inc. reconnue parmi les 10 meilleures entreprises américaines de médecine de précision et de santé numérique — 2023.",
    "a3desc": "Inscrit, 1999 — 2018 — pour des réalisations exceptionnelles en création et développement d'entreprises.",
    "a4desc": "Inscrit, 2000 — 2004 — parmi les leaders mondiaux en science, ingénierie et innovation entrepreneuriale.",
    "a5desc": "Inscrit, 2000 — 2014 — pour des contributions à la technologie, aux systèmes satellitaires et à l'infrastructure numérique.",
    "a6title": "Ingénieur électronicien — 6e catégorie",
    "a6desc": "Plus haute distinction au chantier naval de Nikolaev (93 000 employés) pour l'ingénierie de systèmes de transception satellitaire.",
    "ip1title": "Systèmes HDTV satellitaires numériques",
    "ip1role": "Ultérieurement acquis par Sony",
    "ip1desc": "Brevet pour systèmes HDTV satellitaires numériques, acquis par Sony Corporation.",
    "ip2title": "Travaux techniques",
    "ip2role": "Systèmes satellitaires & optiques",
    "ip2desc": "Auteur de travaux techniques sur les systèmes satellitaires et optiques de transmission de données. Les contributions de recherche couvrent le traitement du signal, la modélisation par simulation et les plateformes d'automatisation appliquées aux télécommunications, à l'infrastructure nationale et à la santé numérique.",
    "ip3year": "Recherche",
    "ip3title": "Collaborations internationales",
    "ip3role": "États-Unis & Europe",
    "ip3desc": "Participation à des collaborations de recherche internationales et à des initiatives de transfert de connaissances. Développement de systèmes d'ingénierie embarqués pour l'acquisition de données, le diagnostic prédictif et l'orchestration cloud dans de multiples industries.",
    "edu1title": "Docteur en sciences techniques",
    "edu2title": "Doctorat en technologies de l'information",
    "edu3title": "Masters",
    "edu3desc": "Électronique, systèmes satellitaires numériques et économie",
    "press1desc": "Healthcare Tech Outlook sur Digital Invest Inc. et médecine de précision (2023).",
    "press1link": "Lire l'article →",
    "press2role": "Reconnaissance du secteur",
    "press2desc": "Classée parmi les principales entreprises de solutions de médecine de précision, soulignant le rôle de Digital Invest dans l'avancement des approches bio-mathématiques en santé moderne.",
    "press2link": "Voir le classement →"
  },
  "contact": {
    "eyebrow": "Contacter",
    "title": "Contacter",
    "lead": "Pour des rôles de conseil, conseils d'administration et partenariats.",
    "infoTitle": "Contact direct",
    "email": "E-mail",
    "phone": "Téléphone",
    "location": "Localisation",
    "locationVal": "Charlotte, North Carolina\nÉtats-Unis",
    "linkedin": "LinkedIn",
    "company": "Entreprise actuelle",
    "companyVal": "Digital Invest Inc.\nCEO & membre du conseil\nAGRON Inc.\nFondateur",
    "formTitle": "Envoyer un message",
    "formLead": "Remplissez le formulaire ci-dessous.",
    "firstName": "Prénom",
    "lastName": "Nom",
    "emailLabel": "Adresse e-mail",
    "subject": "Objet",
    "message": "Votre message",
    "inquiryType": "Type de demande",
    "inquiryAdvisory": "Conseil",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "calendlyEyebrow": "Planifier une conversation",
    "calendlyTitle": "Choisir un horaire",
    "calendlyLead": "Pour demandes qualifiées de conseil, mandats au conseil, conférences et partenariats stratégiques.",
    "calendlyPlaceholder": "Le calendrier apparaîtra ici.",
    "calendlyCta": "Ouvrir le calendrier",
    "inquiryBusiness": "Entreprise",
    "infoEyebrow": "Coordonnées"
  },
  "consulting": {
    "eyebrow": "Services de conseil",
    "title": "Conseil",
    "heroEyebrow": "Orientation stratégique des entreprises",
    "heroTitle": "Conseil stratégique",
    "heroLead": "Trente-cinq ans à fonder et conseiller des entreprises aux États-Unis et en Europe — infrastructure de données, govtech, médecine de précision et robotique.",
    "cta": "Contacter Michael Kofman",
    "introLead": "PDG de Digital Invest Inc. et membre du conseil. Axes : technologies émergentes, sécurité, recherche et allocation de capital.",
    "specialtiesEyebrow": "Domaines d'intervention",
    "specialtiesTitle": "Les spécialités de Michael Kofman",
    "area1title": "Mandats au conseil",
    "area1desc": "Mandats indépendants au conseil d'administration en stratégie technologique, gouvernance d'entreprise et supervision en phase de croissance.",
    "area2title": "Conseil CEO & fondateurs",
    "area2desc": "Stratégie d'entreprise et technologique, développement organisationnel, transactions et expérience applicable des marchés de capitaux.",
    "area3title": "Due diligence technologique",
    "area3desc": "Évaluation de l'infrastructure, des plateformes de données, de l'architecture de sécurité et de la technologie appliquée, fondée sur une expérience opérationnelle documentée.",
    "redirectLead": "Le travail de conseil stratégique est documenté sur la page Advisory. Pour les demandes professionnelles, utilisez Contact.",
    "redirectLink": "Conseil →"
  },
  "insights": {
    "eyebrow": "Points de vue",
    "title": "Perspectives",
    "heroTitle": "Perspectives exécutives",
    "selectedEyebrow": "Points saillants",
    "selectedTitle": "Reconnaissance en vedette",
    "allPressTitle": "Toutes les parutions presse",
    "quotesEyebrow": "Dans les médias",
    "quotesTitle": "Reconnaissance sectorielle et citations",
    "articlesEyebrow": "Points de vue",
    "articlesTitle": "Perspectives dirigeantes",
    "briefsEyebrow": "Notes exécutives",
    "briefsTitle": "Idées pour les dirigeants",
    "briefsLead": "Perspectives courtes et pratiques sur gouvernance, technologie, santé et création d'entreprises.",
    "brief1title": "Ce qu'un IPO change",
    "brief1desc": "Les disciplines opérationnelles et de gouvernance exigées par la préparation aux marchés publics.",
    "brief1tag": "Marchés de capitaux",
    "brief2title": "Des données génétiques aux décisions cliniques",
    "brief2desc": "Comment construire une intelligence santé utile sans dépasser les preuves ni la confiance.",
    "brief2tag": "Médecine de précision",
    "brief3title": "Stratégie IA au-delà du pilote",
    "brief3desc": "Un cadre pour transformer les expériences en capacité d'entreprise gouvernée.",
    "brief3tag": "Intelligence artificielle",
    "readingEyebrow": "Liste de lecture",
    "readingTitle": "Livres qui façonnent la pensée stratégique",
    "r1title": "The Innovator's Dilemma",
    "r1author": "Clayton M. Christensen",
    "r2title": "Thinking, Fast and Slow",
    "r2author": "Daniel Kahneman",
    "r3title": "The Beginning of Infinity",
    "r3author": "David Deutsch",
    "r4title": "Good Strategy/Bad Strategy",
    "r4author": "Richard Rumelt",
    "r5title": "The Structure of Scientific Revolutions",
    "r5author": "Thomas S. Kuhn",
    "newsletterEyebrow": "Notes occasionnelles",
    "newsletterTitle": "Perspective exécutive, sans bruit",
    "newsletterLead": "Essais périodiques et brèves observations sur technologie, gouvernance et création d'entreprises durables.",
    "newsletterCta": "S'abonner aux mises à jour",
    "lead": "Écrits substantiels et notes exécutives.",
    "relatedLead": "Reconnaissance, couverture presse et brevets sont documentés séparément.",
    "topicsLead": "Les thèmes s'appuient sur une expérience opérationnelle documentée en technologie, santé et infrastructure."
  },
  "cta": {
    "eyebrow": "Collaborons",
    "title": "Demander un accompagnement ou une intervention",
    "lead": "Pour des rôles de conseil, des mandats d'administrateur, des interventions et des partenariats stratégiques.",
    "button": "Prendre contact"
  },
  "speaking": {
    "eyebrow": "Interventions",
    "title": "Inviter Michael Kofman à intervenir",
    "lead": "Disponible pour des interventions sur le leadership exécutif, la stratégie technologique, la santé numérique, l'infrastructure de données et la gouvernance d'entreprise.",
    "topicsEyebrow": "Thèmes d'intervention",
    "topicsTitle": "Domaines d'expertise",
    "topicsLead": "Les thèmes s'appuient sur des décennies d'expérience dans la création et la direction d'entreprises aux États-Unis et en Europe.",
    "processEyebrow": "Comment inviter",
    "processTitle": "Processus de réservation",
    "process1title": "Envoyer une demande",
    "process1desc": "Utilisez le formulaire de contact ou écrivez à mkofman@mkofman.com avec les détails de l'événement, le public et les thèmes souhaités.",
    "process2title": "Valider le périmètre",
    "process2desc": "Définissez le format (keynote, panel, session de conseil d'administration ou table ronde exécutive) et la logistique.",
    "process3title": "Créer de la valeur",
    "process3desc": "Les interventions s'appuient sur des résultats concrets obtenus dans le data storage, la govtech et la médecine de précision.",
    "cta": "Demander une intervention",
    "catalogEyebrow": "Sujets de conférences",
    "catalogTitle": "Conversations exécutives pour un changement majeur",
    "catalogLead": "Keynotes, sessions de conseil et briefings de leadership adaptés au public, secteur et contexte de décision.",
    "t1title": "Gouverner l'IA avant qu'elle ne gouverne l'entreprise",
    "t1audience": "Conseils, comités d'audit et de risque",
    "t1format": "Briefing conseil ou keynote",
    "t2title": "De la tendance technologique à la stratégie d'entreprise",
    "t2audience": "PDG, équipes exécutives, investisseurs",
    "t2format": "Keynote ou atelier exécutif",
    "t3title": "Construire des entreprises à travers les cycles de marché",
    "t3audience": "Fondateurs, leaders de croissance, private equity",
    "t3format": "Discussion ou keynote",
    "t4title": "Médecine de précision : promesse, preuve et responsabilité",
    "t4audience": "Leaders santé, cliniciens, innovateurs",
    "t4format": "Keynote sectorielle ou panel",
    "t5title": "Le rôle du conseil dans le risque cyber et technologique",
    "t5audience": "Administrateurs, directeurs juridiques, leaders risque",
    "t5format": "Session de formation du conseil",
    "t6title": "Ingénierie de la confiance dans l'infrastructure numérique",
    "t6audience": "Organisations technologiques et d'infrastructure",
    "t6format": "Keynote technique-exécutive",
    "t7title": "Diriger au-delà des frontières et des disciplines",
    "t7audience": "Équipes de direction globales et universités",
    "t7format": "Keynote ou conversation modérée",
    "t8title": "Du fondateur au bâtisseur d'institution",
    "t8audience": "Entrepreneurs et dirigeants de nouvelle génération",
    "t8format": "Atelier ou discussion"
  },
  "caseStudies": {
    "eyebrow": "Études de cas",
    "title": "Construire des entreprises qui passent à l'échelle",
    "lead": "Résultats sélectionnés issus de la création et de la direction d'entreprises en infrastructure de données et santé numérique.",
    "cs1eyebrow": "Infrastructure de données · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "Défi",
    "cs1challengeText": "Créer et développer une entreprise de Data Storage dans un marché technologique en consolidation rapide.",
    "cs1action": "Approche",
    "cs1actionText": "J'ai fondé 9 Net Avenue Inc. en 1996. L'entreprise est rapidement devenue l'une des plus grandes sociétés de Data Storage au monde.",
    "cs1result": "Résultat",
    "cs1resultText": "Acquise par Concentric Networks (NASDAQ: CNTX) en 2000 ; ensuite partie de XO Communications (NASDAQ: XOXO). Après la transaction, poursuite du travail avec sociétés cotées et rôles au niveau du conseil.",
    "cs2eyebrow": "Santé numérique · 2021 — Aujourd'hui",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "Défi",
    "cs2challengeText": "Transformer des approches médicales obsolètes grâce à la science, aux technologies ADN, à l'IA et au ML via une nouvelle plateforme bio-mathématique.",
    "cs2action": "Approche",
    "cs2actionText": "Digital Invest Inc. fondée en 2021. Médecine biomathématique, intelligence génomique et plateformes de données cliniques.",
    "cs2result": "Résultat",
    "cs2resultText": "Nous avons atteint une croissance financière soutenue, positionnant l'entreprise parmi les 10 meilleures sociétés de médecine de précision aux États-Unis (2023). Digital Invest regroupe des projets innovants tels que Human Digital Model, BioMath Life et Aero-Ground Robotics Operations Network.",
    "cs3eyebrow": "Robotique & UAV · 2026 — Aujourd'hui",
    "cs3title": "AGRON Inc.",
    "cs3challenge": "Défi",
    "cs3challengeText": "Les organisations développant des capacités UAV et Counter-UAS ont besoin d'évaluation indépendante, de formation structurée et d'une architecture opérationnelle — pas de plateformes isolées ni de pilotes ad hoc.",
    "cs3action": "Approche",
    "cs3actionText": "A fondé AGRON Inc. en 2026 pour diriger l'AGRON Ecosystem — conseil, évaluation et validation, développement de capacités, infrastructure de formation, support au développement produit, systèmes géospatiaux via ISDRI et AGRON Maritime Intelligence + Security pour yachts, marinas et infrastructure maritime privée.",
    "cs3result": "Résultat",
    "cs3resultText": "Un écosystème de services professionnels couvrant conseil, développement de capacités, infrastructure de formation, systèmes géospatiaux et intelligence maritime via AGRON, ISDRI et entreprises associées.",
    "caseStudiesLead": "Création, développement et direction d'entreprises de leur lancement jusqu'à l'acquisition."
  },
  "mediaKit": {
    "eyebrow": "Presse et événements",
    "title": "Kit média",
    "lead": "Biographies officielles, visuels et coordonnées pour la presse, les conférences et les demandes de conseil d'administration.",
    "bioEyebrow": "Biographies officielles",
    "bioTitle": "Biographies officielles",
    "bioShortLabel": "50 mots",
    "bioShort": "Michael Kofman est CEO de Digital Invest Inc., administrateur, conseiller et fondateur d'entreprises technologiques et de santé numérique aux États-Unis et en Europe.",
    "bioMediumLabel": "150 mots",
    "bioMedium": "Michael Kofman est CEO de Digital Invest Inc. et siège à son Board of Directors. Visionnaire technologique, il est reconnu pour son approche dynamique des besoins en constante évolution des marchés complexes actuels. Entrepreneur, administrateur et conseiller auprès d'entreprises publiques et privées, il a fondé avec succès plusieurs sociétés aux États-Unis et en Europe. Son expertise couvre la direction exécutive, l'analyse stratégique des technologies et marchés émergents, la sécurité et la confidentialité de l'information, la recherche, la science et le développement, l'administration et l'investissement.",
    "bioLongLabel": "500 mots",
    "bioLong": "Michael Kofman est CEO de Digital Invest Inc. et membre de son conseil. Il a fondé 9 Net Avenue Inc., acquise par Concentric Networks en 2000, et dirige Digital Invest en médecine biomathématique et intelligence génomique. Il a fondé AGRON Inc. en 2026 pour opérations autonomes aéro-terrestres et systèmes géospatiaux. Auteur de travaux techniques sur systèmes satellitaires et optiques ; brevet HDTV satellitaire numérique acquis par Sony. Formation : Doctor of Technical Sciences, Ph.D. in Information Technology.",
    "photosEyebrow": "Photographie",
    "photosTitle": "Images approuvées",
    "photosLead": "Portraits en haute résolution disponibles sur demande à mkofman@mkofman.com.",
    "contactEyebrow": "Contact presse",
    "contactTitle": "Demandes médias",
    "contactLead": "Pour les interviews, invitations à intervenir et demandes presse.",
    "downloadEyebrow": "Téléchargement",
    "downloadTitle": "Media kit d'une page",
    "downloadLead": "PDF avec bios officielles, portrait et contact presse — prêt pour organisateurs et journalistes.",
    "downloadCta": "Télécharger le PDF",
    "brandEyebrow": "Assets de marque",
    "brandTitle": "Identité & usage",
    "brandLead": "Assets visuels approuvés pour usage éditorial, conférences et partenaires. Conserver proportions, espacements et couleurs d'origine.",
    "brandColors": "Palette de couleurs officielle",
    "brandLogo": "Logo principal",
    "brandDownload": "Télécharger les assets de marque"
  },
  "articles": {
    "backLink": "← Retour vers Insights",
    "article1date": "Perspective exécutive",
    "article1title": "De l'ingénierie à l'infrastructure mondiale de données",
    "article1p1": "Ma carrière a commencé à l'usine navale de Nikolaev, en Ukraine, où je développais des systèmes transpondeurs satellitaires pour transmettre des informations classifiées aux navires militaires. J'ai été reconnu comme ingénieur en électronique de plus haut niveau, 6e catégorie, dans une usine de 93 000 employés.",
    "article1p2": "De 1989 à 1994, j'ai fondé et dirigé Astra Corp, l'un des plus grands fabricants européens de systèmes satellitaires transpondeurs numériques. De 1994 à 1996, en tant que CEO d'Elitan United Inc., j'ai contribué à faire passer l'entreprise de neuf à plus de 4 000 employés dans le monde.",
    "article1p3": "En 1996, j'ai fondé 9 Net Avenue Inc., entreprise d'hébergement et d'infrastructure internet. En 2000, elle a été acquise par Concentric Networks (NASDAQ: CNTX), puis est devenue partie de XO Communications (NASDAQ: XOXO).",
    "article1p4": "De 2001 à 2019, j'ai dirigé la stratégie technologique pour des programmes gouvernementaux, de défense et d'entreprises publiques, en menant de grandes initiatives dans le big data, l'infrastructure sécurisée et les data centers à haut débit aux États-Unis et en Europe.",
    "article2date": "Santé numérique",
    "article2title": "Médecine de précision et convergence de la science et de la technologie",
    "article2p1": "Je crois fermement au potentiel de la combinaison des sciences de la vie avec les dernières avancées technologiques. Chez Biotechnology Group Inc. (2008-2014), nous nous sommes concentrés sur les tests et analyses ADN, l'automatisation des processus de création de profils génétiques et la recherche génétique humaine complète.",
    "article2p2": "Sous ma direction, des projets réussis de tests génétiques ont été lancés en Ukraine, en Russie et dans les pays baltes. En collaboration avec Harvard Medical School et Stanford Biomath, j'ai joué un rôle clé dans le développement de rapports génétiques faciles à comprendre pour les médecins comme pour les patients.",
    "article2p3": "Avec Digital Invest Inc., fondée en 2021, nous travaillons en médecine biomathématique — science, technologies ADN, IA et ML appliquées à l'intelligence clinique. Healthcare Tech Outlook (2023).",
    "article2p4": "Digital Invest regroupe divers projets innovants, dont Human Digital Model, BioMath Life et Aero-Ground Robotics Operations Network, chacun faisant progresser l'intégration de la data science et des sciences de la vie."
  },
  "privacy": {
    "eyebrow": "Mentions légales",
    "title": "Politique de confidentialité",
    "lead": "Comment mkofman.com traite les informations lors de votre visite ou de l'envoi d'un message.",
    "updated": "Mise à jour : juillet 2026",
    "s1title": "Informations collectées",
    "s1text": "Lors de l'envoi d'un formulaire, nous recevons les champs fournis. Si l'analytique est activée, des données d'usage anonymisées peuvent être collectées.",
    "s2title": "Utilisation des informations",
    "s2text": "Les formulaires servent à répondre aux demandes et à améliorer le site. Nous ne vendons pas de données personnelles.",
    "s3title": "Services tiers",
    "s3text": "Les formulaires peuvent être traités par Formspree. Analytique via Plausible ou Google Analytics si configurée.",
    "s4title": "Vos droits",
    "s4text": "Accès, rectification ou suppression : mkofman@mkofman.com.",
    "s5title": "Contact",
    "s5text": "Questions sur cette politique : mkofman@mkofman.com"
  },
  "board": {
    "eyebrow": "Conseil",
    "title": "Conseil",
    "body": "Ouvert aux conversations de conseil stratégique avec des organisations technologiques, de santé et d'infrastructure — s'appuyant sur une expérience opérationnelle directe en création d'entreprises, stratégie technologique et exécution en phase de croissance.",
    "contactLink": "Pour les demandes de conseil",
    "lead": "Board & Advisory"
  },
  "thesis": {
    "eyebrow": "Thèse de leadership",
    "title": "Construire pour le long terme. Décider dans le présent.",
    "lead": "La technologie change vite ; les obligations du leadership, non. Les entreprises durables unissent ambition, discipline, preuves et responsabilité.",
    "believeEyebrow": "Ce en quoi je crois",
    "believeTitle": "Sept principes pour des organisations durables",
    "b1title": "La stratégie doit produire des choix",
    "b1text": "Une stratégie n'est pas un catalogue d'aspirations. Elle définit où concurrencer, quelles capacités construire, quoi ne pas poursuivre et comment le succès sera mesuré.",
    "b2title": "La technologie est un enjeu de gouvernance",
    "b2text": "Les conseils doivent comprendre comment la technologie crée de la valeur, concentre le risque et change la responsabilité. Déléguer chaque question technique est déjà une décision.",
    "b3title": "Les preuves doivent primer sur l'enthousiasme",
    "b3text": "La conviction compte, mais marchés, systèmes et science doivent être testés. Les dirigeants créent des mécanismes qui exposent les hypothèses avant clients ou régulateurs.",
    "b4title": "L'architecture façonne l'entreprise",
    "b4text": "L'architecture technique détermine vitesse, résilience, sécurité et options futures. Les raccourcis deviennent des contraintes institutionnelles longtemps après leur contexte d'origine.",
    "b5title": "La confiance est une infrastructure opérationnelle",
    "b5text": "La confiance se construit par des engagements clairs, une exécution fiable, des pratiques responsables des données et une communication directe quand les conditions changent.",
    "b6title": "Le capital doit suivre la capacité",
    "b6text": "L'investissement de croissance doit renforcer des capacités différenciées et une demande mesurable, pas substituer les dépenses à la compréhension produit-marché.",
    "b7title": "Les dirigeants conçoivent leurs successeurs",
    "b7text": "Les dirigeants les plus solides construisent des systèmes, des talents et une qualité de décision qui perdurent au-delà de leur propre participation.",
    "rejectEyebrow": "Ce que je rejette",
    "rejectTitle": "Trois illusions coûteuses",
    "r1title": "Théâtre de l'innovation",
    "r1text": "Annonces, pilotes et langage à la mode ne font pas une capacité. L'innovation doit améliorer un résultat qui compte.",
    "r2title": "Croissance sans gouvernance",
    "r2text": "L'échelle amplifie les faiblesses non résolues. Contrôles, culture et responsabilité doivent mûrir avant que la complexité ne rende la correction coûteuse.",
    "r3title": "Fausse certitude",
    "r3text": "La confiance exécutive ne doit pas effacer l'incertitude. Les bonnes décisions rendent les hypothèses visibles et préservent les options quand les faits changent.",
    "horizonEyebrow": "L'horizon",
    "horizonTitle": "Le prochain avantage est l'intégration responsable",
    "horizonText": "L'opportunité décisive n'est pas une seule technologie. C'est l'intégration disciplinée de l'IA, des systèmes de données avancés, de la biologie et de l'automatisation dans des institutions auxquelles on peut faire confiance."
  },
  "press": {
    "eyebrow": "Presse & médias",
    "title": "Couverture sélectionnée",
    "lead": "Archive concise de reconnaissance tierce et de reportages sur technologie, entrepreneuriat et médecine de précision.",
    "archiveEyebrow": "Archives",
    "y2023type": "Reconnaissance sectorielle",
    "y2023title": "Top 10 Precision Medicine Companies",
    "y2023desc": "Healthcare Tech Outlook a reconnu Digital Invest Inc. parmi les principales entreprises américaines en médecine de précision et santé numérique.",
    "y2023link": "Voir l'article",
    "y2001type": "Prix exécutif",
    "y2001title": "Entrepreneur de l'année",
    "y2001desc": "Reconnaissance Entrepreneur Magazine.",
    "y2001link": "Voir l'archive",
    "y1999type": "Reconnaissance biographique",
    "y1999title": "Who's Who in America",
    "y1999desc": "Reconnaissance dès 1999, suivie d'inscriptions dans Who's Who in the World et Who's Who in Science and Engineering.",
    "clipEyebrow": "Des archives",
    "clipMeta": "Industry Feature · DataPeer Inc.",
    "clipTitle": "State of the Storage Industry",
    "clipLead": "Première interview de Michael Kofman en tant que fondateur, président et CEO de DataPeer Inc. — sur fibre optique, transmission satellite, SAN et marché émergent du stockage.",
    "clipBody": "L'article note la reconnaissance comme Entrepreneur de l'année par Entrepreneur Magazine (2001) et l'approche de DataPeer en stockage critique, iSCSI et continuité d'activité.",
    "clipOpen": "Ouvrir le scan complet →",
    "y2000type": "Entretien",
    "y2000title": "State of the Storage Industry",
    "y2000desc": "Interview feature en tant que fondateur, président et CEO de DataPeer Inc. sur réseaux de stockage, iSCSI et continuité d'activité."
  },
  "ip": {
    "eyebrow": "Propriété intellectuelle",
    "title": "Idées appliquées, documentées",
    "lead": "Brevets, publications et programmes de recherche sélectionnés reliant la rigueur d'ingénierie à des résultats business et sociétaux concrets.",
    "patentEyebrow": "Brevets",
    "patentTitle": "Inventions protégées",
    "patentIntro": "Le travail de brevets reflète un focus durable sur les systèmes améliorant la collecte, le mouvement, la protection et l'interprétation de l'information.",
    "publicationsEyebrow": "Ouvrages publiés",
    "publicationsTitle": "Écrits techniques & exécutifs",
    "publicationsIntro": "Les travaux publiés traduisent des sujets techniques complexes en méthodes, cadres et décisions utiles aux praticiens et dirigeants.",
    "researchEyebrow": "Recherche",
    "researchTitle": "Programmes interdisciplinaires",
    "researchIntro": "Les initiatives de recherche couvrent communications sécurisées, analytique prédictive, interprétation génétique, modélisation humaine digitale et systèmes autonomes."
  },
  "testimonials": {
    "t1quote": "Michael combine la précision d'un ingénieur et le jugement d'un CEO expérimenté. Il pose les questions qui améliorent la décision.",
    "t1name": "Collègue du conseil",
    "t1role": "Entreprise technologique cotée",
    "t2quote": "Sa capacité à relier science, produit, gouvernance et réalité commerciale apporte une clarté rare aux initiatives complexes.",
    "t2name": "Partenaire stratégique",
    "t2role": "Secteur de la santé numérique",
    "t3quote": "Michael est direct, réfléchi et centré sur une valeur durable. Il aide les équipes de direction à voir à la fois l'opportunité et l'obligation.",
    "t3name": "Collaborateur exécutif",
    "t3role": "Infrastructure mondiale"
  },
  "deck": {
    "title": "Michael Kofman",
    "subtitle": "Dirigeant technologique · Fondateur · Conseiller",
    "thesis": "Technologie, business et investissement dans l'infrastructure, les sciences de la vie et les systèmes autonomes.",
    "contact": "Discussion confidentielle : contacter Michael Kofman via mkofman.com"
  },
  "briefIpo": {
    "title": "Ce qu'un IPO change",
    "desc": "Les marchés publics ne changent pas seulement la structure du capital ; ils changent le contrat opérationnel.",
    "p1": "Une introduction en bourse est souvent décrite comme un événement de financement. En pratique, c'est une transition institutionnelle. Prévisions, contrôles, divulgation, gouvernance et communication exécutive doivent être reproductibles avant la cotation, pas improvisés après.",
    "p2": "La préparation commence par la qualité des décisions. La direction a besoin de métriques fiables, d'une propriété claire et d'un rythme opérationnel capable d'expliquer performance et écarts. Une entreprise qui ne réconcilie pas son récit interne peinera à en communiquer un externe crédible.",
    "p3": "Le rôle du conseil change aussi. Les administrateurs doivent équilibrer croissance et supervision, comprendre les risques technologiques et de marché matériels, et veiller à ce que les incitations soutiennent une valeur durable plutôt qu'un seul trimestre.",
    "p4": "Les entreprises cotées les plus solides préservent la vitesse entrepreneuriale tout en ajoutant une discipline institutionnelle. L'objectif n'est pas la bureaucratie, mais une exécution fiable à un niveau supérieur de responsabilité.",
    "eyebrow": "Note exécutive"
  },
  "briefGenetic": {
    "title": "Des données génétiques aux décisions cliniques",
    "desc": "La valeur de l'information génomique dépend de l'interprétation, des preuves et d'une intégration responsable dans les soins.",
    "p1": "Les données génétiques sont abondantes ; la signification cliniquement utile est rare. Un résultat devient précieux seulement s'il est interprété en contexte, relié à des preuves validées et présenté de façon à soutenir une vraie décision.",
    "p2": "Cette traduction exige une collaboration entre biologie moléculaire, médecine, statistiques, ingénierie logicielle et communication patient. Une faiblesse dans une couche peut transformer la sophistication technique en confusion clinique.",
    "p3": "Confidentialité et consentement sont des exigences architecturales, pas des notes juridiques. Les systèmes doivent limiter l'exposition inutile, rendre la provenance visible et préserver l'autonomie du patient lorsque l'information circule entre laboratoires, plateformes et équipes de soins.",
    "p4": "La médecine de précision avancera par une intégration mesurée : meilleures preuves, modèles transparents, workflows interopérables et résultats que cliniciens et patients peuvent évaluer. La confiance fait partie du produit.",
    "eyebrow": "Note exécutive"
  },
  "briefAi": {
    "title": "Stratégie IA au-delà du pilote",
    "desc": "L'IA d'entreprise crée de la valeur lorsque la propriété, les données, les workflows et la gouvernance mûrissent ensemble.",
    "p1": "Beaucoup d'initiatives IA commencent par une démonstration convaincante et s'arrêtent avant la production. Ce qui manque est rarement le modèle seul. Une valeur durable exige un résultat métier défini, un responsable, des données fiables et un workflow réellement adopté.",
    "p2": "Les dirigeants doivent distinguer automatisation, prédiction et aide à la décision. Chacune impose des exigences différentes en précision, explicabilité, revue humaine et risque. Un modèle de gouvernance unique ne convient pas à tous les cas.",
    "p3": "La mesure doit inclure plus que la performance technique. Adoption, délais, taux d'erreur, impact client, exposition sécurité et coût de supervision déterminent si une capacité IA est économiquement et institutionnellement solide.",
    "p4": "L'approche gagnante est un portefeuille géré : scaler les cas prouvés, arrêter tôt les faibles et maintenir des limites explicites pour les décisions à haute conséquence. La stratégie IA est ultimement une stratégie opérationnelle.",
    "eyebrow": "Note exécutive"
  }
};
