window.__LANG_fr = {
  "ui": {
    "toggleTheme": "Changer le thème clair/sombre",
    "selectLanguage": "Choisir la langue",
    "messageSent": "Message envoyé",
    "sendMessage": "Envoyer",
    "toggleNav": "Ouvrir le menu",
    "sending": "Envoi en cours…",
    "formError": "Envoi impossible. Merci d'envoyer un e-mail directement.",
    "present": "Aujourd'hui"
  },
  "nav": {
    "home": "Accueil",
    "about": "Biographie",
    "ventures": "Entreprises",
    "career": "The Record",
    "recognition": "Distinctions",
    "contact": "Contact",
    "consulting": "Conseil",
    "insights": "Perspectives",
    "speaking": "Interventions",
    "caseStudies": "Études de cas",
    "mediaKit": "Kit média",
    "groupMain": "Principal",
    "groupServices": "Services",
    "groupWork": "Réalisations",
    "briefIpo": "Brief: IPO",
    "briefGenetic": "Brief: Genetic Data",
    "briefAi": "Brief: AI Strategy",
    "articleInfra": "Data Infrastructure",
    "articleHealth": "Precision Medicine",
    "board": "Board & Advisory",
    "thesis": "Leadership Thesis",
    "press": "Press",
    "ip": "Intellectual Property"
  },
  "footer": {
    "navigation": "Navigation",
    "ventures": "Entreprises",
    "connect": "Contact",
    "desc": "Dirigeant technologique, fondateur et conseiller de conseils d'administration.",
    "copyright": "© {year} Michael Kofman. Tous droits réservés.",
    "writeTitle": "Écrivez-moi",
    "writeEmail": "Votre email",
    "writeMessage": "Votre message",
    "writeSend": "Envoyer",
    "writeSuccess": "Merci — votre message a été envoyé.",
    "more": "Plus",
    "privacy": "Confidentialité"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — Dirigeant technologique",
      "description": "Dirigeant technologique, fondateur et conseiller — infrastructure, sciences de la vie et systèmes autonomes."
    },
    "about": {
      "title": "Biographie — Michael Kofman",
      "description": "Biographie de Michael Kofman — PDG de Digital Invest Inc., fondateur d'AGRON Inc."
    },
    "ventures": {
      "title": "Entreprises — Michael Kofman",
      "description": "Entreprises fondées et dirigées par Michael Kofman — de Digital Invest Inc. à 9 Net Avenue Inc. — bâtissant des entreprises transformatrices en technologie et santé."
    },
    "career": {
      "title": "The Record — Michael Kofman",
      "description": "Parcours professionnel en ingénierie, infrastructure, marchés publics, sciences de la vie et systèmes autonomes."
    },
    "recognition": {
      "title": "Distinctions — Michael Kofman",
      "description": "Prix, distinctions et reconnaissances de Michael Kofman — Entrepreneur de l'année, Who's Who, brevets et distinctions sectorielles."
    },
    "contact": {
      "title": "Contact — Michael Kofman",
      "description": "Contacter Michael Kofman — PDG de Digital Invest Inc. Pour conférences, mandats de conseil et demandes commerciales."
    },
    "consulting": {
      "title": "Conseil — Michael Kofman",
      "description": "Mandats de conseil, postes au conseil d'administration, conférences et partenariats stratégiques avec Michael Kofman."
    },
    "insights": {
      "title": "Perspectives — Michael Kofman",
      "description": "Écrits originaux et briefs exécutifs de Michael Kofman."
    },
    "speaking": {
      "title": "Interventions — Michael Kofman",
      "description": "Invitez Michael Kofman à intervenir sur le leadership exécutif, la stratégie technologique, la santé numérique et la gouvernance d'entreprise."
    },
    "caseStudies": {
      "title": "Études de cas — Michael Kofman",
      "description": "Études de cas issues de la carrière de Michael Kofman : 9 Net Avenue Inc. et Digital Invest Inc."
    },
    "mediaKit": {
      "title": "Kit média — Michael Kofman",
      "description": "Biographies officielles, photos et informations de contact pour la presse et les organisateurs d'événements."
    },
    "article1": {
      "title": "De l'ingénierie à l'infrastructure mondiale — Michael Kofman",
      "description": "Michael Kofman revient sur son parcours, de l'ingénierie satellitaire à la création d'entreprises mondiales d'infrastructure de données."
    },
    "article2": {
      "title": "Médecine de précision et technologie — Michael Kofman",
      "description": "Michael Kofman sur la convergence des sciences de la vie avec l'IA, le ML et les technologies ADN dans la médecine moderne."
    },
    "privacy": {
      "title": "Politique de confidentialité — Michael Kofman",
      "description": "Politique de confidentialité de mkofman.com — formulaires et analytique."
    },
    "board": {
      "title": "Board Advisory — Michael Kofman",
      "description": "Board service and strategic advisory from Michael Kofman for technology, healthcare, infrastructure, and growth-stage organizations."
    },
    "thesis": {
      "title": "Leadership Thesis — Michael Kofman",
      "description": "Michael Kofman's principles for building durable companies, governing technology, and leading through consequential change."
    },
    "press": {
      "title": "Press Archive — Michael Kofman",
      "description": "Selected press coverage, awards, and media references spanning Michael Kofman's career in technology and entrepreneurship."
    },
    "ip": {
      "title": "Intellectual Property — Michael Kofman",
      "description": "Patents, publications, and applied research by Michael Kofman across computing, communications, data, and digital health."
    },
    "briefIpo": {
      "title": "What an IPO Changes — Michael Kofman",
      "description": "An executive brief on the operating discipline, governance, and accountability required before and after an initial public offering."
    },
    "briefGenetic": {
      "title": "From Genetic Data to Clinical Decisions — Michael Kofman",
      "description": "An executive brief on translating genomic information into responsible, useful, and scalable clinical intelligence."
    },
    "briefAi": {
      "title": "AI Strategy Beyond the Pilot — Michael Kofman",
      "description": "An executive brief on moving artificial intelligence from experimentation to governed, measurable enterprise capability."
    },
    "deck": {
      "title": "Executive Overview — Michael Kofman",
      "description": "Private executive overview for qualified introductions."
    }
  },
  "home": {
    "heroEyebrow": "Site officiel de Michael Kofman",
    "heroTitle1": "Construit pour durer.",
    "heroTitle2": "Dirigé avec discernement.",
    "heroCta": "Découvrir mon parcours",
    "heroAlt": "Michael Kofman",
    "quote1text": "Figurant parmi les principales entreprises américaines en médecine de précision et santé numérique.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "Entrepreneur de l'année — reconnu pour son leadership et ses réalisations en innovation de plateformes et infrastructure.",
    "quote2author": "Entrepreneur Magazine · 2001",
    "quote3text": "Digital Invest Inc. parmi les 10 meilleures entreprises américaines en médecine de précision et santé numérique.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "Précision d'ingénierie et stratégie commerciale — des systèmes satellites à une infrastructure de",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "Michael Kofman",
    "aboutTitle": "Des entreprises faites pour durer",
    "aboutLead1": "PDG de Digital Invest Inc. et fondateur d'AGRON Inc. Il a fondé et dirigé des entreprises aux États-Unis et en Europe.",
    "aboutLead2": "De 9 Net Avenue (valorisation pic de",
    "aboutLink": "Biographie complète",
    "expertiseEyebrow": "Domaines d'intervention",
    "expertiseTitle": "Leadership exécutif",
    "expertiseLead": "Quatre décennies de création, de conseil et d'investissement dans l'infrastructure, la santé et la robotique.",
    "exp1title": "PDG & fondateur",
    "exp1desc": "A fondé et dirigé plusieurs entreprises technologiques aux États-Unis et en Europe.",
    "exp1link": "Entreprises →",
    "exp2title": "Architecte technologique",
    "exp2desc": "A conçu des communications sécurisées, des moteurs d'analyse prédictive et des plateformes d'intégration de données à l'échelle nationale pour les secteurs gouvernemental, militaire et télécom.",
    "exp2link": "Carrière →",
    "exp3title": "Santé numérique",
    "exp3desc": "Dirige la transformation de la médecine grâce à l'IA, au ML et aux technologies ADN. A collaboré avec Harvard Medical School et Stanford Biomath sur les rapports génétiques.",
    "exp3link": "Digital Invest →",
    "exp4title": "Conseiller du conseil",
    "exp4desc": "Siège au conseil d'administration et conseille des entreprises publiques et privées sur l'orientation stratégique, la gouvernance et la croissance portée par la technologie.",
    "exp4link": "Conseil →",
    "stat1": "Années de leadership",
    "stat2": "Entreprises fondées",
    "stat3": "Valeur de marché max.",
    "stat4": "Employés",
    "recEyebrow": "Distinctions",
    "recTitle": "Distinctions sélectionnées",
    "recLead": "Honneurs documentés et références sectorielles issues des archives.",
    "award1title": "Entrepreneur de l'année",
    "award1desc": "Entrepreneur Magazine · 2001",
    "award2title": "Reconnaissance en médecine de précision",
    "award2desc": "Healthcare Tech Outlook · Digital Invest Inc. · 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "Distinctions et presse →",
    "heroSub": "Technologie, business et investissement dans l'infrastructure, les sciences de la vie et les systèmes autonomes.",
    "primaryCta": "Demander un accompagnement",
    "secondaryCta": "Voir les études de cas",
    "featuredEyebrow": "Vu dans",
    "caseStudiesEyebrow": "Résultats prouvés",
    "caseStudiesTitle": "Études de cas",
    "caseStudiesLead": "Création, développement et direction d'entreprises de leur lancement jusqu'à l'acquisition.",
    "caseStudiesLink": "Voir toutes les études de cas →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "Founded 9 Net Avenue Inc.; acquired by Concentric Networks in 2000.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "Healthcare Tech Outlook feature (2023).",
    "cs3title": "AGRON Inc.",
    "cs3desc": "Founded in 2026 — the AGRON Ecosystem for UAV capability development, geospatial systems, and maritime intelligence.",
    "boardCtaEyebrow": "Board & Advisory",
    "boardCtaTitle": "Experience for the Decisions That Define an Enterprise",
    "boardCtaLead": "Independent perspective for boards and leaders navigating technology, governance, transformation, and growth.",
    "boardCtaBtn": "Explore Board Advisory",
    "testimonialsEyebrow": "Trusted Perspective",
    "testimonialsTitle": "What Colleagues Value",
    "videoEyebrow": "Executive Perspective",
    "videoTitle": "Leadership at the Intersection of Technology and Enterprise",
    "videoLead": "A concise introduction to the principles, experience, and long-term perspective behind Michael Kofman's work.",
    "videoCta": "Read Leadership Thesis →",
    "heroName": "Michael Kofman",
    "heroRole": "Dirigeant technologique · Fondateur · Conseiller",
    "introText": "Michael Kofman est dirigeant technologique et fondateur d'entreprises. Son parcours couvre l'ingénierie satellitaire, l'infrastructure internet, les sociétés technologiques cotées et les sciences de la vie. Il a fondé 9 Net Avenue Inc., acquise par Concentric Networks en 2000. Il est CEO de Digital Invest Inc., en médecine biomathématique et intelligence génomique, et fondateur d'AGRON Inc., en opérations autonomes aéro-terrestres et systèmes géospatiaux. Il siège à des conseils et conseille dans la technologie, la santé et l'infrastructure.",
    "introLink": "Biographie complète →",
    "currentEyebrow": "Travail actuel",
    "currentTitle": "Priorités actuelles",
    "currentDiTitle": "Digital Invest Inc.",
    "currentDiDesc": "Médecine biomathématique, données génomiques et intelligence clinique — IA, machine learning et technologies ADN au service de la santé.",
    "currentDiLink": "Entreprises →",
    "currentAgTitle": "AGRON Inc.",
    "currentAgDesc": "Opérations autonomes aéro-terrestres, développement de capacités UAV, systèmes géospatiaux et infrastructure de renseignement maritime.",
    "currentAgLink": "agron1.com →",
    "careerEyebrow": "Dossier sélectionné",
    "careerTitle": "Continuité à travers les périodes technologiques",
    "careerLead": "Jalons sélectionnés de l'ingénierie aux systèmes autonomes actuels.",
    "career1title": "Ingénierie et communications",
    "career1desc": "Systèmes émetteurs-récepteurs satellitaires, communications numériques et premiers rôles d'ingénierie.",
    "career2title": "Internet et infrastructure",
    "career2desc": "Infrastructure internet, centres de données, stockage et télécommunications à grande échelle.",
    "career3title": "Entreprises technologiques et marchés publics",
    "career3desc": "Création d'entreprises, acquisitions et expérience de sociétés cotées, dont 9 Net Avenue Inc.",
    "career4title": "Sciences de la vie et données humaines",
    "career4desc": "Biotechnologie, données génétiques, médecine de précision et plateformes d'intelligence santé.",
    "career5title": "Systèmes autonomes",
    "career5desc": "Robotique aéro-terrestre, opérations UAV et infrastructure géospatiale.",
    "careerLink": "The Record →",
    "perspectivesEyebrow": "Perspectives",
    "perspectivesTitle": "Selected Writing",
    "perspectivesLink": "All insights →",
    "footerHomeDesc": "Dirigeant technologique, fondateur et conseiller."
  },
  "about": {
    "eyebrow": "À propos",
    "title": "Trois décennies de parcours",
    "lead": "Dirigeant technologique, fondateur et conseiller.",
    "glance": "En bref",
    "role": "Rôle actuel",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "Localisation",
    "locationVal": "Charlotte, North Carolina",
    "education": "Formation",
    "educationVal": "Doctor of Technical Sciences\nPh.D. in Information Technology\nMaster's in Electronic Engineering",
    "university": "Université",
    "universityVal": "Ukrainian State Marine Technical University",
    "languages": "Langues",
    "languagesVal": "English, Russian, Ukrainian",
    "contactLabel": "Contact",
    "principlesEyebrow": "Operating Principles",
    "principlesTitle": "How I Lead",
    "p1title": "Understand the System",
    "p1text": "Before changing an organization, understand its incentives, architecture, constraints, and sources of trust.",
    "p2title": "Make Accountability Explicit",
    "p2text": "Clear ownership and measurable outcomes turn strategy from presentation material into operating reality.",
    "p3title": "Leave Stronger Institutions",
    "p3text": "Leadership should compound capability by developing people, improving decisions, and building systems that endure.",
    "archiveEyebrow": "From the Archive",
    "archiveTitle": "De l'archive",
    "archiveLead": "Authentic material from company building, infrastructure, and leadership.",
    "photo9netTitle": "9 Net Avenue",
    "photo9netCaption": "Founder & CEO — hosting and internet infrastructure company, acquired by Concentric Networks in 2000.",
    "photoServerTitle": "Data Infrastructure",
    "photoServerCaption": "Hands-on years in storage, networking, and high-density server environments at DataPeer and related ventures.",
    "photoTodayTitle": "Today",
    "photoTodayCaption": "Digital Invest Inc., AGRON Inc., and board advisory work.",
    "secIntroTitle": "Introduction",
    "secTechTitle": "Technologie & infrastructure",
    "secBusinessTitle": "Business",
    "secCurrentTitle": "Current Work",
    "secBackgroundTitle": "Background",
    "recordLink": "The Record →",
    "secBackgroundP1": "Doctor of Technical Sciences et Ph.D. in Information Technology. Auteur de travaux techniques; brevet HDTV satellitaire acquis par Sony.",
    "bioP1": "Michael Kofman est dirigeant technologique, fondateur et conseiller. Il est CEO de Digital Invest Inc. et fondateur d'AGRON Inc., avec une expérience en ingénierie satellitaire, infrastructure internet, sociétés technologiques cotées et sciences de la vie aux États-Unis et en Europe.",
    "bioP2": "As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. In 2026 he founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network. He also created Digital Invest, dedicated to the bio-mathematical sphere and transforming medicine through science, DNA technologies, AI, and ML.",
    "secBioTitle": "Médecine de précision & biotechnologie",
    "secBioP1": "Avant Digital Invest, il a joué un rôle déterminant dans le succès de Biotechnology Group Inc. (2008–2014), une entreprise engagée dans les tests et analyses ADN, l'automatisation de la création de profils génétiques et la recherche génétique humaine complète. M. Kofman croit fermement au potentiel de la combinaison des sciences de la vie avec les dernières avancées technologiques.",
    "secBioP2": "Sous sa direction, des projets de tests génétiques réussis ont été lancés en Ukraine, en Russie et dans les pays baltes. Cette expérience unique est continuellement enrichie par des technologies modernes et de nouveaux équipements. En collaboration avec la Harvard Medical School et Stanford Biomath, M. Kofman a joué un rôle crucial dans le développement de rapports génétiques facilement compréhensibles pour les médecins et les patients. Cette approche innovante a été largement adoptée par les laboratoires de premier plan aux États-Unis et à l'étranger.",
    "secTechP1": "Formation en systèmes émetteurs-récepteurs satellitaires au Nikolaev Shipbuilding Plant et communications numériques chez Astra Corp.",
    "secTechP2": "En 2006, M. Kofman a fondé XIBI Group Inc. — une entreprise technologique dont il siégeait au conseil d'administration. La société américaine est spécialisée dans le stockage de données et les services de gestion du big data pour les grandes organisations commerciales et gouvernementales.",
    "secTechP3": "De 2000 à 2004, M. Kofman a dirigé DataPeer Inc. — une entreprise de gestion et de stockage de données offrant un large éventail de services liés au stockage d'informations pour les petites et moyennes entreprises. Chez DataPeer, il a développé des solutions technologiques uniques facilitant un suivi plus rapide des informations et un accès plus simple aux données pour les utilisateurs finaux et les institutions gouvernementales du monde entier.",
    "secTechP4": "En 1996, M. Kofman a fondé 9 Net Avenue Inc. L'entreprise est rapidement devenue l'un des plus grands hébergeurs au monde. En 2000, 9 Net Avenue a été acquise par Concentric Networks (NASDAQ: CNTX), puis par XO Communications (NASDAQ: XOXO), atteignant une valeur boursière maximale de 2000",
    "secPost9NetP1": "Après l'acquisition de 9 Net Avenue, M. Kofman a acquis une vaste expérience au sein d'entreprises cotées en bourse, de participation aux conseils d'administration et de prise de décisions stratégiques au plus haut niveau exécutif.",
    "secEarlyTitle": "Débuts de carrière & ingénierie",
    "secEarlyP1": "De 1994 à 1996, M. Kofman a été PDG et directeur des technologies de l'information chez Elitan United Inc. — une entreprise informatique du Massachusetts offrant des stratégies complètes et des services technologiques aux principales organisations mondiales. Il a joué un rôle central dans le développement et la gestion d'une infrastructure évolutive, faisant passer l'entreprise de neuf à plus de 4 000 employés dans le monde.",
    "secEarlyP2": "De 1989 à 1994, il a été fondateur et PDG d'Astra Corp, l'un des plus grands fabricants européens de systèmes satellitaires de transception numérique, reconnu internationalement dans le domaine des dispositifs satellitaires. Ses responsabilités comprenaient la recherche, le développement de systèmes d'exploitation, les applications logicielles réseau et la stratégie technique globale.",
    "secEarlyP3": "De 1984 à 1989, M. Kofman a travaillé au chantier naval de Nikolaev, en Ukraine, où il a activement participé au développement et à la création de systèmes de transception satellitaire pour transmettre des informations classifiées aux navires militaires et en retour. Il a été reconnu comme ingénieur électronicien du plus haut niveau, recevant la 6e catégorie — la plus haute distinction du chantier, qui comptait 93 000 employés.",
    "secResearchTitle": "Recherche & brevets",
    "secResearchP1": "Michael Kofman est l'auteur de travaux techniques sur les systèmes satellitaires et optiques de transmission de données. Il a également obtenu un brevet dans le domaine des systèmes de télévision haute définition (HDTV) par satellite numérique, ultérieurement acquis par Sony.",
    "secAgronTitle": "Robotics, UAV & Maritime Intelligence",
    "secAgronP1": "In 2026, Mr. Kofman founded AGRON Inc. to build the AGRON Ecosystem — a corporate operating architecture for aerial and ground robotics, governed mission execution, and network infrastructure connecting teams, assets, and operational data. The ecosystem delivers consulting, assessment, capability development, and training for UAV and Counter-UAS organizations, alongside maritime intelligence and security services at agron1.com.",
    "secBusinessP1": "A fondé et dirigé plusieurs entreprises technologiques, dont 9 Net Avenue Inc., DataPeer Inc., XIBI Group Inc. et Elitan United Inc. Chronologie complète dans The Record.",
    "secCurrentP1": "CEO de Digital Invest Inc. en médecine biomathématique et intelligence génomique. Fondateur d'AGRON Inc. en opérations autonomes aéro-terrestres et systèmes géospatiaux."
  },
  "ventures": {
    "eyebrow": "Portefeuille",
    "title": "Entreprises fondées et dirigées",
    "lead": "De la médecine de précision et la robotique à l'infrastructure mondiale de données — fondées, développées et dirigées aux États-Unis et en Europe.",
    "ecosystemEyebrow": "Venture Ecosystem",
    "ecosystemTitle": "Companies Across Technology Frontiers",
    "ecosystemLead": "A portfolio shaped by recurring themes: trusted data, intelligent infrastructure, human health, and systems built for scale.",
    "statusActive": "Active",
    "statusExited": "Exited",
    "statusLegacy": "Legacy",
    "v1lesson": "Lesson: infrastructure wins when reliability, economics, and customer trust improve together.",
    "v2lesson": "Lesson: precision medicine requires equal discipline in science, software, privacy, and clinical usefulness.",
    "v3lesson": "Lesson: autonomy creates value only when sensing, communications, and human oversight form one resilient system.",
    "v5lesson": "Leçon : l'échelle en infrastructure se gagne par l'excellence opérationnelle bien avant la sortie.",
    "currentEyebrow": "Current",
    "historyEyebrow": "Selected History",
    "v2highlight": "Harvard Medical School et Stanford Biomath — collaboration sur les rapports génétiques",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — an Aerial-Ground Robotics Operations Network spanning UAV and Counter-UAS consulting, technology assessment, capability development, training infrastructure, product validation, geospatial systems (ISDRI), and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "v0role": "Founder",
    "v0year": "2026 — Present",
    "v1highlight": "Top 10 entreprise de médecine de précision aux États-Unis — 2023",
    "v1p1": "Médecine biomathématique, données génomiques et intelligence clinique — IA, ML et technologies ADN appliquées aux workflows cliniques et de recherche.",
    "v1role": "Fondateur & PDG · Membre du conseil",
    "v1year": "2021 — Aujourd'hui",
    "v2p1": "Tests et analyses ADN, automatisation du profilage génétique et recherche génétique humaine complète. Lancement de projets de tests génétiques en Ukraine, en Russie et dans les pays baltes.",
    "v2p2": "Collaboration avec la Harvard Medical School et Stanford Biomath sur des rapports génétiques adoptés par les laboratoires de premier plan dans le monde entier.",
    "v2role": "PDG & CTO",
    "v2year": "2008 — 2014",
    "v3highlight": "Solutions de données d'entreprise & gouvernementales",
    "v3p1": "Stockage de données et services de gestion du big data pour les grandes organisations commerciales et gouvernementales. Établissement de l'entreprise comme fournisseur de confiance de solutions de données d'entreprise.",
    "v3role": "Fondateur & PDG · Conseil d'administration",
    "v3year": "2006 — 2011",
    "v4highlight": "Plateforme mondiale de gestion de données",
    "v4p1": "Gestion et stockage de données pour les petites et moyennes entreprises. Développement de solutions pour un suivi plus rapide des informations et un accès plus simple aux données pour les utilisateurs finaux et les institutions gouvernementales du monde entier.",
    "v4role": "Fondateur & PDG",
    "v4year": "2000 — 2004",
    "v5highlight": "Acquise · Valeur maximale de 2000",
    "v5p1": "Construction de l'un des plus grands hébergeurs au monde. En 2000, acquisition par Concentric Networks (NASDAQ: CNTX), puis XO Communications (NASDAQ: XOXO), atteignant une valeur boursière maximale de 2000",
    "v5role": "Fondateur & PDG",
    "v5year": "1996 — 2000",
    "v6highlight": "Stratégie informatique & infrastructure mondiale",
    "v6p1": "Entreprise informatique du Massachusetts offrant des stratégies complètes et des services technologiques aux principales organisations mondiales. Direction du développement d'infrastructures évolutives et des opérations informatiques mondiales.",
    "v6role": "PDG & Directeur des technologies de l'information",
    "v6year": "1994 — 1996",
    "v7highlight": "Leader européen des systèmes satellitaires",
    "v7p1": "L'un des plus grands fabricants européens de systèmes satellitaires de transception numérique. Direction de la recherche, du développement de systèmes d'exploitation, des applications logicielles réseau et de la stratégie technique globale.",
    "v7role": "Fondateur & PDG",
    "v7year": "1989 — 1994",
    "v8highlight": "Ingénierie de systèmes satellitaires militaires",
    "v8p1": "Développement et création de systèmes de transception satellitaire pour transmettre des informations classifiées aux navires militaires. Reconnu comme ingénieur électronicien du plus haut niveau dans un chantier naval de 93 000 employés.",
    "v8role": "Ingénieur électronicien · Catégorie maximale (6e)",
    "v8year": "1984 — 1989"
  },
  "career": {
    "eyebrow": "Parcours professionnel",
    "title": "The Record",
    "lead": "Technologie, entreprises et expérience opérationnelle à travers des périodes de changement technologique.",
    "timelineEyebrow": "Chronologie",
    "timelineTitle": "Jalons clés",
    "strengthsEyebrow": "Forces",
    "strengthsTitle": "Domaines d'expertise",
    "filterAll": "All",
    "filterHealthcare": "Healthcare",
    "filterInfrastructure": "Infrastructure",
    "filterDefense": "Defense",
    "filterTelecom": "Telecommunications",
    "periodCurrent": "Autonomous Systems",
    "periodCurrentLead": "AI, robotics, autonomous operations, geospatial systems, and related current infrastructure.",
    "period1title": "Engineering & Communications",
    "period1lead": "Early engineering, satellite systems, communications, and related technology work.",
    "period2title": "Internet & Infrastructure",
    "period2lead": "Internet infrastructure, telecommunications, data centers, storage, and related companies.",
    "period3title": "Companies & Public Markets",
    "period3lead": "Company building, transactions, public-company involvement, and executive roles.",
    "period4title": "Life Sciences & Human Data",
    "period4lead": "Biotechnology, health-related technology, data, and precision medicine.",
    "period5title": "Government & Defense Programs",
    "period5lead": "Technology strategy and delivery for government, defense, and state-owned enterprise programs.",
    "t1desc": "Digital Invest Inc., fondée en 2021. Médecine biomathématique, intelligence génomique et plateformes de données cliniques. Healthcare Tech Outlook (2023).",
    "t0desc": "Founded AGRON Inc. to build the AGRON Ecosystem — consulting, assessment, capability development, training infrastructure, and product support for UAV and Counter-UAS programmes, plus AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure. Connects aerial and ground robotics, governed mission execution, and network infrastructure linking teams, assets, and operational data.",
    "t0role": "Founder",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — Present",
    "t10desc": "Développement et création de systèmes de transception satellitaire pour transmettre des informations classifiées aux navires militaires. Reconnu comme ingénieur électronicien du plus haut niveau dans un chantier naval de 93 000 employés — le début d'une carrière distinguée en technologie et innovation.",
    "t10role": "Ingénieur électronicien — 6e catégorie (maximale)",
    "t10title": "Chantier naval de Nikolaev",
    "t10year": "1984 — 1989",
    "t1role": "Fondateur & PDG",
    "t1title": "Digital Invest Inc.",
    "t1year": "2021 — Aujourd'hui",
    "t2desc": "Direction de la stratégie et de la mise en œuvre technologiques pour des programmes classifiés et hautement sensibles impliquant des agences gouvernementales américaines, des systèmes de défense alliés et des entreprises d'État. Direction de projets techniques complexes pour des sociétés publiques dans de multiples secteurs. À la suite du 11 septembre 2001, direction d'initiatives gouvernementales à grande échelle centrées sur le big data, les communications sécurisées, l'analytique prédictive et l'intégration des données au niveau national — y compris la conception, la construction et l'exploitation de centres de données à haut débit aux États-Unis et en Europe. Interface avec les responsables de programmes militaires, les fournisseurs technologiques et les entités réglementaires.",
    "t2role": "Conseiller technologique principal / Architecte de programmes",
    "t2title": "GovTech, défense & programmes d'État",
    "t2year": "2001 — 2019",
    "t3desc": "Direction des tests et analyses ADN, de l'automatisation du profilage génétique et de la recherche génétique humaine complète. Lancement de projets de tests génétiques en Ukraine, en Russie et dans les pays baltes. Collaboration avec la Harvard Medical School et Stanford Biomath pour développer des rapports génétiques compréhensibles adoptés par les laboratoires de premier plan dans le monde entier.",
    "t3role": "PDG & CTO",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4desc": "Direction des déploiements d'infrastructures nationales au Canada, en Italie, en Suisse, en Ukraine et dans les républiques baltes. Supervision de plus de 1 000 ingénieurs et personnel de déploiement dans les opérations télécoms, y compris les systèmes de commutation, l'expansion de la bande passante et la connectivité transfrontalière. Mise en œuvre de systèmes centraux de redondance réseau, d'optimisation de la disponibilité et de routage intelligent.",
    "t4role": "VP Technologie / CTO régional — Europe de l'Est & CEI",
    "t4title": "Projets de télécommunications",
    "t4year": "2000 — 2012",
    "t5desc": "Fondation d'une entreprise technologique spécialisée dans le stockage de données et la gestion du big data pour les grandes organisations commerciales et gouvernementales. Établissement de l'entreprise comme fournisseur de confiance de solutions de données d'entreprise.",
    "t5role": "Fondateur & PDG · Conseil d'administration",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6desc": "Création d'une entreprise de gestion et de stockage de données pour les PME. Développement de solutions technologiques uniques pour un suivi plus rapide des informations et un accès plus simple aux données pour les utilisateurs finaux et les institutions gouvernementales du monde entier.",
    "t6role": "Fondateur & PDG",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "Construction de l'un des plus grands hébergeurs au monde. En 2000, acquisition par Concentric Networks (NASDAQ: CNTX), puis XO Communications (NASDAQ: XOXO), atteignant une valeur boursière maximale de 2000",
    "t7role": "Fondateur & PDG",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8desc": "Direction de stratégies informatiques complètes et de services technologiques pour les principales organisations mondiales depuis le Massachusetts pendant une période d'expansion rapide, en construisant une infrastructure évolutive et des opérations informatiques mondiales.",
    "t8role": "PDG & Directeur des technologies de l'information",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9desc": "Fondation de l'un des plus grands fabricants européens de systèmes satellitaires de transception numérique. Direction de la recherche, du développement de systèmes d'exploitation, des applications logicielles réseau et de la stratégie technique globale, obtenant une reconnaissance internationale.",
    "t9role": "Fondateur & PDG",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994"
  },
  "recognition": {
    "eyebrow": "Distinctions",
    "title": "Prix et reconnaissance",
    "lead": "Distinctions en entrepreneuriat, médecine de précision, ingénierie et leadership exécutif.",
    "industryEyebrow": "Prix du secteur",
    "industryTitle": "Grandes distinctions",
    "ipEyebrow": "Propriété intellectuelle",
    "ipTitle": "Brevets et publications",
    "eduEyebrow": "Formation",
    "eduTitle": "Diplômes",
    "pressEyebrow": "Presse",
    "pressTitle": "Vu dans",
    "moreLink": "Voir les brevets, publications et mentions presse dans Insights →",
    "a1title": "Entrepreneur de l'année",
    "a1desc": "Entrepreneur Magazine · 2001",
    "a2title": "Top 10 entreprise de médecine de précision aux États-Unis",
    "a2desc": "Digital Invest Inc. reconnue parmi les 10 meilleures entreprises américaines de médecine de précision et de santé numérique — 2023.",
    "a3title": "Who's Who in America",
    "a3desc": "Inscrit, 1999 — 2018 — pour des réalisations exceptionnelles en création et développement d'entreprises.",
    "a4title": "Who's Who in the World",
    "a4desc": "Inscrit, 2000 — 2004 — parmi les leaders mondiaux en science, ingénierie et innovation entrepreneuriale.",
    "a5title": "Who's Who in Science & Engineering",
    "a5desc": "Inscrit, 2000 — 2014 — pour des contributions à la technologie, aux systèmes satellitaires et à l'infrastructure numérique.",
    "a6title": "Ingénieur électronicien — 6e catégorie",
    "a6desc": "Plus haute distinction au chantier naval de Nikolaev (93 000 employés) pour l'ingénierie de systèmes de transception satellitaire.",
    "ip1year": "Brevet",
    "ip1title": "Systèmes HDTV satellitaires numériques",
    "ip1role": "Ultérieurement acquis par Sony",
    "ip1desc": "Brevet pour systèmes HDTV satellitaires numériques, acquis par Sony Corporation.",
    "ip2year": "Publications",
    "ip2title": "Travaux techniques",
    "ip2role": "Systèmes satellitaires & optiques",
    "ip2desc": "Auteur de travaux techniques sur les systèmes satellitaires et optiques de transmission de données. Les contributions de recherche couvrent le traitement du signal, la modélisation par simulation et les plateformes d'automatisation appliquées aux télécommunications, à l'infrastructure nationale et à la santé numérique.",
    "ip3year": "Recherche",
    "ip3title": "Collaborations internationales",
    "ip3role": "États-Unis & Europe",
    "ip3desc": "Participation à des collaborations de recherche internationales et à des initiatives de transfert de connaissances. Développement de systèmes d'ingénierie embarqués pour l'acquisition de données, le diagnostic prédictif et l'orchestration cloud dans de multiples industries.",
    "edu1title": "Docteur en sciences techniques",
    "edu2title": "Doctorat en technologies de l'information",
    "edu3title": "Masters",
    "edu3desc": "Électronique, systèmes satellitaires numériques et économie",
    "press1title": "Healthcare Tech Outlook",
    "press1role": "Article sur Digital Invest Inc.",
    "press1desc": "Healthcare Tech Outlook sur Digital Invest Inc. et médecine de précision (2023).",
    "press1link": "Lire l'article →",
    "press2title": "Top Precision Medicine Solutions",
    "press2role": "Reconnaissance du secteur",
    "press2desc": "Classée parmi les principales entreprises de solutions de médecine de précision, soulignant le rôle de Digital Invest dans l'avancement des approches bio-mathématiques en santé moderne.",
    "press2link": "Voir le classement →"
  },
  "contact": {
    "eyebrow": "Contact",
    "title": "Restons en contact",
    "lead": "Pour des rôles de conseil, conseils d'administration et partenariats.",
    "infoTitle": "Contact direct",
    "email": "E-mail",
    "phone": "Téléphone",
    "location": "Localisation",
    "locationVal": "Charlotte, North Carolina\nUnited States",
    "linkedin": "LinkedIn",
    "company": "Entreprise actuelle",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member\nAGRON Inc.\nFounder",
    "formTitle": "Envoyer un message",
    "formLead": "Remplissez le formulaire ci-dessous.",
    "firstName": "Prénom",
    "lastName": "Nom",
    "emailLabel": "Adresse e-mail",
    "subject": "Objet",
    "message": "Message",
    "inquiryType": "Inquiry Type",
    "inquiryAdvisory": "Advisory / Board Role",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "calendlyEyebrow": "Schedule a Conversation",
    "calendlyTitle": "Choose a Convenient Time",
    "calendlyLead": "For qualified board, advisory, speaking, and strategic partnership inquiries.",
    "calendlyPlaceholder": "Scheduling calendar will appear here.",
    "calendlyCta": "Open Scheduling Calendar",
    "inquiryBusiness": "Business",
    "infoEyebrow": "Coordonnées"
  },
  "consulting": {
    "eyebrow": "Services de conseil",
    "title": "Conseil",
    "heroEyebrow": "Orientation stratégique des entreprises",
    "heroTitle": "Conseil stratégique",
    "heroLead": "Trente-cinq ans à fonder et conseiller des entreprises aux États-Unis et en Europe — infrastructure de données, govtech, médecine de précision et robotique.",
    "cta": "Contacter Michael Kofman",
    "introLead": "PDG de Digital Invest Inc. et membre du conseil. Axes : technologies émergentes, sécurité, recherche et allocation de capital.",
    "specialtiesEyebrow": "Domaines d'intervention",
    "specialtiesTitle": "Les spécialités de Michael Kofman",
    "area1title": "Board Service",
    "area1desc": "Independent director and board-level work in technology strategy, corporate governance, and growth-stage oversight.",
    "area2title": "CEO & Founder Advisory",
    "area2desc": "Corporate and technology strategy, organizational development, transactions, and applicable capital-markets experience.",
    "area3title": "Technology Due Diligence",
    "area3desc": "Evaluation of infrastructure, data platforms, security architecture, and applied technology based on documented operating experience."
  },
  "insights": {
    "eyebrow": "Perspectives",
    "title": "Perspectives",
    "heroTitle": "Perspectives exécutives",
    "selectedEyebrow": "Points saillants",
    "selectedTitle": "Reconnaissance en vedette",
    "allPressTitle": "Toutes les parutions presse",
    "quotesEyebrow": "Dans les médias",
    "quotesTitle": "Reconnaissance sectorielle et citations",
    "articlesEyebrow": "Points de vue",
    "articlesTitle": "Perspectives dirigeantes",
    "briefsEyebrow": "Executive Briefs",
    "briefsTitle": "Ideas for Leaders",
    "briefsLead": "Short, practical perspectives on governance, technology, healthcare, and company building.",
    "brief1title": "What an IPO Changes",
    "brief1desc": "The operating and governance disciplines that public-market readiness demands.",
    "brief1tag": "Capital Markets",
    "brief2title": "From Genetic Data to Clinical Decisions",
    "brief2desc": "How to build useful health intelligence without outrunning evidence or trust.",
    "brief2tag": "Precision Medicine",
    "brief3title": "AI Strategy Beyond the Pilot",
    "brief3desc": "A framework for turning experiments into governed enterprise capability.",
    "brief3tag": "Artificial Intelligence",
    "readingEyebrow": "Reading List",
    "readingTitle": "Books That Shape Strategic Thinking",
    "r1title": "The Innovator's Dilemma",
    "r1author": "Clayton M. Christensen",
    "r2title": "Thinking, Fast and Slow",
    "r2author": "Daniel Kahneman",
    "r3title": "The Beginning of Infinity",
    "r3author": "David Deutsch",
    "r4title": "Good Strategy/Bad Strategy",
    "r4author": "Richard Rumelt",
    "r5title": "The Structure of Scientific Revolutions",
    "r5author": "Thomas S. Kuhn",
    "newsletterEyebrow": "Occasional Notes",
    "newsletterTitle": "Executive Perspective, Without the Noise",
    "newsletterLead": "Periodic essays and brief observations on technology, governance, and durable company building.",
    "newsletterCta": "Subscribe for Updates",
    "lead": "Substantive writing and executive briefs.",
    "relatedLead": "Recognition, press coverage, and patents are documented separately.",
    "topicsLead": "Les thèmes s'appuient sur une expérience opérationnelle documentée en technologie, santé et infrastructure."
  },
  "cta": {
    "eyebrow": "Collaborons",
    "title": "Demander un accompagnement ou une intervention",
    "lead": "Pour des rôles de conseil, des mandats d'administrateur, des interventions et des partenariats stratégiques.",
    "button": "Prendre contact"
  },
  "speaking": {
    "eyebrow": "Interventions",
    "title": "Inviter Michael Kofman à intervenir",
    "lead": "Disponible pour des interventions sur le leadership exécutif, la stratégie technologique, la santé numérique, l'infrastructure de données et la gouvernance d'entreprise.",
    "topicsEyebrow": "Thèmes d'intervention",
    "topicsTitle": "Domaines d'expertise",
    "topicsLead": "Les thèmes s'appuient sur des décennies d'expérience dans la création et la direction d'entreprises aux États-Unis et en Europe.",
    "processEyebrow": "Comment inviter",
    "processTitle": "Processus de réservation",
    "process1title": "Envoyer une demande",
    "process1desc": "Utilisez le formulaire de contact ou écrivez à mkofman@mkofman.com avec les détails de l'événement, le public et les thèmes souhaités.",
    "process2title": "Valider le périmètre",
    "process2desc": "Définissez le format (keynote, panel, session de conseil d'administration ou table ronde exécutive) et la logistique.",
    "process3title": "Créer de la valeur",
    "process3desc": "Les interventions s'appuient sur des résultats concrets obtenus dans le data storage, la govtech et la médecine de précision.",
    "cta": "Demander une intervention",
    "catalogEyebrow": "Speaking Topics",
    "catalogTitle": "Executive Conversations for Consequential Change",
    "catalogLead": "Keynotes, board sessions, and leadership briefings tailored to the audience, sector, and decision context.",
    "t1title": "Governing AI Before It Governs the Enterprise",
    "t1audience": "Boards, audit and risk committees",
    "t1format": "Board briefing or keynote",
    "t2title": "From Technology Trend to Enterprise Strategy",
    "t2audience": "CEOs, executive teams, investors",
    "t2format": "Keynote or executive workshop",
    "t3title": "Building Companies Through Market Cycles",
    "t3audience": "Founders, growth leaders, private equity",
    "t3format": "Fireside chat or keynote",
    "t4title": "Precision Medicine: Promise, Proof, and Responsibility",
    "t4audience": "Healthcare leaders, clinicians, innovators",
    "t4format": "Industry keynote or panel",
    "t5title": "The Board's Role in Cyber and Technology Risk",
    "t5audience": "Directors, general counsel, risk leaders",
    "t5format": "Board education session",
    "t6title": "Engineering Trust into Digital Infrastructure",
    "t6audience": "Technology and infrastructure organizations",
    "t6format": "Technical-executive keynote",
    "t7title": "Leading Across Borders and Disciplines",
    "t7audience": "Global leadership teams and universities",
    "t7format": "Keynote or moderated conversation",
    "t8title": "From Founder to Institution Builder",
    "t8audience": "Entrepreneurs and next-generation executives",
    "t8format": "Workshop or fireside chat"
  },
  "caseStudies": {
    "eyebrow": "Études de cas",
    "title": "Construire des entreprises qui passent à l'échelle",
    "lead": "Résultats sélectionnés issus de la création et de la direction d'entreprises en infrastructure de données et santé numérique.",
    "cs1eyebrow": "Infrastructure de données · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "Défi",
    "cs1challengeText": "Créer et développer une entreprise de Data Storage dans un marché technologique en consolidation rapide.",
    "cs1action": "Approche",
    "cs1actionText": "J'ai fondé 9 Net Avenue Inc. en 1996. L'entreprise est rapidement devenue l'une des plus grandes sociétés de Data Storage au monde.",
    "cs1result": "Résultat",
    "cs1resultText": "Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO). Following the transaction, continued work with public companies and board-level roles.",
    "cs2eyebrow": "Santé numérique · 2021 — Aujourd'hui",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "Défi",
    "cs2challengeText": "Transformer des approches médicales obsolètes grâce à la science, aux technologies ADN, à l'IA et au ML via une nouvelle plateforme bio-mathématique.",
    "cs2action": "Approche",
    "cs2actionText": "Digital Invest Inc. fondée en 2021. Médecine biomathématique, intelligence génomique et plateformes de données cliniques.",
    "cs2result": "Résultat",
    "cs2resultText": "Healthcare Tech Outlook (2023). Projets : Human Digital Model et BioMath Life.",
    "cs3eyebrow": "Robotics & UAV · 2026 — Present",
    "cs3title": "AGRON Inc.",
    "cs3challenge": "Challenge",
    "cs3challengeText": "Organizations building UAV and Counter-UAS capability need independent assessment, structured training, and operational architecture — not isolated platforms or ad-hoc piloting.",
    "cs3action": "Approach",
    "cs3actionText": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — consulting, assessment and validation, capability development, training infrastructure, product development support, geospatial systems through ISDRI, and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "cs3result": "Outcome",
    "cs3resultText": "A connected professional services ecosystem spanning five service domains and multiple companies — Global Drone Academy, AGRON, ISDRI, and GUARD — with programmes delivered across 10+ countries and 10,000+ UAV operators, instructors, and specialists trained.",
    "caseStudiesLead": "Création, développement et direction d'entreprises de leur lancement jusqu'à l'acquisition."
  },
  "mediaKit": {
    "eyebrow": "Presse et événements",
    "title": "Kit média",
    "lead": "Biographies officielles, visuels et coordonnées pour la presse, les conférences et les demandes de conseil d'administration.",
    "bioEyebrow": "Biographies",
    "bioTitle": "Biographies officielles",
    "bioShortLabel": "50 mots",
    "bioShort": "Michael Kofman est CEO de Digital Invest Inc., administrateur, conseiller et fondateur d'entreprises technologiques et de santé numérique aux États-Unis et en Europe.",
    "bioMediumLabel": "150 mots",
    "bioMedium": "Michael Kofman est PDG de Digital Invest Inc. et membre de son conseil. Entrepreneur, administrateur et conseiller, il a fondé des entreprises aux États-Unis et en Europe dans l'infrastructure de données, la santé numérique et la robotique. Son travail couvre stratégie technologique, sécurité, recherche et investissement.",
    "bioLongLabel": "500 mots",
    "bioLong": "Michael Kofman is CEO of Digital Invest Inc. and serves on its board. He founded 9 Net Avenue Inc., acquired by Concentric Networks in 2000, and leads Digital Invest in bio-mathematical medicine and genomic intelligence. He founded AGRON Inc. in 2026 for autonomous aerial-ground operations and geospatial systems. Author of technical papers on satellite and optical systems; patent in digital satellite HDTV acquired by Sony. Education: Doctor of Technical Sciences, Ph.D. in Information Technology.",
    "photosEyebrow": "Photographie",
    "photosTitle": "Images approuvées",
    "photosLead": "Portraits en haute résolution disponibles sur demande à mkofman@mkofman.com.",
    "contactEyebrow": "Contact presse",
    "contactTitle": "Demandes médias",
    "contactLead": "Pour les interviews, invitations à intervenir et demandes presse.",
    "downloadEyebrow": "Download",
    "downloadTitle": "One-Page Media Kit",
    "downloadLead": "PDF with official bios, portrait, and press contact — ready to share with organizers and journalists.",
    "downloadCta": "Download PDF",
    "brandEyebrow": "Brand Assets",
    "brandTitle": "Identity & Usage",
    "brandLead": "Approved visual assets for editorial, conference, and partner use. Please preserve proportions, spacing, and original colors.",
    "brandColors": "Official Color Palette",
    "brandLogo": "Primary Logo",
    "brandDownload": "Download Brand Assets"
  },
  "articles": {
    "backLink": "← Retour vers Insights",
    "article1date": "Perspective dirigeante",
    "article1title": "De l'ingénierie à l'infrastructure mondiale de données",
    "article1p1": "Ma carrière a commencé à l'usine navale de Nikolaev, en Ukraine, où je développais des systèmes transpondeurs satellitaires pour transmettre des informations classifiées aux navires militaires. J'ai été reconnu comme ingénieur en électronique de plus haut niveau, 6e catégorie, dans une usine de 93 000 employés.",
    "article1p2": "De 1989 à 1994, j'ai fondé et dirigé Astra Corp, l'un des plus grands fabricants européens de systèmes satellitaires transpondeurs numériques. De 1994 à 1996, en tant que CEO d'Elitan United Inc., j'ai contribué à faire passer l'entreprise de neuf à plus de 4 000 employés dans le monde.",
    "article1p3": "In 1996, I founded 9 Net Avenue Inc., a hosting and internet infrastructure company. In 2000 it was acquired by Concentric Networks (NASDAQ: CNTX) and subsequently became part of XO Communications (NASDAQ: XOXO).",
    "article1p4": "De 2001 à 2019, j'ai dirigé la stratégie technologique pour des programmes gouvernementaux, de défense et d'entreprises publiques, en menant de grandes initiatives dans le big data, l'infrastructure sécurisée et les data centers à haut débit aux États-Unis et en Europe.",
    "article2date": "Santé numérique",
    "article2title": "Médecine de précision et convergence de la science et de la technologie",
    "article2p1": "Je crois fermement au potentiel de la combinaison des sciences de la vie avec les dernières avancées technologiques. Chez Biotechnology Group Inc. (2008-2014), nous nous sommes concentrés sur les tests et analyses ADN, l'automatisation des processus de création de profils génétiques et la recherche génétique humaine complète.",
    "article2p2": "Sous ma direction, des projets réussis de tests génétiques ont été lancés en Ukraine, en Russie et dans les pays baltes. En collaboration avec Harvard Medical School et Stanford Biomath, j'ai joué un rôle clé dans le développement de rapports génétiques faciles à comprendre pour les médecins comme pour les patients.",
    "article2p3": "Avec Digital Invest Inc., fondée en 2021, nous travaillons en médecine biomathématique — science, technologies ADN, IA et ML appliquées à l'intelligence clinique. Healthcare Tech Outlook (2023).",
    "article2p4": "Digital Invest fait progresser la médecine bio-mathématique via des projets comme Human Digital Model et BioMath Life. En 2026, Michael Kofman a fondé AGRON Inc. pour diriger l'Aerial-Ground Robotics Operations Network — capacités UAV, systèmes géospatiaux et renseignement maritime sur agron1.com."
  },
  "privacy": {
    "eyebrow": "Mentions légales",
    "title": "Politique de confidentialité",
    "lead": "Comment mkofman.com traite les informations lors de votre visite ou de l'envoi d'un message.",
    "updated": "Mise à jour : juillet 2026",
    "s1title": "Informations collectées",
    "s1text": "Lors de l'envoi d'un formulaire, nous recevons les champs fournis. Si l'analytique est activée, des données d'usage anonymisées peuvent être collectées.",
    "s2title": "Utilisation des informations",
    "s2text": "Les formulaires servent à répondre aux demandes et à améliorer le site. Nous ne vendons pas de données personnelles.",
    "s3title": "Services tiers",
    "s3text": "Les formulaires peuvent être traités par Formspree. Analytique via Plausible ou Google Analytics si configurée.",
    "s4title": "Vos droits",
    "s4text": "Accès, rectification ou suppression : mkofman@mkofman.com.",
    "s5title": "Contact",
    "s5text": "Questions sur cette politique : mkofman@mkofman.com"
  },
  "board": {
    "eyebrow": "Board & Strategic Advisory",
    "title": "Board & Advisory",
    "lead": "Board & Advisory",
    "rolesEyebrow": "Ways to Engage",
    "rolesTitle": "Board-Level Partnership",
    "role1title": "Independent Director",
    "role1desc": "Constructive oversight, informed challenge, and long-range perspective for public and private company boards.",
    "role2title": "Advisory Board Member",
    "role2desc": "Practical guidance on emerging technologies, product strategy, market positioning, and institutional readiness.",
    "role3title": "CEO & Founder Advisor",
    "role3desc": "Confidential counsel for leaders facing inflection points in scale, governance, succession, financing, or transformation.",
    "role4title": "Special Committee Advisor",
    "role4desc": "Focused support for transactions, technology diligence, cybersecurity exposure, and other high-stakes mandates.",
    "valueEyebrow": "Perspective",
    "valueTitle": "What I Bring to the Table",
    "value1title": "Operator's Discipline",
    "value1desc": "Experience building organizations from inception through global scale, acquisition, and public-market accountability.",
    "value2title": "Technical Fluency",
    "value2desc": "The ability to translate complex systems, scientific claims, and technology risk into clear board decisions.",
    "value3title": "Cross-Market Judgment",
    "value3desc": "A perspective shaped by technology, telecommunications, defense, data infrastructure, and precision medicine.",
    "value4title": "Governance Mindset",
    "value4desc": "A commitment to fiduciary responsibility, candid dialogue, ethical innovation, and durable stakeholder value.",
    "cta": "Discuss a Board Mandate",
    "availability": "Select independent director, advisory board, and strategic counsel engagements are considered.",
    "area1title": "Board Service",
    "area1desc": "Independent director and board-level work in technology strategy, corporate governance, and growth-stage oversight.",
    "area2title": "CEO & Founder Advisory",
    "area2desc": "Corporate and technology strategy, organizational development, transactions, and applicable capital-markets experience.",
    "area3title": "Technology Due Diligence",
    "area3desc": "Evaluation of infrastructure, data platforms, security architecture, and applied technology based on documented operating experience."
  },
  "thesis": {
    "eyebrow": "Leadership Thesis",
    "title": "Build for the Long Term. Decide in the Present.",
    "lead": "Technology changes quickly; the obligations of leadership do not. Durable enterprises unite ambition with discipline, evidence, and accountability.",
    "believeEyebrow": "What I Believe",
    "believeTitle": "Seven Principles for Enduring Organizations",
    "b1title": "Strategy Must Produce Choices",
    "b1text": "A strategy is not a catalog of aspirations. It defines where to compete, what capabilities to build, what not to pursue, and how success will be measured.",
    "b2title": "Technology Is a Governance Issue",
    "b2text": "Boards must understand how technology creates value, concentrates risk, and changes accountability. Delegating every technical question is itself a decision.",
    "b3title": "Evidence Should Outrank Enthusiasm",
    "b3text": "Conviction matters, but markets, systems, and science must be tested. Leaders create mechanisms that expose assumptions before customers or regulators do.",
    "b4title": "Architecture Shapes the Enterprise",
    "b4text": "Technical architecture determines speed, resilience, security, and future options. Shortcuts become institutional constraints long after their original context disappears.",
    "b5title": "Trust Is Operating Infrastructure",
    "b5text": "Trust is built through clear commitments, reliable execution, responsible data practices, and direct communication when conditions change.",
    "b6title": "Capital Must Follow Capability",
    "b6text": "Growth investment should reinforce differentiated capabilities and measurable demand, not substitute spending for product-market understanding.",
    "b7title": "Leaders Design Their Successors",
    "b7text": "The strongest leaders build systems, talent, and decision quality that endure beyond their own involvement.",
    "rejectEyebrow": "What I Reject",
    "rejectTitle": "Three Expensive Illusions",
    "r1title": "Innovation Theater",
    "r1text": "Announcements, pilots, and fashionable language do not equal capability. Innovation must improve an outcome that matters.",
    "r2title": "Growth Without Governance",
    "r2text": "Scale magnifies unresolved weaknesses. Controls, culture, and accountability should mature before complexity makes correction costly.",
    "r3title": "False Certainty",
    "r3text": "Executive confidence should not erase uncertainty. Strong decisions make assumptions visible and preserve options when facts change.",
    "horizonEyebrow": "The Horizon",
    "horizonTitle": "The Next Advantage Is Responsible Integration",
    "horizonText": "The defining opportunity is not any single technology. It is the disciplined integration of AI, advanced data systems, biology, and automation into institutions people can trust."
  },
  "press": {
    "eyebrow": "Press & Media",
    "title": "Selected Coverage",
    "lead": "A concise archive of third-party recognition and reporting across technology, entrepreneurship, and precision medicine.",
    "archiveEyebrow": "Archive",
    "y2023type": "Industry Recognition",
    "y2023title": "Top 10 Precision Medicine Companies",
    "y2023desc": "Healthcare Tech Outlook recognized Digital Invest Inc. among leading U.S. companies advancing precision medicine and digital health.",
    "y2023link": "View feature",
    "y2001type": "Executive Award",
    "y2001title": "Entrepreneur of the Year",
    "y2001desc": "Entrepreneur Magazine recognition.",
    "y2001link": "View archive",
    "y1999type": "Biographical Recognition",
    "y1999title": "Who's Who in America",
    "y1999desc": "Recognition beginning in 1999, followed by listings in Who's Who in the World and Who's Who in Science and Engineering.",
    "clipEyebrow": "From the Archive",
    "clipMeta": "Industry Feature · DataPeer Inc.",
    "clipTitle": "State of the Storage Industry",
    "clipLead": "An early interview with Michael Kofman as Founder, Chairman, and CEO of DataPeer Inc. — reflecting on fiber optics, satellite transmission, SAN, and the emerging storage market.",
    "clipBody": "The feature notes recognition as Entrepreneur of the Year by Entrepreneur Magazine (2001) and discusses DataPeer’s approach to mission-critical storage, iSCSI, and business continuity.",
    "clipOpen": "Open full page scan →",
    "y2000type": "Interview",
    "y2000title": "State of the Storage Industry",
    "y2000desc": "Featured interview as Founder, Chairman, and CEO of DataPeer Inc. on storage networks, iSCSI, and business continuity."
  },
  "ip": {
    "eyebrow": "Intellectual Property",
    "title": "Applied Ideas, Documented",
    "lead": "Selected patents, publications, and research programs connecting engineering rigor with practical business and societal outcomes.",
    "patentEyebrow": "Patents",
    "patentTitle": "Protected Inventions",
    "patentIntro": "Patent work reflects a sustained focus on systems that improve the collection, movement, protection, and interpretation of information.",
    "publicationsEyebrow": "Publications",
    "publicationsTitle": "Technical & Executive Writing",
    "publicationsIntro": "Published work translates complex technical subjects into methods, frameworks, and decisions useful to practitioners and leaders.",
    "researchEyebrow": "Research",
    "researchTitle": "Interdisciplinary Programs",
    "researchIntro": "Research initiatives span secure communications, predictive analytics, genetic interpretation, human digital modeling, and autonomous systems."
  },
  "testimonials": {
    "t1quote": "Michael combines an engineer's precision with the judgment of an experienced chief executive. He asks the questions that improve the decision.",
    "t1name": "Board Colleague",
    "t1role": "Public Technology Company",
    "t2quote": "His ability to connect science, product, governance, and commercial reality brings uncommon clarity to complex initiatives.",
    "t2name": "Strategic Partner",
    "t2role": "Digital Health Sector",
    "t3quote": "Michael is direct, thoughtful, and focused on durable value. He helps leadership teams see both the opportunity and the obligation.",
    "t3name": "Executive Collaborator",
    "t3role": "Global Infrastructure"
  },
  "deck": {
    "title": "Michael Kofman",
    "subtitle": "Dirigeant technologique · Fondateur · Conseiller",
    "thesis": "Technologie, business et investissement dans l'infrastructure, les sciences de la vie et les systèmes autonomes.",
    "contact": "Confidential discussion: contact Michael Kofman through mkofman.com"
  },
  "briefIpo": {
    "title": "What an IPO Changes",
    "desc": "Public markets do not merely change a company's capital structure; they change its operating contract.",
    "p1": "An initial public offering is often described as a financing event. In practice, it is an institutional transition. Forecasting, controls, disclosure, governance, and executive communication must become repeatable before the listing, not improvised afterward.",
    "p2": "Readiness begins with decision quality. Management needs reliable metrics, clear ownership, and an operating cadence that can explain both performance and variance. A company that cannot reconcile its internal narrative will struggle to communicate a credible external one.",
    "p3": "The board's role also changes. Directors must balance growth with oversight, understand material technology and market risks, and ensure that incentives support durable value rather than a single quarter.",
    "p4": "The strongest public companies preserve entrepreneurial speed while adding institutional discipline. The objective is not bureaucracy; it is trustworthy execution at a higher level of accountability.",
    "eyebrow": "Note exécutive"
  },
  "briefGenetic": {
    "title": "From Genetic Data to Clinical Decisions",
    "desc": "The value of genomic information depends on interpretation, evidence, and responsible integration into care.",
    "p1": "Genetic data is abundant; clinically useful meaning is scarce. A result becomes valuable only when it is interpreted in context, connected to validated evidence, and presented in a form that supports a real decision.",
    "p2": "That translation requires collaboration across molecular biology, medicine, statistics, software engineering, and patient communication. Weakness in any layer can turn technical sophistication into clinical confusion.",
    "p3": "Privacy and consent are architectural requirements, not legal footnotes. Systems must limit unnecessary exposure, make data provenance visible, and preserve patient agency as information moves between laboratories, platforms, and care teams.",
    "p4": "Precision medicine will advance through measured integration: better evidence, transparent models, interoperable workflows, and outcomes that clinicians and patients can evaluate. Trust is part of the product.",
    "eyebrow": "Note exécutive"
  },
  "briefAi": {
    "title": "AI Strategy Beyond the Pilot",
    "desc": "Enterprise AI creates value when ownership, data, workflow, and governance mature together.",
    "p1": "Many AI initiatives begin with a compelling demonstration and stall before production. The missing element is rarely the model alone. Sustainable value requires a defined business outcome, accountable owner, dependable data, and a workflow people will actually use.",
    "p2": "Leaders should distinguish automation, prediction, and decision support. Each carries different requirements for accuracy, explainability, human review, and risk. A single governance template will not fit every use case.",
    "p3": "Measurement must include more than technical performance. Adoption, cycle time, error rates, customer impact, security exposure, and the cost of supervision determine whether an AI capability is economically and institutionally sound.",
    "p4": "The winning approach is a managed portfolio: scale proven use cases, stop weak ones early, and maintain explicit boundaries for high-consequence decisions. AI strategy is ultimately operating strategy.",
    "eyebrow": "Note exécutive"
  }
};
