window.__LANG_fr = {
  "ui": {
    "toggleTheme": "Changer le thème clair/sombre",
    "selectLanguage": "Choisir la langue",
    "messageSent": "Message envoyé",
    "sendMessage": "Envoyer",
    "toggleNav": "Ouvrir le menu",
    "sending": "Envoi en cours…",
    "formError": "Envoi impossible. Merci d'envoyer un e-mail directement.",
    "present": "Aujourd'hui"
  },
  "nav": {
    "home": "Accueil",
    "about": "Biographie",
    "ventures": "Entreprises",
    "career": "Carrière",
    "recognition": "Distinctions",
    "contact": "Contact",
    "consulting": "Conseil",
    "insights": "Perspectives",
    "speaking": "Interventions",
    "caseStudies": "Études de cas",
    "mediaKit": "Kit média",
    "groupMain": "Principal",
    "groupServices": "Services",
    "groupWork": "Réalisations"
  },
  "footer": {
    "navigation": "Navigation",
    "ventures": "Entreprises",
    "connect": "Contact",
    "desc": "PDG, technologue et fondateur. Santé numérique, infrastructure de données, robotique.",
    "copyright": "© {year} Michael Kofman. Tous droits réservés.",
    "writeTitle": "Écrivez-moi",
    "writeEmail": "Votre email",
    "writeMessage": "Votre message",
    "writeSend": "Envoyer",
    "writeSuccess": "Merci — votre message a été envoyé.",
    "more": "Plus"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — PDG & Technologue Stratégique",
      "description": "Site officiel de Michael Kofman — PDG, fondateur et conseiller de conseils en technologie et santé numérique."
    },
    "about": {
      "title": "Biographie — Michael Kofman",
      "description": "Biographie de Michael Kofman — PDG de Digital Invest Inc., fondateur d'AGRON Inc."
    },
    "ventures": {
      "title": "Entreprises — Michael Kofman",
      "description": "Entreprises fondées et dirigées par Michael Kofman — de Digital Invest Inc. à 9 Net Avenue Inc. — bâtissant des entreprises transformatrices en technologie et santé."
    },
    "career": {
      "title": "Carrière — Michael Kofman",
      "description": "Parcours professionnel de Michael Kofman — de l'ingénierie satellitaire au poste de PDG d'entreprises technologiques et de santé mondiales."
    },
    "recognition": {
      "title": "Distinctions — Michael Kofman",
      "description": "Prix, distinctions et reconnaissances de Michael Kofman — Entrepreneur de l'année, Who's Who, brevets et distinctions sectorielles."
    },
    "contact": {
      "title": "Contact — Michael Kofman",
      "description": "Contacter Michael Kofman — PDG de Digital Invest Inc. Pour conférences, mandats de conseil et demandes commerciales."
    },
    "consulting": {
      "title": "Conseil — Michael Kofman",
      "description": "Mandats de conseil, postes au conseil d'administration, conférences et partenariats stratégiques avec Michael Kofman."
    },
    "insights": {
      "title": "Perspectives — Michael Kofman",
      "description": "Publications, articles de presse, brevets et reconnaissance sectorielle de Michael Kofman."
    },
    "speaking": {
      "title": "Interventions — Michael Kofman",
      "description": "Invitez Michael Kofman à intervenir sur le leadership exécutif, la stratégie technologique, la santé numérique et la gouvernance d'entreprise."
    },
    "caseStudies": {
      "title": "Études de cas — Michael Kofman",
      "description": "Études de cas issues de la carrière de Michael Kofman : 9 Net Avenue Inc. et Digital Invest Inc."
    },
    "mediaKit": {
      "title": "Kit média — Michael Kofman",
      "description": "Biographies officielles, photos et informations de contact pour la presse et les organisateurs d'événements."
    },
    "article1": {
      "title": "De l'ingénierie à l'infrastructure mondiale — Michael Kofman",
      "description": "Michael Kofman revient sur son parcours, de l'ingénierie satellitaire à la création d'entreprises mondiales d'infrastructure de données."
    },
    "article2": {
      "title": "Médecine de précision et technologie — Michael Kofman",
      "description": "Michael Kofman sur la convergence des sciences de la vie avec l'IA, le ML et les technologies ADN dans la médecine moderne."
    }
  },
  "home": {
    "heroEyebrow": "Site officiel de Michael Kofman",
    "heroTitle1": "Construit pour durer.",
    "heroTitle2": "Dirigé avec discernement.",
    "heroCta": "Découvrir mon parcours",
    "heroAlt": "Michael Kofman — CEO and Strategic Technologist",
    "quote1text": "Figurant parmi les principales entreprises américaines en médecine de précision et santé numérique.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "Entrepreneur of the Year — recognized for leadership and breakthrough achievements in platform innovation and infrastructure.",
    "quote2author": "Entrepreneur Magazine, 1999 — 2001",
    "quote3text": "Digital Invest Inc. named among America's Top 10 Best Companies in Precision Medicine and Digital Health.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "Précision d'ingénierie et stratégie commerciale — des systèmes satellites à une infrastructure de 19,5 milliards $ et à la médecine de précision.",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "Michael Kofman",
    "aboutTitle": "Des entreprises faites pour durer",
    "aboutLead1": "PDG de Digital Invest Inc. et fondateur d'AGRON Inc. Il a fondé et dirigé des entreprises aux États-Unis et en Europe.",
    "aboutLead2": "De 9 Net Avenue (valorisation pic de 19,5 milliards $) à Digital Invest en médecine de précision et AGRON en robotique — quatre décennies dans l'infrastructure, la santé et la défense.",
    "aboutLink": "Biographie complète",
    "expertiseEyebrow": "Domaines d'intervention",
    "expertiseTitle": "Leadership exécutif",
    "expertiseLead": "Quatre décennies de création, de conseil et d'investissement dans l'infrastructure, la santé et la robotique.",
    "exp1title": "PDG & fondateur",
    "exp1desc": "A fondé et développé plusieurs entreprises de la création à l'introduction en bourse, assurant une croissance financière constante et une présence mondiale dans la technologie et la santé.",
    "exp1link": "Entreprises →",
    "exp2title": "Architecte technologique",
    "exp2desc": "A conçu des communications sécurisées, des moteurs d'analyse prédictive et des plateformes d'intégration de données à l'échelle nationale pour les secteurs gouvernemental, militaire et télécom.",
    "exp2link": "Carrière →",
    "exp3title": "Santé numérique",
    "exp3desc": "Dirige la transformation de la médecine grâce à l'IA, au ML et aux technologies ADN. A collaboré avec Harvard Medical School et Stanford Biomath sur les rapports génétiques.",
    "exp3link": "Digital Invest →",
    "exp4title": "Conseiller du conseil",
    "exp4desc": "Siège au conseil d'administration et conseille des entreprises publiques et privées sur l'orientation stratégique, la gouvernance et la croissance portée par la technologie.",
    "exp4link": "Conseil →",
    "stat1": "Années de leadership",
    "stat2": "Entreprises fondées",
    "stat3": "Valeur de marché max.",
    "stat4": "Employés",
    "recEyebrow": "Distinctions",
    "recTitle": "Prix et honneurs",
    "recLead": "Prix du secteur et reconnaissance par les pairs en entrepreneuriat, médecine et ingénierie.",
    "award1title": "Entrepreneur de l'année",
    "award1desc": "Entrepreneur Magazine, 1999 — 2001",
    "award2title": "Top 10 médecine de précision",
    "award2desc": "Digital Invest Inc. — U.S., 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "Toutes les distinctions",
    "heroSub": "CEO, conseiller de conseils d'administration et stratège technologique pour des entreprises publiques et privées en technologie, Data Storage et santé numérique.",
    "primaryCta": "Demander un accompagnement",
    "secondaryCta": "Voir les études de cas",
    "featuredEyebrow": "Vu dans",
    "caseStudiesEyebrow": "Résultats prouvés",
    "caseStudiesTitle": "Études de cas",
    "caseStudiesLead": "Créer, développer et diriger des entreprises de leur lancement jusqu'à l'acquisition et l'IPO.",
    "caseStudiesLink": "Voir toutes les études de cas →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "A construit l'une des plus grandes sociétés mondiales de Data Storage, acquise avec une capitalisation boursière maximale de 19,5 milliards de dollars.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "Fondée et développée de sa création jusqu'à l'IPO : Top 10 des entreprises américaines de médecine de précision en 2023."
  },
  "about": {
    "eyebrow": "À propos",
    "title": "Trois décennies de parcours",
    "lead": "Entrepreneur et dirigeant en ingénierie, infrastructure, santé numérique et robotique.",
    "glance": "En bref",
    "role": "Rôle actuel",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "Localisation",
    "locationVal": "Charlotte, North Carolina",
    "education": "Formation",
    "educationVal": "Doctor of Technical Sciences (2009)\nPh.D. in Information Technology (2004)\nMaster's in Electronic Engineering",
    "university": "Université",
    "universityVal": "Ukrainian State Marine Technical University",
    "languages": "Langues",
    "languagesVal": "English, Russian, Ukrainian",
    "contactLabel": "Contact",
    "bioP1": "Michael Kofman est PDG de Digital Invest Inc. et fondateur d'AGRON Inc. Il siège au conseil de Digital Invest. Son travail couvre la création d'entreprises, la stratégie technologique, la sécurité, la recherche et l'investissement aux États-Unis et en Europe.",
    "bioP2": "As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. In 2026 he founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network. He also created Digital Invest, dedicated to the bio-mathematical sphere and transforming medicine through science, DNA technologies, AI, and ML.",
    "secBioTitle": "Médecine de précision & biotechnologie",
    "secBioP1": "Avant Digital Invest, il a joué un rôle déterminant dans le succès de Biotechnology Group Inc. (2008–2014), une entreprise engagée dans les tests et analyses ADN, l'automatisation de la création de profils génétiques et la recherche génétique humaine complète. M. Kofman croit fermement au potentiel de la combinaison des sciences de la vie avec les dernières avancées technologiques.",
    "secBioP2": "Sous sa direction, des projets de tests génétiques réussis ont été lancés en Ukraine, en Russie et dans les pays baltes. Cette expérience unique est continuellement enrichie par des technologies modernes et de nouveaux équipements. En collaboration avec la Harvard Medical School et Stanford Biomath, M. Kofman a joué un rôle crucial dans le développement de rapports génétiques facilement compréhensibles pour les médecins et les patients. Cette approche innovante a été largement adoptée par les laboratoires de premier plan aux États-Unis et à l'étranger.",
    "secTechTitle": "Technologie & infrastructure",
    "secTechP1": "De 2001 à 2019, M. Kofman a dirigé la stratégie technologique de programmes gouvernementaux, de défense et d'entreprises d'État — y compris des initiatives techniques complexes pour des sociétés publiques. À la suite du 11 septembre 2001, il a dirigé des projets gouvernementaux à grande échelle centrés sur le big data, l'infrastructure sécurisée et les centres de données à haut débit aux États-Unis et en Europe.",
    "secTechP2": "En 2006, M. Kofman a fondé XIBI Group Inc. — une entreprise technologique dont il siégeait au conseil d'administration. La société américaine est spécialisée dans le stockage de données et les services de gestion du big data pour les grandes organisations commerciales et gouvernementales.",
    "secTechP3": "De 2000 à 2004, M. Kofman a dirigé DataPeer Inc. — une entreprise de gestion et de stockage de données offrant un large éventail de services liés au stockage d'informations pour les petites et moyennes entreprises. Chez DataPeer, il a développé des solutions technologiques uniques facilitant un suivi plus rapide des informations et un accès plus simple aux données pour les utilisateurs finaux et les institutions gouvernementales du monde entier.",
    "secTechP4": "En 1996, M. Kofman a fondé 9 Net Avenue Inc. L'entreprise est rapidement devenue l'un des plus grands hébergeurs au monde. En 2000, 9 Net Avenue a été acquise par Concentric Networks (NASDAQ: CNTX), puis par XO Communications (NASDAQ: XOXO), atteignant une valeur boursière maximale de 19,5 milliards de dollars.",
    "secPost9NetP1": "Après l'acquisition de 9 Net Avenue, M. Kofman a acquis une vaste expérience au sein d'entreprises cotées en bourse, de participation aux conseils d'administration et de prise de décisions stratégiques au plus haut niveau exécutif.",
    "secEarlyTitle": "Débuts de carrière & ingénierie",
    "secEarlyP1": "De 1994 à 1996, M. Kofman a été PDG et directeur des technologies de l'information chez Elitan United Inc. — une entreprise informatique du Massachusetts offrant des stratégies complètes et des services technologiques aux principales organisations mondiales. Il a joué un rôle central dans le développement et la gestion d'une infrastructure évolutive, faisant passer l'entreprise de neuf à plus de 4 000 employés dans le monde.",
    "secEarlyP2": "De 1989 à 1994, il a été fondateur et PDG d'Astra Corp, l'un des plus grands fabricants européens de systèmes satellitaires de transception numérique, reconnu internationalement dans le domaine des dispositifs satellitaires. Ses responsabilités comprenaient la recherche, le développement de systèmes d'exploitation, les applications logicielles réseau et la stratégie technique globale.",
    "secEarlyP3": "De 1984 à 1989, M. Kofman a travaillé au chantier naval de Nikolaev, en Ukraine, où il a activement participé au développement et à la création de systèmes de transception satellitaire pour transmettre des informations classifiées aux navires militaires et en retour. Il a été reconnu comme ingénieur électronicien du plus haut niveau, recevant la 6e catégorie — la plus haute distinction du chantier, qui comptait 93 000 employés.",
    "secResearchTitle": "Recherche & brevets",
    "secResearchP1": "Michael Kofman est l'auteur de travaux techniques sur les systèmes satellitaires et optiques de transmission de données. Il a également obtenu un brevet dans le domaine des systèmes de télévision haute définition (HDTV) par satellite numérique, ultérieurement acquis par Sony.",
    "secAgronTitle": "Robotics, UAV & Maritime Intelligence",
    "secAgronP1": "In 2026, Mr. Kofman founded AGRON Inc. to build the AGRON Ecosystem — a corporate operating architecture for aerial and ground robotics, governed mission execution, and network infrastructure connecting teams, assets, and operational data. The ecosystem delivers consulting, assessment, capability development, and training for UAV and Counter-UAS organizations, alongside maritime intelligence and security services at agron1.com."
  },
  "ventures": {
    "eyebrow": "Portefeuille",
    "title": "Entreprises fondées et dirigées",
    "lead": "De la médecine de précision et la robotique à l'infrastructure mondiale de données — fondées, développées et dirigées aux États-Unis et en Europe.",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — an Aerial-Ground Robotics Operations Network spanning UAV and Counter-UAS consulting, technology assessment, capability development, training infrastructure, product validation, geospatial systems (ISDRI), and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "v0role": "Founder",
    "v0year": "2026 — Present",
    "v1highlight": "Top 10 entreprise de médecine de précision aux États-Unis — 2023",
    "v1p1": "Fondation et développement de Digital Invest depuis sa création jusqu'à une introduction en bourse réussie. L'entreprise est dédiée à la sphère bio-mathématique, transformant la médecine grâce à l'IA, au ML et aux technologies ADN.",
    "v1role": "Fondateur & PDG · Membre du conseil",
    "v1year": "2021 — Aujourd'hui",
    "v2highlight": "Partenaire de la Harvard Medical School & Stanford Biomath",
    "v2p1": "Tests et analyses ADN, automatisation du profilage génétique et recherche génétique humaine complète. Lancement de projets de tests génétiques en Ukraine, en Russie et dans les pays baltes.",
    "v2p2": "Collaboration avec la Harvard Medical School et Stanford Biomath sur des rapports génétiques adoptés par les laboratoires de premier plan dans le monde entier.",
    "v2role": "PDG & CTO",
    "v2year": "2008 — 2014",
    "v3highlight": "Solutions de données d'entreprise & gouvernementales",
    "v3p1": "Stockage de données et services de gestion du big data pour les grandes organisations commerciales et gouvernementales. Établissement de l'entreprise comme fournisseur de confiance de solutions de données d'entreprise.",
    "v3role": "Fondateur & PDG · Conseil d'administration",
    "v3year": "2006 — 2011",
    "v4highlight": "Plateforme mondiale de gestion de données",
    "v4p1": "Gestion et stockage de données pour les petites et moyennes entreprises. Développement de solutions pour un suivi plus rapide des informations et un accès plus simple aux données pour les utilisateurs finaux et les institutions gouvernementales du monde entier.",
    "v4role": "Fondateur & PDG",
    "v4year": "2000 — 2004",
    "v5highlight": "Acquise · Valeur maximale de 19,5 milliards de dollars",
    "v5p1": "Construction de l'un des plus grands hébergeurs au monde. En 2000, acquisition par Concentric Networks (NASDAQ: CNTX), puis XO Communications (NASDAQ: XOXO), atteignant une valeur boursière maximale de 19,5 milliards de dollars.",
    "v5role": "Fondateur & PDG",
    "v5year": "1996 — 2000",
    "v6highlight": "Stratégie informatique & infrastructure mondiale",
    "v6p1": "Entreprise informatique du Massachusetts offrant des stratégies complètes et des services technologiques aux principales organisations mondiales. Direction du développement d'infrastructures évolutives et des opérations informatiques mondiales.",
    "v6role": "PDG & Directeur des technologies de l'information",
    "v6year": "1994 — 1996",
    "v7highlight": "Leader européen des systèmes satellitaires",
    "v7p1": "L'un des plus grands fabricants européens de systèmes satellitaires de transception numérique. Direction de la recherche, du développement de systèmes d'exploitation, des applications logicielles réseau et de la stratégie technique globale.",
    "v7role": "Fondateur & PDG",
    "v7year": "1989 — 1994",
    "v8highlight": "Ingénierie de systèmes satellitaires militaires",
    "v8p1": "Développement et création de systèmes de transception satellitaire pour transmettre des informations classifiées aux navires militaires. Reconnu comme ingénieur électronicien du plus haut niveau dans un chantier naval de 93 000 employés.",
    "v8role": "Ingénieur électronicien · Catégorie maximale (6e)",
    "v8year": "1984 — 1989"
  },
  "career": {
    "eyebrow": "Parcours professionnel",
    "title": "Trois décennies de leadership",
    "lead": "De l'ingénierie satellitaire aux entreprises technologiques mondiales.",
    "timelineEyebrow": "Chronologie",
    "timelineTitle": "Jalons clés",
    "strengthsEyebrow": "Forces",
    "strengthsTitle": "Domaines d'expertise",
    "t0desc": "Founded AGRON Inc. to build the AGRON Ecosystem — consulting, assessment, capability development, training infrastructure, and product support for UAV and Counter-UAS programmes, plus AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure. Connects aerial and ground robotics, governed mission execution, and network infrastructure linking teams, assets, and operational data.",
    "t0role": "Founder",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — Present",
    "s1desc": "Gestion double PDG/CTO dans des entreprises publiques et privées, de la startup à l'introduction en bourse et au-delà.",
    "s1title": "Leadership exécutif",
    "s2desc": "Exécution complète d'offres publiques — structuration juridique, coordination SEC, roadshows investisseurs et conformité.",
    "s2title": "Introduction en bourse & montée en charge financière",
    "s3desc": "Conception de systèmes évolutifs pour l'automatisation d'entreprise, la surveillance prédictive et le contrôle centralisé des données.",
    "s3title": "Architecture de plateforme",
    "s4desc": "Développement et exploitation de centres de données pour les plateformes gouvernementales, militaires et commerciales à haute sécurité.",
    "s4title": "Infrastructure sécurisée",
    "t10desc": "Développement et création de systèmes de transception satellitaire pour transmettre des informations classifiées aux navires militaires. Reconnu comme ingénieur électronicien du plus haut niveau dans un chantier naval de 93 000 employés — le début d'une carrière distinguée en technologie et innovation.",
    "t10role": "Ingénieur électronicien — 6e catégorie (maximale)",
    "t10title": "Chantier naval de Nikolaev",
    "t10year": "1984 — 1989",
    "t1desc": "Fondation et développement de l'entreprise depuis sa création jusqu'à une introduction en bourse réussie. Direction de l'ensemble du processus d'offre publique — structuration juridique, conformité financière, roadshows investisseurs et coordination avec la SEC. Direction de la conception, de la construction et de l'exploitation de plusieurs centres de données aux États-Unis et en Europe. Construction de systèmes logiciels de niveau entreprise pour l'automatisation, la surveillance prédictive et le contrôle centralisé des données. Croissance financière constante, positionnant l'entreprise parmi les 10 meilleures sociétés de médecine de précision aux États-Unis (2023).",
    "t1role": "Fondateur & PDG",
    "t1title": "Digital Invest Inc.",
    "t1year": "2021 — Aujourd'hui",
    "t2desc": "Direction de la stratégie et de la mise en œuvre technologiques pour des programmes classifiés et hautement sensibles impliquant des agences gouvernementales américaines, des systèmes de défense alliés et des entreprises d'État. Direction de projets techniques complexes pour des sociétés publiques dans de multiples secteurs. À la suite du 11 septembre 2001, direction d'initiatives gouvernementales à grande échelle centrées sur le big data, les communications sécurisées, l'analytique prédictive et l'intégration des données au niveau national — y compris la conception, la construction et l'exploitation de centres de données à haut débit aux États-Unis et en Europe. Interface avec les responsables de programmes militaires, les fournisseurs technologiques et les entités réglementaires.",
    "t2role": "Conseiller technologique principal / Architecte de programmes",
    "t2title": "GovTech, défense & programmes d'État",
    "t2year": "2001 — 2019",
    "t3desc": "Direction des tests et analyses ADN, de l'automatisation du profilage génétique et de la recherche génétique humaine complète. Lancement de projets de tests génétiques en Ukraine, en Russie et dans les pays baltes. Collaboration avec la Harvard Medical School et Stanford Biomath pour développer des rapports génétiques compréhensibles adoptés par les laboratoires de premier plan dans le monde entier.",
    "t3role": "PDG & CTO",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4desc": "Direction des déploiements d'infrastructures nationales au Canada, en Italie, en Suisse, en Ukraine et dans les républiques baltes. Supervision de plus de 1 000 ingénieurs et personnel de déploiement dans les opérations télécoms, y compris les systèmes de commutation, l'expansion de la bande passante et la connectivité transfrontalière. Mise en œuvre de systèmes centraux de redondance réseau, d'optimisation de la disponibilité et de routage intelligent.",
    "t4role": "VP Technologie / CTO régional — Europe de l'Est & CEI",
    "t4title": "Projets de télécommunications",
    "t4year": "2000 — 2012",
    "t5desc": "Fondation d'une entreprise technologique spécialisée dans le stockage de données et la gestion du big data pour les grandes organisations commerciales et gouvernementales. Établissement de l'entreprise comme fournisseur de confiance de solutions de données d'entreprise.",
    "t5role": "Fondateur & PDG · Conseil d'administration",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6desc": "Création d'une entreprise de gestion et de stockage de données pour les PME. Développement de solutions technologiques uniques pour un suivi plus rapide des informations et un accès plus simple aux données pour les utilisateurs finaux et les institutions gouvernementales du monde entier.",
    "t6role": "Fondateur & PDG",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "Construction de l'un des plus grands hébergeurs au monde. En 2000, acquisition par Concentric Networks (NASDAQ: CNTX), puis XO Communications (NASDAQ: XOXO), atteignant une valeur boursière maximale de 19,5 milliards de dollars.",
    "t7role": "Fondateur & PDG",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8desc": "Direction de stratégies informatiques complètes et de services technologiques pour les principales organisations mondiales depuis le Massachusetts pendant une période d'expansion rapide, en construisant une infrastructure évolutive et des opérations informatiques mondiales.",
    "t8role": "PDG & Directeur des technologies de l'information",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9desc": "Fondation de l'un des plus grands fabricants européens de systèmes satellitaires de transception numérique. Direction de la recherche, du développement de systèmes d'exploitation, des applications logicielles réseau et de la stratégie technique globale, obtenant une reconnaissance internationale.",
    "t9role": "Fondateur & PDG",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994"
  },
  "recognition": {
    "eyebrow": "Distinctions",
    "title": "Prix et reconnaissance",
    "lead": "Distinctions en entrepreneuriat, médecine de précision, ingénierie et leadership exécutif.",
    "industryEyebrow": "Prix du secteur",
    "industryTitle": "Grandes distinctions",
    "ipEyebrow": "Propriété intellectuelle",
    "ipTitle": "Brevets et publications",
    "eduEyebrow": "Formation",
    "eduTitle": "Diplômes",
    "pressEyebrow": "Presse",
    "pressTitle": "Vu dans",
    "moreLink": "Voir les brevets, publications et mentions presse dans Insights →",
    "a1title": "Entrepreneur de l'année",
    "a1desc": "Entrepreneur Magazine, 1999 — 2001 — leadership et réalisations révolutionnaires en innovation de plateformes et infrastructure.",
    "a2title": "Top 10 entreprise de médecine de précision aux États-Unis",
    "a2desc": "Digital Invest Inc. reconnue parmi les 10 meilleures entreprises américaines de médecine de précision et de santé numérique — 2023.",
    "a3title": "Who's Who in America",
    "a3desc": "Inscrit, 1999 — 2018 — pour des réalisations exceptionnelles en création et développement d'entreprises.",
    "a4title": "Who's Who in the World",
    "a4desc": "Inscrit, 2000 — 2004 — parmi les leaders mondiaux en science, ingénierie et innovation entrepreneuriale.",
    "a5title": "Who's Who in Science & Engineering",
    "a5desc": "Inscrit, 2000 — 2014 — pour des contributions à la technologie, aux systèmes satellitaires et à l'infrastructure numérique.",
    "a6title": "Ingénieur électronicien — 6e catégorie",
    "a6desc": "Plus haute distinction au chantier naval de Nikolaev (93 000 employés) pour l'ingénierie de systèmes de transception satellitaire.",
    "ip1year": "Brevet",
    "ip1title": "Systèmes HDTV satellitaires numériques",
    "ip1role": "Ultérieurement acquis par Sony",
    "ip1desc": "Obtention d'un brevet dans le domaine des systèmes de télévision haute définition (HDTV) par satellite numérique. Le brevet a été ultérieurement acquis par Sony Corporation, validant l'importance commerciale de l'innovation.",
    "ip2year": "Publications",
    "ip2title": "Travaux techniques",
    "ip2role": "Systèmes satellitaires & optiques",
    "ip2desc": "Auteur de travaux techniques sur les systèmes satellitaires et optiques de transmission de données. Les contributions de recherche couvrent le traitement du signal, la modélisation par simulation et les plateformes d'automatisation appliquées aux télécommunications, à l'infrastructure nationale et à la santé numérique.",
    "ip3year": "Recherche",
    "ip3title": "Collaborations internationales",
    "ip3role": "États-Unis & Europe",
    "ip3desc": "Participation à des collaborations de recherche internationales et à des initiatives de transfert de connaissances. Développement de systèmes d'ingénierie embarqués pour l'acquisition de données, le diagnostic prédictif et l'orchestration cloud dans de multiples industries.",
    "edu1title": "Docteur en sciences techniques",
    "edu1desc": "2009 — Université d'État technique marine d'Ukraine",
    "edu2title": "Doctorat en technologies de l'information",
    "edu2desc": "2004 — Université d'État technique marine d'Ukraine",
    "edu3title": "Masters",
    "edu3desc": "Électronique, systèmes satellitaires numériques et économie",
    "press1title": "Healthcare Tech Outlook",
    "press1role": "Article sur Digital Invest Inc.",
    "press1desc": "Digital Invest Inc. présentée comme l'une des entreprises américaines de premier plan en médecine de précision et santé numérique, reconnue pour ses approches innovantes de transformation de la médecine grâce à l'IA, au ML et aux technologies ADN.",
    "press1link": "Lire l'article →",
    "press2title": "Top Precision Medicine Solutions",
    "press2role": "Reconnaissance du secteur",
    "press2desc": "Classée parmi les principales entreprises de solutions de médecine de précision, soulignant le rôle de Digital Invest dans l'avancement des approches bio-mathématiques en santé moderne.",
    "press2link": "Voir le classement →"
  },
  "contact": {
    "eyebrow": "Contact",
    "title": "Restons en contact",
    "lead": "Pour des rôles de conseil, conseils d'administration et partenariats.",
    "infoTitle": "Contact direct",
    "email": "E-mail",
    "phone": "Téléphone",
    "location": "Localisation",
    "locationVal": "Charlotte, North Carolina\nUnited States",
    "linkedin": "LinkedIn",
    "company": "Entreprise actuelle",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member\nAGRON Inc.\nFounder",
    "formTitle": "Envoyer un message",
    "formLead": "Remplissez le formulaire ci-dessous.",
    "firstName": "Prénom",
    "lastName": "Nom",
    "emailLabel": "Adresse e-mail",
    "subject": "Objet",
    "message": "Message",
    "inquiryType": "Inquiry Type",
    "inquiryAdvisory": "Advisory / Board Role",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "infoEyebrow": "Coordonnées"
  },
  "consulting": {
    "eyebrow": "Services de conseil",
    "title": "Conseil",
    "heroEyebrow": "Orientation stratégique des entreprises",
    "heroTitle": "Conseil stratégique",
    "heroLead": "Trente-cinq ans à fonder et conseiller des entreprises aux États-Unis et en Europe — infrastructure de données, govtech, médecine de précision et robotique.",
    "cta": "Contacter Michael Kofman",
    "introLead": "PDG de Digital Invest Inc. et membre du conseil. Axes : technologies émergentes, sécurité, recherche et allocation de capital.",
    "specialtiesEyebrow": "Domaines d'intervention",
    "specialtiesTitle": "Les spécialités de Michael Kofman"
  },
  "insights": {
    "eyebrow": "Leadership éclairé",
    "title": "Perspectives",
    "heroTitle": "Perspectives exécutives",
    "selectedEyebrow": "Points saillants",
    "selectedTitle": "Reconnaissance en vedette",
    "allPressTitle": "Toutes les parutions presse",
    "quotesEyebrow": "Dans les médias",
    "quotesTitle": "Reconnaissance sectorielle et citations",
    "articlesEyebrow": "Points de vue",
    "articlesTitle": "Perspectives dirigeantes"
  },
  "cta": {
    "eyebrow": "Collaborons",
    "title": "Demander un accompagnement ou une intervention",
    "lead": "Pour des rôles de conseil, des mandats d'administrateur, des interventions et des partenariats stratégiques.",
    "button": "Prendre contact"
  },
  "speaking": {
    "eyebrow": "Interventions",
    "title": "Inviter Michael Kofman à intervenir",
    "lead": "Disponible pour des interventions sur le leadership exécutif, la stratégie technologique, la santé numérique, l'infrastructure de données et la gouvernance d'entreprise.",
    "topicsEyebrow": "Thèmes d'intervention",
    "topicsTitle": "Domaines d'expertise",
    "topicsLead": "Les thèmes s'appuient sur des décennies d'expérience dans la création et la direction d'entreprises aux États-Unis et en Europe.",
    "processEyebrow": "Comment inviter",
    "processTitle": "Processus de réservation",
    "process1title": "Envoyer une demande",
    "process1desc": "Utilisez le formulaire de contact ou écrivez à mkofman@mkofman.com avec les détails de l'événement, le public et les thèmes souhaités.",
    "process2title": "Valider le périmètre",
    "process2desc": "Définissez le format (keynote, panel, session de conseil d'administration ou table ronde exécutive) et la logistique.",
    "process3title": "Créer de la valeur",
    "process3desc": "Les interventions s'appuient sur des résultats concrets obtenus dans le data storage, la govtech et la médecine de précision.",
    "cta": "Demander une intervention"
  },
  "caseStudies": {
    "eyebrow": "Études de cas",
    "title": "Construire des entreprises qui passent à l'échelle",
    "lead": "Résultats sélectionnés issus de la création et de la direction d'entreprises en infrastructure de données et santé numérique.",
    "cs1eyebrow": "Infrastructure de données · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "Défi",
    "cs1challengeText": "Créer et développer une entreprise de Data Storage dans un marché technologique en consolidation rapide.",
    "cs1action": "Approche",
    "cs1actionText": "J'ai fondé 9 Net Avenue Inc. en 1996. L'entreprise est rapidement devenue l'une des plus grandes sociétés de Data Storage au monde.",
    "cs1result": "Résultat",
    "cs1resultText": "En 2000, elle a été acquise par Concentric Networks (NASDAQ: CNTX), puis XO Communications (NASDAQ: XOXO), atteignant une capitalisation boursière maximale de 19,5 milliards de dollars. Après l'acquisition, j'ai acquis une solide expérience avec des entreprises cotées, la gouvernance de conseil et la prise de décisions stratégiques au plus haut niveau.",
    "cs2eyebrow": "Santé numérique · 2021 — Aujourd'hui",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "Défi",
    "cs2challengeText": "Transformer des approches médicales obsolètes grâce à la science, aux technologies ADN, à l'IA et au ML via une nouvelle plateforme bio-mathématique.",
    "cs2action": "Approche",
    "cs2actionText": "J'ai fondé et développé Digital Invest Inc. de sa création à une introduction en bourse réussie. J'ai dirigé l'ensemble du processus d'IPO : structuration juridique, conformité financière, roadshows investisseurs et coordination avec la SEC. J'ai également piloté la conception, la construction et l'exploitation de plusieurs data centers aux États-Unis et en Europe.",
    "cs2result": "Résultat",
    "cs2resultText": "Nous avons atteint une croissance financière soutenue, positionnant l'entreprise parmi les 10 meilleures sociétés de médecine de précision aux États-Unis (2023), avec des projets comme Human Digital Model et BioMath Life."
  },
  "mediaKit": {
    "eyebrow": "Presse et événements",
    "title": "Kit média",
    "lead": "Biographies officielles, visuels et coordonnées pour la presse, les conférences et les demandes de conseil d'administration.",
    "bioEyebrow": "Biographies",
    "bioTitle": "Biographies officielles",
    "bioShortLabel": "50 mots",
    "bioShort": "Michael Kofman est CEO de Digital Invest Inc., administrateur, conseiller et fondateur d'entreprises technologiques et de santé numérique aux États-Unis et en Europe.",
    "bioMediumLabel": "150 mots",
    "bioMedium": "Michael Kofman est PDG de Digital Invest Inc. et membre de son conseil. Entrepreneur, administrateur et conseiller, il a fondé des entreprises aux États-Unis et en Europe dans l'infrastructure de données, la santé numérique et la robotique. Son travail couvre stratégie technologique, sécurité, recherche et investissement.",
    "bioLongLabel": "500 mots",
    "bioLong": "Michael Kofman est PDG de Digital Invest Inc. et membre de son conseil. Il a fondé 9 Net Avenue Inc. (valorisation pic de 19,5 milliards $) et dirige Digital Invest en médecine de précision. Expérience en govtech et défense, XIBI Group Inc., DataPeer Inc., Biotechnology Group Inc. Collaboration avec Harvard Medical School et Stanford Biomath. Auteur de travaux techniques; brevet HDTV acquis par Sony. En 2026, il a fondé AGRON Inc. pour la robotique aéro-terrestre et le renseignement maritime.",
    "photosEyebrow": "Photographie",
    "photosTitle": "Images approuvées",
    "photosLead": "Portraits en haute résolution disponibles sur demande à mkofman@mkofman.com.",
    "contactEyebrow": "Contact presse",
    "contactTitle": "Demandes médias",
    "contactLead": "Pour les interviews, invitations à intervenir et demandes presse."
  },
  "articles": {
    "backLink": "← Retour vers Insights",
    "article1date": "Perspective dirigeante",
    "article1title": "De l'ingénierie à l'infrastructure mondiale de données",
    "article1p1": "Ma carrière a commencé à l'usine navale de Nikolaev, en Ukraine, où je développais des systèmes transpondeurs satellitaires pour transmettre des informations classifiées aux navires militaires. J'ai été reconnu comme ingénieur en électronique de plus haut niveau, 6e catégorie, dans une usine de 93 000 employés.",
    "article1p2": "De 1989 à 1994, j'ai fondé et dirigé Astra Corp, l'un des plus grands fabricants européens de systèmes satellitaires transpondeurs numériques. De 1994 à 1996, en tant que CEO d'Elitan United Inc., j'ai contribué à faire passer l'entreprise de neuf à plus de 4 000 employés dans le monde.",
    "article1p3": "En 1996, j'ai fondé 9 Net Avenue Inc., rapidement devenue l'une des plus grandes entreprises mondiales de Data Storage. En 2000, elle a été acquise par Concentric Networks (NASDAQ: CNTX) et XO Communications (NASDAQ: XOXO), atteignant une capitalisation boursière maximale de 19,5 milliards de dollars.",
    "article1p4": "De 2001 à 2019, j'ai dirigé la stratégie technologique pour des programmes gouvernementaux, de défense et d'entreprises publiques, en menant de grandes initiatives dans le big data, l'infrastructure sécurisée et les data centers à haut débit aux États-Unis et en Europe.",
    "article2date": "Santé numérique",
    "article2title": "Médecine de précision et convergence de la science et de la technologie",
    "article2p1": "Je crois fermement au potentiel de la combinaison des sciences de la vie avec les dernières avancées technologiques. Chez Biotechnology Group Inc. (2008-2014), nous nous sommes concentrés sur les tests et analyses ADN, l'automatisation des processus de création de profils génétiques et la recherche génétique humaine complète.",
    "article2p2": "Sous ma direction, des projets réussis de tests génétiques ont été lancés en Ukraine, en Russie et dans les pays baltes. En collaboration avec Harvard Medical School et Stanford Biomath, j'ai joué un rôle clé dans le développement de rapports génétiques faciles à comprendre pour les médecins comme pour les patients.",
    "article2p3": "Avec Digital Invest Inc., fondée en 2021, nous nous consacrons au domaine bio-mathématique, transformant les approches médicales obsolètes grâce à la science, aux technologies ADN, à l'IA et au ML. L'entreprise a été développée de sa création jusqu'à une introduction en bourse réussie et reconnue parmi les 10 meilleures entreprises américaines de médecine de précision et de santé numérique en 2023.",
    "article2p4": "Digital Invest fait progresser la médecine bio-mathématique via des projets comme Human Digital Model et BioMath Life. En 2026, Michael Kofman a fondé AGRON Inc. pour diriger l'Aerial-Ground Robotics Operations Network — capacités UAV, systèmes géospatiaux et renseignement maritime sur agron1.com."
  }
};
