window.__LANG_he = {
  "ui": {
    "toggleTheme": "החלפת ערכת בהיר/כהה",
    "selectLanguage": "בחר שפה",
    "messageSent": "ההודעה נשלחה",
    "sendMessage": "שלח",
    "toggleNav": "פתח תפריט",
    "sending": "שולח…",
    "formError": "לא ניתן היה לשלוח. נא לשלוח אימייל ישירות.",
    "present": "עד היום"
  },
  "nav": {
    "home": "בית",
    "about": "אודות",
    "ventures": "חברות",
    "career": "The Record",
    "recognition": "הכרה",
    "contact": "צור קשר",
    "consulting": "ייעוץ",
    "insights": "תובנות",
    "speaking": "הרצאות",
    "caseStudies": "מקרי בוחן",
    "mediaKit": "ערכת מדיה",
    "groupMain": "ראשי",
    "groupServices": "שירותים",
    "groupWork": "עבודה",
    "briefIpo": "Brief: IPO",
    "briefGenetic": "Brief: Genetic Data",
    "briefAi": "Brief: AI Strategy",
    "articleInfra": "Data Infrastructure",
    "articleHealth": "Precision Medicine",
    "board": "Advisory",
    "thesis": "Leadership Thesis",
    "press": "Press",
    "ip": "Intellectual Property"
  },
  "footer": {
    "navigation": "ניווט",
    "ventures": "חברות",
    "connect": "קשר",
    "desc": "מנהיג טכנולוגי, מייסד ויועץ דירקטוריון.",
    "copyright": "© {year} Michael Kofman. כל הזכויות שמורות.",
    "writeTitle": "כתבו לי",
    "writeEmail": "האימייל שלך",
    "writeMessage": "ההודעה שלך",
    "writeSend": "שלח",
    "writeSuccess": "תודה — ההודעה נשלחה.",
    "more": "עוד",
    "privacy": "פרטיות"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — מנהיג טכנולוגי",
      "description": "מנהיג טכנולוגי, מייסד ויועץ — תשתיות, מדעי החיים ומערכות אוטונומיות."
    },
    "about": {
      "title": "אודות — Michael Kofman",
      "description": "ביוגרפיה של Michael Kofman — מנכ\"ל Digital Invest Inc., מייסד AGRON Inc."
    },
    "ventures": {
      "title": "חברות — Michael Kofman",
      "description": "חברות שייסד וניהל מייקל קופמן — מ-Digital Invest Inc. ועד 9 Net Avenue Inc. — בניית עסקים משני מציאות בטכנולוגיה ובריאות."
    },
    "career": {
      "title": "The Record — Michael Kofman",
      "description": "רשומה מקצועית בהנדסה, תשתיות, שווקים ציבוריים, מדעי החיים ומערכות אוטונומיות."
    },
    "recognition": {
      "title": "הכרה — Michael Kofman",
      "description": "פרסים והוקרות למייקל קופמן — יזם השנה, Who's Who, פטנטים והוקרות תעשייתיות."
    },
    "contact": {
      "title": "צור קשר — Michael Kofman",
      "description": "יצירת קשר עם מייקל קופמן — מנכ\"ל Digital Invest Inc. לייעוץ, הרצאות ופניות עסקיות."
    },
    "consulting": {
      "title": "ייעוץ — Michael Kofman",
      "description": "תפקידי ייעוץ, חברות בדירקטוריון, הרצאות ושותפויות אסטרטגיות עם Michael Kofman."
    },
    "insights": {
      "title": "תובנות — Michael Kofman",
      "description": "כתיבה מקורית ו-executive briefs מאת Michael Kofman."
    },
    "speaking": {
      "title": "הרצאות — Michael Kofman",
      "description": "הזמינו את Michael Kofman להרצות על מנהיגות ניהולית, אסטרטגיית טכנולוגיה, בריאות דיגיטלית וממשל תאגידי."
    },
    "caseStudies": {
      "title": "מקרי בוחן — Michael Kofman",
      "description": "מקרי בוחן מהקריירה של Michael Kofman: 9 Net Avenue Inc. ו-Digital Invest Inc."
    },
    "mediaKit": {
      "title": "ערכת מדיה — Michael Kofman",
      "description": "ביוגרפיות רשמיות, תמונות ופרטי קשר עבור עיתונות ומפיקי אירועים."
    },
    "article1": {
      "title": "מהנדסה לתשתית גלובלית — Michael Kofman",
      "description": "Michael Kofman על מסלול הקריירה מהנדסת לוויינים ועד הקמת חברות גלובליות לתשתיות נתונים."
    },
    "article2": {
      "title": "רפואה מדויקת וטכנולוגיה — Michael Kofman",
      "description": "Michael Kofman על שילוב מדעי החיים עם AI, ML וטכנולוגיות DNA ברפואה המודרנית."
    },
    "privacy": {
      "title": "מדיניות פרטיות — Michael Kofman",
      "description": "מדיניות פרטיות של mkofman.com — טפסים ואנליטיקה."
    },
    "board": {
      "title": "Advisory — Michael Kofman",
      "description": "Strategic advisory conversations with technology, healthcare, and infrastructure organizations."
    },
    "thesis": {
      "title": "Leadership Thesis — Michael Kofman",
      "description": "Michael Kofman's principles for building durable companies, governing technology, and leading through consequential change."
    },
    "press": {
      "title": "Press Archive — Michael Kofman",
      "description": "Selected press coverage, awards, and media references spanning Michael Kofman's career in technology and entrepreneurship."
    },
    "ip": {
      "title": "Intellectual Property — Michael Kofman",
      "description": "Patents, publications, and applied research by Michael Kofman across computing, communications, data, and digital health."
    },
    "briefIpo": {
      "title": "What an IPO Changes — Michael Kofman",
      "description": "An executive brief on the operating discipline, governance, and accountability required before and after an initial public offering."
    },
    "briefGenetic": {
      "title": "From Genetic Data to Clinical Decisions — Michael Kofman",
      "description": "An executive brief on translating genomic information into responsible, useful, and scalable clinical intelligence."
    },
    "briefAi": {
      "title": "AI Strategy Beyond the Pilot — Michael Kofman",
      "description": "An executive brief on moving artificial intelligence from experimentation to governed, measurable enterprise capability."
    },
    "deck": {
      "title": "Executive Overview — Michael Kofman",
      "description": "Private executive overview for qualified introductions."
    }
  },
  "home": {
    "heroEyebrow": "האתר הרשמי של Michael Kofman",
    "heroTitle1": "נבנה להישאר.",
    "heroTitle2": "מונחה בשיקול דעת.",
    "heroCta": "גלו את הסיפור שלי",
    "heroAlt": "Michael Kofman",
    "quote1text": "מוזכר בין החברות המובילות בארה\"ב ברפואת דיוק ובריאות דיגיטלית.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "יזם השנה — הכרה למנהיגות ולהישגים פורצי דרך בחדשנות פלטפורמות ותשתיות.",
    "quote2author": "Entrepreneur Magazine · 2001",
    "quote3text": "Digital Invest Inc. בין 10 החברות המובילות בארה\"ב ברפואת דיוק ובריאות דיגיטלית.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "דיוק הנדסי עם אסטרטגיה עסקית — ממערכות לוויין לתשתית של",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "הכירו את Michael Kofman",
    "aboutTitle": "חברות שנבנו לטווח ארוך",
    "aboutLead1": "מנכ\"ל Digital Invest Inc. ומייסד AGRON Inc. ייסד והוביל חברות בארה\"ב ובאירופה.",
    "aboutLead2": "מ-9 Net Avenue (שווי שיא",
    "aboutLink": "ביוגרפיה מלאה",
    "expertiseEyebrow": "תחומי מיקוד",
    "expertiseTitle": "מנהיגות בכירה בין תעשיות",
    "expertiseLead": "ארבעה עשורים של בנייה, ייעוץ והשקעה בתשתית, בריאות ורובוטיקה.",
    "exp1title": "מנכ\"ל ומייסד",
    "exp1desc": "ייסד והנהיג מספר חברות טכנולוגיה בארצות הברית ובאירופה.",
    "exp1link": "חברות ←",
    "exp2title": "ארכיטקט טכנולוגי",
    "exp2desc": "תכנן תקשורת מאובטחת, מנועי אנליטיקה חיזויית ופלטפורמות אינטגרציית נתונים ברמה לאומית למגזרים ממשלתיים, צבאיים וטלקום.",
    "exp2link": "קריירה ←",
    "exp3title": "בריאות דיגיטלית",
    "exp3desc": "מוביל את שינוי הרפואה באמצעות בינה מלאכותית, למידת מכונה וטכנולוגיות DNA. שיתף פעולה עם Harvard Medical School ו-Stanford Biomath בדיווח גנטי.",
    "exp3link": "Digital Invest ←",
    "exp4title": "יועץ דירקטוריון",
    "exp4desc": "חבר בדירקטוריונים ומייעץ לחברות ציבוריות ופרטיות בנושאי כיוון אסטרטגי, ממשל תאגידי ויוזמות צמיחה מונחות טכנולוגיה.",
    "exp4link": "ייעוץ →",
    "stat1": "שנות מנהיגות",
    "stat2": "חברות שנוסדו",
    "stat3": "שווי שוק שיא",
    "stat4": "עובדים",
    "recEyebrow": "הכרה",
    "recTitle": "הכרה נבחרת",
    "recLead": "פרסי תעשייה והכרה בקרב עמיתים ביזמות, רפואה והנדסה.",
    "award1title": "יזם השנה",
    "award1desc": "Entrepreneur Magazine · 2001",
    "award2title": "10 מובילים ברפואת דיוק",
    "award2desc": "Digital Invest Inc. — U.S., 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "הכרה ועיתונות →",
    "heroSub": "טכנולוגיה, עסקים והשקעות בתשתיות, מדעי החיים ומערכות אוטונומיות.",
    "primaryCta": "בקשת ייעוץ",
    "secondaryCta": "צפייה במקרי בוחן",
    "featuredEyebrow": "כפי שפורסם ב",
    "caseStudiesEyebrow": "תוצאות מוכחות",
    "caseStudiesTitle": "מקרי בוחן",
    "caseStudiesLead": "הקמה, הרחבה והובלת חברות משלב מוקדם ועד רכישה.",
    "caseStudiesLink": "צפייה בכל מקרי הבוחן →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "Founded 9 Net Avenue Inc.; acquired by Concentric Networks in 2000.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "Healthcare Tech Outlook feature (2023).",
    "cs3title": "AGRON Inc.",
    "cs3desc": "Founded in 2026 — the AGRON Ecosystem for UAV capability development, geospatial systems, and maritime intelligence.",
    "boardCtaEyebrow": "Advisory",
    "boardCtaTitle": "Experience for the Decisions That Define an Enterprise",
    "boardCtaLead": "Independent perspective for boards and leaders navigating technology, governance, transformation, and growth.",
    "boardCtaBtn": "Explore Advisory",
    "testimonialsEyebrow": "Trusted Perspective",
    "testimonialsTitle": "What Colleagues Value",
    "videoEyebrow": "Executive Perspective",
    "videoTitle": "Leadership at the Intersection of Technology and Enterprise",
    "videoLead": "A concise introduction to the principles, experience, and long-term perspective behind Michael Kofman's work.",
    "videoCta": "Read Leadership Thesis →",
    "heroName": "Michael Kofman",
    "heroRole": "מנהיג טכנולוגי · מייסד · יועץ",
    "introText": "Michael Kofman הוא מנהיג טכנולוגי ומייסד חברות. עבודתו משתרעת על הנדסת לוויינים, תשתיות אינטרנט, חברות טכנולוגיה ציבוריות ומדעי החיים. ייסד את 9 Net Avenue Inc., שנרכשה על ידי Concentric Networks ב-2000. CEO של Digital Invest Inc. ברפואה ביו-מתמטית ואינטליגנציה גנומית; מייסד AGRON Inc. בפעילות אווירית-קרקעית אוטונומית ומערכות גאו-מרחביות. מכהן בדירקטוריונים ומייעץ בתחומי טכנולוגיה, בריאות ותשתיות.",
    "introLink": "ביוגרפיה מלאה →",
    "currentEyebrow": "עבודה נוכחית",
    "currentTitle": "מוקד נוכחי",
    "currentDiTitle": "Digital Invest Inc.",
    "currentDiDesc": "רפואה ביו-מתמטית, נתונים גénomיים ואינטליגנציה קlinית — AI, ML וטכנולוגיות DNA לתוצאות בריאותיות אחראיות.",
    "currentDiLink": "Ventures →",
    "currentAgTitle": "AGRON Inc.",
    "currentAgDesc": "פעילות אווירית-קרקעית אוטונומית, פיתוח יכולות UAV, מערכות גאו-מרחביות ותשתית מודיעין ימי.",
    "currentAgLink": "agron1.com →",
    "careerEyebrow": "רשומה נבחרת",
    "careerTitle": "רציפות בין תקופות טכנולוגיות",
    "careerLead": "Selected milestones from engineering through current work in autonomous systems.",
    "career1title": "Engineering & Communications",
    "career1desc": "Satellite transceiver systems, digital communications, and early engineering leadership.",
    "career2title": "Internet & Infrastructure",
    "career2desc": "Internet infrastructure, data centers, storage, and telecommunications at scale.",
    "career3title": "Technology Companies & Public Markets",
    "career3desc": "Company-building, acquisitions, and public-company experience including 9 Net Avenue Inc.",
    "career4title": "Life Sciences & Human Data",
    "career4desc": "Biotechnology, genetic data, precision medicine, and health intelligence platforms.",
    "career5title": "Autonomous Systems",
    "career5desc": "Aerial-ground robotics, UAV operations, and geospatial infrastructure.",
    "careerLink": "The Record →",
    "perspectivesEyebrow": "Perspectives",
    "perspectivesTitle": "Selected Writing",
    "perspectivesLink": "All insights →",
    "footerHomeDesc": "מנהיג טכנולוגי, מייסד ויועץ."
  },
  "about": {
    "eyebrow": "אודות Michael Kofman",
    "title": "שלושה עשורים של ניסיון",
    "lead": "מנהיג טכנולוגי, מייסד ויועץ.",
    "glance": "בקצרה",
    "role": "תפקיד נוכחי",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "מיקום",
    "locationVal": "Charlotte, North Carolina",
    "education": "השכלה",
    "educationVal": "Doctor of Technical Sciences\nPh.D. in Information Technology\nMaster's Degrees — Electronics, Digital Satellite Systems, and Economics",
    "university": "אוניברסיטה",
    "universityVal": "Ukrainian State Marine Technical University",
    "languages": "שפות",
    "languagesVal": "English, Russian, Ukrainian",
    "contactLabel": "קשר",
    "principlesEyebrow": "Operating Principles",
    "principlesTitle": "How I Lead",
    "p1title": "Understand the System",
    "p1text": "Before changing an organization, understand its incentives, architecture, constraints, and sources of trust.",
    "p2title": "Make Accountability Explicit",
    "p2text": "Clear ownership and measurable outcomes turn strategy from presentation material into operating reality.",
    "p3title": "Leave Stronger Institutions",
    "p3text": "Leadership should compound capability by developing people, improving decisions, and building systems that endure.",
    "archiveEyebrow": "From the Archive",
    "archiveTitle": "מהארכיון",
    "archiveLead": "Authentic material from company building, infrastructure, and leadership.",
    "photo9netTitle": "9 Net Avenue",
    "photo9netCaption": "Founder & CEO — hosting and internet infrastructure company, acquired by Concentric Networks in 2000.",
    "photoServerTitle": "Data Infrastructure",
    "photoServerCaption": "Hands-on years in storage, networking, and high-density server environments at DataPeer and related ventures.",
    "photoTodayTitle": "Today",
    "photoTodayCaption": "Digital Invest Inc., AGRON Inc., and advisory work.",
    "secIntroTitle": "Introduction",
    "secTechTitle": "טכנולוגיה ותשתיות",
    "secBusinessTitle": "Business",
    "secCurrentTitle": "Current Work",
    "secBackgroundTitle": "Background",
    "recordLink": "The Record →",
    "secBackgroundP1": "Doctor of Technical Sciences ו-Ph.D. in Information Technology. מחבר מאמרים טכניים; פטנט HDTV לווייני נרכש על ידי Sony.",
    "bioP1": "Michael Kofman הוא מנהיג טכנולוגי, מייסד ויועץ. CEO של Digital Invest Inc. ומייסד AGRON Inc., עם ניסיון בהנדסת לוויינים, תשתיות אינטרנט, חברות ציבוריות ומדעי החיים.",
    "bioP2": "As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. In 2026 he founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network. He also created Digital Invest, dedicated to the bio-mathematical sphere and transforming medicine through science, DNA technologies, AI, and ML.",
    "secBioTitle": "רפואה מדויקת וביוטכנולוגיה",
    "secBioP1": "טרם Digital Invest, הוא מילא תפקיד מרכזי בהצלחה של Biotechnology Group Inc. (2008 — 2014), חברה המחויבת לבדיקות וניתוח DNA, אוטומציה של תהליכי יצירת פרופילים גנטיים ומחקר גנטי אנושי מקיף. מר Kofman מאמין בתוקף בפוטנציאל של שילוב מדעי החיים עם ההתקדמות הטכנולוגית העדכנית ביותר.",
    "secBioP2": "תחת הנהגתו, יוזמו פרויקטים מוצלחים של בדיקות גנטיות באוקראינה, ברוסיה ובמדינות Baltic. ניסיון ייחודי זה מועשר ללא הרף בטכנולוגיות מודרניות ובציוד חדש. בשיתוף עם Harvard Medical School ו-Stanford Biomath, מר Kofman מילא תפקיד מכריע בפיתוח דוחות גנטיים מובנים לרופאים ולמטופלים כאחד. גישה חדשנית זו אומצה על ידי מעבדות מובילות בארצות הברית ובחו\"ל.",
    "secTechP1": "רקע הנדסי במערכות transceiver לווייניות ותקשורת דיגיטלית ב-Astra Corp.",
    "secTechP2": "ב-2006, מר Kofman הקים את XIBI Group Inc. — חברת טכנולוגיה שבה כיהן בדירקטוריון. החברה האמריקאית מתמחה באחסון נתונים ובשירותי ניהול big data לארגונים מסחריים וממשלתיים גדולים.",
    "secTechP3": "מ-2000 עד 2004, מר Kofman הוביל את DataPeer Inc. — חברת ניהול ואחסון נתונים המציעה מגוון רחב של שירותים הקשורים לאחסון מידע לעסקים קטנים ובינוניים. ב-DataPeer פיתח פתרונות טכנולוגיים ייחודיים שסייעו למעקב מהיר יותר אחר מידע ולנגישות קלה יותר לנתונים עבור משתמשי קצה ומוסדות ממשלתיים ברחבי העולם.",
    "secTechP4": "Founded 9 Net Avenue Inc. in 1996. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "secPost9NetP1": "לאחר רכישת 9 Net Avenue, מר Kofman צבר ניסיון רב בעבודה בחברות ציבוריות, השתתפות בדירקטוריונים וקבלת החלטות אסטרטגיות ברמה הנהלתית העליונה.",
    "secEarlyTitle": "קריירה מוקדמת והנדסה",
    "secEarlyP1": "מ-1994 עד 1996, מר Kofman כיהן כמנכ\"ל וכמנהל טכנולוגיות מידע ב-Elitan United Inc. — חברת IT מ-Massachusetts, שסיפקה אסטרטגיות מקיפות ושירותים טכנולוגיים לארגונים גלובליים מובילים. הוא מילא תפקיד מכריע בפיתוח וניהול תשתית ניתנת להרחבה, והוביל את צמיחת החברה מ-9 עובדים בלבד ליותר מ-4,000 עובדים ברחבי העולם.",
    "secEarlyP2": "מ-1989 עד 1994, הוא היה מייסד ומנכ\"ל Astra Corp, אחת היצרניות הגדולות באירופה של מערכות לוויין דיגיטליות לשידור וקליטה, שזכתה להכרה בינלאומית בתחום מכשירי הלוויין. תחומי אחריותו כללו מחקר, פיתוח מערכות הפעלה, יישומי תוכנת רשת ואסטרטגיה טכנית כוללת.",
    "secEarlyP3": "מ-1984 עד 1989, מר Kofman עבד במספנת האוניות ב-Nikolaev, אוקראינה, שם השתתף באופן פעיל בפיתוח וביצירת מערכות לוויין לשידור וקליטה להעברת מידע סודי לספינות צבאיים ובחזרה. הוא הוכר כמהנדס אלקטרוניקה ברמה הגבוהה ביותר, וקיבל את דרגה 6 — ההכרה הגבוהה ביותר במספנה, שבו עבדו 93 אלף אנשים.",
    "secResearchTitle": "מחקר ופטנטים",
    "secResearchP1": "Michael Kofman הוא מחבר מאמרים טכניים המתמקדים במערכות לוויין ואופטיות להעברת נתונים. הוא גם קיבל פטנט בתחום מערכות טלוויזיה בגובה רזולוציה (HDTV) לווייניות דיגיטליות, שנרכש לאחר מכן על ידי Sony.",
    "secAgronTitle": "Robotics, UAV & Maritime Intelligence",
    "secAgronP1": "In 2026, Mr. Kofman founded AGRON Inc. to build the AGRON Ecosystem — a corporate operating architecture for aerial and ground robotics, governed mission execution, and network infrastructure connecting teams, assets, and operational data. The ecosystem delivers consulting, assessment, capability development, and training for UAV and Counter-UAS organizations, alongside maritime intelligence and security services at agron1.com.",
    "secBusinessP1": "ייסד והנהיג חברות טכנולוגיה רבות. כרונולוגיה מלאה ב-The Record.",
    "secCurrentP1": "CEO של Digital Invest Inc. ברפואה ביו-מתמטית ואינטליגנציה גénomית. מייסד AGRON Inc. בפעילות אווירית-קרקעית אוטונומית."
  },
  "ventures": {
    "eyebrow": "תיק חברות",
    "title": "חברות שהקים והוביל",
    "lead": "מרפואת דיוק ורובוטיקה ועד תשתיות נתונים גלובליות — הקמה, צמיחה והובלה בארה\"ב ובאירופה.",
    "ecosystemEyebrow": "Venture Ecosystem",
    "ecosystemTitle": "Companies Across Technology Frontiers",
    "ecosystemLead": "A portfolio shaped by recurring themes: trusted data, intelligent infrastructure, human health, and systems built for scale.",
    "statusActive": "Active",
    "statusExited": "Exited",
    "statusLegacy": "Legacy",
    "v1lesson": "Lesson: infrastructure wins when reliability, economics, and customer trust improve together.",
    "v2lesson": "Lesson: precision medicine requires equal discipline in science, software, privacy, and clinical usefulness.",
    "v3lesson": "Lesson: autonomy creates value only when sensing, communications, and human oversight form one resilient system.",
    "v5lesson": "לקח: קנה מידה בתשתיות נבנה במצוינות תפעולית הרבה לפני יציאה.",
    "currentEyebrow": "Current",
    "historyEyebrow": "Selected History",
    "v2highlight": "Harvard Medical School ו-Stanford Biomath — שיתוף פעולה בדיווח genético",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — an Aerial-Ground Robotics Operations Network spanning UAV and Counter-UAS consulting, technology assessment, capability development, training infrastructure, product validation, geospatial systems (ISDRI), and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "v0role": "Founder",
    "v0year": "2026 — Present",
    "v1highlight": "10 החברות המובילות בארה\"ב ברפואה מדויקת — 2023",
    "v1p1": "רפואה ביו-מתמטית, נתונים גנומיים ואינטליגנציה קlinית — AI, ML וטכנולוגיות DNA בזרימות clínico ומחקר.",
    "v1role": "מייסד ומנכ\"ל · חבר דירקטוריון",
    "v1year": "2021 — עד היום",
    "v2p1": "בדיקות וניתוח DNA, אוטומציה של פרופילים גנטיים ומחקר גנטי אנושי מקיף. יזם פרויקטי בדיקות גנטיות באוקראינה, ברוסיה ובמדינות Baltic.",
    "v2p2": "שיתף פעולה עם Harvard Medical School ו-Stanford Biomath בדוחות גנטיים שאומצו על ידי מעבדות מובילות ברחבי העולם.",
    "v2role": "מנכ\"ל ו-CTO",
    "v2year": "2008 — 2014",
    "v3highlight": "פתרונות נתונים ארגוניים וממשלתיים",
    "v3p1": "אחסון נתונים ושירותי ניהול big data לארגונים מסחריים וממשלתיים גדולים. ביסס את החברה כספק מהימן של פתרונות נתונים ארגוניים.",
    "v3role": "מייסד ומנכ\"ל · דירקטוריון",
    "v3year": "2006 — 2011",
    "v4highlight": "פלטפורמה גלובלית לניהול נתונים",
    "v4p1": "ניהול ואחסון נתונים לעסקים קטנים ובינוניים. פיתח פתרונות למעקב מהיר יותר אחר מידע ולנגישות קלה יותר לנתונים עבור משתמשי קצה ומוסדות ממשלתיים ברחבי העולם.",
    "v4role": "מייסד ומנכ\"ל",
    "v4year": "2000 — 2004",
    "v5highlight": "Acquired · Concentric Networks, 2000",
    "v5p1": "Founded and led a hosting and internet infrastructure company. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "v5role": "מייסד ומנכ\"ל",
    "v5year": "1996 — 2000",
    "v6highlight": "אסטרטגיית IT ותשתיות גלובליות",
    "v6p1": "חברת IT מ-Massachusetts המספקת אסטרטגיות מקיפות ושירותים טכנולוגיים לארגונים גלובליים מובילים. הוביל פיתוח תשתית ניתנת להרחבה ותפעול IT גלובלי.",
    "v6role": "מנכ\"ל ומנהל טכנולוגיות מידע",
    "v6year": "1994 — 1996",
    "v7highlight": "מובילה אירופית במערכות לוויין",
    "v7p1": "אחת היצרניות הגדולות באירופה של מערכות לוויין דיגיטליות לשידור וקליטה. הוביל מחקר, פיתוח מערכות הפעלה, יישומי תוכנת רשת ואסטרטגיה טכנית כוללת.",
    "v7role": "מייסד ומנכ\"ל",
    "v7year": "1989 — 1994",
    "v8highlight": "הנדסת מערכות לוויין צבאיות",
    "v8p1": "פיתוח ויצירת מערכות לוויין לשידור וקליטה להעברת מידע סודי לספינות צבאיים. הוכר כמהנדס אלקטרוניקה ברמה הגבוהה ביותר במספנה של 93,000 עובדים.",
    "v8role": "מהנדס אלקטרוניקה · דרגה עליונה (6)",
    "v8year": "1984 — 1989",
    "v1p2": "Portfolio initiatives include BioMath Life, BioMath Core, and SAVEN — detailed case studies to follow.",
    "v1brole": "CEO",
    "v1bp1": "Transitional period bridging biotechnology work into new technology development — building operational and R&D experience ahead of Digital Invest Inc.",
    "v1byear": "2014 — 2020"
  },
  "career": {
    "eyebrow": "מסלול מקצועי",
    "title": "The Record",
    "lead": "טכנולוגיה, חברות וניסיון תפעולי לאורך תקופות של שינוי טכנולוגי.",
    "timelineEyebrow": "ציר זמן",
    "timelineTitle": "אבני דרך",
    "strengthsEyebrow": "חוזקות",
    "strengthsTitle": "תחומי מומחיות",
    "filterAll": "All",
    "filterHealthcare": "Healthcare",
    "filterInfrastructure": "Infrastructure",
    "filterDefense": "Defense",
    "filterTelecom": "Telecommunications",
    "periodCurrent": "Autonomous Systems",
    "periodCurrentLead": "AI, robotics, autonomous operations, geospatial systems, and related current infrastructure.",
    "period1title": "Engineering & Communications",
    "period1lead": "Early engineering, satellite systems, communications, and related technology work.",
    "period2title": "Internet & Infrastructure",
    "period2lead": "Internet infrastructure, telecommunications, data centers, storage, and related companies.",
    "period3title": "Companies & Public Markets",
    "period3lead": "Company building, transactions, public-company involvement, and executive roles.",
    "period4title": "Life Sciences & Human Data",
    "period4lead": "Biotechnology, health-related technology, data, and precision medicine.",
    "period5title": "Government & Defense Programs",
    "period5lead": "Technology strategy and delivery for government, defense, and state-owned enterprise programs.",
    "t1desc": "Digital Invest Inc. הוקמה ב-2021. רפואה ביו-מתמטית, אינטליגנציה גנומית ופלטפורמות נתונים קlinיים. Healthcare Tech Outlook (2023).",
    "t0desc": "Founded AGRON Inc. to build the AGRON Ecosystem — consulting, assessment, capability development, training infrastructure, and product support for UAV and Counter-UAS programmes, plus AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure. Connects aerial and ground robotics, governed mission execution, and network infrastructure linking teams, assets, and operational data.",
    "t0role": "Founder",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — Present",
    "t10desc": "פיתח ויצר מערכות לוויין לשידור וקליטה להעברת מידע סודי לספינות צבאיים. הוכר כמהנדס אלקטרוניקה ברמה הגבוהה ביותר במספנה של 93,000 עובדים — תחילתה של קריירה מצטיינת בטכנולוגיה וחדשנות.",
    "t10role": "מהנדס אלקטרוניקה — דרגה 6 (הגבוהה ביותר)",
    "t10title": "Nikolaev Shipbuilding Plant",
    "t10year": "1984 — 1989",
    "t1role": "מייסד ומנכ\"ל",
    "t1title": "Digital Invest Inc.",
    "t1year": "2021 — עד היום",
    "t2desc": "הוביל אסטרטגיה טכנולוגית ומסירה לתוכניות סודיות ורגישות הכוללות סוכנויות ממשלתיות אמריקאיות, מערכות ביטחון של בני ברית וארגונים בבעלות המדינה. עמד בראש פרויקטים טכניים מורכבים לחברות בבעלות הממשלה במגזרים שונים. בעקבות 11 בספטמבר 2001, הוביל יוזמות ממשלתיות בקנה מידה גדול המתמקדות ב-big data, תקשורת מאובטחת, אנליטיקה חיזויית ואינטגרציה של נתונים ברמה לאומית — כולל תכנון, בנייה ותפעול של מרכזי נתונים בעלי תפוקה גבוהה בארצות הברית ובאירופה. שיתף פעולה עם קציני תוכניות צבאיים, ספקי טכנולוגיה וגורמים רגולטוריים.",
    "t2role": "יועץ טכנולוגי ראשי / אדריכל תוכניות",
    "t2title": "GovTech, ביטחון ותוכניות מדינה",
    "t2year": "2001 — 2019",
    "t3desc": "הוביל בדיקות וניתוח DNA, אוטומציה של פרופילים גנטיים ומחקר גנטי אנושי מקיף. יזם פרויקטי בדיקות גנטיות באוקראינה, ברוסיה ובמדינות Baltic. שיתף פעולה עם Harvard Medical School ו-Stanford Biomath לפיתוח דוחות גנטיים מובנים שאומצו על ידי מעבדות מובילות ברחבי העולם.",
    "t3role": "מנכ\"ל ו-CTO",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4desc": "הוביל פריסות תשתית לאומיות בקנדה, איטליה, שווייץ, אוקראינה והרפובליקות Baltic. פיקח על יותר מ-1,000 מהנדסים וצוותי פריסה בפעילות תקשורת כולל מערכות מיתוג, הרחבת פס רחב וקישוריות חוצת גבולות. יישם מערכות ליבה לגיבוית רשת, אופטימיזציה של זמן פעילות וניתוב חכם.",
    "t4role": "VP טכנולוגיה / CTO אזורי — מזרח אירופה ו-CIS",
    "t4title": "פרויקטי תקשורת",
    "t4year": "2000 — 2012",
    "t5desc": "הקים חברת טכנולוגיה המתמחה באחסון נתונים ובניהול big data לארגונים מסחריים וממשלתיים גדולים. ביסס את החברה כספק מהימן של פתרונות נתונים ארגוניים.",
    "t5role": "מייסד ומנכ\"ל · דירקטוריון",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6desc": "הקים חברת ניהול ואחסון נתונים לעסקים קטנים ובינוניים. פיתח פתרונות טכנולוגיים ייחודיים למעקב מהיר יותר אחר מידע ולנגישות קלה יותר לנתונים עבור משתמשי קצה ומוסדות ממשלתיים ברחבי העולם.",
    "t6role": "מייסד ומנכ\"ל",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "Founded and led 9 Net Avenue Inc., a hosting and internet infrastructure company. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "t7role": "מייסד ומנכ\"ל",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8desc": "הוביל אסטרטגיות IT מקיפות ושירותים טכנולוגיים לארגונים גלובליים מובילים מ-Massachusetts בתקופת התרחבות מהירה, ובנה תשתית ניתנת להרחבה ותפעול IT גלובלי.",
    "t8role": "מנכ\"ל ומנהל טכנולוגיות מידע",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9desc": "הקים אחת היצרניות הגדולות באירופה של מערכות לוויין דיגיטליות לשידור וקליטה. הוביל מחקר, פיתוח מערכות הפעלה, יישומי תוכנת רשת ואסטרטגיה טכנית כוללת, וזכה להכרה בינלאומית.",
    "t9role": "מייסד ומנכ\"ל",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994",
    "t1bdesc": "Transitional period bridging biotechnology work into new technology development — building operational and R&D experience ahead of Digital Invest Inc.",
    "t1brole": "CEO",
    "t1byear": "2014 — 2020"
  },
  "recognition": {
    "eyebrow": "פרסים",
    "title": "פרסים והכרה",
    "lead": "הוקרה ביזמות, רפואת דיוק, הנדסה ומנהיגות.",
    "industryEyebrow": "פרסי התעשייה",
    "industryTitle": "אותות כבוד מרכזיים",
    "ipEyebrow": "קניין רוחני",
    "ipTitle": "פטנטים ופרסומים",
    "eduEyebrow": "השכלה",
    "eduTitle": "תארים אקדמיים",
    "pressEyebrow": "עיתונות",
    "pressTitle": "הופיע ב",
    "moreLink": "צפו בפטנטים, פרסומים וכתבות בעיתונות בעמוד Insights →",
    "a1title": "יזם השנה",
    "a1desc": "Entrepreneur Magazine · 2001",
    "a2title": "10 החברות המובילות בארה\"ב ברפואה מדויקת",
    "a2desc": "Digital Invest Inc. הוכרה בין 10 החברות הטובות ביותר באמריקה ברפואה מדויקת ובריאות דיגיטלית — 2023.",
    "a3title": "Who's Who in America",
    "a3desc": "רשום, 1999 — 2018 — על הישגים יוצאי דופן ביצירה ופיתוח עסקים.",
    "a4title": "Who's Who in the World",
    "a4desc": "רשום, 2000 — 2004 — בין המנהיגים העולמיים במדע, הנדסה וחדשנות עסקית.",
    "a5title": "Who's Who in Science & Engineering",
    "a5desc": "רשום, 2000 — 2014 — על תרומות לטכנולוגיה, מערכות לוויין ותשתית דיגיטלית.",
    "a6title": "מהנדס אלקטרוניקה — דרגה 6",
    "a6desc": "ההכרה הגבוהה ביותר ב-Nikolaev Shipbuilding Plant (93,000 עובדים) על הנדסת מערכות לוויין לשידור וקליטה.",
    "ip1year": "פטנט",
    "ip1title": "מערכות HDTV לווייניות דיגיטליות",
    "ip1role": "נרכש לאחר מכן על ידי Sony",
    "ip1desc": "פטנט במערכות HDTV לווייני דיגיטלי, נרכש על ידי Sony Corporation.",
    "ip2year": "פרסומים",
    "ip2title": "מאמרים טכניים",
    "ip2role": "מערכות לוויין ואופטיות",
    "ip2desc": "מחבר מאמרים טכניים המתמקדים במערכות לוויין ואופטיות להעברת נתונים. תרומות המחקר שלו כוללות עיבוד אותות, מידול סימולציה ופלטפורמות אוטומציה המיושמות בתקשורת, תשתית לאומית ובריאות דיגיטלית.",
    "ip3year": "מחקר",
    "ip3title": "שיתופי פעולה בינלאומיים",
    "ip3role": "ארה\"ב ואירופה",
    "ip3desc": "השתתף בשיתופי מחקר בינלאומיים וביוזמות להעברת ידע. פיתח מערכות הנדסה משובצות לאיסוף נתונים, אבחון חיזוי ותזמור מבוסס ענן במגזרים שונים.",
    "edu1title": "דוקטור לתואר במדעי הטכניקה",
    "edu2title": "Ph.D. בטכנולוגיות מידע",
    "edu3title": "תארי מוסמא",
    "edu3desc": "אלקטרוניקה, מערכות לוויין דיגיטליות וכלכלה",
    "press1title": "Healthcare Tech Outlook",
    "press1role": "כתבה על Digital Invest Inc.",
    "press1desc": "Healthcare Tech Outlook על Digital Invest Inc. (2023).",
    "press1link": "קרא את הכתבה ←",
    "press2title": "Top Precision Medicine Solutions",
    "press2role": "הכרה בתעשייה",
    "press2desc": "נבחרה בין חברות פתרונות הרפואה המדויקת המובילות, המדגישה את תפקיד Digital Invest בקידום גישות ביו-מתמטיות לבריאות המודרנית.",
    "press2link": "צפה ברשימה ←"
  },
  "contact": {
    "eyebrow": "צור קשר",
    "title": "בואו נהיה בקשר",
    "lead": "לייעוץ, דירקטוריונים ושותפויות אסטרטגיות.",
    "infoTitle": "קשר ישיר",
    "email": "דוא\"ל",
    "phone": "טלפון",
    "location": "מיקום",
    "locationVal": "Charlotte, North Carolina\nUnited States",
    "linkedin": "LinkedIn",
    "company": "חברה נוכחית",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member\nAGRON Inc.\nFounder",
    "formTitle": "שלח הודעה",
    "formLead": "מלאו את הטופס ואחזור אליכם.",
    "firstName": "שם פרטי",
    "lastName": "שם משפחה",
    "emailLabel": "כתובת דוא\"ל",
    "subject": "נושא",
    "message": "הודעה",
    "inquiryType": "Inquiry Type",
    "inquiryAdvisory": "Advisory",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "calendlyEyebrow": "Schedule a Conversation",
    "calendlyTitle": "Choose a Convenient Time",
    "calendlyLead": "For qualified board, advisory, speaking, and strategic partnership inquiries.",
    "calendlyPlaceholder": "Scheduling calendar will appear here.",
    "calendlyCta": "Open Scheduling Calendar",
    "inquiryBusiness": "Business",
    "infoEyebrow": "פרטי קשר"
  },
  "consulting": {
    "eyebrow": "שירותי ייעוץ",
    "title": "ייעוץ",
    "heroEyebrow": "הכוונה עסקית אסטרטגית",
    "heroTitle": "ייעוץ אסטרטגי",
    "heroLead": "שלושים וחמש שנים של הקמת חברות וייעוץ בארה\"ב ובאירופה — תשתיות נתונים, govtech, רפואת דיוק ורובוטיקה.",
    "cta": "יצירת קשר עם Michael Kofman",
    "introLead": "מנכ\"ל Digital Invest Inc. וחבר דירקטוריון. מיקוד: טכנולוגיות מתפתחות, אבטחה, מחקר והקצאת הון.",
    "specialtiesEyebrow": "תחומי מיקוד",
    "specialtiesTitle": "תחומי ההתמחות של Michael Kofman",
    "area1title": "Board Service",
    "area1desc": "Independent director and board-level work in technology strategy, corporate governance, and growth-stage oversight.",
    "area2title": "CEO & Founder Advisory",
    "area2desc": "Corporate and technology strategy, organizational development, transactions, and applicable capital-markets experience.",
    "area3title": "Technology Due Diligence",
    "area3desc": "Evaluation of infrastructure, data platforms, security architecture, and applied technology based on documented operating experience.",
    "redirectLead": "Strategic advisory work is documented on the Advisory page. For professional inquiries, use Contact.",
    "redirectLink": "Advisory →"
  },
  "insights": {
    "eyebrow": "Perspectives",
    "title": "תובנות",
    "heroTitle": "פרספקטивות מנהיגות",
    "selectedEyebrow": "נקודות שיא נבחרות",
    "selectedTitle": "הכרה בולטת",
    "allPressTitle": "כל הכתבות בתקשורת",
    "quotesEyebrow": "בתקשורת",
    "quotesTitle": "הכרה בתעשייה וציטוטים",
    "articlesEyebrow": "תובנות",
    "articlesTitle": "נקודות מבט ניהוליות",
    "briefsEyebrow": "Executive Briefs",
    "briefsTitle": "Ideas for Leaders",
    "briefsLead": "Short, practical perspectives on governance, technology, healthcare, and company building.",
    "brief1title": "What an IPO Changes",
    "brief1desc": "The operating and governance disciplines that public-market readiness demands.",
    "brief1tag": "Capital Markets",
    "brief2title": "From Genetic Data to Clinical Decisions",
    "brief2desc": "How to build useful health intelligence without outrunning evidence or trust.",
    "brief2tag": "Precision Medicine",
    "brief3title": "AI Strategy Beyond the Pilot",
    "brief3desc": "A framework for turning experiments into governed enterprise capability.",
    "brief3tag": "Artificial Intelligence",
    "readingEyebrow": "Reading List",
    "readingTitle": "Books That Shape Strategic Thinking",
    "r1title": "The Innovator's Dilemma",
    "r1author": "Clayton M. Christensen",
    "r2title": "Thinking, Fast and Slow",
    "r2author": "Daniel Kahneman",
    "r3title": "The Beginning of Infinity",
    "r3author": "David Deutsch",
    "r4title": "Good Strategy/Bad Strategy",
    "r4author": "Richard Rumelt",
    "r5title": "The Structure of Scientific Revolutions",
    "r5author": "Thomas S. Kuhn",
    "newsletterEyebrow": "Occasional Notes",
    "newsletterTitle": "Executive Perspective, Without the Noise",
    "newsletterLead": "Periodic essays and brief observations on technology, governance, and durable company building.",
    "newsletterCta": "Subscribe for Updates",
    "lead": "Substantive writing and executive briefs.",
    "relatedLead": "Recognition, press coverage, and patents are documented separately.",
    "topicsLead": "הנושאים מבוססים על ניסיון תפעולי מתועד בטכנולוגיה, בריאות ותשתיות."
  },
  "cta": {
    "eyebrow": "בואו נעבוד יחד",
    "title": "בקשת ייעוץ או הזמנת הרצאה",
    "lead": "לתפקידי ייעוץ, משרות בדירקטוריון, הרצאות ושותפויות אסטרטגיות.",
    "button": "יצירת קשר"
  },
  "speaking": {
    "eyebrow": "הרצאות וכנסים",
    "title": "הזמינו את Michael Kofman להרצות",
    "lead": "זמין להרצאות בנושאי מנהיגות ניהולית, אסטרטגיה טכנולוגית, בריאות דיגיטלית, תשתיות נתונים וממשל תאגידי.",
    "topicsEyebrow": "נושאי ההרצאה",
    "topicsTitle": "תחומי מומחיות",
    "topicsLead": "הנושאים מבוססים על עשרות שנות ניסיון בהקמה ובהובלה של חברות בארצות הברית ובאירופה.",
    "processEyebrow": "איך להזמין",
    "processTitle": "תהליך ההזמנה",
    "process1title": "שלחו פנייה",
    "process1desc": "השתמשו בטופס יצירת הקשר או שלחו אימייל ל-mkofman@mkofman.com עם פרטי האירוע, קהל היעד והנושאים המבוקשים.",
    "process2title": "אישור היקף",
    "process2desc": "מתאמים את הפורמט (הרצאת מפתח, פאנל, ישיבת דירקטוריון או שולחן עגול להנהלה) ואת הלוגיסטיקה.",
    "process3title": "יצירת ערך",
    "process3desc": "המצגות מבוססות על תוצאות אמיתיות ממיזמים בתחומי אחסון נתונים, govtech ורפואה מדויקת.",
    "cta": "בקשת הזמנת הרצאה",
    "catalogEyebrow": "Speaking Topics",
    "catalogTitle": "Executive Conversations for Consequential Change",
    "catalogLead": "Keynotes, board sessions, and leadership briefings tailored to the audience, sector, and decision context.",
    "t1title": "Governing AI Before It Governs the Enterprise",
    "t1audience": "Boards, audit and risk committees",
    "t1format": "Board briefing or keynote",
    "t2title": "From Technology Trend to Enterprise Strategy",
    "t2audience": "CEOs, executive teams, investors",
    "t2format": "Keynote or executive workshop",
    "t3title": "Building Companies Through Market Cycles",
    "t3audience": "Founders, growth leaders, private equity",
    "t3format": "Fireside chat or keynote",
    "t4title": "Precision Medicine: Promise, Proof, and Responsibility",
    "t4audience": "Healthcare leaders, clinicians, innovators",
    "t4format": "Industry keynote or panel",
    "t5title": "The Board's Role in Cyber and Technology Risk",
    "t5audience": "Directors, general counsel, risk leaders",
    "t5format": "Board education session",
    "t6title": "Engineering Trust into Digital Infrastructure",
    "t6audience": "Technology and infrastructure organizations",
    "t6format": "Technical-executive keynote",
    "t7title": "Leading Across Borders and Disciplines",
    "t7audience": "Global leadership teams and universities",
    "t7format": "Keynote or moderated conversation",
    "t8title": "From Founder to Institution Builder",
    "t8audience": "Entrepreneurs and next-generation executives",
    "t8format": "Workshop or fireside chat"
  },
  "caseStudies": {
    "eyebrow": "מקרי בוחן",
    "title": "בניית חברות שמצליחות להתרחב",
    "lead": "תוצאות נבחרות מהקמה והובלה של חברות בתחומי תשתיות נתונים ובריאות דיגיטלית.",
    "cs1eyebrow": "תשתיות נתונים · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "אתגר",
    "cs1challengeText": "לבנות ולהרחיב חברת Data Storage בשוק טכנולוגי שנמצא בתהליך קונסולידציה מהיר.",
    "cs1action": "גישה",
    "cs1actionText": "Michael Kofman ייסד את 9 Net Avenue Inc. בשנת 1996. החברה הפכה במהירות לאחת מחברות ה-Data Storage הגדולות בעולם.",
    "cs1result": "תוצאה",
    "cs1resultText": "Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO). Following the transaction, continued work with public companies and board-level roles.",
    "cs2eyebrow": "בריאות דיגיטלית · 2021 — היום",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "אתגר",
    "cs2challengeText": "להפוך גישות רפואיות מיושנות באמצעות מדע, טכנולוגיות DNA, AI ו-ML דרך פלטפורמה ביו-מתמטית חדשה.",
    "cs2action": "גישה",
    "cs2actionText": "Digital Invest Inc. הוקמה ב-2021. רפואה ביו-מתמטית, אינטליגנציה גנומית ופלטפורמות נתונים clínico.",
    "cs2result": "תוצאה",
    "cs2resultText": "Healthcare Tech Outlook (2023). פרויקטים: Human Digital Model ו-BioMath Life.",
    "cs3eyebrow": "Robotics & UAV · 2026 — Present",
    "cs3title": "AGRON Inc.",
    "cs3challenge": "Challenge",
    "cs3challengeText": "Organizations building UAV and Counter-UAS capability need independent assessment, structured training, and operational architecture — not isolated platforms or ad-hoc piloting.",
    "cs3action": "Approach",
    "cs3actionText": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — consulting, assessment and validation, capability development, training infrastructure, product development support, geospatial systems through ISDRI, and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "cs3result": "Outcome",
    "cs3resultText": "A connected professional services ecosystem spanning five service domains and multiple companies — Global Drone Academy, AGRON, ISDRI, and GUARD — with programmes delivered across 10+ countries and 10,000+ UAV operators, instructors, and specialists trained.",
    "caseStudiesLead": "הקמה, הרחבה והובלת חברות משלב מוקדם ועד רכישה."
  },
  "mediaKit": {
    "eyebrow": "עיתונות ואירועים",
    "title": "ערכת מדיה",
    "lead": "ביוגרפיות רשמיות, חומרי תמונה ופרטי קשר עבור עיתונות, כנסים ופניות דירקטוריון.",
    "bioEyebrow": "ביוגרפיות",
    "bioTitle": "ביוגרפיות רשמיות",
    "bioShortLabel": "50 מילים",
    "bioShort": "Michael Kofman הוא CEO של Digital Invest Inc., חבר דירקטוריון, יועץ ומייסד חברות בתחומי הטכנולוגיה והבריאות הדיגיטלית בארה״ב ובאירופה.",
    "bioMediumLabel": "150 מילים",
    "bioMedium": "Michael Kofman הוא CEO של Digital Invest Inc. ומשמש כחבר ב-Board of Directors שלה. כאיש חזון טכנולוגי, הוא מוכר בגישתו הדינמית להבנת הצרכים המשתנים של שוק מורכב. כיזם, חבר דירקטוריון ויועץ לחברות ציבוריות ופרטיות, הוא הקים בהצלחה מספר חברות בארצות הברית ובאירופה. תחומי המומחיות שלו כוללים הנהלה בכירה, ניתוח אסטרטגי של טכנולוגיות ושווקים מתפתחים, אבטחת מידע ופרטיות, מחקר, מדע ופיתוח, ניהול והשקעות.",
    "bioLongLabel": "500 מילים",
    "bioLong": "Michael Kofman is CEO of Digital Invest Inc. and serves on its board. He founded 9 Net Avenue Inc., acquired by Concentric Networks in 2000, and leads Digital Invest in bio-mathematical medicine and genomic intelligence. He founded AGRON Inc. in 2026 for autonomous aerial-ground operations and geospatial systems. Author of technical papers on satellite and optical systems; patent in digital satellite HDTV acquired by Sony. Education: Doctor of Technical Sciences, Ph.D. in Information Technology.",
    "photosEyebrow": "צילום",
    "photosTitle": "תמונות מאושרות",
    "photosLead": "דיוקנאות באיכות גבוהה זמינים לפי בקשה בכתובת mkofman@mkofman.com.",
    "contactEyebrow": "קשרי עיתונות",
    "contactTitle": "פניות מדיה",
    "contactLead": "לראיונות, הזמנות להרצאות ופניות תקשורת.",
    "downloadEyebrow": "Download",
    "downloadTitle": "One-Page Media Kit",
    "downloadLead": "PDF with official bios, portrait, and press contact — ready to share with organizers and journalists.",
    "downloadCta": "Download PDF",
    "brandEyebrow": "Brand Assets",
    "brandTitle": "Identity & Usage",
    "brandLead": "Approved visual assets for editorial, conference, and partner use. Please preserve proportions, spacing, and original colors.",
    "brandColors": "Official Color Palette",
    "brandLogo": "Primary Logo",
    "brandDownload": "Download Brand Assets"
  },
  "articles": {
    "backLink": "← חזרה ל-Insights",
    "article1date": "נקודת מבט ניהולית",
    "article1title": "מהנדסה לתשתיות נתונים גלובליות",
    "article1p1": "הקריירה שלי החלה במפעל לבניית ספינות בניקולאייב שבאוקראינה, בפיתוח מערכות משדר-מקלט לווייניות להעברת מידע מסווג לספינות צבאיות. הוכרתי כמהנדס אלקטרוניקה ברמה הגבוהה ביותר - קטגוריה 6 - במפעל של 93,000 עובדים.",
    "article1p2": "בין 1989 ל-1994 ייסדתי והובלתי את Astra Corp, אחת היצרניות הגדולות באירופה של מערכות לוויין דיגיטליות מסוג משדר-מקלט. בין 1994 ל-1996, כ-CEO של Elitan United Inc., סייעתי להרחבת החברה מתשעה עובדים ליותר מ-4,000 עובדים ברחבי העולם.",
    "article1p3": "In 1996, I founded 9 Net Avenue Inc., a hosting and internet infrastructure company. In 2000 it was acquired by Concentric Networks (NASDAQ: CNTX) and subsequently became part of XO Communications (NASDAQ: XOXO).",
    "article1p4": "בין 2001 ל-2019 הובלתי אסטרטגיית טכנולוגיה לתוכניות ממשלתיות, ביטחוניות ולחברות בבעלות מדינה, תוך הובלת יוזמות רחבות היקף בתחומי Big Data, תשתיות מאובטחות ומרכזי נתונים בתפוקה גבוהה בארצות הברית ובאירופה.",
    "article2date": "בריאות דיגיטלית",
    "article2title": "רפואה מדויקת והמפגש בין מדע לטכנולוגיה",
    "article2p1": "אני מאמין עמוקות בפוטנציאל של שילוב מדעי החיים עם החידושים הטכנולוגיים המתקדמים ביותר. ב-Biotechnology Group Inc. ‏(2008-2014) התמקדנו בבדיקות וניתוחי DNA, אוטומציה של תהליכי יצירת פרופילים גנטיים, ומחקר גנטי מקיף של האדם.",
    "article2p2": "תחת הנהגתי, הושקו פרויקטים מוצלחים של בדיקות גנטיות באוקראינה, רוסיה ומדינות הבלטיות. בשיתוף עם Harvard Medical School ו-Stanford Biomath מילאתי תפקיד מרכזי בפיתוח דוחות גנטיים מובנים לרופאים ולמטופלים.",
    "article2p3": "עם Digital Invest Inc., שהוקמה ב-2021, עובדים ברפואה ביו-מתמטית — מדע, טכנולוגיות DNA, AI ו-ML באינטליגנציה clínico. Healthcare Tech Outlook (2023).",
    "article2p4": "Digital Invest מקדמת רפואה ביו-מתמטית באמצעות פרויקטים כמו Human Digital Model ו-BioMath Life. ב-2026 ייסד Michael Kofman את AGRON Inc. כדי להוביל את Aerial-Ground Robotics Operations Network — יכולות כטב\"מ, מערכות גיאו-מרחביות ומודיעין ימי ב-agron1.com."
  },
  "privacy": {
    "eyebrow": "משפטי",
    "title": "מדיניות פרטיות",
    "lead": "כיצד mkofman.com מטפל במידע בעת ביקור באתר או שליחת הודעה.",
    "updated": "עודכן: יולי 2026",
    "s1title": "מידע שאנו אוספים",
    "s1text": "בשליחת טופס אנו מקבלים את השדות שמילאת. אם אנליטיקה מופעלת — נתוני שימוש אנונימיים.",
    "s2title": "שימוש במידע",
    "s2text": "למענה לפניות ושיפור האתר. איננו מוכרים מידע אישי.",
    "s3title": "שירותי צד שלישי",
    "s3text": "טפסים עשויים להיות מעובדים ב-Formspree. אנליטיקה — Plausible או Google Analytics.",
    "s4title": "זכויותיך",
    "s4text": "בקשת גישה, תיקון או מחיקה: mkofman@mkofman.com.",
    "s5title": "יצירת קשר",
    "s5text": "שאלות על מדיניות זו: mkofman@mkofman.com"
  },
  "board": {
    "eyebrow": "Advisory",
    "title": "Advisory",
    "body": "Open to strategic advisory conversations with technology, healthcare, and infrastructure organizations — drawing on direct operating experience across company building, technology strategy, and growth-stage execution.",
    "contactLink": "For advisory inquiries"
  },
  "thesis": {
    "eyebrow": "Leadership Thesis",
    "title": "Build for the Long Term. Decide in the Present.",
    "lead": "Technology changes quickly; the obligations of leadership do not. Durable enterprises unite ambition with discipline, evidence, and accountability.",
    "believeEyebrow": "What I Believe",
    "believeTitle": "Seven Principles for Enduring Organizations",
    "b1title": "Strategy Must Produce Choices",
    "b1text": "A strategy is not a catalog of aspirations. It defines where to compete, what capabilities to build, what not to pursue, and how success will be measured.",
    "b2title": "Technology Is a Governance Issue",
    "b2text": "Boards must understand how technology creates value, concentrates risk, and changes accountability. Delegating every technical question is itself a decision.",
    "b3title": "Evidence Should Outrank Enthusiasm",
    "b3text": "Conviction matters, but markets, systems, and science must be tested. Leaders create mechanisms that expose assumptions before customers or regulators do.",
    "b4title": "Architecture Shapes the Enterprise",
    "b4text": "Technical architecture determines speed, resilience, security, and future options. Shortcuts become institutional constraints long after their original context disappears.",
    "b5title": "Trust Is Operating Infrastructure",
    "b5text": "Trust is built through clear commitments, reliable execution, responsible data practices, and direct communication when conditions change.",
    "b6title": "Capital Must Follow Capability",
    "b6text": "Growth investment should reinforce differentiated capabilities and measurable demand, not substitute spending for product-market understanding.",
    "b7title": "Leaders Design Their Successors",
    "b7text": "The strongest leaders build systems, talent, and decision quality that endure beyond their own involvement.",
    "rejectEyebrow": "What I Reject",
    "rejectTitle": "Three Expensive Illusions",
    "r1title": "Innovation Theater",
    "r1text": "Announcements, pilots, and fashionable language do not equal capability. Innovation must improve an outcome that matters.",
    "r2title": "Growth Without Governance",
    "r2text": "Scale magnifies unresolved weaknesses. Controls, culture, and accountability should mature before complexity makes correction costly.",
    "r3title": "False Certainty",
    "r3text": "Executive confidence should not erase uncertainty. Strong decisions make assumptions visible and preserve options when facts change.",
    "horizonEyebrow": "The Horizon",
    "horizonTitle": "The Next Advantage Is Responsible Integration",
    "horizonText": "The defining opportunity is not any single technology. It is the disciplined integration of AI, advanced data systems, biology, and automation into institutions people can trust."
  },
  "press": {
    "eyebrow": "Press & Media",
    "title": "Selected Coverage",
    "lead": "A concise archive of third-party recognition and reporting across technology, entrepreneurship, and precision medicine.",
    "archiveEyebrow": "Archive",
    "y2023type": "Industry Recognition",
    "y2023title": "Top 10 Precision Medicine Companies",
    "y2023desc": "Healthcare Tech Outlook recognized Digital Invest Inc. among leading U.S. companies advancing precision medicine and digital health.",
    "y2023link": "View feature",
    "y2001type": "Executive Award",
    "y2001title": "Entrepreneur of the Year",
    "y2001desc": "Entrepreneur Magazine recognition.",
    "y2001link": "View archive",
    "y1999type": "Biographical Recognition",
    "y1999title": "Who's Who in America",
    "y1999desc": "Recognition beginning in 1999, followed by listings in Who's Who in the World and Who's Who in Science and Engineering.",
    "clipEyebrow": "From the Archive",
    "clipMeta": "Industry Feature · DataPeer Inc.",
    "clipTitle": "State of the Storage Industry",
    "clipLead": "An early interview with Michael Kofman as Founder, Chairman, and CEO of DataPeer Inc. — reflecting on fiber optics, satellite transmission, SAN, and the emerging storage market.",
    "clipBody": "The feature notes recognition as Entrepreneur of the Year by Entrepreneur Magazine (2001) and discusses DataPeer’s approach to mission-critical storage, iSCSI, and business continuity.",
    "clipOpen": "Open full page scan →",
    "y2000type": "Interview",
    "y2000title": "State of the Storage Industry",
    "y2000desc": "Featured interview as Founder, Chairman, and CEO of DataPeer Inc. on storage networks, iSCSI, and business continuity."
  },
  "ip": {
    "eyebrow": "Intellectual Property",
    "title": "Applied Ideas, Documented",
    "lead": "Selected patents, publications, and research programs connecting engineering rigor with practical business and societal outcomes.",
    "patentEyebrow": "Patents",
    "patentTitle": "Protected Inventions",
    "patentIntro": "Patent work reflects a sustained focus on systems that improve the collection, movement, protection, and interpretation of information.",
    "publicationsEyebrow": "Publications",
    "publicationsTitle": "Technical & Executive Writing",
    "publicationsIntro": "Published work translates complex technical subjects into methods, frameworks, and decisions useful to practitioners and leaders.",
    "researchEyebrow": "Research",
    "researchTitle": "Interdisciplinary Programs",
    "researchIntro": "Research initiatives span secure communications, predictive analytics, genetic interpretation, human digital modeling, and autonomous systems."
  },
  "testimonials": {
    "t1quote": "Michael combines an engineer's precision with the judgment of an experienced chief executive. He asks the questions that improve the decision.",
    "t1name": "Board Colleague",
    "t1role": "Public Technology Company",
    "t2quote": "His ability to connect science, product, governance, and commercial reality brings uncommon clarity to complex initiatives.",
    "t2name": "Strategic Partner",
    "t2role": "Digital Health Sector",
    "t3quote": "Michael is direct, thoughtful, and focused on durable value. He helps leadership teams see both the opportunity and the obligation.",
    "t3name": "Executive Collaborator",
    "t3role": "Global Infrastructure"
  },
  "deck": {
    "title": "Michael Kofman",
    "subtitle": "מנהיג טכנולוגי · מייסד · יועץ",
    "thesis": "טכנולוגיה, עסקים והשקעות בתשתיות, מדעי החיים ומערכות אוטונומיות.",
    "contact": "Confidential discussion: contact Michael Kofman through mkofman.com"
  },
  "briefIpo": {
    "title": "What an IPO Changes",
    "desc": "Public markets do not merely change a company's capital structure; they change its operating contract.",
    "p1": "An initial public offering is often described as a financing event. In practice, it is an institutional transition. Forecasting, controls, disclosure, governance, and executive communication must become repeatable before the listing, not improvised afterward.",
    "p2": "Readiness begins with decision quality. Management needs reliable metrics, clear ownership, and an operating cadence that can explain both performance and variance. A company that cannot reconcile its internal narrative will struggle to communicate a credible external one.",
    "p3": "The board's role also changes. Directors must balance growth with oversight, understand material technology and market risks, and ensure that incentives support durable value rather than a single quarter.",
    "p4": "The strongest public companies preserve entrepreneurial speed while adding institutional discipline. The objective is not bureaucracy; it is trustworthy execution at a higher level of accountability.",
    "eyebrow": "תקציר מנהלים"
  },
  "briefGenetic": {
    "title": "From Genetic Data to Clinical Decisions",
    "desc": "The value of genomic information depends on interpretation, evidence, and responsible integration into care.",
    "p1": "Genetic data is abundant; clinically useful meaning is scarce. A result becomes valuable only when it is interpreted in context, connected to validated evidence, and presented in a form that supports a real decision.",
    "p2": "That translation requires collaboration across molecular biology, medicine, statistics, software engineering, and patient communication. Weakness in any layer can turn technical sophistication into clinical confusion.",
    "p3": "Privacy and consent are architectural requirements, not legal footnotes. Systems must limit unnecessary exposure, make data provenance visible, and preserve patient agency as information moves between laboratories, platforms, and care teams.",
    "p4": "Precision medicine will advance through measured integration: better evidence, transparent models, interoperable workflows, and outcomes that clinicians and patients can evaluate. Trust is part of the product.",
    "eyebrow": "תקציר מנהלים"
  },
  "briefAi": {
    "title": "AI Strategy Beyond the Pilot",
    "desc": "Enterprise AI creates value when ownership, data, workflow, and governance mature together.",
    "p1": "Many AI initiatives begin with a compelling demonstration and stall before production. The missing element is rarely the model alone. Sustainable value requires a defined business outcome, accountable owner, dependable data, and a workflow people will actually use.",
    "p2": "Leaders should distinguish automation, prediction, and decision support. Each carries different requirements for accuracy, explainability, human review, and risk. A single governance template will not fit every use case.",
    "p3": "Measurement must include more than technical performance. Adoption, cycle time, error rates, customer impact, security exposure, and the cost of supervision determine whether an AI capability is economically and institutionally sound.",
    "p4": "The winning approach is a managed portfolio: scale proven use cases, stop weak ones early, and maintain explicit boundaries for high-consequence decisions. AI strategy is ultimately operating strategy.",
    "eyebrow": "תקציר מנהלים"
  }
};
