window.__LANG_he = {
  "ui": {
    "toggleTheme": "החלפת ערכת בהיר/כהה",
    "selectLanguage": "בחר שפה",
    "messageSent": "ההודעה נשלחה",
    "sendMessage": "שלח",
    "toggleNav": "פתח תפריט",
    "sending": "שולח…",
    "formError": "לא ניתן היה לשלוח. נא לשלוח אימייל ישירות.",
    "present": "עד היום"
  },
  "nav": {
    "home": "בית",
    "about": "אודות",
    "ventures": "חברות",
    "career": "קריירה",
    "recognition": "הכרה",
    "contact": "צור קשר",
    "consulting": "ייעוץ",
    "insights": "תובנות",
    "speaking": "הרצאות",
    "caseStudies": "מקרי בוחן",
    "mediaKit": "ערכת מדיה",
    "groupMain": "ראשי",
    "groupServices": "שירותים",
    "groupWork": "עבודה"
  },
  "footer": {
    "navigation": "ניווט",
    "ventures": "חברות",
    "connect": "קשר",
    "desc": "מנכ\"ל, טכנולוג אסטרטגי ויזם עטור פרסים.",
    "copyright": "© 2025–2026 Michael Kofman. כל הזכויות שמורות.",
    "writeTitle": "כתבו לי",
    "writeEmail": "האימייל שלך",
    "writeMessage": "ההודעה שלך",
    "writeSend": "שלח",
    "writeSuccess": "תודה — ההודעה נשלחה.",
    "more": "עוד"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — מנכ\"ל",
      "description": "האתר הרשמי של מייקל קופמן — מנכ\"ל זוכה פרסים, מייסד וטכנולוג אסטרטגי."
    },
    "about": {
      "title": "אודות — Michael Kofman",
      "description": "ביוגרפיה של מייקל קופמן — מנכ\"ל Digital Invest Inc. — חזון טכנולוגי ויזם זוכה פרסים."
    },
    "ventures": {
      "title": "חברות — Michael Kofman",
      "description": "חברות שייסד וניהל מייקל קופמן — מ-Digital Invest Inc. ועד 9 Net Avenue Inc. — בניית עסקים משני מציאות בטכנולוגיה ובריאות."
    },
    "career": {
      "title": "קריירה — Michael Kofman",
      "description": "מסלול הקריירה של מייקל קופמן — מהנדסות לוויינים ועד מנכ\"ל חברות טכנולוגיה ובריאות גלובליות."
    },
    "recognition": {
      "title": "הכרה — Michael Kofman",
      "description": "פרסים והוקרות למייקל קופמן — יזם השנה, Who's Who, פטנטים והוקרות תעשייתיות."
    },
    "contact": {
      "title": "צור קשר — Michael Kofman",
      "description": "יצירת קשר עם מייקל קופמן — מנכ\"ל Digital Invest Inc. לייעוץ, הרצאות ופניות עסקיות."
    },
    "consulting": {
      "title": "ייעוץ — Michael Kofman",
      "description": "תפקידי ייעוץ, חברות בדירקטוריון, הרצאות ושותפויות אסטרטגיות עם Michael Kofman."
    },
    "insights": {
      "title": "תובנות — Michael Kofman",
      "description": "פרסומים, כתבות, פטנטים והכרה בתעשייה של Michael Kofman."
    },
    "speaking": {
      "title": "הרצאות — Michael Kofman",
      "description": "הזמינו את Michael Kofman להרצות על מנהיגות ניהולית, אסטרטגיית טכנולוגיה, בריאות דיגיטלית וממשל תאגידי."
    },
    "caseStudies": {
      "title": "מקרי בוחן — Michael Kofman",
      "description": "מקרי בוחן מהקריירה של Michael Kofman: 9 Net Avenue Inc. ו-Digital Invest Inc."
    },
    "mediaKit": {
      "title": "ערכת מדיה — Michael Kofman",
      "description": "ביוגרפיות רשמיות, תמונות ופרטי קשר עבור עיתונות ומפיקי אירועים."
    },
    "article1": {
      "title": "מהנדסה לתשתית גלובלית — Michael Kofman",
      "description": "Michael Kofman על מסלול הקריירה מהנדסת לוויינים ועד הקמת חברות גלובליות לתשתיות נתונים."
    },
    "article2": {
      "title": "רפואה מדויקת וטכנולוגיה — Michael Kofman",
      "description": "Michael Kofman על שילוב מדעי החיים עם AI, ML וטכנולוגיות DNA ברפואה המודרנית."
    }
  },
  "home": {
    "heroEyebrow": "האתר הרשמי של Michael Kofman",
    "heroTitle1": "מנהיגות חזונית.",
    "heroTitle2": "חדשנות אסטרטגית.",
    "heroCta": "גלו את הסיפור שלי",
    "heroAlt": "Michael Kofman — CEO and Strategic Technologist",
    "quote1text": "A technology visionary recognized for his dynamic approach to understanding the ever-changing demands of today's complex marketplace.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "Entrepreneur of the Year — recognized for leadership and breakthrough achievements in platform innovation and infrastructure.",
    "quote2author": "Entrepreneur Magazine, 1999 — 2001",
    "quote3text": "Digital Invest Inc. named among America's Top 10 Best Companies in Precision Medicine and Digital Health.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "Known for uniting engineering precision with business strategy, delivering high-value outcomes, and building future-oriented companies from scratch.",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "הכירו את Michael Kofman",
    "aboutTitle": "מורשת של חדשנות ומנהיגות",
    "aboutLead1": "Michael Kofman is a technological visionary renowned for his dynamic approach to understanding the ever-evolving needs of today's complex market. An entrepreneur, board member, and advisor for both public and private companies, he has successfully established several companies in the United States and Europe.",
    "aboutLead2": "מייסוד אחת מחברות ה-Data Storage הגדולות בעולם — שנרכשה בשווי שוק שיא של 19.5 מיליארד דולר — ועד הובלת Digital Invest Inc. בתחום אחסון הנתונים וחדשנות טכנולוגית מתקדמת. Digital Invest כוללת מגוון פרויקטים חדשניים, ביניהם Human Digital Model, BioMath Life ו-Aero-Ground Robotics Operations Network.",
    "aboutLink": "ביוגרפיה מלאה",
    "expertiseEyebrow": "מומחיות רב-תחומית",
    "expertiseTitle": "מנהיגות בכירה בין תעשיות",
    "expertiseLead": "Explore Michael Kofman's diverse expertise as a CEO, technologist, advisor, and investor. With decades of experience, he provides unparalleled insight and guidance to drive success.",
    "exp1title": "מנכ\"ל ומייסד",
    "exp1desc": "ייסד והרחיב מספר חברות מהקמתן ועד הנפקה מוצלחת, תוך צמיחה פיננסית עקבית ונוכחות גלובלית בתחומי הטכנולוגיה והבריאות.",
    "exp1link": "חברות ←",
    "exp2title": "ארכיטקט טכנולוגי",
    "exp2desc": "תכנן תקשורת מאובטחת, מנועי אנליטיקה חיזויית ופלטפורמות אינטגרציית נתונים ברמה לאומית למגזרים ממשלתיים, צבאיים וטלקום.",
    "exp2link": "קריירה ←",
    "exp3title": "בריאות דיגיטלית",
    "exp3desc": "מוביל את שינוי הרפואה באמצעות בינה מלאכותית, למידת מכונה וטכנולוגיות DNA. שיתף פעולה עם Harvard Medical School ו-Stanford Biomath בדיווח גנטי.",
    "exp3link": "Digital Invest ←",
    "exp4title": "יועץ דירקטוריון",
    "exp4desc": "חבר בדירקטוריונים ומייעץ לחברות ציבוריות ופרטיות בנושאי כיוון אסטרטגי, ממשל תאגידי ויוזמות צמיחה מונחות טכנולוגיה.",
    "exp4link": "ייעוץ →",
    "stat1": "שנות מנהיגות",
    "stat2": "חברות שנוסדו",
    "stat3": "שווי שוק שיא",
    "stat4": "עובדים",
    "recEyebrow": "הכרה",
    "recTitle": "פרסים ואותות כבוד",
    "recLead": "Consistently recognized for exceptional achievements in business creation, innovation, and executive leadership.",
    "award1title": "יזם השנה",
    "award1desc": "Entrepreneur Magazine, 1999 — 2001",
    "award2title": "10 מובילים ברפואת דיוק",
    "award2desc": "Digital Invest Inc. — U.S., 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "כל ההכרות",
    "heroSub": "CEO, יועץ לדירקטוריונים וטכנולוג אסטרטגי עבור חברות ציבוריות ופרטיות בתחומי הטכנולוגיה, אחסון הנתונים והבריאות הדיגיטלית.",
    "primaryCta": "בקשת ייעוץ",
    "secondaryCta": "צפייה במקרי בוחן",
    "featuredEyebrow": "פורסם ב-",
    "caseStudiesEyebrow": "תוצאות מוכחות",
    "caseStudiesTitle": "מקרי בוחן",
    "caseStudiesLead": "הקמה, הרחבה והובלת חברות מהשלב הראשוני ועד רכישה ו-IPO.",
    "caseStudiesLink": "צפייה בכל מקרי הבוחן →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "נבנתה כאחת מחברות ה-Data Storage הגדולות בעולם ונרכשה בשווי שוק שיא של 19.5 מיליארד דולר.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "הוקמה והורחבה מההתחלה ועד IPO מוצלח - בין 10 החברות המובילות בארה״ב ברפואה מדויקת, 2023."
  },
  "about": {
    "eyebrow": "אודות Michael Kofman",
    "title": "מורשת של חדשנות",
    "lead": "חזון טכנולוגי ומנהיג בכיר עם קריירה של más de שלושה décades.",
    "glance": "בקצרה",
    "role": "תפקיד נוכחי",
    "roleVal": "CEO & Board Member · Digital Invest Inc.",
    "location": "מיקום",
    "locationVal": "Charlotte, North Carolina",
    "education": "השכלה",
    "educationVal": "Doctor of Technical Sciences (2009)\nPh.D. in Information Technology (2004)\nMaster's in Electronic Engineering",
    "university": "אוניברסיטה",
    "universityVal": "Ukrainian State Marine Technical University",
    "languages": "שפות",
    "languagesVal": "English, Russian, Ukrainian",
    "contactLabel": "קשר",
    "bioP1": "Michael Kofman הוא המנכ\"ל של Digital Invest Inc. וחבר בדירקטוריון. כחזון טכנולוגי, הוא ידוע בגישה הדינמית שלו להבנת הצרכים המתפתחים ללא הרף של השוק המורכב של ימינו. מומחיותו כוללת מנהיגות מנהלית, ניתוח אסטרטגי של טכנולוגיות ושווקים מתפתחים, אבטחת מידע ופרטיות, מחקר, מדע ופיתוח, ניהול והשקעות.",
    "bioP2": "כיזם, חבר דירקטוריון ויועץ לחברות ציבוריות ופרטיות, Michael Kofman הקים בהצלחה מספר חברות בארצות הברית ובאירופה. לאחרונה יצא למיזם שאפתני עם הקמת Digital Invest, חברה המוקדשת לתחום הביו-מתמטי, שמטרתה לשנות גישות מיושנות ברפואה באמצעות ההתקדמות העדכנית ביותר במדע, טכנולוגיות DNA, AI ו-ML.",
    "secBioTitle": "רפואה מדויקת וביוטכנולוגיה",
    "secBioP1": "טרם Digital Invest, הוא מילא תפקיד מרכזי בהצלחה של Biotechnology Group Inc. (2008 — 2014), חברה המחויבת לבדיקות וניתוח DNA, אוטומציה של תהליכי יצירת פרופילים גנטיים ומחקר גנטי אנושי מקיף. מר Kofman מאמין בתוקף בפוטנציאל של שילוב מדעי החיים עם ההתקדמות הטכנולוגית העדכנית ביותר.",
    "secBioP2": "תחת הנהגתו, יוזמו פרויקטים מוצלחים של בדיקות גנטיות באוקראינה, ברוסיה ובמדינות Baltic. ניסיון ייחודי זה מועשר ללא הרף בטכנולוגיות מודרניות ובציוד חדש. בשיתוף עם Harvard Medical School ו-Stanford Biomath, מר Kofman מילא תפקיד מכריע בפיתוח דוחות גנטיים מובנים לרופאים ולמטופלים כאחד. גישה חדשנית זו אומצה על ידי מעבדות מובילות בארצות הברית ובחו\"ל.",
    "secTechTitle": "טכנולוגיה ותשתיות",
    "secTechP1": "מ-2001 עד 2019, מר Kofman הוביל את האסטרטגיה הטכנולוגית לתוכניות ממשלתיות, ביטחוניות וארגונים בבעלות המדינה — כולל יוזמות טכניות מורכבות לחברות בבעלות הממשלה. בעקבות 11 בספטמבר 2001, הוא הוביל פרויקטים ממשלתיים בקנה מידה גדול המתמקדים ב-big data, תשתיות מאובטחות ומרכזי נתונים בעלי תפוקה גבוהה בארצות הברית ובאירופה.",
    "secTechP2": "ב-2006, מר Kofman הקים את XIBI Group Inc. — חברת טכנולוגיה שבה כיהן בדירקטוריון. החברה האמריקאית מתמחה באחסון נתונים ובשירותי ניהול big data לארגונים מסחריים וממשלתיים גדולים.",
    "secTechP3": "מ-2000 עד 2004, מר Kofman הוביל את DataPeer Inc. — חברת ניהול ואחסון נתונים המציעה מגוון רחב של שירותים הקשורים לאחסון מידע לעסקים קטנים ובינוניים. ב-DataPeer פיתח פתרונות טכנולוגיים ייחודיים שסייעו למעקב מהיר יותר אחר מידע ולנגישות קלה יותר לנתונים עבור משתמשי קצה ומוסדות ממשלתיים ברחבי העולם.",
    "secTechP4": "ב-1996, מר Kofman הקים את 9 Net Avenue Inc. היא הפכה במהירות לאחת מחברות האחסון הגדולות בעולם. עד 2000, 9 Net Avenue נרכשה על ידי Concentric Networks (NASDAQ: CNTX), ולאחר מכן על ידי XO Communications (NASDAQ: XOXO), והגיעה לשווי שוק שיא של 19.5 מיליארד דולר.",
    "secPost9NetP1": "לאחר רכישת 9 Net Avenue, מר Kofman צבר ניסיון רב בעבודה בחברות ציבוריות, השתתפות בדירקטוריונים וקבלת החלטות אסטרטגיות ברמה הנהלתית העליונה.",
    "secEarlyTitle": "קריירה מוקדמת והנדסה",
    "secEarlyP1": "מ-1994 עד 1996, מר Kofman כיהן כמנכ\"ל וכמנהל טכנולוגיות מידע ב-Elitan United Inc. — חברת IT מ-Massachusetts, שסיפקה אסטרטגיות מקיפות ושירותים טכנולוגיים לארגונים גלובליים מובילים. הוא מילא תפקיד מכריע בפיתוח וניהול תשתית ניתנת להרחבה, והוביל את צמיחת החברה מ-9 עובדים בלבד ליותר מ-4,000 עובדים ברחבי העולם.",
    "secEarlyP2": "מ-1989 עד 1994, הוא היה מייסד ומנכ\"ל Astra Corp, אחת היצרניות הגדולות באירופה של מערכות לוויין דיגיטליות לשידור וקליטה, שזכתה להכרה בינלאומית בתחום מכשירי הלוויין. תחומי אחריותו כללו מחקר, פיתוח מערכות הפעלה, יישומי תוכנת רשת ואסטרטגיה טכנית כוללת.",
    "secEarlyP3": "מ-1984 עד 1989, מר Kofman עבד במספנת האוניות ב-Nikolaev, אוקראינה, שם השתתף באופן פעיל בפיתוח וביצירת מערכות לוויין לשידור וקליטה להעברת מידע סודי לספינות צבאיים ובחזרה. הוא הוכר כמהנדס אלקטרוניקה ברמה הגבוהה ביותר, וקיבל את דרגה 6 — ההכרה הגבוהה ביותר במספנה, שבו עבדו 93 אלף אנשים.",
    "secResearchTitle": "מחקר ופטנטים",
    "secResearchP1": "Michael Kofman הוא מחבר מאמרים טכניים המתמקדים במערכות לוויין ואופטיות להעברת נתונים. הוא גם קיבל פטנט בתחום מערכות טלוויזיה בגובה רזולוציה (HDTV) לווייניות דיגיטליות, שנרכש לאחר מכן על ידי Sony."
  },
  "ventures": {
    "eyebrow": "תיק חברות",
    "title": "חברות שמשנות תעשיות",
    "lead": "מרפואת דיוק ועד תקשורת גלובלית.",
    "v1year": "2021 — עד היום",
    "v1role": "מייסד ומנכ\"ל · חבר דירקטוריון",
    "v1p1": "הקים והרחיב את Digital Invest מההקמה ועד IPO מוצלח. החברה מוקדשת לתחום הביו-מתמטי, ומשנה את הרפואה באמצעות AI, ML וטכנולוגיות DNA.",
    "v1highlight": "10 החברות המובילות בארה\"ב ברפואה מדויקת — 2023",
    "v2year": "2008 — 2014",
    "v2role": "מנכ\"ל ו-CTO",
    "v2p1": "בדיקות וניתוח DNA, אוטומציה של פרופילים גנטיים ומחקר גנטי אנושי מקיף. יזם פרויקטי בדיקות גנטיות באוקראינה, ברוסיה ובמדינות Baltic.",
    "v2p2": "שיתף פעולה עם Harvard Medical School ו-Stanford Biomath בדוחות גנטיים שאומצו על ידי מעבדות מובילות ברחבי העולם.",
    "v2highlight": "שותף Harvard Medical School ו-Stanford Biomath",
    "v3year": "2006 — 2011",
    "v3role": "מייסד ומנכ\"ל · דירקטוריון",
    "v3p1": "אחסון נתונים ושירותי ניהול big data לארגונים מסחריים וממשלתיים גדולים. ביסס את החברה כספק מהימן של פתרונות נתונים ארגוניים.",
    "v3highlight": "פתרונות נתונים ארגוניים וממשלתיים",
    "v4year": "2000 — 2004",
    "v4role": "מייסד ומנכ\"ל",
    "v4p1": "ניהול ואחסון נתונים לעסקים קטנים ובינוניים. פיתח פתרונות למעקב מהיר יותר אחר מידע ולנגישות קלה יותר לנתונים עבור משתמשי קצה ומוסדות ממשלתיים ברחבי העולם.",
    "v4highlight": "פלטפורמה גלובלית לניהול נתונים",
    "v5year": "1996 — 2000",
    "v5role": "מייסד ומנכ\"ל",
    "v5p1": "בנה אחת מחברות האחסון הגדולות בעולם. עד 2000, נרכשה על ידי Concentric Networks (NASDAQ: CNTX), ולאחר מכן על ידי XO Communications (NASDAQ: XOXO), והגיעה לשווי שוק שיא של 19.5 מיליארד דולר.",
    "v5highlight": "נרכשה · שווי שיא של 19.5 מיליארד דולר",
    "v6year": "1994 — 1996",
    "v6role": "מנכ\"ל ומנהל טכנולוגיות מידע",
    "v6p1": "חברת IT מ-Massachusetts המספקת אסטרטגיות מקיפות ושירותים טכנולוגיים לארגונים גלובליים מובילים. הוביל פיתוח תשתית ניתנת להרחבה ותפעול IT גלובלי.",
    "v6highlight": "אסטרטגיית IT ותשתיות גלובליות",
    "v7year": "1989 — 1994",
    "v7role": "מייסד ומנכ\"ל",
    "v7p1": "אחת היצרניות הגדולות באירופה של מערכות לוויין דיגיטליות לשידור וקליטה. הוביל מחקר, פיתוח מערכות הפעלה, יישומי תוכנת רשת ואסטרטגיה טכנית כוללת.",
    "v7highlight": "מובילה אירופית במערכות לוויין",
    "v8year": "1984 — 1989",
    "v8role": "מהנדס אלקטרוניקה · דרגה עליונה (6)",
    "v8p1": "פיתוח ויצירת מערכות לוויין לשידור וקליטה להעברת מידע סודי לספינות צבאיים. הוכר כמהנדס אלקטרוניקה ברמה הגבוהה ביותר במספנה של 93,000 עובדים.",
    "v8highlight": "הנדסת מערכות לוויין צבאיות"
  },
  "career": {
    "eyebrow": "מסלול מקצועי",
    "title": "שלושה décades של מנהיגות",
    "lead": "מהנדס לוויינים ועד חברות טכנולוגיה גלובליות.",
    "timelineEyebrow": "ציר זמן",
    "timelineTitle": "אבני דרך",
    "strengthsEyebrow": "חוזקות",
    "strengthsTitle": "תחומי מומחיות",
    "t1year": "2021 — עד היום",
    "t1title": "Digital Invest Inc.",
    "t1role": "מייסד ומנכ\"ל",
    "t1desc": "הקים והרחיב את החברה מההקמה ועד IPO מוצלח. הוביל את תהליך ההנפקה הציבורית המלא — מבנה משפטי, ציות פיננסי, סיבובי משקיעים ותיאום עם SEC. הוביל את תכנון, בנייה ותפעול של מספר מרכזי נתונים בארה\"ב ובאירופה. בנה מערכות תוכנה ארגוניות לאוטומציה, ניטור חיזוי ושליטה מרכזית בנתונים. השיג צמיחה פיננסית עקבית, ומיקם את החברה בין 10 החברות המובילות ברפואה מדויקת בארה\"ב (2023).",
    "t2year": "2001 — 2019",
    "t2title": "GovTech, ביטחון ותוכניות מדינה",
    "t2role": "יועץ טכנולוגי ראשי / אדריכל תוכניות",
    "t2desc": "הוביל אסטרטגיה טכנולוגית ומסירה לתוכניות סודיות ורגישות הכוללות סוכנויות ממשלתיות אמריקאיות, מערכות ביטחון של בני ברית וארגונים בבעלות המדינה. עמד בראש פרויקטים טכניים מורכבים לחברות בבעלות הממשלה במגזרים שונים. בעקבות 11 בספטמבר 2001, הוביל יוזמות ממשלתיות בקנה מידה גדול המתמקדות ב-big data, תקשורת מאובטחת, אנליטיקה חיזויית ואינטגרציה של נתונים ברמה לאומית — כולל תכנון, בנייה ותפעול של מרכזי נתונים בעלי תפוקה גבוהה בארצות הברית ובאירופה. שיתף פעולה עם קציני תוכניות צבאיים, ספקי טכנולוגיה וגורמים רגולטוריים.",
    "t3year": "2008 — 2014",
    "t3title": "Biotechnology Group Inc.",
    "t3role": "מנכ\"ל ו-CTO",
    "t3desc": "הוביל בדיקות וניתוח DNA, אוטומציה של פרופילים גנטיים ומחקר גנטי אנושי מקיף. יזם פרויקטי בדיקות גנטיות באוקראינה, ברוסיה ובמדינות Baltic. שיתף פעולה עם Harvard Medical School ו-Stanford Biomath לפיתוח דוחות גנטיים מובנים שאומצו על ידי מעבדות מובילות ברחבי העולם.",
    "t4year": "2000 — 2012",
    "t4title": "פרויקטי תקשורת",
    "t4role": "VP טכנולוגיה / CTO אזורי — מזרח אירופה ו-CIS",
    "t4desc": "הוביל פריסות תשתית לאומיות בקנדה, איטליה, שווייץ, אוקראינה והרפובליקות Baltic. פיקח על יותר מ-1,000 מהנדסים וצוותי פריסה בפעילות תקשורת כולל מערכות מיתוג, הרחבת פס רחב וקישוריות חוצת גבולות. יישם מערכות ליבה לגיבוית רשת, אופטימיזציה של זמן פעילות וניתוב חכם.",
    "t5year": "2006 — 2011",
    "t5title": "XIBI Group Inc.",
    "t5role": "מייסד ומנכ\"ל · דירקטוריון",
    "t5desc": "הקים חברת טכנולוגיה המתמחה באחסון נתונים ובניהול big data לארגונים מסחריים וממשלתיים גדולים. ביסס את החברה כספק מהימן של פתרונות נתונים ארגוניים.",
    "t6year": "2000 — 2004",
    "t6title": "DataPeer Inc.",
    "t6role": "מייסד ומנכ\"ל",
    "t6desc": "הקים חברת ניהול ואחסון נתונים לעסקים קטנים ובינוניים. פיתח פתרונות טכנולוגיים ייחודיים למעקב מהיר יותר אחר מידע ולנגישות קלה יותר לנתונים עבור משתמשי קצה ומוסדות ממשלתיים ברחבי העולם.",
    "t7year": "1996 — 2000",
    "t7title": "9 Net Avenue Inc.",
    "t7role": "מייסד ומנכ\"ל",
    "t7desc": "בנה אחת מחברות האחסון הגדולות בעולם. עד 2000, נרכשה על ידי Concentric Networks (NASDAQ: CNTX), ולאחר מכן על ידי XO Communications (NASDAQ: XOXO), והגיעה לשווי שוק שיא של 19.5 מיליארד דולר.",
    "t8year": "1994 — 1996",
    "t8title": "Elitan United Inc.",
    "t8role": "מנכ\"ל ומנהל טכנולוגיות מידע",
    "t8desc": "הוביל אסטרטגיות IT מקיפות ושירותים טכנולוגיים לארגונים גלובליים מובילים מ-Massachusetts בתקופת התרחבות מהירה, ובנה תשתית ניתנת להרחבה ותפעול IT גלובלי.",
    "t9year": "1989 — 1994",
    "t9title": "Astra Corp",
    "t9role": "מייסד ומנכ\"ל",
    "t9desc": "הקים אחת היצרניות הגדולות באירופה של מערכות לוויין דיגיטליות לשידור וקליטה. הוביל מחקר, פיתוח מערכות הפעלה, יישומי תוכנת רשת ואסטרטגיה טכנית כוללת, וזכה להכרה בינלאומית.",
    "t10year": "1984 — 1989",
    "t10title": "Nikolaev Shipbuilding Plant",
    "t10role": "מהנדס אלקטרוניקה — דרגה 6 (הגבוהה ביותר)",
    "t10desc": "פיתח ויצר מערכות לוויין לשידור וקליטה להעברת מידע סודי לספינות צבאיים. הוכר כמהנדס אלקטרוניקה ברמה הגבוהה ביותר במספנה של 93,000 עובדים — תחילתה של קריירה מצטיינת בטכנולוגיה וחדשנות.",
    "s1title": "מנהיגות מנהלית",
    "s1desc": "ניהול דו-צדדי של מנכ\"ל/CTO בחברות ציבוריות ופרטיות, מסטארטאפ ועד IPO ומעבר לכך.",
    "s2title": "IPO והרחבה פיננסית",
    "s2desc": "ביצוע מלא של הנפקה ציבורית — מבנה משפטי, תיאום SEC, סיבובי משקיעים וציות.",
    "s3title": "ארכיטקטורת פלטפורמות",
    "s3desc": "תכנון מערכות ניתנות להרחבה לאוטומציה ארגונית, ניטור חיזוי ושליטה מרכזית בנתונים.",
    "s4title": "תשתית מאובטחת",
    "s4desc": "פיתוח ותפעול של מרכזי נתונים לפלטפורמות ממשלתיות, צבאיות ומסחריות בעלות אבטחה גבוהה."
  },
  "recognition": {
    "eyebrow": "פרסים",
    "title": "הכרה במצוינות",
    "lead": "עשורים של הישגים יוצאי דופן.",
    "industryEyebrow": "פרסי התעשייה",
    "industryTitle": "אותות כבוד מרכזיים",
    "ipEyebrow": "קניין רוחני",
    "ipTitle": "פטנטים ופרסומים",
    "eduEyebrow": "השכלה",
    "eduTitle": "תארים אקדמיים",
    "pressEyebrow": "עיתונות",
    "pressTitle": "הופיע ב",
    "moreLink": "צפו בפטנטים, פרסומים וכתבות בעיתונות בעמוד Insights →",
    "a1title": "יזם השנה",
    "a1desc": "Entrepreneur Magazine, 1999 — 2001 — מנהיגות והישגים פורצי דרך בחדשנות פלטפורמות ותשתיות.",
    "a2title": "10 החברות המובילות בארה\"ב ברפואה מדויקת",
    "a2desc": "Digital Invest Inc. הוכרה בין 10 החברות הטובות ביותר באמריקה ברפואה מדויקת ובריאות דיגיטלית — 2023.",
    "a3title": "Who's Who in America",
    "a3desc": "רשום, 1999 — 2018 — על הישגים יוצאי דופן ביצירה ופיתוח עסקים.",
    "a4title": "Who's Who in the World",
    "a4desc": "רשום, 2000 — 2004 — בין המנהיגים העולמיים במדע, הנדסה וחדשנות עסקית.",
    "a5title": "Who's Who in Science & Engineering",
    "a5desc": "רשום, 2000 — 2014 — על תרומות לטכנולוגיה, מערכות לוויין ותשתית דיגיטלית.",
    "a6title": "מהנדס אלקטרוניקה — דרגה 6",
    "a6desc": "ההכרה הגבוהה ביותר ב-Nikolaev Shipbuilding Plant (93,000 עובדים) על הנדסת מערכות לוויין לשידור וקליטה.",
    "ip1year": "פטנט",
    "ip1title": "מערכות HDTV לווייניות דיגיטליות",
    "ip1role": "נרכש לאחר מכן על ידי Sony",
    "ip1desc": "קיבל פטנט בתחום מערכות טלוויזיה בגובה רזולוציה (HDTV) לווייניות דיגיטליות. הפטנט נרכש לאחר מכן על ידי Sony Corporation, מה שמאשר את המשמעות המסחרית של החדשנות.",
    "ip2year": "פרסומים",
    "ip2title": "מאמרים טכניים",
    "ip2role": "מערכות לוויין ואופטיות",
    "ip2desc": "מחבר מאמרים טכניים המתמקדים במערכות לוויין ואופטיות להעברת נתונים. תרומות המחקר שלו כוללות עיבוד אותות, מידול סימולציה ופלטפורמות אוטומציה המיושמות בתקשורת, תשתית לאומית ובריאות דיגיטלית.",
    "ip3year": "מחקר",
    "ip3title": "שיתופי פעולה בינלאומיים",
    "ip3role": "ארה\"ב ואירופה",
    "ip3desc": "השתתף בשיתופי מחקר בינלאומיים וביוזמות להעברת ידע. פיתח מערכות הנדסה משובצות לאיסוף נתונים, אבחון חיזוי ותזמור מבוסס ענן במגזרים שונים.",
    "edu1title": "דוקטור לתואר במדעי הטכניקה",
    "edu1desc": "2009 — Ukrainian State Marine Technical University",
    "edu2title": "Ph.D. בטכנולוגיות מידע",
    "edu2desc": "2004 — Ukrainian State Marine Technical University",
    "edu3title": "תארי מוסמא",
    "edu3desc": "אלקטרוניקה, מערכות לוויין דיגיטליות וכלכלה",
    "press1title": "Healthcare Tech Outlook",
    "press1role": "כתבה על Digital Invest Inc.",
    "press1desc": "Digital Invest Inc. הוצגה כאחת מחברות המובילות באמריקה ברפואה מדויקת ובריאות דיגיטלית, וזכתה להכרה על גישות חדשניות לשינוי הרפואה באמצעות AI, ML וטכנולוגיות DNA.",
    "press1link": "קרא את הכתבה ←",
    "press2title": "Top Precision Medicine Solutions",
    "press2role": "הכרה בתעשייה",
    "press2desc": "נבחרה בין חברות פתרונות הרפואה המדויקת המובילות, המדגישה את תפקיד Digital Invest בקידום גישות ביו-מתמטיות לבריאות המודרנית.",
    "press2link": "צפה ברשימה ←"
  },
  "contact": {
    "eyebrow": "צור קשר",
    "title": "בואו נהיה בקשר",
    "lead": "לייעוץ, דירקטוריונים ושותפויות אסטרטגיות.",
    "infoTitle": "קשר ישיר",
    "email": "דוא\"ל",
    "phone": "טלפון",
    "location": "מיקום",
    "locationVal": "Charlotte, North Carolina\nUnited States",
    "linkedin": "LinkedIn",
    "company": "חברה נוכחית",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member",
    "formTitle": "שלח הודעה",
    "formLead": "מלאו את הטופס ואחזור אליכם.",
    "firstName": "שם פרטי",
    "lastName": "שם משפחה",
    "emailLabel": "כתובת דוא\"ל",
    "subject": "נושא",
    "message": "הודעה",
    "inquiryType": "Inquiry Type",
    "inquiryAdvisory": "Advisory / Board Role",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "infoEyebrow": "פרטי קשר"
  },
  "consulting": {
    "eyebrow": "שירותי ייעוץ",
    "title": "ייעוץ",
    "heroEyebrow": "הכוונה עסקית אסטרטגית",
    "heroTitle": "ייעוץ מומחה עם Michael Kofman",
    "heroLead": "Michael Kofman הוא חזון טכנולוגי הידוע בגישה הדינמית שלו להבנת הצרכים המשתנים של השוק המורכב של היום. יזם, חבר דירקטוריון ויועץ לחברות ציבוריות ופרטיות, ייסד בהצלחה מספר חברות בארצות הברית ובאירופה.",
    "cta": "יצירת קשר עם Michael Kofman",
    "introLead": "Michael Kofman הוא מנכ\"ל Digital Invest Inc. וחבר בדירקטוריון. מומחיותו כוללת כישורי ניהול, ניתוח אסטרטגי של טכנולוגיות ושווקים מתפתחים, אבטחת מידע ופרטיות, מחקר, מדע ופיתוח, ניהול והשקעות.",
    "specialtiesEyebrow": "תחומי מיקוד",
    "specialtiesTitle": "תחומי ההתמחות של Michael Kofman"
  },
  "insights": {
    "eyebrow": "מנהיגות מחשבתית",
    "title": "תובנות",
    "heroTitle": "תובנות להצלחה",
    "selectedEyebrow": "נקודות שיא נבחרות",
    "selectedTitle": "הכרה בולטת",
    "allPressTitle": "כל הכתבות בתקשורת",
    "quotesEyebrow": "בתקשורת",
    "quotesTitle": "הכרה בתעשייה וציטוטים",
    "articlesEyebrow": "תובנות",
    "articlesTitle": "נקודות מבט ניהוליות"
  },
  "cta": {
    "eyebrow": "בואו נעבוד יחד",
    "title": "בקשת ייעוץ או הזמנת הרצאה",
    "lead": "לתפקידי ייעוץ, משרות בדירקטוריון, הרצאות ושותפויות אסטרטגיות.",
    "button": "יצירת קשר"
  },
  "speaking": {
    "eyebrow": "הרצאות וכנסים",
    "title": "הזמינו את Michael Kofman להרצות",
    "lead": "זמין להרצאות בנושאי מנהיגות ניהולית, אסטרטגיה טכנולוגית, בריאות דיגיטלית, תשתיות נתונים וממשל תאגידי.",
    "topicsEyebrow": "נושאי ההרצאה",
    "topicsTitle": "תחומי מומחיות",
    "topicsLead": "הנושאים מבוססים על עשרות שנות ניסיון בהקמה ובהובלה של חברות בארצות הברית ובאירופה.",
    "processEyebrow": "איך להזמין",
    "processTitle": "תהליך ההזמנה",
    "process1title": "שלחו פנייה",
    "process1desc": "השתמשו בטופס יצירת הקשר או שלחו אימייל ל-mkofman@mkofman.com עם פרטי האירוע, קהל היעד והנושאים המבוקשים.",
    "process2title": "אישור היקף",
    "process2desc": "מתאמים את הפורמט (הרצאת מפתח, פאנל, ישיבת דירקטוריון או שולחן עגול להנהלה) ואת הלוגיסטיקה.",
    "process3title": "יצירת ערך",
    "process3desc": "המצגות מבוססות על תוצאות אמיתיות ממיזמים בתחומי אחסון נתונים, govtech ורפואה מדויקת.",
    "cta": "בקשת הזמנת הרצאה"
  },
  "caseStudies": {
    "eyebrow": "מקרי בוחן",
    "title": "בניית חברות שמצליחות להתרחב",
    "lead": "תוצאות נבחרות מהקמה והובלה של חברות בתחומי תשתיות נתונים ובריאות דיגיטלית.",
    "cs1eyebrow": "תשתיות נתונים · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "אתגר",
    "cs1challengeText": "לבנות ולהרחיב חברת Data Storage בשוק טכנולוגי שנמצא בתהליך קונסולידציה מהיר.",
    "cs1action": "גישה",
    "cs1actionText": "Michael Kofman ייסד את 9 Net Avenue Inc. בשנת 1996. החברה הפכה במהירות לאחת מחברות ה-Data Storage הגדולות בעולם.",
    "cs1result": "תוצאה",
    "cs1resultText": "בשנת 2000 נרכשה החברה על ידי Concentric Networks (NASDAQ: CNTX), ובהמשך על ידי XO Communications (NASDAQ: XOXO), והגיעה לשווי שוק שיא של 19.5 מיליארד דולר. לאחר הרכישה נצבר ניסיון רב בעבודה עם חברות ציבוריות, ישיבה בדירקטוריונים וקבלת החלטות אסטרטגיות בדרג הניהולי הבכיר ביותר.",
    "cs2eyebrow": "בריאות דיגיטלית · 2021 — היום",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "אתגר",
    "cs2challengeText": "להפוך גישות רפואיות מיושנות באמצעות מדע, טכנולוגיות DNA, AI ו-ML דרך פלטפורמה ביו-מתמטית חדשה.",
    "cs2action": "גישה",
    "cs2actionText": "Michael Kofman ייסד והרחיב את Digital Invest Inc. מהקמה ועד IPO מוצלח. הוא הוביל את כל תהליך ההנפקה: מבנה משפטי, ציות פיננסי, סבבי משקיעים ותיאום מול SEC. בנוסף הוביל תכנון, הקמה ותפעול של מספר מרכזי נתונים בארצות הברית ובאירופה.",
    "cs2result": "תוצאה",
    "cs2resultText": "הושגה צמיחה פיננסית עקבית, שמיצבה את החברה בין 10 החברות המובילות בארה״ב ברפואה מדויקת (2023). Digital Invest כוללת פרויקטים חדשניים כמו Human Digital Model, BioMath Life ו-Aero-Ground Robotics Operations Network."
  },
  "mediaKit": {
    "eyebrow": "עיתונות ואירועים",
    "title": "ערכת מדיה",
    "lead": "ביוגרפיות רשמיות, חומרי תמונה ופרטי קשר עבור עיתונות, כנסים ופניות דירקטוריון.",
    "bioEyebrow": "ביוגרפיות",
    "bioTitle": "ביוגרפיות רשמיות",
    "bioShortLabel": "50 מילים",
    "bioShort": "Michael Kofman הוא CEO של Digital Invest Inc., חבר דירקטוריון, יועץ ומייסד חברות בתחומי הטכנולוגיה והבריאות הדיגיטלית בארה״ב ובאירופה.",
    "bioMediumLabel": "150 מילים",
    "bioMedium": "Michael Kofman הוא CEO של Digital Invest Inc. ומשמש כחבר ב-Board of Directors שלה. כאיש חזון טכנולוגי, הוא מוכר בגישתו הדינמית להבנת הצרכים המשתנים של שוק מורכב. כיזם, חבר דירקטוריון ויועץ לחברות ציבוריות ופרטיות, הוא הקים בהצלחה מספר חברות בארצות הברית ובאירופה. תחומי המומחיות שלו כוללים הנהלה בכירה, ניתוח אסטרטגי של טכנולוגיות ושווקים מתפתחים, אבטחת מידע ופרטיות, מחקר, מדע ופיתוח, ניהול והשקעות.",
    "bioLongLabel": "500 מילים",
    "bioLong": "Michael Kofman הוא CEO של Digital Invest Inc. ומשמש כחבר ב-Board of Directors שלה. כאיש חזון טכנולוגי, הוא מוכר בגישתו הדינמית להבנת הצרכים המשתנים של השוק המורכב של ימינו. מומחיותו כוללת הנהלה בכירה, ניתוח אסטרטגי של טכנולוגיות ושווקים מתפתחים, אבטחת מידע ופרטיות, מחקר, מדע ופיתוח, ניהול והשקעות. כיזם, חבר דירקטוריון ויועץ לחברות ציבוריות ופרטיות, Michael Kofman הקים בהצלחה מספר חברות בארצות הברית ובאירופה. הוא ייסד את 9 Net Avenue Inc., שנרכשה בשווי שוק שיא של 19.5 מיליארד דולר, ומוביל את Digital Invest Inc. בתחומי אחסון נתונים וחדשנות טכנולוגית מתקדמת. הוא ניהל אסטרטגיה טכנולוגית לתוכניות ממשלתיות וביטחוניות, ייסד את XIBI Group Inc. ואת DataPeer Inc. בתחום אחסון הנתונים, ומילא תפקיד משמעותי ב-Biotechnology Group Inc. הוא שיתף פעולה עם Harvard Medical School ו-Stanford Biomath בתחום הדוחות הגנטיים. מחבר מאמרים טכניים על מערכות לוויין ואופטיקה; פטנט בתחום HDTV לווייני דיגיטלי נרכש על ידי Sony. השכלה: Doctor of Technical Sciences (2009), Ph.D. in Information Technology (2004), Ukrainian State Marine Technical University.",
    "photosEyebrow": "צילום",
    "photosTitle": "תמונות מאושרות",
    "photosLead": "דיוקנאות באיכות גבוהה זמינים לפי בקשה בכתובת mkofman@mkofman.com.",
    "contactEyebrow": "קשרי עיתונות",
    "contactTitle": "פניות מדיה",
    "contactLead": "לראיונות, הזמנות להרצאות ופניות תקשורת."
  },
  "articles": {
    "backLink": "← חזרה ל-Insights",
    "article1date": "נקודת מבט ניהולית",
    "article1title": "מהנדסה לתשתיות נתונים גלובליות",
    "article1p1": "הקריירה שלי החלה במפעל לבניית ספינות בניקולאייב שבאוקראינה, בפיתוח מערכות משדר-מקלט לווייניות להעברת מידע מסווג לספינות צבאיות. הוכרתי כמהנדס אלקטרוניקה ברמה הגבוהה ביותר - קטגוריה 6 - במפעל של 93,000 עובדים.",
    "article1p2": "בין 1989 ל-1994 ייסדתי והובלתי את Astra Corp, אחת היצרניות הגדולות באירופה של מערכות לוויין דיגיטליות מסוג משדר-מקלט. בין 1994 ל-1996, כ-CEO של Elitan United Inc., סייעתי להרחבת החברה מתשעה עובדים ליותר מ-4,000 עובדים ברחבי העולם.",
    "article1p3": "בשנת 1996 ייסדתי את 9 Net Avenue Inc., שהפכה במהירות לאחת מחברות ה-Data Storage הגדולות בעולם. עד שנת 2000 היא נרכשה על ידי Concentric Networks (NASDAQ: CNTX) ו-XO Communications (NASDAQ: XOXO), והגיעה לשווי שוק שיא של 19.5 מיליארד דולר.",
    "article1p4": "בין 2001 ל-2019 הובלתי אסטרטגיית טכנולוגיה לתוכניות ממשלתיות, ביטחוניות ולחברות בבעלות מדינה, תוך הובלת יוזמות רחבות היקף בתחומי Big Data, תשתיות מאובטחות ומרכזי נתונים בתפוקה גבוהה בארצות הברית ובאירופה.",
    "article2date": "בריאות דיגיטלית",
    "article2title": "רפואה מדויקת והמפגש בין מדע לטכנולוגיה",
    "article2p1": "אני מאמין עמוקות בפוטנציאל של שילוב מדעי החיים עם החידושים הטכנולוגיים המתקדמים ביותר. ב-Biotechnology Group Inc. ‏(2008-2014) התמקדנו בבדיקות וניתוחי DNA, אוטומציה של תהליכי יצירת פרופילים גנטיים, ומחקר גנטי מקיף של האדם.",
    "article2p2": "תחת הנהגתי, הושקו פרויקטים מוצלחים של בדיקות גנטיות באוקראינה, רוסיה ומדינות הבלטיות. בשיתוף עם Harvard Medical School ו-Stanford Biomath מילאתי תפקיד מרכזי בפיתוח דוחות גנטיים מובנים לרופאים ולמטופלים.",
    "article2p3": "עם Digital Invest Inc., שנוסדה ב-2021, אנו מתמקדים בתחום הביו-מתמטי ומשנים גישות מיושנות ברפואה באמצעות מדע, טכנולוגיות DNA, AI ו-ML. החברה הורחבה מהקמה ועד IPO מוצלח והוכרה בין 10 החברות הטובות בארצות הברית ברפואה מדויקת ובריאות דיגיטלית בשנת 2023.",
    "article2p4": "Digital Invest כוללת פרויקטים חדשניים מגוונים, בהם Human Digital Model, ‏BioMath Life ו-Aero-Ground Robotics Operations Network - וכל אחד מהם מקדם את שילוב מדעי הנתונים עם מדעי החיים."
  }
};
