window.__LANG_he = {
  "ui": {
    "toggleTheme": "החלפת ערכת בהיר/כהה",
    "selectLanguage": "בחר שפה",
    "messageSent": "ההודעה נשלחה",
    "sendMessage": "שלח",
    "toggleNav": "פתח תפריט",
    "sending": "שולח…",
    "formError": "לא ניתן היה לשלוח. נא לשלוח אימייל ישירות.",
    "present": "עד היום"
  },
  "nav": {
    "home": "בית",
    "about": "אודות",
    "ventures": "חברות",
    "career": "הרישום",
    "recognition": "הכרה",
    "contact": "יצירת קשר",
    "consulting": "ייעוץ",
    "insights": "תובנות",
    "speaking": "הרצאות",
    "caseStudies": "מקרי בוחן",
    "mediaKit": "ערכת מדיה",
    "groupMain": "ראשי",
    "groupServices": "שירותים",
    "groupWork": "עבודה",
    "briefIpo": "תקציר: IPO",
    "briefGenetic": "Brief: נתונים גנטיים",
    "briefAi": "Brief: אסטרטגיית AI",
    "articleInfra": "תשתית נתונים",
    "articleHealth": "רפואת דיוק",
    "board": "ייעוץ",
    "thesis": "תזת מנהיגות",
    "press": "עיתונות",
    "ip": "קניין רוחני"
  },
  "footer": {
    "navigation": "ניווט",
    "ventures": "חברות",
    "connect": "קשר",
    "desc": "מנהיג טכנולוגי, מייסד ויועץ דירקטוריון.",
    "copyright": "© {year} Michael Kofman. כל הזכויות שמורות.",
    "writeTitle": "כתבו לי",
    "writeEmail": "האימייל שלך",
    "writeMessage": "ההודעה שלך",
    "writeSend": "שלח",
    "writeSuccess": "תודה — ההודעה נשלחה.",
    "more": "עוד",
    "privacy": "פרטיות"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — מנהיג טכנולוגי",
      "description": "מנהיג טכנולוגי, מייסד ויועץ — תשתיות, מדעי החיים ומערכות אוטונומיות."
    },
    "about": {
      "title": "אודות — Michael Kofman",
      "description": "ביוגרפיה של Michael Kofman — מנכ\"ל Digital Invest Inc., מייסד AGRON Inc."
    },
    "ventures": {
      "title": "חברות — Michael Kofman",
      "description": "חברות שייסד וניהל מייקל קופמן — מ-Digital Invest Inc. ועד 9 Net Avenue Inc. — בניית עסקים משני מציאות בטכנולוגיה ובריאות."
    },
    "career": {
      "title": "הרישום — Michael Kofman",
      "description": "רשומה מקצועית בהנדסה, תשתיות, שווקים ציבוריים, מדעי החיים ומערכות אוטונומיות."
    },
    "recognition": {
      "title": "הכרה — Michael Kofman",
      "description": "פרסים והוקרות למייקל קופמן — יזם השנה, Who's Who, פטנטים והוקרות תעשייתיות."
    },
    "contact": {
      "title": "יצירת קשר — Michael Kofman",
      "description": "יצירת קשר עם מייקל קופמן — מנכ\"ל Digital Invest Inc. לייעוץ, הרצאות ופניות עסקיות."
    },
    "consulting": {
      "title": "ייעוץ — Michael Kofman",
      "description": "תפקידי ייעוץ, חברות בדירקטוריון, הרצאות ושותפויות אסטרטגיות עם Michael Kofman."
    },
    "insights": {
      "title": "תובנות — Michael Kofman",
      "description": "כתיבה מקורית ו-executive briefs מאת Michael Kofman."
    },
    "speaking": {
      "title": "הרצאות — Michael Kofman",
      "description": "הזמינו את Michael Kofman להרצות על מנהיגות ניהולית, אסטרטגיית טכנולוגיה, בריאות דיגיטלית וממשל תאגידי."
    },
    "caseStudies": {
      "title": "מקרי בוחן — Michael Kofman",
      "description": "מקרי בוחן מהקריירה של Michael Kofman: 9 Net Avenue Inc. ו-Digital Invest Inc."
    },
    "mediaKit": {
      "title": "ערכת מדיה — Michael Kofman",
      "description": "ביוגרפיות רשמיות, תמונות ופרטי קשר עבור עיתונות ומפיקי אירועים."
    },
    "article1": {
      "title": "מהנדסה לתשתית גלובלית — Michael Kofman",
      "description": "Michael Kofman על מסלול הקריירה מהנדסת לוויינים ועד הקמת חברות גלובליות לתשתיות נתונים."
    },
    "article2": {
      "title": "רפואה מדויקת וטכנולוגיה — Michael Kofman",
      "description": "Michael Kofman על שילוב מדעי החיים עם AI, ML וטכנולוגיות DNA ברפואה המודרנית."
    },
    "privacy": {
      "title": "מדיניות פרטיות — Michael Kofman",
      "description": "מדיניות פרטיות של mkofman.com — טפסים ואנליטיקה."
    },
    "board": {
      "title": "ייעוץ — Michael Kofman",
      "description": "שיחות ייעוץ אסטרטגי עם ארגוני טכנולוגיה, בריאות ותשתיות."
    },
    "thesis": {
      "title": "תזת מנהיגות — Michael Kofman",
      "description": "עקרונותיו של Michael Kofman לבניית חברות מתמשכות, ממשל טכנולוגיה ומנהיגות בשינוי משמעותי."
    },
    "press": {
      "title": "ארכיון עיתונות — Michael Kofman",
      "description": "Selected press coverage."
    },
    "ip": {
      "title": "קניין רוחני — Michael Kofman",
      "description": "Patents, publications ו-applied research."
    },
    "briefIpo": {
      "title": "מה IPO משנה — Michael Kofman",
      "description": "תקציר על operating discipline לפני ואחרי IPO."
    },
    "briefGenetic": {
      "title": "מנתונים גנטיים להחלטות קליניות — Michael Kofman",
      "description": "תקציר על תרגום genomic information ל-clinical intelligence."
    },
    "briefAi": {
      "title": "AI Strategy — Michael Kofman",
      "description": "תקציר מנהלים על מעבר AI מ-experimentation ל-governed enterprise capability."
    },
    "deck": {
      "title": "סקירה מנהלית — Michael Kofman",
      "description": "Private executive overview."
    }
  },
  "home": {
    "heroEyebrow": "האתר הרשמי של Michael Kofman",
    "heroTitle1": "נבנה להישאר.",
    "heroTitle2": "מונחה בשיקול דעת.",
    "heroCta": "גלו את הסיפור שלי",
    "heroAlt": "Michael Kofman",
    "quote1text": "מוזכר בין החברות המובילות בארה\"ב ברפואת דיוק ובריאות דיגיטלית.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "יזם השנה — הכרה למנהיגות ולהישגים פורצי דרך בחדשנות פלטפורמות ותשתיות.",
    "quote2author": "Entrepreneur Magazine · 2001",
    "quote3text": "Digital Invest Inc. בין 10 החברות המובילות בארה\"ב ברפואת דיוק ובריאות דיגיטלית.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "דיוק הנדסי עם אסטרטגיה עסקית — ממערכות לוויין לתשתית של",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "הכירו את Michael Kofman",
    "aboutTitle": "חברות שנבנו לטווח ארוך",
    "aboutLead1": "מנכ\"ל Digital Invest Inc. ומייסד AGRON Inc. ייסד והוביל חברות בארה\"ב ובאירופה.",
    "aboutLead2": "מ-9 Net Avenue (שווי שיא",
    "aboutLink": "ביוגרפיה מלאה",
    "expertiseEyebrow": "תחומי מיקוד",
    "expertiseTitle": "מנהיגות בכירה בין תעשיות",
    "expertiseLead": "ארבעה עשורים של בנייה, ייעוץ והשקעה בתשתית, בריאות ורובוטיקה.",
    "exp1title": "מנכ\"ל ומייסד",
    "exp1desc": "ייסד והנהיג מספר חברות טכנולוגיה בארצות הברית ובאירופה.",
    "exp1link": "חברות ←",
    "exp2title": "ארכיטקט טכנולוגי",
    "exp2desc": "תכנן תקשורת מאובטחת, מנועי אנליטיקה חיזויית ופלטפורמות אינטגרציית נתונים ברמה לאומית למגזרים ממשלתיים, צבאיים וטלקום.",
    "exp2link": "קריירה ←",
    "exp3title": "בריאות דיגיטלית",
    "exp3desc": "מוביל את שינוי הרפואה באמצעות בינה מלאכותית, למידת מכונה וטכנולוגיות DNA. שיתף פעולה עם Harvard Medical School ו-Stanford Biomath בדיווח גנטי.",
    "exp3link": "Digital Invest ←",
    "exp4title": "יועץ דירקטוריון",
    "exp4desc": "חבר בדירקטוריונים ומייעץ לחברות ציבוריות ופרטיות בנושאי כיוון אסטרטגי, ממשל תאגידי ויוזמות צמיחה מונחות טכנולוגיה.",
    "exp4link": "ייעוץ →",
    "stat1": "שנות מנהיגות",
    "stat2": "חברות שנוסדו",
    "stat3": "שווי שוק שיא",
    "stat4": "עובדים",
    "recEyebrow": "הכרה",
    "recTitle": "הכרה נבחרת",
    "recLead": "פרסי תעשייה והכרה בקרב עמיתים ביזמות, רפואה והנדסה.",
    "award1title": "יזם השנה",
    "award1desc": "Entrepreneur Magazine · 2001",
    "award2title": "10 מובילים ברפואת דיוק",
    "award2desc": "Digital Invest Inc. — U.S., 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "הכרה ועיתונות →",
    "heroSub": "טכנולוגיה, עסקים והשקעות בתשתיות, מדעי החיים ומערכות אוטונומיות.",
    "primaryCta": "בקשת ייעוץ",
    "secondaryCta": "צפייה במקרי בוחן",
    "featuredEyebrow": "מהארכיון",
    "caseStudiesEyebrow": "תוצאות מוכחות",
    "caseStudiesTitle": "מקרי בוחן",
    "caseStudiesLead": "הקמה, הרחבה והובלת חברות מהשלב הראשוני ועד רכישה ו-IPO.",
    "caseStudiesLink": "צפייה בכל מקרי הבוחן →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "נבנתה כאחת מחברות ה-Data Storage הגדולות בעולם ונרכשה בשווי שוק שיא של 19.5 מיליארד דולר.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "הוקמה והורחבה מההתחלה ועד IPO מוצלח - בין 10 החברות המובילות בארה״ב ברפואה מדויקת, 2023.",
    "cs3title": "AGRON Inc.",
    "cs3desc": "Founded in 2026 — the AGRON Ecosystem for UAV capability development, geospatial systems, and maritime intelligence.",
    "boardCtaEyebrow": "Advisory",
    "boardCtaTitle": "Experience for the Decisions That Define an Enterprise",
    "boardCtaLead": "Independent perspective for boards and leaders navigating technology, governance, transformation, and growth.",
    "boardCtaBtn": "Explore Advisory",
    "testimonialsEyebrow": "Trusted Perspective",
    "testimonialsTitle": "What Colleagues Value",
    "videoEyebrow": "Executive Perspective",
    "videoTitle": "Leadership at the Intersection of Technology and Enterprise",
    "videoLead": "A concise introduction to the principles, experience, and long-term perspective behind Michael Kofman's work.",
    "videoCta": "Read Leadership Thesis →",
    "heroName": "Michael Kofman",
    "heroRole": "מנהיג טכנולוגי · מייסד · יועץ",
    "introText": "Michael Kofman הוא מנהיג טכנולוגי ומייסד חברות. עבודתו משתרעת על הנדסת לוויינים, תשתיות אינטרנט, חברות טכנולוגיה ציבוריות ומדעי החיים. ייסד את 9 Net Avenue Inc., שנרכשה על ידי Concentric Networks ב-2000. CEO של Digital Invest Inc. ברפואה ביו-מתמטית ואינטליגנציה גנומית; מייסד AGRON Inc. בפעילות אווירית-קרקעית אוטונומית ומערכות גאו-מרחביות. מכהן בדירקטוריונים ומייעץ בתחומי טכנולוגיה, בריאות ותשתיות.",
    "introLink": "ביוגרפיה מלאה →",
    "currentEyebrow": "עבודה נוכחית",
    "currentTitle": "מוקד נוכחי",
    "currentDiTitle": "Digital Invest Inc.",
    "currentDiDesc": "רפואה ביו-מתמטית, נתונים גénomיים ואינטליגנציה קlinית — AI, ML וטכנולוגיות DNA לתוצאות בריאותיות אחראיות.",
    "currentDiLink": "Ventures →",
    "currentAgTitle": "AGRON Inc.",
    "currentAgDesc": "פעילות אווירית-קרקעית אוטונומית, פיתוח יכולות UAV, מערכות גאו-מרחביות ותשתית מודיעין ימי.",
    "currentAgLink": "agron1.com →",
    "careerEyebrow": "רשומה נבחרת",
    "careerTitle": "רציפות בין תקופות טכנולוגיות",
    "careerLead": "Selected milestones מהנדסה ועד current work ב-autonomous systems.",
    "career1title": "הנדסה ותקשורת",
    "career1desc": "מערכות transceiver לווייניות, תקשורת דיגיטלית ומנהיגות הנדסית מוקדמת.",
    "career2title": "אינטרנט ותשתית",
    "career2desc": "תשתית אינטרנט, מרכזי נתונים, אחסון וטלקום בקנה מידה.",
    "career3title": "חברות טכנולוגיה ושווקים ציבוריים",
    "career3desc": "בניית חברות, רכישות וניסיון בחברות ציבוריות, כולל 9 Net Avenue Inc.",
    "career4title": "מדעי החיים ונתוני אדם",
    "career4desc": "Biotechnology, genetic data, precision medicine ו-health intelligence platforms.",
    "career5title": "מערכות אוטונומיות",
    "career5desc": "Aerial-ground robotics, UAV operations ו-geospatial infrastructure.",
    "careerLink": "הרישום →",
    "perspectivesEyebrow": "פרספקטיבות",
    "perspectivesTitle": "כתיבה נבחרת",
    "perspectivesLink": "כל התובנות →",
    "footerHomeDesc": "מנהיג טכנולוגי, מייסד ויועץ.",
    "activeSitesLink": "כל האתרים הפעילים →"
  },
  "about": {
    "eyebrow": "אודות Michael Kofman",
    "title": "שלושה עשורים של ניסיון",
    "lead": "מנהיג טכנולוגי, מייסד ויועץ.",
    "glance": "בקצרה",
    "role": "תפקיד נוכחי",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "מיקום",
    "locationVal": "Charlotte, North Carolina",
    "education": "השכלה",
    "educationVal": "דוקטור למדעי הטכניקה\nPh.D. בטכנולוגיות מידע\nתארים שני — אלקטרוניקה, מערכות לוויין דיגיטליות וכלכלה",
    "university": "אוניברסיטה",
    "universityVal": "האוניברסיטה הטכנית הימית הממלכתית של אוקראינה",
    "languages": "שפות",
    "languagesVal": "אנגלית, רוסית, אוקראינית",
    "contactLabel": "יצירת קשר",
    "principlesEyebrow": "עקרונות תפעול",
    "principlesTitle": "איך אני מנהיג",
    "p1title": "להבין את המערכת",
    "p1text": "לפני שינוי ארגון, להבין את התמריצים, הארכיטקטורה, האילוצים ומקורות האמון.",
    "p2title": "להפוך אחריות לברורה",
    "p2text": "בעלות ברורה ותוצאות מדידות הופכות אסטרטגיה מחומר מצגת למציאות תפעולית.",
    "p3title": "להשאיר מוסדות חזקים יותר",
    "p3text": "מנהיגות צריכה להכפיל יכולת על ידי פיתוח אנשים, שיפור החלטות ובניית מערכות שנשארות.",
    "archiveEyebrow": "מהארכיון",
    "archiveTitle": "מהארכיון",
    "archiveLead": "חומר אותנטי מבניית חברות, תשתיות ומנהיגות.",
    "photo9netTitle": "9 Net Avenue",
    "photo9netCaption": "מייסד ו-CEO — חברת אירוח ותשתית אינטרנט, נרכשה על ידי Concentric Networks ב-2000.",
    "photoServerTitle": "תשתית נתונים",
    "photoServerCaption": "סביבות אחסון, רשתות ושרתים ב-DataPeer ובחברות קשורות.",
    "photoTodayTitle": "היום",
    "photoTodayCaption": "Digital Invest Inc., AGRON Inc. ועבודת ייעוץ.",
    "secIntroTitle": "הקדמה",
    "secTechTitle": "טכנולוגיה ותשתיות",
    "secBusinessTitle": "עסקים",
    "secCurrentTitle": "עבודה נוכחית",
    "secBackgroundTitle": "רקע",
    "recordLink": "הרישום →",
    "secBackgroundP1": "Doctor of Technical Sciences ו-Ph.D. in Information Technology. מחבר מאמרים טכניים; פטנט HDTV לווייני נרכש על ידי Sony.",
    "bioP1": "Michael Kofman הוא מנהיג טכנולוגי, מייסד ויועץ. CEO של Digital Invest Inc. ומייסד AGRON Inc., עם ניסיון בהנדסת לוויינים, תשתיות אינטרנט, חברות ציבוריות ומדעי החיים.",
    "bioP2": "As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. In 2026 he founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network. He also created Digital Invest, dedicated to the bio-mathematical sphere and transforming medicine through science, DNA technologies, AI, and ML.",
    "secBioTitle": "רפואה מדויקת וביוטכנולוגיה",
    "secBioP1": "טרם Digital Invest, הוא מילא תפקיד מרכזי בהצלחה של Biotechnology Group Inc. (2008 — 2014), חברה המחויבת לבדיקות וניתוח DNA, אוטומציה של תהליכי יצירת פרופילים גנטיים ומחקר גנטי אנושי מקיף. מר Kofman מאמין בתוקף בפוטנציאל של שילוב מדעי החיים עם ההתקדמות הטכנולוגית העדכנית ביותר.",
    "secBioP2": "תחת הנהגתו, יוזמו פרויקטים מוצלחים של בדיקות גנטיות באוקראינה, ברוסיה ובמדינות Baltic. ניסיון ייחודי זה מועשר ללא הרף בטכנולוגיות מודרניות ובציוד חדש. בשיתוף עם Harvard Medical School ו-Stanford Biomath, מר Kofman מילא תפקיד מכריע בפיתוח דוחות גנטיים מובנים לרופאים ולמטופלים כאחד. גישה חדשנית זו אומצה על ידי מעבדות מובילות בארצות הברית ובחו\"ל.",
    "secTechP1": "רקע הנדסי במערכות transceiver לווייניות ותקשורת דיגיטלית ב-Astra Corp.",
    "secTechP2": "ב-2006, מר Kofman הקים את XIBI Group Inc. — חברת טכנולוגיה שבה כיהן בדירקטוריון. החברה האמריקאית מתמחה באחסון נתונים ובשירותי ניהול big data לארגונים מסחריים וממשלתיים גדולים.",
    "secTechP3": "מ-2000 עד 2004, מר Kofman הוביל את DataPeer Inc. — חברת ניהול ואחסון נתונים המציעה מגוון רחב של שירותים הקשורים לאחסון מידע לעסקים קטנים ובינוניים. ב-DataPeer פיתח פתרונות טכנולוגיים ייחודיים שסייעו למעקב מהיר יותר אחר מידע ולנגישות קלה יותר לנתונים עבור משתמשי קצה ומוסדות ממשלתיים ברחבי העולם.",
    "secTechP4": "Founded 9 Net Avenue Inc. in 1996. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "secPost9NetP1": "לאחר רכישת 9 Net Avenue, מר Kofman צבר ניסיון רב בעבודה בחברות ציבוריות, השתתפות בדירקטוריונים וקבלת החלטות אסטרטגיות ברמה הנהלתית העליונה.",
    "secEarlyTitle": "קריירה מוקדמת והנדסה",
    "secEarlyP1": "מ-1994 עד 1996, מר Kofman כיהן כמנכ\"ל וכמנהל טכנולוגיות מידע ב-Elitan United Inc. — חברת IT מ-Massachusetts, שסיפקה אסטרטגיות מקיפות ושירותים טכנולוגיים לארגונים גלובליים מובילים. הוא מילא תפקיד מכריע בפיתוח וניהול תשתית ניתנת להרחבה, והוביל את צמיחת החברה מ-9 עובדים בלבד ליותר מ-4,000 עובדים ברחבי העולם.",
    "secEarlyP2": "מ-1989 עד 1994, הוא היה מייסד ומנכ\"ל Astra Corp, אחת היצרניות הגדולות באירופה של מערכות לוויין דיגיטליות לשידור וקליטה, שזכתה להכרה בינלאומית בתחום מכשירי הלוויין. תחומי אחריותו כללו מחקר, פיתוח מערכות הפעלה, יישומי תוכנת רשת ואסטרטגיה טכנית כוללת.",
    "secEarlyP3": "מ-1984 עד 1989, מר Kofman עבד במספנת האוניות ב-Nikolaev, אוקראינה, שם השתתף באופן פעיל בפיתוח וביצירת מערכות לוויין לשידור וקליטה להעברת מידע סודי לספינות צבאיים ובחזרה. הוא הוכר כמהנדס אלקטרוניקה ברמה הגבוהה ביותר, וקיבל את דרגה 6 — ההכרה הגבוהה ביותר במספנה, שבו עבדו 93 אלף אנשים.",
    "secResearchTitle": "מחקר ופטנטים",
    "secResearchP1": "Michael Kofman הוא מחבר מאמרים טכניים המתמקדים במערכות לוויין ואופטיות להעברת נתונים. הוא גם קיבל פטנט בתחום מערכות טלוויזיה בגובה רזולוציה (HDTV) לווייניות דיגיטליות, שנרכש לאחר מכן על ידי Sony.",
    "secAgronTitle": "Robotics, UAV & Maritime Intelligence",
    "secAgronP1": "In 2026, Mr. Kofman founded AGRON Inc. to build the AGRON Ecosystem — a corporate operating architecture for aerial and ground robotics, governed mission execution, and network infrastructure connecting teams, assets, and operational data. The ecosystem delivers consulting, assessment, capability development, and training for UAV and Counter-UAS organizations, alongside maritime intelligence and security services at agron1.com.",
    "secBusinessP1": "ייסד והנהיג חברות טכנולוגיה רבות. כרונולוגיה מלאה ב-The Record.",
    "secCurrentP1": "CEO של Digital Invest Inc. ברפואה ביו-מתמטית ואינטליגנציה גénomית. מייסד AGRON Inc. בפעילות אווירית-קרקעית אוטונומית."
  },
  "ventures": {
    "eyebrow": "תיק חברות",
    "title": "חברות שהקים והוביל",
    "lead": "מרפואת דיוק ורובוטיקה ועד תשתיות נתונים גלובליות — הקמה, צמיחה והובלה בארה\"ב ובאירופה.",
    "ecosystemEyebrow": "Venture Ecosystem",
    "ecosystemTitle": "Companies Across Technology Frontiers",
    "ecosystemLead": "A portfolio shaped by recurring themes: trusted data, intelligent infrastructure, human health, and systems built for scale.",
    "statusActive": "פעיל",
    "statusExited": "יציאה",
    "statusLegacy": "מורשת",
    "v1lesson": "לקח: תשתית מנצחת כשאמינות, כלכליות ואמון לקוחות משתפרים יחד.",
    "v2lesson": "לקח: רפואת דיוק דורשת משמעת שווה במדע, תוכנה, פרטיות ותועלת קלינית.",
    "v3lesson": "לקח: אוטונומיה יוצרת ערך רק כשחישה, תקשורת ופיקוח אנושי יוצרים מערכת אחת עמידה.",
    "v5lesson": "לקח: קנה מידה בתשתיות נבנה במצוינות תפעולית הרבה לפני יציאה.",
    "currentEyebrow": "נוכחי",
    "historyEyebrow": "היסטוריה נבחרת",
    "v2highlight": "Harvard Medical School ו-Stanford Biomath — שיתוף פעולה בדיווח genético",
    "activeSitesEyebrow": "פרויקטים פעילים",
    "activeSitesTitle": "אתרים פעילים",
    "activeSitesLead": "אתרים פעילים של חברות נוכחיות ויוזמות portfolio.",
    "activeSitesMeta": "10 אתרים פעילים · לחצו על כרטיס לביקור",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — an Aerial-Ground Robotics Operations Network spanning UAV and Counter-UAS consulting, technology assessment, capability development, training infrastructure, product validation, geospatial systems (ISDRI), and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "v0role": "Founder",
    "v0year": "2026 — Present",
    "v2role": "מנכ\"ל ו-CTO",
    "v2year": "2008 — 2014",
    "v3year": "2006 — 2011",
    "v4year": "2000 — 2004",
    "v5highlight": "Acquired · Concentric Networks, 2000",
    "v5p1": "Founded and led a hosting and internet infrastructure company. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "v5year": "1996 — 2000",
    "v6year": "1994 — 1996",
    "v7year": "1989 — 1994",
    "v8year": "1984 — 1989",
    "v1highlight": "10 החברות המובילות בארה\"ב ברפואה מדויקת — 2023",
    "v1p1": "רפואה ביו-מתמטית, נתונים גנומיים ואינטליגנציה קlinית — AI, ML וטכנולוגיות DNA בזרימות clínico ומחקר.",
    "v1role": "מייסד ומנכ\"ל · חבר דירקטוריון",
    "v1year": "2021 — עד היום",
    "v2p1": "בדיקות וניתוח DNA, אוטומציה של פרופילים גנטיים ומחקר גנטי אנושי מקיף. יזם פרויקטי בדיקות גנטיות באוקראינה, ברוסיה ובמדינות Baltic.",
    "v2p2": "שיתף פעולה עם Harvard Medical School ו-Stanford Biomath בדוחות גנטיים שאומצו על ידי מעבדות מובילות ברחבי העולם.",
    "v3highlight": "פתרונות נתונים ארגוניים וממשלתיים",
    "v3p1": "אחסון נתונים ושירותי ניהול big data לארגונים מסחריים וממשלתיים גדולים. ביסס את החברה כספק מהימן של פתרונות נתונים ארגוניים.",
    "v3role": "מייסד ומנכ\"ל · דירקטוריון",
    "v4highlight": "פלטפורמה גלובלית לניהול נתונים",
    "v4p1": "ניהול ואחסון נתונים לעסקים קטנים ובינוניים. פיתח פתרונות למעקב מהיר יותר אחר מידע ולנגישות קלה יותר לנתונים עבור משתמשי קצה ומוסדות ממשלתיים ברחבי העולם.",
    "v4role": "מייסד ומנכ\"ל",
    "v5role": "מייסד ומנכ\"ל",
    "v6highlight": "אסטרטגיית IT ותשתיות גלובליות",
    "v6p1": "חברת IT מ-Massachusetts המספקת אסטרטגיות מקיפות ושירותים טכנולוגיים לארגונים גלובליים מובילים. הוביל פיתוח תשתית ניתנת להרחבה ותפעול IT גלובלי.",
    "v6role": "מנכ\"ל ומנהל טכנולוגיות מידע",
    "v7highlight": "מובילה אירופית במערכות לוויין",
    "v7p1": "אחת היצרניות הגדולות באירופה של מערכות לוויין דיגיטליות לשידור וקליטה. הוביל מחקר, פיתוח מערכות הפעלה, יישומי תוכנת רשת ואסטרטגיה טכנית כוללת.",
    "v7role": "מייסד ומנכ\"ל",
    "v8highlight": "הנדסת מערכות לוויין צבאיות",
    "v8p1": "פיתוח ויצירת מערכות לוויין לשידור וקליטה להעברת מידע סודי לספינות צבאיים. הוכר כמהנדס אלקטרוניקה ברמה הגבוהה ביותר במספנה של 93,000 עובדים.",
    "v8role": "מהנדס אלקטרוניקה · דרגה עליונה (6)",
    "v1p2": "יוזמות בתיק כוללות <a href=\"https://biomathlife.com\" target=\"_blank\" rel=\"noopener\">BioMath Life</a>, <a href=\"https://www.biomathcore.com\" target=\"_blank\" rel=\"noopener\">BioMath Core</a>, <a href=\"https://www.type1and2.com\" target=\"_blank\" rel=\"noopener\">Type 1 &amp; 2</a> ו-<a href=\"https://www.luna29.com\" target=\"_blank\" rel=\"noopener\">Luna29</a> — מחקרי מקרה מפורטים יעלו בהמשך.",
    "v1brole": "מנכ\"ל",
    "v1bp1": "תקופת מעבר בין ביוטכנולוגיה לפיתוח טכנולוגי חדש — בניית ניסיון תפעולי ו-R&D לפני Digital Invest Inc.",
    "v1byear": "2014 — 2020"
  },
  "career": {
    "eyebrow": "מסלול מקצועי",
    "title": "הרישום",
    "lead": "טכנולוגיה, חברות וניסיון תפעולי לאורך תקופות של שינוי טכנולוגי.",
    "timelineEyebrow": "ציר זמן",
    "timelineTitle": "אבני דרך",
    "strengthsEyebrow": "חוזקות",
    "strengthsTitle": "תחומי מומחיות",
    "filterAll": "All",
    "filterHealthcare": "Healthcare",
    "filterInfrastructure": "Infrastructure",
    "filterDefense": "Defense",
    "filterTelecom": "Telecommunications",
    "periodCurrent": "מערכות אוטונומיות",
    "periodCurrentLead": "AI, רובוטיקה, פעילות אוטונומית, מערכות geospatial ותשתית נוכחית קשורה.",
    "period1title": "הנדסה ותקשורת",
    "period1lead": "הנדסה מוקדמת, מערכות לוויין, תקשורת ועבודה טכנולוגית קשורה.",
    "period2title": "אינטרנט ותשתית",
    "period2lead": "תשתית אינטרנט, טלקום, מרכזי נתונים, אחסון וחברות קשורות.",
    "period3title": "חברות ושווקים ציבוריים",
    "period3lead": "בניית חברות, עסקאות, מעורבות בחברות ציבוריות ותפקידים executive.",
    "period4title": "מדעי החיים ונתוני אדם",
    "period4lead": "ביוטכנולוגיה, טכנולוגיית בריאות, נתונים ורפואת דיוק.",
    "period5title": "תוכניות ממשלה וביטחון",
    "period5lead": "אסטרטגיה ומסירה טכנולוגית לתוכניות ממשלתיות, ביטחוניות ומ enterprises בבעלות מדינה.",
    "t1desc": "Digital Invest Inc. הוקמה ב-2021. רפואה ביו-מתמטית, אינטליגנציה גנומית ופלטפורמות נתונים קlinיים. Healthcare Tech Outlook (2023).",
    "t0desc": "Founded AGRON Inc. to build the AGRON Ecosystem — consulting, assessment, capability development, training infrastructure, and product support for UAV and Counter-UAS programmes, plus AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure. Connects aerial and ground robotics, governed mission execution, and network infrastructure linking teams, assets, and operational data.",
    "t0role": "Founder",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — Present",
    "t10title": "Nikolaev Shipbuilding Plant",
    "t10year": "1984 — 1989",
    "t1title": "Digital Invest Inc.",
    "t2year": "2001 — 2019",
    "t3role": "מנכ\"ל ו-CTO",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4year": "2000 — 2012",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "Founded and led 9 Net Avenue Inc., a hosting and internet infrastructure company. Acquired by Concentric Networks (NASDAQ: CNTX) in 2000; subsequently part of XO Communications (NASDAQ: XOXO).",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994",
    "t10desc": "פיתח ויצר מערכות לוויין לשידור וקליטה להעברת מידע סודי לספינות צבאיים. הוכר כמהנדס אלקטרוניקה ברמה הגבוהה ביותר במספנה של 93,000 עובדים — תחילתה של קריירה מצטיינת בטכנולוגיה וחדשנות.",
    "t10role": "מהנדס אלקטרוניקה — דרגה 6 (הגבוהה ביותר)",
    "t1role": "מייסד ומנכ\"ל",
    "t1year": "2021 — עד היום",
    "t2desc": "הוביל אסטרטגיה טכנולוגית ומסירה לתוכניות סודיות ורגישות הכוללות סוכנויות ממשלתיות אמריקאיות, מערכות ביטחון של בני ברית וארגונים בבעלות המדינה. עמד בראש פרויקטים טכניים מורכבים לחברות בבעלות הממשלה במגזרים שונים. בעקבות 11 בספטמבר 2001, הוביל יוזמות ממשלתיות בקנה מידה גדול המתמקדות ב-big data, תקשורת מאובטחת, אנליטיקה חיזויית ואינטגרציה של נתונים ברמה לאומית — כולל תכנון, בנייה ותפעול של מרכזי נתונים בעלי תפוקה גבוהה בארצות הברית ובאירופה. שיתף פעולה עם קציני תוכניות צבאיים, ספקי טכנולוגיה וגורמים רגולטוריים.",
    "t2role": "יועץ טכנולוגי ראשי / אדריכל תוכניות",
    "t2title": "GovTech, ביטחון ותוכניות מדינה",
    "t3desc": "הוביל בדיקות וניתוח DNA, אוטומציה של פרופילים גנטיים ומחקר גנטי אנושי מקיף. יזם פרויקטי בדיקות גנטיות באוקראינה, ברוסיה ובמדינות Baltic. שיתף פעולה עם Harvard Medical School ו-Stanford Biomath לפיתוח דוחות גנטיים מובנים שאומצו על ידי מעבדות מובילות ברחבי העולם.",
    "t4desc": "הוביל פריסות תשתית לאומיות בקנדה, איטליה, שווייץ, אוקראינה והרפובליקות Baltic. פיקח על יותר מ-1,000 מהנדסים וצוותי פריסה בפעילות תקשורת כולל מערכות מיתוג, הרחבת פס רחב וקישוריות חוצת גבולות. יישם מערכות ליבה לגיבוית רשת, אופטימיזציה של זמן פעילות וניתוב חכם.",
    "t4role": "VP טכנולוגיה / CTO אזורי — מזרח אירופה ו-CIS",
    "t4title": "פרויקטי תקשורת",
    "t5desc": "הקים חברת טכנולוגיה המתמחה באחסון נתונים ובניהול big data לארגונים מסחריים וממשלתיים גדולים. ביסס את החברה כספק מהימן של פתרונות נתונים ארגוניים.",
    "t5role": "מייסד ומנכ\"ל · דירקטוריון",
    "t6desc": "הקים חברת ניהול ואחסון נתונים לעסקים קטנים ובינוניים. פיתח פתרונות טכנולוגיים ייחודיים למעקב מהיר יותר אחר מידע ולנגישות קלה יותר לנתונים עבור משתמשי קצה ומוסדות ממשלתיים ברחבי העולם.",
    "t6role": "מייסד ומנכ\"ל",
    "t7role": "מייסד ומנכ\"ל",
    "t8desc": "הוביל אסטרטגיות IT מקיפות ושירותים טכנולוגיים לארגונים גלובליים מובילים מ-Massachusetts בתקופת התרחבות מהירה, ובנה תשתית ניתנת להרחבה ותפעול IT גלובלי.",
    "t8role": "מנכ\"ל ומנהל טכנולוגיות מידע",
    "t9desc": "הקים אחת היצרניות הגדולות באירופה של מערכות לוויין דיגיטליות לשידור וקליטה. הוביל מחקר, פיתוח מערכות הפעלה, יישומי תוכנת רשת ואסטרטגיה טכנית כוללת, וזכה להכרה בינלאומית.",
    "t9role": "מייסד ומנכ\"ל",
    "t1bdesc": "תקופת מעבר בין ביוטכנולוגיה לפיתוח טכנולוגי חדש — בניית ניסיון תפעולי ו-R&D לפני Digital Invest Inc.",
    "t1brole": "מנכ\"ל",
    "t1byear": "2014 — 2020"
  },
  "recognition": {
    "eyebrow": "פרסים",
    "title": "פרסים והכרה",
    "lead": "הוקרה ביזמות, רפואת דיוק, הנדסה ומנהיגות.",
    "industryEyebrow": "פרסי התעשייה",
    "industryTitle": "אותות כבוד מרכזיים",
    "ipEyebrow": "קניין רוחני",
    "ipTitle": "פטנטים ופרסומים",
    "eduEyebrow": "השכלה",
    "eduTitle": "תארים אקדמיים",
    "pressEyebrow": "עיתונות",
    "pressTitle": "הופיע ב",
    "moreLink": "צפו בפטנטים, פרסומים וכתבות בעיתונות בעמוד Insights →",
    "a1desc": "Entrepreneur Magazine · 2001",
    "a3title": "Who's Who in America",
    "a4title": "Who's Who in the World",
    "a5title": "Who's Who in Science & Engineering",
    "ip1year": "פטנט",
    "ip2year": "פרסומים",
    "press1role": "כתבה על Digital Invest Inc.",
    "press1title": "Healthcare Tech Outlook",
    "press2title": "Top Precision Medicine Solutions",
    "a1title": "יזם השנה",
    "a2title": "10 החברות המובילות בארה\"ב ברפואה מדויקת",
    "a2desc": "Digital Invest Inc. הוכרה בין 10 החברות הטובות ביותר באמריקה ברפואה מדויקת ובריאות דיגיטלית — 2023.",
    "a3desc": "רשום, 1999 — 2018 — על הישגים יוצאי דופן ביצירה ופיתוח עסקים.",
    "a4desc": "רשום, 2000 — 2004 — בין המנהיגים העולמיים במדע, הנדסה וחדשנות עסקית.",
    "a5desc": "רשום, 2000 — 2014 — על תרומות לטכנולוגיה, מערכות לוויין ותשתית דיגיטלית.",
    "a6title": "מהנדס אלקטרוניקה — דרגה 6",
    "a6desc": "ההכרה הגבוהה ביותר ב-Nikolaev Shipbuilding Plant (93,000 עובדים) על הנדסת מערכות לוויין לשידור וקליטה.",
    "ip1title": "מערכות HDTV לווייניות דיגיטליות",
    "ip1role": "נרכש לאחר מכן על ידי Sony",
    "ip1desc": "פטנט במערכות HDTV לווייני דיגיטלי, נרכש על ידי Sony Corporation.",
    "ip2title": "מאמרים טכניים",
    "ip2role": "מערכות לוויין ואופטיות",
    "ip2desc": "מחבר מאמרים טכניים המתמקדים במערכות לוויין ואופטיות להעברת נתונים. תרומות המחקר שלו כוללות עיבוד אותות, מידול סימולציה ופלטפורמות אוטומציה המיושמות בתקשורת, תשתית לאומית ובריאות דיגיטלית.",
    "ip3year": "מחקר",
    "ip3title": "שיתופי פעולה בינלאומיים",
    "ip3role": "ארה\"ב ואירופה",
    "ip3desc": "השתתף בשיתופי מחקר בינלאומיים וביוזמות להעברת ידע. פיתח מערכות הנדסה משובצות לאיסוף נתונים, אבחון חיזוי ותזמור מבוסס ענן במגזרים שונים.",
    "edu1title": "דוקטור לתואר במדעי הטכניקה",
    "edu2title": "Ph.D. בטכנולוגיות מידע",
    "edu3title": "תארי מוסמא",
    "edu3desc": "אלקטרוניקה, מערכות לוויין דיגיטליות וכלכלה",
    "press1desc": "Healthcare Tech Outlook על Digital Invest Inc. (2023).",
    "press1link": "קרא את הכתבה ←",
    "press2role": "הכרה בתעשייה",
    "press2desc": "נבחרה בין חברות פתרונות הרפואה המדויקת המובילות, המדגישה את תפקיד Digital Invest בקידום גישות ביו-מתמטיות לבריאות המודרנית.",
    "press2link": "צפה ברשימה ←"
  },
  "contact": {
    "eyebrow": "יצירת קשר",
    "title": "יצירת קשר",
    "lead": "לייעוץ, דירקטוריונים ושותפויות אסטרטגיות.",
    "infoTitle": "קשר ישיר",
    "email": "דוא\"ל",
    "phone": "טלפון",
    "location": "מיקום",
    "locationVal": "Charlotte, North Carolina\nארצות הברית",
    "linkedin": "LinkedIn",
    "company": "חברה נוכחית",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member\nAGRON Inc.\nמייסד",
    "formTitle": "שלח הודעה",
    "formLead": "מלאו את הטופס ואחזור אליכם.",
    "firstName": "שם פרטי",
    "lastName": "שם משפחה",
    "emailLabel": "כתובת דוא\"ל",
    "subject": "נושא",
    "message": "הודעה",
    "inquiryType": "סוג פנייה",
    "inquiryAdvisory": "ייעוץ",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "calendlyEyebrow": "קבע שיחה",
    "calendlyTitle": "בחרו זמן נוח",
    "calendlyLead": "לפניות qualified בנושאי דירקטוריון, ייעוץ, הרצאות ושותפויות אסטרטגיות.",
    "calendlyPlaceholder": "יומן התיאומים יופיע כאן.",
    "calendlyCta": "פתח יומן תיאומים",
    "inquiryBusiness": "עסקים",
    "infoEyebrow": "פרטי קשר"
  },
  "consulting": {
    "eyebrow": "שירותי ייעוץ",
    "title": "ייעוץ",
    "heroEyebrow": "הכוונה עסקית אסטרטגית",
    "heroTitle": "ייעוץ אסטרטגי",
    "heroLead": "שלושים וחמש שנים של הקמת חברות וייעוץ בארה\"ב ובאירופה — תשתיות נתונים, govtech, רפואת דיוק ורובוטיקה.",
    "cta": "יצירת קשר עם Michael Kofman",
    "introLead": "מנכ\"ל Digital Invest Inc. וחבר דירקטוריון. מיקוד: טכנולוגיות מתפתחות, אבטחה, מחקר והקצאת הון.",
    "specialtiesEyebrow": "תחומי מיקוד",
    "specialtiesTitle": "תחומי ההתמחות של Michael Kofman",
    "area1title": "שירות דירקטוריון",
    "area1desc": "עבודה עצמאית בדירקטוריונים באסטרטגיה טכנולוגית, ממשל תאגידי ופיקוח בשלבי צמיחה.",
    "area2title": "ייעוץ CEO ומייסדים",
    "area2desc": "אסטרטגיה תאגידית וטכנולוגית, פיתוח ארגוני, עסקאות וניסיון בשוק ההון.",
    "area3title": "Due diligence טכנולוגי",
    "area3desc": "הערכת תשתיות, פלטפורמות נתונים, ארכיטקטורת אבטחה וטכנולוגיה יישומית על בסיס ניסיון תפעולי מתועד.",
    "redirectLead": "עבודת ייעוץ אסטרטגי מתועדת בעמוד Advisory. לפניות מקצועיות, השתמשו ב-Contact.",
    "redirectLink": "ייעוץ →"
  },
  "insights": {
    "eyebrow": "פרספקטיבות",
    "title": "תובנות",
    "heroTitle": "פרספקטивות מנהיגות",
    "selectedEyebrow": "נקודות שיא נבחרות",
    "selectedTitle": "הכרה בולטת",
    "allPressTitle": "כל הכתבות בתקשורת",
    "quotesEyebrow": "בתקשורת",
    "quotesTitle": "הכרה בתעשייה וציטוטים",
    "articlesEyebrow": "פרספקטיבות",
    "articlesTitle": "נקודות מבט ניהוליות",
    "briefsEyebrow": "תקצירי מנהלים",
    "briefsTitle": "רעיונות למנהיגים",
    "briefsLead": "Short, practical perspectives על governance, technology, healthcare ו-company building.",
    "brief1title": "מה IPO משנה",
    "brief1desc": "Operating ו-governance disciplines ש-public-market readiness דורש.",
    "brief1tag": "שוק ההון",
    "brief2title": "מנתונים גenetיים להחלטות קlinיות",
    "brief2desc": "כיצד לבנות מודיעין בריאותי שימושי מבלי לעקוף ראיות או אמון.",
    "brief2tag": "רפואת דיוק",
    "brief3title": "אסטרטגיית AI מעבר לפיילוט",
    "brief3desc": "Framework להפיכת experiments ל-governed enterprise capability.",
    "brief3tag": "בינה מלאכותית",
    "readingEyebrow": "רשימת קריאה",
    "readingTitle": "ספרים שמעצבים חשיבה אסטרטגית",
    "r1title": "The Innovator's Dilemma",
    "r1author": "Clayton M. Christensen",
    "r2title": "Thinking, Fast and Slow",
    "r2author": "Daniel Kahneman",
    "r3title": "The Beginning of Infinity",
    "r3author": "David Deutsch",
    "r4title": "Good Strategy/Bad Strategy",
    "r4author": "Richard Rumelt",
    "r5title": "The Structure of Scientific Revolutions",
    "r5author": "Thomas S. Kuhn",
    "newsletterEyebrow": "הערות מדי פעם",
    "newsletterTitle": "פרספקטיבה מנהלית, ללא רעש",
    "newsletterLead": "Periodic essays ו-brief observations על technology, governance ו-durable company building.",
    "newsletterCta": "הירשמו לעדכונים",
    "lead": "Substantive writing ו-executive briefs.",
    "relatedLead": "Recognition, press coverage ו-patents documented separately.",
    "topicsLead": "הנושאים מבוססים על ניסיון תפעולי מתועד בטכנולוגיה, בריאות ותשתיות."
  },
  "cta": {
    "eyebrow": "בואו נעבוד יחד",
    "title": "בקשת ייעוץ או הזמנת הרצאה",
    "lead": "לתפקידי ייעוץ, משרות בדירקטוריון, הרצאות ושותפויות אסטרטגיות.",
    "button": "יצירת קשר"
  },
  "speaking": {
    "eyebrow": "הרצאות וכנסים",
    "title": "הזמינו את Michael Kofman להרצות",
    "lead": "זמין להרצאות בנושאי מנהיגות ניהולית, אסטרטגיה טכנולוגית, בריאות דיגיטלית, תשתיות נתונים וממשל תאגידי.",
    "topicsEyebrow": "נושאי ההרצאה",
    "topicsTitle": "תחומי מומחיות",
    "topicsLead": "הנושאים מבוססים על עשרות שנות ניסיון בהקמה ובהובלה של חברות בארצות הברית ובאירופה.",
    "processEyebrow": "איך להזמין",
    "processTitle": "תהליך ההזמנה",
    "process1title": "שלחו פנייה",
    "process1desc": "השתמשו בטופס יצירת הקשר או שלחו אימייל ל-mkofman@mkofman.com עם פרטי האירוע, קהל היעד והנושאים המבוקשים.",
    "process2title": "אישור היקף",
    "process2desc": "מתאמים את הפורמט (הרצאת מפתח, פאנל, ישיבת דירקטוריון או שולחן עגול להנהלה) ואת הלוגיסטיקה.",
    "process3title": "יצירת ערך",
    "process3desc": "המצגות מבוססות על תוצאות אמיתיות ממיזמים בתחומי אחסון נתונים, govtech ורפואה מדויקת.",
    "cta": "בקשת הזמנת הרצאה",
    "catalogEyebrow": "נושאי הרצאות",
    "catalogTitle": "שיחות מנהליות לשינוי משמעותי",
    "catalogLead": "Keynotes, ישיבות דירקטוריון ו-briefings מנהיגותיים המותאמים לקהל, לsector ולהקשר ההחלטה.",
    "t1title": "לממשל AI לפני שהוא ימשול בארגון",
    "t1audience": "דירקטוריונים, ועדות ביקורת וסיכונים",
    "t1format": "briefing דירקטוריון או keynote",
    "t2title": "מטרnd טכנולוגי לאסטרטegיה ארגונית",
    "t2audience": "CEOs, צוותים executive ומשקיעים",
    "t2format": "keynote או workshop executive",
    "t3title": "בניית חברות דרך מחזורי שוק",
    "t3audience": "מייסדים, מנהיגי צמיחה ו-private equity",
    "t3format": "fireside chat או keynote",
    "t4title": "רפואת דיוק: הבטחה, הוכחה ואחריות",
    "t4audience": "מנהיגי בריאות, קlinicians ו-innovators",
    "t4format": "keynote ענפי או panel",
    "t5title": "תפקיד הדירקטוריון בסיכון סיiber וטכנולוגי",
    "t5audience": "directors, general counsel ומנהיגי סיכון",
    "t5format": "מפגש חינוך לדירקטוריון",
    "t6title": "הנדסת אמון לתשתית דיגיטלית",
    "t6audience": "ארגוני טכנולוגיה ותשתיות",
    "t6format": "keynote טכני-executive",
    "t7title": "מנהיגות מעבר לגבולות ולתחומים",
    "t7audience": "צוותי מנהיגות גלובליים ואוניברסיטאות",
    "t7format": "keynote או שיחה moderated",
    "t8title": "ממייסד לבונה מוסד",
    "t8audience": "יזמים ומנהלים מהדור הבא",
    "t8format": "workshop או fireside chat"
  },
  "caseStudies": {
    "eyebrow": "מקרי בוחן",
    "title": "בניית חברות שמצליחות להתרחב",
    "lead": "תוצאות נבחרות מהקמה והובלה של חברות בתחומי תשתיות נתונים ובריאות דיגיטלית.",
    "cs1eyebrow": "תשתית נתונים · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "אתגר",
    "cs1challengeText": "לבנות ולהרחיב חברת Data Storage בשוק טכנולוגי שנמצא בתהליך קונסולידציה מהיר.",
    "cs1action": "גישה",
    "cs1actionText": "Michael Kofman ייסד את 9 Net Avenue Inc. בשנת 1996. החברה הפכה במהירות לאחת מחברות ה-Data Storage הגדולות בעולם.",
    "cs1result": "תוצאה",
    "cs1resultText": "נרכשה על ידי Concentric Networks (NASDAQ: CNTX) ב-2000; לאחר מכן חלק מ-XO Communications (NASDAQ: XOXO). המשיך לעבוד עם חברות ציבוריות ותפקידים ברמת דירקטוריון לאחר העסקה.",
    "cs2eyebrow": "בריאות דיגיטלית · 2021 — היום",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "אתגר",
    "cs2challengeText": "להפוך גישות רפואיות מיושנות באמצעות מדע, טכנולוגיות DNA, AI ו-ML דרך פלטפורמה ביו-מתמטית חדשה.",
    "cs2action": "גישה",
    "cs2actionText": "Digital Invest Inc. הוקמה ב-2021. רפואה ביו-מתמטית, אינטליגנציה גנומית ופלטפורמות נתונים clínico.",
    "cs2result": "תוצאה",
    "cs2resultText": "הושגה צמיחה פיננסית עקבית, שמיצבה את החברה בין 10 החברות המובילות בארה״ב ברפואה מדויקת (2023). Digital Invest כוללת פרויקטים חדשניים כמו Human Digital Model, BioMath Life ו-Aero-Ground Robotics Operations Network.",
    "cs3eyebrow": "רובוטיקה ו-UAV · 2026 — הווה",
    "cs3title": "AGRON Inc.",
    "cs3challenge": "אתגר",
    "cs3challengeText": "ארגונים שבונים יכולת UAV ו-Counter-UAS זקוקים להערכה עצמאית, הכשרה מובנית וארכיטקטורה תפעולית — לא לפלטפורמות מבודדות או ניסויים ad hoc.",
    "cs3action": "גישה",
    "cs3actionText": "ייסד AGRON Inc. ב-2026 כדי להוביל את AGRON Ecosystem — ייעוץ, הערכה ואימות, פיתוח יכולות, תשתית הכשרה, תמיכה בפיתוח מוצרים, מערכות geospatial דרך ISDRI ו-AGRON Maritime Intelligence + Security ליachts, marinas ותשתית ימית פרטית.",
    "cs3result": "תוצאה",
    "cs3resultText": "מערכת אקולוגית מקושרת של שירותים מקצועיים — ייעוץ, פיתוח יכולות, תשתית הכשרה, מערכות geospatial ומודיעין ימי דרך AGRON, ISDRI וחברות קשורות.",
    "caseStudiesLead": "הקמה, הרחבה והובלת חברות משלב מוקדם ועד רכישה."
  },
  "mediaKit": {
    "eyebrow": "עיתונות ואירועים",
    "title": "ערכת מדיה",
    "lead": "ביוגרפיות רשמיות, חומרי תמונה ופרטי קשר עבור עיתונות, כנסים ופניות דירקטוריון.",
    "bioEyebrow": "ביוגרפיות",
    "bioTitle": "ביוגרפיות רשמיות",
    "bioShortLabel": "50 מילים",
    "bioShort": "Michael Kofman הוא CEO של Digital Invest Inc., חבר דירקטוריון, יועץ ומייסד חברות בתחומי הטכנולוגיה והבריאות הדיגיטלית בארה״ב ובאירופה.",
    "bioMediumLabel": "150 מילים",
    "bioMedium": "Michael Kofman הוא CEO של Digital Invest Inc. ומשמש כחבר ב-Board of Directors שלה. כאיש חזון טכנולוגי, הוא מוכר בגישתו הדינמית להבנת הצרכים המשתנים של שוק מורכב. כיזם, חבר דירקטוריון ויועץ לחברות ציבוריות ופרטיות, הוא הקים בהצלחה מספר חברות בארצות הברית ובאירופה. תחומי המומחיות שלו כוללים הנהלה בכירה, ניתוח אסטרטגי של טכנולוגיות ושווקים מתפתחים, אבטחת מידע ופרטיות, מחקר, מדע ופיתוח, ניהול והשקעות.",
    "bioLongLabel": "500 מילים",
    "bioLong": "Michael Kofman CEO של Digital Invest Inc. וחבר בדירקטוריון. ייסד 9 Net Avenue Inc., acquired by Concentric Networks 2000, ומוביל Digital Invest ב-biomathematical medicine ו-genomic intelligence. ייסד AGRON Inc. 2026 ל-autonomous aerial-ground operations ו-geospatial systems.",
    "photosEyebrow": "צילום",
    "photosTitle": "תמונות מאושרות",
    "photosLead": "דיוקנאות באיכות גבוהה זמינים לפי בקשה בכתובת mkofman@mkofman.com.",
    "contactEyebrow": "קשרי עיתונות",
    "contactTitle": "פניות מדיה",
    "contactLead": "לראיונות, הזמנות להרצאות ופניות תקשורת.",
    "downloadEyebrow": "הורדה",
    "downloadTitle": "ערכת מדיה בעמוד אחד",
    "downloadLead": "PDF עם ביוגרפיות רשמיות, דיוקן ואיש קשר לעיתונות — מוכן לשיתוף עם מארגנים ועיתונאים.",
    "downloadCta": "הורדת PDF",
    "brandEyebrow": "נכסי מותג",
    "brandTitle": "זהות ושימוש",
    "brandLead": "Approved visual assets ל-editorial, conference ו-partner use.",
    "brandColors": "לוח צבעים רשמי",
    "brandLogo": "לוגו ראשי",
    "brandDownload": "הורדת נכסי מותג"
  },
  "articles": {
    "backLink": "← חזרה ל-Insights",
    "article1date": "פרספקטיבה מנהלית",
    "article1title": "מהנדסה לתשתיות נתונים גלובליות",
    "article1p1": "הקריירה שלי החלה במפעל לבניית ספינות בניקולאייב שבאוקראינה, בפיתוח מערכות משדר-מקלט לווייניות להעברת מידע מסווג לספינות צבאיות. הוכרתי כמהנדס אלקטרוניקה ברמה הגבוהה ביותר - קטגוריה 6 - במפעל של 93,000 עובדים.",
    "article1p2": "בין 1989 ל-1994 ייסדתי והובלתי את Astra Corp, אחת היצרניות הגדולות באירופה של מערכות לוויין דיגיטליות מסוג משדר-מקלט. בין 1994 ל-1996, כ-CEO של Elitan United Inc., סייעתי להרחבת החברה מתשעה עובדים ליותר מ-4,000 עובדים ברחבי העולם.",
    "article1p3": "ב-1996 ייסדתי את 9 Net Avenue Inc., חברת אירוח ותשתית אינטרנט. ב-2000 נרכשה על ידי Concentric Networks (NASDAQ: CNTX) והפכה לאחר מכן לחלק מ-XO Communications (NASDAQ: XOXO).",
    "article1p4": "בין 2001 ל-2019 הובלתי אסטרטגיית טכנולוגיה לתוכניות ממשלתיות, ביטחוניות ולחברות בבעלות מדינה, תוך הובלת יוזמות רחבות היקף בתחומי Big Data, תשתיות מאובטחות ומרכזי נתונים בתפוקה גבוהה בארצות הברית ובאירופה.",
    "article2date": "בריאות דיגיטלית",
    "article2title": "רפואה מדויקת והמפגש בין מדע לטכנולוגיה",
    "article2p1": "אני מאמין עמוקות בפוטנציאל של שילוב מדעי החיים עם החידושים הטכנולוגיים המתקדמים ביותר. ב-Biotechnology Group Inc. ‏(2008-2014) התמקדנו בבדיקות וניתוחי DNA, אוטומציה של תהליכי יצירת פרופילים גנטיים, ומחקר גנטי מקיף של האדם.",
    "article2p2": "תחת הנהגתי, הושקו פרויקטים מוצלחים של בדיקות גנטיות באוקראינה, רוסיה ומדינות הבלטיות. בשיתוף עם Harvard Medical School ו-Stanford Biomath מילאתי תפקיד מרכזי בפיתוח דוחות גנטיים מובנים לרופאים ולמטופלים.",
    "article2p3": "עם Digital Invest Inc., שהוקמה ב-2021, עובדים ברפואה ביו-מתמטית — מדע, טכנולוגיות DNA, AI ו-ML באינטליגנציה clínico. Healthcare Tech Outlook (2023).",
    "article2p4": "Digital Invest כוללת פרויקטים חדשניים מגוונים, בהם Human Digital Model, ‏BioMath Life ו-Aero-Ground Robotics Operations Network - וכל אחד מהם מקדם את שילוב מדעי הנתונים עם מדעי החיים."
  },
  "privacy": {
    "eyebrow": "משפטי",
    "title": "מדיניות פרטיות",
    "lead": "כיצד mkofman.com מטפל במידע בעת ביקור באתר או שליחת הודעה.",
    "updated": "עודכן: יולי 2026",
    "s1title": "מידע שאנו אוספים",
    "s1text": "בשליחת טופס אנו מקבלים את השדות שמילאת. אם אנליטיקה מופעלת — נתוני שימוש אנונימיים.",
    "s2title": "שימוש במידע",
    "s2text": "למענה לפניות ושיפור האתר. איננו מוכרים מידע אישי.",
    "s3title": "שירותי צד שלישי",
    "s3text": "טפסים עשויים להיות מעובדים ב-Formspree. אנליטיקה — Plausible או Google Analytics.",
    "s4title": "זכויותיך",
    "s4text": "בקשת גישה, תיקון או מחיקה: mkofman@mkofman.com.",
    "s5title": "יצירת קשר",
    "s5text": "שאלות על מדיניות זו: mkofman@mkofman.com"
  },
  "board": {
    "eyebrow": "ייעוץ",
    "title": "ייעוץ",
    "body": "פתוח לשיחות ייעוץ אסטרטגי עם ארגוני טכנולוגיה, בריאות ותשתיות — על בסיס ניסיון תפעולי ישיר בבניית חברות, אסטרטגיה טכנולוגית וביצוע בשלבי צמיחה.",
    "contactLink": "לפניות ייעוץ",
    "lead": "Board & Advisory"
  },
  "thesis": {
    "eyebrow": "תזת מנהיגות",
    "title": "לבנות לטווח ארוך. להחליט בהווה.",
    "lead": "טכנולוגיה משתנה במהירות; חובות המנהיגות — לא. ארגונים מתמשכים מאחדים שאפתנות עם משמעת, ראיות ואחריות.",
    "believeEyebrow": "במה אני מאמין",
    "believeTitle": "שבעה עקרונות לארגונים מתמשכים",
    "b1title": "אסטרטegיה חייבת לייצר בחירות",
    "b1text": "אסטרטegיה אינה קטalog של שאיפות. היא מגדירה היכן להת конкуруents, אילו יכולות לבנות, מה לא לרדוף וכיצד יימדד הצלחה.",
    "b2title": "טכנולוגיה היא סוגיית ממשל",
    "b2text": "דירקטוריונים חייבים להבין כיצד טכנולוגיה יוצרת ערך, מרכזת סיכון ומשנה אחריות. העברת כל שאלה טכנית לאחרים היא בעצמה החלטה.",
    "b3title": "ראיות צריכות לגבור על התלהבות",
    "b3text": "conviction חשוב, אך שווקים, מערכות ומדע חייבים להיבחן. מנהיגים יוצרים מנגנונים שחושפים הנחות לפני לקוחות או רגulators.",
    "b4title": "ארכיטקטורה מעצבת את הארגון",
    "b4text": "ארכיטקטורה טכנית קובעת מהירות, חוסן, אבטחה ואפשרויות עתיד. קיצורי דרך הופכים לאילוצים מוסדיים long after שההקשר המקורי נעלם.",
    "b5title": "אמון הוא תשתית תפעולית",
    "b5text": "אמון נבנה דרך התחייבויות ברורות, ביצוע אמין, פרaktikות נתונים אחראיות ותקשורת ישירה כשהתנאים משתנים.",
    "b6title": "הון חייב לעקוב אחר יכולת",
    "b6text": "השקעות צמיחה צריכות לחזק יכולות differentiated וביקוש measurable, לא להחליף הוצאות בהבנת product-market.",
    "b7title": "מנהיגים מתכננים את יורשיהם",
    "b7text": "המנהיגים החזקים ביותר בונים מערכות, כישרונות ואיכות החלטה שנשארים מעבר למעורבותם.",
    "rejectEyebrow": "מה שאני דוחה",
    "rejectTitle": "שלוש אשליות יקרות",
    "r1title": "תיאטרון חדשנות",
    "r1text": "הכרזות, pilots ושפה אופנתית לא שווים capability. חדשנות חייבת לשפר תוצאה שחשובה.",
    "r2title": "צמיחה ללא ממשל",
    "r2text": "קנה מידה מגביר חולשות לא פתורות. controls, culture ו-accountability צריכים להתבגר לפני שcomplexity הופכת correction ליקר.",
    "r3title": "ודאות כוזבת",
    "r3text": "confidence מנהלית לא צריכה למחוק uncertainty. החלטות חזקות הופכות assumptions ל-visible ושומרות options כשfacts משתנים.",
    "horizonEyebrow": "האופק",
    "horizonTitle": "היתרון הבא הוא אינטגרציה אחראית",
    "horizonText": "ההזדמנות המכרעת אינה technology בודדת. זו אינטegration ממושמעת של AI, מערכות נתונים מתקדמות, biology ו-automation במוסדות שאנשים יכולים לסמוך עליהם."
  },
  "press": {
    "eyebrow": "עיתונות ומדיה",
    "title": "כיסוי נבחר",
    "lead": "ארכיון תמציתי של הכרה ודיווחים מצד שלישי בטכנולוגיה, יזמות ורפואת דיוק.",
    "archiveEyebrow": "ארכיון",
    "y2023type": "הכרה ענפית",
    "y2023title": "Top 10 Precision Medicine Companies",
    "y2023desc": "Healthcare Tech Outlook recognized Digital Invest Inc.",
    "y2023link": "צפייה בכתבה",
    "y2001type": "פרס מנהלים",
    "y2001title": "יזם השנה",
    "y2001desc": "הכרה מ-Entrepreneur Magazine.",
    "y2001link": "צפייה בארכיון",
    "y1999type": "הכרה биográfית",
    "y1999title": "Who's Who in America",
    "y1999desc": "Recognition beginning in 1999.",
    "clipEyebrow": "מהארכיון",
    "clipMeta": "Industry Feature · DataPeer Inc.",
    "clipTitle": "State of the Storage Industry",
    "clipLead": "ראיון מוקדם עם Michael Kofman כ-Founder, Chairman ו-CEO של DataPeer Inc. — על סיבים אופtיים, שידור לווייני, SAN ושוק האחסון המתפתח.",
    "clipBody": "הכתבה מציינת הכרה כ«יזם השנה» מ-Entrepreneur Magazine (2001) ואת גישת DataPeer לאחסון קריטי, iSCSI והמשכיות עסקית.",
    "clipOpen": "פתיחת סריקה מלאה →",
    "y2000type": "ראיון",
    "y2000title": "State of the Storage Industry",
    "y2000desc": "ראיון מובלט עם Michael Kofman כ-Founder, Chairman ו-CEO של DataPeer Inc. על רשתות אחסון, iSCSI והמשכיות עסקית."
  },
  "ip": {
    "eyebrow": "קניין רוחני",
    "title": "רעיונות יישומיים, מתועדים",
    "lead": "Selected patents, publications ו-research programs, connecting engineering rigor עם practical business ו-societal outcomes.",
    "patentEyebrow": "פטנטים",
    "patentTitle": "המצאות מוגנות",
    "patentIntro": "Patent work reflects sustained focus על systems improving collection, movement, protection ו-interpretation of information.",
    "publicationsEyebrow": "פרסומים",
    "publicationsTitle": "כתיבה טכנית ומנהלית",
    "publicationsIntro": "Published work translates complex technical subjects ל-methods, frameworks ו-decisions useful ל-practitioners ו-leaders.",
    "researchEyebrow": "מחקר",
    "researchTitle": "תוכניות בין-תחומיות",
    "researchIntro": "Research initiatives span secure communications, predictive analytics, genetic interpretation, human digital modeling ו-autonomous systems."
  },
  "testimonials": {
    "t1quote": "Michael משלב דיוק של engineer עם judgment של CEO מנוסה. הוא שואל את השאלות שמשפרות decision.",
    "t1name": "עמית דירקטוריון",
    "t1role": "חברת טכנולוגיה ציבורית",
    "t2quote": "היכולת שלו connect science, product, governance ו-commercial reality מביאה uncommon clarity ליוזמות מורכבות.",
    "t2name": "שותף אסטרטגי",
    "t2role": "מגזר בריאות דיגיטלית",
    "t3quote": "Michael direct, thoughtful ו-focused על durable value. הוא עוזר ל-leadership teams לראות opportunity ו-obligation.",
    "t3name": "שותף executive",
    "t3role": "תשתית גлобלית"
  },
  "deck": {
    "title": "Michael Kofman",
    "subtitle": "מנהיג טכנולוגי · מייסד · יועץ",
    "thesis": "טכנולוגיה, עסקים והשקעות בתשתיות, מדעי החיים ומערכות אוטונומיות.",
    "contact": "דיון סודי: צרו קשר עם Michael Kofman דרך mkofman.com"
  },
  "briefIpo": {
    "title": "מה IPO משנה",
    "desc": "שווקים ציבוריים לא רק משנים capital structure; הם משנים operating contract.",
    "p1": "IPO מתואר לעיתים כ-financing event. בפועל, institutional transition. forecasting, controls, disclosure, governance ו-executive communication חייבים repeatable לפני listing.",
    "p2": "readiness מתחיל ב-decision quality. management צריך reliable metrics, clear ownership ו-operating cadence. חברה שלא reconciling internal narrative ת struggle עם external one.",
    "p3": "תפקיד board משתנה. directors חייבים balance growth ו-oversight, understand material risks, ensure incentives support durable value.",
    "p4": "strongest public companies שומרות entrepreneurial speed עם institutional discipline. objective — trustworthy execution ברמת accountability גבוהה יותר.",
    "eyebrow": "תקציר מנהלים"
  },
  "briefGenetic": {
    "title": "מנתונים גenetיים להחלטות קlinיות",
    "desc": "ערך המידע הגénomi תלוי בפרשנות, ראיות ואינטגרציה אחראית לטיפול.",
    "p1": "נתונים גenetיים abundant; clinically useful meaning scarce. תוצאה הופכת לערכית רק כשמinterpreted בהקשר, connected ל-validated evidence ו-presented בצורה שתומכת בהחלטה אמיתית.",
    "p2": "translation זה דורש collaboration בין molecular biology, medicine, statistics, software engineering ו-patient communication. חולשה בשכבה כלשהי עלולה להפוך technical sophistication ל-clinical confusion.",
    "p3": "privacy ו-consent הם architectural requirements, לא legal footnotes. מערכות חייבות להגביל unnecessary exposure, להפוך data provenance visible ולשמר patient agency.",
    "p4": "רפואת דיוק תתקדם דרך אינטגרציה מדודה: ראיות טובות יותר, מודלים שקופים, תהליכי עבודה מתואמים ותוצאות שרופאים ומטופלים יכולים להעריך. אמון הוא חלק מהמוצר.",
    "eyebrow": "תקציר מנהלים"
  },
  "briefAi": {
    "title": "אסטרטגיית AI מעבר לפיילוט",
    "desc": "בינה מלאכותית ארגונית יוצרת ערך כשבעלות, נתונים, תהליכי עבודה וממשל מתבגרים יחד.",
    "p1": "הרבה יוזמות AI מתחילות בהדגמה משכנעת ונתקעות לפני production. החסר לעיתים רחוקות הוא המודל בלבד. ערך בר-קיימא דורש תוצאה עסקית מוגדרת, בעלים אחראי, נתונים אמינים ו-workflow שאנשים באמת משתמשים בו.",
    "p2": "מנהיגים צריכים להבחין בין automation, prediction ו-decision support. לכל אחד דרישות שונות לדיוק, explainability, ביקורת אנושית וסיכון. תבנית governance אחת לא מתאימה לכל use case.",
    "p3": "מדידה חייבת לכלול יותר מביצועים טכניים. adoption, cycle time, error rates, customer impact, security exposure ו-cost of supervision קובעים אם יכולת AI sound כלכלית ומוסדית.",
    "p4": "הגישה המנצחת היא managed portfolio: scale proven use cases, stop weak ones early, maintain explicit boundaries ל-high-consequence decisions. AI strategy היא ultimately operating strategy.",
    "eyebrow": "תקציר מנהלים"
  }
};
