window.__LANG_uk = {
  "ui": {
    "toggleTheme": "Світла/темна тема",
    "selectLanguage": "Обрати мову",
    "messageSent": "Повідомлення надіслано",
    "sendMessage": "Надіслати",
    "toggleNav": "Відкрити меню",
    "sending": "Надсилання…",
    "formError": "Не вдалося надіслати. Будь ласка, напишіть напряму на email.",
    "present": "дотепер"
  },
  "nav": {
    "home": "Головна",
    "about": "Біографія",
    "ventures": "Компанії",
    "career": "Хроніка",
    "recognition": "Визнання",
    "contact": "Контакти",
    "consulting": "Консалтинг",
    "insights": "Інсайти",
    "speaking": "Виступи",
    "caseStudies": "Кейси",
    "mediaKit": "Медіа-кит",
    "groupMain": "Основне",
    "groupServices": "Послуги",
    "groupWork": "Робота",
    "board": "Консалтинг",
    "thesis": "Тезис лідерства",
    "press": "Пресса",
    "briefIpo": "Бриф: IPO",
    "briefGenetic": "Бриф: генетичні дані",
    "briefAi": "Бриф: стратегія ШІ",
    "articleInfra": "Інфраструктура даних",
    "articleHealth": "Прецизійна медицина",
    "ip": "Інтелектуальна власність"
  },
  "footer": {
    "navigation": "Навігація",
    "ventures": "Компанії",
    "connect": "Зв'язок",
    "desc": "Технологічний executive, засновник і радник рад директорів.",
    "copyright": "© {year} Michael Kofman. Усі права захищені.",
    "writeTitle": "Напишіть мені",
    "writeEmail": "Ваш email",
    "writeMessage": "Ваше повідомлення",
    "writeSend": "Надіслати",
    "writeSuccess": "Дякуємо — ваше повідомлення надіслано.",
    "more": "Більше",
    "privacy": "Конфіденційність"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — Технологічний executive",
      "description": "Технологічний executive, засновник і радник — інфраструктура, life sciences та автономні системи."
    },
    "about": {
      "title": "Біографія — Michael Kofman",
      "description": "Біографія Michael Kofman — CEO Digital Invest Inc., засновник AGRON Inc."
    },
    "ventures": {
      "title": "Компанії — Michael Kofman",
      "description": "Компанії, засновані та очолювані Михайлом Кофманом — від Digital Invest Inc. до 9 Net Avenue Inc. — трансформуючі бізнес у технологіях і охороні здоров'я."
    },
    "career": {
      "title": "Хроніка — Michael Kofman",
      "description": "Професійний record: інженерія, інфраструктура, публічні ринки, life sciences та автономні системи."
    },
    "recognition": {
      "title": "Визнання — Michael Kofman",
      "description": "Нагороди та визнання Михайла Кофмана — Підприємець року, Who's Who, патенти та галузеві відзнаки."
    },
    "contact": {
      "title": "Контакти — Michael Kofman",
      "description": "Зв'язатися з Михайлом Кофманом — CEO Digital Invest Inc. Для виступів, консультацій і ділових запитів."
    },
    "consulting": {
      "title": "Консалтинг — Michael Kofman",
      "description": "Advisory-ролі, ради директорів, виступи та стратегічні партнерства з Michael Kofman."
    },
    "insights": {
      "title": "Інсайти — Michael Kofman",
      "description": "Оригінальні тексти та executive briefs Michael Kofman."
    },
    "speaking": {
      "title": "Виступи — Michael Kofman",
      "description": "Запросіть Michael Kofman виступити про executive-лідерство, технологічну стратегію, digital health і корпоративне управління."
    },
    "caseStudies": {
      "title": "Кейси — Michael Kofman",
      "description": "Кейси з кар'єри Michael Kofman — 9 Net Avenue Inc. та Digital Invest Inc."
    },
    "mediaKit": {
      "title": "Медіа-кит — Michael Kofman",
      "description": "Офіційні біографії, фотографії та контактна інформація для преси й організаторів подій."
    },
    "article1": {
      "title": "Від інженерії до глобальної інфраструктури — Michael Kofman",
      "description": "Michael Kofman про шлях від супутникової інженерії до заснування глобальних компаній у сфері інфраструктури даних."
    },
    "article2": {
      "title": "Прецизійна медицина і технології — Michael Kofman",
      "description": "Michael Kofman про поєднання наук про життя з AI, ML і ДНК-технологіями в сучасній медицині."
    },
    "board": {
      "title": "Консалтинг — Michael Kofman",
      "description": "Стратегічні advisory-діалоги з технологічними, медичними та інфраструктурними організаціями."
    },
    "thesis": {
      "title": "Тезис лідерства — Michael Kofman",
      "description": "Принципи Michael Kofman щодо створення стійких компаній, управління технологіями та лідерства в умовах значущих змін."
    },
    "press": {
      "title": "Архів преси — Michael Kofman",
      "description": "Selected press coverage, awards і media references кар'єри Michael Kofman у technology і entrepreneurship."
    },
    "ip": {
      "title": "Інтелектуальна власність — Michael Kofman",
      "description": "Патенти, публікації та applied research Michael Kofman у computing, communications, data і digital health."
    },
    "briefIpo": {
      "title": "Що змінює IPO — Michael Kofman",
      "description": "Executive brief про operating discipline, governance і accountability до і після IPO."
    },
    "briefGenetic": {
      "title": "Від генетичних даних до клінічних рішень — Michael Kofman",
      "description": "Executive brief про перетворення геномної інформації на responsible, useful, scalable clinical intelligence."
    },
    "briefAi": {
      "title": "Стратегія ШІ за межами пілота — Michael Kofman",
      "description": "Executive brief про перехід від AI-експериментів до governed, measurable enterprise capability."
    },
    "privacy": {
      "title": "Політика конфіденційності — Michael Kofman",
      "description": "Політика конфіденційності mkofman.com — форми та аналітика."
    },
    "deck": {
      "title": "Виконавчий огляд — Michael Kofman",
      "description": "Private executive overview для qualified introductions."
    }
  },
  "home": {
    "heroEyebrow": "Офіційний сайт Michael Kofman",
    "heroTitle1": "Будувати на довгі роки.",
    "heroTitle2": "Керувати з розумінням.",
    "heroCta": "Дізнатися історію",
    "heroAlt": "Michael Kofman",
    "quote1text": "Digital Invest Inc. — серед провідних компаній США в precision medicine та digital health.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "Підприємець року — за лідерство та проривні досягнення в платформних інноваціях і інфраструктурі.",
    "quote2author": "Entrepreneur Magazine · 2001",
    "quote3text": "Digital Invest Inc. — серед 10 найкращих компаній США в precision medicine та digital health.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "Інженерна точність і бізнес-стратегія — від супутникових систем до інфраструктури на $",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "Michael Kofman",
    "aboutTitle": "Компанії, розраховані на тривалий час",
    "aboutLead1": "CEO Digital Invest Inc. і засновник AGRON Inc. Заснував і очолював компанії в США та Європі.",
    "aboutLead2": "Від 9 Net Avenue (пік $",
    "aboutLink": "Повна біографія",
    "expertiseEyebrow": "Напрямки",
    "expertiseTitle": "Executive-лідерство в різних галузях",
    "expertiseLead": "Чотири десятиліття створення компаній, консультування та інвестицій в інфраструктуру, охорону здоров'я та робототехніку.",
    "exp1title": "CEO і засновник",
    "exp1desc": "Заснував і керував кількома технологічними компаніями в США та Європі.",
    "exp1link": "Компанії →",
    "exp2title": "Технологічний архітектор",
    "exp2desc": "Проєктував захищені комунікації, системи предиктивної аналітики та платформи інтеграції даних національного рівня для державного, військового та телекомунікаційного секторів.",
    "exp2link": "Кар'єра →",
    "exp3title": "Цифрове здоров'я",
    "exp3desc": "Очолює трансформацію медицини за допомогою ШІ, ML і ДНК-технологій. Співпрацював із Harvard Medical School та Stanford Biomath над генетичними звітами.",
    "exp3link": "Digital Invest →",
    "exp4title": "Радник ради директорів",
    "exp4desc": "У входить до рад директорів і консультує публічні та приватні компанії щодо стратегічного розвитку, корпоративного управління та технологічного зростання.",
    "exp4link": "Консалтинг →",
    "stat1": "Років лідерства",
    "stat2": "Заснованих компаній",
    "stat3": "Пікова капіталізація",
    "stat4": "Масштабованих співробітників",
    "recEyebrow": "Визнання",
    "recTitle": "Вибрані нагороди",
    "recLead": "Галузеві нагороди та визнання в підприємництві, медицині та інженерії.",
    "award1title": "Підприємець року",
    "award1desc": "Entrepreneur Magazine · 2001",
    "award2title": "Топ-10 precision medicine",
    "award2desc": "Digital Invest Inc. — U.S., 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "Визнання та преса →",
    "heroSub": "Технології, бізнес і інвестиції в інфраструктуру, life sciences та автономні системи.",
    "primaryCta": "Запросити консультацію",
    "secondaryCta": "Переглянути кейси",
    "featuredEyebrow": "Згадки в медіа",
    "caseStudiesEyebrow": "Підтверджені результати",
    "caseStudiesTitle": "Кейси",
    "caseStudiesLead": "Заснування, масштабування та керівництво компаніями від старту до угод M&A та IPO.",
    "caseStudiesLink": "Переглянути всі кейси →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "Побудовано одну з найбільших у світі компаній Data Storage, придбану при піковій ринковій вартості 19,5 млрд доларів.",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "Засновано та масштабовано від старту до IPO — Top 10 компаній прецизійної медицини у США, 2023.",
    "boardCtaEyebrow": "Ради директорів і консультування",
    "boardCtaTitle": "Досвід для рішень, що визначають майбутнє компанії",
    "boardCtaLead": "Незалежний погляд для рад і лідерів, які управляють технологіями, корпоративним управлінням, трансформацією та зростанням.",
    "boardCtaBtn": "Докладніше про роботу з радами",
    "testimonialsEyebrow": "Авторитетний погляд",
    "testimonialsTitle": "Що цінують колеги",
    "videoEyebrow": "Погляд керівника",
    "videoTitle": "Лідерство на перетині технологій і бізнесу",
    "videoLead": "Стисле знайомство з принципами, досвідом і довгостроковим підходом, що лежать в основі роботи Майкла Кофмана.",
    "videoCta": "Читати Leadership Thesis →",
    "cs3title": "AGRON Inc.",
    "cs3desc": "Заснована у 2026 році — екосистема AGRON для БПЛА, геопространствених систем і морської розвідки.",
    "heroName": "Michael Kofman",
    "heroRole": "Технологічний executive · Засновник · Радник",
    "introText": "Michael Kofman — технологічний executive і засновник компаній. Його робота охоплює супутникову інженерію, інтернет-інфраструктуру, публічні технологічні компанії та life sciences. Він заснував 9 Net Avenue Inc., придбану Concentric Networks у 2000 році. CEO Digital Invest Inc. у біоматематичній медицині та геномній аналітиці; засновник AGRON Inc. в автономних повітряно-наземних операціях і геопросторових системах. Бере участь у радах директорів і консультує в технологіях, охороні здоров'я та інфраструктурі.",
    "introLink": "Повна біографія →",
    "currentEyebrow": "Поточна робота",
    "currentTitle": "Поточний фокус",
    "currentDiTitle": "Digital Invest Inc.",
    "currentDiDesc": "Біоматематична медицина, геномні дані та клінічна аналітика — застосування AI, ML і DNA-технологій для відповідальних медичних результатів.",
    "currentDiLink": "Ventures →",
    "currentAgTitle": "AGRON Inc.",
    "currentAgDesc": "Автономні повітряно-наземні операції, розробка UAV, геопросторові системи та морська intelligence-інфраструктура.",
    "currentAgLink": "agron1.com →",
    "careerEyebrow": "Вибраний record",
    "careerTitle": "Преемственність технологічних періодів",
    "careerLead": "Selected milestones від engineering через current work в autonomous systems.",
    "career1title": "Інженерія та комунікації",
    "career1desc": "Супутникові transceiver systems, digital communications і раннє engineering leadership.",
    "career2title": "Інтернет та інфраструктура",
    "career2desc": "Інтернет-інфраструктура, дата-центри, storage і telecommunications at scale.",
    "career3title": "Технологічні компанії та публічні ринки",
    "career3desc": "Створення компаній, угоди M&A та досвід публічних компаній, включно з 9 Net Avenue Inc.",
    "career4title": "Науки про життя та дані про людину",
    "career4desc": "Biotechnology, genetic data, precision medicine і health intelligence platforms.",
    "career5title": "Автономні системи",
    "career5desc": "Aerial-ground robotics, UAV operations і geospatial infrastructure.",
    "careerLink": "Хроніка →",
    "perspectivesEyebrow": "Перспективи",
    "perspectivesTitle": "Обрані тексти",
    "perspectivesLink": "Усі інсайти →",
    "footerHomeDesc": "Технологічний executive, засновник і радник.",
    "activeSitesLink": "Усі активні сайти →"
  },
  "about": {
    "eyebrow": "Про Michael Kofman",
    "title": "Три десятиліття досвіду",
    "lead": "Технологічний executive, засновник і радник.",
    "glance": "Коротко",
    "role": "Поточна роль",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "Локація",
    "locationVal": "Charlotte, North Carolina",
    "education": "Освіта",
    "educationVal": "Доктор технічних наук\nPh.D. з інформаційних технологій\nМагістерські ступені — електроніка, цифрові супутникові системи та економіка",
    "university": "Університет",
    "universityVal": "Український державний морський технічний університет",
    "languages": "Мови",
    "languagesVal": "Англійська, російська, українська",
    "contactLabel": "Контакти",
    "principlesEyebrow": "Операційні принципи",
    "principlesTitle": "Як я керую",
    "p1title": "Зрозуміти систему",
    "p1text": "Перш ніж змінювати організацію, потрібно зрозуміти її стимули, архітектуру, обмеження та джерела довіри.",
    "p2title": "Зробити відповідальність явною",
    "p2text": "Чітка відповідальність і вимірювані результати перетворюють стратегію з презентації на операційну реальність.",
    "p3title": "Залишати сильніші institution",
    "p3text": "Лідerstvo має примножувати spromожності, розвиваючи людей, покращуючи rішення та будуючи системи, які переживають зміну лідerів.",
    "archiveEyebrow": "З архіву",
    "archiveTitle": "З архіву",
    "archiveLead": "Автентичні матеріали про створення компаній, інфраструктуру та лідерство.",
    "photo9netTitle": "9 Net Avenue",
    "photo9netCaption": "Засновник і CEO — компанія хостингу та інтернет-інфраструктури, придбана Concentric Networks у 2000 році.",
    "photoServerTitle": "Інфраструктура даних",
    "photoServerCaption": "Середовища зберігання, мереж і серверів у DataPeer та пов’язаних компаніях.",
    "photoTodayTitle": "Сьогодні",
    "photoTodayCaption": "Digital Invest Inc., AGRON Inc. та advisory-робота.",
    "secIntroTitle": "Вступ",
    "secTechTitle": "Технології та інфраструктура",
    "secBusinessTitle": "Бізнес",
    "secCurrentTitle": "Поточна робота",
    "secBackgroundTitle": "Освіта та background",
    "recordLink": "Хроніка →",
    "secBackgroundP1": "Doctor of Technical Sciences і Ph.D. in Information Technology. Автор технічних робіт; патент digital satellite HDTV, придбаний Sony.",
    "bioP1": "Michael Kofman — технологічний executive, засновник і радник. CEO Digital Invest Inc. і засновник AGRON Inc.; досвід у супутниковій інженерії, інтернет-інфраструктурі, публічних технологічних компаніях і life sciences у США та Європі.",
    "bioP2": "Як підприємець, член рад директорів і радник публічних і приватних компаній, Michael Kofman заснував кілька компаній у США та Європі. У 2026 році він заснув AGRON Inc. для розвитку Aerial-Ground Robotics Operations Network. Також створив Digital Invest — компанію в біоматематичній сфері, що трансформує медицину за допомогою науки, ДНК-технологій, ШІ та ML.",
    "secBioTitle": "Прецизійна медицина та біотехнології",
    "secBioP1": "До Digital Invest він відіграв значну роль у успіху Biotechnology Group Inc. (2008–2014) — компанії, що займається ДНК-тестуванням і аналізом, автоматизацією процесів створення генетичних профілів і комплексними дослідженнями людської генетики. Пан Кофман твердо вірить у потенціал поєднання наук про життя з новітніми технологічними досягненнями.",
    "secBioP2": "Під його керівництвом в Україні, Росії та країнах Балтії були запущені успішні проєкти генетичного тестування. Цей унікальний досвід постійно збагачується сучасними технологіями та новим обладнанням. У співпраці з Harvard Medical School і Stanford Biomath пан Кофман відіграв ключову роль у розробці зрозумілих генетичних звітів для лікарів і пацієнтів. Цей інноваційний підхід широко впроваджений провідними лабораторіями в США та за кордоном.",
    "secTechP1": "Інженерна підготовка: супутникові трансивери на Nikolaev Shipbuilding Plant і цифрові комунікації в Astra Corp.",
    "secTechP2": "У 2006 році пан Кофман заснував XIBI Group Inc. — технологічну компанію, до ради директорів якої він увійшов. Американська компанія спеціалізується на зберіганні даних і керуванні big data для великих комерційних та державних організацій.",
    "secTechP3": "З 2000 по 2004 рік пан Кофман керував DataPeer Inc. — компанією з управління та зберігання даних, що пропонувала широкий спектр послуг зі зберігання інформації для малого та середнього бізнесу. У DataPeer він розробив унікальні технологічні рішення, що прискорили відстеження інформації та спростили доступ до даних для кінцевих користувачів і державних установ у всьому світі.",
    "secTechP4": "У 1996 році пан Кофман заснував 9 Net Avenue Inc. Компанія швидко стала одним із найбільших хостинг-провайдерів у світі. До 2000 року 9 Net Avenue була придбана Concentric Networks (NASDAQ: CNTX), а потім XO Communications (NASDAQ: XOXO), досягнувши пікової ринкової капіталізації в $2000",
    "secPost9NetP1": "Після придбання 9 Net Avenue пан Кофман отримав величезний досвід роботи в публічних компаніях, участі в радах директорів і прийняття стратегічних рішень на найвищому executive-рівні.",
    "secEarlyTitle": "Ранній етап кар'єри та інженерія",
    "secEarlyP1": "З 1994 по 1996 рік пан Кофман обіймав посади CEO і директора з інформаційних технологій у Elitan United Inc. — IT-компанії з Массачусетсу, що надавала комплексні стратегії та технологічні послуги провідним світовим організаціям. Він відіграв ключову роль у розробці та керуванні масштабованою інфраструктурою, забезпечивши зростання компанії з дев'яти до понад 4 000 співробітників у всьому світі.",
    "secEarlyP2": "З 1989 по 1994 рік він був засновником і CEO Astra Corp — одного з найбільших у Європі виробників цифрових супутникових трансиверних систем, що отримав міжнародне визнання в галузі супутникових пристроїв. Його обов'язки включали дослідження, розробку операційних систем, мережеві програмні застосунки та загальну технічну стратегію.",
    "secEarlyP3": "З 1984 по 1989 рік пан Кофман працював на суднобудівному заводі в Миколаєві, Україна, де активно брав участь у розробці та створенні супутникових трансиверних систем для передачі секретної інформації на військові кораблі та назад. Він був визнаний інженером-електроніком найвищого рівня, отримавши 6-ту категорію — найвище визнання на заводі, де працювали 93 тисячі людей.",
    "secResearchTitle": "Дослідження та патенти",
    "secResearchP1": "Майкл Кофман — автор технічних праць, присвячених супутниковим і оптичним системам передачі даних. Він також отримав патент у галузі цифрових супутникових систем телебачення високої чіткості (HDTV), згодом придбаний Sony.",
    "secAgronTitle": "Робототехніка, БПЛА та морська розвідка",
    "secAgronP1": "У 2026 році пан Kofman заснув AGRON Inc. для побудови екосистеми AGRON — корпоративної архітектури повітряної та наземної робототехніки, керованого виконання місій і мережевої інфраструктури. Екосистема включає консалтинг, оцінку, розвиток компетенцій і навчання для організацій БПЛА та Counter-UAS, а також морську розвідку та безпеку на agron1.com.",
    "secBusinessP1": "Заснував і очолював технологічні компанії, зокрема 9 Net Avenue Inc., DataPeer Inc., XIBI Group Inc. і Elitan United Inc. Повна хронологія — у The Record.",
    "secCurrentP1": "CEO Digital Invest Inc. у біоматематичній медицині та геномній аналітиці. Засновник AGRON Inc. в автономних повітряно-наземних операціях і геопросторових системах."
  },
  "ventures": {
    "eyebrow": "Портфель компаній",
    "title": "Засновані та очолювані компанії",
    "lead": "Від precision medicine і робототехніки до глобальної data infrastructure — створення, масштабування та керівництво в США та Європі.",
    "ecosystemEyebrow": "Екосистема проєктів",
    "ecosystemTitle": "Компанії на передньому краї технологій",
    "ecosystemLead": "Портфель об'єднують повторювані теми: надійні дані, інтелектуальна інфраструктура, здоров'я людини та масштабовані системи.",
    "statusActive": "Активно",
    "statusExited": "Exit",
    "statusLegacy": "Спадщина",
    "v1lesson": "Урок: інфраструктура перемагає, коли надійність, економіка та довіра клієнтів зростають разом.",
    "v2lesson": "Урок: прецизійна медицина вимагає однакової дисципліни в науці, ПЗ, конфіденційності та клінічній користі.",
    "v3lesson": "Урок: автономія створює цінність лише коли sensing, комунікації та людський нагляд утворюють одну стійку систему.",
    "v5lesson": "Урок: масштаб у інфраструктурі досягається операційною досконалістю задовго до exit.",
    "currentEyebrow": "Поточне",
    "historyEyebrow": "Вибрана історія",
    "v2highlight": "Harvard Medical School і Stanford Biomath — співпраця з генетичними звітами",
    "activeSitesEyebrow": "Активні проєкти",
    "activeSitesTitle": "Активні сайти",
    "activeSitesLead": "Активні сайти поточних компаній і портфельних ініціатив.",
    "activeSitesMeta": "10 активних сайтів · натисніть на картку для переходу",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "У 2026 році заснув AGRON Inc. для розвитку екосистеми AGRON — Aerial-Ground Robotics Operations Network: консалтинг і оцінка БПЛА та Counter-UAS, розвиток компетенцій, навчальна інфраструктура, валідація продуктів, геопросторові системи (ISDRI) та AGRON Maritime Intelligence + Security для яхт, марин і приватної морської інфраструктури.",
    "v0role": "Засновник",
    "v0year": "2026 — дотепер",
    "v2role": "CEO і CTO",
    "v2year": "2008 — 2014",
    "v3year": "2006 — 2011",
    "v4year": "2000 — 2004",
    "v5highlight": "Придбана · Пікова вартість $2000",
    "v5p1": "Побудував одну з найбільших хостинг-компаній у світі. До 2000 року придбана Concentric Networks (NASDAQ: CNTX), потім XO Communications (NASDAQ: XOXO), з піковою ринковою капіталізацією $2000",
    "v5year": "1996 — 2000",
    "v6year": "1994 — 1996",
    "v7year": "1989 — 1994",
    "v8year": "1984 — 1989",
    "v1highlight": "Топ-10 компаній precision medicine у США — 2023",
    "v1p1": "Біоматематична медицина, геномні дані та кlinічна аналітика — ШІ, ML і ДНК-технології в кlinічних та дослідницьких процесах.",
    "v1role": "Засновник і CEO · Член ради директорів",
    "v1year": "2021 — дотепер",
    "v2p1": "ДНК-тестування й аналіз, автоматизація генетичного профілювання та комплексні дослідження людської генетики. Ініціював проєкти генетичного тестування в Україні, Росії та країнах Балтії.",
    "v2p2": "Співпрацював з Harvard Medical School і Stanford Biomath над генетичними звітами, впровадженими провідними лабораторіями у всьому світі.",
    "v3highlight": "Корпоративні та державні data-рішення",
    "v3p1": "Зберігання даних і керування big data для великих комерційних та державних організацій. Вивів компанію в число надійних постачальників корпоративних data-рішень.",
    "v3role": "Засновник і CEO · Рада директорів",
    "v4highlight": "Глобальна платформа управління даними",
    "v4p1": "Управління та зберігання даних для малого та середнього бізнесу. Розробив рішення для прискореного відстеження інформації та спрощеного доступу до даних для кінцевих користувачів і державних установ у всьому світі.",
    "v4role": "Засновник і CEO",
    "v5role": "Засновник і CEO",
    "v6highlight": "Глобальна IT-стратегія та інфраструктура",
    "v6p1": "IT-компанія з Массачусетсу, що надавала комплексні стратегії та технологічні послуги провідним світовим організаціям. Керував розробкою масштабованої інфраструктури та глобальними IT-операціями.",
    "v6role": "CEO і директор з інформаційних технологій",
    "v7highlight": "Європейський лідер у супутникових системах",
    "v7p1": "Один з найбільших у Європі виробників цифрових супутникових трансиверних систем. Керував дослідженнями, розробкою операційних систем, мережевими програмними застосунками та загальною технічною стратегією.",
    "v7role": "Засновник і CEO",
    "v8highlight": "Інженерія військових супутникових систем",
    "v8p1": "Розробка та створення супутникових трансиверних систем для передачі секретної інформації на військові кораблі. Визнаний інженером-електроніком найвищого рівня на заводі з 93 000 співробітників.",
    "v8role": "Інженер-електронік · Найвища категорія (6-та)",
    "v1p2": "Портфельні ініціативи: <a href=\"https://biomathlife.com\" target=\"_blank\" rel=\"noopener\">BioMath Life</a>, <a href=\"https://www.biomathcore.com\" target=\"_blank\" rel=\"noopener\">BioMath Core</a>, <a href=\"https://www.type1and2.com\" target=\"_blank\" rel=\"noopener\">Type 1 &amp; 2</a> та <a href=\"https://www.luna29.com\" target=\"_blank\" rel=\"noopener\">Luna29</a> — детальні кейси будуть опубліковані пізніше.",
    "v1brole": "CEO",
    "v1bp1": "Перехідний період між біотехнологією та новою технологічною розробкою — операційний і R&D досвід перед Digital Invest Inc.",
    "v1byear": "2014 — 2020"
  },
  "career": {
    "eyebrow": "Професійний шлях",
    "title": "Хроніка",
    "lead": "Технології, компанії та операційний досвід у послідовні періоди технологічних змін.",
    "timelineEyebrow": "Хронологія",
    "timelineTitle": "Ключові етапи",
    "strengthsEyebrow": "Сильні сторони",
    "strengthsTitle": "Сфери експертизи",
    "filterAll": "Усі",
    "filterHealthcare": "Охорона здоров'я",
    "filterInfrastructure": "Інфраструктура",
    "filterDefense": "Оборона",
    "filterTelecom": "Телекомунікації",
    "periodCurrent": "Автономні системи",
    "periodCurrentLead": "ШІ, робототехніка, автономні операції, geospatial systems та related current infrastructure.",
    "period1title": "Інженерія та комунікації",
    "period1lead": "Рання інженерія, супутникові системи, комунікації та суміжні технології.",
    "period2title": "Інтернет та інфраструктура",
    "period2lead": "Інтернет-інфраструктура, телекомунікації, дата-центри, storage та суміжні компанії.",
    "period3title": "Компанії та публічні ринки",
    "period3lead": "Створення компаній, угоди, участь у public companies та executive-ролі.",
    "period4title": "Науки про життя та дані про людину",
    "period4lead": "Біотехнології, health-related technology, data та precision medicine.",
    "period5title": "Державні та оборонні програми",
    "period5lead": "Технологічна стратегія та delivery для government, defense і state-owned enterprise programs.",
    "t1desc": "Digital Invest Inc. заснована у 2021. Біоматематична медицина, геномна аналітика та клінічні платформи. Healthcare Tech Outlook (2023).",
    "t0desc": "Заснув AGRON Inc. для побудови екосистеми AGRON — консалтинг, оцінка, розвиток компетенцій, навчальна інфраструктура та підтримка продуктів для програм БПЛА і Counter-UAS, а також AGRON Maritime Intelligence + Security. Поєднує повітряну та наземну робототехніку, кероване виконання місій та мережеву інфраструктуру, що з'єднує команди, активи та операційні дані.",
    "t0role": "Засновник",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — дотепер",
    "t10title": "Миколаївський суднобудівний завод",
    "t10year": "1984 — 1989",
    "t1title": "Digital Invest Inc.",
    "t2year": "2001 — 2019",
    "t3role": "CEO і CTO",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4year": "2000 — 2012",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "Побудував одну з найбільших хостинг-компаній у світі. До 2000 року придбана Concentric Networks (NASDAQ: CNTX), потім XO Communications (NASDAQ: XOXO), з піковою ринковою капіталізацією $2000",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994",
    "t10desc": "Розробляв і створював супутникові трансиверні системи для передачі секретної інформації на військові кораблі. Визнаний інженером-електроніком найвищого рівня на заводі з 93 000 співробітників — початок видатної кар'єри в технологіях і інноваціях.",
    "t10role": "Інженер-електронік — 6-та категорія (найвища)",
    "t1role": "Засновник і CEO",
    "t1year": "2021 — дотепер",
    "t2desc": "Керував технологічною стратегією та реалізацією секретних і високочутливих програм із участю державних агентств США, союзних оборонних систем і підприємств із державною участю. Очолював складні технічні проєкти для державних компаній у різних секторах. Після 11 вересня 2001 року очолив масштабні державні ініціативи, зосереджені на big data, захищених комунікаціях, предиктивній аналітиці та інтеграції даних на національному рівні — включно з проєктуванням, будівництвом та експлуатацією високопродуктивних дата-центрів у США та Європі. Взаємодіяв із військовими програмними офіцерами, технологічними вендорами та регуляторами.",
    "t2role": "Головний технологічний радник / Архітектор програм",
    "t2title": "GovTech, оборона та державні програми",
    "t3desc": "Керував ДНК-тестуванням і аналізом, автоматизацією генетичного профілювання та комплексними дослідженнями людської генетики. Ініціював проєкти генетичного тестування в Україні, Росії та країнах Балтії. Співпрацював з Harvard Medical School і Stanford Biomath над розробкою зрозумілих генетичних звітів, впроваджених провідними лабораторіями у всьому світі.",
    "t4desc": "Керував розгортанням національної інфраструктури в Канаді, Італії, Швейцарії, Україні та країнах Балтії. Курував понад 1 000 інженерів і фахівців із розгортання в телеком-операціях, включно з комутаційними системами, розширенням широкосмугового доступу та транскордонною зв'язністю. Впровадив базові системи резервування мереж, оптимізації uptime та інтелектуальної маршрутизації.",
    "t4role": "VP з технологій / Регіональний CTO — Східна Європа та СНД",
    "t4title": "Телекомунікаційні проєкти",
    "t5desc": "Заснував технологічну компанію, що спеціалізується на зберіганні даних і керуванні big data для великих комерційних та державних організацій. Вивів компанію в число надійних постачальників корпоративних data-рішень.",
    "t5role": "Засновник і CEO · Рада директорів",
    "t6desc": "Створив компанію з управління та зберігання даних для малого та середнього бізнесу. Розробив унікальні технологічні рішення для прискореного відстеження інформації та спрощеного доступу до даних для кінцевих користувачів і державних установ у всьому світі.",
    "t6role": "Засновник і CEO",
    "t7role": "Засновник і CEO",
    "t8desc": "Керував комплексними IT-стратегіями та технологічними послугами для провідних світових організацій з Массачусетсу в період стрімкого зростання, створюючи масштабовану інфраструктуру та глобальні IT-операції.",
    "t8role": "CEO і директор з інформаційних технологій",
    "t9desc": "Заснував одного з найбільших у Європі виробників цифрових супутникових трансиверних систем. Керував дослідженнями, розробкою операційних систем, мережевими програмними застосунками та загальною технічною стратегією, отримавши міжнародне визнання.",
    "t9role": "Засновник і CEO",
    "t1bdesc": "Перехідний період між біотехнологією та новою технологічною розробкою — операційний і R&D досвід перед Digital Invest Inc.",
    "t1brole": "CEO",
    "t1byear": "2014 — 2020"
  },
  "recognition": {
    "eyebrow": "Нагороди",
    "title": "Нагороди та визнання",
    "lead": "Відзнаки в підприємництві, precision medicine, інженерії та executive-лідерстві.",
    "industryEyebrow": "Галузеві нагороди",
    "industryTitle": "Головні почесті",
    "ipEyebrow": "Інтелектуальна власність",
    "ipTitle": "Патенти та публікації",
    "eduEyebrow": "Освіта",
    "eduTitle": "Академічні ступені",
    "pressEyebrow": "Пресa",
    "pressTitle": "Згадки",
    "moreLink": "Переглянути патенти, публікації та матеріали преси на сторінці Insights →",
    "a1desc": "Entrepreneur Magazine · 2001",
    "a3title": "Who's Who in America",
    "a4title": "Who's Who in the World",
    "a5title": "Who's Who in Science & Engineering",
    "ip1year": "Патент",
    "ip2year": "Публікації",
    "press1role": "Матеріал про Digital Invest Inc.",
    "press1title": "Healthcare Tech Outlook",
    "press2title": "Top Precision Medicine Solutions",
    "a1title": "Підприємець року",
    "a2title": "Топ-10 компаній precision medicine у США",
    "a2desc": "Digital Invest Inc. визнана серед 10 найкращих американських компаній у галузі precision medicine і digital health — 2023.",
    "a3desc": "Включений, 1999 — 2018 — за видатні досягнення у створенні та розвитку бізнесу.",
    "a4desc": "Включений, 2000 — 2004 — серед світових лідерів у науці, інженерії та бізнес-інноваціях.",
    "a5desc": "Включений, 2000 — 2014 — за внесок у технології, супутникові системи та цифрову інфраструктуру.",
    "a6title": "Інженер-електронік — 6-та категорія",
    "a6desc": "Найвище визнання на Миколаївському суднобудівному заводі (93 000 співробітників) за інженерію супутникових трансиверних систем.",
    "ip1title": "Цифрові супутникові HDTV-системи",
    "ip1role": "Згодом придбаний Sony",
    "ip1desc": "Патент у сфері digital satellite HDTV, згодом придбаний Sony Corporation.",
    "ip2title": "Технічні праці",
    "ip2role": "Супутникові та оптичні системи",
    "ip2desc": "Автор технічних праць, присвячених супутниковим і оптичним системам передачі даних. Науковий внесок охоплює обробку сигналів, імітаційне моделювання та платформи автоматизації, застосовані в телекомунікаціях, національній інфраструктурі та цифровому здоров'ю.",
    "ip3year": "Дослідження",
    "ip3title": "Міжнародна співпраця",
    "ip3role": "США та Європа",
    "ip3desc": "Брав участь у міжнародних дослідницьких колабораціях та ініціативах із трансферу знань. Розробив вбудовані інженерні системи для збору даних, предиктивної діагностики та хмарної оркестрації в різних галузях.",
    "edu1title": "Доктор технічних наук",
    "edu2title": "Ph.D. у галузі інформаційних технологій",
    "edu3title": "Ступені магістра",
    "edu3desc": "Електроніка, цифрові супутникові системи та економіка",
    "press1desc": "Healthcare Tech Outlook про Digital Invest Inc. і precision medicine (2023).",
    "press1link": "Читати матеріал →",
    "press2role": "Галузеве визнання",
    "press2desc": "Включена до числа провідних компаній у галузі precision medicine, підкреслюючи роль Digital Invest у розвитку біоматематичних підходів до сучасної охорони здоров'я.",
    "press2link": "Дивитися рейтинг →"
  },
  "contact": {
    "eyebrow": "Контакти",
    "title": "Контакти",
    "lead": "Для advisory-ролей, рад директорів і стратегічних партнерств.",
    "infoTitle": "Прямий контакт",
    "email": "Електронна пошта",
    "phone": "Телефон",
    "location": "Локація",
    "locationVal": "Charlotte, North Carolina\nСполучені Штати",
    "linkedin": "LinkedIn",
    "company": "Поточна компанія",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member\nAGRON Inc.\nЗасновник",
    "formTitle": "Надіслати повідомлення",
    "formLead": "Заповніть форму — відповім найближчим часом.",
    "firstName": "Ім'я",
    "lastName": "Прізвище",
    "emailLabel": "Email",
    "subject": "Тема",
    "message": "Повідомлення",
    "inquiryType": "Тип запиту",
    "inquiryAdvisory": "Консалтинг",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "calendlyEyebrow": "Запланувати розмову",
    "calendlyTitle": "Оберіть зручний час",
    "calendlyLead": "Для qualified запитів щодо board, advisory, speaking і strategic partnerships.",
    "calendlyPlaceholder": "Календар зустрічей з'явиться тут.",
    "calendlyCta": "Відкрити календар зустрічей",
    "inquiryBusiness": "Бізнес",
    "infoEyebrow": "Контактна інформація"
  },
  "consulting": {
    "eyebrow": "Консультаційні послуги",
    "title": "Консалтинг",
    "heroEyebrow": "Стратегічне бізнес-керівництво",
    "heroTitle": "Стратегічне консультування",
    "heroLead": "Тридцять п'ять років створення та консультування компаній у США та Європі — інфраструктура даних, govtech, precision medicine та робототехніка.",
    "cta": "Зв'язатися з Michael Kofman",
    "introLead": "CEO Digital Invest Inc., член ради директорів. Фокус: emerging-технології, безпека, дослідження та розподіл капіталу.",
    "specialtiesEyebrow": "Напрямки",
    "specialtiesTitle": "Спеціалізація Michael Kofman",
    "area1title": "Робота в раді директорів",
    "area1desc": "Незалежна робота в радах директорів: технологічна стратегія, корпоративне управління та oversight на growth stage.",
    "area2title": "Консалтинг для CEO та засновників",
    "area2desc": "Корпоративна та технологічна стратегія, організаційний розвиток, угоди та applicable capital-markets experience.",
    "area3title": "Технологічний due diligence",
    "area3desc": "Оцінка інфраструктури, data platforms, security architecture та applied technology на основі documented operating experience.",
    "redirectLead": "Strategic advisory work задокументовано на сторінці Advisory. Для professional inquiries — Contact.",
    "redirectLink": "Консалтинг →"
  },
  "insights": {
    "eyebrow": "Перспективи",
    "title": "Інсайти",
    "heroTitle": "Executive Perspectives",
    "selectedEyebrow": "Обрані матеріали",
    "selectedTitle": "Визнання та нагороди",
    "allPressTitle": "Усі прес-матеріали",
    "quotesEyebrow": "У ЗМІ",
    "quotesTitle": "Галузеве визнання та цитати",
    "articlesEyebrow": "Перспективи",
    "articlesTitle": "Погляди керівника",
    "briefsEyebrow": "Виконавчі брифи",
    "briefsTitle": "Ідеї для лідерів",
    "briefsLead": "Короткі практичні perspectives про governance, technology, healthcare і company building.",
    "brief1title": "Що змінює IPO",
    "brief1desc": "Operating і governance disciplines, які вимагає public-market readiness.",
    "brief1tag": "Ринки капіталу",
    "brief2title": "Від генетичних даних до клінічних рішень",
    "brief2desc": "Як створити корисну health intelligence, не випереджаючи докази та довіру.",
    "brief2tag": "Прецизійна медицина",
    "brief3title": "Стратегія ШІ за межами пілота",
    "brief3desc": "Framework для перетворення experiments на governed enterprise capability.",
    "brief3tag": "Штучний інтелект",
    "readingEyebrow": "Список для читання",
    "readingTitle": "Книги, що формують стратегічне мислення",
    "r1title": "The Innovator's Dilemma",
    "r1author": "Clayton M. Christensen",
    "r2title": "Thinking, Fast and Slow",
    "r2author": "Daniel Kahneman",
    "r3title": "The Beginning of Infinity",
    "r3author": "David Deutsch",
    "r4title": "Good Strategy/Bad Strategy",
    "r4author": "Richard Rumelt",
    "r5title": "The Structure of Scientific Revolutions",
    "r5author": "Thomas S. Kuhn",
    "newsletterEyebrow": "Час від часу",
    "newsletterTitle": "Виконавча перспектива без шуму",
    "newsletterLead": "Periodic essays і brief observations про technology, governance і durable company building.",
    "newsletterCta": "Підписатися на оновлення",
    "lead": "Substantive writing і executive briefs.",
    "relatedLead": "Recognition, press coverage і patents задокументовано окремо.",
    "topicsLead": "Теми базуються на задокументованому операційному досвіді в технологіях, охороні здоров'я та інфраструктурі."
  },
  "cta": {
    "eyebrow": "Співпраця",
    "title": "Запросити консультацію або виступ",
    "lead": "Для advisory-ролей, членства в радах директорів, виступів і стратегічних партнерств.",
    "button": "Зв'язатися"
  },
  "speaking": {
    "eyebrow": "Публічні виступи",
    "title": "Запросіть Michael Kofman виступити",
    "lead": "Доступний для виступів про executive-лідерство, технологічну стратегію, digital health, інфраструктуру даних і корпоративне управління.",
    "topicsEyebrow": "Теми виступів",
    "topicsTitle": "Сфери експертизи",
    "topicsLead": "Теми базуються на десятиліттях досвіду заснування та керівництва компаніями у США та Європі.",
    "processEyebrow": "Як запросити",
    "processTitle": "Процес бронювання",
    "process1title": "Надішліть запит",
    "process1desc": "Скористайтеся контактною формою або напишіть на mkofman@mkofman.com, вказавши деталі події, аудиторію та бажані теми.",
    "process2title": "Узгодьте формат",
    "process2desc": "Погодьте формат (keynote, панель, сесія ради директорів або executive roundtable) і логістику.",
    "process3title": "Отримайте практичну цінність",
    "process3desc": "Виступи спираються на реальні результати проєктів у data storage, govtech і прецизійній медицині.",
    "cta": "Запросити виступ",
    "catalogEyebrow": "Теми виступів",
    "catalogTitle": "Виконавчі діалоги про значущі зміни",
    "catalogLead": "Keynote, засідання рад директорів і leadership-briefings з урахуванням аудиторії, сектору та контексту рішень.",
    "t1title": "Керувати ШІ, перш ніж він почне керувати компанією",
    "t1audience": "Ради директорів, комітети з аудиту та ризиків",
    "t1format": "Briefing для ради або keynote",
    "t2title": "Від технологічного тренду до корпоративної стратегії",
    "t2audience": "CEO, executive-команди, інвестори",
    "t2format": "Keynote або executive workshop",
    "t3title": "Будувати компанії через ринкові цикли",
    "t3audience": "Засновники, лідери зростання, private equity",
    "t3format": "Fireside chat або keynote",
    "t4title": "Precision medicine: обіцянка, докази та відповідальність",
    "t4audience": "Лідери охорони здоров'я, клініцисти, innovatorи",
    "t4format": "Галузевий keynote або panel",
    "t5title": "Роль ради директорів у cyber- та technology risk",
    "t5audience": "Директори, general counsel, лідери з ризиків",
    "t5format": "Освітня сесія для ради директорів",
    "t6title": "Інженерія довіри в цифровій інфраструктурі",
    "t6audience": "Технологічні та інфраструктурні організації",
    "t6format": "Технічно-executive keynote",
    "t7title": "Лідерство через кордони та дисципліни",
    "t7audience": "Глобальні leadership-команди та університети",
    "t7format": "Keynote або moderated conversation",
    "t8title": "Від засновника до творця institution",
    "t8audience": "Підприємці та executive наступного покоління",
    "t8format": "Workshop або fireside chat"
  },
  "caseStudies": {
    "eyebrow": "Кейси",
    "title": "Побудова компаній, що масштабуються",
    "lead": "Вибрані результати заснування та керівництва компаніями у сферах інфраструктури даних і digital health.",
    "cs1eyebrow": "Інфраструктура даних · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "Виклик",
    "cs1challengeText": "Побудувати та масштабувати компанію Data Storage на технологічному ринку, що швидко консолідувався.",
    "cs1action": "Підхід",
    "cs1actionText": "9 Net Avenue Inc. була заснована у 1996 році. Компанія швидко стала однією з найбільших у світі у сфері Data Storage.",
    "cs1result": "Результат",
    "cs1resultText": "Придбана Concentric Networks (NASDAQ: CNTX) у 2000; потім частина XO Communications (NASDAQ: XOXO). Після угоди продовжив роботу з публічними компаніями та ролями на рівні ради директорів.",
    "cs2eyebrow": "Digital Health · 2021 — дотепер",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "Виклик",
    "cs2challengeText": "Трансформувати застарілі підходи в медицині за допомогою науки, ДНК-технологій, AI і ML через нову біо-математичну платформу.",
    "cs2action": "Підхід",
    "cs2actionText": "Засновано Digital Invest Inc. у 2021. Біоматематична медицина, геномна аналітика та клінічні платформи даних.",
    "cs2result": "Результат",
    "cs2resultText": "Досягнуто стабільного фінансового зростання, що вивело компанію до Top 10 компаній прецизійної медицини у США (2023). Digital Invest об'єднує інноваційні проєкти Human Digital Model, BioMath Life та Aero-Ground Robotics Operations Network.",
    "cs3eyebrow": "Робототехніка та БПЛА · 2026 — сьогодні",
    "cs3title": "AGRON Inc.",
    "cs3challenge": "Завдання",
    "cs3challengeText": "Створити екосистему для розробки БПЛА, геопространственних систем і морської розвідки.",
    "cs3action": "Підхід",
    "cs3actionText": "AGRON Ecosystem об'єднує Global Drone Academy, AGRON, ISDRI та GUARD.",
    "cs3result": "Результат",
    "cs3resultText": "Програми у 10+ країнах, понад 10 000 операторів і фахівців БПЛА.",
    "caseStudiesLead": "Заснування, масштабування та керівництво компаніями — від ранньої стадії до угод M&A."
  },
  "mediaKit": {
    "eyebrow": "Преса та події",
    "title": "Медіа-кит",
    "lead": "Офіційні біографії, зображення та контакти для преси, конференцій і запитів від рад директорів.",
    "bioEyebrow": "Биографії",
    "bioTitle": "Офіційні біографії",
    "bioShortLabel": "50 слів",
    "bioShort": "Michael Kofman — CEO Digital Invest Inc., член рад директорів, радник і засновник компаній у сферах технологій і digital health у США та Європі.",
    "bioMediumLabel": "150 слів",
    "bioMedium": "Michael Kofman — CEO Digital Invest Inc. і член її Board of Directors. Технологічний візіонер, відомий динамічним підходом до розуміння потреб сучасного складного ринку, що постійно змінюється. Як підприємець, член рад директорів і радник публічних та приватних компаній, він успішно заснував кілька компаній у США та Європі. Його експертиза охоплює executive-менеджмент, стратегічний аналіз нових технологій і ринків, інформаційну безпеку та приватність, дослідження, науку й розробки, адміністрування та інвестиції.",
    "bioLongLabel": "500 слів",
    "bioLong": "Michael Kofman — CEO Digital Invest Inc. і член її ради директорів. Заснував 9 Net Avenue Inc., придбану Concentric Networks у 2000, і очолює Digital Invest у biomathematical medicine та genomic intelligence. Заснував AGRON Inc. у 2026 для autonomous aerial-ground operations і geospatial systems. Автор technical papers про satellite і optical systems; patent у digital satellite HDTV, acquired Sony. Education: Doctor of Technical Sciences, Ph.D. in Information Technology.",
    "photosEyebrow": "Фотографії",
    "photosTitle": "Погоджені зображення",
    "photosLead": "Портрети високої роздільної здатності доступні за запитом на mkofman@mkofman.com.",
    "contactEyebrow": "Контакт для преси",
    "contactTitle": "Медійні запити",
    "contactLead": "Для інтерв'ю, запрошень на виступи та запитів від преси.",
    "brandEyebrow": "Бренд-активи",
    "brandTitle": "Ідентичність та використання",
    "brandLead": "Approved visual assets для editorial, conference і partner use. Please preserve proportions, spacing і original colors.",
    "brandColors": "Офіційна палітра кольорів",
    "brandLogo": "Основний логотип",
    "brandDownload": "Завантажити бренд-активи",
    "downloadEyebrow": "Завантажити",
    "downloadTitle": "Односторінковий media kit",
    "downloadLead": "PDF з офіційними біографіями, портретом і прес-контактом — готовий для організаторів і журналістів.",
    "downloadCta": "Завантажити PDF"
  },
  "articles": {
    "backLink": "← Назад до Insights",
    "article1date": "Виконавча перспектива",
    "article1title": "Від інженерії до глобальної інфраструктури даних",
    "article1p1": "Моя кар'єра почалася на Миколаївському суднобудівному заводі в Україні, де я розробляв супутникові трансиверні системи для передавання засекреченої інформації військовим кораблям. Мене визнали інженером-електронщиком найвищого рівня — 6-ї категорії на підприємстві з 93 000 працівників.",
    "article1p2": "У 1989-1994 роках я заснував і очолював Astra Corp, одного з найбільших у Європі виробників цифрових супутникових трансиверних систем. У 1994-1996 роках, як CEO Elitan United Inc., я допоміг масштабувати компанію з дев'яти до понад 4 000 працівників у світі.",
    "article1p3": "У 1996 році я заснував 9 Net Avenue Inc. — компанію хостингу та інтернет-інфраструктури. У 2000 році її придбала Concentric Networks (NASDAQ: CNTX), а згодом вона стала частиною XO Communications (NASDAQ: XOXO).",
    "article1p4": "У 2001-2019 роках я керував технологічною стратегією для державних, оборонних і квазідержавних програм, очолюючи масштабні ініціативи у сфері big data, захищеної інфраструктури та високопродуктивних дата-центрів у США та Європі.",
    "article2date": "Цифрове охорону здоров'я",
    "article2title": "Прецизійна медицина та конвергенція науки й технологій",
    "article2p1": "Я переконаний у потенціалі поєднання наук про життя з найновішими технологічними досягненнями. У Biotechnology Group Inc. (2008-2014) ми зосереджувалися на ДНК-тестуванні та аналізі, автоматизації процесів створення генетичних профілів і комплексних дослідженнях генетики людини.",
    "article2p2": "Під моїм керівництвом було започатковано успішні проєкти генетичного тестування в Україні, Росії та країнах Балтії. У співпраці з Harvard Medical School і Stanford Biomath я відіграв ключову роль у створенні зрозумілих генетичних звітів як для лікарів, так і для пацієнтів.",
    "article2p3": "З Digital Invest Inc., заснованою у 2021, працюємо в біоматематичній медицині — наука, ДНК-технології, ШІ та ML у кlinічній аналітиці. Healthcare Tech Outlook (2023).",
    "article2p4": "Digital Invest об'єднує інноваційні проєкти, зокрема Human Digital Model, BioMath Life та Aero-Ground Robotics Operations Network, кожен з яких посилює інтеграцію data science і наук про життя."
  },
  "board": {
    "eyebrow": "Консалтинг",
    "title": "Консалтинг",
    "body": "Відкритий до стратегічних advisory-діалогів із технологічними, медичними та інфраструктурними організаціями — на основі прямого operating-досвіду у створенні компаній, технологічній стратегії та зростанні.",
    "contactLink": "Щодо advisory-запитів",
    "lead": "Board & Advisory"
  },
  "thesis": {
    "eyebrow": "Тезис лідерства",
    "title": "Будувати надовго. Вирішувати — зараз.",
    "lead": "Технології змінюються швидко; зобов'язання лідерства — ні. Стійкі компанії поєднують амбіції з дисципліною, доказами та підзвітністю.",
    "believeEyebrow": "У що я вірю",
    "believeTitle": "Сім принципів для стійких організацій",
    "b1title": "Стратегія повинна породжувати вибір",
    "b1text": "Стратегія — не каталог амбіцій. Вона визначає, де конкурувати, які спроможності будувати, чого не pursue і як вимірювати успіх.",
    "b2title": "Технологія — питання управління",
    "b2text": "Ради директорів мають розуміти, як технологія створює цінність, конcentрує ризик і змінює підзвітність. Делегування кожного технічного питання — само по собі рішення.",
    "b3title": "Докази важливіші за ентузіазм",
    "b3text": "Переконання важливе, але ринки, системи та науку потрібно перевіряти. Лідери створюють механізми, що виявляють припущення раніше клієнтів або регуляторів.",
    "b4title": "Архітектура формує компанію",
    "b4text": "Технічна архітектура визначає швидкість, стійкість, безпеку та майбутні опції. Shortcut'и стають інституційними обмеженнями long after зникнення їхнього контексту.",
    "b5title": "Довіра — операційна інфраструктура",
    "b5text": "Довіра будується через чіткі зobов'язання, надійне виконання, відповідальну роботу з даними та пряму комунікацію при зміні умов.",
    "b6title": "Капітал повинен слідувати за спроможностями",
    "b6text": "Інвестиції в зростання мають посилювати диференційовані спроможності та вимірюваний попит, а не замінювати витрати розумінням product-market.",
    "b7title": "Лідери проектують своїх наступників",
    "b7text": "Найсильніші лідери будують системи, таланти та якість рішень, які переживають їхню власну участь.",
    "rejectEyebrow": "Що я відкидаю",
    "rejectTitle": "Три дорогих ілюзії",
    "r1title": "Театр інновацій",
    "r1text": "Анонси, пілоти та модна мова не дорівнюють capability. Інновації мають покращувати результат, який має значення.",
    "r2title": "Зростання без управління",
    "r2text": "Масштаб збільшує невирішені слабкості. Controls, culture і accountability мають дозріти, поки complexity не зробить correction costly.",
    "r3title": "Хибна певненість",
    "r3text": "Executive confidence не повинна стирати uncertainty. Сильні рішення роблять assumptions visible і зберігають options при зміні facts.",
    "horizonEyebrow": "Горizont",
    "horizonTitle": "Наступна перевага — відповідальна інтеграція",
    "horizonText": "Визначальна можливість — не одна технологія. Це дисциплінована інтеграція ШІ, просунутих data systems, біології та automation в institution, яким люди можуть довіряти."
  },
  "press": {
    "eyebrow": "Пресса і медіа",
    "title": "Обрані публікації",
    "lead": "Стислий архів стороннього визнання та публікацій про технології, підприємництво та прецизійну медицину.",
    "archiveEyebrow": "Архів",
    "y2023type": "Галузеве визнання",
    "y2023title": "Топ-10 компаній у точній медицині",
    "y2023desc": "Healthcare Tech Outlook recognized Digital Invest Inc. among leading U.S. companies advancing precision medicine і digital health.",
    "y2023link": "Переглянути матеріал",
    "y2001type": "Виконавча награда",
    "y2001title": "Підприємець року",
    "y2001desc": "Визнання Entrepreneur Magazine.",
    "y2001link": "Переглянути архів",
    "y1999type": "Біографічне визнання",
    "y1999title": "Who's Who in America",
    "y1999desc": "Recognition beginning 1999, followed listings Who's Who in the World і Who's Who in Science and Engineering.",
    "clipEyebrow": "З архіву",
    "clipMeta": "Industry Feature · DataPeer Inc.",
    "clipTitle": "State of the Storage Industry",
    "clipLead": "Раннє інтерв'ю з Michael Kofman як Founder, Chairman і CEO DataPeer Inc. — про волоконну оптику, супутникову передачу, SAN і формуючий ринок зберігання.",
    "clipBody": "Матеріал відзначає звання «Підприємець року» від Entrepreneur Magazine (2001) і підхід DataPeer до критично важливого зберігання, iSCSI і безперервності бізнесу.",
    "clipOpen": "Відкрити повний скан →",
    "y2000type": "Інтерв'ю",
    "y2000title": "State of the Storage Industry",
    "y2000desc": "Featured interview з Michael Kofman як Founder, Chairman і CEO DataPeer Inc. про мережі зберігання, iSCSI і безперервність бізнесу."
  },
  "ip": {
    "eyebrow": "Інтелектуальна власність",
    "title": "Прикладні ідеї, задокументовані",
    "lead": "Selected patents, publications і research programs, connecting engineering rigor з practical business і societal outcomes.",
    "patentEyebrow": "Патенти",
    "patentTitle": "Захищені винаходи",
    "patentIntro": "Patent work відображає sustained focus на systems, improving collection, movement, protection і interpretation of information.",
    "publicationsEyebrow": "Публікації",
    "publicationsTitle": "Технічне та виконавче письмо",
    "publicationsIntro": "Published work перекладає complex technical subjects у methods, frameworks і decisions, useful practitioners і leaders.",
    "researchEyebrow": "Дослідження",
    "researchTitle": "Міждисциплінарні програми",
    "researchIntro": "Research initiatives span secure communications, predictive analytics, genetic interpretation, human digital modeling і autonomous systems."
  },
  "testimonials": {
    "t1quote": "Michael поєднує інженерну точність із judgment досвідченого CEO. Він ставить запитання, які покращують decision.",
    "t1name": "Колега з ради директорів",
    "t1role": "Публічна технологічна компанія",
    "t2quote": "Його здатність connect science, product, governance і commercial reality приносить uncommon clarity складним ініціативам.",
    "t2name": "Стратегічний партнер",
    "t2role": "Сектор цифрового охорону здоров'я",
    "t3quote": "Michael direct, thoughtful і focused на durable value. Він допомагає leadership teams бачити і opportunity, і obligation.",
    "t3name": "Executive collaborator",
    "t3role": "Глобальна інфраструктура"
  },
  "deck": {
    "title": "Michael Kofman",
    "subtitle": "Технологічний executive · Засновник · Радник",
    "thesis": "Технології, бізнес і інвестиції в інфраструктуру, life sciences та автономні системи.",
    "contact": "Конфіденційна розмова: зв'язатися з Michael Kofman через mkofman.com"
  },
  "briefIpo": {
    "title": "Що змінює IPO",
    "desc": "Публічні ринки змінюють не лише capital structure; вони змінюють operating contract.",
    "p1": "IPO часто описують як financing event. На практиці це institutional transition. Forecasting, controls, disclosure, governance і executive communication мають стати repeatable до listing, а не improvised після.",
    "p2": "Readiness починається з decision quality. Management потрібні reliable metrics, clear ownership і operating cadence, здатний пояснити performance і variance. Компанія, що не reconciling internal narrative, буде struggle з credible external one.",
    "p3": "Роль board теж змінюється. Directors мають balance growth і oversight, розуміти material technology і market risks і ensure, що incentives support durable value, а не single quarter.",
    "p4": "Найсильніші public companies зберігають entrepreneurial speed, додаючи institutional discipline. Objective — не bureaucracy; це trustworthy execution на вищому рівні accountability.",
    "eyebrow": "Виконавчий бриф"
  },
  "briefGenetic": {
    "title": "Від генетичних даних до клінічних рішень",
    "desc": "Цінність геномної інформації залежить від інтерпретації, доказової бази та відповідальної інтеграції в клінічну практику.",
    "p1": "Генетичних даних багато; clinically useful meaning — рідкість. Результат стає цінним лише коли інтерпретований у контексті, пов'язаний із validated evidence і поданий у формі, що підтримує реальне рішення.",
    "p2": "Такий переклад потребує collaboration між molecular biology, medicine, statistics, software engineering і patient communication. Слабкість на будь-якому рівні перетворює technical sophistication на clinical confusion.",
    "p3": "Privacy і consent — architectural requirements, а не legal footnotes. Системи мають обмежувати unnecessary exposure, робити data provenance visible і зберігати patient agency під час руху інформації між laboratories, platforms і care teams.",
    "p4": "Прецизійна медицина розвиватиметься через вимірювану інтеграцію: кращі докази, прозорі моделі, interoperable workflows і результати, які можуть оцінити клініцисти та пацієнти. Довіра — частина продукту.",
    "eyebrow": "Виконавчий бриф"
  },
  "briefAi": {
    "title": "Стратегія ШІ за межами пілота",
    "desc": "Корпоративний ШІ створює цінність, коли ownership, дані, workflow і governance дозрівають разом.",
    "p1": "Багато AI-ініціатив починаються з переконливої демонстрації й зупиняються до production. Бракує рідко лише моделі. Стійка цінність потребує визначеного business outcome, відповідального власника, надійних даних і workflow, яким люди справді користуються.",
    "p2": "Лідерам варто розрізняти automation, prediction і decision support. Кожен має різні вимоги до точності, explainability, human review і ризику. Єдиний governance-шаблон не підходить для всіх use cases.",
    "p3": "Вимірювання має включати більше, ніж технічну продуктивність. Adoption, cycle time, error rates, customer impact, security exposure і cost of supervision визначають, чи є AI-capability економічно та institutionally sound.",
    "p4": "Переможний підхід — managed portfolio: масштабувати proven use cases, рано зупиняти слабкі та підтримувати explicit boundaries для high-consequence decisions. AI strategy — це ultimately operating strategy.",
    "eyebrow": "Виконавчий бриф"
  },
  "privacy": {
    "eyebrow": "Правова інформація",
    "title": "Політика конфіденційності",
    "lead": "Як mkofman.com обробляє інформацію під час відвідування сайту або надсилання повідомлення.",
    "updated": "Оновлено: липень 2026",
    "s1title": "Які дані збираємо",
    "s1text": "Під час надсилання форми отримуємо вказані вами поля. За увімкненої аналітики — анонімізовані дані відвідувань.",
    "s2title": "Як використовуємо дані",
    "s2text": "Для відповіді на запити та покращення сайту. Персональні дані не продаємо.",
    "s3title": "Сторонні сервіси",
    "s3text": "Форми можуть оброблятися Formspree. Аналітика — Plausible або Google Analytics за налаштуванням.",
    "s4title": "Ваші права",
    "s4text": "Запит доступу, виправлення або видалення: mkofman@mkofman.com.",
    "s5title": "Контакт",
    "s5text": "Питання щодо політики: mkofman@mkofman.com"
  }
};
