window.__LANG_zh = {
  "ui": {
    "toggleTheme": "切换浅色/深色主题",
    "selectLanguage": "选择语言",
    "messageSent": "消息已发送",
    "sendMessage": "发送消息",
    "toggleNav": "打开菜单",
    "sending": "发送中…",
    "formError": "发送失败。请直接发送电子邮件。",
    "present": "至今"
  },
  "nav": {
    "home": "首页",
    "about": "简介",
    "ventures": "企业",
    "career": "职业",
    "recognition": "荣誉",
    "contact": "联系",
    "consulting": "咨询",
    "insights": "洞见",
    "speaking": "演讲邀约",
    "caseStudies": "案例研究",
    "mediaKit": "媒体资料包",
    "groupMain": "主要",
    "groupServices": "服务",
    "groupWork": "成果"
  },
  "footer": {
    "navigation": "导航",
    "ventures": "企业",
    "connect": "联系",
    "desc": "首席执行官、战略技术专家和获奖企业家。",
    "copyright": "© 2025–2026 Michael Kofman. 版权所有。",
    "writeTitle": "给我留言",
    "writeEmail": "您的邮箱",
    "writeMessage": "您的留言",
    "writeSend": "发送",
    "writeSuccess": "谢谢 — 您的留言已发送。",
    "more": "更多"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — 首席执行官",
      "description": "Michael Kofman官方网站——屡获殊荣的CEO、创始人和战略技术专家。"
    },
    "about": {
      "title": "简介 — Michael Kofman",
      "description": "Michael Kofman传记——Digital Invest Inc. CEO——技术愿景家和屡获殊荣的企业家。"
    },
    "ventures": {
      "title": "企业 — Michael Kofman",
      "description": "Michael Kofman创办和领导的企业——从Digital Invest Inc.到9 Net Avenue Inc.——在科技和医疗领域构建变革性业务。"
    },
    "career": {
      "title": "职业 — Michael Kofman",
      "description": "Michael Kofman职业历程——从卫星工程到全球科技和医疗公司CEO。"
    },
    "recognition": {
      "title": "荣誉 — Michael Kofman",
      "description": "Michael Kofman获得的奖项与荣誉——年度企业家、Who's Who、专利和行业殊荣。"
    },
    "contact": {
      "title": "联系 — Michael Kofman",
      "description": "联系Michael Kofman——Digital Invest Inc. CEO。咨询顾问职位、演讲邀约和商业合作。"
    },
    "consulting": {
      "title": "咨询 — Michael Kofman",
      "description": "与Michael Kofman的顾问职位、董事会成员、演讲邀约和战略合作。"
    },
    "insights": {
      "title": "洞见 — Michael Kofman",
      "description": "Michael Kofman的出版物、媒体报道、专利和行业认可。"
    },
    "speaking": {
      "title": "演讲邀约 — Michael Kofman",
      "description": "邀请 Michael Kofman 就高管领导力、技术战略、数字健康和公司治理发表演讲。"
    },
    "caseStudies": {
      "title": "案例研究 — Michael Kofman",
      "description": "Michael Kofman 职业生涯案例研究：9 Net Avenue Inc. 与 Digital Invest Inc."
    },
    "mediaKit": {
      "title": "媒体资料包 — Michael Kofman",
      "description": "面向媒体与活动主办方的官方简介、照片及联系方式。"
    },
    "article1": {
      "title": "从工程到全球基础设施 — Michael Kofman",
      "description": "Michael Kofman 讲述自己从卫星工程到创办全球数据基础设施公司的职业路径。"
    },
    "article2": {
      "title": "精准医疗与科技融合 — Michael Kofman",
      "description": "Michael Kofman 谈生命科学与 AI、ML 及 DNA 技术在现代医学中的融合。"
    }
  },
  "home": {
    "heroEyebrow": "Michael Kofman 官方网站",
    "heroTitle1": "远见卓识的领导力。",
    "heroTitle2": "战略创新。",
    "heroCta": "了解我的故事",
    "heroAlt": "Michael Kofman — CEO and Strategic Technologist",
    "quote1text": "A technology visionary recognized for his dynamic approach to understanding the ever-changing demands of today's complex marketplace.",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "Entrepreneur of the Year — recognized for leadership and breakthrough achievements in platform innovation and infrastructure.",
    "quote2author": "Entrepreneur Magazine, 1999 — 2001",
    "quote3text": "Digital Invest Inc. named among America's Top 10 Best Companies in Precision Medicine and Digital Health.",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "Known for uniting engineering precision with business strategy, delivering high-value outcomes, and building future-oriented companies from scratch.",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "认识 Michael Kofman",
    "aboutTitle": "创新与领导力的传承",
    "aboutLead1": "Michael Kofman is a technological visionary renowned for his dynamic approach to understanding the ever-evolving needs of today's complex market. An entrepreneur, board member, and advisor for both public and private companies, he has successfully established several companies in the United States and Europe.",
    "aboutLead2": "从创立全球最大的 Data Storage 公司之一——峰值市值达195亿美元——到领导 Digital Invest Inc. 从事数据存储与前沿技术创新。Digital Invest 涵盖多项创新项目，包括 Human Digital Model、BioMath Life 和 Aero-Ground Robotics Operations Network。",
    "aboutLink": "阅读完整传记",
    "expertiseEyebrow": "多元专长",
    "expertiseTitle": "跨行业高管领导力",
    "expertiseLead": "Explore Michael Kofman's diverse expertise as a CEO, technologist, advisor, and investor. With decades of experience, he provides unparalleled insight and guidance to drive success.",
    "exp1title": "CEO与创始人",
    "exp1desc": "从创立到成功上市，创办并扩展了多家公司，在科技与医疗领域实现了持续财务增长和全球布局。",
    "exp1link": "查看企业 →",
    "exp2title": "技术架构师",
    "exp2desc": "为政府、军事和电信领域设计安全通信、预测分析引擎和国家级数据集成平台。",
    "exp2link": "查看职业 →",
    "exp3title": "数字健康",
    "exp3desc": "通过人工智能、机器学习和DNA技术引领医学变革。曾与哈佛医学院和Stanford Biomath合作开展基因报告项目。",
    "exp3link": "Digital Invest →",
    "exp4title": "董事会顾问",
    "exp4desc": "担任董事会成员，为上市和非上市公司提供战略方向、公司治理和技术驱动增长方面的咨询。",
    "exp4link": "咨询 →",
    "stat1": "领导年数",
    "stat2": "创立公司",
    "stat3": "峰值市值",
    "stat4": "扩展员工",
    "recEyebrow": "荣誉",
    "recTitle": "奖项与荣誉",
    "recLead": "Consistently recognized for exceptional achievements in business creation, innovation, and executive leadership.",
    "award1title": "年度企业家",
    "award1desc": "Entrepreneur Magazine, 1999 — 2001",
    "award2title": "精准医疗前十",
    "award2desc": "Digital Invest Inc. — U.S., 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "查看所有荣誉",
    "heroSub": "面向公私营企业的 CEO、董事会顾问与战略技术专家，专注科技、数据存储与数字健康领域。",
    "primaryCta": "申请顾问咨询",
    "secondaryCta": "查看案例研究",
    "featuredEyebrow": "媒体报道",
    "caseStudiesEyebrow": "可验证成果",
    "caseStudiesTitle": "案例研究",
    "caseStudiesLead": "从创立到并购和 IPO，持续推动企业创建、扩张与领导。",
    "caseStudiesLink": "查看全部案例研究 →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "打造了全球最大的数据存储企业之一，并在峰值市值 195 亿美元时被收购。",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "从创立扩展至成功 IPO，入选 2023 年美国精准医疗十强企业。"
  },
  "about": {
    "eyebrow": "关于 Michael Kofman",
    "title": "创新传承",
    "lead": "技术愿景家与高管，职业生涯跨越三十多年。",
    "glance": "概览",
    "role": "现任职位",
    "roleVal": "CEO & Board Member · Digital Invest Inc.",
    "location": "地点",
    "locationVal": "Charlotte, North Carolina",
    "education": "教育",
    "educationVal": "Doctor of Technical Sciences (2009)\nPh.D. in Information Technology (2004)\nMaster's in Electronic Engineering",
    "university": "大学",
    "universityVal": "Ukrainian State Marine Technical University",
    "languages": "语言",
    "languagesVal": "English, Russian, Ukrainian",
    "contactLabel": "联系",
    "bioP1": "Michael Kofman 现任 Digital Invest Inc. 首席执行官，并担任该公司董事会成员。作为一位技术远见者，他以动态方式洞察当今复杂市场不断演变的需求而著称。其专业领域涵盖高管领导力、新兴技术与市场战略分析、信息安全与隐私、科研与开发、行政管理及投资。",
    "bioP2": "作为企业家、董事会成员以及上市公司与私营企业的顾问，Michael Kofman 在美国和欧洲成功创立了多家公司。近期，他启动了雄心勃勃的 Digital Invest 项目——一家致力于生物数学领域的企业，旨在运用科学、DNA 技术、人工智能和机器学习的最新成果，变革陈旧的医疗模式。",
    "secBioTitle": "精准医疗与生物技术",
    "secBioP1": "在创立 Digital Invest 之前，他在 Biotechnology Group Inc.（2008 — 2014）的成功中发挥了重要作用。该公司致力于 DNA 检测与分析、基因图谱构建流程自动化以及全面的人类遗传学研究。科夫曼先生坚信，将生命科学与最新技术进展相结合具有巨大潜力。",
    "secBioP2": "在他的领导下，乌克兰、俄罗斯和波罗的海国家成功启动了基因检测项目。这一独特经验不断融入现代技术与新设备。在与 Harvard Medical School 和 Stanford Biomath 的合作中，科夫曼先生在开发医生与患者均易于理解的基因报告方面发挥了关键作用。这一创新方法已被美国及海外领先实验室广泛采用。",
    "secTechTitle": "技术与基础设施",
    "secTechP1": "2001 年至 2019 年，科夫曼先生为政府、国防及国有企业项目制定技术战略——包括面向国有企业的复杂技术倡议。2001 年 9·11 事件后，他领导了以大数据、安全基础设施和高吞吐量数据中心为核心的美国政府大型项目，覆盖美国与欧洲。",
    "secTechP2": "2006 年，科夫曼先生创立了 XIBI Group Inc.——一家他担任董事会成员的技术公司。这家美国公司专注于为大型商业及政府组织提供数据存储与大数据管理服务。",
    "secTechP3": "2000 年至 2004 年，科夫曼先生领导 DataPeer Inc.——一家为中小企业提供广泛信息存储服务的数据管理与存储公司。在 DataPeer，他开发了独特的技术解决方案，使全球个人用户和政府机构能够更快速地追踪信息、更便捷地访问数据。",
    "secTechP4": "1996 年，科夫曼先生创立了 9 Net Avenue Inc.，该公司迅速成为全球最大的主机托管公司之一。2000 年，9 Net Avenue 被 Concentric Networks（NASDAQ: CNTX）收购，随后被 XO Communications（NASDAQ: XOXO）收购，峰值市值达 195 亿美元。",
    "secPost9NetP1": "在 9 Net Avenue 被收购后，科夫曼先生积累了在上市公司工作、参与董事会并参与最高管理层战略决策的丰富经验。",
    "secEarlyTitle": "早期职业与工程",
    "secEarlyP1": "1994 年至 1996 年，科夫曼先生担任 Elitan United Inc. 首席执行官兼信息技术总监——这是一家位于马萨诸塞州的 IT 公司，为领先全球组织提供全面战略与技术服务。他在开发和管理可扩展基础设施方面发挥了关键作用，推动公司从仅 9 名员工增长至全球 4,000 余人。",
    "secEarlyP2": "1989 年至 1994 年，他创立并担任 Astra Corp 首席执行官，该公司是欧洲最大的数字收发卫星系统制造商之一，在卫星设备领域获得国际认可。其职责涵盖研究、操作系统开发、网络软件应用及整体技术战略。",
    "secEarlyP3": "1984 年至 1989 年，科夫曼先生在乌克兰尼古拉耶夫造船厂工作，积极参与用于向军舰及回传传输机密信息的卫星收发系统的研发与制造。他被认定为最高级别的电子工程师，获得第六类职称——在该拥有 9.3 万名员工的工厂中，这是最高荣誉。",
    "secResearchTitle": "研究与专利",
    "secResearchP1": "Michael Kofman 是专注于卫星与光学数据传输系统的技术论文作者。他还获得了数字卫星高清电视（HDTV）系统领域的专利，该专利随后被 Sony 收购。"
  },
  "ventures": {
    "eyebrow": "企业组合",
    "title": "改变行业的企业",
    "lead": "从精准医疗到全球电信。",
    "v1year": "2021 — 至今",
    "v1role": "创始人兼首席执行官 · 董事会成员",
    "v1p1": "从创立到成功 IPO，创办并规模化发展 Digital Invest。公司致力于生物数学领域，通过 AI、ML 和 DNA 技术变革医疗。",
    "v1highlight": "2023 年美国精准医疗十大公司",
    "v2year": "2008 — 2014",
    "v2role": "首席执行官兼首席技术官",
    "v2p1": "DNA 检测与分析、基因图谱自动化以及全面的人类遗传学研究。在乌克兰、俄罗斯和波罗的海国家发起基因检测项目。",
    "v2p2": "与 Harvard Medical School 和 Stanford Biomath 合作，开发被全球领先实验室采用的基因报告。",
    "v2highlight": "Harvard Medical School 与 Stanford Biomath 合作伙伴",
    "v3year": "2006 — 2011",
    "v3role": "创始人兼首席执行官 · 董事会",
    "v3p1": "为大型商业及政府组织提供数据存储与大数据管理服务。将公司确立为值得信赖的企业数据解决方案提供商。",
    "v3highlight": "企业与政府数据解决方案",
    "v4year": "2000 — 2004",
    "v4role": "创始人兼首席执行官",
    "v4p1": "为中小企业提供数据管理与存储服务。开发解决方案，使全球终端用户和政府机构能够更快速地追踪信息、更便捷地访问数据。",
    "v4highlight": "全球数据管理平台",
    "v5year": "1996 — 2000",
    "v5role": "创始人兼首席执行官",
    "v5p1": "打造了全球最大的主机托管公司之一。2000 年被 Concentric Networks（NASDAQ: CNTX）收购，随后被 XO Communications（NASDAQ: XOXO）收购，峰值市值达 195 亿美元。",
    "v5highlight": "被收购 · 峰值市值 195 亿美元",
    "v6year": "1994 — 1996",
    "v6role": "首席执行官兼信息技术总监",
    "v6p1": "马萨诸塞州 IT 公司，为领先全球组织提供全面战略与技术服务。领导可扩展基础设施开发及全球 IT 运营。",
    "v6highlight": "全球 IT 战略与基础设施",
    "v7year": "1989 — 1994",
    "v7role": "创始人兼首席执行官",
    "v7p1": "欧洲最大的数字收发卫星系统制造商之一。领导研究、操作系统开发、网络软件应用及整体技术战略。",
    "v7highlight": "欧洲卫星系统领导者",
    "v8year": "1984 — 1989",
    "v8role": "电子工程师 · 最高类别（第六类）",
    "v8p1": "研发用于向军舰传输机密信息的卫星收发系统。在拥有 93,000 名员工的工厂中，被认定为最高级别的电子工程师。",
    "v8highlight": "军用卫星系统工程"
  },
  "career": {
    "eyebrow": "职业历程",
    "title": "三十年的高管领导力",
    "lead": "从卫星工程到全球科技企业。",
    "timelineEyebrow": "时间线",
    "timelineTitle": "关键里程碑",
    "strengthsEyebrow": "核心优势",
    "strengthsTitle": "专业领域",
    "t1year": "2021 — 至今",
    "t1title": "Digital Invest Inc.",
    "t1role": "创始人兼首席执行官",
    "t1desc": "从创立到成功 IPO，创办并规模化发展公司。领导完整的公开募股流程——法律架构、财务合规、投资者路演及 SEC 协调。指导美国与欧洲多个数据中心的设计、建设与运营。构建企业级软件系统，实现自动化、预测性监控和集中化数据管控。实现持续财务增长，使公司跻身 2023 年美国精准医疗十大公司之列。",
    "t2year": "2001 — 2019",
    "t2title": "GovTech、国防与国有项目",
    "t2role": "首席技术顾问 / 项目架构师",
    "t2desc": "为涉及美国政府机构、盟国国防系统及国有企业的机密与高敏感项目制定并交付技术战略。领导跨多个行业国有企业的复杂技术项目。2001 年 9·11 事件后，主导以大数据、安全通信、预测分析和国家级数据整合为核心的大规模政府倡议——包括在美国与欧洲设计、建设并运营高吞吐量数据中心。与军事项目官员、技术供应商及监管机构对接。",
    "t3year": "2008 — 2014",
    "t3title": "Biotechnology Group Inc.",
    "t3role": "首席执行官兼首席技术官",
    "t3desc": "领导 DNA 检测与分析、基因图谱自动化以及全面的人类遗传学研究。在乌克兰、俄罗斯和波罗的海国家发起基因检测项目。与 Harvard Medical School 和 Stanford Biomath 合作，开发被全球领先实验室采用的易于理解的基因报告。",
    "t4year": "2000 — 2012",
    "t4title": "电信项目",
    "t4role": "技术副总裁 / 区域首席技术官 — 东欧与独联体",
    "t4desc": "指导加拿大、意大利、瑞士、乌克兰及波罗的海共和国的国家级基础设施部署。监管 1,000 余名工程与部署人员，涵盖交换系统、宽带扩展及跨境互联等电信运营。实施网络冗余、正常运行时间优化和智能路由核心系统。",
    "t5year": "2006 — 2011",
    "t5title": "XIBI Group Inc.",
    "t5role": "创始人兼首席执行官 · 董事会",
    "t5desc": "创立专注于为大型商业及政府组织提供数据存储与大数据管理服务的技术公司。将公司确立为值得信赖的企业数据解决方案提供商。",
    "t6year": "2000 — 2004",
    "t6title": "DataPeer Inc.",
    "t6role": "创始人兼首席执行官",
    "t6desc": "为中小企业建立数据管理与存储公司。开发独特技术解决方案，使全球终端用户和政府机构能够更快速地追踪信息、更便捷地访问数据。",
    "t7year": "1996 — 2000",
    "t7title": "9 Net Avenue Inc.",
    "t7role": "创始人兼首席执行官",
    "t7desc": "打造了全球最大的主机托管公司之一。2000 年被 Concentric Networks（NASDAQ: CNTX）收购，随后被 XO Communications（NASDAQ: XOXO）收购，峰值市值达 195 亿美元。",
    "t8year": "1994 — 1996",
    "t8title": "Elitan United Inc.",
    "t8role": "首席执行官兼信息技术总监",
    "t8desc": "在马萨诸塞州快速扩张时期，为领先全球组织提供全面 IT 战略与技术服务的领导工作，构建可扩展基础设施和全球 IT 运营。",
    "t9year": "1989 — 1994",
    "t9title": "Astra Corp",
    "t9role": "创始人兼首席执行官",
    "t9desc": "创立欧洲最大的数字收发卫星系统制造商之一。领导研究、操作系统开发、网络软件应用及整体技术战略，获得国际认可。",
    "t10year": "1984 — 1989",
    "t10title": "Nikolaev Shipbuilding Plant",
    "t10role": "电子工程师 — 第六类（最高级）",
    "t10desc": "研发用于向军舰传输机密信息的卫星收发系统。在拥有 93,000 名员工的工厂中，被认定为最高级别的电子工程师——这是其在技术与创新领域卓越职业生涯的起点。",
    "s1title": "高管领导力",
    "s1desc": "在上市公司与私营企业中兼任 CEO/CTO 双重管理，从初创到 IPO 及之后全程引领。",
    "s2title": "IPO 与财务规模化",
    "s2desc": "完整执行公开募股——法律架构、SEC 协调、投资者路演及合规管理。",
    "s3title": "平台架构",
    "s3desc": "为企业自动化、预测性监控和集中化数据管控设计可扩展系统。",
    "s4title": "安全基础设施",
    "s4desc": "为政府、军事及高安全商业平台提供数据中心开发与运营。"
  },
  "recognition": {
    "eyebrow": "奖项",
    "title": "卓越认可",
    "lead": "数十年在商业和创新方面的杰出成就。",
    "industryEyebrow": "行业奖项",
    "industryTitle": "主要荣誉",
    "ipEyebrow": "知识产权",
    "ipTitle": "专利与出版物",
    "eduEyebrow": "教育",
    "eduTitle": "学术资格",
    "pressEyebrow": "媒体",
    "pressTitle": "媒体报道",
    "moreLink": "在 Insights 查看专利、出版物与媒体报道 →",
    "a1title": "年度企业家",
    "a1desc": "Entrepreneur Magazine，1999 — 2001 — 在平台创新与基础设施领域的领导力与突破性成就。",
    "a2title": "美国精准医疗十大公司",
    "a2desc": "Digital Invest Inc. 入选美国精准医疗与数字健康十大最佳公司 — 2023。",
    "a3title": "Who's Who in America",
    "a3desc": "1999 — 2018 年收录 — 因在企业创建与发展方面的卓越成就。",
    "a4title": "Who's Who in the World",
    "a4desc": "2000 — 2004 年收录 — 位列全球科学、工程与商业创新领袖。",
    "a5title": "Who's Who in Science & Engineering",
    "a5desc": "2000 — 2014 年收录 — 因对技术、卫星系统及数字基础设施的贡献。",
    "a6title": "电子工程师 — 第六类",
    "a6desc": "Nikolaev Shipbuilding Plant（93,000 名员工）最高荣誉，表彰卫星收发系统工程成就。",
    "ip1year": "专利",
    "ip1title": "数字卫星 HDTV 系统",
    "ip1role": "随后被 Sony 收购",
    "ip1desc": "获得数字卫星高清电视（HDTV）系统领域专利。该专利随后被 Sony Corporation 收购，验证了这项创新的商业价值。",
    "ip2year": "出版物",
    "ip2title": "技术论文",
    "ip2role": "卫星与光学系统",
    "ip2desc": "专注于卫星与光学数据传输系统的技术论文作者。研究贡献涵盖信号处理、仿真建模及应用于电信、国家基础设施和数字健康的自动化平台。",
    "ip3year": "研究",
    "ip3title": "国际合作",
    "ip3role": "美国与欧洲",
    "ip3desc": "参与国际研究合作与知识转移倡议。为多个行业开发用于数据采集、预测性诊断和云端编排的嵌入式工程系统。",
    "edu1title": "技术科学博士",
    "edu1desc": "2009 — Ukrainian State Marine Technical University",
    "edu2title": "信息技术哲学博士",
    "edu2desc": "2004 — Ukrainian State Marine Technical University",
    "edu3title": "硕士学位",
    "edu3desc": "电子学、数字卫星系统与经济学",
    "press1title": "Healthcare Tech Outlook",
    "press1role": "Digital Invest Inc. 专题报道",
    "press1desc": "Digital Invest Inc. 作为美国精准医疗与数字健康领先企业之一受到专题报道，因其通过 AI、ML 和 DNA 技术变革医疗的创新方法而获得认可。",
    "press1link": "阅读专题 →",
    "press2title": "Top Precision Medicine Solutions",
    "press2role": "行业认可",
    "press2desc": "入选顶尖精准医疗解决方案公司，彰显 Digital Invest 在推进现代医疗保健生物数学方法方面的角色。",
    "press2link": "查看榜单 →"
  },
  "contact": {
    "eyebrow": "联系我们",
    "title": "保持联系",
    "lead": "咨询角色、董事会职位和战略合作。",
    "infoTitle": "直接联系",
    "email": "电子邮件",
    "phone": "电话",
    "location": "地点",
    "locationVal": "Charlotte, North Carolina\nUnited States",
    "linkedin": "LinkedIn",
    "company": "现任公司",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member",
    "formTitle": "发送消息",
    "formLead": "填写以下表格，我会尽快回复。",
    "firstName": "名",
    "lastName": "姓",
    "emailLabel": "电子邮件地址",
    "subject": "主题",
    "message": "消息",
    "inquiryType": "Inquiry Type",
    "inquiryAdvisory": "Advisory / Board Role",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "infoEyebrow": "联系信息"
  },
  "consulting": {
    "eyebrow": "顾问服务",
    "title": "咨询",
    "heroEyebrow": "战略商业指导",
    "heroTitle": "Michael Kofman 专家咨询",
    "heroLead": "Michael Kofman是一位技术愿景家，以动态方式理解当今复杂市场不断演变的需求而著称。作为企业家、董事会成员以及上市和非上市公司的顾问，他在美国和欧洲成功创立了多家公司。",
    "cta": "联系 Michael Kofman",
    "introLead": "Michael Kofman是Digital Invest Inc.首席执行官兼董事会成员。他的专长涵盖高管能力、新兴技术与市场的战略分析、信息安全与隐私、研究、科学与开发、行政管理以及投资。",
    "specialtiesEyebrow": "专注领域",
    "specialtiesTitle": "Michael Kofman 的专业方向"
  },
  "insights": {
    "eyebrow": "思想领导力",
    "title": "洞见",
    "heroTitle": "成功洞见",
    "selectedEyebrow": "精选亮点",
    "selectedTitle": "重要认可",
    "allPressTitle": "全部媒体报道",
    "quotesEyebrow": "媒体评价",
    "quotesTitle": "行业认可与引述",
    "articlesEyebrow": "观点洞察",
    "articlesTitle": "高管观点"
  },
  "cta": {
    "eyebrow": "合作共赢",
    "title": "申请咨询或演讲",
    "lead": "适用于顾问合作、董事会职位、演讲邀约及战略合作伙伴关系。",
    "button": "联系我"
  },
  "speaking": {
    "eyebrow": "演讲活动",
    "title": "邀请 Michael Kofman 演讲",
    "lead": "可就高管领导力、技术战略、数字健康、数据基础设施和公司治理进行演讲。",
    "topicsEyebrow": "演讲主题",
    "topicsTitle": "专业领域",
    "topicsLead": "主题内容基于其在美国和欧洲创办并领导企业数十年的实践经验。",
    "processEyebrow": "邀请方式",
    "processTitle": "预订流程",
    "process1title": "提交咨询",
    "process1desc": "请通过联系表单或发送邮件至 mkofman@mkofman.com，提供活动详情、受众信息及期望主题。",
    "process2title": "确认范围",
    "process2desc": "确认形式（主题演讲、论坛对谈、董事会会议或高管圆桌）及相关执行安排。",
    "process3title": "交付价值",
    "process3desc": "演讲内容基于在数据存储、政务科技和精准医疗领域的真实业务成果。",
    "cta": "申请演讲邀约"
  },
  "caseStudies": {
    "eyebrow": "案例研究",
    "title": "打造可规模化增长的公司",
    "lead": "精选其在数据基础设施与数字健康领域创办并领导企业的成果。",
    "cs1eyebrow": "数据基础设施 · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "挑战",
    "cs1challengeText": "在快速整合的科技市场中建立并扩展一家数据存储公司。",
    "cs1action": "策略",
    "cs1actionText": "1996 年创立 9 Net Avenue Inc.，公司迅速成长为全球最大的数据存储企业之一。",
    "cs1result": "成果",
    "cs1resultText": "到 2000 年，公司先后被 Concentric Networks（NASDAQ: CNTX）和 XO Communications（NASDAQ: XOXO）收购，峰值市值达到 195 亿美元。收购后，他积累了在上市公司、董事会治理及最高层战略决策方面的丰富经验。",
    "cs2eyebrow": "数字健康 · 2021 — 至今",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "挑战",
    "cs2challengeText": "通过全新的生物数学平台，结合科学、DNA 技术、AI 与 ML，革新医学中的过时方法。",
    "cs2action": "策略",
    "cs2actionText": "创立并推动 Digital Invest Inc. 从零发展到成功 IPO，主导完整上市流程，包括法律架构、财务合规、投资者路演及与 SEC 协调。同时负责美国和欧洲多个数据中心的设计、建设与运营。",
    "cs2result": "成果",
    "cs2resultText": "实现持续财务增长，使公司跻身美国精准医疗企业前十（2023）。Digital Invest 旗下包括 Human Digital Model、BioMath Life 及 Aero-Ground Robotics Operations Network 等创新项目。"
  },
  "mediaKit": {
    "eyebrow": "媒体与活动",
    "title": "媒体资料包",
    "lead": "面向媒体、会议及董事会合作咨询的官方简介、视觉资料与联系方式。",
    "bioEyebrow": "人物简介",
    "bioTitle": "官方简介",
    "bioShortLabel": "50 词",
    "bioShort": "Michael Kofman 是 Digital Invest Inc. 的 CEO，同时担任董事会成员、顾问，并在美国和欧洲创办多家科技与数字健康企业。",
    "bioMediumLabel": "150 词",
    "bioMedium": "Michael Kofman 是 Digital Invest Inc. 的 CEO，并担任其董事会成员。作为技术远见者，他以动态方式洞察当今复杂市场不断变化的需求。作为企业家、董事会成员以及公私营企业顾问，他已在美国和欧洲成功创办多家公司。其专长覆盖高管领导力、新兴技术与市场战略分析、信息安全与隐私、科研与开发、管理及投资。",
    "bioLongLabel": "500 词",
    "bioLong": "Michael Kofman 是 Digital Invest Inc. 的 CEO，并担任其董事会成员。作为技术远见者，他以动态方式洞察当今复杂市场不断变化的需求。其专长涵盖高管领导力、新兴技术与市场战略分析、信息安全与隐私、科研与开发、管理及投资。作为企业家、董事会成员以及公私营企业顾问，Michael Kofman 在美国和欧洲成功创办了多家公司。他创立了 9 Net Avenue Inc.，并在峰值市值达 195 亿美元时被收购；目前他领导 Digital Invest Inc. 推动数据存储与先进技术创新。他曾主导政府及国防项目的技术战略，创立了数据存储领域的 XIBI Group Inc. 与 DataPeer Inc.，并在 Biotechnology Group Inc. 中发挥关键作用。他与 Harvard Medical School 和 Stanford Biomath 合作开展遗传报告项目。著有卫星与光学系统技术论文；其数字卫星 HDTV 专利被 Sony 收购。教育背景：技术科学博士（2009）、信息技术博士（2004）、Ukrainian State Marine Technical University。",
    "photosEyebrow": "摄影素材",
    "photosTitle": "授权图片",
    "photosLead": "如需高清肖像照，请发送邮件至 mkofman@mkofman.com。",
    "contactEyebrow": "媒体联系人",
    "contactTitle": "媒体咨询",
    "contactLead": "用于采访、演讲邀请及媒体合作请求。"
  },
  "articles": {
    "backLink": "← 返回 Insights",
    "article1date": "高管观点",
    "article1title": "从工程实践到全球数据基础设施",
    "article1p1": "我的职业生涯始于乌克兰尼古拉耶夫造船厂，当时负责开发用于向军舰传输机密信息的卫星收发系统。我被评为最高等级电子工程师，即在拥有 93,000 名员工的工厂中达到第 6 类工程师级别。",
    "article1p2": "1989 至 1994 年，我创立并领导了 Astra Corp，它是欧洲最大的数字卫星收发系统制造商之一。1994 至 1996 年，作为 Elitan United Inc. 的 CEO，我帮助公司从 9 人扩展到全球 4,000 余名员工。",
    "article1p3": "1996 年，我创立了 9 Net Avenue Inc.，该公司迅速成长为全球最大的数据存储企业之一。到 2000 年，公司被 Concentric Networks（NASDAQ: CNTX）和 XO Communications（NASDAQ: XOXO）收购，峰值市值达到 195 亿美元。",
    "article1p4": "2001 至 2019 年，我负责政府、国防及国有企业项目的技术战略，主导了美国和欧洲在大数据、安全基础设施及高吞吐数据中心方面的大型计划。",
    "article2date": "数字健康",
    "article2title": "精准医疗与科学技术融合",
    "article2p1": "我始终坚信生命科学与前沿技术结合所蕴含的巨大潜力。在 Biotechnology Group Inc.（2008-2014）期间，我们重点推进 DNA 检测与分析、遗传画像流程自动化以及全面的人类遗传学研究。",
    "article2p2": "在我的领导下，乌克兰、俄罗斯和波罗的海国家启动了多个成功的基因检测项目。与 Harvard Medical School 和 Stanford Biomath 的合作中，我在为医生和患者开发易于理解的基因报告方面发挥了关键作用。",
    "article2p3": "我们于 2021 年创立 Digital Invest Inc.，专注生物数学领域，借助科学、DNA 技术、AI 与 ML 改变传统医疗方式。公司从创立发展至成功 IPO，并在 2023 年被评为美国精准医疗与数字健康领域十佳公司之一。",
    "article2p4": "Digital Invest 旗下包括 Human Digital Model、BioMath Life 与 Aero-Ground Robotics Operations Network 等创新项目，持续推动数据科学与生命科学的深度融合。"
  }
};
