window.__LANG_zh = {
  "ui": {
    "toggleTheme": "切换浅色/深色主题",
    "selectLanguage": "选择语言",
    "messageSent": "消息已发送",
    "sendMessage": "发送消息",
    "toggleNav": "打开菜单",
    "sending": "发送中…",
    "formError": "发送失败。请直接发送电子邮件。",
    "present": "至今"
  },
  "nav": {
    "home": "首页",
    "about": "简介",
    "ventures": "企业",
    "career": "职业",
    "recognition": "荣誉",
    "contact": "联系",
    "consulting": "咨询",
    "insights": "洞见",
    "speaking": "演讲邀约",
    "caseStudies": "案例研究",
    "mediaKit": "媒体资料包",
    "groupMain": "主要",
    "groupServices": "服务",
    "groupWork": "成果",
    "briefIpo": "Brief: IPO",
    "briefGenetic": "Brief: Genetic Data",
    "briefAi": "Brief: AI Strategy",
    "articleInfra": "Data Infrastructure",
    "articleHealth": "Precision Medicine",
    "board": "Board Advisory",
    "thesis": "Leadership Thesis",
    "press": "Press",
    "ip": "Intellectual Property"
  },
  "footer": {
    "navigation": "导航",
    "ventures": "企业",
    "connect": "联系",
    "desc": "首席执行官、技术专家和创始人。数字医疗、数据基础设施、机器人。",
    "copyright": "© {year} Michael Kofman. 版权所有。",
    "writeTitle": "给我留言",
    "writeEmail": "您的邮箱",
    "writeMessage": "您的留言",
    "writeSend": "发送",
    "writeSuccess": "谢谢 — 您的留言已发送。",
    "more": "更多",
    "privacy": "隐私政策"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — 首席执行官",
      "description": "Michael Kofman 官方网站——技术与数字医疗领域的首席执行官、创始人和董事会顾问。"
    },
    "about": {
      "title": "简介 — Michael Kofman",
      "description": "Michael Kofman 传记——Digital Invest Inc. 首席执行官，AGRON Inc. 创始人。"
    },
    "ventures": {
      "title": "企业 — Michael Kofman",
      "description": "Michael Kofman创办和领导的企业——从Digital Invest Inc.到9 Net Avenue Inc.——在科技和医疗领域构建变革性业务。"
    },
    "career": {
      "title": "职业 — Michael Kofman",
      "description": "Michael Kofman职业历程——从卫星工程到全球科技和医疗公司CEO。"
    },
    "recognition": {
      "title": "荣誉 — Michael Kofman",
      "description": "Michael Kofman获得的奖项与荣誉——年度企业家、Who's Who、专利和行业殊荣。"
    },
    "contact": {
      "title": "联系 — Michael Kofman",
      "description": "联系Michael Kofman——Digital Invest Inc. CEO。咨询顾问职位、演讲邀约和商业合作。"
    },
    "consulting": {
      "title": "咨询 — Michael Kofman",
      "description": "与Michael Kofman的顾问职位、董事会成员、演讲邀约和战略合作。"
    },
    "insights": {
      "title": "洞见 — Michael Kofman",
      "description": "Michael Kofman的出版物、媒体报道、专利和行业认可。"
    },
    "speaking": {
      "title": "演讲邀约 — Michael Kofman",
      "description": "邀请 Michael Kofman 就高管领导力、技术战略、数字健康和公司治理发表演讲。"
    },
    "caseStudies": {
      "title": "案例研究 — Michael Kofman",
      "description": "Michael Kofman 职业生涯案例研究：9 Net Avenue Inc. 与 Digital Invest Inc."
    },
    "mediaKit": {
      "title": "媒体资料包 — Michael Kofman",
      "description": "面向媒体与活动主办方的官方简介、照片及联系方式。"
    },
    "article1": {
      "title": "从工程到全球基础设施 — Michael Kofman",
      "description": "Michael Kofman 讲述自己从卫星工程到创办全球数据基础设施公司的职业路径。"
    },
    "article2": {
      "title": "精准医疗与科技融合 — Michael Kofman",
      "description": "Michael Kofman 谈生命科学与 AI、ML 及 DNA 技术在现代医学中的融合。"
    },
    "privacy": {
      "title": "隐私政策 — Michael Kofman",
      "description": "mkofman.com 隐私政策——联系表单与分析说明。"
    },
    "board": {
      "title": "Board Advisory — Michael Kofman",
      "description": "Board service and strategic advisory from Michael Kofman for technology, healthcare, infrastructure, and growth-stage organizations."
    },
    "thesis": {
      "title": "Leadership Thesis — Michael Kofman",
      "description": "Michael Kofman's principles for building durable companies, governing technology, and leading through consequential change."
    },
    "press": {
      "title": "Press Archive — Michael Kofman",
      "description": "Selected press coverage, awards, and media references spanning Michael Kofman's career in technology and entrepreneurship."
    },
    "ip": {
      "title": "Intellectual Property — Michael Kofman",
      "description": "Patents, publications, and applied research by Michael Kofman across computing, communications, data, and digital health."
    },
    "briefIpo": {
      "title": "What an IPO Changes — Michael Kofman",
      "description": "An executive brief on the operating discipline, governance, and accountability required before and after an initial public offering."
    },
    "briefGenetic": {
      "title": "From Genetic Data to Clinical Decisions — Michael Kofman",
      "description": "An executive brief on translating genomic information into responsible, useful, and scalable clinical intelligence."
    },
    "briefAi": {
      "title": "AI Strategy Beyond the Pilot — Michael Kofman",
      "description": "An executive brief on moving artificial intelligence from experimentation to governed, measurable enterprise capability."
    },
    "deck": {
      "title": "Executive Overview — Michael Kofman",
      "description": "Private executive overview for qualified introductions."
    }
  },
  "home": {
    "heroEyebrow": "Michael Kofman 官方网站",
    "heroTitle1": "基业长青。",
    "heroTitle2": "审慎领导。",
    "heroCta": "了解我的故事",
    "heroAlt": "Michael Kofman — CEO and Strategic Technologist",
    "quote1text": "入选美国精准医疗与数字健康领域的领先公司。",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "年度企业家——因平台创新与基础设施领域的领导力与突破成就而获认可。",
    "quote2author": "Entrepreneur Magazine, 1999 — 2001",
    "quote3text": "Digital Invest Inc. 入选美国精准医学与数字健康十大最佳公司。",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "工程精度与商业战略并重——从卫星系统到195亿美元基础设施，再到精准医疗。",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "认识 Michael Kofman",
    "aboutTitle": "经得起时间考验的公司",
    "aboutLead1": "Digital Invest Inc. 首席执行官兼 AGRON Inc. 创始人。在美国和欧洲创立并领导多家公司。",
    "aboutLead2": "从 9 Net Avenue（峰值估值195亿美元）到 Digital Invest 精准医疗和 AGRON 机器人——四十年深耕基础设施、医疗与国防。",
    "aboutLink": "阅读完整传记",
    "expertiseEyebrow": "重点领域",
    "expertiseTitle": "跨行业高管领导力",
    "expertiseLead": "四十年在基础设施、医疗和机器人领域的创业、咨询与投资。",
    "exp1title": "CEO与创始人",
    "exp1desc": "从创立到成功上市，创办并扩展了多家公司，在科技与医疗领域实现了持续财务增长和全球布局。",
    "exp1link": "查看企业 →",
    "exp2title": "技术架构师",
    "exp2desc": "为政府、军事和电信领域设计安全通信、预测分析引擎和国家级数据集成平台。",
    "exp2link": "查看职业 →",
    "exp3title": "数字健康",
    "exp3desc": "通过人工智能、机器学习和DNA技术引领医学变革。曾与哈佛医学院和Stanford Biomath合作开展基因报告项目。",
    "exp3link": "Digital Invest →",
    "exp4title": "董事会顾问",
    "exp4desc": "担任董事会成员，为上市和非上市公司提供战略方向、公司治理和技术驱动增长方面的咨询。",
    "exp4link": "咨询 →",
    "stat1": "领导年数",
    "stat2": "创立公司",
    "stat3": "峰值市值",
    "stat4": "扩展员工",
    "recEyebrow": "荣誉",
    "recTitle": "奖项与荣誉",
    "recLead": "在创业、医学和工程领域获得行业奖项与同行认可。",
    "award1title": "年度企业家",
    "award1desc": "Entrepreneur Magazine, 1999 — 2001",
    "award2title": "精准医疗前十",
    "award2desc": "Digital Invest Inc. — U.S., 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "查看所有荣誉",
    "heroSub": "面向公私营企业的 CEO、董事会顾问与战略技术专家，专注科技、数据存储与数字健康领域。",
    "primaryCta": "申请顾问咨询",
    "secondaryCta": "查看案例研究",
    "featuredEyebrow": "媒体报道",
    "caseStudiesEyebrow": "可验证成果",
    "caseStudiesTitle": "案例研究",
    "caseStudiesLead": "从创立到并购和 IPO，持续推动企业创建、扩张与领导。",
    "caseStudiesLink": "查看全部案例研究 →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "打造了全球最大的数据存储企业之一，并在峰值市值 195 亿美元时被收购。",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "从创立扩展至成功 IPO，入选 2023 年美国精准医疗十强企业。",
    "cs3title": "AGRON Inc.",
    "cs3desc": "Founded in 2026 — the AGRON Ecosystem for UAV capability development, geospatial systems, and maritime intelligence.",
    "boardCtaEyebrow": "Board & Advisory",
    "boardCtaTitle": "Experience for the Decisions That Define an Enterprise",
    "boardCtaLead": "Independent perspective for boards and leaders navigating technology, governance, transformation, and growth.",
    "boardCtaBtn": "Explore Board Advisory",
    "testimonialsEyebrow": "Trusted Perspective",
    "testimonialsTitle": "What Colleagues Value",
    "videoEyebrow": "Executive Perspective",
    "videoTitle": "Leadership at the Intersection of Technology and Enterprise",
    "videoLead": "A concise introduction to the principles, experience, and long-term perspective behind Michael Kofman's work.",
    "videoCta": "Read Leadership Thesis →",
    "heroName": "Michael Kofman",
    "heroRole": "Technology Executive · Founder · Board Advisor",
    "introText": "Michael Kofman is a technology executive and company founder whose career spans satellite and communications engineering, internet infrastructure, public technology companies, and life sciences. He founded 9 Net Avenue Inc., later acquired by Concentric Networks and XO Communications. He is CEO of Digital Invest Inc., working in bio-mathematical medicine and genomic intelligence, and founder of AGRON Inc., focused on autonomous aerial-ground operations and geospatial systems. He serves on boards and advises leaders in technology, health, and infrastructure.",
    "introLink": "Full biography →",
    "currentEyebrow": "Current Work",
    "currentTitle": "Where Focus Is Now",
    "currentDiTitle": "Digital Invest Inc.",
    "currentDiDesc": "Bio-mathematical medicine, genomic data, and clinical intelligence — applying AI, machine learning, and DNA technologies to responsible health outcomes.",
    "currentDiLink": "Ventures →",
    "currentAgTitle": "AGRON Inc.",
    "currentAgDesc": "Autonomous aerial-ground operations, UAV capability development, geospatial systems, and maritime intelligence infrastructure.",
    "currentAgLink": "agron1.com →",
    "careerEyebrow": "Selected Career",
    "careerTitle": "Continuity Across Technology Periods",
    "careerLead": "Selected milestones from engineering through current work in autonomous systems.",
    "career1title": "Engineering & Communications",
    "career1desc": "Satellite transceiver systems, digital communications, and early engineering leadership.",
    "career2title": "Internet & Infrastructure",
    "career2desc": "Internet infrastructure, data centers, storage, and telecommunications at scale.",
    "career3title": "Technology Companies & Public Markets",
    "career3desc": "Company-building, acquisitions, and public-company experience including 9 Net Avenue Inc.",
    "career4title": "Life Sciences & Human Data",
    "career4desc": "Biotechnology, genetic data, precision medicine, and health intelligence platforms.",
    "career5title": "Autonomous Systems",
    "career5desc": "Aerial-ground robotics, UAV operations, and geospatial infrastructure.",
    "careerLink": "Full career →",
    "perspectivesEyebrow": "Perspectives",
    "perspectivesTitle": "Selected Writing",
    "perspectivesLink": "All insights →",
    "footerHomeDesc": "Technology executive, founder, and board advisor."
  },
  "about": {
    "eyebrow": "关于 Michael Kofman",
    "title": "三十年历程",
    "lead": "工程、基础设施、数字医疗和机器人领域的企业家与高管。",
    "glance": "概览",
    "role": "现任职位",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "地点",
    "locationVal": "Charlotte, North Carolina",
    "education": "教育",
    "educationVal": "Doctor of Technical Sciences (2009)\nPh.D. in Information Technology (2004)\nMaster's in Electronic Engineering",
    "university": "大学",
    "universityVal": "Ukrainian State Marine Technical University",
    "languages": "语言",
    "languagesVal": "English, Russian, Ukrainian",
    "contactLabel": "联系",
    "principlesEyebrow": "Operating Principles",
    "principlesTitle": "How I Lead",
    "p1title": "Understand the System",
    "p1text": "Before changing an organization, understand its incentives, architecture, constraints, and sources of trust.",
    "p2title": "Make Accountability Explicit",
    "p2text": "Clear ownership and measurable outcomes turn strategy from presentation material into operating reality.",
    "p3title": "Leave Stronger Institutions",
    "p3text": "Leadership should compound capability by developing people, improving decisions, and building systems that endure.",
    "archiveEyebrow": "From the Archive",
    "archiveTitle": "Moments Across the Journey",
    "archiveLead": "Selected photographs from company building, infrastructure, and leadership — from the 9 Net Avenue years to today.",
    "photo9netTitle": "9 Net Avenue",
    "photo9netCaption": "Founder & CEO — one of the world’s largest hosting companies, later acquired at a peak market value of $19.5 billion.",
    "photoServerTitle": "Data Infrastructure",
    "photoServerCaption": "Hands-on years in storage, networking, and high-density server environments at DataPeer and related ventures.",
    "photoTodayTitle": "Today",
    "photoTodayCaption": "Board advisory, strategic technology leadership, and building the next generation of digital health and infrastructure companies.",
    "secIntroTitle": "Introduction",
    "secTechTitle": "技术与基础设施",
    "secBusinessTitle": "Business",
    "secCurrentTitle": "Current Work",
    "secBackgroundTitle": "Background",
    "recordLink": "The Record →",
    "bioP1": "Michael Kofman 是 Digital Invest Inc. 首席执行官兼 AGRON Inc. 创始人，担任 Digital Invest 董事会成员。其工作涵盖在美国和欧洲的公司创建、技术战略、安全、研究与投资。",
    "bioP2": "As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. In 2026 he founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network. He also created Digital Invest, dedicated to the bio-mathematical sphere and transforming medicine through science, DNA technologies, AI, and ML.",
    "secBioTitle": "精准医疗与生物技术",
    "secBioP1": "在创立 Digital Invest 之前，他在 Biotechnology Group Inc.（2008 — 2014）的成功中发挥了重要作用。该公司致力于 DNA 检测与分析、基因图谱构建流程自动化以及全面的人类遗传学研究。科夫曼先生坚信，将生命科学与最新技术进展相结合具有巨大潜力。",
    "secBioP2": "在他的领导下，乌克兰、俄罗斯和波罗的海国家成功启动了基因检测项目。这一独特经验不断融入现代技术与新设备。在与 Harvard Medical School 和 Stanford Biomath 的合作中，科夫曼先生在开发医生与患者均易于理解的基因报告方面发挥了关键作用。这一创新方法已被美国及海外领先实验室广泛采用。",
    "secTechP1": "2001 年至 2019 年，科夫曼先生为政府、国防及国有企业项目制定技术战略——包括面向国有企业的复杂技术倡议。2001 年 9·11 事件后，他领导了以大数据、安全基础设施和高吞吐量数据中心为核心的美国政府大型项目，覆盖美国与欧洲。",
    "secTechP2": "2006 年，科夫曼先生创立了 XIBI Group Inc.——一家他担任董事会成员的技术公司。这家美国公司专注于为大型商业及政府组织提供数据存储与大数据管理服务。",
    "secTechP3": "2000 年至 2004 年，科夫曼先生领导 DataPeer Inc.——一家为中小企业提供广泛信息存储服务的数据管理与存储公司。在 DataPeer，他开发了独特的技术解决方案，使全球个人用户和政府机构能够更快速地追踪信息、更便捷地访问数据。",
    "secTechP4": "1996 年，科夫曼先生创立了 9 Net Avenue Inc.，该公司迅速成为全球最大的主机托管公司之一。2000 年，9 Net Avenue 被 Concentric Networks（NASDAQ: CNTX）收购，随后被 XO Communications（NASDAQ: XOXO）收购，峰值市值达 195 亿美元。",
    "secPost9NetP1": "在 9 Net Avenue 被收购后，科夫曼先生积累了在上市公司工作、参与董事会并参与最高管理层战略决策的丰富经验。",
    "secEarlyTitle": "早期职业与工程",
    "secEarlyP1": "1994 年至 1996 年，科夫曼先生担任 Elitan United Inc. 首席执行官兼信息技术总监——这是一家位于马萨诸塞州的 IT 公司，为领先全球组织提供全面战略与技术服务。他在开发和管理可扩展基础设施方面发挥了关键作用，推动公司从仅 9 名员工增长至全球 4,000 余人。",
    "secEarlyP2": "1989 年至 1994 年，他创立并担任 Astra Corp 首席执行官，该公司是欧洲最大的数字收发卫星系统制造商之一，在卫星设备领域获得国际认可。其职责涵盖研究、操作系统开发、网络软件应用及整体技术战略。",
    "secEarlyP3": "1984 年至 1989 年，科夫曼先生在乌克兰尼古拉耶夫造船厂工作，积极参与用于向军舰及回传传输机密信息的卫星收发系统的研发与制造。他被认定为最高级别的电子工程师，获得第六类职称——在该拥有 9.3 万名员工的工厂中，这是最高荣誉。",
    "secResearchTitle": "研究与专利",
    "secResearchP1": "Michael Kofman 是专注于卫星与光学数据传输系统的技术论文作者。他还获得了数字卫星高清电视（HDTV）系统领域的专利，该专利随后被 Sony 收购。",
    "secAgronTitle": "Robotics, UAV & Maritime Intelligence",
    "secAgronP1": "In 2026, Mr. Kofman founded AGRON Inc. to build the AGRON Ecosystem — a corporate operating architecture for aerial and ground robotics, governed mission execution, and network infrastructure connecting teams, assets, and operational data. The ecosystem delivers consulting, assessment, capability development, and training for UAV and Counter-UAS organizations, alongside maritime intelligence and security services at agron1.com.",
    "secBusinessP1": "Founded and led multiple technology companies including 9 Net Avenue Inc., DataPeer Inc., XIBI Group Inc., and Elitan United Inc. Full chronology is documented in The Record.",
    "secCurrentP1": "CEO of Digital Invest Inc., focused on bio-mathematical medicine and genomic intelligence. Founder of AGRON Inc., building autonomous aerial-ground operations, UAV capability development, and geospatial systems.",
    "secBackgroundP1": "Doctor of Technical Sciences (2009) and Ph.D. in Information Technology (2004), Ukrainian State Marine Technical University. Author of technical papers on satellite and optical systems; patent in digital satellite HDTV subsequently acquired by Sony."
  },
  "ventures": {
    "eyebrow": "企业组合",
    "title": "创立并领导的公司",
    "lead": "从精准医疗和机器人到全球数据基础设施——在美国和欧洲创立、扩展并领导。",
    "ecosystemEyebrow": "Venture Ecosystem",
    "ecosystemTitle": "Companies Across Technology Frontiers",
    "ecosystemLead": "A portfolio shaped by recurring themes: trusted data, intelligent infrastructure, human health, and systems built for scale.",
    "statusActive": "Active",
    "statusExited": "Exited",
    "statusLegacy": "Legacy",
    "v1lesson": "Lesson: infrastructure wins when reliability, economics, and customer trust improve together.",
    "v2lesson": "Lesson: precision medicine requires equal discipline in science, software, privacy, and clinical usefulness.",
    "v3lesson": "Lesson: autonomy creates value only when sensing, communications, and human oversight form one resilient system.",
    "v5lesson": "经验：基础设施的规模来自长期运营卓越，而非退出前的冲刺。",
    "currentEyebrow": "Current",
    "historyEyebrow": "Selected History",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — an Aerial-Ground Robotics Operations Network spanning UAV and Counter-UAS consulting, technology assessment, capability development, training infrastructure, product validation, geospatial systems (ISDRI), and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "v0role": "Founder",
    "v0year": "2026 — Present",
    "v1highlight": "2023 年美国精准医疗十大公司",
    "v1p1": "从创立到成功 IPO，创办并规模化发展 Digital Invest。公司致力于生物数学领域，通过 AI、ML 和 DNA 技术变革医疗。",
    "v1role": "创始人兼首席执行官 · 董事会成员",
    "v1year": "2021 — 至今",
    "v2highlight": "Harvard Medical School 与 Stanford Biomath 合作伙伴",
    "v2p1": "DNA 检测与分析、基因图谱自动化以及全面的人类遗传学研究。在乌克兰、俄罗斯和波罗的海国家发起基因检测项目。",
    "v2p2": "与 Harvard Medical School 和 Stanford Biomath 合作，开发被全球领先实验室采用的基因报告。",
    "v2role": "首席执行官兼首席技术官",
    "v2year": "2008 — 2014",
    "v3highlight": "企业与政府数据解决方案",
    "v3p1": "为大型商业及政府组织提供数据存储与大数据管理服务。将公司确立为值得信赖的企业数据解决方案提供商。",
    "v3role": "创始人兼首席执行官 · 董事会",
    "v3year": "2006 — 2011",
    "v4highlight": "全球数据管理平台",
    "v4p1": "为中小企业提供数据管理与存储服务。开发解决方案，使全球终端用户和政府机构能够更快速地追踪信息、更便捷地访问数据。",
    "v4role": "创始人兼首席执行官",
    "v4year": "2000 — 2004",
    "v5highlight": "被收购 · 峰值市值 195 亿美元",
    "v5p1": "打造了全球最大的主机托管公司之一。2000 年被 Concentric Networks（NASDAQ: CNTX）收购，随后被 XO Communications（NASDAQ: XOXO）收购，峰值市值达 195 亿美元。",
    "v5role": "创始人兼首席执行官",
    "v5year": "1996 — 2000",
    "v6highlight": "全球 IT 战略与基础设施",
    "v6p1": "马萨诸塞州 IT 公司，为领先全球组织提供全面战略与技术服务。领导可扩展基础设施开发及全球 IT 运营。",
    "v6role": "首席执行官兼信息技术总监",
    "v6year": "1994 — 1996",
    "v7highlight": "欧洲卫星系统领导者",
    "v7p1": "欧洲最大的数字收发卫星系统制造商之一。领导研究、操作系统开发、网络软件应用及整体技术战略。",
    "v7role": "创始人兼首席执行官",
    "v7year": "1989 — 1994",
    "v8highlight": "军用卫星系统工程",
    "v8p1": "研发用于向军舰传输机密信息的卫星收发系统。在拥有 93,000 名员工的工厂中，被认定为最高级别的电子工程师。",
    "v8role": "电子工程师 · 最高类别（第六类）",
    "v8year": "1984 — 1989"
  },
  "career": {
    "eyebrow": "职业历程",
    "title": "三十年的高管领导力",
    "lead": "从卫星工程到全球科技企业。",
    "timelineEyebrow": "时间线",
    "timelineTitle": "关键里程碑",
    "strengthsEyebrow": "核心优势",
    "strengthsTitle": "专业领域",
    "filterAll": "All",
    "filterHealthcare": "Healthcare",
    "filterInfrastructure": "Infrastructure",
    "filterDefense": "Defense",
    "filterTelecom": "Telecommunications",
    "periodCurrent": "Current",
    "periodCurrentLead": "Principal companies and projects in active development.",
    "period1title": "Engineering & Communications",
    "period1lead": "Early engineering, satellite systems, communications, and related technology work.",
    "period2title": "Internet & Infrastructure",
    "period2lead": "Internet infrastructure, telecommunications, data centers, storage, and related companies.",
    "period3title": "Companies & Public Markets",
    "period3lead": "Company building, transactions, public-company involvement, and executive roles.",
    "period4title": "Life Sciences & Human Data",
    "period4lead": "Biotechnology, health-related technology, data, and precision medicine.",
    "period5title": "Government & Defense Programs",
    "period5lead": "Technology strategy and delivery for government, defense, and state-owned enterprise programs.",
    "t0desc": "Founded AGRON Inc. to build the AGRON Ecosystem — consulting, assessment, capability development, training infrastructure, and product support for UAV and Counter-UAS programmes, plus AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure. Connects aerial and ground robotics, governed mission execution, and network infrastructure linking teams, assets, and operational data.",
    "t0role": "Founder",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — Present",
    "s1desc": "在上市公司与私营企业中兼任 CEO/CTO 双重管理，从初创到 IPO 及之后全程引领。",
    "s1title": "高管领导力",
    "s2desc": "完整执行公开募股——法律架构、SEC 协调、投资者路演及合规管理。",
    "s2title": "IPO 与财务规模化",
    "s3desc": "为企业自动化、预测性监控和集中化数据管控设计可扩展系统。",
    "s3title": "平台架构",
    "s4desc": "为政府、军事及高安全商业平台提供数据中心开发与运营。",
    "s4title": "安全基础设施",
    "t10desc": "研发用于向军舰传输机密信息的卫星收发系统。在拥有 93,000 名员工的工厂中，被认定为最高级别的电子工程师——这是其在技术与创新领域卓越职业生涯的起点。",
    "t10role": "电子工程师 — 第六类（最高级）",
    "t10title": "Nikolaev Shipbuilding Plant",
    "t10year": "1984 — 1989",
    "t1desc": "从创立到成功 IPO，创办并规模化发展公司。领导完整的公开募股流程——法律架构、财务合规、投资者路演及 SEC 协调。指导美国与欧洲多个数据中心的设计、建设与运营。构建企业级软件系统，实现自动化、预测性监控和集中化数据管控。实现持续财务增长，使公司跻身 2023 年美国精准医疗十大公司之列。",
    "t1role": "创始人兼首席执行官",
    "t1title": "Digital Invest Inc.",
    "t1year": "2021 — 至今",
    "t2desc": "为涉及美国政府机构、盟国国防系统及国有企业的机密与高敏感项目制定并交付技术战略。领导跨多个行业国有企业的复杂技术项目。2001 年 9·11 事件后，主导以大数据、安全通信、预测分析和国家级数据整合为核心的大规模政府倡议——包括在美国与欧洲设计、建设并运营高吞吐量数据中心。与军事项目官员、技术供应商及监管机构对接。",
    "t2role": "首席技术顾问 / 项目架构师",
    "t2title": "GovTech、国防与国有项目",
    "t2year": "2001 — 2019",
    "t3desc": "领导 DNA 检测与分析、基因图谱自动化以及全面的人类遗传学研究。在乌克兰、俄罗斯和波罗的海国家发起基因检测项目。与 Harvard Medical School 和 Stanford Biomath 合作，开发被全球领先实验室采用的易于理解的基因报告。",
    "t3role": "首席执行官兼首席技术官",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4desc": "指导加拿大、意大利、瑞士、乌克兰及波罗的海共和国的国家级基础设施部署。监管 1,000 余名工程与部署人员，涵盖交换系统、宽带扩展及跨境互联等电信运营。实施网络冗余、正常运行时间优化和智能路由核心系统。",
    "t4role": "技术副总裁 / 区域首席技术官 — 东欧与独联体",
    "t4title": "电信项目",
    "t4year": "2000 — 2012",
    "t5desc": "创立专注于为大型商业及政府组织提供数据存储与大数据管理服务的技术公司。将公司确立为值得信赖的企业数据解决方案提供商。",
    "t5role": "创始人兼首席执行官 · 董事会",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6desc": "为中小企业建立数据管理与存储公司。开发独特技术解决方案，使全球终端用户和政府机构能够更快速地追踪信息、更便捷地访问数据。",
    "t6role": "创始人兼首席执行官",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "打造了全球最大的主机托管公司之一。2000 年被 Concentric Networks（NASDAQ: CNTX）收购，随后被 XO Communications（NASDAQ: XOXO）收购，峰值市值达 195 亿美元。",
    "t7role": "创始人兼首席执行官",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8desc": "在马萨诸塞州快速扩张时期，为领先全球组织提供全面 IT 战略与技术服务的领导工作，构建可扩展基础设施和全球 IT 运营。",
    "t8role": "首席执行官兼信息技术总监",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9desc": "创立欧洲最大的数字收发卫星系统制造商之一。领导研究、操作系统开发、网络软件应用及整体技术战略，获得国际认可。",
    "t9role": "创始人兼首席执行官",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994"
  },
  "recognition": {
    "eyebrow": "奖项",
    "title": "奖项与认可",
    "lead": "涵盖创业、精准医疗、工程和领导力的荣誉。",
    "industryEyebrow": "行业奖项",
    "industryTitle": "主要荣誉",
    "ipEyebrow": "知识产权",
    "ipTitle": "专利与出版物",
    "eduEyebrow": "教育",
    "eduTitle": "学术资格",
    "pressEyebrow": "媒体",
    "pressTitle": "媒体报道",
    "moreLink": "在 Insights 查看专利、出版物与媒体报道 →",
    "a1title": "年度企业家",
    "a1desc": "Entrepreneur Magazine，1999 — 2001 — 在平台创新与基础设施领域的领导力与突破性成就。",
    "a2title": "美国精准医疗十大公司",
    "a2desc": "Digital Invest Inc. 入选美国精准医疗与数字健康十大最佳公司 — 2023。",
    "a3title": "Who's Who in America",
    "a3desc": "1999 — 2018 年收录 — 因在企业创建与发展方面的卓越成就。",
    "a4title": "Who's Who in the World",
    "a4desc": "2000 — 2004 年收录 — 位列全球科学、工程与商业创新领袖。",
    "a5title": "Who's Who in Science & Engineering",
    "a5desc": "2000 — 2014 年收录 — 因对技术、卫星系统及数字基础设施的贡献。",
    "a6title": "电子工程师 — 第六类",
    "a6desc": "Nikolaev Shipbuilding Plant（93,000 名员工）最高荣誉，表彰卫星收发系统工程成就。",
    "ip1year": "专利",
    "ip1title": "数字卫星 HDTV 系统",
    "ip1role": "随后被 Sony 收购",
    "ip1desc": "获得数字卫星高清电视（HDTV）系统领域专利。该专利随后被 Sony Corporation 收购，验证了这项创新的商业价值。",
    "ip2year": "出版物",
    "ip2title": "技术论文",
    "ip2role": "卫星与光学系统",
    "ip2desc": "专注于卫星与光学数据传输系统的技术论文作者。研究贡献涵盖信号处理、仿真建模及应用于电信、国家基础设施和数字健康的自动化平台。",
    "ip3year": "研究",
    "ip3title": "国际合作",
    "ip3role": "美国与欧洲",
    "ip3desc": "参与国际研究合作与知识转移倡议。为多个行业开发用于数据采集、预测性诊断和云端编排的嵌入式工程系统。",
    "edu1title": "技术科学博士",
    "edu1desc": "2009 — Ukrainian State Marine Technical University",
    "edu2title": "信息技术哲学博士",
    "edu2desc": "2004 — Ukrainian State Marine Technical University",
    "edu3title": "硕士学位",
    "edu3desc": "电子学、数字卫星系统与经济学",
    "press1title": "Healthcare Tech Outlook",
    "press1role": "Digital Invest Inc. 专题报道",
    "press1desc": "Digital Invest Inc. 作为美国精准医疗与数字健康领先企业之一受到专题报道，因其通过 AI、ML 和 DNA 技术变革医疗的创新方法而获得认可。",
    "press1link": "阅读专题 →",
    "press2title": "Top Precision Medicine Solutions",
    "press2role": "行业认可",
    "press2desc": "入选顶尖精准医疗解决方案公司，彰显 Digital Invest 在推进现代医疗保健生物数学方法方面的角色。",
    "press2link": "查看榜单 →"
  },
  "contact": {
    "eyebrow": "联系我们",
    "title": "保持联系",
    "lead": "咨询角色、董事会职位和战略合作。",
    "infoTitle": "直接联系",
    "email": "电子邮件",
    "phone": "电话",
    "location": "地点",
    "locationVal": "Charlotte, North Carolina\nUnited States",
    "linkedin": "LinkedIn",
    "company": "现任公司",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member\nAGRON Inc.\nFounder",
    "formTitle": "发送消息",
    "formLead": "填写以下表格，我会尽快回复。",
    "firstName": "名",
    "lastName": "姓",
    "emailLabel": "电子邮件地址",
    "subject": "主题",
    "message": "消息",
    "inquiryType": "Inquiry Type",
    "inquiryAdvisory": "Advisory / Board Role",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "calendlyEyebrow": "Schedule a Conversation",
    "calendlyTitle": "Choose a Convenient Time",
    "calendlyLead": "For qualified board, advisory, speaking, and strategic partnership inquiries.",
    "calendlyPlaceholder": "Scheduling calendar will appear here.",
    "calendlyCta": "Open Scheduling Calendar",
    "inquiryBusiness": "Business",
    "infoEyebrow": "联系信息"
  },
  "consulting": {
    "eyebrow": "顾问服务",
    "title": "咨询",
    "heroEyebrow": "战略商业指导",
    "heroTitle": "战略顾问",
    "heroLead": "三十五年在美国和欧洲创立并顾问公司——数据基础设施、政府科技、精准医疗和机器人。",
    "cta": "联系 Michael Kofman",
    "introLead": "Digital Invest Inc. 首席执行官兼董事会成员。重点：新兴技术、安全、研究与资本配置。",
    "specialtiesEyebrow": "专注领域",
    "specialtiesTitle": "Michael Kofman 的专业方向",
    "area1title": "Board Service",
    "area1desc": "Independent director and board-level work in technology strategy, corporate governance, and growth-stage oversight.",
    "area2title": "CEO & Founder Advisory",
    "area2desc": "Corporate and technology strategy, organizational development, transactions, and applicable capital-markets experience.",
    "area3title": "Technology Due Diligence",
    "area3desc": "Evaluation of infrastructure, data platforms, security architecture, and applied technology based on documented operating experience."
  },
  "insights": {
    "eyebrow": "思想领导力",
    "title": "洞见",
    "heroTitle": "高管视角",
    "selectedEyebrow": "精选亮点",
    "selectedTitle": "重要认可",
    "allPressTitle": "全部媒体报道",
    "quotesEyebrow": "媒体评价",
    "quotesTitle": "行业认可与引述",
    "articlesEyebrow": "观点洞察",
    "articlesTitle": "高管观点",
    "briefsEyebrow": "Executive Briefs",
    "briefsTitle": "Ideas for Leaders",
    "briefsLead": "Short, practical perspectives on governance, technology, healthcare, and company building.",
    "brief1title": "What an IPO Changes",
    "brief1desc": "The operating and governance disciplines that public-market readiness demands.",
    "brief1tag": "Capital Markets",
    "brief2title": "From Genetic Data to Clinical Decisions",
    "brief2desc": "How to build useful health intelligence without outrunning evidence or trust.",
    "brief2tag": "Precision Medicine",
    "brief3title": "AI Strategy Beyond the Pilot",
    "brief3desc": "A framework for turning experiments into governed enterprise capability.",
    "brief3tag": "Artificial Intelligence",
    "readingEyebrow": "Reading List",
    "readingTitle": "Books That Shape Strategic Thinking",
    "r1title": "The Innovator's Dilemma",
    "r1author": "Clayton M. Christensen",
    "r2title": "Thinking, Fast and Slow",
    "r2author": "Daniel Kahneman",
    "r3title": "The Beginning of Infinity",
    "r3author": "David Deutsch",
    "r4title": "Good Strategy/Bad Strategy",
    "r4author": "Richard Rumelt",
    "r5title": "The Structure of Scientific Revolutions",
    "r5author": "Thomas S. Kuhn",
    "newsletterEyebrow": "Occasional Notes",
    "newsletterTitle": "Executive Perspective, Without the Noise",
    "newsletterLead": "Periodic essays and brief observations on technology, governance, and durable company building.",
    "newsletterCta": "Subscribe for Updates"
  },
  "cta": {
    "eyebrow": "合作共赢",
    "title": "申请咨询或演讲",
    "lead": "适用于顾问合作、董事会职位、演讲邀约及战略合作伙伴关系。",
    "button": "联系我"
  },
  "speaking": {
    "eyebrow": "演讲活动",
    "title": "邀请 Michael Kofman 演讲",
    "lead": "可就高管领导力、技术战略、数字健康、数据基础设施和公司治理进行演讲。",
    "topicsEyebrow": "演讲主题",
    "topicsTitle": "专业领域",
    "topicsLead": "主题内容基于其在美国和欧洲创办并领导企业数十年的实践经验。",
    "processEyebrow": "邀请方式",
    "processTitle": "预订流程",
    "process1title": "提交咨询",
    "process1desc": "请通过联系表单或发送邮件至 mkofman@mkofman.com，提供活动详情、受众信息及期望主题。",
    "process2title": "确认范围",
    "process2desc": "确认形式（主题演讲、论坛对谈、董事会会议或高管圆桌）及相关执行安排。",
    "process3title": "交付价值",
    "process3desc": "演讲内容基于在数据存储、政务科技和精准医疗领域的真实业务成果。",
    "cta": "申请演讲邀约",
    "catalogEyebrow": "Speaking Topics",
    "catalogTitle": "Executive Conversations for Consequential Change",
    "catalogLead": "Keynotes, board sessions, and leadership briefings tailored to the audience, sector, and decision context.",
    "t1title": "Governing AI Before It Governs the Enterprise",
    "t1audience": "Boards, audit and risk committees",
    "t1format": "Board briefing or keynote",
    "t2title": "From Technology Trend to Enterprise Strategy",
    "t2audience": "CEOs, executive teams, investors",
    "t2format": "Keynote or executive workshop",
    "t3title": "Building Companies Through Market Cycles",
    "t3audience": "Founders, growth leaders, private equity",
    "t3format": "Fireside chat or keynote",
    "t4title": "Precision Medicine: Promise, Proof, and Responsibility",
    "t4audience": "Healthcare leaders, clinicians, innovators",
    "t4format": "Industry keynote or panel",
    "t5title": "The Board's Role in Cyber and Technology Risk",
    "t5audience": "Directors, general counsel, risk leaders",
    "t5format": "Board education session",
    "t6title": "Engineering Trust into Digital Infrastructure",
    "t6audience": "Technology and infrastructure organizations",
    "t6format": "Technical-executive keynote",
    "t7title": "Leading Across Borders and Disciplines",
    "t7audience": "Global leadership teams and universities",
    "t7format": "Keynote or moderated conversation",
    "t8title": "From Founder to Institution Builder",
    "t8audience": "Entrepreneurs and next-generation executives",
    "t8format": "Workshop or fireside chat"
  },
  "caseStudies": {
    "eyebrow": "案例研究",
    "title": "打造可规模化增长的公司",
    "lead": "精选其在数据基础设施与数字健康领域创办并领导企业的成果。",
    "cs1eyebrow": "数据基础设施 · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "挑战",
    "cs1challengeText": "在快速整合的科技市场中建立并扩展一家数据存储公司。",
    "cs1action": "策略",
    "cs1actionText": "1996 年创立 9 Net Avenue Inc.，公司迅速成长为全球最大的数据存储企业之一。",
    "cs1result": "成果",
    "cs1resultText": "到 2000 年，公司先后被 Concentric Networks（NASDAQ: CNTX）和 XO Communications（NASDAQ: XOXO）收购，峰值市值达到 195 亿美元。收购后，他积累了在上市公司、董事会治理及最高层战略决策方面的丰富经验。",
    "cs2eyebrow": "数字健康 · 2021 — 至今",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "挑战",
    "cs2challengeText": "通过全新的生物数学平台，结合科学、DNA 技术、AI 与 ML，革新医学中的过时方法。",
    "cs2action": "策略",
    "cs2actionText": "创立并推动 Digital Invest Inc. 从零发展到成功 IPO，主导完整上市流程，包括法律架构、财务合规、投资者路演及与 SEC 协调。同时负责美国和欧洲多个数据中心的设计、建设与运营。",
    "cs2result": "成果",
    "cs2resultText": "实现持续财务增长，使公司跻身美国精准医疗企业前十（2023），旗下包括 Human Digital Model 和 BioMath Life 等项目。",
    "cs3eyebrow": "Robotics & UAV · 2026 — Present",
    "cs3title": "AGRON Inc.",
    "cs3challenge": "Challenge",
    "cs3challengeText": "Organizations building UAV and Counter-UAS capability need independent assessment, structured training, and operational architecture — not isolated platforms or ad-hoc piloting.",
    "cs3action": "Approach",
    "cs3actionText": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — consulting, assessment and validation, capability development, training infrastructure, product development support, geospatial systems through ISDRI, and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "cs3result": "Outcome",
    "cs3resultText": "A connected professional services ecosystem spanning five service domains and multiple companies — Global Drone Academy, AGRON, ISDRI, and GUARD — with programmes delivered across 10+ countries and 10,000+ UAV operators, instructors, and specialists trained."
  },
  "mediaKit": {
    "eyebrow": "媒体与活动",
    "title": "媒体资料包",
    "lead": "面向媒体、会议及董事会合作咨询的官方简介、视觉资料与联系方式。",
    "bioEyebrow": "人物简介",
    "bioTitle": "官方简介",
    "bioShortLabel": "50 词",
    "bioShort": "Michael Kofman 是 Digital Invest Inc. 的 CEO，同时担任董事会成员、顾问，并在美国和欧洲创办多家科技与数字健康企业。",
    "bioMediumLabel": "150 词",
    "bioMedium": "Michael Kofman 是 Digital Invest Inc. 的 CEO，并担任其董事会成员。作为技术远见者，他以动态方式洞察当今复杂市场不断变化的需求。作为企业家、董事会成员以及公私营企业顾问，他已在美国和欧洲成功创办多家公司。其专长覆盖高管领导力、新兴技术与市场战略分析、信息安全与隐私、科研与开发、管理及投资。",
    "bioLongLabel": "500 词",
    "bioLong": "Michael Kofman 是 Digital Invest Inc. 的 CEO，并担任其董事会成员。作为技术远见者，他以动态方式洞察当今复杂市场不断变化的需求。其专长涵盖高管领导力、新兴技术与市场战略分析、信息安全与隐私、科研与开发、管理及投资。作为企业家、董事会成员以及公私营企业顾问，Michael Kofman 在美国和欧洲成功创办了多家公司。他创立了 9 Net Avenue Inc.，并在峰值市值达 195 亿美元时被收购；目前他领导 Digital Invest Inc. 推动数据存储与先进技术创新。他曾主导政府及国防项目的技术战略，创立了数据存储领域的 XIBI Group Inc. 与 DataPeer Inc.，并在 Biotechnology Group Inc. 中发挥关键作用。他与 Harvard Medical School 和 Stanford Biomath 合作开展遗传报告项目。著有卫星与光学系统技术论文；其数字卫星 HDTV 专利被 Sony 收购。教育背景：技术科学博士（2009）、信息技术博士（2004）、Ukrainian State Marine Technical University。",
    "photosEyebrow": "摄影素材",
    "photosTitle": "授权图片",
    "photosLead": "如需高清肖像照，请发送邮件至 mkofman@mkofman.com。",
    "contactEyebrow": "媒体联系人",
    "contactTitle": "媒体咨询",
    "contactLead": "用于采访、演讲邀请及媒体合作请求。",
    "downloadEyebrow": "Download",
    "downloadTitle": "One-Page Media Kit",
    "downloadLead": "PDF with official bios, portrait, and press contact — ready to share with organizers and journalists.",
    "downloadCta": "Download PDF",
    "brandEyebrow": "Brand Assets",
    "brandTitle": "Identity & Usage",
    "brandLead": "Approved visual assets for editorial, conference, and partner use. Please preserve proportions, spacing, and original colors.",
    "brandColors": "Official Color Palette",
    "brandLogo": "Primary Logo",
    "brandDownload": "Download Brand Assets"
  },
  "articles": {
    "backLink": "← 返回 Insights",
    "article1date": "高管观点",
    "article1title": "从工程实践到全球数据基础设施",
    "article1p1": "我的职业生涯始于乌克兰尼古拉耶夫造船厂，当时负责开发用于向军舰传输机密信息的卫星收发系统。我被评为最高等级电子工程师，即在拥有 93,000 名员工的工厂中达到第 6 类工程师级别。",
    "article1p2": "1989 至 1994 年，我创立并领导了 Astra Corp，它是欧洲最大的数字卫星收发系统制造商之一。1994 至 1996 年，作为 Elitan United Inc. 的 CEO，我帮助公司从 9 人扩展到全球 4,000 余名员工。",
    "article1p3": "1996 年，我创立了 9 Net Avenue Inc.，该公司迅速成长为全球最大的数据存储企业之一。到 2000 年，公司被 Concentric Networks（NASDAQ: CNTX）和 XO Communications（NASDAQ: XOXO）收购，峰值市值达到 195 亿美元。",
    "article1p4": "2001 至 2019 年，我负责政府、国防及国有企业项目的技术战略，主导了美国和欧洲在大数据、安全基础设施及高吞吐数据中心方面的大型计划。",
    "article2date": "数字健康",
    "article2title": "精准医疗与科学技术融合",
    "article2p1": "我始终坚信生命科学与前沿技术结合所蕴含的巨大潜力。在 Biotechnology Group Inc.（2008-2014）期间，我们重点推进 DNA 检测与分析、遗传画像流程自动化以及全面的人类遗传学研究。",
    "article2p2": "在我的领导下，乌克兰、俄罗斯和波罗的海国家启动了多个成功的基因检测项目。与 Harvard Medical School 和 Stanford Biomath 的合作中，我在为医生和患者开发易于理解的基因报告方面发挥了关键作用。",
    "article2p3": "我们于 2021 年创立 Digital Invest Inc.，专注生物数学领域，借助科学、DNA 技术、AI 与 ML 改变传统医疗方式。公司从创立发展至成功 IPO，并在 2023 年被评为美国精准医疗与数字健康领域十佳公司之一。",
    "article2p4": "Digital Invest 通过 Human Digital Model 和 BioMath Life 等项目推进生物数学医学。2026 年，Michael Kofman 创立 AGRON Inc.，领导 Aerial-Ground Robotics Operations Network——无人机能力、地理空间系统与海事情报，见 agron1.com。"
  },
  "privacy": {
    "eyebrow": "法律信息",
    "title": "隐私政策",
    "lead": "说明 mkofman.com 在您访问网站或发送消息时如何处理信息。",
    "updated": "更新：2026年7月",
    "s1title": "我们收集的信息",
    "s1text": "提交表单时，我们接收您填写的字段。若启用分析，可能收集匿名使用数据。",
    "s2title": "信息用途",
    "s2text": "用于回复咨询并改进网站。我们不出售个人数据。",
    "s3title": "第三方服务",
    "s3text": "表单可能由 Formspree 处理。分析可使用 Plausible 或 Google Analytics（如已配置）。",
    "s4title": "您的权利",
    "s4text": "访问、更正或删除数据请联系 mkofman@mkofman.com。",
    "s5title": "联系",
    "s5text": "政策相关问题：mkofman@mkofman.com"
  },
  "board": {
    "eyebrow": "Board & Strategic Advisory",
    "title": "Independent Judgment for Consequential Decisions",
    "lead": "I work with boards, founders, and executive teams navigating technology risk, market transitions, capital allocation, and responsible growth.",
    "rolesEyebrow": "Ways to Engage",
    "rolesTitle": "Board-Level Partnership",
    "role1title": "Independent Director",
    "role1desc": "Constructive oversight, informed challenge, and long-range perspective for public and private company boards.",
    "role2title": "Advisory Board Member",
    "role2desc": "Practical guidance on emerging technologies, product strategy, market positioning, and institutional readiness.",
    "role3title": "CEO & Founder Advisor",
    "role3desc": "Confidential counsel for leaders facing inflection points in scale, governance, succession, financing, or transformation.",
    "role4title": "Special Committee Advisor",
    "role4desc": "Focused support for transactions, technology diligence, cybersecurity exposure, and other high-stakes mandates.",
    "valueEyebrow": "Perspective",
    "valueTitle": "What I Bring to the Table",
    "value1title": "Operator's Discipline",
    "value1desc": "Experience building organizations from inception through global scale, acquisition, and public-market accountability.",
    "value2title": "Technical Fluency",
    "value2desc": "The ability to translate complex systems, scientific claims, and technology risk into clear board decisions.",
    "value3title": "Cross-Market Judgment",
    "value3desc": "A perspective shaped by technology, telecommunications, defense, data infrastructure, and precision medicine.",
    "value4title": "Governance Mindset",
    "value4desc": "A commitment to fiduciary responsibility, candid dialogue, ethical innovation, and durable stakeholder value.",
    "cta": "Discuss a Board Mandate",
    "availability": "Select independent director, advisory board, and strategic counsel engagements are considered."
  },
  "thesis": {
    "eyebrow": "Leadership Thesis",
    "title": "Build for the Long Term. Decide in the Present.",
    "lead": "Technology changes quickly; the obligations of leadership do not. Durable enterprises unite ambition with discipline, evidence, and accountability.",
    "intro": "These principles reflect more than three decades of founding companies, engineering critical systems, advising boards, and leading through market cycles.",
    "believeEyebrow": "What I Believe",
    "believeTitle": "Seven Principles for Enduring Organizations",
    "b1title": "Strategy Must Produce Choices",
    "b1text": "A strategy is not a catalog of aspirations. It defines where to compete, what capabilities to build, what not to pursue, and how success will be measured.",
    "b2title": "Technology Is a Governance Issue",
    "b2text": "Boards must understand how technology creates value, concentrates risk, and changes accountability. Delegating every technical question is itself a decision.",
    "b3title": "Evidence Should Outrank Enthusiasm",
    "b3text": "Conviction matters, but markets, systems, and science must be tested. Leaders create mechanisms that expose assumptions before customers or regulators do.",
    "b4title": "Architecture Shapes the Enterprise",
    "b4text": "Technical architecture determines speed, resilience, security, and future options. Shortcuts become institutional constraints long after their original context disappears.",
    "b5title": "Trust Is Operating Infrastructure",
    "b5text": "Trust is built through clear commitments, reliable execution, responsible data practices, and direct communication when conditions change.",
    "b6title": "Capital Must Follow Capability",
    "b6text": "Growth investment should reinforce differentiated capabilities and measurable demand, not substitute spending for product-market understanding.",
    "b7title": "Leaders Design Their Successors",
    "b7text": "The strongest leaders build systems, talent, and decision quality that endure beyond their own involvement.",
    "rejectEyebrow": "What I Reject",
    "rejectTitle": "Three Expensive Illusions",
    "r1title": "Innovation Theater",
    "r1text": "Announcements, pilots, and fashionable language do not equal capability. Innovation must improve an outcome that matters.",
    "r2title": "Growth Without Governance",
    "r2text": "Scale magnifies unresolved weaknesses. Controls, culture, and accountability should mature before complexity makes correction costly.",
    "r3title": "False Certainty",
    "r3text": "Executive confidence should not erase uncertainty. Strong decisions make assumptions visible and preserve options when facts change.",
    "horizonEyebrow": "The Horizon",
    "horizonTitle": "The Next Advantage Is Responsible Integration",
    "horizonText": "The defining opportunity is not any single technology. It is the disciplined integration of AI, advanced data systems, biology, and automation into institutions people can trust."
  },
  "press": {
    "eyebrow": "Press & Media",
    "title": "Selected Coverage",
    "lead": "A concise archive of third-party recognition and reporting across technology, entrepreneurship, and precision medicine.",
    "archiveEyebrow": "Archive",
    "y2023type": "Industry Recognition",
    "y2023title": "Top 10 Precision Medicine Companies",
    "y2023desc": "Healthcare Tech Outlook recognized Digital Invest Inc. among leading U.S. companies advancing precision medicine and digital health.",
    "y2023link": "View feature",
    "y2001type": "Executive Award",
    "y2001title": "Entrepreneur of the Year",
    "y2001desc": "Entrepreneur Magazine recognition for leadership, company building, and breakthrough achievement in technology infrastructure.",
    "y2001link": "View archive",
    "y1999type": "Biographical Recognition",
    "y1999title": "Who's Who in America",
    "y1999desc": "Recognition beginning in 1999, followed by listings in Who's Who in the World and Who's Who in Science and Engineering.",
    "clipEyebrow": "From the Archive",
    "clipMeta": "Industry Feature · DataPeer Inc.",
    "clipTitle": "State of the Storage Industry",
    "clipLead": "An early interview with Michael Kofman as Founder, Chairman, and CEO of DataPeer Inc. — reflecting on fiber optics, satellite transmission, SAN, and the emerging storage market.",
    "clipBody": "The feature notes recognition as Entrepreneur of the Year by Entrepreneur Magazine (1999) and discusses DataPeer’s approach to mission-critical storage, iSCSI, and business continuity.",
    "clipOpen": "Open full page scan →",
    "y2000type": "Interview",
    "y2000title": "State of the Storage Industry",
    "y2000desc": "Featured interview as Founder, Chairman, and CEO of DataPeer Inc. on storage networks, iSCSI, and business continuity."
  },
  "ip": {
    "eyebrow": "Intellectual Property",
    "title": "Applied Ideas, Documented",
    "lead": "Selected patents, publications, and research programs connecting engineering rigor with practical business and societal outcomes.",
    "patentEyebrow": "Patents",
    "patentTitle": "Protected Inventions",
    "patentIntro": "Patent work reflects a sustained focus on systems that improve the collection, movement, protection, and interpretation of information.",
    "publicationsEyebrow": "Publications",
    "publicationsTitle": "Technical & Executive Writing",
    "publicationsIntro": "Published work translates complex technical subjects into methods, frameworks, and decisions useful to practitioners and leaders.",
    "researchEyebrow": "Research",
    "researchTitle": "Interdisciplinary Programs",
    "researchIntro": "Research initiatives span secure communications, predictive analytics, genetic interpretation, human digital modeling, and autonomous systems."
  },
  "testimonials": {
    "t1quote": "Michael combines an engineer's precision with the judgment of an experienced chief executive. He asks the questions that improve the decision.",
    "t1name": "Board Colleague",
    "t1role": "Public Technology Company",
    "t2quote": "His ability to connect science, product, governance, and commercial reality brings uncommon clarity to complex initiatives.",
    "t2name": "Strategic Partner",
    "t2role": "Digital Health Sector",
    "t3quote": "Michael is direct, thoughtful, and focused on durable value. He helps leadership teams see both the opportunity and the obligation.",
    "t3name": "Executive Collaborator",
    "t3role": "Global Infrastructure"
  },
  "deck": {
    "title": "Michael Kofman",
    "subtitle": "Executive Leadership, Strategic Technology & Board Advisory",
    "thesis": "Building durable enterprises at the intersection of technology, governance, and human progress.",
    "stat1": "30+ years of executive leadership",
    "stat2": "Multiple companies founded and scaled",
    "stat3": "$19.5B peak market value",
    "contact": "Confidential discussion: contact Michael Kofman through mkofman.com"
  },
  "briefIpo": {
    "title": "What an IPO Changes",
    "desc": "Public markets do not merely change a company's capital structure; they change its operating contract.",
    "p1": "An initial public offering is often described as a financing event. In practice, it is an institutional transition. Forecasting, controls, disclosure, governance, and executive communication must become repeatable before the listing, not improvised afterward.",
    "p2": "Readiness begins with decision quality. Management needs reliable metrics, clear ownership, and an operating cadence that can explain both performance and variance. A company that cannot reconcile its internal narrative will struggle to communicate a credible external one.",
    "p3": "The board's role also changes. Directors must balance growth with oversight, understand material technology and market risks, and ensure that incentives support durable value rather than a single quarter.",
    "p4": "The strongest public companies preserve entrepreneurial speed while adding institutional discipline. The objective is not bureaucracy; it is trustworthy execution at a higher level of accountability.",
    "eyebrow": "高管简报"
  },
  "briefGenetic": {
    "title": "From Genetic Data to Clinical Decisions",
    "desc": "The value of genomic information depends on interpretation, evidence, and responsible integration into care.",
    "p1": "Genetic data is abundant; clinically useful meaning is scarce. A result becomes valuable only when it is interpreted in context, connected to validated evidence, and presented in a form that supports a real decision.",
    "p2": "That translation requires collaboration across molecular biology, medicine, statistics, software engineering, and patient communication. Weakness in any layer can turn technical sophistication into clinical confusion.",
    "p3": "Privacy and consent are architectural requirements, not legal footnotes. Systems must limit unnecessary exposure, make data provenance visible, and preserve patient agency as information moves between laboratories, platforms, and care teams.",
    "p4": "Precision medicine will advance through measured integration: better evidence, transparent models, interoperable workflows, and outcomes that clinicians and patients can evaluate. Trust is part of the product.",
    "eyebrow": "高管简报"
  },
  "briefAi": {
    "title": "AI Strategy Beyond the Pilot",
    "desc": "Enterprise AI creates value when ownership, data, workflow, and governance mature together.",
    "p1": "Many AI initiatives begin with a compelling demonstration and stall before production. The missing element is rarely the model alone. Sustainable value requires a defined business outcome, accountable owner, dependable data, and a workflow people will actually use.",
    "p2": "Leaders should distinguish automation, prediction, and decision support. Each carries different requirements for accuracy, explainability, human review, and risk. A single governance template will not fit every use case.",
    "p3": "Measurement must include more than technical performance. Adoption, cycle time, error rates, customer impact, security exposure, and the cost of supervision determine whether an AI capability is economically and institutionally sound.",
    "p4": "The winning approach is a managed portfolio: scale proven use cases, stop weak ones early, and maintain explicit boundaries for high-consequence decisions. AI strategy is ultimately operating strategy.",
    "eyebrow": "高管简报"
  }
};
