window.__LANG_zh = {
  "ui": {
    "toggleTheme": "切换浅色/深色主题",
    "selectLanguage": "选择语言",
    "messageSent": "消息已发送",
    "sendMessage": "发送消息",
    "toggleNav": "打开菜单",
    "sending": "发送中…",
    "formError": "发送失败。请直接发送电子邮件。",
    "present": "至今"
  },
  "nav": {
    "home": "首页",
    "about": "简介",
    "ventures": "企业",
    "career": "履历",
    "recognition": "荣誉",
    "contact": "联系",
    "consulting": "咨询",
    "insights": "洞见",
    "speaking": "演讲邀约",
    "caseStudies": "案例研究",
    "mediaKit": "媒体资料包",
    "groupMain": "主要",
    "groupServices": "服务",
    "groupWork": "成果",
    "briefIpo": "简报：IPO",
    "briefGenetic": "简报：基因数据",
    "briefAi": "简报：AI战略",
    "articleInfra": "数据基础设施",
    "articleHealth": "精准医疗",
    "board": "顾问",
    "thesis": "领导力论题",
    "press": "媒体",
    "ip": "知识产权"
  },
  "footer": {
    "navigation": "导航",
    "ventures": "企业",
    "connect": "联系",
    "desc": "技术高管、创始人和董事会顾问。",
    "copyright": "© {year} Michael Kofman. 版权所有。",
    "writeTitle": "给我留言",
    "writeEmail": "您的邮箱",
    "writeMessage": "您的留言",
    "writeSend": "发送",
    "writeSuccess": "谢谢 — 您的留言已发送。",
    "more": "更多",
    "privacy": "隐私政策"
  },
  "meta": {
    "home": {
      "title": "Michael Kofman — 技术高管",
      "description": "技术高管、创始人和董事会顾问 — 基础设施、生命科学和自主系统。"
    },
    "about": {
      "title": "简介 — Michael Kofman",
      "description": "Michael Kofman 传记——Digital Invest Inc. 首席执行官，AGRON Inc. 创始人。"
    },
    "ventures": {
      "title": "企业 — Michael Kofman",
      "description": "Michael Kofman创办和领导的企业——从Digital Invest Inc.到9 Net Avenue Inc.——在科技和医疗领域构建变革性业务。"
    },
    "career": {
      "title": "履历 — Michael Kofman",
      "description": "涵盖工程、基础设施、公开市场、生命科学和自主系统的专业记录。"
    },
    "recognition": {
      "title": "荣誉 — Michael Kofman",
      "description": "Michael Kofman获得的奖项与荣誉——年度企业家、Who's Who、专利和行业殊荣。"
    },
    "contact": {
      "title": "联系 — Michael Kofman",
      "description": "联系Michael Kofman——Digital Invest Inc. CEO。咨询顾问职位、演讲邀约和商业合作。"
    },
    "consulting": {
      "title": "咨询 — Michael Kofman",
      "description": "与Michael Kofman的顾问职位、董事会成员、演讲邀约和战略合作。"
    },
    "insights": {
      "title": "见解 — Michael Kofman",
      "description": "Michael Kofman 的原创文章与 executive briefs。"
    },
    "speaking": {
      "title": "演讲邀约 — Michael Kofman",
      "description": "邀请 Michael Kofman 就高管领导力、技术战略、数字健康和公司治理发表演讲。"
    },
    "caseStudies": {
      "title": "案例研究 — Michael Kofman",
      "description": "Michael Kofman 职业生涯案例研究：9 Net Avenue Inc. 与 Digital Invest Inc."
    },
    "mediaKit": {
      "title": "媒体资料包 — Michael Kofman",
      "description": "面向媒体与活动主办方的官方简介、照片及联系方式。"
    },
    "article1": {
      "title": "从工程到全球基础设施 — Michael Kofman",
      "description": "Michael Kofman 讲述自己从卫星工程到创办全球数据基础设施公司的职业路径。"
    },
    "article2": {
      "title": "精准医疗与科技融合 — Michael Kofman",
      "description": "Michael Kofman 谈生命科学与 AI、ML 及 DNA 技术在现代医学中的融合。"
    },
    "privacy": {
      "title": "隐私政策 — Michael Kofman",
      "description": "mkofman.com 隐私政策——联系表单与分析说明。"
    },
    "board": {
      "title": "顾问 — Michael Kofman",
      "description": "与科技、医疗和基础设施机构的战略顾问对话。"
    },
    "thesis": {
      "title": "领导力论题 — Michael Kofman",
      "description": "Michael Kofman关于构建持久企业、治理技术和引领重大变革的原则。"
    },
    "press": {
      "title": "媒体档案 — Michael Kofman",
      "description": "Michael Kofman在科技和创业领域职业生涯的精选媒体报道、奖项和媒体引用。"
    },
    "ip": {
      "title": "知识产权 — Michael Kofman",
      "description": "Michael Kofman在计算、通信、数据和数字健康领域的专利、出版物和应用研究。"
    },
    "briefIpo": {
      "title": "IPO带来的变化 — Michael Kofman",
      "description": "关于IPO前后所需运营纪律、治理和问责的高管简报。"
    },
    "briefGenetic": {
      "title": "从遗传数据到临床决策 — Michael Kofman",
      "description": "关于将基因组信息转化为负责任、有用且可扩展临床智能的高管简报。"
    },
    "briefAi": {
      "title": "超越试点的AI战略 — Michael Kofman",
      "description": "关于将人工智能从实验转向受治理、可衡量企业能力的高管简报。"
    },
    "deck": {
      "title": "高管概览 — Michael Kofman",
      "description": "面向合格介绍的私人高管概览。"
    }
  },
  "home": {
    "heroEyebrow": "Michael Kofman 官方网站",
    "heroTitle1": "基业长青。",
    "heroTitle2": "审慎领导。",
    "heroCta": "了解我的故事",
    "heroAlt": "Michael Kofman",
    "quote1text": "入选美国精准医疗与数字健康领域的领先公司。",
    "quote1author": "Healthcare Tech Outlook",
    "quote2text": "年度企业家——因平台创新与基础设施领域的领导力与突破成就而获认可。",
    "quote2author": "Entrepreneur Magazine · 2001",
    "quote3text": "Digital Invest Inc. 入选美国精准医学与数字健康十大最佳公司。",
    "quote3author": "Healthcare Tech Outlook, 2023",
    "quote4text": "工程精度与商业战略并重——从卫星系统到195亿美元基础设施，再到精准医疗。",
    "quote4author": "Executive Profile",
    "aboutEyebrow": "认识 Michael Kofman",
    "aboutTitle": "经得起时间考验的公司",
    "aboutLead1": "Digital Invest Inc. 首席执行官兼 AGRON Inc. 创始人。在美国和欧洲创立并领导多家公司。",
    "aboutLead2": "从 9 Net Avenue（峰值估值195亿美元）到 Digital Invest 精准医疗和 AGRON 机器人——四十年深耕基础设施、医疗与国防。",
    "aboutLink": "阅读完整传记",
    "expertiseEyebrow": "重点领域",
    "expertiseTitle": "跨行业高管领导力",
    "expertiseLead": "四十年在基础设施、医疗和机器人领域的创业、咨询与投资。",
    "exp1title": "CEO与创始人",
    "exp1desc": "在美国和欧洲创办并领导多家科技公司。",
    "exp1link": "查看企业 →",
    "exp2title": "技术架构师",
    "exp2desc": "为政府、军事和电信领域设计安全通信、预测分析引擎和国家级数据集成平台。",
    "exp2link": "查看职业 →",
    "exp3title": "数字健康",
    "exp3desc": "通过人工智能、机器学习和DNA技术引领医学变革。曾与哈佛医学院和Stanford Biomath合作开展基因报告项目。",
    "exp3link": "Digital Invest →",
    "exp4title": "董事会顾问",
    "exp4desc": "担任董事会成员，为上市和非上市公司提供战略方向、公司治理和技术驱动增长方面的咨询。",
    "exp4link": "咨询 →",
    "stat1": "领导年数",
    "stat2": "创立公司",
    "stat3": "峰值市值",
    "stat4": "扩展员工",
    "recEyebrow": "荣誉",
    "recTitle": "精选荣誉",
    "recLead": "在创业、医学和工程领域获得行业奖项与同行认可。",
    "award1title": "年度企业家",
    "award1desc": "Entrepreneur Magazine · 2001",
    "award2title": "精准医疗前十",
    "award2desc": "Digital Invest Inc. — U.S., 2023",
    "award3title": "Who's Who",
    "award3desc": "America 1999 — 2018 · World 2000 — 2004 · Science & Engineering 2000 — 2014",
    "recLink": "荣誉与媒体 →",
    "heroSub": "技术、商业与投资 — 涵盖基础设施、生命科学和自主系统。",
    "primaryCta": "申请顾问咨询",
    "secondaryCta": "查看案例研究",
    "featuredEyebrow": "来自档案",
    "caseStudiesEyebrow": "可验证成果",
    "caseStudiesTitle": "案例研究",
    "caseStudiesLead": "从创立到并购和 IPO，持续推动企业创建、扩张与领导。",
    "caseStudiesLink": "查看全部案例研究 →",
    "cs1title": "9 Net Avenue Inc.",
    "cs1desc": "打造了全球最大的数据存储企业之一，并在峰值市值 195 亿美元时被收购。",
    "cs2title": "Digital Invest Inc.",
    "cs2desc": "从创立扩展至成功 IPO，入选 2023 年美国精准医疗十强企业。",
    "cs3title": "AGRON Inc.",
    "cs3desc": "Founded in 2026 — the AGRON Ecosystem for UAV capability development, geospatial systems, and maritime intelligence.",
    "boardCtaEyebrow": "Advisory",
    "boardCtaTitle": "Experience for the Decisions That Define an Enterprise",
    "boardCtaLead": "Independent perspective for boards and leaders navigating technology, governance, transformation, and growth.",
    "boardCtaBtn": "Explore Advisory",
    "testimonialsEyebrow": "Trusted Perspective",
    "testimonialsTitle": "What Colleagues Value",
    "videoEyebrow": "Executive Perspective",
    "videoTitle": "Leadership at the Intersection of Technology and Enterprise",
    "videoLead": "A concise introduction to the principles, experience, and long-term perspective behind Michael Kofman's work.",
    "videoCta": "Read Leadership Thesis →",
    "heroName": "Michael Kofman",
    "heroRole": "技术高管 · 创始人 · 董事会顾问",
    "introText": "Michael Kofman 是技术高管和公司创始人。其工作涵盖卫星工程、互联网基础设施、公开科技公司和生命科学。他创立了 9 Net Avenue Inc.，于 2000 年被 Concentric Networks 收购。现任 Digital Invest Inc. CEO，从事生物数学医学和基因组智能；AGRON Inc. 创始人，专注自主空地作业和地理空间系统。他担任董事会成员，并在技术、医疗和基础设施领域提供顾问服务。",
    "introLink": "完整传记 →",
    "currentEyebrow": "当前工作",
    "currentTitle": "当前重点",
    "currentDiTitle": "Digital Invest Inc.",
    "currentDiDesc": "生物数学医学、基因组数据和临床智能 — 将 AI、机器学习和 DNA 技术应用于负责任的医疗成果。",
    "currentDiLink": "Ventures →",
    "currentAgTitle": "AGRON Inc.",
    "currentAgDesc": "自主空地作业、无人机能力开发、地理空间系统和海事情报基础设施。",
    "currentAgLink": "agron1.com →",
    "careerEyebrow": "精选记录",
    "careerTitle": "跨技术时期的延续",
    "careerLead": "从工程到当前自主系统工作的精选里程碑。",
    "career1title": "工程与通信",
    "career1desc": "卫星收发器系统、数字通信和早期工程领导。",
    "career2title": "互联网与基础设施",
    "career2desc": "互联网基础设施、数据中心、存储和大规模电信。",
    "career3title": "科技公司与公开市场",
    "career3desc": "企业创建、收购和上市公司经验，包括9 Net Avenue Inc.",
    "career4title": "生命科学与人类数据",
    "career4desc": "生物技术、基因数据、精准医疗和健康智能平台。",
    "career5title": "自主系统",
    "career5desc": "空地机器人、UAV运营和地理空间基础设施。",
    "careerLink": "履历 →",
    "perspectivesEyebrow": "观点",
    "perspectivesTitle": "精选文章",
    "perspectivesLink": "全部见解 →",
    "footerHomeDesc": "技术高管、创始人和董事会顾问。",
    "activeSitesLink": "所有活跃网站 →"
  },
  "about": {
    "eyebrow": "关于 Michael Kofman",
    "title": "三十年历程",
    "lead": "技术高管、创始人和董事会顾问。",
    "glance": "概览",
    "role": "现任职位",
    "roleVal": "CEO · Digital Invest Inc. · Founder · AGRON Inc.",
    "location": "地点",
    "locationVal": "Charlotte, North Carolina",
    "education": "教育",
    "educationVal": "技术科学博士\n信息技术博士\n硕士学位——电子学、数字卫星系统和经济学",
    "university": "大学",
    "universityVal": "乌克兰国立海洋技术大学",
    "languages": "语言",
    "languagesVal": "英语、俄语、乌克兰语",
    "contactLabel": "联系",
    "principlesEyebrow": "运营原则",
    "principlesTitle": "我如何领导",
    "p1title": "理解系统",
    "p1text": "在改变组织之前，理解其激励、架构、约束和信任来源。",
    "p2title": "使问责明确",
    "p2text": "明确的所有权和可衡量结果将战略从演示材料变为运营现实。",
    "p3title": "留下更强的机构",
    "p3text": "领导力应通过培养人才、改善决策和构建持久系统来增强能力。",
    "archiveEyebrow": "档案精选",
    "archiveTitle": "来自档案",
    "archiveLead": "来自企业创建、基础设施和领导力的真实资料。",
    "photo9netTitle": "9 Net Avenue",
    "photo9netCaption": "创始人兼CEO——托管与互联网基础设施公司，2000年被Concentric Networks收购。",
    "photoServerTitle": "数据基础设施",
    "photoServerCaption": "DataPeer及相关企业的存储、网络和服务器环境。",
    "photoTodayTitle": "今日",
    "photoTodayCaption": "Digital Invest Inc.、AGRON Inc.及顾问工作。",
    "secIntroTitle": "简介",
    "secTechTitle": "技术与基础设施",
    "secBusinessTitle": "商业",
    "secCurrentTitle": "当前工作",
    "secBackgroundTitle": "背景",
    "recordLink": "履历 →",
    "secBackgroundP1": "技术科学博士和信息技术博士。技术论文作者；数字卫星 HDTV 专利被 Sony 收购。",
    "bioP1": "Michael Kofman 是技术高管、创始人和董事会顾问。现任 Digital Invest Inc. CEO 和 AGRON Inc. 创始人，此前工作涵盖卫星工程、互联网基础设施、公开科技公司和生命科学。",
    "bioP2": "As an entrepreneur, board member, and advisor for both public and private companies, Michael Kofman has successfully established several companies in the United States and Europe. In 2026 he founded AGRON Inc. to lead the Aerial-Ground Robotics Operations Network. He also created Digital Invest, dedicated to the bio-mathematical sphere and transforming medicine through science, DNA technologies, AI, and ML.",
    "secBioTitle": "精准医疗与生物技术",
    "secBioP1": "在创立 Digital Invest 之前，他在 Biotechnology Group Inc.（2008 — 2014）的成功中发挥了重要作用。该公司致力于 DNA 检测与分析、基因图谱构建流程自动化以及全面的人类遗传学研究。科夫曼先生坚信，将生命科学与最新技术进展相结合具有巨大潜力。",
    "secBioP2": "在他的领导下，乌克兰、俄罗斯和波罗的海国家成功启动了基因检测项目。这一独特经验不断融入现代技术与新设备。在与 Harvard Medical School 和 Stanford Biomath 的合作中，科夫曼先生在开发医生与患者均易于理解的基因报告方面发挥了关键作用。这一创新方法已被美国及海外领先实验室广泛采用。",
    "secTechP1": "工程背景包括 Nikolaev Shipbuilding Plant 的卫星收发器系统和 Astra Corp 的数字通信工作。",
    "secTechP2": "2006 年，科夫曼先生创立了 XIBI Group Inc.——一家他担任董事会成员的技术公司。这家美国公司专注于为大型商业及政府组织提供数据存储与大数据管理服务。",
    "secTechP3": "2000 年至 2004 年，科夫曼先生领导 DataPeer Inc.——一家为中小企业提供广泛信息存储服务的数据管理与存储公司。在 DataPeer，他开发了独特的技术解决方案，使全球个人用户和政府机构能够更快速地追踪信息、更便捷地访问数据。",
    "secTechP4": "1996 年，科夫曼先生创立了 9 Net Avenue Inc.，该公司迅速成为全球最大的主机托管公司之一。2000 年，9 Net Avenue 被 Concentric Networks（NASDAQ: CNTX）收购，随后被 XO Communications（NASDAQ: XOXO）收购，峰值市值达 195 亿美元。",
    "secPost9NetP1": "在 9 Net Avenue 被收购后，科夫曼先生积累了在上市公司工作、参与董事会并参与最高管理层战略决策的丰富经验。",
    "secEarlyTitle": "早期职业与工程",
    "secEarlyP1": "1994 年至 1996 年，科夫曼先生担任 Elitan United Inc. 首席执行官兼信息技术总监——这是一家位于马萨诸塞州的 IT 公司，为领先全球组织提供全面战略与技术服务。他在开发和管理可扩展基础设施方面发挥了关键作用，推动公司从仅 9 名员工增长至全球 4,000 余人。",
    "secEarlyP2": "1989 年至 1994 年，他创立并担任 Astra Corp 首席执行官，该公司是欧洲最大的数字收发卫星系统制造商之一，在卫星设备领域获得国际认可。其职责涵盖研究、操作系统开发、网络软件应用及整体技术战略。",
    "secEarlyP3": "1984 年至 1989 年，科夫曼先生在乌克兰尼古拉耶夫造船厂工作，积极参与用于向军舰及回传传输机密信息的卫星收发系统的研发与制造。他被认定为最高级别的电子工程师，获得第六类职称——在该拥有 9.3 万名员工的工厂中，这是最高荣誉。",
    "secResearchTitle": "研究与专利",
    "secResearchP1": "Michael Kofman 是专注于卫星与光学数据传输系统的技术论文作者。他还获得了数字卫星高清电视（HDTV）系统领域的专利，该专利随后被 Sony 收购。",
    "secAgronTitle": "Robotics, UAV & Maritime Intelligence",
    "secAgronP1": "In 2026, Mr. Kofman founded AGRON Inc. to build the AGRON Ecosystem — a corporate operating architecture for aerial and ground robotics, governed mission execution, and network infrastructure connecting teams, assets, and operational data. The ecosystem delivers consulting, assessment, capability development, and training for UAV and Counter-UAS organizations, alongside maritime intelligence and security services at agron1.com.",
    "secBusinessP1": "创立并领导多家科技公司，包括 9 Net Avenue Inc.、DataPeer Inc.、XIBI Group Inc. 和 Elitan United Inc。完整年表见 The Record。",
    "secCurrentP1": "Digital Invest Inc. CEO，专注生物数学医学和基因组智能。AGRON Inc. 创始人，从事自主空地作业和地理空间系统。"
  },
  "ventures": {
    "eyebrow": "企业组合",
    "title": "创立并领导的公司",
    "lead": "从精准医疗和机器人到全球数据基础设施——在美国和欧洲创立、扩展并领导。",
    "ecosystemEyebrow": "Venture Ecosystem",
    "ecosystemTitle": "Companies Across Technology Frontiers",
    "ecosystemLead": "A portfolio shaped by recurring themes: trusted data, intelligent infrastructure, human health, and systems built for scale.",
    "statusActive": "活跃",
    "statusExited": "已退出",
    "statusLegacy": "遗留",
    "v1lesson": "经验：当可靠性、经济性和客户信任共同提升时，基础设施才能胜出。",
    "v2lesson": "经验：精准医疗在科学、软件、隐私和临床实用性上需要同等纪律。",
    "v3lesson": "经验：只有当感知、通信和人工监督形成一个有韧性的系统时，自主性才创造价值。",
    "v5lesson": "经验：基础设施的规模来自长期运营卓越，而非退出前的冲刺。",
    "currentEyebrow": "当前",
    "historyEyebrow": "精选历史",
    "v2highlight": "Harvard Medical School 与 Stanford Biomath — 遗传报告合作",
    "activeSitesEyebrow": "活跃项目",
    "activeSitesTitle": "活跃网站",
    "activeSitesLead": "当前公司和投资组合项目的活跃网站。",
    "activeSitesMeta": "10个活跃网站 · 点击任意卡片访问",
    "v0highlight": "Aerial-Ground Robotics Operations Network · agron1.com",
    "v0p1": "Founded AGRON Inc. in 2026 to lead the AGRON Ecosystem — an Aerial-Ground Robotics Operations Network spanning UAV and Counter-UAS consulting, technology assessment, capability development, training infrastructure, product validation, geospatial systems (ISDRI), and AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure.",
    "v0role": "Founder",
    "v0year": "2026 — Present",
    "v2role": "首席执行官兼首席技术官",
    "v2year": "2008 — 2014",
    "v3year": "2006 — 2011",
    "v4year": "2000 — 2004",
    "v5highlight": "被收购 · 峰值市值 195 亿美元",
    "v5p1": "打造了全球最大的主机托管公司之一。2000 年被 Concentric Networks（NASDAQ: CNTX）收购，随后被 XO Communications（NASDAQ: XOXO）收购，峰值市值达 195 亿美元。",
    "v5year": "1996 — 2000",
    "v6year": "1994 — 1996",
    "v7year": "1989 — 1994",
    "v8year": "1984 — 1989",
    "v1highlight": "2023 年美国精准医疗十大公司",
    "v1p1": "生物数学医学、基因组数据与临床智能 — AI、ML 和 DNA 技术应用于临床与研究流程。",
    "v1role": "创始人兼首席执行官 · 董事会成员",
    "v1year": "2021 — 至今",
    "v2p1": "DNA 检测与分析、基因图谱自动化以及全面的人类遗传学研究。在乌克兰、俄罗斯和波罗的海国家发起基因检测项目。",
    "v2p2": "与 Harvard Medical School 和 Stanford Biomath 合作，开发被全球领先实验室采用的基因报告。",
    "v3highlight": "企业与政府数据解决方案",
    "v3p1": "为大型商业及政府组织提供数据存储与大数据管理服务。将公司确立为值得信赖的企业数据解决方案提供商。",
    "v3role": "创始人兼首席执行官 · 董事会",
    "v4highlight": "全球数据管理平台",
    "v4p1": "为中小企业提供数据管理与存储服务。开发解决方案，使全球终端用户和政府机构能够更快速地追踪信息、更便捷地访问数据。",
    "v4role": "创始人兼首席执行官",
    "v5role": "创始人兼首席执行官",
    "v6highlight": "全球 IT 战略与基础设施",
    "v6p1": "马萨诸塞州 IT 公司，为领先全球组织提供全面战略与技术服务。领导可扩展基础设施开发及全球 IT 运营。",
    "v6role": "首席执行官兼信息技术总监",
    "v7highlight": "欧洲卫星系统领导者",
    "v7p1": "欧洲最大的数字收发卫星系统制造商之一。领导研究、操作系统开发、网络软件应用及整体技术战略。",
    "v7role": "创始人兼首席执行官",
    "v8highlight": "军用卫星系统工程",
    "v8p1": "研发用于向军舰传输机密信息的卫星收发系统。在拥有 93,000 名员工的工厂中，被认定为最高级别的电子工程师。",
    "v8role": "电子工程师 · 最高类别（第六类）",
    "v1p2": "投资组合项目包括 <a href=\"https://biomathlife.com\" target=\"_blank\" rel=\"noopener\">BioMath Life</a>、<a href=\"https://www.biomathcore.com\" target=\"_blank\" rel=\"noopener\">BioMath Core</a>、<a href=\"https://www.type1and2.com\" target=\"_blank\" rel=\"noopener\">Type 1 &amp; 2</a> 和 <a href=\"https://www.luna29.com\" target=\"_blank\" rel=\"noopener\">Luna29</a> — 详细案例研究将陆续发布。",
    "v1brole": "首席执行官",
    "v1bp1": "生物技术工作向新技术开发过渡的时期 — 在 Digital Invest Inc. 之前积累运营和研发经验。",
    "v1byear": "2014 — 2020"
  },
  "career": {
    "eyebrow": "职业历程",
    "title": "履历",
    "lead": "技术、公司与 successive 技术变革时期的运营经验。",
    "timelineEyebrow": "时间线",
    "timelineTitle": "关键里程碑",
    "strengthsEyebrow": "核心优势",
    "strengthsTitle": "专业领域",
    "filterAll": "All",
    "filterHealthcare": "Healthcare",
    "filterInfrastructure": "Infrastructure",
    "filterDefense": "Defense",
    "filterTelecom": "Telecommunications",
    "periodCurrent": "自主系统",
    "periodCurrentLead": "AI、机器人、自主运营、地理空间系统及相关当前基础设施。",
    "period1title": "工程与通信",
    "period1lead": "早期工程、卫星系统、通信及相关技术工作。",
    "period2title": "互联网与基础设施",
    "period2lead": "互联网基础设施、电信、数据中心、存储及相关公司。",
    "period3title": "公司与公开市场",
    "period3lead": "企业创建、交易、上市公司参与和高管角色。",
    "period4title": "生命科学与人类数据",
    "period4lead": "生物技术、健康相关技术、数据和精准医疗。",
    "period5title": "政府与国防项目",
    "period5lead": "为政府、国防和国有企事业项目提供技术战略与交付。",
    "t1desc": "Digital Invest Inc. 创立于 2021 年，专注生物数学医学、基因组智能和临床数据平台。Healthcare Tech Outlook（2023）。",
    "t0desc": "Founded AGRON Inc. to build the AGRON Ecosystem — consulting, assessment, capability development, training infrastructure, and product support for UAV and Counter-UAS programmes, plus AGRON Maritime Intelligence + Security for yachts, marinas, and private maritime infrastructure. Connects aerial and ground robotics, governed mission execution, and network infrastructure linking teams, assets, and operational data.",
    "t0role": "Founder",
    "t0title": "AGRON Inc.",
    "t0year": "2026 — Present",
    "t10title": "Nikolaev Shipbuilding Plant",
    "t10year": "1984 — 1989",
    "t1title": "Digital Invest Inc.",
    "t2year": "2001 — 2019",
    "t3role": "首席执行官兼首席技术官",
    "t3title": "Biotechnology Group Inc.",
    "t3year": "2008 — 2014",
    "t4year": "2000 — 2012",
    "t5title": "XIBI Group Inc.",
    "t5year": "2006 — 2011",
    "t6title": "DataPeer Inc.",
    "t6year": "2000 — 2004",
    "t7desc": "打造了全球最大的主机托管公司之一。2000 年被 Concentric Networks（NASDAQ: CNTX）收购，随后被 XO Communications（NASDAQ: XOXO）收购，峰值市值达 195 亿美元。",
    "t7title": "9 Net Avenue Inc.",
    "t7year": "1996 — 2000",
    "t8title": "Elitan United Inc.",
    "t8year": "1994 — 1996",
    "t9title": "Astra Corp",
    "t9year": "1989 — 1994",
    "t10desc": "研发用于向军舰传输机密信息的卫星收发系统。在拥有 93,000 名员工的工厂中，被认定为最高级别的电子工程师——这是其在技术与创新领域卓越职业生涯的起点。",
    "t10role": "电子工程师 — 第六类（最高级）",
    "t1role": "创始人兼首席执行官",
    "t1year": "2021 — 至今",
    "t2desc": "为涉及美国政府机构、盟国国防系统及国有企业的机密与高敏感项目制定并交付技术战略。领导跨多个行业国有企业的复杂技术项目。2001 年 9·11 事件后，主导以大数据、安全通信、预测分析和国家级数据整合为核心的大规模政府倡议——包括在美国与欧洲设计、建设并运营高吞吐量数据中心。与军事项目官员、技术供应商及监管机构对接。",
    "t2role": "首席技术顾问 / 项目架构师",
    "t2title": "GovTech、国防与国有项目",
    "t3desc": "领导 DNA 检测与分析、基因图谱自动化以及全面的人类遗传学研究。在乌克兰、俄罗斯和波罗的海国家发起基因检测项目。与 Harvard Medical School 和 Stanford Biomath 合作，开发被全球领先实验室采用的易于理解的基因报告。",
    "t4desc": "指导加拿大、意大利、瑞士、乌克兰及波罗的海共和国的国家级基础设施部署。监管 1,000 余名工程与部署人员，涵盖交换系统、宽带扩展及跨境互联等电信运营。实施网络冗余、正常运行时间优化和智能路由核心系统。",
    "t4role": "技术副总裁 / 区域首席技术官 — 东欧与独联体",
    "t4title": "电信项目",
    "t5desc": "创立专注于为大型商业及政府组织提供数据存储与大数据管理服务的技术公司。将公司确立为值得信赖的企业数据解决方案提供商。",
    "t5role": "创始人兼首席执行官 · 董事会",
    "t6desc": "为中小企业建立数据管理与存储公司。开发独特技术解决方案，使全球终端用户和政府机构能够更快速地追踪信息、更便捷地访问数据。",
    "t6role": "创始人兼首席执行官",
    "t7role": "创始人兼首席执行官",
    "t8desc": "在马萨诸塞州快速扩张时期，为领先全球组织提供全面 IT 战略与技术服务的领导工作，构建可扩展基础设施和全球 IT 运营。",
    "t8role": "首席执行官兼信息技术总监",
    "t9desc": "创立欧洲最大的数字收发卫星系统制造商之一。领导研究、操作系统开发、网络软件应用及整体技术战略，获得国际认可。",
    "t9role": "创始人兼首席执行官",
    "t1bdesc": "生物技术工作向新技术开发过渡的时期 — 在 Digital Invest Inc. 之前积累运营和研发经验。",
    "t1brole": "首席执行官",
    "t1byear": "2014 — 2020"
  },
  "recognition": {
    "eyebrow": "奖项",
    "title": "奖项与认可",
    "lead": "涵盖创业、精准医疗、工程和领导力的荣誉。",
    "industryEyebrow": "行业奖项",
    "industryTitle": "主要荣誉",
    "ipEyebrow": "知识产权",
    "ipTitle": "专利与出版物",
    "eduEyebrow": "教育",
    "eduTitle": "学术资格",
    "pressEyebrow": "媒体",
    "pressTitle": "媒体报道",
    "moreLink": "在 Insights 查看专利、出版物与媒体报道 →",
    "a1desc": "Entrepreneur Magazine · 2001",
    "a3title": "Who's Who in America",
    "a4title": "Who's Who in the World",
    "a5title": "Who's Who in Science & Engineering",
    "ip1year": "专利",
    "ip2year": "出版物",
    "press1role": "Digital Invest Inc. 专题报道",
    "press1title": "Healthcare Tech Outlook",
    "press2title": "Top Precision Medicine Solutions",
    "a1title": "年度企业家",
    "a2title": "美国精准医疗十大公司",
    "a2desc": "Digital Invest Inc. 入选美国精准医疗与数字健康十大最佳公司 — 2023。",
    "a3desc": "1999 — 2018 年收录 — 因在企业创建与发展方面的卓越成就。",
    "a4desc": "2000 — 2004 年收录 — 位列全球科学、工程与商业创新领袖。",
    "a5desc": "2000 — 2014 年收录 — 因对技术、卫星系统及数字基础设施的贡献。",
    "a6title": "电子工程师 — 第六类",
    "a6desc": "Nikolaev Shipbuilding Plant（93,000 名员工）最高荣誉，表彰卫星收发系统工程成就。",
    "ip1title": "数字卫星 HDTV 系统",
    "ip1role": "随后被 Sony 收购",
    "ip1desc": "数字卫星 HDTV 系统专利，后被 Sony Corporation 收购。",
    "ip2title": "技术论文",
    "ip2role": "卫星与光学系统",
    "ip2desc": "专注于卫星与光学数据传输系统的技术论文作者。研究贡献涵盖信号处理、仿真建模及应用于电信、国家基础设施和数字健康的自动化平台。",
    "ip3year": "研究",
    "ip3title": "国际合作",
    "ip3role": "美国与欧洲",
    "ip3desc": "参与国际研究合作与知识转移倡议。为多个行业开发用于数据采集、预测性诊断和云端编排的嵌入式工程系统。",
    "edu1title": "技术科学博士",
    "edu2title": "信息技术哲学博士",
    "edu3title": "硕士学位",
    "edu3desc": "电子学、数字卫星系统与经济学",
    "press1desc": "Healthcare Tech Outlook 关于 Digital Invest Inc. 和精准医疗（2023）。",
    "press1link": "阅读专题 →",
    "press2role": "行业认可",
    "press2desc": "入选顶尖精准医疗解决方案公司，彰显 Digital Invest 在推进现代医疗保健生物数学方法方面的角色。",
    "press2link": "查看榜单 →"
  },
  "contact": {
    "eyebrow": "联系",
    "title": "联系",
    "lead": "咨询角色、董事会职位和战略合作。",
    "infoTitle": "直接联系",
    "email": "电子邮件",
    "phone": "电话",
    "location": "地点",
    "locationVal": "Charlotte, North Carolina\n美国",
    "linkedin": "LinkedIn",
    "company": "现任公司",
    "companyVal": "Digital Invest Inc.\nCEO & Board Member\nAGRON Inc.\n创始人",
    "formTitle": "发送消息",
    "formLead": "填写以下表格，我会尽快回复。",
    "firstName": "名",
    "lastName": "姓",
    "emailLabel": "电子邮件地址",
    "subject": "主题",
    "message": "留言",
    "inquiryType": "咨询类型",
    "inquiryAdvisory": "顾问",
    "inquirySpeaking": "Speaking Engagement",
    "inquiryPress": "Press / Media",
    "inquiryPartnership": "Strategic Partnership",
    "inquiryOther": "Other",
    "calendlyEyebrow": "预约对话",
    "calendlyTitle": "选择方便的时间",
    "calendlyLead": "适用于董事会、顾问、演讲和战略合作伙伴方面的 qualified 咨询。",
    "calendlyPlaceholder": "预约日历将显示在此处。",
    "calendlyCta": "打开预约日历",
    "inquiryBusiness": "商业",
    "infoEyebrow": "联系信息"
  },
  "consulting": {
    "eyebrow": "顾问服务",
    "title": "咨询",
    "heroEyebrow": "战略商业指导",
    "heroTitle": "战略顾问",
    "heroLead": "三十五年在美国和欧洲创立并顾问公司——数据基础设施、政府科技、精准医疗和机器人。",
    "cta": "联系 Michael Kofman",
    "introLead": "Digital Invest Inc. 首席执行官兼董事会成员。重点：新兴技术、安全、研究与资本配置。",
    "specialtiesEyebrow": "专注领域",
    "specialtiesTitle": "Michael Kofman 的专业方向",
    "area1title": "董事会服务",
    "area1desc": "独立担任董事会成员，从事技术战略、公司治理和成长期监督工作。",
    "area2title": "CEO与创始人顾问",
    "area2desc": "企业和技术战略、组织发展、交易及适用的资本市场经验。",
    "area3title": "技术尽职调查",
    "area3desc": "基于 documented 运营经验，评估基础设施、数据平台、安全架构和应用技术。",
    "redirectLead": "战略顾问工作详见Advisory页面。专业咨询请使用Contact。",
    "redirectLink": "顾问 →"
  },
  "insights": {
    "eyebrow": "观点",
    "title": "见解",
    "heroTitle": "高管视角",
    "selectedEyebrow": "精选亮点",
    "selectedTitle": "重要认可",
    "allPressTitle": "全部媒体报道",
    "quotesEyebrow": "媒体评价",
    "quotesTitle": "行业认可与引述",
    "articlesEyebrow": "观点",
    "articlesTitle": "高管观点",
    "briefsEyebrow": "高管简报",
    "briefsTitle": "领导者之思",
    "briefsLead": "关于治理、技术、医疗和企业创建的简短实用观点。",
    "brief1title": "IPO带来的变化",
    "brief1desc": "公开市场准备所要求的运营和治理纪律。",
    "brief1tag": "资本市场",
    "brief2title": "从遗传数据到临床决策",
    "brief2desc": "如何在不超越证据或信任的前提下构建有用的健康智能。",
    "brief2tag": "精准医疗",
    "brief3title": "超越试点的AI战略",
    "brief3desc": "将实验转化为受治理的企业能力的框架。",
    "brief3tag": "人工智能",
    "readingEyebrow": "阅读清单",
    "readingTitle": "塑造战略思维的书籍",
    "r1title": "The Innovator's Dilemma",
    "r1author": "Clayton M. Christensen",
    "r2title": "Thinking, Fast and Slow",
    "r2author": "Daniel Kahneman",
    "r3title": "The Beginning of Infinity",
    "r3author": "David Deutsch",
    "r4title": "Good Strategy/Bad Strategy",
    "r4author": "Richard Rumelt",
    "r5title": "The Structure of Scientific Revolutions",
    "r5author": "Thomas S. Kuhn",
    "newsletterEyebrow": "不定期札记",
    "newsletterTitle": "高管视角，拒绝噪音",
    "newsletterLead": "关于技术、治理和持久企业创建的定期随笔和简短观察。",
    "newsletterCta": "订阅更新",
    "lead": "实质性文章和高管简报。",
    "relatedLead": "荣誉、媒体报道和专利另见专门页面。",
    "topicsLead": "主题基于在科技、医疗和基础设施领域的 documented 运营经验。"
  },
  "cta": {
    "eyebrow": "合作共赢",
    "title": "申请咨询或演讲",
    "lead": "适用于顾问合作、董事会职位、演讲邀约及战略合作伙伴关系。",
    "button": "联系我"
  },
  "speaking": {
    "eyebrow": "演讲活动",
    "title": "邀请 Michael Kofman 演讲",
    "lead": "可就高管领导力、技术战略、数字健康、数据基础设施和公司治理进行演讲。",
    "topicsEyebrow": "演讲主题",
    "topicsTitle": "专业领域",
    "topicsLead": "主题内容基于其在美国和欧洲创办并领导企业数十年的实践经验。",
    "processEyebrow": "邀请方式",
    "processTitle": "预订流程",
    "process1title": "提交咨询",
    "process1desc": "请通过联系表单或发送邮件至 mkofman@mkofman.com，提供活动详情、受众信息及期望主题。",
    "process2title": "确认范围",
    "process2desc": "确认形式（主题演讲、论坛对谈、董事会会议或高管圆桌）及相关执行安排。",
    "process3title": "交付价值",
    "process3desc": "演讲内容基于在数据存储、政务科技和精准医疗领域的真实业务成果。",
    "cta": "申请演讲邀约",
    "catalogEyebrow": "演讲主题",
    "catalogTitle": "面向重大变革的高管对话",
    "catalogLead": "根据受众、行业和决策背景定制的主旨演讲、董事会会议和领导简报。",
    "t1title": "在AI治理企业之前治理AI",
    "t1audience": "董事会、审计与风险委员会",
    "t1format": "董事会简报或主题演讲",
    "t2title": "从技术趋势到企业战略",
    "t2audience": "CEO、高管团队、投资者",
    "t2format": "主题演讲或高管工作坊",
    "t3title": "穿越市场周期构建企业",
    "t3audience": "创始人、成长型领导者、私募股权",
    "t3format": "炉边对话或主题演讲",
    "t4title": "精准医疗：承诺、证据与责任",
    "t4audience": "医疗领导者、临床医生、创新者",
    "t4format": "行业主题演讲或 panel",
    "t5title": "董事会在网络与技术风险中的角色",
    "t5audience": "董事、总法律顾问、风险领导者",
    "t5format": "董事会教育会议",
    "t6title": "将信任工程化融入数字基础设施",
    "t6audience": "技术与基础设施机构",
    "t6format": "技术-高管主题演讲",
    "t7title": "跨越边界与学科的领导",
    "t7audience": "全球领导团队和大学",
    "t7format": "主题演讲或 moderated 对话",
    "t8title": "从创始人到机构建设者",
    "t8audience": "创业者和新一代高管",
    "t8format": "工作坊或炉边对话"
  },
  "caseStudies": {
    "eyebrow": "案例研究",
    "title": "打造可规模化增长的公司",
    "lead": "精选其在数据基础设施与数字健康领域创办并领导企业的成果。",
    "cs1eyebrow": "数据基础设施 · 1996 — 2000",
    "cs1title": "9 Net Avenue Inc.",
    "cs1challenge": "挑战",
    "cs1challengeText": "在快速整合的科技市场中建立并扩展一家数据存储公司。",
    "cs1action": "策略",
    "cs1actionText": "1996 年创立 9 Net Avenue Inc.，公司迅速成长为全球最大的数据存储企业之一。",
    "cs1result": "成果",
    "cs1resultText": "2000年被Concentric Networks（NASDAQ: CNTX）收购；后成为XO Communications（NASDAQ: XOXO）的一部分。交易后继续与上市公司合作并担任董事会级别职务。",
    "cs2eyebrow": "数字健康 · 2021 — 至今",
    "cs2title": "Digital Invest Inc.",
    "cs2challenge": "挑战",
    "cs2challengeText": "通过全新的生物数学平台，结合科学、DNA 技术、AI 与 ML，革新医学中的过时方法。",
    "cs2action": "策略",
    "cs2actionText": "2021 年创立 Digital Invest Inc.，领导生物数学医学、基因组智能和临床数据平台。",
    "cs2result": "成果",
    "cs2resultText": "实现持续财务增长，使公司跻身美国精准医疗企业前十（2023）。Digital Invest 旗下包括 Human Digital Model、BioMath Life 及 Aero-Ground Robotics Operations Network 等创新项目。",
    "cs3eyebrow": "机器人与UAV · 2026 — 至今",
    "cs3title": "AGRON Inc.",
    "cs3challenge": "挑战",
    "cs3challengeText": "构建UAV和Counter-UAS能力的组织需要独立评估、结构化培训和运营架构——而非孤立平台或临时试点。",
    "cs3action": "方法",
    "cs3actionText": "于2026年创立AGRON Inc.以领导AGRON Ecosystem——涵盖咨询、评估与验证、能力开发、培训基础设施、产品开发支持、通过ISDRI的地理空间系统，以及面向游艇、 marina和私人海事基础设施的AGRON Maritime Intelligence + Security。",
    "cs3result": "成果",
    "cs3resultText": "通过AGRON、ISDRI及相关公司，涵盖咨询、能力开发、培训基础设施、地理空间系统和海事情报的互联专业服务生态系统。",
    "caseStudiesLead": "从早期阶段到被收购，持续创办、扩张并领导企业。"
  },
  "mediaKit": {
    "eyebrow": "媒体与活动",
    "title": "媒体资料包",
    "lead": "面向媒体、会议及董事会合作咨询的官方简介、视觉资料与联系方式。",
    "bioEyebrow": "传记",
    "bioTitle": "官方简介",
    "bioShortLabel": "50 词",
    "bioShort": "Michael Kofman 是 Digital Invest Inc. 的 CEO，同时担任董事会成员、顾问，并在美国和欧洲创办多家科技与数字健康企业。",
    "bioMediumLabel": "150 词",
    "bioMedium": "Michael Kofman 是 Digital Invest Inc. 的 CEO，并担任其董事会成员。作为技术远见者，他以动态方式洞察当今复杂市场不断变化的需求。作为企业家、董事会成员以及公私营企业顾问，他已在美国和欧洲成功创办多家公司。其专长覆盖高管领导力、新兴技术与市场战略分析、信息安全与隐私、科研与开发、管理及投资。",
    "bioLongLabel": "500 词",
    "bioLong": "Michael Kofman是Digital Invest Inc. CEO并担任董事会成员。他创立了9 Net Avenue Inc.，2000年被Concentric Networks收购，并领导Digital Invest从事生物数学医学和基因组智能。2026年创立AGRON Inc.，从事自主空地作业和地理空间系统。卫星和光学系统技术论文作者；数字卫星HDTV专利被Sony收购。教育：技术科学博士，信息技术博士。",
    "photosEyebrow": "摄影素材",
    "photosTitle": "授权图片",
    "photosLead": "如需高清肖像照，请发送邮件至 mkofman@mkofman.com。",
    "contactEyebrow": "媒体联系人",
    "contactTitle": "媒体咨询",
    "contactLead": "用于采访、演讲邀请及媒体合作请求。",
    "downloadEyebrow": "下载",
    "downloadTitle": "单页媒体资料包",
    "downloadLead": "包含官方简介、肖像和新闻联系人信息的PDF——可与活动组织者和记者分享。",
    "downloadCta": "下载PDF",
    "brandEyebrow": "品牌资产",
    "brandTitle": "标识与使用",
    "brandLead": "经批准的视觉资产，供编辑、会议和合作伙伴使用。请保持比例、间距和原始颜色。",
    "brandColors": "官方配色",
    "brandLogo": "主标识",
    "brandDownload": "下载品牌资产"
  },
  "articles": {
    "backLink": "← 返回 Insights",
    "article1date": "高管视角",
    "article1title": "从工程实践到全球数据基础设施",
    "article1p1": "我的职业生涯始于乌克兰尼古拉耶夫造船厂，当时负责开发用于向军舰传输机密信息的卫星收发系统。我被评为最高等级电子工程师，即在拥有 93,000 名员工的工厂中达到第 6 类工程师级别。",
    "article1p2": "1989 至 1994 年，我创立并领导了 Astra Corp，它是欧洲最大的数字卫星收发系统制造商之一。1994 至 1996 年，作为 Elitan United Inc. 的 CEO，我帮助公司从 9 人扩展到全球 4,000 余名员工。",
    "article1p3": "1996年，我创立了9 Net Avenue Inc.，一家托管与互联网基础设施公司。2000年被Concentric Networks（NASDAQ: CNTX）收购，随后成为XO Communications（NASDAQ: XOXO）的一部分。",
    "article1p4": "2001 至 2019 年，我负责政府、国防及国有企业项目的技术战略，主导了美国和欧洲在大数据、安全基础设施及高吞吐数据中心方面的大型计划。",
    "article2date": "数字健康",
    "article2title": "精准医疗与科学技术融合",
    "article2p1": "我始终坚信生命科学与前沿技术结合所蕴含的巨大潜力。在 Biotechnology Group Inc.（2008-2014）期间，我们重点推进 DNA 检测与分析、遗传画像流程自动化以及全面的人类遗传学研究。",
    "article2p2": "在我的领导下，乌克兰、俄罗斯和波罗的海国家启动了多个成功的基因检测项目。与 Harvard Medical School 和 Stanford Biomath 的合作中，我在为医生和患者开发易于理解的基因报告方面发挥了关键作用。",
    "article2p3": "Digital Invest Inc. 创立于 2021 年，从事生物数学医学 — 将科学、DNA 技术、AI 和 ML 应用于临床智能。Healthcare Tech Outlook（2023）。",
    "article2p4": "Digital Invest 旗下包括 Human Digital Model、BioMath Life 与 Aero-Ground Robotics Operations Network 等创新项目，持续推动数据科学与生命科学的深度融合。"
  },
  "privacy": {
    "eyebrow": "法律信息",
    "title": "隐私政策",
    "lead": "说明 mkofman.com 在您访问网站或发送消息时如何处理信息。",
    "updated": "更新：2026年7月",
    "s1title": "我们收集的信息",
    "s1text": "提交表单时，我们接收您填写的字段。若启用分析，可能收集匿名使用数据。",
    "s2title": "信息用途",
    "s2text": "用于回复咨询并改进网站。我们不出售个人数据。",
    "s3title": "第三方服务",
    "s3text": "表单可能由 Formspree 处理。分析可使用 Plausible 或 Google Analytics（如已配置）。",
    "s4title": "您的权利",
    "s4text": "访问、更正或删除数据请联系 mkofman@mkofman.com。",
    "s5title": "联系",
    "s5text": "政策相关问题：mkofman@mkofman.com"
  },
  "board": {
    "eyebrow": "顾问",
    "title": "顾问",
    "body": "欢迎与科技、医疗和基础设施机构进行战略顾问对话——基于企业创建、技术战略和成长期执行的一手运营经验。",
    "contactLink": "顾问咨询",
    "lead": "Board & Advisory"
  },
  "thesis": {
    "eyebrow": "领导力论题",
    "title": "为长期建设。在当下决策。",
    "lead": "技术变化迅速；领导力的义务不变。持久企业将雄心与纪律、证据和问责相结合。",
    "believeEyebrow": "我的信念",
    "believeTitle": "持久组织的七项原则",
    "b1title": "战略必须产生选择",
    "b1text": "战略不是愿望清单。它定义在哪里竞争、构建哪些能力、不 pursue 什么以及如何衡量成功。",
    "b2title": "技术是治理问题",
    "b2text": "董事会必须理解技术如何创造价值、集中风险并改变问责。将每个技术问题外包本身就是决策。",
    "b3title": "证据应胜过热情",
    "b3text": "信念重要，但市场、系统和科学必须被检验。领导者创建机制，在客户或监管者之前暴露假设。",
    "b4title": "架构塑造企业",
    "b4text": "技术架构决定速度、韧性、安全和未来选项。捷径在其原始背景消失很久后仍会成为制度约束。",
    "b5title": "信任是运营基础设施",
    "b5text": "信任通过明确承诺、可靠执行、负责任的数据实践以及在条件变化时的直接沟通来建立。",
    "b6title": "资本必须跟随能力",
    "b6text": "增长投资应强化差异化能力和可衡量需求，而非用支出替代产品-市场理解。",
    "b7title": "领导者设计继任者",
    "b7text": "最强的领导者构建超越自身参与的系统、人才和决策质量。",
    "rejectEyebrow": "我拒绝的",
    "rejectTitle": "三种昂贵的幻觉",
    "r1title": "创新表演",
    "r1text": "公告、试点和时髦语言不等于能力。创新必须改善重要的结果。",
    "r2title": "无治理的增长",
    "r2text": "规模放大未解决的弱点。控制、文化和问责应在复杂性使纠正代价高昂之前成熟。",
    "r3title": "虚假确定性",
    "r3text": "高管信心不应消除不确定性。强有力的决策使假设可见，并在事实变化时保留选项。",
    "horizonEyebrow": "地平线",
    "horizonTitle": "下一个优势是 responsible integration",
    "horizonText": "决定性机遇不是任何单一技术，而是将AI、先进数据系统、生物学和自动化 disciplined 融入人们可信赖的机构。"
  },
  "press": {
    "eyebrow": "媒体",
    "title": "精选报道",
    "lead": "关于技术、创业和精准医疗的第三方认可与报道简明档案。",
    "archiveEyebrow": "档案",
    "y2023type": "行业认可",
    "y2023title": "Top 10 Precision Medicine Companies",
    "y2023desc": "Healthcare Tech Outlook将Digital Invest Inc.列为推进精准医疗和数字健康的美国领先企业之一。",
    "y2023link": "查看专题",
    "y2001type": "高管奖项",
    "y2001title": "年度企业家",
    "y2001desc": "Entrepreneur Magazine 认可。",
    "y2001link": "查看档案",
    "y1999type": "传记认可",
    "y1999title": "Who's Who in America",
    "y1999desc": "自1999年起获得认可，随后列入Who's Who in the World和Who's Who in Science and Engineering。",
    "clipEyebrow": "档案精选",
    "clipMeta": "Industry Feature · DataPeer Inc.",
    "clipTitle": "State of the Storage Industry",
    "clipLead": "对Michael Kofman作为DataPeer Inc.创始人、董事长兼CEO的早期采访——谈及光纤、卫星传输、SAN和新兴存储市场。",
    "clipBody": "该专题提到2001年获Entrepreneur Magazine年度企业家称号，并讨论DataPeer在关键任务存储、iSCSI和业务连续性方面的方法。",
    "clipOpen": "打开完整扫描 →",
    "y2000type": "采访",
    "y2000title": "State of the Storage Industry",
    "y2000desc": "作为DataPeer Inc.创始人、董事长兼CEO的专题采访，谈及存储网络、iSCSI和业务连续性。"
  },
  "ip": {
    "eyebrow": "知识产权",
    "title": "应用思想，有据可查",
    "lead": "精选专利、出版物和研究项目，将工程严谨性与实际的商业和社会成果相连接。",
    "patentEyebrow": "专利",
    "patentTitle": "受保护的发明",
    "patentIntro": "专利工作反映了对改善信息收集、传输、保护和解读的系统的持续关注。",
    "publicationsEyebrow": "出版物",
    "publicationsTitle": "技术与高管写作",
    "publicationsIntro": "已发表作品将复杂技术主题转化为对从业者和领导者有用的方法、框架和决策。",
    "researchEyebrow": "研究",
    "researchTitle": "跨学科项目",
    "researchIntro": "研究计划涵盖安全通信、预测分析、基因解读、人类数字建模和自主系统。"
  },
  "testimonials": {
    "t1quote": "Michael兼具工程师的精确与资深CEO的判断力。他提出改善决策的问题。",
    "t1name": "董事会同事",
    "t1role": "上市科技公司",
    "t2quote": "他将科学、产品、治理和商业现实联系起来的能力，为复杂计划带来难得的清晰。",
    "t2name": "战略合作伙伴",
    "t2role": "数字健康领域",
    "t3quote": "Michael直接、深思熟虑，专注于持久价值。他帮助领导团队同时看到机遇与责任。",
    "t3name": "高管合作者",
    "t3role": "全球基础设施"
  },
  "deck": {
    "title": "Michael Kofman",
    "subtitle": "技术高管 · 创始人 · 董事会顾问",
    "thesis": "技术、商业与投资 — 基础设施、生命科学和自主系统。",
    "contact": "保密讨论：通过 mkofman.com 联系 Michael Kofman"
  },
  "briefIpo": {
    "title": "IPO带来的变化",
    "desc": "公开市场不仅改变资本结构，还改变运营契约。",
    "p1": "IPO常被描述为融资事件。实际上是制度转型。预测、控制、披露、治理和高管沟通必须在上市前可重复，而非事后即兴。",
    "p2": "准备始于决策质量。管理层需要可靠指标、明确所有权和能解释绩效与偏差的运营节奏。无法调和内部叙事的公司将难以传达可信的外部叙事。",
    "p3": "董事会角色也改变。董事须平衡增长与监督，理解重大技术和市场风险，并确保激励支持持久价值而非单一季度。",
    "p4": "最强的上市公司在增加制度纪律的同时保持创业速度。目标不是官僚主义，而是在更高问责水平上的可信执行。",
    "eyebrow": "高管简报"
  },
  "briefGenetic": {
    "title": "从遗传数据到临床决策",
    "desc": "基因组信息的价值取决于解读、证据和负责任地融入临床护理。",
    "p1": "遗传数据 abundant，临床有用的含义 scarce。结果只有在上下文中解读、与已验证证据关联并以支持真实决策的形式呈现时才有价值。",
    "p2": "这种转化需要分子生物学、医学、统计学、软件工程和患者沟通之间的协作。任何一层的薄弱都可能将技术 sophistication 变成临床 confusion。",
    "p3": "隐私和同意是架构要求，而非法律脚注。系统必须限制不必要的暴露，使数据来源可见，并在信息在实验室、平台和护理团队之间流动时 preserve 患者自主权。",
    "p4": "精准医疗将通过有节制的整合推进：更好的证据、透明模型、互操作工作流以及临床医生和患者可评估的结果。信任是产品的一部分。",
    "eyebrow": "高管简报"
  },
  "briefAi": {
    "title": "超越试点的AI战略",
    "desc": "企业AI在所有权、数据、工作流和治理共同成熟时才能创造价值。",
    "p1": "许多AI计划始于令人信服的演示，却在投产前停滞。缺失的很少只是模型本身。可持续价值需要明确的业务成果、负责人、可靠的数据以及人们真正会使用的工作流。",
    "p2": "领导者应区分自动化、预测和决策支持。各自对准确性、可解释性、人工审查和风险有不同要求。单一治理模板无法适用于所有用例。",
    "p3": "衡量标准必须超越技术性能。采用率、周期时间、错误率、客户影响、安全暴露和监督成本决定AI能力是否在经济和制度上站得住脚。",
    "p4": "制胜方法是管理型组合：扩展已验证的用例，及早停止弱项，并为高后果决策设定明确边界。AI战略本质上是运营战略。",
    "eyebrow": "高管简报"
  }
};
